### ISSUE TITLE
Determine and calculate Maximums

### ISSUE THREAD

**Issue by abschwenker** [bcgov/SIMS#1005]
**Calculating maximums**
 - Program Year (PY) maximums (all)
   - PY Maximums are specific to the Program Year of that application.  In other words, PY maximums must be associated with each program year.  
   - Impact of PY Maxiums on an award will be **_calculated at the time of E-CERT generation_**.  Maximums are _**calculated AFTER**_ restrictions are applied and overawards are deducted. The remaining award amount will then be subject to **_lifetime maximums being applied first and then PY maximums_** to follow.  
   - Need to display message to student in NOA and Summary if they are PREDICTED to hit a maximum as a result of the awards in the application.  For the prediction, DO NOT need to factor in overaward deductions and restrictions. 

 - Lifetime maximums
   - Lifetime maximums are universally applicable regardless of Program Year.
   - CSL/CSG Lifetime Maximums.  
      - Federal Government is in charge of tracking a student against their CSL/CSG lifetime maximums and they will notify us when to apply a restriction or not.
      - If restriction is in place, do not disburse any CSL/CSG.  In other words, we do not actually perform any calculation to reduce an award at time of ECERT generation. 
   - BCSL Lifetime Maximums.
    - Impact of BCSL Lifetime Maxiums on an award will be **_calculated at the time of E-CERT generation_**.  Maximums are _**calculated AFTER**_ restrictions are applied and overawards are deducted. The remaining award amount will then be subject to **_lifetime maximums being applied first and then PY maximums_** to follow.  
    - Add restriction to student when they hit BCSL amount
    - If restriction is in place, do not disburse any BCSL.  In other words, we do not actually perform any calculation to reduce an award at time of ECERT generation. 

**Student UI**
- At the time of NOA generation, we need to determine if there is potential that an PY Maximum will be hit and if so, warn the student in the NOA and summary page which award types may be impacted by maximums.  But we will not be displaying what those maximum limits are.  We will provide link to material on PY maximums.
- Since Lifetime Maximums are handled as restrictions, we can let the student know with certainty in their NOA and summary page that they WILL be impacted by maximums.  Again, we will not be displaying what those maximum limits are; just a link to the info.
- Special case: For CSL/CSG, federal government gives us a restriction code when they are in close proximity to reaching the maximum.  This is the only funding type that we warn the student they are close to hitting a maximum.

~~**Ministry UI**~~
 - Ministry requires a page or modal they can access when reviewing a student's application that will display the PY maximums associated with the Program Year of the application they are viewing.   We will include the lifetime maximum values as well in this display. 
 - Things NOT REQUIRED for MVP
    - We do not need to display the student's aggregate PY nor lifetime awards received. 
    - Once maximums are set for the program year, it is unlikely to change, so it would be acceptable for a developer to set it directly in the database and don't need to have a Ministry interface to enter/modify the maximum values at this time. 
 - Ministry staff will need to be able to see the CSL/CSG lifetime maximum restrictions somewhere in the student's profile. 

**Integration/File Load**
 - We need to read the file from the ESDC that contains lifetime maximum restriction information for a student and add/modify the restriction for the student. 
    - Federal Restriction List Load” in SFAS, also known as “federal_restricted_file.dat . **_Need to ask Harry where to find this file/data._**
 - There are two restrictions we will receive from ESDC.
    - First, we will receive a "restriction" that the student is "in close proximity" to the lifetime maximum.  This "restriction" has no impact on the ECERT generation.
    - The second restriction we'll receive is that a student has actually reach/exceeded the lifetime maximum.  This restriction will stop any further disbursements of CSL/CSG.

Additional context:
- References for PY Maximums
    - Loan and Grant maximums: https://studentaidbc.ca/sites/all/files/school-officials/allowances.pdf 
    - Lifetime and weekly limits: https://studentaidbc.ca/help-centre/applying-loans/maximum-funding-limits
    - Grants and Scholarships with allowances: https://studentaidbc.ca/explore/grants-scholarships
- Additional analysis found general - analysis -> Over awards and Maximums
- Lifetime Maximums for BC student Loans is $50,000 (regardless of program length)
- Lifetime max for Canada Student Loan & Canada Student Grant combined is 340 weeks of study  (this includes our SABC funded weeks as well as any unfunded weeks where student was in interest-free status) and $71,400. 
- A student can be disbursed an award that EXCEEDS the CSL/CSG lifetime maximum of $71,400, but just the one time.  After this is disbursed and the feds are updated, they will notify us of the restriction that the student has hit their lifetime maximum and only then, will we apply the restriction on any future ECERT generations.

**Acceptance Criteria**
- [ ] PY maximums are associated with each program year and persisted in the database.
- [ ] Lifetime maximums are persisted in the database.
- [ ] Determine and calculate PY maximums at time of ECERT generation.
- [ ] Program Year maximums apply to the following (add in DMN lookup or something similar in the assessment? plus a load previous data worker?)
    - CSL
    - CSG
      - CSGP
      - CSGD
      - CSGF
      - CSGT
    - BCSL
    - BCAG
    - BCAG
    - BGPD
    - SBSD
 - [ ]Check for lifetime maximum restrictions at time of ECERT generation.
 - [ ]**_Lifetime maximums apply to the following (add in DMN lookup or something similar in the assessment? plus a load previous data worker?)_**
    - CSL/CSG
    - BCSL  
- [ ] Ministry Portal UI for PY Maximums.
- [ ] Display message for CSL/CSG maximum restrictions to student in NOA and summary when nearing maximum and maximum reached.
- [ ] **_Display message for BCSL maximum restricitions to student in NOA and summary when maximum is reached_**
- [ ] Implement a validation to predict if the estimated award will cause an PY maximum will be reached by a disbursement.  It is understood that this will be an unreliable predication. 
- [ ] Display message warning that awards MAY be impacted by PY maximums to student in NOA and summary.
- [ ] Display CSL/CSG restriction status to Ministry Staff.

**Comment by JasonCTang** [comment]
This work was completed under the ticket #1761 and #1813
