### ISSUE TITLE
Remaining student change requests

### ISSUE THREAD

**Issue by abschwenker** [bcgov/SIMS#1006]
@hugh @josh. This looks like a old laundry list of questions.  Is there anything in here that we need to uplift into a new ticket? Has some of this been taken care of? Can we pair this down a bit?

- [ ] Get complete list of appeals/requests.
- [ ] What information does student need to provide.
- [ ] What needs to be overrided in the workflow calculation.  
- [ ] When a reassessment occurs after an appeal, we need to be able to carry the appeal ID to the new reassessment.
- [ ] Currently, additional appeals will overwrite any existing appeal.  How do we plan to handle this? Is there a requirement to maintain appeal history?
- [ ] Are students allowed to submit multiple appeals for an application?  **YES**
- [ ] Multiple requests for change need to be aggregated per application.  
- [ ] Multiple requrests for change of the same field, newer requests overwrites older ones. 

Acceptance Criteria
- [ ] Add remaining areas that a student can request a change on
- [ ] Change assessment to use new values from changed numbers

- How many do we need for MVP?  All of them.

**Comment by CarlyCotton** [comment]
Addressed on other tickets
