### ISSUE TITLE
Parent Partner Content Updates

### ISSUE THREAD

**Issue by TeresaBia** [bcgov/SIMS#1017]
Tasks
- [ ] Polish UI design (for content designer)
- [ ] Revisit the words and where the fields are organization
- [ ] Revisit login page text
- [ ] Revisit home page text
- [ ] Polish parent partner form
- [ ] Additional context: mobile friendly, accessibility considerations

https://dev-aest-sims.apps.silver.devops.gov.bc.ca/supporting-users

Assumptions:
Partner / parent may fill the form on mobile or tablet (as opposed to desktop)

**Comment by abschwenker** [comment]
duplicate, see #960
