### ISSUE TITLE
Student Confirms Profile information

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#105]
**As a** *(Student)* **I want** *(confirm my profile information)* **So That** *(so that I can verify that my address is current on my application)*

**Additional Context**
- The Profile information is the source of Truth on the Student Profile- not the application
- 
**Acceptance Criteria**
- [ ] Given (A Student), When (A student initiates an application), Then they are confirming that Read-Only view of both BC Services Card and SABC Profile Information is correct.
- [ ] Given (A student), When (cannot confirm the Profile Information), Then (they will be redirected to the Student Profile Section).
- [ ] Given (A student), When (they confirm their profile info is correct), Then (they select 'Yes), 
- [ ] Given (A student), When (they confirm their profile info is incorrect), Then (they select 'No, I need to update my profile information')
- [ ] Given (A student), When (they are viewing the profile information ), Then (it is NOT displayed as editable (its greyed out) for both Services Card and SABC Profile Information

**Technical Tasks**
- [ ] Display the entire student profile as a read-only. Probably creating a component to hold this. - Sandeep
- [ ] Starting saving to DB the fields that are not being saved right now (e.g. DOB and Gender) - Andrew Signori
- [ ] Update the new fields on DB during user synchronization after the login. - Andrew Signori
- [ ] Expose in the API an endpoint to retrieve all the student data needed to populate all the fields. - Sandeep

**Comment by andrewsignori-aot** [comment]
![image.png](https://images.zenhubusercontent.com/5fcebe3c076e6aaed83693fb/e6674180-981a-4265-8ff5-0bbd01dd4fc9)
