### ISSUE TITLE
UI Updates to manage users

### ISSUE THREAD

**Issue by TeresaBia** [bcgov/SIMS#1059]
**- Additional Context**
- This feature is required for the Business BCeID alternate solution
- Institution user modal is being componentized 
- This will be used for Institution and Ministry users
- Functionality remains the same as before:
_If Business BCeID user, legal operating name is grabbed by BCeID and user name is selected from dropdown menu 
If Basic BCeID user, legal operating name and user name are manually entered in free text fields_
- Institution Edit user modal (applying disabled field to BCeID user ID name field) is a future enhancement not part of this ticket 

**- Acceptance Criteria**
- Update manage user page to new figma layout
- Update add user modal to new figma layout
Note: Only Institution Admin can be Legal Signing Authority 
-[ ] Only display Assign user to locations radio buttons if Admin not true
-[ ] Remove primary contact and admin roles for Admin User (old mockup)
- Remove location-manager and primary contact from the user role table in DB (no longer required)

Old mockup: ![old.JPG](https://images.zenhubusercontent.com/61c390f5d34132a9b12ca101/dc3a002e-b779-4881-a57d-6bac8cbafd1e)

**Comment by hellolynn-tbtb** [comment]
In case an "edit" view is needed as well. [Mockup here.](https://www.figma.com/file/9Om2tzLAVEoMQrjmrH4fhu/MOD-SIMS?node-id=5651%3A114639)

**Comment by abschwenker** [comment]
Added to #1018
