### ISSUE TITLE
UX Accessibility for Programs & Offerings

### ISSUE THREAD

**Issue by hellolynn-dsib** [bcgov/SIMS#1070]
### Additional Context

- Use #1076 accessibility guideline for form template

### Acceptance Criteria

- Mockup the following pages:
- [ ] Program summary
- [ ] Program detail
- [ ] Create program page
- [ ] Add study period offering

- Keep in mind these pages are used for ministry user (read-only)
- [ ] Ensure headers match design system and patterns 
- [ ] Ensure colours used match design system and patterns
- [ ] Ensure no issues on page was flagged during accessibility audit

**Comment by IrenaMilosevic1** [comment]
Approved
