### ISSUE TITLE
Ministry User Complete Institution Scholastic Standing

### ISSUE THREAD

**Issue by abschwenker** [bcgov/SIMS#1079]
**Acceptance Criteria**
From the Ministry view Student application "Assessments" page (#770)
- When clicking "View" from the "Request Form" column in the "Requests" table with the type "Scholastic Standing" 
- [ ] The user is navigated to the request that was submitted by the institution
- [ ] Display 2 buttons, Approve for reassessment?  or Decline reassessment
- [ ] On click display approve/decline modal with a note
- [ ] Note (Required) -These will be displayed back on a completed request and fall under an "assessments" note label
- [ ] Submit the changed items with values to camunda for reassessment and sims.assessments

**Comment by TeresaBia** [comment]
No longer required as scholastic standings are automatically accepted.
