### ISSUE TITLE
Resolve missing fieldset on forms

### ISSUE THREAD

**Issue by abschwenker** [bcgov/SIMS#1082]
**Additional Context**
- Issue primary occurs on radio buttons and checkbox's
- How to test: Use https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh
- Formio accessiblity: https://help.form.io/developers/accessibility
- Other references: https://www.w3.org/WAI/tutorials/forms/grouping/

**Acceptance Criteria**
- [ ] Determine how to resolve missing fieldset accessilibty alert (Implementing the fix on each page will be part of subsequent tickets)
- [ ] Determine how to resolve form label (could be related to fieldset) accessilibty alert (Implementing the fix on each page will be part of subsequent tickets)

**Tech Notes**
Possibly import of uswds may resolve???
- <body>
-        <div id="formio"></div>
-        <script type="text/javascript">
-            Formio.use(uswds);
-            Formio.use(vpat);
-            Formio.createForm(document.getElementById('formio'), 'https://examples.form.io/example');
-        </script>

**Comment by ann-aot** [comment]
Findings
1. uswds 
tried uswds package in create education form and it was breaking the styles, screenshots added
![image.png](https://images.zenhubusercontent.com/608872f7d0d25cdfe8dab75d/20a240da-3e95-4211-a481-aaa8277bc966)
![image.png](https://images.zenhubusercontent.com/608872f7d0d25cdfe8dab75d/ba289a98-fb25-4963-9660-f43979d37353)

2. role and aria-labellledby is internally added by the formio to the child div and i tried to added it to the parent div, its was not having any effect.

3. field set tag along with legend tag resolved the issue, but adding legend tag also has some styles issue like,
  a. font size is large
  b. required '*' is showing for all radio/checkbox inputs
(screenshots added)
![image.png](https://images.zenhubusercontent.com/608872f7d0d25cdfe8dab75d/281671e5-9778-46ff-b78a-228a3237df27)

4. missing label -> for some fields, we are hiding the label, screenshot added
![image.png](https://images.zenhubusercontent.com/608872f7d0d25cdfe8dab75d/cfd58b4d-695a-4386-a877-26ae985786ca)

5.Orphed form label -> formio is internally adding all input label `for` (i.e. id of the input), in a group or radio or checkbox case the individual input and label are tagged with for in formio, but the original title or the field is translated as a title internally by formio with a `for` and the id of the for is not present
![image.png](https://images.zenhubusercontent.com/608872f7d0d25cdfe8dab75d/dd3f3ef9-9add-4cbd-8198-53935dde04c2)

**Comment by abschwenker** [comment]
reviewed with Lynn and GDX. Confirmed via manual testing that the field set and label issues are false positives and screen reader working as intended. Have flagged for extra testing during next review in summer. No action needed at this time.
