### ISSUE TITLE
Accessibility UI clean-up for Parent / Partner

### ISSUE THREAD

**Issue by TeresaBia** [bcgov/SIMS#1114]
**Additional Context:**
Related UX ticket [#1076](https://app.zenhub.com/workspaces/student-information-management-system-5fce9df5aa1b45000e937014/issues/bcgov/sims/1076)

Related UX ticket (Parent Partner): [#873](https://app.zenhub.com/workspaces/student-information-management-system-5fce9df5aa1b45000e937014/issues/bcgov/sims/873)

**Acceptance Criteria:**
- [ ] Ensure student account (and all pages) match figma and accessibility checks pass

**Comment by abschwenker** [comment]
duplicate of #1110
