### ISSUE TITLE
Review API class validators

### ISSUE THREAD

**Issue by andrewsignori-aot** [bcgov/SIMS#1117]
- [ ] Convert all input DTO to classes
- [ ] Ensure that all input DTO properties have a decorator (@IsOptional, @IsRequired, AND OTHERS).

Some decorators already used in the API
@IsPositive()
@IsNotEmpty()
@IsArray()
@ArrayMinSize(1)
@ValidateNested({ each: true })
@Type(() => DisbursementValueDTO)
@IsEnum(...)
@IsObject()
More: https://docs.nestjs.com/techniques/validation

**Comment by abschwenker** [comment]
Completed as part of the other reorganize API ticker
