### ISSUE TITLE
Upgrade Typeorm

### ISSUE THREAD

**Issue by andrewsignori-aot** [bcgov/SIMS#1134]
**Acceptance Criteria**
- [x] Upgrade Typeorm to the latest version.

**Additional Context**
- at least Version 0.30 (https://github.com/typeorm/typeorm/releases/tag/0.3.0) (0.3.6 stable version - https://www.npmjs.com/package/typeorm) introduced new nice features and some breaching changes that will require some refactoring. Some of the new features allow us to create queries using less strings, building the queries in a more type-safe way, like the below one:
![image.png](https://images.zenhubusercontent.com/5fcebe3c076e6aaed83693fb/b426d8f1-0f7b-4022-b4a2-3132bf6c1d0a)

The upgraded version for nestjs typeorm is now available on version 8.1.0 and it supports typeorm 0.3.0.
https://github.com/nestjs/typeorm/releases/tag/8.1.0

**Comment by abschwenker** [comment]
block until nestjs/typeorm version 9 release

**Comment by guru-aot** [comment]
https://www.npmjs.com/package/@nestjs/typeorm/v/9.0.0-next.2
