### ISSUE TITLE
UX / UI  Notifications and Communications Approach for MVP

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#115]
**Describe the task**
Define the MVP approach for notifications and communications for Students.
When does a student get a toast, when.... an email, when a ...? and where are they located in a centralized place?

**Acceptance Criteria**
- [x] Validate previous notification lists to ensure they are still valid
- [x] Document types of notifications for MVP
- [x] Document functions of notifications for MVP
- [x] Determine Notification Settings (Communication Preferences)- Email is MVP text is a MAYBE (depending on tech feasibility (lower priority)
- [x] Determine When does a student get a toast, when.... an email, when they receive (insert types)
- [x] Determine where a student can see a centralized view of Notifications.

------
- [x] Definitions of status' so they know what they mean aka = In Progress means "Your Assessment is now in Progress"

**Additional context**
The previous list resides in the confluence

**Comment by courtneygringras** [comment]
Test - checking access
