### ISSUE TITLE
Review Offering ID Validations

### ISSUE THREAD

**Issue by andrewsignori-aot** [bcgov/SIMS#1154]
The solution has two moments where the offering ID can be set

1. During the Student Application submission when the workflow detects that an offering id was provided and sets it on the sims.student_assessments table;
2. During the PIR process when the Institution provides the offering id to be set into sims.student_assessments table.

Backend exclusive (validated during PIR and workflow offering setting)
1 - Program year;
2 - Offering intensity;
3 - Offering location;

Backend/frontend with a nice user message (validated during application submission and PIR)
- Dates overlap;

**Comment by abschwenker** [comment]
completed in #1345
