### ISSUE TITLE
Student Provides Personal Information- Citizenship. Yes CDN

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#126]
**As a** *(Student)* **I want** *(to provide my citizenship information)* **So That** *(I can accurately be assessed for Financial Aid).

**Additional Context**
- Student is required to answer a question to determine Citizenship by selecting one of the following: Canadian Citizen, Protected Person, Permanent Resident 
-The default answer will be blank, the field is mandatory on 'Submit' (Another User Story)
- All of the Personal Information is listed on One Page
- Static information for now as a list of values to select from
- Students don't have an option of selecting a "blank' option

**Acceptance Criteria**
- [x] Given (A student), When (providing their Citizenship), Then (they can select from the following: Canadian Citizen, Protected Person, Permanent Resident )

**Technical Task List**
- [ ] Create Reusable Radio button component with N-options + question + additional info as input
- [ ] Integrate Reusable component with FA application form

**Comment by roopfw** [comment]
![image.png](https://images.zenhubusercontent.com/5e66ca845237f60c730a4aa3/270f422d-b96b-4bd0-9f1e-22f8e33d1b17)
