### ISSUE TITLE
Create indexed full name DB search

### ISSUE THREAD

**Issue by andrewsignori-aot** [bcgov/SIMS#1280]
**Acceptance Criteria**
- [ ] Create the below index's
- [ ] Change the search (select) to use the index

Previous Notes
- Allow the search by full name in an indexed way to avoid a full table scan.
- Check for possibility to do full name using like/ilike operator (Search for John Doe using John D)
- Prepare expression to use case insensitive search (Search for John Doe using john doe)
- Test it including mononymous names
- One suggestion is to create an indexed expression, as shown below (we created one already to deal with `lower(name)`);
```sql
CREATE INDEX users_full_name ON sims.users ((first_name || ' ' || last_name));
```
and change the query to use the same expression, like below:
```sql
SELECT * FROM sims.users WHERE (first_name || ' ' || last_name) = 'John Smith';
```
References
- Source: https://www.postgresql.org/docs/current/indexes-expressional.html

Another alternative would be to create a "calculated" column that would have the result of the concatenation: https://www.postgresql.org/docs/current/ddl-generated-columns.html

**Comment by sh16011993** [comment]
Some Useful Links related to GIN Index (used for operators LIKE and ILIKE):

https://pganalyze.com/blog/gin-index

https://www.cybertec-postgresql.com/en/postgresql-more-performance-for-like-and-ilike-statements/

https://www.postgresql.org/docs/9.4/textsearch-indexes.html

https://niallburkley.com/blog/index-columns-for-like-in-postgres/

https://stackoverflow.com/questions/1566717/postgresql-like-query-performance-variations

https://stackoverflow.com/questions/28975517/difference-between-gist-and-gin-index/28976555#28976555

https://dba.stackexchange.com/questions/4521/how-to-create-an-index-to-speed-up-an-aggregate-like-query-on-an-expression

https://www.dbrnd.com/2016/08/postgresql-example-of-trigram-index-for-full-text-search-using-pg_trgm-extension/
