### ISSUE TITLE
Institution Edits Offering

### ISSUE THREAD

**Issue by abschwenker** [bcgov/SIMS#1281]
**Additional Context**
- After students are linked (applied) for a specific offering, changes to that offering can affect a student's funding. This ticket is to implement the rules provided. 
- Non-editable fields mean that a new program will need to be created or requested to change
- This ticket includes the migrations for this feature

**Acceptance Criteria**
- While NO students are linked (applied) to a specific offering allow the following to be edited 
- [x] All fields, this may cause an offering to become pending
- While students are linked (applied) to a specific offering allow the following offering details to be edited:
- [x] Name
- [x] ALL other fields are not editable (unless you are requesting to change)
- [x] Display "edit actions" button
- [x] Display "request to change" button in dropdown of "edit actions"
- [x] on click of "request to change" display editable form with banner (see figma)
- [x] On click of submit save the offering to the db (do not relink students)
- [x] Mark Current offering to not be selected by students
- Change status to: Under review
- [x] Mark Future offering to not be selected by students
- Change status to: Awaiting approval
- [x] Offerings in Awaiting approval or Under review are not editable

Student Application
- [x] Ensure students can not select offerings with status (Under review, Awaiting approval)

**Comment by dheepak-aot** [comment]
Definition of Offering linked to a student application.
When an offering is validated to check if it has any application linked to it, we check the student_assessments table to see if the given offering is present in student_assessments table at all. 
What it means is, if there was at least one assessment started with (creation of workflow instance) given offering for any student application in the present or past, then it is considered to be linked to a student application. And in such case institution user will not be able to update any of offering fields except offering name and they need to request for change to update the offering further.
