### ISSUE TITLE
Determine and calculate Overawards

### ISSUE THREAD

**Issue by abschwenker** [bcgov/SIMS#1346]
Additional Context
- Further analysis docs are located in the analysis folder.
- This ticket is the fundamental changes for overawards, remaining UI-related tickets will be done in #1355.
- Overawards are generated only for loans.
- Overawards are generated when the student received more money than he is supposed to receive.
- Grants are not paid twice but they do not generate overawards in case more money than the student is entitled was already paid.
- All possible deductions for loans and grants are always per award code in the same way that the overaward balance is also per award code.
- When the e-Cert is generated the money is considered disbursed/paid/sent.

**Acceptance Criteria**

**Overawards generation (loans only)**

- [x] Once a reassessment happens on an application that already had money disbursed (paid), the amount already paid must be subtracted from the new assessment generated. For instance, if the student already received $2000 for CSLF and a reassessment happens where the new values indicate that the student is entitled to receive only $1500 the CSLF will have its value defined as 0 (zero) and an overaward of $500 will be added to the student account.
- [x] While calculating the total amount already paid to the student, the "overaward amount" (subtracted during e-Cert generation) is added to the "effective amount" because it should be considered part of what the student received. The "overaward amount subtracted' is money that the student is being paid but before e-Cert generation, it is used to deduct student debt, and the deduction is made with "student money".
- [x] The deductions must happen as much as possible from the sooner disbursement. For instance, if the student already received $2000 and there will be two disbursement schedules for CSLF where schedule 1 is defined as $1500 and schedule 2 is defined as $1500 the disbursements will look as below (no overawards generated for this case but it servers to illustrate how the deduction happen).
    - Disbursement Schedule 1: Award = $1500 | Deduction $1500 = 0 (**ducuted as much as possible from the first schedule**)
    - Disbursement Schedule 2: Award = $1500 | Deduction $500 = $1000

**Grants reassessments**

- [x] Grants already paid should not be paid again but if the value already paid is greater than the amount that the student is entitled to after the reassessment no overaward is generated. For instance, assuming that the student already received $2000 for CSPT and after the reassessment, the new CSPT was defined as $1500. In this situation, the student will not receive any money in the new assessment for CSPT but the $500 extra already received will not generate an overaward.

**Overall criteria**

- [x] The overawards are calculated during the execution of the `save-disbursement-schedules` worker when the disbursement schedules are created.
- [x] The overaward balance is only applied (deducted) upon e-Cert generation.
- [x] The award effective value is only calculated during the e-Cert generation.
- [x] If the student has a restriction with the action type `Stop full time BC funding` this will force the effective values for "BC Loans" and "BC Grants" to be 0(zero) and no overawards deductions will happen because the student will not be receiving any money.
- [x] "BC Total Grant" (BCSG) will be calculated during e-Cert generation.
- [x] "Canada Loans" should not generate overawards if the amount is less or equal to CAD$250.00.
- [x] A reassessment only produces an overaward if the application had some money sent(disbursed) already. Applications that have all their disbursements in a 'Pending' state will be freely recalculated but will never generate an overaward.
- [x] The effective value for every award considering amounts already paid, overawards and possible restrictions are calculated altogether during the e-Cert generation in one single transaction. An error during the DB operations or during the e-Cert file upload to to SFTP will cause the DB transaction rollback.

**DB Migrations**

- [x] Create a new OA table (sims.disbursement_overawards).
- [x] Add status for disbursement schedules to Cancel Non-Sent Disbursements (Pending, Sent, Cancelled)
    - `Pending`: status for every created disbursement schedule record;
    - `Sent`: updated upon e-Cert generation when the awards are considered "paid";
    - `Cancelled`: if a record was on a Pending status and the application was reassessed or if the application was cancelled.
-  [x] Add new columns to the `sims.disbursement_values` to store the overaward-related values.
    - `disbursed_amount_subtracted`: for a reassessment, when a disbursement was already sent (paid), this column will store the amount that will be subtracted from an award during the e-Cert generation. For instance, if during the first assessment, the student received $5000 and during the reassessment, this value was $6000, the student in this column will store the value of the $5000 that was already paid, which will result in the student receiving only $1000.
    - `overaward_amount_subtracted`: during the e-Cert generation, if the student has any overaward balance this column stores the amount of the overaward that will be deducted from this award. For instance, if the student is entitled to receive CSLF $5000 but has an overaward balance for the CSLF of $2000, the student will receive only $3000.
    - `effective_amount`: Value resulted from the calculation between the award value_amount, disbursed_amount_subtracted and overaward_amount_subtracted. This is the value that was sent on the e-Cert and effectively paid to the student.

**Overawards cancellation during application cancellation**

- [x] When an application is cancelled by the student, the application status is immediately changed to "Cancelled" (no changes in the current process) and an entry is added to the queue `cancel-application-assessment` to cancel the workflow instance, if present, and check for possible overawards cancellation. 
    - [x] Soft delete records from `sims.disbursement_overawards` that are associated with the assessment being cancelled and that are not associated with any award. A record associated with an assessment and with an award means that it is a deduction that happened during the e-Cert generation which also means that the award was already sent to be paid to the student. These records are not cancelled.
    - [x] Any disbursement schedule in 'Pending' state must be changed to 'Cancelled'.

**Overawards cancellation during application edit**

- [x] When a student edits an application a new copy of the same application is generated (no changes in the current process) and during this process, the overawards cancellation must happen in the same way that they would happen if the student was cancelling the application.

**How to cause some loans assessment variations to create overawards**
- Create an offering with 6 months with the start date today or in the near past or near future (less than 5 days ahead). Add tuition values as 80,000 (later we will reduce tuition values to cause overawards).
- Create a student application with this offering, approve NOA and confirm COE to make it completed and ready for disbursement.
- Trigger the e-Cert generation. Considering the disbursement schedule is around today, the application is completed, and the student has a valid MSFAA, and all others requirements, the disbursement should happen.
- After the disbursement happened, request an offering change to reduce the number of weeks (2 months) and the tuition values (cut values by half).
- Go to AEST portal and approve the offering change request to force the reassessment to happen. The new values generated by Canada/BC loans should be reduced in a way where what was already paid is greater than the money that the student will be receiving in the reassessment.

**Comment by JasonCTang** [comment]
Verified through database.  We will need to run through some more tests once we have the UI in place.
