### ISSUE TITLE
Load additional information from legacy account

### ISSUE THREAD

**Issue by abschwenker** [bcgov/SIMS#1352]
**Context**
**Review with DEVs.  Does this mean there is existing data in the file that we're not important, or it's imported but not being utilized right now? Or is this about requesting more data to be added to the file? **

**Acceptance Criteria**
- [ ] Load additional information from legacy account
- During maximums calculations, need to retrieve this data as well

**Comment by JasonCTang** [comment]
Need to review this with DEVs to determine if there is outstanding data we still need from SFAS.

**Comment by ninosamson** [comment]
@JasonCTang @HRAGANBC  is this a duplicate?

**Comment by sslaws** [comment]
@HRAGANBC @ninosamson Jason, Signori, and myself propose that we close this ticket as it doesn't have sufficient information to do anything.

**Comment by HRAGANBC** [comment]
@sslaws @ninosamson 

Agreed, Stephen, I will close this. 

I believe it just speaks to the need to implement Program-Year maximums which have now been implemented a few months ago.
