### ISSUE TITLE
send student notifications - Assessment & SIN

### ISSUE THREAD

**Issue by TeresaBia** [bcgov/SIMS#1360]
Additional Context
- Followup to #1423

Acceptance Criteria
- Send the following emails at the specific event, each notification will have a common set of variables (subject to change in future)

- [x] Scenario - Assessment ready for student confirmation
- Template name: Student - Assessment Ready
- givenNames, lastName, email address, date
- message sentence: Your application assessment has been completed. Please visit your application details page to view additional information.
- Every time NOA status (required/ not required) is defined, we will be sending notification.

- [x] Scenario - SIN Validation complete
- Template name: Student - SIN Validation Complete
- givenNames, lastName, email address, date
- message sentence: Your SIN validation has been completed. Please log in to view additional information.
- Incase ESDC returns status code 2 (under review), we will not be generating notification.

**Comment by ann-aot** [comment]
Created below templates in https://notification.canada.ca/services

1. Student - SIN Validation Complete

-Template ID : 9a607113-198e-4f8a-b28e-dad3f69cb46a

2. Student - Assessment Ready

- Template ID : bbe0341a-cfb5-4262-b817-6f4b70a0c2cf
