### ISSUE TITLE
Remove gender from BCSC integration

### ISSUE THREAD

**Issue by abschwenker** [bcgov/SIMS#1390]
**Additional Context**
BCSC indicates that we should not to collect gender for parents and partners via integration as our use case does not fit the needs. This also means since we have 1 integration that students will also not have their gender provided by BCSC

Acceptance Criteria
- [x] Remove gender from BCSC login integration (including mappers in keycloak)
- [x] Move gender field out of the area that says "go to BCSC to change"
- [x] Change Student readonly Gender field to a dropdown with the values
- Male (male)
- Female (female)
- Unknown (unknown)
- Diverse (diverse)
- [x] Remove Gender field from supporting users (and column)

**Comment by dheepak-aot** [comment]
BCSC Create user testing in local.

![image](https://user-images.githubusercontent.com/54600590/210011494-aa21bd15-57c0-46af-bab1-c254ebce32b5.png)

**Comment by dheepak-aot** [comment]
## Gender field moved to common area in form
As the gender field moved out of the read only area which belongs bcsc information the gender field is now common and between the student create form(student created from bcsc) and student account application form(student requesting for account from bcsc). 
Hence create student profile looks like
![image](https://user-images.githubusercontent.com/54600590/210011494-aa21bd15-57c0-46af-bab1-c254ebce32b5.png)
