### ISSUE TITLE
Overlapping study period or pending PIR error message

### ISSUE THREAD

**Issue by TeresaBia** [bcgov/SIMS#1405]
To replicate in TEST:

1. Student submit PIR
2. Not clear if the error message is accurate and how to resolve it

![MicrosoftTeams-image (5).png](https://images.zenhubusercontent.com/61c390f5d34132a9b12ca101/776e8290-7fa2-4a66-a250-1e9290df4679)h

**Comment by abschwenker** [comment]
Not a bug, content review will be conducted in the future
