### ISSUE TITLE
Edit/refresh student application - some tabs remain empty

### ISSUE THREAD

**Issue by TeresaBia** [bcgov/SIMS#1408]
To replicate:
1. Edit application from Application Details page 
2. Toggle between Edit and View
3. There should be values in all application tabs but only program tab retains values
4. Refresh Page
5. Same error - some tabs are empty
6. Bug is intermittent and does not always occur

**Comment by andrepestana-aot** [comment]
The error could not be reproduced. It should happen before because there was an issue with the logout. If the session was finished but the UI doesn't reflect it, then this kind of error can happen.
