### ISSUE TITLE
send student notifications

### ISSUE THREAD

**Issue by abschwenker** [bcgov/SIMS#1449]
Additional Context
- Followup to #1423

Acceptance Criteria
- Send the following emails at the specific event, each notification will have a common set of variables (subject to change in future)

- [x] Scenario - Ministry completes or denies an exception
- Template name: Student - Student - Ministry Completes Exception
- givenNames, lastName, email address, date
- message sentence: Your exception request has been completed. Please visit your application details page to view additional information.

- [x] Scenario - Ministry completes or denies a change request
- Template name: Student - Student - Ministry Completes Requested Change
- givenNames, lastName, email address, date
- message sentence: Your requested change has been completed. Please visit your application details page to view additional information.

- [x] Scenario - School reports a change
- Template name: Student - Student - Institution Reports A Change
- givenNames, lastName, email address, date
- message sentence: Your institution has reported a change to your application. Please visit your application details page to view additional information.

- [x] Scenario - School completes a PIR
- Template name: Student - Student - Institution Completes Program Information Request
- givenNames, lastName, email address, date
- message sentence: Your institution has completed your program information request. Please visit your application details page to view additional information.

- [x] Scenario - School completes Enrollment (including tuition remittance status)
- Template name: Student - Student - Institution Confirms Enrolment
- givenNames, lastName, email address, date
- message sentence: Your institution has completed your confirmation of enrolment. Please visit your application details page to view additional information.

**Comment by dheepak-aot** [comment]
Technical debt SIMS #1618 to create index for notifications table has been created.
