### ISSUE TITLE
Design Challenge- Financial Aid Application Question and Data Model

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#145]
**Describe the task**
Determine Financial Aid Application Data Model Decisions

Tasks
-----------------------------------
Save Data (Raw or Structured?). 
Data Logic - Dynamic Questions
Submit Data
Data that is saved but it is not yet validated

**Comment by abschwenker** [comment]
Needed Further investigation.

Will be investigating further options via "hackathon" #272
