### ISSUE TITLE
replace export default with `defineComponent`

### ISSUE THREAD

**Issue by ann-aot** [bcgov/SIMS#1461]
1. replace `export default` with `defineComponent`
2. there are some property type error in some vue files
![image.png](https://images.zenhubusercontent.com/608872f7d0d25cdfe8dab75d/4f0c7ddd-d7bd-4cf3-be13-44d42be32a61)
![image.png](https://images.zenhubusercontent.com/608872f7d0d25cdfe8dab75d/c140e6fb-7f62-40bf-a7c4-0009a2f443d1)
3. make min-width and max-width of the modal component generic

**Comment by andrepestana-aot** [comment]
Added defineComponent() to:

sources/packages/web/src/App.vue
sources/packages/web/src/components/aest/OfferingApplicationBanner.vue
sources/packages/web/src/components/aest/OfferingChangeRequest.vue
sources/packages/web/src/components/aest/institution/modals/ApproveProgramModal.vue
sources/packages/web/src/components/aest/institution/modals/AssessOfferingChangeModal.vue
sources/packages/web/src/components/aest/institution/modals/AssessOfferingModal.vue
sources/packages/web/src/components/aest/institution/modals/DeclineProgramModal.vue
sources/packages/web/src/components/common/AppealRequestsForm.vue
sources/packages/web/src/components/common/AssessmentAwardDetails.vue
sources/packages/web/src/components/common/IdleTimeChecker.vue
sources/packages/web/src/components/common/InstitutionUserSummary.vue
sources/packages/web/src/components/common/LocationSummary.vue
sources/packages/web/src/components/common/ManageProgramAndOfferingSummary.vue
sources/packages/web/src/components/common/OfferingSummary.vue
sources/packages/web/src/components/common/ProgramDetails.vue
sources/packages/web/src/components/common/ProgramOfferingDetailHeader.vue
sources/packages/web/src/components/common/ScholasticStandingForm.vue
sources/packages/web/src/components/common/StudentAppealForm.vue
sources/packages/web/src/components/common/StudentApplication.vue
sources/packages/web/src/components/common/StudentProfileForm.vue
sources/packages/web/src/components/common/modals/ConfirmExtendTime.vue
sources/packages/web/src/components/common/modals/ConfirmModal.vue
sources/packages/web/src/components/common/notes/Notes.vue
sources/packages/web/src/components/common/restriction/AddRestriction.vue
sources/packages/web/src/components/common/restriction/ViewRestriction.vue
sources/packages/web/src/components/common/sin/AddNewSIN.vue
sources/packages/web/src/components/generic/BCLogo.vue
sources/packages/web/src/components/generic/Banner.vue
sources/packages/web/src/components/generic/BodyHeader.vue
sources/packages/web/src/components/generic/CheckPermissionRole.vue
sources/packages/web/src/components/generic/ChipLabel.vue
sources/packages/web/src/components/generic/ChipStatus.vue
sources/packages/web/src/components/generic/DetailHeader.vue
sources/packages/web/src/components/generic/ErrorSummary.vue
sources/packages/web/src/components/generic/FooterButtons.vue
sources/packages/web/src/components/generic/FormioModalDialog.vue
sources/packages/web/src/components/generic/HeaderNavigator.vue
sources/packages/web/src/components/generic/HeaderTitleValue.vue
sources/packages/web/src/components/generic/SnackBar.vue
sources/packages/web/src/components/generic/StatusChipActiveApplication.vue
sources/packages/web/src/components/generic/StatusChipActiveUser.vue
sources/packages/web/src/components/generic/StatusChipApplication.vue
sources/packages/web/src/components/generic/StatusChipAssessmentHistory.vue
sources/packages/web/src/components/generic/StatusChipCOE.vue
sources/packages/web/src/components/generic/StatusChipDesignation.vue
sources/packages/web/src/components/generic/StatusChipDesignationAgreement.vue
sources/packages/web/src/components/generic/StatusChipOffering.vue
sources/packages/web/src/components/generic/StatusChipProgram.vue
sources/packages/web/src/components/generic/StatusChipProgramInfoRequest.vue
sources/packages/web/src/components/generic/StatusChipRequestedAssessment.vue
sources/packages/web/src/components/generic/StatusChipRestriction.vue
sources/packages/web/src/components/generic/StringToHtmlParagraphs.vue
sources/packages/web/src/components/generic/StudentRestrictionChip.vue
sources/packages/web/src/components/generic/TitleValue.vue
sources/packages/web/src/components/generic/ToggleContent.vue
sources/packages/web/src/components/generic/ValidatedInput.vue
sources/packages/web/src/components/institutions/active-application/ActiveApplicationSummaryData.vue
sources/packages/web/src/components/institutions/locations/LocationEditForm.vue
sources/packages/web/src/components/institutions/modals/AddInstitutionUserModal.vue
sources/packages/web/src/components/institutions/modals/EditInstitutionUserModal.vue
sources/packages/web/src/components/institutions/modals/InstitutionUserManagement.vue
sources/packages/web/src/components/institutions/modals/confirmationOfEnrollment/ApproveCOE.vue
sources/packages/web/src/components/institutions/modals/confirmationOfEnrollment/DenyCOE.vue
sources/packages/web/src/components/institutions/profile/InstitutionProfileForm.vue
sources/packages/web/src/components/layouts/Institution/sidebar/HomeSideBar.vue
sources/packages/web/src/components/layouts/Institution/sidebar/ManageInstitutionSideBar.vue
sources/packages/web/src/components/layouts/aest/AESTApplicationSideBar.vue
sources/packages/web/src/components/layouts/aest/AESTHomeSideBar.vue
sources/packages/web/src/components/partial-view/DesignationAgreement/DesignationAgreementForm.vue
sources/packages/web/src/components/partial-view/DesignationAgreement/DesignationAgreementSummary.vue
sources/packages/web/src/components/students/RestrictionBanner.vue
sources/packages/web/src/components/students/applicationTracker/Draft.vue
sources/packages/web/src/components/students/applicationTracker/Submitted.vue
sources/packages/web/src/components/students/modals/PDStatusApplicationModal.vue
sources/packages/web/src/views/aest/AppAEST.vue
sources/packages/web/src/views/aest/ApplicationExceptionsApproval.vue
sources/packages/web/src/views/aest/Login.vue
sources/packages/web/src/views/aest/NoticeOfAssessment.vue
sources/packages/web/src/views/aest/Reports.vue
sources/packages/web/src/views/aest/SearchInstitutions.vue
sources/packages/web/src/views/aest/SearchStudents.vue
sources/packages/web/src/views/aest/StudentAppealRequestsApproval.vue
sources/packages/web/src/views/aest/StudentApplicationView.vue
sources/packages/web/src/views/aest/SupportingUser.vue
sources/packages/web/src/views/aest/institution/Designation.vue
sources/packages/web/src/views/aest/institution/DesignationAESTView.vue
sources/packages/web/src/views/aest/institution/InstitutionDetails.vue
sources/packages/web/src/views/aest/institution/InstitutionLocationEdit.vue
sources/packages/web/src/views/aest/institution/InstitutionNotes.vue
sources/packages/web/src/views/aest/institution/Locations.vue
sources/packages/web/src/views/aest/institution/OfferingChangeRequests.vue
sources/packages/web/src/views/aest/institution/PendingDesignation.vue
sources/packages/web/src/views/aest/institution/Profile.vue
sources/packages/web/src/views/aest/institution/ProfileCreate.vue
sources/packages/web/src/views/aest/institution/ProfileEdit.vue
sources/packages/web/src/views/aest/institution/ProgramDetails.vue
sources/packages/web/src/views/aest/institution/Programs.vue
sources/packages/web/src/views/aest/institution/Restrictions.vue
sources/packages/web/src/views/aest/institution/Users.vue
sources/packages/web/src/views/aest/institution/ViewOffering.vue
sources/packages/web/src/views/aest/institution/ViewOfferingChangeRequest.vue
sources/packages/web/src/views/aest/institution/ViewOfferingChangeRequestComplete.vue
sources/packages/web/src/views/aest/student/Applications.vue
sources/packages/web/src/views/aest/student/FileUploads.vue
sources/packages/web/src/views/aest/student/Profile.vue
sources/packages/web/src/views/aest/student/SINManagement.vue
sources/packages/web/src/views/aest/student/StudentAccountApplications.vue
sources/packages/web/src/views/aest/student/StudentAccountApplicationsApproval.vue
sources/packages/web/src/views/aest/student/StudentApplicationAppeals.vue
sources/packages/web/src/views/aest/student/StudentApplicationExceptions.vue
sources/packages/web/src/views/aest/student/StudentDetails.vue
sources/packages/web/src/views/aest/student/StudentNotes.vue
sources/packages/web/src/views/aest/student/StudentRestrictions.vue
sources/packages/web/src/views/aest/student/ViewScholasticStanding.vue
sources/packages/web/src/views/institution/AddInstitutionLocation.vue
sources/packages/web/src/views/institution/AppInstitution.vue
sources/packages/web/src/views/institution/EditInstitutionLocation.vue
sources/packages/web/src/views/institution/InstitutionCreate.vue
sources/packages/web/src/views/institution/InstitutionProfile.vue
sources/packages/web/src/views/institution/InstitutionUserDetails.vue
sources/packages/web/src/views/institution/InstitutionUserProfile.vue
sources/packages/web/src/views/institution/Login.vue
sources/packages/web/src/views/institution/ManageLocations.vue
sources/packages/web/src/views/institution/designations/DesignationRequest.vue
sources/packages/web/src/views/institution/designations/DesignationView.vue
sources/packages/web/src/views/institution/designations/ManageDesignations.vue
sources/packages/web/src/views/institution/locations/active-applications/ActiveApplicationReportAChange.vue
sources/packages/web/src/views/institution/locations/active-applications/LocationActiveApplicationSummary.vue
sources/packages/web/src/views/institution/locations/active-applications/ViewSubmittedApplicationScholasticStanding.vue
sources/packages/web/src/views/institution/locations/confirmation-of-enrollment/ApplicationDetailsForCOE.vue
sources/packages/web/src/views/institution/locations/confirmation-of-enrollment/COESummaryData.vue
sources/packages/web/src/views/institution/locations/confirmation-of-enrollment/LocationCOESummary.vue
sources/packages/web/src/views/institution/locations/program-info-request/LocationProgramInfoRequestSummary.vue
sources/packages/web/src/views/institution/locations/programs/LocationProgramAddEdit.vue
sources/packages/web/src/views/institution/locations/programs/LocationProgramView.vue
sources/packages/web/src/views/institution/locations/programs/LocationPrograms.vue
sources/packages/web/src/views/student/CheckValidSINBanner.vue
sources/packages/web/src/views/student/Login.vue
sources/packages/web/src/views/student/StudentAccountActivity.vue
sources/packages/web/src/views/student/StudentApplicationSummary.vue
sources/packages/web/src/views/student/StudentDashboard.vue
sources/packages/web/src/views/student/StudentFileUploader.vue
sources/packages/web/src/views/student/StudentProfileCreate.vue
sources/packages/web/src/views/student/StudentProfileEdit.vue
sources/packages/web/src/views/student/financial-aid-application/Applications.vue
sources/packages/web/src/views/student/financial-aid-application/FullTimeApplication.vue
sources/packages/web/src/views/supporting-user/AppSupportingUser.vue
sources/packages/web/src/views/supporting-user/Dashboard.vue
sources/packages/web/src/views/supporting-user/Login.vue

Some errors TS errors are shown as below:
![image.png](https://images.zenhubusercontent.com/601c6b4f5322cf5c519d503f/b3ff1fa4-a611-4bd8-bd86-bc4e49c01889)

We don't have any compilations errors though.
