### ISSUE TITLE
Queues Analysis and Implementation

### ISSUE THREAD

**Issue by abschwenker** [bcgov/SIMS#1476]
**Analysis**
- [x] investigate nest usage of bull and redis for queue usage
- [x] investigate persistent vs memory storage
- [x] investigate backup of queue
- [x] determine work effort of of fully enabling queue in all environments with backups
- [x] determine work effort to create pods and deployment scripts
- [x] determine local setup
- [x] investigate alternatives (postgres queue?)
- [x] investigate queue monitoring ui

**Implementation**
- [x] Define and review above implementation
- [x] Implement defined above solution

**Purposed Work Strategy**
- Create new application
- Install nest package
- create consumer
- make local work
- dev review
- create and deploy 1 queue working
- dev review
- create deployment scripts
- create backups

**Comment by dheepak-aot** [comment]
Created technical debt #1580 for liveness and readiness probe.

**Comment by dheepak-aot** [comment]
Back up of queues are subjective on how queues are going to be used further. Created tech debt #1583 if backup is required for redis.
