### ISSUE TITLE
Process Confirmation of Enrolment file for institutions

### ISSUE THREAD

**Issue by abschwenker** [bcgov/SIMS#1501]
Additional Context
- File layout:
  -[https://app.zenhub.com/files/319429847/123a8930-13e2-47b1-80f0-b720cff7b7cb/download](https://app.zenhub.com/files/319429847/123a8930-13e2-47b1-80f0-b720cff7b7cb/download) 
- Sample file:
 - https://bcgov.sharepoint.com/:t:/r/teams/03177/Shared%20Documents/General/Analysis/Institution%20File%20Specs/CONR_008.TXT?csf=1&web=1&e=alE9WO
- File is based off all applications that have an eligible COE request waiting
- When SIMS creates ECE file and passes it to SFAS/HARRY, the SFAS COEs will be appended before sending to institutions.  So the response file will contain approvals/denials for both systems meaning we need to skip over any apps that don't match.
- If one award is approved, then assume all awards are approved for that disbursement. 
- Sum all tuition remittance from awards for a single disbursement. 
- Notifications ***WILL NOT*** be included in this ticket.

Acceptance Criteria
- [x] System user to read file and update database.
- [x] For each disbursement, sum all tuition remittance amounts for all awards.
- [x] When processing the file, treat it the same as the manual COE confirmation process and perform the same validations and notifications.
- [x] Move API COE approval process to shared services to be used by schedule
- [x] When COE is declined, there needs to be a reason.  If response file does not include a reason for declines, then we need to have a default reason to populate the field.
- [ ] Search institutions by the institution code (it's a field in the file and also in the file name)
- [x] Search disbursement by the Award_disbursement_id we sent them
- [x] Assume a record can be received twice, update the first time only. 
- [x] If parsing the file fails, stop processing the file. 
- [x] When processing the records after the file has been passed, if a record does not pass validation, skip over the WHOLE DISBURSEMENT and continue.
- [x] In the log, identify which records did not pass validation and report how many applications were not found and report how many applications were duplicates.
- [ ] If a COE is denied, there is no "reason" provided in the CONR_008.txt file, so default to "Please speak to your institution."
- [x] Create E2E test.

Questions
- [ ]  What do we do when any records in the response file does not pass validations? How is this handled in SFAS currently?
  - SFAS stops processing the file if it encounters an error and automatically emails the Institution user to let them know there was an issue with the file. Any records that were not updated, get included again in the next file. 
  - ***Notifications WILL NOT be included in this ticket***
- [ ] What is the folder and file name of the response file?
  - Reponse file name is CONR_008.TXT.  Will be on Linda. E:\OpenSSH_Root\Institution-Response\[XXXX] <-- folder named by institution code.  
- [ ] Is the file we receive based on disbursement or awards? 
  - Harry said it's by disbursement, but to him, it's one disbursement per funding type.  So if one ecert has CSL, BCSL, and a BC grant, then it contains 3 separate disbursements.
- [ ] Is it one record per disbursement or one record per award (multiple awards to a disbursement)? Is one yes, considered yes for all?
  - They SHOULD NOT be approving only some of the awards.
  - If One is approved, then assume all approved.
- [ ] Get an example file.
  - Submitted request for Harry to provide example file. 
- [ ] What is maximum number of records we can expect to process in one file?
  - Unlimited, but reallistically, it would be in the thousands.  
  - 
###  Updates and assumptions to the story which were identified during implementation (Updated by @dheepak-aot )

- As per discussion with @JasonCTang 24 institutions are expected to be part of the ECE response file integration with an expected transaction volume of 1000 records per day.
- To identify the disbursements which belong to SIMS in the file records, we check the record with disbursement schedule Id and the application number.
- Only following values in the ECE detail records are read ignoring all other values. Institution code, Award_Disbursement_Idx, Application number, Confirmed Enrollment  for Disbursement  Flag, Enrollment Confirmation Date and Pay to School $ Amount.
- It is assumed that pay to school $ amount must be 0 if tuition remittance is not requested by institution.
- It is assumed that Pay to school $ amount will be 0 for BGPD and SBSD as it cannot be requested for these awards.
- When an enrolment is confirmed, the enrolment period validations are done based on enrolment confirmation date in the file.
- The enrolment decline reason content has been updated for declining enrolment through ece file integration  as per discussion with @hellolynn-tbtb as `A reason was not provided by your institution. Please speak to your Financial Aid Officer at your institution for details.`

**Comment by dheepak-aot** [comment]
@JasonCTang During the implementation, at a discussion with @andrewsignori-aot we found that, the institution location code is unique only within the institution as per our database constraint. e.g. InstitutionA can have a location with code KHID and Institution B can have a location with same institution code KHID. 

![image.png](https://images.zenhubusercontent.com/60e72aa247c95cd873ed8ce1/c6ed8e96-8e99-4797-9020-7a3d6d63771b)

So is it possible that 2 different institution's locations can have same institution code?  
All the institution integration efforts were done based on institution code being unique across SIMS.

**Comment by dheepak-aot** [comment]
Test scenarios covered by E2E tests.

![image](https://github.com/bcgov/SIMS/assets/54600590/8832e8cb-6483-4fa1-abb2-ecf5d4356542)
