### ISSUE TITLE
 Content - Notifications to Institutions on Programs

### ISSUE THREAD

**Issue by hellolynn-tbtb** [bcgov/SIMS#1544]
### **Describe the task**
- Lynn to implement content updates in DEV environment.
- Content updates include business feedback, accessibility (AA+), and B.C. government content standards.

### **Acceptance Criteria**
- [ ] Update Programs (Summary)
- [ ] Update Programs (Detail)
- [ ] Update Programs - Form
- [ ] Check off on forms (Allow only available values) https://app.zenhub.com/workspaces/student-information-management-system-5fce9df5aa1b45000e937014/issues/bcgov/sims/176

**Comment by michesmith** [comment]
Covered under content review- closing
