### ISSUE TITLE
Upgrade Postgres

### ISSUE THREAD

**Issue by andrewsignori-aot** [bcgov/SIMS#1578]
**Acceptance Criteria**
- Update Postgres for the most recent version (currently version 15)

**Comment by guru-aot** [comment]
**Steps for upgading postgres locally**

- take current db backup

docker container ls
docker exec -it {container_name} /usr/bin/pg_dumpall -U admin > dumpfile

- stop container
- delete container
- delete image
- delete volumes
- change postgres version from 12 to 15 in sources/.docker/postgres/Dockerfile file
- Delete the role query at the top of the dumpfile by opening it in textpad(eg: CREATE ROLE admin;
ALTER ROLE admin WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN REPLICATION BYPASSRLS PASSWORD 'xxxxxxxxxxxxx’;)

make db
docker exec -i {container_name} psql -U admin -d aest < dumpfile

**Upgading postgres in openshift analysis**
- Our postgres image for openshift is build using the BCGov patroni repository https://github.com/BCDevOps/platform-services.git
- This repo contains the upgrade till postgres 12.5, the current version in out openshift dev and test are 12.5 
<img width="654" alt="image" src="https://user-images.githubusercontent.com/62901416/213802795-c0ddec70-d7d9-483b-9281-ed0429a0f2ea.png">
- So to upgrade our current database we may need additional libraries to be build in the patroni image, and deployment should happen.

**Sample commands to deploy patroni**
  - Prerequisite: You should have a role in your github to create Rolebindings access in openshift
  - Goto devops folder in our current repo in Terminal
  - make oc-build-patroni -p NAMESPACE=0c27fb-tools
  - make init-patroni -p NAMESPACE=0c27fb-dev
  - make oc-deploy-patroni -p NAMESPACE=0c27fb-dev
