### ISSUE TITLE
Ministry Confirm Enrolment and Disburse after Study End Date

### ISSUE THREAD

**Issue by abschwenker** [bcgov/SIMS#1590]
### Acceptance Criteria
- [x] Disable institution COE if (today - 42 days (6 weeks)) > offeringEndDate (At present it is assumed to be 42 days(6weeks) and this number may change)
- [x] If student application selected offering end date is past today trigger EXCEPTION and display banner
- [x] During PIR if institution selects offering that is past today display banner
- [x] Add "confirm enrolment" button on ministry disbursement summary page (mockup 3)
- [x] If user clicks confirm enrolment display yes/no modal
- [x] Tuition remittance always = 0 if completed by ministry
- [x] Add role to keycloak AEST user as "student-confirm-enrolment" add to groups: aest-business-administrators

#### Additional Context(Added by @dheepak-aot )

Confirmed with @JasonCTang on following context of the user story.
 - Ministry staff should be able to confirm enrolment at any time.(Even outside the 21 day COE window)
 - We can allow COE to be declined past the study end date by both Institutions and Ministry users.(Note: ministry declining COE is not in the scope of this story).

### Figma

Mockup 1 (student - Application including "program not listed")

https://www.figma.com/file/9Om2tzLAVEoMQrjmrH4fhu/MOD-SIMS?node-id=5517%3A105612&t=0H8HhRFLnYItlOQH-0

https://www.figma.com/file/9Om2tzLAVEoMQrjmrH4fhu/MOD-SIMS?node-id=5517%3A105807&t=0H8HhRFLnYItlOQH-0

Mockup 2 (institution - PIR)

https://www.figma.com/file/9Om2tzLAVEoMQrjmrH4fhu/MOD-SIMS?node-id=10003%3A106780&t=0H8HhRFLnYItlOQH-0

Mockup 3 (ministry - Confirm button)
https://www.figma.com/file/9Om2tzLAVEoMQrjmrH4fhu/MOD-SIMS?node-id=9942%3A106726&t=DIVl4GkY5TgFndcI-0

**Comment by dheepak-aot** [comment]
Hello @JasonCTang ,

Here are the questions that I had regarding the story

- The AC says **Disable institution COE** which for sure is Institution should not be able to confirm/approve the COE if the application study end date is past today, but should the decline COE be disabled for institution in such case?
Currently I am proceeding with the story with yes as assumption to this.

- While Ministry is approving COE, should the approve button be disabled if the disbursement date is outside the 21 day window from the current date(the rule that we have for institution) ?
I am currently proceeding story with the assumption No to this question.

**Comment by dheepak-aot** [comment]
Hello @hellolynn-tbtb ,

When Confirm Enrollment is disabled when the application end date is past, I beilieve we must show a banner in Confirm Enrolment page like we do while restricting COE confirmation which is outside 21 days and looking forward for the same. 

![image.png](https://images.zenhubusercontent.com/60e72aa247c95cd873ed8ce1/dd15a647-9e28-4761-9388-4593ee0ecf92)

**Comment by dheepak-aot** [comment]
Confirmed with @JasonCTang on following context of the user story.

- Ministry staff should be able to confirm enrolment at any time.(Even outside the 21 day COE window)
- We can allow COE to be declined past the study end date by both Institutions and Ministry users.(Note: ministry declining COE is not in the scope of this story).

**Comment by dheepak-aot** [comment]
Updating the first AC as per discussion with @JasonCTang to 

Disable institution COE if (today - 42 days (6 weeks)) > offeringEndDate (At present it is assumed to be 42 days(6weeks) and this number may change)

We are yet to get confirmation from business if that x in (today - (x)days) is 42.

**Comment by dheepak-aot** [comment]
Ticket #1669 is created to handle changes when business logic behind a valid and date for confirmation period for institution once it is concluded. https://app.zenhub.com/workspaces/student-information-management-system-5fce9df5aa1b45000e937014/issues/gh/bcgov/sims/1669
