### ISSUE TITLE
Migrate Keycloak from Silver to Gold cluster

### ISSUE THREAD

**Issue by abschwenker** [bcgov/SIMS#1615]
**Additional Context**
- SSO is decommission silver cluster
- We are migrating to gold to allow for better disaster recovery
- Currently Keylcloak Realm: dev.oidc.gov.bc.ca/auth/admin/jxoe2o46
- New Keylcloak Realm: https://dev.loginproxy.gov.bc.ca/auth/admin/master/console/#/realms/aestsims/

**Acceptance Criteria**
- [x] Create instructions for standing up a new realm for SIMS (template in analysis folder)
- [x] Migrate to new realm
- [x] Fix logoff after migration to gold
- Purposed fix, number 1 in https://github.com/bcgov/sso-keycloak/discussions/161
- Investigate is keycloak package on Vue can be upgrades and provide an out of box solution

Instructions created on https://github.com/bcgov/SIMS/wiki/Keycloak-(SSO)---Config

**Comment by andrewsignori-aot** [comment]
Keycloak configs backup added to Teams, as shown below.
![image.png](https://images.zenhubusercontent.com/5fcebe3c076e6aaed83693fb/cecfb0b2-8c27-49af-ad49-d4ae8fd92601)
