### ISSUE TITLE
Student Confirms Consent to Share and Validate Income with CRA

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#163]
**As a** *(Student)* **I want** *(to consent to share and validate my Personal Income information with CRA )* **So That** *(I can accurately be assessed for Financial Aid)

**Additional Context**
- CRA =Canada Revenue Agency
- Persona Matt- Selects Yes
This Feild is Mandatory upon submit (separate user Story)

**Figma Wireframe Link**
[Loan Application - Financial Information ](https://www.figma.com/file/VykmBDwobGoGvK9M5wgOvN/FreshWorks-Studios-StudentAid-BC-App-Design-System-WIP?node-id=158%3A469)

**Acceptance Criteria**
- [x] Given (The student, When (wants to confirm that they consent to share their information with CRA for Validation, Then (they select Yes)
- [x] Given (The student, When (wants to confirm that they consent to share their information with CRA for Validation, Then (they select No)
- [x] Given (The student, When (is reading the consent to share summary Then (the student can select "read more" to expand the consent information field to include the remaining information)- See Figma
- [x] Given (The student, When (has expended the text to "read more and they want to see less text Then (the student can s select "read less)".- see Figma

**Comment by andrewsignori-aot** [comment]
![image.png](https://images.zenhubusercontent.com/5fcebe3c076e6aaed83693fb/da6f4edd-278a-40d8-9942-702112aa9c03)
