### ISSUE TITLE
Student Overawards /  Maximums / Tuition Remittance on NOA

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#1632]
**Acceptance Criteria**
- [ ] If **restrictions** caused final/actual funding to be different than estimated award amount:
- Add red label next to each impacted funding type on application
- Add tooltip with text reading _"one or more restrictions active on your account resulted in actual funding which was different than the originally estimated award for this funding type"_  

- [ ] If **overawards** caused final/actual funding to be different than estimated award amount:
- Add red label next to each impacted funding type on application
- Add tooltip with text reading _"overawards were active on your account and were therefore deducted from your award amount. This resulted in actual funding which was different than the originally estimated award for this funding type"_  

<img width="407" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGI1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ec7a95e030c2b16b492bc8ee0a3dfdceeeb3932e/image.png" alt="image.png" />

General rules
Anytime **any** reason caused differences between actual funding and estimated awards, 
- [ ] When NoA is first displayed to student (i.e. before it's accepted), and OA are present on the student's account, add a banner warning immediately beneath the total estimated award amount on the NoA reading: _"You have overawards on your account, which will be deducted from your eligible award if they are not repaid. Contact NSLSC to repay your overawards, otherwise they will be automatically subtracted from your funding amount displayed above"_
- [ ] add an Application Status Tracker Card with the following message: _"Your funding has been disbursed. The actual amount received is different than the estimated award amounts originally displayed on your Notice of Assessment. This could be due to active restrictions on your account, overawards active on your account, or tuition remittance which was requested and disbursed directly to your school."_
- [ ] Add a banner message on NoA with wording which reads: _"Your actual funding amounts received are different than the amounts estimated during the initial assessment. This was caused by restrictions, overawards, or tuition remittance"_
- [ ] On the Final Award Card, multiple labels can be applied next to each funding type. I.e. if a restriction and overaward impacted a single funding type, there can be two red labels and two tooltips next to that funding type, one for each reason. 
- [ ] Any labels applied to the Award Cards should be presented identically to student and Ministry user

**Comment by michesmith** [comment]
Duplicate ticket- will be covered in NOA review
