### ISSUE TITLE
Student Provides Financial Information-Travel Costs

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#165]
**As a** *(Student)* **I want** *(to provide my Travel Costs)* **So That** *(I can accurately be assessed for Financial Aid)

**Additional Context**
- "If you must relocate to a different city to attend school and you will return home at least once during your study period, what is the cost of one return trip home?"
- This Question is mandatory upon Submit (another User Story)
- This field is mandatory upon Submit (another User Story)
- Persona Matt Does not have Travel Costs

**Figma Wireframe Link**
[Loan Application - Financial Information ](https://www.figma.com/file/VykmBDwobGoGvK9M5wgOvN/FreshWorks-Studios-StudentAid-BC-App-Design-System-WIP?node-id=158%3A469) (Do not show the Yes options)

**Acceptance Criteria**
- [x] Given (The Student), When (is providing an answer to Travel Costs), Then (They Select Yes / No)

**Comment by 2011sandeepraj** [comment]
![image.png](https://images.zenhubusercontent.com/5f7666963ac7b77e35e99678/bfd38b6d-09de-44fd-b1c8-c32230213196)
