### ISSUE TITLE
Determine what information needs to be logged for technical operational support

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#1651]
@Jason.. Does the ministry have requirements for this or gov in general? 

The system in general generates logs. SIMS Api, Queue-consumers, and Camunda Workers generate some sort of information log and error logs. Are there any specific logging requirements that the system must comply with in terms of:
- Ability to enable different log levels. Useful for troubleshooting in some cases.
- Persist logs in any different location. Right now they are saved to the console and captured by Kibana.
- Is there any sort of format that the system must comply with?
 
Please find below some examples of information logs the system generates regularly for the 3 different applications.

#### SIMS Api
![image.png](https://images.zenhubusercontent.com/5fcebe3c076e6aaed83693fb/15f71fc5-4194-4719-a0c2-a94e8d136899)

#### Camunda Workers
![image.png](https://images.zenhubusercontent.com/5fcebe3c076e6aaed83693fb/c6ac0409-9047-465f-99eb-2ee7bd1043cb)

#### Queue-consumers
![image.png](https://images.zenhubusercontent.com/5fcebe3c076e6aaed83693fb/931431aa-472f-45df-ae68-1c63a0cba816)

**Comment by ninosamson** [comment]
@JasonCTang - just looking at screenshots - I don't see any user/IP address info. Maybe we just confirm if this is configurable.
