### ISSUE TITLE
UXUI - Addition of PD/PPD status to COE and ECE

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#1695]
PSIs need to be able to identify PD/PPD status whenever confirming enrollment, but the info currently isn’t reflected in the COE processes because PD/PPD wasn’t built at the time. 

**Additional Context**
This means PD/PPD status needs to be provided for each COE provided to the institution.  In the UX/UI, there needs to be a field that indicates whether student is PD, PPD or Neither.   And in the ECE-request files, there needs to be the addition of a data element indicating if the student is PD, PPD or Neither.

**Acceptance Criteria**
- [ ] The student’s PD / PPD status is included as data element in the ECE-request file sent to PSIs 
- [ ] A field in the UX/UI of every COE screen indicating the student's PD/PPD status.

**Question**
- Why does the institution need to know the PD/PPD status of the student at time of COE? SIMS would've already handled this status vs the course load rules during assessment.

**Comment by HRAGANBC** [comment]
Closing ticket - replaced by #2523
