### ISSUE TITLE
Remove obsolete form definitions

### ISSUE THREAD

**Issue by dheepak-aot** [bcgov/SIMS#1705]
**Describe the task**
Remove all the un-used form definitions from GIT repository and also form.io server.

Here are the list of forms which are identified as obsolete ones.

aestdashboard.json
approvedeclineoffering.json
approvedenydesignation.json
approveeducationprogram.json
createnote.json
declineeducationprogram.json
institutiondashboard.json
studentapplicationdetails.json
studentdashboard.json
trackstudentapplication.json

**Acceptance Criteria**
- [x] Remove the obsolete form definitions from GIT repository

**Comment by andrewsignori-aot** [comment]
Added to the sprint as agreed by @ninosamson  and @michesmith.
