### ISSUE TITLE
Add estimated current year income exception question to PT and FT(form only) application

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#1706]
As a student I want to be able to submit a request for exception in order to use the "current year" income. This allows me to reflect changes to my financial circumstance and receive a more accurate assessment.

**Acceptance Criteria**
- [x] Add form question for use of current year income. (Can see Image 1 on FT app and below. However, there are additions in this ticket)
- [x] The year listed at the top of the question should be dynamic and should reflect the program application year (eg. 2024-2025 should show 2024)
- [x] This question needs to be an exception question and trigger the exception path 

- [x] Add a document uploader to this question. Uploader should show up when student selects yes to this question. It should be below the current form information.

Content for documentation for uploader:
> **Upload supporting documents for current year estimated income.**
> Please provide supporting documentation for your request to use your current year estimated income.
Provide the following:

> - A letter explaining the circumstances that meet one or more of the Criteria (see above)
> 
> Provide at least one of the following:
> 
> - All relevant supporting documentation of the circumstance(s) (medical records, letter from the physician, record of employment, layoff or strike, invoices from damages, etc.).
> - The more recent CRA Income Tax Return and income information for the year matching the student financial assistance application number (with relevant supporting documentation to show the decrease in income), if available.
> - All relevant supporting documentation of estimated total income for the year matching the student financial assistance application number, if applicable (pay stubs, invoices, bank statements, Employment Insurance benefit statements, Record of Employment, etc.).
> 

- [x] Will need a variable for the estimated current year income from app. suggested name `studentDataCurrentYearIncome`
- [x] New variable will need to be part of the following calculation and the new variable will need to trump all other income options.  if  `studentDataCurrentYearIncome` (sample new variable) exists use it over all of the current calculation. If it does not exist then user current calculation as usual.
- [x] This exception approval and variable would take precedence over all other income variables including CRA 
```

Current
 if
 studentDataCRAReportedIncome = null
then
  calculatedDataTaxReturnIncome
else
  studentDataCRAReportedIncome
```

```
Suggested new calculation
if 
studentDataCurrentYearIncome = null
then
	if 
                studentDataCRAReportingIncome = null
	then
		calculatedDataTaxReturnIncome
	else
		studentDataCRAReportingIncome

else
studentDataCurrentYearIncome
```

- [ ] Ministry approval portal content view for this exception
<img width="917" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeE56QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--32c6d3bd25470316766831181b88f9d442a18328/image.png" alt="image.png" />

Additional Context:
Image 1
<img width="845" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHRpQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e03f6d56f56455270aaf328334fb48a1eb033096/image.png" alt="image.png" />

Image 2
"Please submit at least one of the following"
<img width="856" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1ZuQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8ce92ac9b7491a4e87e7de4b404b251d39af4f04/image.png" alt="image.png" />

Camunda view of calculation
Image 3
<img width="1039" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVJuQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--332a107fa607e8edf7a326a5750a28b494b8006e/image.png" alt="image.png" />
<img width="781" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1Z6QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7e224efe9b14b9340c09c336712728267f596b0f/image.png" alt="image.png" />

**Technical**
- [ ] Adjust the form.io content for PT/FT including the hidden field for the exception.
- [x] Load the new variable `studentDataCurrentYearIncome` into the assessment gateway.
- [ ] Update the `part-time-assessment-*` BPMNs (no full-time changes required).
- [ ] Update form.io content in the `studentExceptions` definition to show the new exception to the Ministry.
- [ ] E2E tests
  - [ ] Update workflow tests as needed.
  - [ ] Create at least one new specific scenario to test the new variable.

**Comment by CarlyCotton** [comment]
Similar to Student Application Updates: Income Appeal re-located exclusively to Request a Change process #2144

**Comment by Joshua-Lakusta** [comment]
Reworked this ticket into adding the part time question back.
