### ISSUE TITLE
Application Form - Additional Transportation Costs (FT and PT)

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#1707]
**User Story**
As a FT or PT student, I need to be able to report exceptional transportation expenses so that it can be approved and incorporated into my assessed need. 

**Current Behaviour**
In the Financial information tab of the application under "Additional transportation cost", if the student selected "Yes" to _Do you want to be assessed for additional transportation costs_ they get prompted for more information (radio dials, supporting document upload).

They are also prompted to provide an estimate of weekly transportation cost.

This is an exception request that goes to the Ministry to approve or decline.

If approved, it is unclear where the value is being incorporated in the assessment.

**Expected Behaviour**
In the Financial information tab of the application (PART TIME and FULL TIME) under "Additional transportation cost", if the student selected "Yes" to _Do you want to be assessed for additional transportation costs_ they get prompted for more information (radio dial, and supporting document upload).

In addition to the estimate of weekly transportation costs, we need more fields to capture the total estimated kms being travelled, how many weeks the student needs additional transportation for and if they are already receiving transportation allowance as part of their exceptional expenses: 
<img width="921" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWZPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c6396d8d74261d972c62df5efa32e98dc40797bc/image.png" alt="image.png" />

This is an exception request that goes to the Ministry to approve or decline.

Where this fits in the PT & FT assessments will vary. Additional tickets for each workflow update will be created. 

**Additional Context**
- Additional Transportation Cost is different from Return Transportation Cost.
- The AdditionalTransportationAllowance does NOT need to get mapped to IER-12
- There is a transportation cost variable in Camunda: studentDataTransportationCost but it is UNCLEAR which field is attached.
- Ministry policy on the data provided:
> If you travel more than 280 km per week:
> - Multiply $94 times the number of weeks during your study period that you require the additional transportation allowance. Enter this number in the field below.
> If you travel 280 km or less per week:
> - Multiply [the number of km driven per week] x [0.34] x [the number of weeks in your study period that you will need the additional transportation allowance]. Enter this number in the field below.
>Please note in either situation if you are already receiving the $25 weekly allowance for a clinical or practicum placement from your institution please subtract that from the calculated amount of Kilometers driven x 0.34 or from the $94 when travelling over 280 km per week."_

**Acceptance Criteria**
- [ ] Update application form (FT & PT) based on screenshot provided:
- New question for KMs "During your study period, what is the average number of kilometers you will travel each week from your place of residence to your school and back?"
- New field for KMs ( 3 digits, set max at 999kms, no negatives, and whole numbers)
- As per conformation from @Joshua-Lakusta , the validation for weekly transportation cost is: 0 <= cost <= 9999.
- New question for weeks needed "How many weeks of your study period will you be requiring funding for additional transportation"
- New field for weeks ( 2 numerical digit field, 52 weeks maximum, no negatives numbers, and whole numbers only no decimals)
- New question for allowance from PSI / radio dial input  "Have you received funding for transportation from your institution related to a practicum or clinical placement?"  Options would be yes or no with radial buttons for the selection
- [ ] Variables required for the fields to be used in Camunda: 
- studentDataAdditionalTransportKm (numerical)
- studentDataAdditionalTransportCost(if not already mapped) (numerical)
- studentDataAdditionalTransportWeeks (numerical, max 2 digits)
- studentDataAdditionalTransportPlacement (true/false)

**Comment by andrewsignori-aot** [comment]
Please see the below screenshot. Except for the first option, the other three options there creates a place to receive uploads and also input the "weekly transportation costs". If that is not the expected behavior, please let us know the expectation.
![image.png](https://images.zenhubusercontent.com/5fcebe3c076e6aaed83693fb/de479e0c-e5f4-4d6a-a227-b1bc286b65f7)

**Comment by HRAGANBC** [comment]
Copy of SABC Policy Manual - this exception / appeal type IS needed for PT

This will need a new ticket to re-add the Additional Transportation allowance question into the PT application, and to add the corresponding variables into the workflow, similar to however it is reflected in PT workflows. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODdiQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b950f38300423b35d272d802a5a5aa32230ccc20/image.png)

**Comment by CarlyCotton** [comment]
FT & PT - question/workflow:

- [ ] Same initial question for "Additional transportation cost" with Yes/No radio dial
- [ ] "Which of the following" multiple option radio dial still the same.
- [ ] Supporting document upload feature
- [ ] "Please estimate your weekly transportation cost during the study period" (dollar field)
- [ ] This will generate an exception request to the Ministry
- [ ] Ministry user can view: Exception type (Additional transportation cost), Radio dial (Which of the following..), Estimated weekly cost (dollar field).
- [ ] Ministry user **Approves** the exception and transportation amount is adjusted:
**Part time:**
<img width="242" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTA4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--05b284ab10c471eabff4021f19cb3c50b99de051/image.png" alt="image.png" />
`if offeringDelivered = "onsite" && (exception is denied or exception not applied for)
then dmnPartTimeProgramYearMaximums.limitTransportationAllownace * offeringWeeks
else if offeringDelivered = "onsite" && (exception is approved)
then max(dmnPartTimeProgramYearMaximums.limitTransportationMaxAllowance,studentDataTransportationcostsEstimate) * offeringWeeks
else
  0`
- [ ] New column in dmnPartTimeProgramYearMaximums for limitWeeklyTransportationAllowanceMax (2023-2024 $94)

**Comment by michesmith** [comment]
@HRAGANBC Is Updates to the application included inthis ticket OR is this just a workflow update?

**Comment by michesmith** [comment]
@HRAGANBC This will not pass User Accessibility in content or workflos- Please lets discuss at our next review. How can we take the bourdon OFF the student for these calculations.

**Comment by HRAGANBC** [comment]
@michesmith 

Carly has some additional mock-ups for how this could be handled in a more sophisticated way and save the student from the burden of calculating themselves. However, given this is only used on exceptional basis as it is, and there is plenty of opportunity for Ministry and Student to liaise to get the numbers right, I'd like to continue down this path given it's simplest from Dev perspective for MVP.

**Comment by michesmith** [comment]
@HRAGANBC @CarlyCotton im still uncomfortable with the accessibility of this question. I will confirm the larger strategy with nino but I believe the language here or solution needs to be simplified for students.

**Comment by HRAGANBC** [comment]
@michesmith @CarlyCotton There is always the possibility of adding additional questions to support automatic calculation of these figures, and perhaps that can be done with less additional workload than I assumed. Carly already has these mockups in place that can support a grooming convo with the Devs

**Comment by CarlyCotton** [comment]
@HRAGANBC I've updated this to capture the change required in the application form and created two new tickets to address the actual calculations in FT & PT. This is to support getting the work started and split off the assessment piece as it's in different places when we get to that. Do we want some of the additional context in this ticket on the Ministry Exception screen or can we expect that they know what to do with the data? (Or do we do some calculation to be presented to them in their view)

**Comment by HRAGANBC** [comment]
@CarlyCotton 

I don't think we need to provide that info to Ministry staff through the interface - that's something that will always be decided by the Appeals team, and I'm comfortable defering them to an Ops manual type thing for this level of detail. I think this is ready for grooming & implementation so have moved to lather

**Comment by michesmith** [comment]
@Joshua-Lakusta can you please add some basic form validations.

**Comment by CarlyCotton** [comment]
@michesmith what form validations are we wanting on this? length of input? just "required"?

**Comment by Joshua-Lakusta** [comment]
I updated to add content for the questions in the AC's and added validations of the numerical entries in the forms.

**Comment by andrewsignori-aot** [comment]
Thanks @Joshua-Lakusta for the update.
@CarlyCotton that was raised during the grooming.
The idea is that we are pretty behind in any UI validations for the Student Application.
It would be good if every new field had some validation. When unknown or not clear we can have some ballpark idea around it.
For instance, for distance, it probably will never be negative, it may or may not have decimals and it probably has a limit. If no limit is clear from policy we can have something in place.

**Comment by sh16011993** [comment]
As per conformation from @Joshua-Lakusta , the validation for weekly transportation cost is: 0 <= cost <= 9999.

**Comment by lewischen-aot** [comment]
It's been confirmed that the Additional Transportation Costs questions (this story) also apply to PT applications.
