### ISSUE TITLE
Create Release Strategy

### ISSUE THREAD

**Issue by andrewsignori-aot** [bcgov/SIMS#1719]
Create the release strategy for the CI/CD.
Currently, while building the application, a number is associated with the generated images for Openshift but the repo is not tagged, which makes it harder to keep the code in sync with the proper Form.io and Camunda definitions. Besides that, we need to version the deploys to TEST to allow us to better track the bugs and features between the TEST deployments right now and on PROD in the future.

**Comment by ann-aot** [comment]
https://github.com/bcgov/SIMS/pull/1814#issue-1626452437
