### ISSUE TITLE
Institution User can View Read Only BCeID Information on account set up

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#172]
**As a** *(Institution User)* **I want** *( want to view the Read-Only Business BCeid information, So That *(I can confidently ensure that SABC has the correct information.

**Additional Context**
- The information from Business BCeID includes Given Names, Last Name, and Institution
- When Business BCeID information is updated, then the information will be updated on the SABC account).- Another User Story
-The information from Business BCeID is viewed as read-only.

**Acceptance Criteria**
- [x] (The Institution User), When (has been redirected to the SABC Site after authentication, Then they can view the information that has been received from the Business BCeID site (First Name, Last Name, and Legal Institution Name (NOT GUIDs)
- [x] Given (The  Institution User has been redirected to the SABC Site ), When (they are viewing the Business BCeID information) Then, this information is there but it greyed out and may not be updated.

Technical Tasks 
--------------------------------------------------

- [ ] Create webservice call to retrieve additional info (SOAP Client)
- [ ] Display required info
- [ ] ...
- [ ] ...
- [ ] ...
- [ ] ....

Reference Docs
--------------------------------------------------
https://github.com/bcgov/ocp-sso/wiki/3.2-Identity-Provider-Attribute-Mapping

**Comment by andrewsignori-aot** [comment]
Please find below some documentation for BCeID Attribute Mapping

![image.png](https://images.zenhubusercontent.com/5fcebe3c076e6aaed83693fb/8fe2b927-6ce2-4278-aa11-4f8572c17877)
Source: https://github.com/bcgov/ocp-sso/wiki/3.2-Identity-Provider-Attribute-Mapping
