### ISSUE TITLE
E2E/Units Tests - Expand the API E2E Tests - Notes/Config

### ISSUE THREAD

**Issue by andrewsignori-aot** [bcgov/SIMS#1725]
Added E2E Tests to the below controllers for all methods.
- Notes
- Config

**Comment by dheepak-aot** [comment]
Test run on Github actions

![image.png](https://images.zenhubusercontent.com/60e72aa247c95cd873ed8ce1/0b83a2f8-74c8-473c-8c76-e946ac29f11e)

![image.png](https://images.zenhubusercontent.com/60e72aa247c95cd873ed8ce1/2bf96efc-8ac1-43f3-813f-7d9a470d11c6)

![image.png](https://images.zenhubusercontent.com/60e72aa247c95cd873ed8ce1/45572f2d-b0eb-4652-b587-f5406f4d5023)

![image.png](https://images.zenhubusercontent.com/60e72aa247c95cd873ed8ce1/67ddc4e6-48a9-46dc-99cc-c167a2cc1ad2)
