### ISSUE TITLE
Upgrade Vuetify to Release Version

### ISSUE THREAD

**Issue by andrewsignori-aot** [bcgov/SIMS#1730]
- Upgrade Vuetify to most recent release version ([currently 3.1](https://github.com/vuetifyjs/vuetify/releases/tag/v3.1.0)).
- Check if the [v-data-table](https://next.vuetifyjs.com/en/api/v-data-table/) is fully functional and can replace the current PrimeVue component.

**Comment by ann-aot** [comment]
1. implemented `v-datatable-server` for location program. 
2. search option is not available as of now, so we are using the existing implementation.
4. we are restricting `All` option in the pagination in the API.  -> planning to work on it in the feature tickets if the new release does not any custom pagination option.
