### ISSUE TITLE
Update Student Gender field labels to meet B.C. Government Standards

### ISSUE THREAD

**Issue by hellolynn-tbtb** [bcgov/SIMS#1740]
**Question**
from Lynn

- [ ] Confirm our use of Gender - why do we need to ask it? Do we get this info from Services Card?
- [ ] What does the Tool tip Say?
- [ ] Where should we put the tool tip?

**Additional Context**
BC Government Standards for Gender](https://www2.gov.bc.ca/assets/gov/government/services-for-government-and-broader-public-sector/information-technology-services/standards-files/312_gender_and_sex_data_standard.pdf)

- Before Gathering New Data Consider if you need to collect personally identifiable information:
• Is the information necessary for a government program or initiative?
• Can you provide services without collecting this information?
• Should the collection of information be done in consultation or collaboration with representatives from the relevant communities? 

**Context**
Need to bring our gender field labels up to B.C. Government standards. This work likely requires database changes.

**Currently in SIMS:**

- Male
- Female
- Unknown
- Diverse

 **From BC gov standards, should be:**

- Man/Boy
- Non-binary
- Women/Girl
- Prefer not to answer

**Identified Pages that require updating:**
- Student create account form (BCSC)
- Student create account form (BCeID)
- Student profile
- Student profile in application
- Ministry viewing student profile
- Institution viewing student profile

## Acceptance criteria
- [ ] Change labels to bc gov standards (listed above), and ensure listing gender in alphabetical order
- [ ] Confirm it is updated in all places that indicate gender
- [ ] Add tooltip to explain why we collect gender

**Comment by michesmith** [comment]
Duplicate #2831
