### ISSUE TITLE
Bulk Offerting Upload failing to link offerings to an approved program

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#1741]
The issue related to the Bulk Offering Template (attached here) which is failing to properly link the offerings to an approved program. 

When the Bulk Upload template is uploaded into SIMS, an error message is generated saying the program (or specifically the Program Code) used in the template doesn’t exist in our system. 

Here is the spreadsheets and word doc containing scenarios that the tester was working with. 
[https://app.zenhub.com/files/319429847/d3ce1b64-5f88-44a5-a899-c206be1dac0c/download](https://app.zenhub.com/files/319429847/d3ce1b64-5f88-44a5-a899-c206be1dac0c/download)
[Bulk Offering Upload - DINS.csv](https://github.com/bcgov/SIMS/files/10758835/Bulk.Offering.Upload.-.DINS.csv)

The user experienced the error with the following programs: 

DINS:
1.	Institution user: Ask Jason
2.	Danielle's INst, Danielle Institute - Victoria - designated
3.	BC Public, Institution code: DINS
4.	DI Tech 100, program code: DIT1 - pending status

Screenshot of error:
![image.png](https://images.zenhubusercontent.com/6398d78b550c6ab79f2d32ac/6bd17d0f-9d40-448c-b970-928bab48c436)

**Comment by andrewsignori-aot** [comment]
The program code required seems to be the SABC Program code, as stated on the spreadsheet, and it seems to be missing on the program, as shown below.
Is it not the case that the wrong field was used?
Maybe the content can be adjusted to make it clear.

![image.png](https://images.zenhubusercontent.com/5fcebe3c076e6aaed83693fb/6dbc5789-c3e4-4e90-87ca-5c0a1b252090)

![image.png](https://images.zenhubusercontent.com/5fcebe3c076e6aaed83693fb/a929de42-08f1-404a-9b2b-2507c6b0dc86)

**Comment by JasonCTang** [comment]
Confirmed that Signori's theory was correct and not a bug afterall.  Closing ticket.
