### ISSUE TITLE
Non-deductable Overawards 

### ISSUE THREAD

**Issue by hellolynn-tbtb** [bcgov/SIMS#1745]
QUESTION: Hugh Confirming that I can Close this ticket?

## Context
Update the ministry overawards page. 

- Add non-deductible overawards
- A notes area

## Acceptance Criteria
- [ ] Add a card for non-deductible overawards balance
- [ ] In "add manual record" modal, add a checkbox "apply this to a non-deductible overaward balance" -- and show only if CSLF/CSLP
- [ ] In "overaward deductions" table, add a new column to display "Non-deductible" and "Deductible"
- [ ] Update content as per figma

**Comment by HRAGANBC** [comment]
Confirmed with SABC Policy (as of August 2, 2023) that SIMS will **not** include non-deductible OA whatsoever. 

This means that **all** OA amounts, for all funding types, will be ignored altogether if the amount for the individual OA is less than $250. (Currently this logic is applicable to CSL overawards, but is being extended to BCSL as well)
