### ISSUE TITLE
Handling full time BCSL lifetime and federal maximums

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#1761]
**BCSL Lifetime Maximum**
The student's cumulative full-time BCSL awards received over a lifetime need to be tracked by SIMS and identify when the student has hit the full-time BCSL Lifetime Maximum.

This will require some calculations at the time of e-Cert generation to determine if the current disbursement will cause the student to hit the maximum.  If it will, then it will be necessary to reduce the award amount accordingly so that the final total exactly equals the full-time BCSL lifetime maximum that is in effect for that program year.  

Once the maximum is hit, a restriction will be applied to the student. All subsequent disbursements will effectively zero out the full-time BCSL award amounts (and all BC funding) at the time of e-Cert generation.

Restriction applies only to full-time BCSL as part-time maximums follow completely different rules.

**Federal lifetime maximum changes**
Federal lifetime maximum restriction codes impact Full Time funding only.  The actions for the following federal restriction codes need to be modified to stop full time disbursements only, allowing part time funding to proceed without impact. 

Codes:
AV, 5, 7 and 9

**Acceptance Criteria for Federal lifetime maximum**
- [x] Modify actions for the codes (AV, 5, 7, 9) to stop full time disbursements only. (Remove "stop part time" part of action)
- [x] Perform Database Update together with the addition of a new restriction for BCSL lifetime maximum ticket #1761

**Acceptance Criteria for BCSL lifetime maximum**
- [x] Ensure that the restriction (to be created) has only `Stop full time BC funding` action.
- [x] Consider only full-time BCSL for the maximum calculation but once the restriction is in place, all BC Funding is blocked. This is because the grants can only be awarded to students who are eligible for Loans. 
    - When there are two disbursements, the BCSL is part of the second one. The system should determine the total BCSL for the current and past applications, even if the current disbursement is for the first disbursement of an application with two disbursements.
- [x] The amounts used for maximums can change and need to be stored within a program year. If a reassessment of a past application occurs, the maximum values that were in effect for the program year of the application are still in effect. The values will never change in the middle of a program year.
    - There are three different categories for maximum (PD/non-doctorate/doctorate) but the system should consider all as always the same, hence 
just one maximum configuration is needed and only one provincial restriction is needed.
    - Create a new column `max_lifetime_bc_loan_amount` on `sims.program_years` table to store the BCSL max lifetime amount. `(max_lifetime_bc_loan_amount is 50,000CAD for all program year now)`
- [x] Check the restriction following the below order:
    - Check for any “Stop full-time disbursement” actions;
    - Check for “Stop full-time BC funding” action;
    - Check for BCSL maximum limits and apply restriction, if needed.
first 2 orders are already in place, as part of ticket, 3rd order need to be placed after first 2

**When a disbursement causes the student to hit the lifetime maximum:**
- [x] total disbursed BCSL from legacy(SFAS) +total disbursed BCSL from SIMS + current BCSL value >= programyear life time maximum
- [x] The award is reduced so the student hits the maximum value exactly.
    - New columns must be added to `sims.disbursement_values` to record the “reason” and the amount reduced for BCSL and BC grants.
        - `restriction_amount_subtracted`
        - `restriction_id_subtracted`
- [x] Update all BC funding values on the current disbursement populating the newly added columns `restriction_amount_subtracted` and 
`restriction_id_subtracted`.
    - Add the restriction to the `sims.student_restrictions` table.

**When a disbursement happens and the `Stop full time BC funding` is already in place:**
- [x] Update all BC-related funding awards (BCSL and grants) to have the `restriction_amount_subtracted` to make the effective value of the award to be defined as 0 (zero). For instance, current award effective value calculation is at $500, make the `restriction_amount_subtracted` as -$500 to make the effective value as 0.
- [x] Update `the restriction_id_subtracted` with the restriction id that has the `Stop full time BC funding` associated with it. _Any restriction can have the action `Stop full time BC funding` associated with it, not only the one related to BCSL._

- [x] Add placeholder for new restriction in the student `account activity` page

**Comment by ann-aot** [comment]
Provincial Restriction Code `BCLM`, `"BC Lifetime Maximum Reached"` and the action should be to `stop BC Fulltime Funding` and the the notification type is `error`

**Comment by ann-aot** [comment]
restrcitionCateogory for BCLM is `Other`

**Comment by ann-aot** [comment]
total disbursed BCSL from  sfas_application is querying with last_name, dob and sin. But if the student had a temporary sin in SFAS and in our system his/her sin is a permanent one, then we can't match the details. (There is a possibility of missing the details from SFAS)

**Comment by ann-aot** [comment]
This ticket is not handing same e-cert having multiple disbursement of a same student. below is one scenario, Edge case but a possible scenario.
Depending on certain circumstances we may be processing at the same time 2 disbursements for the same students, for instance, assuming that we have two applications as below.

Application A: Jan, 1st - April, 30th
Application B: May, 1st - July, 31st.
Wonder that Application A can be reassessed near the offering end date on April, 30th and it may be having the e-Cert generated on May, 1st, which will lead both to be part of the same e-Cert file.

The e-Cert SQL query will get both records where no BCSL restriction will be in place, but then the first one will be adding the BCSL restriction and the second one must be aware of it to stop the BC funding.

When we have 2 records for the same student, we may need to have a way to refresh the restrictions in a way that the second disbursement will not have the BC fundings disbursed.
