### ISSUE TITLE
Move MSFAA association from Application to Disbursement

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#1780]
Currently MSFAA is associated to the application, but we need to associate it at the disbursement level because the number can change in the middle of an application.

Currently, when an application is submitted and there is an active MSFAA in place, SIMS associates the exisitng MSFAA to the application. This needs to change to being associated with the disbursement.

When a new MSFAA is issued, it needs to be reassociated with all pending disbursements.

**Additional Context**

No change: an ECERT does not get generated when the student does not have a valid MSFAA.
No change: an application is submitted and the student does not have an active MSFAA (including never had a MSFAA before), a new MSFAA number is generated.
No change: Separate MSFAAs for PT and FT
No change: MSFAA is sent with every ECERT

**Acceptance Criteria**
- [x] Create new field to store the MSFAA number in the disbursement table.
- [x] Database migration to copy the MSFAA number to the new column in the corresponding disbursement record.
- [x] Drop the MSFAA number column from the application table.
- [x] Adjusting the workflow to work based on the new table structure. (Read and write MSFAA number to/from the disbursement table instead of application table)
- [x] Ensure that MSFAA is still generated during assessment workflow execution and the NOA is still displaying the MSFAA number.

**Comment by dheepak-aot** [comment]
The association of MSFAA to an application was based on (it is assumed that offering Intensity is matched for all the given points)

1. Check if the student has either a _**signed MSFAA number where the date_signed is not older than 2 years(730 days) and with cancelled_date as null**_ or
an _**MSFAA number which is pending to be signed with cancelled_date as null**_
2. If the above conditions does not return an MSFAA number, then check for the most recent study period for which the student submitted an application and the application is in completed status( atleast one enrolment is confirmed) and the study period end date is not older than 2 years and if the condition is satisfied, get the MSFAA number of that application.
3. Even if point 2 did not return an MSFAA number, then create a new MSFAA number.

With the implementation of this story, where the association of MSFAA is with the disbursement and not with the application, the point 2 was slightly modified. @JasonCTang that is what we discussed over the call.

Modified point 2.
**_If the point 1 does not return any MSFAA number, check for the most recent study period who's disbursement is sent and and the study period end date is not older than 2 years and if the condition is satisfied, get the MSFAA number of that disbursement._**
