### ISSUE TITLE
Updating NOA to handle new MSFAA being issued.

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#1781]
**As a** *(User Type/Persona)* **I want** *(Feature/enhancement)* **So That** *(Value, why is this wanted, what is the user trying to accomplish)*

**Additional Context**
- enter text here
- enter text here

**Acceptance Criteria**
- [ ] Given (Context), When (action carried out), Then (expected outcome)
- [ ] Given (Context), When (action carried out), Then (expected outcome)

**Comment by CarlyCotton** [comment]
@HRAGANBC - this looks to be completed but I'm unable to confirm in Test. Can you confirm this is done?

**Comment by HRAGANBC** [comment]
@CarlyCotton  Got confirmation from Devs this is done. We will be able to see it ourselves in TEST later in the MSFAA testing process in a few weeks.
