### ISSUE TITLE
 Interface for reissue MSFAA button for Ministry Staff

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#1782]
**As a** *(User Type/Persona)* **I want** *(Feature/enhancement)* **So That** *(Value, why is this wanted, what is the user trying to accomplish)*

**Additional Context**
- enter text here
- enter text here

**Acceptance Criteria**
- [ ] Given (Context), When (action carried out), Then (expected outcome)
- [ ] Given (Context), When (action carried out), Then (expected outcome)

**Comment by CarlyCotton** [comment]
Ministry Re-Issuing MSFAA Number #1759
- Reissue MSFAA - Part 1 - New SIMS API Endpoint #1928
- Reissue MSFAA - Part 2 - NOA UI Changes #1936
- MSFAA UI Changes for NOA - Fix form.io definition#1939
Add role to restrict MSFAA Reissue #1964

FIGMA shows button and modals for reissue process by Ministry user.

Cannot view button shown in FIGMA as Ministry user - not sure if keycloak group required or not implemented?

**Comment by CarlyCotton** [comment]
@HRAGANBC - this looks to be completed but I'm unable to confirm in Test. Can you confirm this is done?

**Comment by HRAGANBC** [comment]
@CarlyCotton - yes, looks like this is down. Thanks for tracking down related tickets. 

I will pass this off to Josh, now, to create some test scenarios related to it. This is not something Buiz side can test on our own - we'll need support from Devs to change database values to 'cancelled' which then allows the 're-issue' feature to be used.
