### ISSUE TITLE
Database Encryption Solution- EDW

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#1784]
**User Story**
 

**Describe the task**
A clear and concise description of what the task is.

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by michesmith** [comment]
Devs @ Jason tang  please prioritize which Release its needed for or trash if duplicate or no longer needed

**Comment by sslaws** [comment]
Please add requirements if still required.

**Comment by michesmith** [comment]
@HRAGANBC we want to confirm with you on approach

**Comment by michesmith** [comment]
@HRAGANBC we want to confirm with you on approach

**Comment by ninosamson** [comment]
Closing ticket as alternative technical integration has been identified.
