### ISSUE TITLE
Enable Student Profile Tab for Institutions

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#1788]
**As an** *institution users* **I want** *to view Student Profile information*

**Additional Context**
https://www.figma.com/file/9Om2tzLAVEoMQrjmrH4fhu/MOD-SIMS?node-id=11337-140498&t=K5C151j6g3EQtqRi-0

**Acceptance Criteria**
- [x] Convert Form.io to Vuetify.
- [x] Build E2E tests.

**Comment by dheepak-aot** [comment]
The AC `Enable authorization paths for Student Profile Tab for institution users` is removed as it is scoped as centralized solution to be implemented in #1830

**Comment by dheepak-aot** [comment]
As discussed with team and @JasonCTang , the restriction badge that indicates if a student has any active restrictions is not included in the student details page on institution side as it may not be accurate/misleading to show a no restriction badge to a student who may be having a verification restriction which institution does not have access to.

![image.png](https://images.zenhubusercontent.com/60e72aa247c95cd873ed8ce1/95f6bfe6-5ec9-400e-a9fc-2899ef6ac283)

![image.png](https://images.zenhubusercontent.com/60e72aa247c95cd873ed8ce1/ea176fda-bc30-49cb-97a0-dc2d942bf479)
