### ISSUE TITLE
Dependabot failures

### ISSUE THREAD

**Issue by dheepak-aot** [bcgov/SIMS#1806]
**Describe the task**
Currently dependabot is failing due to the following issue

![image.png](https://images.zenhubusercontent.com/60e72aa247c95cd873ed8ce1/199033fc-a5fd-4d99-96e3-c06bb438b630)

![image.png](https://images.zenhubusercontent.com/60e72aa247c95cd873ed8ce1/a9c9fccd-2bd6-452e-8d8e-2164b6e587aa)
**Acceptance Criteria**
- [ ] fix dependabot issue

**Comment by andrewsignori-aot** [comment]
Merged the PRs for the security alerts.

![image.png](https://images.zenhubusercontent.com/5fcebe3c076e6aaed83693fb/5889ae89-8651-4043-84bb-58456be08111)
