### ISSUE TITLE
Fix css style for dividers (<hr />)

### ISSUE THREAD

**Issue by andrepestana-aot** [bcgov/SIMS#1807]
The HR is there but its style is set to be transparent:

![image.png](https://images.zenhubusercontent.com/601c6b4f5322cf5c519d503f/6e91ed10-5551-43a1-8d9f-cb5a4bf934ab)

![image.png](https://images.zenhubusercontent.com/601c6b4f5322cf5c519d503f/cee33e5a-8d39-4c89-ba81-5faab5ac9e76)

It's needed to check why it changed to transparent and make it visible again.

**Comment by ann-aot** [comment]
As discussed, keeping the PR as it is and created a ticket with the fix https://app.zenhub.com/workspaces/student-information-management-system-5fce9df5aa1b45000e937014/issues/gh/bcgov/sims/2359 to implement after the release signoff
