### ISSUE TITLE
Handling Loan Agreements without a signed date from SFAS 

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#1812]
Some students in SFAS have a Loan Agreement instead of an MSFAA.  The Loan Agreement was the paper version of the MSFAA and it lacks signed data information.  They are accepted in place of an MSFAA and handled in the same manner.  

They will need to be read from the SFAS SIMS Bridge file and handled as if it were an active MSFAA.

**Additional Context**
- Need to confirm if these are included as MSFAA data in the bridge file. 
 - **They are currently not included, but Harry does not believe there are any active ones left.  He will look into that and get back to me.**

- If Harry provides the as if they are MSFAAs and chooses a date as the "signed" date, we don't have to handle these specificaly.
 - **Harry says Loan Agreements do actually have a signed date.**

- Does the MSFAA number and the signed date in the bridge file reliably indicate an active MSFAA.
  - **No, SFAS bridge file sends all data, but we the MSFAA record and all the student's application records, and we will be able to calculate it based on their last active study end date.**

- Are the MSFAA records associated with the individual (and not the application) in the bridge file? 
 - **We read MSFAA records from the bridge file into a table in SIMS but do not do anything with them yet. (ie, we do not attached the MSFAA records to any students in SIMS)**

- Need to identify when generation of new MSFAAs will be cut off in SFAS, as well as when we no longer need to continue "syncing" with MSFAA statuses from SFAS (Maybe it's just a one time initial load?)
  - **It would be the end of the next program year following the program year where SFAS stops accepting applications.**

**Acceptance Criteria**
- [ ] 
- [ ]

**Comment by michesmith** [comment]
Harry confirmed there are no paperbased loan agreements
