### ISSUE TITLE
Analysis Ticket for #1743 - Allow institutions to change the details of a program offering for a single student application

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#1820]
Answer questions and determine the breakdown of tickets for $1743

**Comment by guru-aot** [comment]
Analysis on Edit Program Offering for Completed student application:

**Assumptions**

1. Student can only request the change of offering for the particular application to the Institution.
2. The application the offering change is requested by the student should be in completed status and not in any other status(Archived or in progress statuses). Applications other than the completed status will go through alternate flows or will not be considered for change.
3. Institution can view and request the change from the student in the "Report a completed application change" in the Home side bar menu of the particular institution location.
4. On clicking the "Report a completed application change", it should open a screen with 2 tabs. One with Available to report and another unavailable to report of the completed applications.
    - The available to report tab will contain the un archived completed application, which are in completed status.
    - The unavailable to report tab will contain the archived application/ the application that have the offering change in progress, this is to report the student back if their application cannot be changed.
5. The new offering can be created by the institution from the add offering page or the add program and the add offering page. The offering can private and be for a specific student(if its only specific for the particular student). 
6. For the "Available to report a change" tab, there needs to be a button to view the existing offering and to attach the new offering to the application, similar to the report a change screen.
7. On assigning the new offering to the application and submitting.
    - The institution should get a card stating "The change of offering for the application number "XXXXXXXXX" should be approved by the ministry" and the application moves to the "Unavailable to report tab"
    - The student sees the application progress bar as "In progress" and will get a grey banner stating "The change of offering is in progress"
    - The ministry user will

**Comment by guru-aot** [comment]
https://github.com/bcgov/SIMS/issues/1900
