### ISSUE TITLE
Review Restrictions Notifications

### ISSUE THREAD

**Issue by ann-aot** [bcgov/SIMS#1828]
1. The function `getRestrictionsForNotifications` is checking for `actiontype` instead of `notificationType`
![image.png](https://images.zenhubusercontent.com/608872f7d0d25cdfe8dab75d/0b603074-432e-4e74-a6d2-23a42e029287)
2. As per the story https://app.zenhub.com/workspaces/student-information-management-system-5fce9df5aa1b45000e937014/issues/gh/bcgov/sims/1453, system-generated restrictions on student account  WHERE notification type != no effect should only be notified, and the example are Application submit (SINF), institution report change (WTHD), etc..

But as per of restriction table `WTHD` has `notification_type = "no effect"`. is this any configuration issue? or should we not notify the student when there is a `WTHD` added to the student
![image.png](https://images.zenhubusercontent.com/608872f7d0d25cdfe8dab75d/fa4a2b0a-e373-4bf4-a820-84749da2505b)

3. When SINF is added to a student, student is notified, but its a verification type restriction (confirm with Jason)

**Comment by JasonCTang** [comment]
Reviewed with Shashank
