### ISSUE TITLE
UX/UI for Ignore Restriction - Bypass List

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#1862]
**User Story**
As a Ministry user, I need the ability to Ignore restrictions through the interface, as well as see some limited historical details of any ignored restrictions 

**Acceptance Criteria**
- [x] Build a page for when the Ministry selects an application and selects "Restrictions Management" from the left panel.
- [x] Applications are eligible for this ignore restriction bypass once they have been submitted and have an application number.
- [x] Ignore the content section in the mockup below, do not include.
- [x] Change the heading to sentence case "History of bypassed restrictions" to align with other pages. 
- [x] In the "Restriction Type" column, please use the `restriction_category` for the fields.
- [x] Include "Restriction status" to reflect the current status of any restriction in the table.
- [x] Disable the action button for any Resolved restrictions
- [x] Include "Bypass status" column to reflect the status of the bypass: Active / Removed

**Technical**
- [x] Not available for Public Institutions.
- [x] Create a new link in the left menu named "Restrictions Management".
  - [x] Disable the link for draft applications.
- [x] Create the new list "History of Bypassed Restrictions" (use Vuetify table).
  - [x] No server-side pagination needed.
  - [x] Order the list DESC by creation date (most recent entry on the top).
  - [x] "Restriction type" and "Restriction code" from `sims.restrictions`, and "Restriction status" (is_active) populated from `sims.student_restrictions`. Use the same formatting and chip status from the restrictions page.
  - [x] Buttons related to modals present in the #3691 ticket should be present but disabled.
- [x] Suggested API endpoints
  - `GET` aest/application-restriction-bypass/application/:applicationId
- [x] E2E tests
  - Get bypasses 
    - Should get a list of restrictions bypasses when there are restrictions bypassed for a Student Application.

**Supporting Mockups**

**Ministry 'Application Restrictions' Page**
<img width="1063" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnVQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4c08c7da7d2e878ef94d640fc1e465dc9e599ca7/image.png" alt="image.png" />

**Comment by HRAGANBC** [comment]
@CarlyCotton @Joshua-Lakusta Let me know if OK with you, and we can move straight to Lather.

**Comment by CarlyCotton** [comment]
@HRAGANBC How does the ministry user access that first "Application Restriction Management" screen?

**Comment by HRAGANBC** [comment]
@CarlyCotton Added following note next to the first mockup - please dont make me adjust the mockups themselves :) 
_Ministry should be able to access this page by selecting an application, and then selecting "Application Restriction Management" from the left-hand panel along with "Assessments"; "Parent 1 Info"; "Parent 2 Info", etc..._

**Comment by CarlyCotton** [comment]
@lewischen-aot Based on questions raised to me re content, I've added two ACs to clarify the content expectations of the page:
- [ ] Ignore the content section in the mockup below, do not include.
- [ ] Change the heading to sentence case "History of bypassed restrictions" to align with other pages. 

FYI @dheepak-aot @Joshua-Lakusta

**Comment by dheepak-aot** [comment]
@CarlyCotton there was a question raised by @andrewsignori-aot in PR on the data that is displayed in the `Restriction type` column of the data table. The question is, for the `Restriction type` column are we expected to map the restriction category? as per the image, because the restriction type according to us is `Federal | Provincial`

<img width="628" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODhFQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c363499a051c0cd9b4436f2bdfd3d1d03bb86f23/image.png" alt="image.png" />

**Comment by CarlyCotton** [comment]
@dheepak-aot Can we use `restriction_category` for that column? It tells us if it's Federal (which is critical that we know about) and a little more info about the type of Provincial restriction. 

FYI @andrewsignori-aot @lewischen-aot

**Comment by lewischen-aot** [comment]
Thanks @CarlyCotton for adding the additional ACs, and we certainly can use `restriction_category` for column "Restriction Type" to give a little more info about the type of Provincial restriction.

**Comment by CarlyCotton** [comment]
@lewischen-aot I've added some biz ACs based on some conversation today.

FYI @andrewsignori-aot @Joshua-Lakusta
