### ISSUE TITLE
Review PT Integration Specifications and confirm our files are compliant.

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#1864]
**Describe the task**
Review the finalized PT Integration Specs document and confirm the following files we are already creating are compliant.
- [x] Send PT MSFAA Send File to Finastra
- [x] Receive and process the PT MSFAA Received File
- [x] Send new PT e-Cert file to Finastra
- [x] Receive and process new e-Cert Feedback file

**Additional context**
- [BC Part-Time MSFAA Sent File](https://app.zenhub.com/files/319429847/f277e264-b3ca-4a8a-8d2e-0a9ec548ec02/download)
- [BC Part-Time MSFAA  Received File](https://app.zenhub.com/files/319429847/805e87c6-243f-4b07-be93-bbb15b1efdf9/download)
- [BC Part-Time E-Cert File V 3.0](https://app.zenhub.com/files/319429847/fbeefb54-0e86-4126-a08b-e8b9aa181bfb/download)
- [BC Part-Time E-Cert Feedback File V 1.3](https://app.zenhub.com/files/319429847/358b6ec8-69b0-420c-bb85-03c7b06d24cf/download)

**Acceptance Critera**
- [x] Review finalized specs and compare to the files we are currently generating.
- [x] If we discover that there have been changes to the file format, then modify the files to the new specs. (It's possible there will be zero changes)
- [x] Perform analysis of receiving and processing new e-Cert Feedback file for Part Time.
- [x] Perfom a knowledge transfer session with business area to demonstrate where in the process the files are generated. 
- [x] Review receive and process of the e-Cert Feedback file Part Time
- [x] Save files generated and received as part of the test with Finastra into our Teams channel
- [x] Ensure the country is converted to CAN when Canada for the part-time e-Cert that has a 4-character max field for country information. Other countries will be truncated at 4 characters, for instance, "United States" will be sent as "Unit"

**Comment by andrewsignori-aot** [comment]
## MSFAA Sent File

Questions
- As per the documentation "Gender" is expected to be sent as "Borrower's Gender (F or M)". SIMS is actually sending it as below. Is the type "O" still supported?
    - males: M
    - female: F
    - Not male or female: O

**Comment by andrewsignori-aot** [comment]
## e-Cert File

Questions
- "First Name" is stated in the documentation as mandatory but it will not be true for mononymos names.

Changes
- Originator updated to "NEW PT ENTITLEMENT".
- Added sequence number to the header. It was already present for full-time but not for part-time.

**Comment by andrewsignori-aot** [comment]
## e-Cert Feedback File

Questions
- SIMS only saves to the DB the errors 1-5 from the file and no further processing is happening right now. Is there a missing feature or the intention is just to have the errors saved for a possible investigation?

Points to be clarified
- SIMS does not perform any validation on the data received in the file. The file contains all the data form the generated e-Cert plus error codes. The only information consumed from the files is the error code and the only verification being performed is related to the received header code.
