### ISSUE TITLE
Fix Sonarcloud high security issues

### ISSUE THREAD

**Issue by andrewsignori-aot** [bcgov/SIMS#1867]
Sonarcloud started to report high-security issues mostly about the docker files and showed the repo with an error.
The same issue was already resolved on a previous PR and now we need to investigate and possibly apply the same fix globally (https://github.com/bcgov/SIMS/blob/main/sources/packages/backend/workflow/Dockerfile.dev).

![image.png](https://images.zenhubusercontent.com/5fcebe3c076e6aaed83693fb/dc9e8773-7b27-4afa-8e74-798cb7321103)

- Copying recursively might inadvertently add sensitive data to the container. Make sure it is safe here.
- The node image runs with root as the default user. Make sure it is safe here.

**Acceptance criteria**
- [ ] Review Sonarcloud and already in place fix to possibly apply the solution and eliminate all related issues present on the link https://sonarcloud.io/project/security_hotspots?id=bcgov_SIMS&branch=main&resolved=false&types=SECURITY_HOTSPOT
- [ ] If more high-security issues are present, create tickets to have them all fixed or handled.

**Comment by andrewsignori-aot** [comment]
Moved back to in progress to change the user ID running the PROD images.

**Comment by sh16011993** [comment]
The following links are a good read pointing to the fact that OpenShift does not run the containers as a root user:

https://number1.co.za/openshift-will-not-run-your-container-as-a-root-user/
https://d-nix.nl/2020/07/running-a-container-as-non-root/
https://opensource.com/article/18/3/just-say-no-root-containers#:~:text=OpenShift%20is%20Red%20Hat's%20container,run%20without%20ever%20being%20root.
https://dev.to/ksingh7/allow-containers-to-run-as-root-on-openshift-4-hack-3gp7
https://docs.openshift.com/container-platform/4.11/openshift_images/create-images.html#use-uid_create-images

**Comment by sh16011993** [comment]
Moved back to in progress to remove the redundant nonroot user from the Dockerfiles.
