### ISSUE TITLE
Clean npm packages warnings

### ISSUE THREAD

**Issue by andrewsignori-aot** [bcgov/SIMS#1869]
Review the below npm warning and upgrade the packages accordingly.

- [ ] npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
- [ ] npm WARN deprecated har-validator@5.1.5: this library is no longer supported
- [ ] npm WARN deprecated formidable@1.2.2: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
- [ ] npm WARN deprecated @types/keyv@4.2.0: This is a stub types definition. keyv provides its own type definitions, so you do not need this installed.
- [ ] npm WARN deprecated @types/jwt-decode@3.1.0: This is a stub types definition. jwt-decode provides its own type definitions, so you do not need this installed.
- [ ] npm WARN deprecated @types/bull@4.10.0: This is a stub types definition. bull provides its own type definitions, so you do not need this installed.
- [ ] npm WARN deprecated superagent@6.1.0: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>. Thanks to @shadowgate15, @spence-s, and @niftylettuce. Superagent is sponsored by Forward Email at <https://forwardemail.net>.
- [ ] npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
- [ ] npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
- [ ] npm WARN deprecated class-transformer@0.3.2: This release contains a breaking change from 0.3.1 but otherwise functions properly. Please read the changelog on Github to learn more.

**Comment by JasonCTang** [comment]
Confirmed all NPM warnings have been cleared.
