### ISSUE TITLE
Implementing resiliency measures

### ISSUE THREAD

**Issue by guru-aot** [bcgov/SIMS#1875]
The listed resiliency measures make your application perform better in the case of failures. They protect your application from getting overloaded (rate limiting), and improve the performance when facing connectivity issues (timeouts, retries)

**Acceptance Criteria**

- [x]  Check all YAML for replicas and load balancing for applications, review if all pods have at least two instances or what is the best practice in BC Gov?. 
- [x]  Ensure the pod restart, bandwidth and disruption budgets are set.
- [x]  Ensure proper Documentation on all the above measures in git wiki

**Comment by michesmith** [comment]
Related ticket is #1582

**Comment by guru-aot** [comment]
Patroni podDisruptionBudget confirmed in RocketChat by BCGov Patroni team
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaXRpIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f9d390c195ee8995fe109716e0b1931eeb258bd0/image.png)

**Comment by guru-aot** [comment]
Release notes to create PDB in production manually is updated in https://app.zenhub.com/workspaces/student-information-management-system-5fce9df5aa1b45000e937014/reports/release?release=Z2lkOi8vcmFwdG9yL1JlbGVhc2UvOTQxODU

**Comment by guru-aot** [comment]
Documentation of the PDB is updated in https://github.com/bcgov/SIMS/wiki/DevOps-and-Running-the-Application#pod-disruption-budget-and-pod-replicas
