### ISSUE TITLE
Ensure that application pods terminate gracefully

### ISSUE THREAD

**Issue by guru-aot** [bcgov/SIMS#1878]
On termination, an application pod should complete all in-flight requests and terminate existing connections gracefully. This allows for restarting the pod without end-users noticing, for example when a new version of the application is deployed or
you might need to temporarily shut down your cluster for maintenance reasons

**Acceptance Criteria**
- [ ] Install the below configurations in prod environment.
https://docs.openshift.com/container-platform/4.10/backup_and_restore/graceful-cluster-shutdown.html

**Comment by michesmith** [comment]
@Guru is going to confirm if this is still needed or if this is a duplicate.
