### ISSUE TITLE
Check the container images are trusted base container images and latest

### ISSUE THREAD

**Issue by guru-aot** [bcgov/SIMS#1879]
Use vendor-provided container images where possible. Vendor images are tested, hardened, and supported. If using community-supported images, use only the images provided by the communities that you trust. There are images of unknown origin available in public registries like Docker Hub. Do not use them!

**Acceptance Criteria**
Check for possible containers in our application and check for validated images, sample given below https://stackoverflow.com/questions/48545928/how-to-validate-the-authenticity-of-docker-base-images

**Comment by JasonCTang** [comment]
Done
