### ISSUE TITLE
SIMS DB read access to external db backup team

### ISSUE THREAD

**Issue by guru-aot** [bcgov/SIMS#1883]
DB dump to extract data from SIMS.

**Acceptance Criteria**
Create a grant access or user to access only read only access to our SIMS Patroni DB

Sample code to grant access:
GRANT CONNECT ON DATABASE mydb TO xxx;
-- This assumes you're actually connected to mydb..
GRANT USAGE ON SCHEMA public TO xxx;
GRANT SELECT ON mytable TO xxx;

https://stackoverflow.com/questions/760210/how-do-you-create-a-read-only-user-in-postgresql

**Questions:**
* Do we need backup for Mongo and Redis DB ??

**Comment by JasonCTang** [comment]
Determined that because we are storing our backups in the "Backup Container" pod provided by Platform Services, our backups are automatically backed up externally by OCIO every day.  Therefore, we do not need to explicitly implement any additional external backup solution.
