### ISSUE TITLE
Approach on creating separate portal deployments wrt user types in SIMS

### ISSUE THREAD

**Issue by guru-aot** [bcgov/SIMS#1884]
Create separate portal deployments for Ministry, Institution and Student portal. 
Currently for the initial MVP release we may need to deploy only Ministry and Institution portal.
 
**Acceptance Criteria**

1. Analysis on possible changes in code base needed for configuration in env to expose routes for Ministry, Institution, student && parent/partner portal.
2. Deployment configurations required in changing the deployment yamls.

**Comment by JasonCTang** [comment]
No longer pursuing this approach.
