### ISSUE TITLE
Analysis to process assessments in the queue

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#1896]
**Describe the task**
Analysis to trigger Camunda assessment workflows using queues. Right now, most of the time, the assessment/reassessment records are created and the call to the queue happens right away. If the queue call fails or the queue is cleared there is no other attempt to start the workflow again.

**Acceptance Criteria**

- [x] Strategy to trigger the workflow for the different scenarios.
    - Student application submission.
    - Scholastic change
    - Bulk withdrawal
    - Student appeal
    - Bulk offering change
    - Application offering change
- [x] Ensure that we are not triggering the workflow multiple times for an assessment.  Whatever the duration between the scheduler runs, only trigger workflow for assessments that have not been triggered within that time period.
    - [x] On the occasion where the workflow is called twice, check how to cancel the workflow in a nice way to avoid generating an unnecessary Camunda incident.
- [x] Define how exclusive the execution of the workflow needs to be. Can we safely execute in parallel workflows for the same student for different applications?
- [x] How to handle multiple assessment records creation for the same student application? Right now some features (Student Appeals/Scholastic Standing) verify if there is already another workflow under execution for the same application [assertAllAssessmentsCompleted](https://github.com/bcgov/SIMS/blob/c5a37a92dfb602482d7e4e787ba0d78b3e3f8c43/sources/packages/backend/apps/api/src/services/student-assessment/student-assessment.service.ts). 
    - Should we allow multiple assessment records creation for the same application?
    - How the "current assessment" relationship in the applications table be updated?
    - Should we ensure that an assessment will be calculated for every single workflow?
- [x] Create an epic to group the upcoming tickets needed to have the Camunda workflow-related queues ready for production MVP as much as possible.

**Comment by andrewsignori-aot** [comment]
### New status for the assessment

- Created: when the student_assessment is created.
- Queued: when the student_assessment is queued to be executed on Camunda. Change the status to `Queued` and call the queue after, in this way, if the Camunda call fails it will retry later because the status is already set.
- In progress: when the workflow id is associated with the student_assessment.
- Completed: at the end by a dedicated worker.
- Cancelled: when the student cancels the application.
