### ISSUE TITLE
Allow Institutions User to change the program offering for a single student completed application

### ISSUE THREAD

**Issue by guru-aot** [bcgov/SIMS#1900]
As a institution user I want the ability to change the program and/or program offering for a specific student's application, so that we can avoid reporting a withdrawal for the student's current application and having them start a new one.

Creating or assigning a new offering for a single student with a completed application. 
This includes:
 - Assigning an existing or an student specific offering to a student.
    - Existing screens can be used by the institution portal to create a new student specific offering.
    - Create pages in the institution portal to have the list of completed students application to report the change of offering.
    - Once the change of offering is reported by the institution, the application should not be available to report the change of offering again, until the the student and/or ministry approves/ denies it.
- Student approving the request from institution.
   - Student should have a notification indicating that the institution has submitted a request to change their offering for a particular application. 
    - Students will be able to view the details of the offering change in their list of requests. 
    - Students should have the ability to allow or decline the request for change in offering for the application.
    - If the change of offering is allowed by the student, the application should remain not available to report the change of offering, until the ministry approves/denies it.
    - Student must check the declaration box to approve change request.  If student denies it, they do not need to have declaration box checked.
    - If the change of offering is declined by the student, the application should go back to available to report.
- Ministry approving the request from institution.
    - Ministry should have a screen to view the institution requests for the offering change for a particular application in a list.
    - Once the application list is clicked, the request and the history of the offering changes has to be shown.
    - The request will contain the application offering change requested by the institution.
    - Ministry should have the ability to approve or deny the request for the change in offering for the application.
- Student should have the ability to see the status of the application in the progress bar by banners/cards.

Analysis story is attached in the dependencies for further details.

**Assumptions**
1. Student can only request a offering change for their application to the institution.
2. Institution Private/Public can either create a new offering of assign a existing offering for the student.
3. The ministry should always approve the change in offering by the institution.
4. The offering change that triggers the reassessment should have a new assessmentTriggerType.
5. There can be a situation where the student still can request a offering a change multiple time to the institution, even after the offering change is approved by the ministry.

**Analysis on Edit Program Offering for Completed student application**

1. Student can only request the change of offering for the particular application to the Institution.
2. The application the offering change is requested by the student should be in completed status and not in any other status(Archived or in progress statuses). Applications other than the completed status will go through alternate flows or will not be considered for change.
3. Institution can view and request the change from the student in the "Report a completed application change" in the Home side bar menu of the particular institution location.
4. On clicking the "Report a completed application change", it should open a screen with 2 tabs. One with Available to report and another unavailable to report of the completed applications.
    - The available to report tab will contain the un archived completed application, which are in completed status.
    - The unavailable to report tab will contain the archived application/ the application that have the offering change in progress, this is to report the student back if their application cannot be changed.
5. The new offering can be created by the institution from the add offering page or the add program and the add offering page. The offering can private and be for a specific student(if its only specific for the particular student). 
6. For the "Available to report a change" tab, there needs to be a button to view the existing offering and to attach the new offering to the application, similar to the report a change screen.
7. On assigning the new offering to the application, with notes and submitting.
    - An entry in the application_offering_change_requests table will be entered with "Pending" application_offering_change_request_status.
    - The institution should get a card stating "The change of offering for the application number "XXXXXXXXX" should be approved by the ministry" and the application moves to the "Unavailable to report tab".
    - The student sees the application progress bar as "In progress" and will get a orange banner stating "The change of offering is in progress with information about the new offering and the option to allow or decline the new offering."
    - An email notification is sent to the student indicating that the institution has submited a change in offering on their application.
8. The student receives the email and logs into the portal and navigates to the specific application to find the banner with information about the new offering and the option to allow or decline the new offering.     
    - On allow, the banner message will change to the generic your change request is in progress banner and the request will go to the Ministry's Institution Requests for Change queue for approval or denial.  The applications remains in "Unavailable to report" in the Institution portal.
    - On declining the change:
        - The application again move to completed status.
        - The institution should see the application again in the completed application tabs.
        - The ministry should **not** see the application in the list shown when "Institution Requests -> Specific Offerings" page.
        - If additional offering change is requested again by the student and the institution creates an specific offering change, the approved offering change should be shown in the History tab for the ministry in the  "Institution Requests -> Specific Offerings -> Applications list -> click 'View request'" and the cycle continues. 
9. The ministry user will see have a side bar menu below the "Institution requests" called as "Specific offerings"
    - On click of the "Specific offerings" it should open a similar page as the study period offerings page, where the list of specific applications where the offering changes are requested by the institution and a "View" button will be present.
    - On click of the "View" button, it should open a page with "Request" and "History" panel similar to the "Student Requests -> Appeals" page.
         - The Requests will contain the offering change request from the institutions for the completed application (this in-turn shows the list of applications in "application_offering_change_requests" table with "application_offering_change_request_status" as "Pending") and will contain a "view request" hyperlink in the list.
         - The History will contain the completed successful approval done by the ministry for the particular application (this in-turn shows the list of applications in "application_offering_change_requests" table with "application_offering_change_request_status" as "Approved or Declined").
         - On click of the "view request" link it will open a page with requested change and the active offering change tabs.
    - The requested change tab will show the previous offering the student has selected during the application completed and the active offering change will have the change of offering selected by the institution.
    - Note: similar to the offering request, the status banners for the tabs "Change awaiting approval" and "Change under review" should be present. 
    - Try to reuse or edit the ViewOfferingChangeRequest.vue form for the above offering change tabs.
10. On approving or Declining the specific offering by the ministry the following behaviour should happen same.
     - The application again move to completed status.
     - The institution should see the application again in the completed application tabs.
     - The ministry should **not** see the application in the list shown when "Institution Requests -> Specific Offerings" page.
     - If additional offering change is requested again by the student and the institution creates an specific offering change, the approved offering change should be shown in the History tab for the ministry in the  "Institution Requests -> Specific Offerings -> Applications list -> click 'View request'" and the cycle continues.
11. The change in the flow other than the above for 
    - Approving the offering by the ministry are:
        - The particular application_id in the "application_offering_change_requests" table with "application_offering_change_request_status" is changed to "Approved"
        - The reassessment for the particular application is triggered.
        - Student will see the green banner status in their progress bar, with the card stating "The offering change is applied/ approved"
        - Once the reassessment is triggered the remaining disbursement and overawards calculations should happen seamlessly without any change.
    - Declining the offering change by the ministry:
        - The particular application_id in the "application_offering_change_requests" table with "application_offering_change_request_status" is changed to "Declined"
        - Student will see the green banner status in their progress bar, with the card stating "The offering change is declined"
        - No reassessment is triggered

   
**Table changes**

1.  
![image](https://user-images.githubusercontent.com/62901416/233706808-24d355e3-eb28-45d4-b253-a1a750e4d2ab.png)

2. application_offering_change_request_status Types are "Pending", "Approved", "Declined"

3. application_offering_change_requests_id_seq has to be created start 1 increment 1 owned by "application_offering_change_requests" table

**Comment by JasonCTang** [comment]
This turned into the analysis ticket and was split into multiple subtickets for implementation.
