### ISSUE TITLE
Add PD/PPD status flag to Electronic Confirmation of Enrolment File (ECE) 

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#1904]
Replaced by Ticket #2522

**Comment by ann-aot** [comment]
Are these `Application PD Status Flag`,
 - 0 = No PD/PPD status
 - 1 = PD or PPD status requested
 - 2 = PD status approved
 - 3 = PPD status approved
 - 4 = PD or PPD request was not approved

**Comment by HRAGANBC** [comment]
Replaced by #2522
