### ISSUE TITLE
Git reorganization for smooth release cycle

### ISSUE THREAD

**Issue by guru-aot** [bcgov/SIMS#1917]
**As a** *developer* **I want** *these changes in our github repository* **So That** *we can create smooth releases on production and development openshift cluster*

**Acceptance Criteria**
- [ ] Analysis and discuss with the team on the new github branches and make the team understand the differences from the current change
- [ ] Create new branches accordingly as per the discussion and reviews from the team.

![image](https://user-images.githubusercontent.com/62901416/236027551-29ebcf42-e68d-403f-9565-4c92ebd5aa53.png)

**Comment by andrewsignori-aot** [comment]
## Analysis for suggested branch strategy

- Create automated Github workflows to create release/hotfix branches.
- Separated the build workflow and execute it on branches `main`, `release/*`, and `hotfix/*`. The build workflow will work similarly to the one in place right now, creating a tag and creating the build on the Openshift for all the applications.
- Stop deploying automatically from `main` to DEV once the build is ready. If need to control te deploys to ensure that the build version can be deployed to DEV, for instance, the database may be not in the expected state and migrations may need to be rolled back.
- Use [Semantic Versioning](https://semver.org/) including the build number.
- Use the `main` branch as the only temporary branch following the below diagram.

![image.png](https://images.zenhubusercontent.com/5fcebe3c076e6aaed83693fb/85309d2f-18a2-49f1-b7f3-778b01581bc5)

### Some references
- https://www.endoflineblog.com/oneflow-a-git-branching-model-and-workflow
- https://medium.com/@patrickporto/4-branching-workflows-for-git-30d0aaee7bf
