### ISSUE TITLE
Deploy SIMS in production cluster

### ISSUE THREAD

**Issue by guru-aot** [bcgov/SIMS#1922]
**As a** *User **I want** *deploy all components of SIMS in production cluster in openshift* **So That** *we are ready for production release*

**Acceptance Criteria**
- [ ] Create github secrets for PROD env.
- [ ] Change current github actions to accommodate Prod environment. 
- [ ] Deploy all components such as DB's, API, Web, Queue Consumers, workers, formio through github actions.
- [ ] Create DB backup pods.

**Comment by JasonCTang** [comment]
This has been completed.
