### ISSUE TITLE
Modal for the restriction resolution has the note typed in from the immediate previous resolved restriction.

### ISSUE THREAD

**Issue by sh16011993** [bcgov/SIMS#1935]
**Describe the Bug**
When resolving a restriction in the ministry portal by providing a note and then viewing another restriction to resolve it,  the modal has the note typed in from the immediate previous resolved restriction.

**Expected Behaviour**
The input field to enter the restriction resolution note should be empty when the modal is rendered.

**Actual Behaviour**
The modal has note typed in from the immediate previous resolved restriction.

**Steps To Reproduce**
1. Login to the ministry portal.
2. Search for a student and click on the Restrictions tab.
3. Create two new restriction for the student if there are no active restrictions.
4. Resolve the first restriction by entering a restriction resolution note.
5. Click on the view restriction button for the other restriction.
6. The note from the previous resolved restriction is already typed in the modal.

**Comment by michesmith** [comment]
This is a duplicate - move to close
