### ISSUE TITLE
Change existing QA environment to Staging environment.

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#1963]
**Describe the task**
Change existing QA environment to Staging environment

**Acceptance Criteria**
- [x] Create seperate database, form.io, camunda, api, etc
- [x] Share Patroni, Redis, keycloak
- [x] Remove QA database secret entry and make it as a parameter
- [x] Rename to Staging prefix.

**Comment by guru-aot** [comment]
DEVS Staging Environment is deployed and it resides in the same namespace as that of test 0c27fb-test.
Things to note:
The patroni is shared between test and staging, but the DATABASE is different Test - SIMSDB , Staging - STGSIMSDB. To include this change, I manually created the DB by connecting the test Patroni in local. Also added one secret in patroni-creds called as stg-database-name which has the value STGSIMSDB. Also changing the database-name-key - > github secrets for the staging environment to stg-database-name.
The forms and mongodb are all seperate, this is done as staging should mimic prod environment and any form hotfixes that come in production can be deployed here and tested, without affecting test environment.
Good thing, all our github actions work in the new staging environment and I tried to clean as much as stuff created as part of QA environment creation. 
Lastly the current version of Staging environment is v1.1.1-414, this is the hotfix tag created by dheepak and I tested the legal operating name bug, it works.
URLs to access institution
http://stg-aest-sims.apps.silver.devops.gov.bc.ca/institution
URLs to access Ministry
http://stg-aest-sims.apps.silver.devops.gov.bc.ca/ministry
​​​Although student and supporting users login are available, as we are sharing the same keycloak as that of test, please do not use it, as we mimic Prod environment and queue-consumers and workers are deleted after deploy all github action is done.
Please do not try the file exchange operations, as the secrets are not applied to mimic prod environment.
