### ISSUE TITLE
Confirm location of PROD SFTP and populate the SFTP secret in PROD environment.

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#2007]
**Describe the task**
Confirm location of PROD SFTP and populate the SFTP secret in PROD environment.

**Acceptance Criteria**
- [ ] Confirm location of PROD SFTP
- [ ] Populate SFTP secret information in PROD environment
- [ ] Connect to SIMS PROD OSID

**Additional context**
- Currently, we are using the server Linda, which is not a PROD server.

**Comment by cditcher** [comment]
Hi @JasonCTang I assume this is referring to the values stored in the zone-b-sftp secrets on dev/test/prod? Prod is not populated so I would assume this to be the case.

**Comment by michesmith** [comment]
@JasonCTang is this a duplicate?
