### ISSUE TITLE
Enhance the Notification Framework to send email to multiple recipients

### ISSUE THREAD

**Issue by dheepak-aot** [bcgov/SIMS#2014]
**Describe the task**
Currently our notification framework which is based on GC Notify is capable of sending an email to only a single recipient.

To send an email to multiple recipients, GC Notify used a different endpoint and slightly different payload.
Reference: https://documentation.notification.canada.ca/en/send.html#sending-notifications-in-bulk

Update the notifications framework support the multiple recipient sending.

**Acceptance Criteria**
- [ ] Update the existing notification service and GC notify service to send email to multiple recipients.
- [ ] A new endpoint needs to be added to env variable,devops or determine the root of end point from env variable and  append email or bulk at the end based on the service invoked. TBD.

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by michesmith** [comment]
Devs please prioritize which release.

**Comment by sslaws** [comment]
Can you confirm if you see any need for this in PT or FT or we can move to a future release.

**Comment by CarlyCotton** [comment]
Closing - no longer needed.
