### ISSUE TITLE
Connect PROD to SIMS BCeID OSID (and update the TEST and DEV environment to SIMS OSID at same time. 

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#2015]
**Describe the task**
Connect PROD to SIMS BCeID OSID (and update the TEST and DEV environment to SIMS OSID at same time. 

**Acceptance Criteria**
- [ ] Populate the PROD environment to SIMS BCeID OSID.
- [ ] Update TEST and DEV environments to switch from SFAS OSID to SIMS OSID.

**Comment by michesmith** [comment]
iT WAS ALREADY IMPLEMENTED ACROSS ALL ENVIRONMENTS- PER Jason
