### ISSUE TITLE
Resolve Server-Side Request Forgery in Request

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#2016]
**Describe the task**
Resolve Server-Side Request Forgery in Request.  (Link in additional context below)

**Acceptance Criteria**
- [ ] Resolve Server-Side Request Forgery in Request

**Additional context**
- https://github.com/bcgov/SIMS/security/dependabot/111

**Comment by andrewsignori-aot** [comment]
Added to the #2017
