### ISSUE TITLE
Update NOC code to accept 5 digits instead of 4

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#2024]
**Describe the task**
Federal government's new format for NOC codes is now 5 digits long and currently, our forms only accept 4 digits.  Update to accept 5.

**Acceptance Criteria**
- [x] Make necessary changes to accept and store 5 digit NOC codes.

**Comment by andrewsignori-aot** [comment]
Changed NOC code to accept exact 5 digits.

It shows a validation error for 4 or 6 digits.

![image.png](https://images.zenhubusercontent.com/5fcebe3c076e6aaed83693fb/56d18b63-6cd2-417a-ae2c-08a97205cd8c)

![image.png](https://images.zenhubusercontent.com/5fcebe3c076e6aaed83693fb/77f86fbc-4039-43f7-ba3f-e52ce08bdf8e)

No errors when 5 digits are provided.

![image.png](https://images.zenhubusercontent.com/5fcebe3c076e6aaed83693fb/5f6adc16-2241-48e2-a6c8-d3ded94c0b9e)
