### ISSUE TITLE
Bugs and changes to Institution Portal -> Add Offering

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#2027]
**Describe the task**
The following is a mix of bugs and further requirements to the Add Offering in the Institution Portal
- When an offering doesn't align with the delivery method of a program, the submission should go to pending status.  (Currently returning an internal service error)
- Update the following content: 
  - Cost Fields
    - "Tuition" stays the same
    - Change "Program Related Costs" to "Books and Supplies"
    - "Mandatory fees" stays the same
    - Change "Exceptional Expenses" to "Exceptional Costs"
    - Add help text next to the cost fields that says "These costs must comply with the maximum allowable costs according to the SABC polciy manual."
  - Ammend content under the "Offering Name" field to read "Please include the institution location, year of study, and cohort details directly into the name of the offering so that students can differentiate it from other similar offerings."
  - Study Breaks Fields:
    - Change "Identify scheduled breaks for the program year" to: 
      - "Identify schedule breaks for the study period offering: 
        * Study breaks of five or fewer consecutive calendar days that would normally be instructional days do not count towards study breaks.
        * Study breaks cannot exceed three weeks, or 21 consecutive days.  Excess break days will be deducted from overall funded weeks.
        * Breaks in study may not exceed 10% (individually or cumulatively) of the study period offering length.  Exccess break days will be deducted from overall funded weeks."

**Acceptance Criteria**
- [ ] Investigate and resolve internal service error. 
- [ ] Confirm Lynn has reviewed content.
- [ ] Update content.

**Comment by dheepak-aot** [comment]
For the bug mentioned in AC1 (Internal server error on offering submission when offering doesn't align with the delivery method of a program), I was not able to replicate the issue after trying all possible combinations of testing.

## Onsite Program and Online Offering

Offering created in "Creation pending status"
![image.png](https://images.zenhubusercontent.com/60e72aa247c95cd873ed8ce1/aa49756e-3bdf-466f-a147-ab71bdba521c)

![image.png](https://images.zenhubusercontent.com/60e72aa247c95cd873ed8ce1/20834348-6d94-497e-9f42-c9adbc76a90d)

## Online Program and Onsite Offering

![image.png](https://images.zenhubusercontent.com/60e72aa247c95cd873ed8ce1/8434b3d1-9a8b-49e4-b762-f39532bab4c7)

![image.png](https://images.zenhubusercontent.com/60e72aa247c95cd873ed8ce1/681c9e10-2067-44d4-8016-600287ec7d27)

**Comment by JasonCTang** [comment]
Business could not recreate the internal service error bug neither.  Closing ticket.
