### ISSUE TITLE
Change to PSI -> Institution Designation

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#2030]
**Describe the task**
When an out-of-province, US and international schools attempts designation, they currently go through the same route as BC Privates, when in fact, they should see the same screen as the BC Publics.  

**Acceptance Criteria**
- [ ] All institutions but BC Privates must follow same behaviour as BC publics.

**Comment by andrepestana-aot** [comment]
The problem could not be reproduced:

Out of Province College:
![image.png](https://images.zenhubusercontent.com/601c6b4f5322cf5c519d503f/9f8cd188-e14a-4103-937f-70e96c122ebd)

US College:
![image.png](https://images.zenhubusercontent.com/601c6b4f5322cf5c519d503f/2b082bc1-710d-43bf-8f91-1dab7076b4f6)

BC Private:
![image.png](https://images.zenhubusercontent.com/601c6b4f5322cf5c519d503f/87ae355e-3d1e-46f4-9486-4300f64b03a8)

BC Public:
![image.png](https://images.zenhubusercontent.com/601c6b4f5322cf5c519d503f/f1a122bc-fc8d-40b2-9230-025cc09ffd84)

**Comment by andrepestana-aot** [comment]
## Test in DEV

BC Private:
![image.png](https://images.zenhubusercontent.com/601c6b4f5322cf5c519d503f/573ea8ed-2111-4b94-802f-be47a4ab332b)

Out of Province:
![image.png](https://images.zenhubusercontent.com/601c6b4f5322cf5c519d503f/386eede0-7461-496b-9712-8d5c02023a00)

International:
![image.png](https://images.zenhubusercontent.com/601c6b4f5322cf5c519d503f/4ff99786-1cef-4b7d-ade4-4ab08c7fc202)
