### ISSUE TITLE
Seperate minimum offering length validation between Fulltime and Partime. 

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#2033]
**Describe the task**
- Seperate minimum offering length validation between Fulltime and Partime.
- Fulltime will be 84 days and Parttime will remain at 42 days. 
- Maximum will be 365 for both fulltime and partime.
- When offering is created and the days are below the minimum for the intensity, the submissions goes to pending status.

**Acceptance Criteria**
- [x] Create separate constant and set to 84 days for FULLTIME.
- [x] Change form to handle new parameters
- [x] Change class to handle validation for both form and bulk upload.

**Comment by hellolynn-tbtb** [comment]
DEVS demod with Hugh/Josh on June 29, 2023.
