### ISSUE TITLE
Unexpected error during designation agreement submission

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#2039]
**Describe the Bug**
It appears as if when submitting a designation agreement, it times out and returns an unexpected error. 

**Expected Behaviour**
Agreement should submit successfully.

**Actual Behaviour**

** Steps To Reproduce**
Steps to reproduce the behaviour:
-	Use ministry to create institution [complete/successful]
-	Use ministry account to add user to account (username hughragan66) [complete/successful]
-	Login to institution account with username hughragan66 [complete/successful]
-	Institution user creates location
-	Institution user selects ‘request designation’ 
-	Institution user selects location and selects submit
-	Upon clicking submit, the request times out and generates an error message (same as below email)

** More Detail**
Account name (user ID): ErikPIT
Institution name: Academy of Research Best Practices
Completing designation for a private institution. Upon submission error message created (see screen shot from Danielle)

Same for Danielle doing a private institution
Could not get Danielle details as her day ended but she captured a screen show of the issue and the others confirmed that theirs looked the same.

Hugh tried to recreate the issue and had the same error.
Identifying Details:
-	Username: hughragan66 (basic BCeID)
-	Institution Operating Name: PSI Final Testing (created by Ministry)
-	Institution Type: BC Public (Other testers have encountered same issue with BC Privates)
-	Institution location: “Vancouver Campus” – location code: AUBC

Claire ran into the same issue when submitted designation for a BCPublic institution 
Institution name: June Test Institute
User: DKSims027
![image.png](https://images.zenhubusercontent.com/6398d78b550c6ab79f2d32ac/480e7c5d-1275-4a3d-98ab-701fd83fcf44)

**Comment by andrewsignori-aot** [comment]
This seems to be related to the cache issue that happen and was fixed right before the v1.0.0 release.
Please revalidated it.

**Comment by HRAGANBC** [comment]
Reviewed by Business and approved for deployment

**Comment by JasonCTang** [comment]
Verified by business to be working.
