### ISSUE TITLE
Remove cache from Institution type on SIMS API

### ISSUE THREAD

**Issue by andrewsignori-aot** [bcgov/SIMS#2043]
The [institution.service.ts](https://github.com/bcgov/SIMS/blob/c5a37a92dfb602482d7e4e787ba0d78b3e3f8c43/sources/packages/backend/apps/api/src/services/institution/institution.service.ts#L720) currently has the cache enable to the authorization for Public Institutions accessing Student data, which would not be the case for the August release.
We can have the cache removed for the August release and have it enabled back with the cache invalidation implemented altogether in a separate ticket.

- [ ] Remove the `cache: true` from the method at  [institution.service.ts](https://github.com/bcgov/SIMS/blob/c5a37a92dfb602482d7e4e787ba0d78b3e3f8c43/sources/packages/backend/apps/api/src/services/institution/institution.service.ts#L720)

**Comment by hellolynn-tbtb** [comment]
DEVS demod with Hugh/Josh on June 29, 2023.
