### ISSUE TITLE
Invalid Education Program Field of Study

### ISSUE THREAD

**Issue by andrewsignori-aot** [bcgov/SIMS#2053]
While an institution is creating or editing an Education Program there is a calculation between “Credential Type” and “Classification of Instruction Programs (CIP)” that must result in the “Field of study code”.

So, the below scenario ends up in an error (Internal Server Error) because the “Field of study code” is not being populated.

![image.png](https://images.zenhubusercontent.com/5fcebe3c076e6aaed83693fb/db1d1312-4b53-402d-8c7e-e99348cf6d96)

The expected scenario would be like below.

![image.png](https://images.zenhubusercontent.com/5fcebe3c076e6aaed83693fb/9478be7f-0ad0-41b3-8b91-cd8df8b3ffc9)

This was implemented as part of #1222 and apparently, there is at least one combination missing (probably W3).

Currently, the possible combinations are present on form.io.
Form.io reference:
https://github.com/bcgov/SIMS/blob/d521713b923c825fe5af347868787187a21ca1fb/sources/packages/forms/src/form-definitions/educationprogram.json#L216.

The spreadsheet including all definitions is present at 
`Documents>General>Analysis>User Story Specifications>Federal Study Code (#1222)>Fed Study Code Mapping.xlsx`

Curent list:
P7: "25",
P5: "55",
P8: "25",
P3: "40",
P6: "70",
P4: "40",
P2: "25",
P1: "25",
Q4: "39",
Q7: "24",
Q5: "54",
Q1: "24",
Q6: "69",
Q2: "24",
Q8: "24",
Q3: "39",
R7: "23",
R6: "68",
R4: "38",
R5: "53",
R2: "23",
R3: "38",
R8: "23",
R1: "23",
S8: "22",
S1: "22",
S4: "37",
S3: "37",
S2: "22",
S5: "52",
S7: "22",
S6: "67",
T1: "21",
T7: "21",
T4: "36",
T5: "51",
T3: "36",
T8: "21",
T6: "66",
T2: "21",
U8: "20",
U3: "35",
U2: "20",
U4: "35",
U7: "20",
U5: "50",
U1: "20",
U6: "65",
V1: "19",
V3: "34",
V6: "64",
V5: "49",
V2: "19",
V7: "19",
V4: "34",
V8: "19",
W8: "18",
W4: "33",
W2: "18",
W7: "18",
W5: "48",
W1: "18",
W6: "63",
X5: "47",
X2: "17",
X1: "17",
X4: "32",
X8: "17",
X3: "32",
X6: "62",
X7: "17",
Y4: "31",
Y8: "16",
Y5: "46",
Y6: "61",
Y2: "16",
Y3: "31",
Y1: "16",
Y7: "16",
Z7: "15",
Z8: "15",
Z5: "45",
Z4: "30",
Z2: "15",
Z3: "30",
Z1: "15",
Z6: "60"

**Expected fixes**

- [ ] Ensure that all the configurations available on the spreadsheet are updated on form.io.
- [ ] Check if it is possible to add a validation to the "Field of Study" to ensure that, if some combination is missing the form will not be submitted avoiding the `internal server error`. For instance, add a required filed validation with the custom error message "The combination of the Credential Type and CIP did not result in a known Field of Study code." (Nice to have).

**Comment by JasonCTang** [comment]
Created #2083 for business area to validate fix.
