### ISSUE TITLE
Institution Missing Menu Options

### ISSUE THREAD

**Issue by andrewsignori-aot** [bcgov/SIMS#2055]
After a new institution is created using a business BCeID the menus are not rendered as expected due to an issue with the vue store reactivity.

Main page rendered without the menus.
![image.png](https://images.zenhubusercontent.com/5fcebe3c076e6aaed83693fb/ca43724d-543e-458c-a231-54945c426094)

Expected page with the expected menus.

![image.png](https://images.zenhubusercontent.com/5fcebe3c076e6aaed83693fb/c33bacf8-3d1f-49e3-b384-ccd041fecb86)

**Comment by hellolynn-tbtb** [comment]
DEVS demod with Hugh/Josh on June 29, 2023.
