### ISSUE TITLE
Institutions - Enhance regulatory body dropdown

### ISSUE THREAD

**Issue by Joshua-Lakusta** [bcgov/SIMS#2058]
### Acceptance criteria

- [ ] Add a new dropdown item called "Senate, Academic Council, Education Council, and/or Program Council and Board of Governors". Define the option code as `senateOrEducationCouncil`.

### Note

- "Other" field is already being implemented in #2028

**Comment by HRAGANBC** [comment]
Hugh (representing business area) confirms testing was conducted on this ticket on June 29, with no issues identified. Signed-off for release to PROD
