### ISSUE TITLE
Institutions - Rename an item in Regulatory Dropdown field

### ISSUE THREAD

**Issue by Joshua-Lakusta** [bcgov/SIMS#2059]
An item in the regulatory dropdown field needs to be renamed.

### Acceptance criteria

- [ ] ITA = needs to be changed to “Skilled Trades BC” on label in both the Create Program and Create Institution Profile forms. 
- [ ] Update database code with migration.

### Questions

- [ ] Will the policy/admin manuals be updated as well?

**Comment by JasonCTang** [comment]
Confirmed with Business area this will be updated in policy/admin manual as well.
