### ISSUE TITLE
Issue with student application advancement

### ISSUE THREAD

**Issue by hellolynn-tbtb** [bcgov/SIMS#2061]
## Context

Bug not for summer launch but is holding up the business from testing.

- Portal: Student portal
- Account name: joshuaS
- App number: 2023000046 

**Time of occurrence**
Occurring consistently (tested today)
Happened in June, there was a FIX, but broke again

**Page/section of application**
Any submission or edit of the application leads to the status being stuck as “Submitted” status

**Program or offering name (if applicable)**
My app used Josh walking program Sept-Dec offering

## Bug
 
**Describe the Bug**
When you submit any application or edit of an application the status of the application goes to submitted but does not proceed and complete other processes.

**Expected Behaviour**
It should proceed to in progress then assessment then coe etc…

**Actual Behaviour**
Does not move past the submitted status.

**Steps To Reproduce**
Steps to reproduce the behaviour:
1.	Create and complete a student application 
2.	Submit the application
3.	Check status and it is stuck at submitted

**Screenshots**
![image.png](https://images.zenhubusercontent.com/6047d6ac906f4ec904f7286c/5d23f93f-3f3c-4bea-8729-41c82c6da57b)

**Comment by michesmith** [comment]
Signori resolved this
