### ISSUE TITLE
Patroni creds should be changed from superuser to database username/pwd for DB backup verification

### ISSUE THREAD

**Issue by guru-aot** [bcgov/SIMS#2067]
Currently our Application is accessing Patroni using the superuser and superpassword, as per this story, the accessing of the application should be done using the database username/pwd

**Acceptance Criteria**

- [x]  Implement backups in PROD 
- [x] Change the user in database-user in patroni-pre-req.yml, to be constant and not trailing autogenerated.
- [x] Add scripts to assign permission of database user to access sims schema.
- [x] Change the backup-deploy.yml to use the DATABASE_USER_KEY_NAME and DATABASE_PASSWORD_KEY_NAME from the database user/pwd by changing the makefile db-backup-deploy-patroni job.
- [x] Create verifiation scheduler in patroni-simsdb-backup.conf

**Comment by JasonCTang** [comment]
Two ACs removed and new tickets created for follow up:
- [ ] Jason to do: Determine if OCIO provides off server storage of backups (Currently being stored on PV in OpenShift)
- [ ] Jason to do: To check with the team on the outage for the backup and restore
