### ISSUE TITLE
New Program Credential Type- Undergraduate Citation

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2072]
**Description of Task**
- Create new credential type to be available on the 'Add Program' form.
- Map the new credential type with Level of Study, Field of Study and Federal Study Code. 

**Context:** 
There are not other impacts on workflow or other impacts. 

**Acceptance Criteria** 
- [x] Add "Undergraduate Citation" to the dropdown of Program Credentials.
- [x] Undergraduate Citation should be considered SABC Credential = 8 (i.e. categorized equivalent to "undergraduate certificate")
- [x] Map this Undergraduate Citation credential type to Federal Study Code **identically** as if it were a undergraduate certificate. (i.e. the mapping is already done)
- Add 'undergraduate Citation' as one of the credential types eligible in FT workflow for:
  - [x]  awardEligibilityBCAG
  - [x] awardEligibilityBCAG2Year
  - [x] awardEligibilityCSGF
- Add 'undergraduate Citation' as one of the credential types eligible in PT workflow for:
  - [x] awardEligibilityBCAG
- [x] Update Federal Study Code Documentation with the new mapping: Documents>General>Analysis>User Story Specifications>Federal Study Code (#1222)>Fed Study Code Mapping.xlsx
- [x] Check IER12 integration for level of study codes. Reference [here](https://github.com/bcgov/SIMS/blob/main/sources/packages/backend/libs/integrations/src/institution-integration/ier12-integration/ier12.integration.service.ts#L410).
- [x] Update credential type friendly name. Reference [here](https://github.com/bcgov/SIMS/blob/main/sources/packages/backend/apps/api/src/utilities/credential-type-utils.ts).
- [x] Update E2E for FT/PT eligibility.

**Comment by HRAGANBC** [comment]
Critical?
Yes - we need it for august launch

Ministry or Institution portal
Institution portal

Page/section of application
'Add Program' page/form

---

Current Behaviour:
When adding a program, there are 8 options for the 'credential type' field; 
Undergraduate Certificate
Undergraduate Diploma
Undergraduate Degree
Graduate Certificate
Graduate Diploma
Graduate Degree / Master's
Post-Graduate / Doctorate
Qualifying Studies

Expected Behaviour
There should be a new, 9th option, called "Undergraduate citation"
This option should not have any validations or functionality attached to it. We just want to save that program in the database as UndergradCitation


![image.png](https://images.zenhubusercontent.com/62fc03010dde35d5a39ff930/2338fbe7-4e55-4e0d-a2e1-743959831b86)

**Comment by HRAGANBC** [comment]
The new credential type, - undergraduate citation - should have Level of Study = 1 according to this analysis: https://bcgov.sharepoint.com/❌/t/03177/EQBQY3nY0JxMhBkRDIYcYBsBqn2efsJYwu8_1hcIVfzMiA?e=WCUlhH

The undergraduate citation should be it's own distinct option in the dropdown menu when institution users select, but can be considered equivalent to 'qualifying studies' form the perspective of determining the 'level of study'.

![image.png](https://images.zenhubusercontent.com/62fc03010dde35d5a39ff930/ca4b20b4-422d-41ee-afed-d5599256ee22)

**Comment by michesmith** [comment]
@HRAGANBC Confirming Caps for  "undergraduate citation" should it be all lowercase or Caps the first letter?

**Comment by HRAGANBC** [comment]
@michesmith thanks- just adjusted ACs with capitalization
