### ISSUE TITLE
Designation Workflow Diagram

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#208]

**Comment by roopfw** [comment]
Initial pass complete- review to happen tommorow with business area + @alpivett 

View on Figma:
https://www.figma.com/proto/mLw9vmpZj7BM0T8Y59Qf8Q/FreshWorks-Studios-StudentAid-BC-User-Flows?node-id=244%3A0&viewport=213%2C-2768%2C0.5&scaling=min-zoom

Preview:
![image.png](https://images.zenhubusercontent.com/5e66ca845237f60c730a4aa3/d3f32e8b-9c92-4b15-9935-331eb00e4194)
