### ISSUE TITLE
Verify Field of Study code generation fix in #2053

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#2083]
JASON ARE YOU HAPPY WITH THIS?

**Describe the task**
This ticket is for the Business area to verify the Field of Study code generation fix in #2053

**Comment by HRAGANBC** [comment]
Signing off on this after review and business area testing. 

With one note: there MAY be an additional credential type being added.

**Comment by HRAGANBC** [comment]
The new credential type, - undergraduate citation - should have Level of Study = 1 according to this analysis: https://bcgov.sharepoint.com/:x:/t/03177/EQBQY3nY0JxMhBkRDIYcYBsBqn2efsJYwu8_1hcIVfzMiA?e=WCUlhH

The undergraduate citation should be it's own distinct option in the dropdown menu when institution users select, but can be considered equivalent to 'qualifying studies' form the perspective of determining the 'level of study'.

![image.png](https://images.zenhubusercontent.com/62fc03010dde35d5a39ff930/f02de7f6-493a-4284-b495-dd8c78c15b66)
