### ISSUE TITLE
Institution Edits Program

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2085]

**Comment by HRAGANBC** [comment]
Expected Behaviour: 

When editing the program form of an approved program, all fields should be editable until an OFFERING is attached. 

When at least one offering is attached, a banner message should appear saying "Offerings have been attached to this program - only the program name and program description can be edited"

Actual Behaviour:
When the banner message appears, it says "Students have applied to financial aid for this program"

**Comment by michesmith** [comment]
Duplicate
