### ISSUE TITLE
Institutions - Enhance regulatory body dropdown

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#2086]
Same change as #2058 which was only applied to the hotfix and this one will target the next release. 

Acceptance criteria
- [x] Add a new dropdown item called "Senate, Academic Council, Education Council, and/or Program Council and Board of Governors". Define the option code as senateOrEducationCouncil.
- [x] This needs to be applied to both the program and institution profile forms

Note
"Other" field is already being implemented in #2028

**Comment by dheepak-aot** [comment]
During the demo of this story, there was a point raised by @JasonCTang  that the select components in the create/edit program page did not have arrow icon at the right corner, which was seen in select components of institution profile form.

![image.png](https://images.zenhubusercontent.com/60e72aa247c95cd873ed8ce1/45ade97c-d3a7-4d73-aeeb-b78f206c53c4)

![image.png](https://images.zenhubusercontent.com/60e72aa247c95cd873ed8ce1/7b114a0e-d899-4a99-b2d1-44882419d7bd)

On investigating further, we found that in form.io select components with widget type as "html5" the OOTB look does not have the arrow in it. At the same time, the select component with default widget in form.io has the arrow icon along with search option on the select. And as expected, the "educationprogram" form had each of it's select components using widget type as "html5" and "institutionprofile" select component for regulatory body was using default widget.

Here are the list of "html5" widgets used in our application

![image.png](https://images.zenhubusercontent.com/60e72aa247c95cd873ed8ce1/ce076cd9-1402-4c13-b4a9-e2c36eab6f48)

As per discussion with @JasonCTang  we will not be making any changes to the program form as of now.
