### ISSUE TITLE
Establishing independent status for Youth in care students

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#2102]
**Describe the task**
Revision of the "former youth in care" question (refer to this as Parent Question) and introduce new sub-question for anyone who answers ‘yes.'

Current Parent Question: 
"Were you ever a youth in the continuing custody of a director of child welfare in BC (ward of the court this means the provincial government is/ was your legal guardian)? "

Requested Change to Parent Questions:
"Were you ever considered a child or youth under government care" with tooltip that reads "Ministry of Children and Family Development (MCFD) or Indigenous Child and Family Service Agency [ICFSA] care, care through the Ministry of Social Development and Poverty Reduction [SDPR] Child in the Home of Relative Program or government care through a Canadian province or territory outside of B.C.

New question: (this should only be presented to the applicant if they answer YES to parent question.
“Are you, or were you at the time of your 19th birthday, in continuing care or custody of a director of child welfare in B.C.?"

Also add an associated tooltip: 
“This means that the provincial government is currently your legal guardian if you are younger than 19 or was your legal guardian at the time of your 19th birthday”

If student answers no, no effect. 
 - No effect means that we still follow the rules of answering YES to parent question.   
 - There will be no impact on the family size calculations.  If student has dependents, it will be counted as normal.

If student answers ‘yes’ AND the student is dependent status, convert student to independent status and treated as independent for the entire assessment workflow. This independent status would overrule any other application logic that determines the student to be a dependent. *Answering 'yes' to second question has no impact on student's exemption from StudentFixedContribution that was determined by virtue of answering yes to the Parent question

This is the same for both Part-Time and Full-Time

***Acceptance Criteria***
- [x]  Check workflow where dependent vs independent is applied.
- [x]  Update the form to the current question. 
- [x]  If student answers Yes to secondary question, convert student to independent status and treat as independent for entire assessment workflow.
- [x]  Only override dependent to single independent. (i.e. if student is married, preserve them as maried)
- [x]  Question only presents to applicant in form if they answer ‘yes’ to being a former youth in care. 
- [x]  Add tool tip to question.

**Comment by ann-aot** [comment]
As part of this ticket there is no workflow changes. The `dependantstatus` logic is set the form itself, so as part of the ticket the `dependantstatus` logic is updated in the form, which will used in the workflow for the calculation.
