### ISSUE TITLE
Add "Apply PD Status" option to the application form

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#2104]
**As a** *student* **I want** *an Apply PD Status option* **So That** *I can choose if I want PD/PPD status applied to the assessment of my application.*

**Additional Context**
- If I already have PD Status, it will be applied as expected, but if I do not yet have PD status, then the PD Grants will be withheld until we receive the response from AT-BC.
- Ask the student in student application if they would like to apply to PD or opt-out.
- Upon ATBC answer, do an reassessment once the application is completed.
- Hold the disbursement till get an answer from ATBC.
- No changes expected to the student profile right now.
 

**Acceptance Criteria**
- [ ] Please add Apply for PD Status to the application form under the personal information section PLEASE INDICATE WHERE
- [ ] Y/N Question.  (operates the same at the account level)
- [ ]  "if they select yes then.... TEXT FROM HUGH 
- [ ] Link the 'answer to the 'Account' Functionality

**Comment by ann-aot** [comment]
Looks this is a duplicated ticket, 
reference: https://app.zenhub.com/workspaces/student-information-management-system-5fce9df5aa1b45000e937014/issues/gh/bcgov/sims/2147

**Comment by michesmith** [comment]
This is a duplicate- closing
