### ISSUE TITLE
Import MSFAA information from SFAS

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#2106]
MUST CONFIRM WITH DEVS IF THIS IS STILL REQUIRED

**Describe the task**
A clear and concise description of what the task is.

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by ninosamson** [comment]
Closing this ticket as obsolete - MSFAA data is available.
