### ISSUE TITLE
Invalid request when trying to created basic bceid student profiles in Test

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#2109]
*Describe the Bug**
Becky had some new ministry users create sutdent profiles in the test environment using Basic BCeIDs (Nate Schaeffer and Pratpal Gill) and experienced an invalid error when she got to the "Create account now" stage.  

**Expected Behaviour**
When user clicks on  "Create account now," it should result in the student's account being created with a Basic BCeID.

**Actual Behaviour**
When user clicks on "Create account now" it is returning the response "Not able to approved the student account application due to an invalid request" error message. 

** Steps To Reproduce**
Steps to reproduce the behaviour:
1. Log in as ministry user and navigate to Student requests accounts.
2. Click on the View button next to one of the students.
3. In View Request, click on Create account for student
4. A confirmation card will pop up where you will need to click on Create account now.

**Screenshots:** *[https://app.zenhub.com/files/319429847/174c244f-2b56-44ce-a459-d2a2c1f42f05/download](https://app.zenhub.com/files/319429847/174c244f-2b56-44ce-a459-d2a2c1f42f05/download)

**Comment by michesmith** [comment]
This has been fixed in a duplicate ticket #2126. Please review duplicate ticket to validate testing.

**Comment by michesmith** [comment]
Resolved
