### ISSUE TITLE
Estranged for parents exception allowing future date (BUG)

### ISSUE THREAD

**Issue by Joshua-Lakusta** [bcgov/SIMS#2110]
### Step 1 <span style="color:#ff5538"> **[Fail]** </span>
[Pre-requisites]
- Fill all applications program details as needed but for Program Capacity please select “Full time” 
- User selects “No” for “out of high school for 4 years? ” on personal information tab
- User single and mentions no dependants on the family information tab 
- User is now on the parent information tab”
[Actual Application Steps]
- Select “I am estranged from both of my parents” for “parents resident of BC?”

#### Expected Result
Should populate additional section whrere you enter date you became estranged and support documentation upload.

#### Actual Result
Sub scenario questions populate, test itself is a pass.

However, you can add a date in the future for when you were estranged (does not flag as error) , you can also advance to the next step without uploading any documentation.

**Comment by Joshua-Lakusta** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/gov2/project/16463?defectId=14297)

**Comment by JasonCTang** [comment]
This was created as a test of the Test Quality & Zenhub integration.  Closing for testing purposes.
