### ISSUE TITLE
UI and file format validation for Bulk Withdrawal Upload

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#2111]
**Describe the task**
UI and file format validation for Bulk Withdrawal Upload

**Figma Design**
https://www.figma.com/file/9Om2tzLAVEoMQrjmrH4fhu/MOD-SIMS?type=design&node-id=12566-163067&mode=design&t=LyYYv68zdOfihIDs-0

**Additional Context**

- File Layout: [https://app.zenhub.com/files/319429847/d246b205-1c6f-449d-b998-b8c75d8e08b2/download](https://app.zenhub.com/files/319429847/d246b205-1c6f-449d-b998-b8c75d8e08b2/download)
- File is based off all applications that have had an assessment since the last file was sent
- The withdrawal file is a flat ASCII text file.
- Workaround: Institutions that use a bulk withdrawal file still have the ability to enter withdrawals through Insitution Portal.
- Process each record as if it were an manually entered withdrawal. 
- Although this is an "integration" file, it currently still requires a manual process to be executed by the Institution user in SFAS where they have the opportunity to review the warnings prior to committing the changes to SFAS. Therefore, we are suggesting the same approach as the Bulk Offering Upload.

**Acceptance Criteria**
- [x] Process each record as if it were a manually entered withdrawal.
- [x] Allow only BC Public institutions to use and perform this upload.
- [x] Allow only Institution Administrator role to perform this upload.
- [x] Follow the same approach as bulk offering file upload, only process file if all records pass validation (all or nothing), display issues on the page, etc.
- [x] As part of this ticket, do only the file structural format validation.
- [x] Validate the file structure and abort the process if the files are not as expected. In case one or multiple validations failed, return the validation errors.
        - [ ] Validate header record type.
        - [ ] Validate withdrawal record type.
        - [ ] Validate SIN to be numeric and with 9 digits.
        - [ ] Validate the application number to be numeric with 10 digits.
        - [ ] Validate the withdrawal to be a valid date in the format YYYYMMDD.
        - [ ] Validate footer record type.
        - [ ] Validate if the total number of records in the file matches the footer information.
- [x] Allow the process to be executed as validation only, that will check further for possible errors (future ticket https://app.zenhub.com/workspaces/student-information-management-system-5fce9df5aa1b45000e937014/issues/gh/bcgov/sims/2112) but should not persist any data to the database. 
- [x] For every single file line that has an error or warning, a summary should be displayed
        - [ ] Line number: record number including the header in the count.
        - [ ] Validations: display a user-friendly message about why the record was not considered valid.
- [x]  Only allow plain text files to be uploaded.  (Use similar model to the offering CSV upload: https://teams.microsoft.com/l/message/19:meeting_YmYwNTBjZmQtMDBkMS00YmYzLTliZDEtNzJhOGRiOTBjY2Ew@thread.v2/1689705689456?context=%7B%22contextType%22%3A%22chat%22%7D)

**Comment by guru-aot** [comment]
As per the existing design, changing the figma design from numbered to bullets as followed in offering upload 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbUE0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--50ae66176e9aa0652c3712c62aeeb6d45d606751/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbUU0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a8a82c28a78acd5f6334337b9acad3c96536809b/image.png)

**Comment by guru-aot** [comment]
@JasonCTang Please confirm the error messages on the validations, if anything needed to be changed, it had to be taken as part of next story #2112
