### ISSUE TITLE
Business validations for Bulk Withdrawal Upload

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#2112]
**Describe the task**
Business validations for Bulk Withdrawal Upload.
Assuming the file parsing and file format validation is already done the dependency ticket https://app.zenhub.com/workspaces/student-information-management-system-5fce9df5aa1b45000e937014/issues/gh/bcgov/sims/2111

**Reference figma Design**
https://www.figma.com/file/9Om2tzLAVEoMQrjmrH4fhu/MOD-SIMS?type=design&node-id=12566-163067&mode=design&t=LyYYv68zdOfihIDs-0

**Additional Context**

- File Layout: [https://app.zenhub.com/files/319429847/d246b205-1c6f-449d-b998-b8c75d8e08b2/download](https://app.zenhub.com/files/319429847/d246b205-1c6f-449d-b998-b8c75d8e08b2/download)
- File is based off all applications that have had an assessment since the last file was sent
- Workaround: Institutions that use a bulk withdrawal file still have the ability to enter withdrawals through Insitution Portal.
- Process each record as if it were an manually entered withdrawal. 
- Although this is an "integration" file, it currently still requires a manual process to be executed by the Institution user in SFAS where they have the opportunity to review the warnings prior to committing the changes to SFAS. Therefore, we are suggesting the same approach as the Bulk Offering Upload.
- Each record are proceeded as if it were a manually entered withdrawal.
- Only BC Public institutions are allowed to use and perform this upload.
- Only Institution Administrator role are allowed to perform this upload.
- Affected Student Application belongs to the institution uploading the file.
- Follow the same approach as bulk offering file upload, only process file if all records pass validation (all or nothing), display issues on the page, etc.

**Acceptance Criteria**
- [ ] Ensure that the affected Student Application belongs to the institution uploading the file.
- [ ] If the application number is not found, assume it is an SFAS application and just skip over it, do not perform any other validations on the record and proceed onto the next record to continue processing the file.  Generate warning to user: "Application number not found.  The withdrawal request for this application will not be processed."
- [ ] Create an interface in the SIMS application to upload the file, similar to the bulk offering file upload, using the same validation models structure.
    - [ ] In case one or multiple validations failed, return the validation errors.
    - [ ] Allow the process to be executed as validation only, that will check for the next for possible business validation errors but should not persist any data to the database. 
        - [ ] Validate if the combination of the SIN, Application number and institution match with a record on SIMS, if not, return the line as a warning message "Application number not found.  The withdrawal request for this application will not be processed."
        - [ ] For each record, validate if the application belongs to the institution location provided as the `originator` in the header of the file. [Confirmed with @HRAGANBC]. If the institution location for a record does not match as per the file `originator` field, throw the error "Application number not found.  The withdrawal request for this application will not be processed."
        - [ ] If the file contains a line for an application that already has a withdrawal recorded, return the line as a warning message "This application is already withdrawn and is going to be skipped." [Confirmed with @JasonCTang]
        - [ ] Verify if the application is in "Completed" status and not archived to execute the withdrawal, if not, return it as an error with the message "The application is not in the completed status." or "The application is already archived and cannot be withdrawn."
    - [ ] For every single file line that has an error or warning, a summary should be displayed.
        - [ ] Line number: record number including the header in the count.
        - [ ] Application Number (even if invalid): display the file content to show what was interpreted as the "Application Number".
        - [ ] Withdrawal Date (even if invalid): display the file content to show what was interpreted as the "Withdrawal Date".
        - [ ] Validations: display a user-friendly message about why the record was not considered valid.
        - [ ] If there is a withdrawal already in place- skip the record from processing.

**Comment by michesmith** [comment]
**Question**
- Why does the manual withdrawal entry check that the application has no ongoing assessments when applying the withdrawal? Is there a business reason for this or is it purely a technical reason? If technical, does moving assessment to a queue address this so that we can remove this requirement? -- this is covered with Que'd assessments
