### ISSUE TITLE
Content Fixes for Institution Account

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2123]
Following content fixes are needed to support Institution Account launch

**Acceptance Criteria**

- [x] **1. Update Help Text Next to Institution Location Code.**
Help text currently reads: "Unique 4 digit alpha code assigned the first time an institution is designated in Canada.
   - [x] Help text should read: "Unique 4 digit alpha code assigned the first time an institution is designated in Canada. If your institution has not yet been designated, input TEMP as a temporary Institution Location Code, and contact SABC to revise this code once your permanent code has been received."
![image.png](https://images.zenhubusercontent.com/62fc03010dde35d5a39ff930/dc1235ec-1c25-4cb6-8ccf-90c875bb60a4)

- [x] **NEW NOTE RE TEMP CODE** - Please revise above text to ""A Unique 4 digit alpha code assigned the first time an institution is designated in Canada. If your institution has not yet been designated, please input a random 4-letter code as a temporary Institution Location Code, and contact SABC to revise this code once your permanent code has been received. This code must be a valid federal education institution code prior to students submitting applications"

- [x] **2. Update banner message when institution attempts edits to program details after offerings are linked**. 
Current behavior - when editing a program with already-linked offerings, a banner message appears saying "this program already has students linked, and cannot be edited". 
   - [x] Expected behavior - this banner message should read "This program has study period offerings attached to it, and the program details can no longer be edited. If revisions are required other than to program name or program description, you must create a new program with the correct details." ![image.png](https://images.zenhubusercontent.com/62fc03010dde35d5a39ff930/89ab23e8-af04-4ae4-91cf-06ea225479b4)
   
- [ ] **3. Change all references to "Ministry of Advanced Education" in BC Private designation agreement to "Ministry of Post-Secondary and Future Skills.**
   - [ ]  Confirm that their is no garbage in test. " ![image.png](https://images.zenhubusercontent.com/62fc03010dde35d5a39ff930/e2e40c3a-a274-4a01-aeeb-0fe67639ff5f)
 
- [x] **4. Add a 'section header' called 'Designation Agreement' in the BC Private Designation Request screen.** 
   - [x] The header should encompass the existing sub-section headers titled "Signing Officers", "Agreement Documentation", and "Designation Acknowledgements"
 ![image.png](https://images.zenhubusercontent.com/62fc03010dde35d5a39ff930/b64ca7ac-1ca1-42cb-a590-2b78cc068e0f)

- [x] **5 . Change reference to the SIMS Administration Manual (Schedule B within BC Private Designation Requests) to "Schedule B - StudentAidBC Instructional Guide for Institutions".** 
   - [x] The hyperlink should send users to: _https://studentaidbc.ca/institution-officials_ as opposed to the current link, which sends them to the Admin manual (which is now obsolete).
   
  
- [x] **6. Update the instructions in "get started here" for Institutions.** 
Instructions for Step 1 currently read: "Begin by adding users from your institution who need access. Ensure you assign a role for a legal signing authority or additional admins as your require" 
   - [x] The instructions should instead read: "Begin by adding other users from your institution who will be account administrators. After creating your locations (Step 2), you can continue to add the basic users who will have access to particular locations" 
   - [x] Step 4 also needs revision. It should read: "Request designation for your institution. Request designation status even if you have already received designation from SABC in previous years.  
(https://images.zenhubusercontent.com/62fc03010dde35d5a39ff930/cde57c8c-e579-4411-8ffd-3ac8eab27311)

- [x] **7. Update content to Offering cost fields:** 
Content beneath the offering costs header currently reads: "Please add the costs for each section (use 0 if there are no costs). These costs must comply with the maximum allowable costs according to the SABC policy manual" 
   - [x] The content should read: "Please add the costs for each section (use 0 if there are no costs). These costs must comply with the maximum allowable costs according to the SABC policy manual. No amounts beyond the maximum allowable limits will be factored into a student's need assessment."

**Comment by HRAGANBC** [comment]
Following content fixes are needed to support Institution Account launch, but recognizing that the fixes themselves are not required ahead of August 3 release:

1. Add Help Text Next to Institution Location Code. Help text currently reads: "Unique 4 digit alpha code assigned the first time an institution is designated in Canada." Help text should read: "Unique 4 digit alpha code assigned the first time an institution is designated in Canada. If your institution has not yet been designated, input TEMP as a temporary Institution Location Code, and contact SABC to revise this code once your permanent code has been received."
![image.png](https://images.zenhubusercontent.com/62fc03010dde35d5a39ff930/dc1235ec-1c25-4cb6-8ccf-90c875bb60a4)

**Comment by HRAGANBC** [comment]
2. Change banner message when institution attempts edits to program details after offerings are linked. Current behaviour - when editing a program with already-linked offerings, a banner message appears saying "this program already has students linked, and cannot be edited". Expected behaviour - this banner message should read "This program has study period offerings attached to it, and the program details can no longer be edited. If revisions are required other than to program name or program description, you must create a new program with the correct details." ![image.png](https://images.zenhubusercontent.com/62fc03010dde35d5a39ff930/89ab23e8-af04-4ae4-91cf-06ea225479b4)
3. Change all references to "Mininstry of Advanced Education" in BC Private designation agreement to "Ministry of Post-Secondary and Future Skills" ![image.png](https://images.zenhubusercontent.com/62fc03010dde35d5a39ff930/e2e40c3a-a274-4a01-aeeb-0fe67639ff5f)
3. Add a 'section header' called 'Designation Agreement' in the BC Private Designation Request screen. The header should encompass the existing sub-section headers titled "Signing Officers", "Agreement Documentation", and "Designation Agknowledgements"
 ![image.png](https://images.zenhubusercontent.com/62fc03010dde35d5a39ff930/b64ca7ac-1ca1-42cb-a590-2b78cc068e0f)
4. Change reference to the SIMS Administration Manual (Schedule B within BC Private Designation Requests) to "Schedule B - StudentAidBC Instructional Guide for Institutions". The hyperlink should send users to: _https://studentaidbc.ca/institution-officials_ as opposed to the current link, which sends them to the Admin manual (which is now obsolete)
5. Change the instructions in "get started here" for Institutions. Instructions for Step 1 currently read: "Begin by adding users from your institution who need access. Ensure you assign a role for a legal signing authority or additional admins as your require" The instructions should instead read: "Begin by adding other users from your institution who will be account administrators. After creating your locations (Step 2), you can continue to add the basic users who will have access to particular locations" 
Step 4 also needs revision. It should read: "Request designation for your institution. Request designation status even if you have already received designation from SABC in previous years.  
(https://images.zenhubusercontent.com/62fc03010dde35d5a39ff930/cde57c8c-e579-4411-8ffd-3ac8eab27311)
6. Add content to Offering cost fields: Content beneath the offering costs header currently reads: "Please add the costs for each section (use 0 if there are no costs). These costs must comply with the maximum allowable costs according to the SABC policy manual" The content **should read**: "Please add the costs for each section (use 0 if there are no costs). These costs must comply with the maximum allowable costs according to the SABC policy manual. No amounts beyond the maximum allowable limits will be factored into a student's need assessment."

**Comment by ann-aot** [comment]
For AC 1, As per the current logic we won't be able to use `TEMP` for multiple locations.
I checked with @michesmith , She confirmed to go with the tooltip content for now and to create a ticket to discuss with the business and the business will possibly come up with a requirement.

**Comment by ann-aot** [comment]
created https://app.zenhub.com/workspaces/student-information-management-system-5fce9df5aa1b45000e937014/issues/gh/bcgov/sims/2200

**Comment by ann-aot** [comment]
Ac-1 is context is updated, as per https://app.zenhub.com/workspaces/student-information-management-system-5fce9df5aa1b45000e937014/issues/gh/bcgov/sims/2200
