### ISSUE TITLE
CSFA 2024/ 2025 -Program Year-  Cap for for our Fed Grants. 

### ISSUE THREAD

**Issue by michesmith** [bcgov/SIMS#2125]
@hugh / @Josh to start?

- [ ] What are the required changes from the Feds?
- [ ] What is the impact of updating this policy.? - Business Policy Review (Hugh) 
- [ ] What are the Camunda changes requirements (Signori)

- Rebecca Fontaine has the policy provide updates.

**Comment by HRAGANBC** [comment]
Closing this issue. It is replaced by placeholder ticker #2495 and placeholder Epic #2494

**Comment by gamahugh** [comment]
you probably meant to tag a different hugh :)
