### ISSUE TITLE
2.2.2 Student- Permanent Disability PD/PPD

### ISSUE THREAD

**Issue by michesmith** [bcgov/SIMS#2135]
**Context**

PD/PPD status students only need 40% course load to qualify for full time application.
PD/PPD status does not apply to Part Time applications. IE, if the student has a part time application with 50% course load and is granted PD/PPD status, while their course load technically qualifies them for a full time application, it DOES NOT automatically change them to full time. If they want full time, they would need to withdraw a part time application and start a new full time application.

-PD = Permanent Disability
-PPD = Persistent or Prolonged Disability (When performing assessments, treat this exactly the same as PD)
-Federal PPD legislation changes for Program Year 22/23 were implemented July 17
-Partner PPD status is out of scope (the question regarding partner permanent disability will not be expanded to include PPD)
-To reverify PPD status, students with PPD must attest that their PPD is still active on each application, through the single disability question
-PD/PPD status students only need 40% course load to qualify for full time application.
-PD/PPD status does not apply to Part Time applications. IE, if the student has a part time application with 50% course load and is granted PD/PPD status, while their course load technically qualifies them for a full time application, it DOES NOT automatically change them to full time. If they want full time, they would need to withdraw a part time application and start a new full time application.

Overall PD Requirements are attached in the process graphic. 

The most important distinction is that a student's PD/PPD **Application** status is what controls their assessment, but the student's PD/PPD **Profile** status is what controls their disbursements. 

PPD is not fully captured by the attached graphic, but the only difference is that an expiry date is attached to ATBC's 'approval' of a student's PPD profile request. 

Functional Testing Scenarios:

1. 
    -Expected Outcome:
2. 
   -Expected Outcome:
3. 
   -Expected Outcome:
4.
   -Expected Outcome:
5.
   -Expected Outcome:
6.
   -Expected Outcome:
7.
   -Expected Outcome:
8.
   -Expected Outcome:
9.
   -Expected Outcome:
10. 
   -Expected Outcome:

![PD,PPD in SIMS.png](https://images.zenhubusercontent.com/62fc03010dde35d5a39ff930/0250a081-42cc-4d4a-a737-b8c1dff0e6cd)  

[https://app.zenhub.com/files/319429847/689a856c-2013-4daf-a49c-e5e09b2e42d0/download](https://app.zenhub.com/files/319429847/689a856c-2013-4daf-a49c-e5e09b2e42d0/download)

**Comment by ann-aot** [comment]
**Analysis and questions**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBakcvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--79280af0bea959d235cbb333b64bb356378288c4/1.jpg)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaksvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--efe1c7cd2df7158850a7a096a89b848c5fa23524/2.jpg)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBak8vIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e573b2aebc988ab0b5f0f7e562a34160ac81af41/3.jpg)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBalcvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--dd55a385ba99d4657b3ad1b0cb1de9cb5857543c/4.jpg)

**Comment by ann-aot** [comment]
- If the students selects option 1 and if they are pending for the verification, still the system will generate the NOA with the PD/PPD with an content to the student indicating that "the awards can change depending on the ATBC verification" (content has been added in screenshot by Hugh) and they can accept the NOA and institution can accept the COE as well (again there will be a content indication the blockage). And during the e-cert the disbursement will be blocked as per the condition in the workflow.
