### ISSUE TITLE
Student Application Update-YEAF Revisions

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#2139]
This is fully replaced by #2102. Suggest closing this ticket altogether to avoid confusion.

@Jason- who does this downstream impact analysis? You? The Devs, me? Can we get ahead of the Devs here?
@Biz Team- Can you please screenshot all the places you see YEAF Content change to YIC.. This will help streamline things.
                    - Confirming Reporting Requirements "Report on all students YIC" (.. Discuss for MVP or?)
@All We need UX on this one- What is the standard for "banner below or hover over question mark?
- We likely need to break this ticket

**Describe the task**
Perform analysis on this information for reporting purposes.  
- What kind of reporting is needed? 
- Is the logic for this question already in the workflow? In other words, is this only a wording change or is this new functionality? 
- How will we know that the assessment has successfully waived the student contribution?
- What is the expected output of waived vs not waived funding amounts?

**Context**
Revise wording to use ‘youth in care’ as the umbrella term.  
Current question is worded as: “Were you ever a youth in continuing care…..”
Revised wording of the actual question should read: “Were you ever considered a child or youth under government care?”

Associated content (either help text displayed in the ‘?’ or wth a banner message underneath the question) should read “Government care could be qualified as Ministry of Children and Family Development (MCFD) or Indigenous Child and Family Service Agency [ICFSA] care, care through the Ministry of Social Development and Poverty Reduction [SDPR] Child in the Home of Relative Program or government care through a Canadian province or territory outside of B.C.)”

Question should have two options: yes or no.

Selecting ‘no’ has no impact.
Impact of selecting ‘Yes’ to this question should result in:
•	Indicating in database that this applicant is a former youth in care. This is for purposes of running a report to identify all youth in care students, so SABC can target additional funding programs to these students. 
•	Waiving the student fixed contribution for this application

Introduce new sub-question for anyone who answers ‘yes’ to being a former youth in care.

Question should read “Are you, or were you at the time of your 19th birthday, in continuing care or custody of a director of child welfare in B.C.
Associated content (either in “?’ or with banner underneath the question) should read: “This means that the provincial government is currently your legal guardian if you are younger than 19 or was your legal guardian at the time of your 19th birthday”

If student answers no, no effect. 
If student answers ‘yes’, then student is automatically converted to independent status and treated as independent for the entire assessment workflow. This independent status would overrule any other application logic which might suggest otherwise. 

**Acceptance Criteria**
- [ ] **1. Conduct Impact Analysis**
- [ ] Assess the down stream impacts of this change 
- [ ] Document the impacts in this ticket on the:
     - [ ]  The Impacts to Reporting. What kind of reporting is needed? 
     - [ ] Is the logic for this question already in the workflow? In other words, is this only a wording change or is this new functionality? 
     -  [ ] How will we know that the assessment has successfully waived the student contribution?
      - [ ] What is the expected output of waived vs not waived funding amounts?
      - [ ] Anything else?
- [ ] Confirm Impact Analysis with PO 
 ------------------------
- [ ] **2. Change YEAF Content (pending no major impacts identified)**: Revise wording to use ‘youth in care’ as the umbrella term across the whole application
----------------
- [ ] **3. Revise Student Application Question** Current question is worded as: “Were you ever a youth in continuing car…..”
-Change to: “Were you ever considered a child or youth under government care?”
 -----------
- [ ] **4. Question should have two options: yes or no as options**
- Selecting ‘no’ has no impact.
- Selecting ‘Yes’ to this question should result in: - Introducing new sub-question for anyone who answers ‘yes’ to being a former youth in care. (Details below in #6)
- [ ] **Reporting** Indicating in database that this applicant is a 'former youth in care'. This is for purposes of running a report to identify all youth in care students, so SABC can target additional funding programs to these students. 
- [ ] **Assessment** Waiving the student fixed contribution for this application. Is this Rule already in assessment
-------
- [ ] **5. Add Help Text -_(either help text displayed in the ‘?’ or with a banner message underneath the question)_**
-Help Text Should Read “Government care could be qualified as Ministry of Children and Family Development (MCFD) or Indigenous Child and Family Service Agency [ICFSA] care, care through the Ministry of Social Development and Poverty Reduction [SDPR] Child in the Home of Relative Program or government care through a Canadian province or territory outside of B.C.)”
 ---------
- [ ] **6. Introduce new sub-question for anyone who answers ‘yes’ to being a former youth in care**
New Question should read “Are you, or were you at the time of your 19th birthday, in continuing care or custody of a director of child welfare in B.C.
- If student answers no, no effect. 
- If student answers ‘yes’, then student is automatically converted to **independent status** and treated as independent for the entire assessment workflow. 
- [ ] **Independent Status** This independent status would overrule any other application logic which might suggest otherwise.

**Comment by michesmith** [comment]
@HRAGANBC -CLOSED
