### ISSUE TITLE
Student Application Updates: Enable dollar amount field for Financial Exceptional Expenses - FT Only

### ISSUE THREAD

**Issue by michesmith** [bcgov/SIMS#2143]
This was captured as part of Phase 1 Testing

**User Stories**
- As a Student I want to add a dollar amount to my Exceptional Expenses so that it can be considered with my entire expenses and increase my opportunity to receive more Financial Aid
- As Ministry Staff I want to review the exceptional expenses dollar amount as an exception request, and ensure that if approved, it is incorporated into a students Total Costs as part of their assessment. 

**Current behavior:** 
If a student selects ‘yes’ to the question, the following things currently occur:  

- Options are presented allowing student to indicate the reason for their decrease in income 
- Free text paragraph field allowing student to explain in their own words what their situation is 
- Document uploader tool prompted 
- Exception triggered in the application workflow. 

**Context and Expected Behavior**
There should be no maximum amount validation imposed by the system; exceptional cost field will always be reviewed by SABC staff before being approved and factored into the workflow, so staff will not approve the request unless it complies with our maximum limits.
If a student selects ‘yes’ to the question, the following things should occur:  
- Options are presented allowing student to indicate the reason for their decrease in income 
- Free text paragraph field allowing student to explain in their own words what their situation is 
- Document uploader tool prompted; then **add** a
- Numeric field where student can input a dollar amount. There is no maximum amount validation, this cost will always be reviewed by SABC and only if approved it will be factored into the workflow. 
- Exception triggered in the application workflow. 
- Approved value is added to calculatedDataTotalCosts 

**Acceptance Criteria**
The following apply **only** to the FT application
- [ ] Add a Numeric field where student can input a dollar amount. 
- [ ] Ensure that a student requesting exceptional expenses generates a dedicated exception card viewable by Ministry staff when reviewing the complete list of exceptions
- [ ] If exception is approved by SABC, the value will be added to a student's total costs

![image.png](https://images.zenhubusercontent.com/64b6f330bf2c3f481d13bc8d/fe3bced6-ee19-4add-8a68-1f9a88a2fe85)
 [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMW0vQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5aa77c217bbe572730293f53ff3df79d2446c493/image.png)

**Comment by CarlyCotton** [comment]
I've updated the acceptance criteria and expected behaviour.

**Comment by HRAGANBC** [comment]
@CarlyCotton Thanks Carly. Although we thought originally it should be mapped to the IER, I'm not sure anymore, and at a minimum don't know what field it would be mapped to. For context, in SFAS the exceptional expense was handled as an appeal, and the process varied about where staff would incorporate this expense (See Josh's email to Policy about this). If there was never a consistent way of handling this previously, it makes me think that there was probably never a dedicated field in legacy IER fields for it, and therefore there won't be a SIMS ier field for it either. 



Can you identify where in the IER it belongs?
