### ISSUE TITLE
Student Application Updates:  Remove Interface Policy Question

### ISSUE THREAD

**Issue by michesmith** [bcgov/SIMS#2145]
Given interface policy is being disabled for MVP, we’d like to ensure that it is entirely removed from the assessment workflow (at least for now). I am not clear about how much of this is ‘already built’. It might be the case that none of this was built to begin with, and therefore all the steps listed below don’t require any action. But at a minimum we want to review to confirm.  

 

Below is my understanding of the work required- all steps below apply equally to FullTime and PartTime 

 

Preserve the question in application titled “Will you have B.C. income assistance for persons with disabilities that you will be receiving under the Employment and Assistance for Persons with Disabilities Act during your study period?” (We may enable  
interface policy later on and so it’s useful to preserve the question) 

The impact at the above question should be NOTHING in the workflow. It is purely for information-only. 

SIMS should not integrate with SDPR at all 

Ensure that any steps in assessment workflow referencing “MSS” fields are bypassed. They can be preserved in the workflow in case we eventually build interface policy in the future, but for now, no students should be diverted down the interface policy path of the assessment workflow and should therefore not utilize any of the ‘MSS’ fields 

***Acceptance Criteria***
- [x] Leave BC income for disabiilities question in form.
- [x] Confirm that the answer to this question has no impact on the assessment workflow.
- [ ] Do not calculate MSS fields and ensure it has no impact on the assessment workflow.

**Comment by HRAGANBC** [comment]
Closing as this was just a discussion-prompt ticket, and the investigation has been closed.
