### ISSUE TITLE
Student Application Updates: PD/ PPD Form Update on application 

### ISSUE THREAD

**Issue by michesmith** [bcgov/SIMS#2147]
As a Student I want to apply for PD Status on my application too and not just when I first create an account with SABC as my situation may have changed and I need to understand the funding options if I claim PD 'PPD Status or not

**Additional Context**

Account PD/PPD status = False  AND Application PD/PPD question = Yes THEN no funds will go out until one of two events occurs:  
A. student requests change
B. Student auto reassessed at 2 weeks before end date.   

*If a student is already confirmed as PD at the account profile level then we STILL ask again. They have to be YES at Account Level and YES in the application in order to get PD Funding assessment. 
Technical analysis
There are 3 major areas which needs to be updated as part of this change.

1. Submitting PD request on application submit: Based on current PD status of the student and option 1 being selected in new PD question call to ATBC needs to happen. Should we consider queue for this? if so we need to have a way to handle the requests which failed to be sent to ATBC during their outage

2. Workflow code changes
The workflow derive the value for `studentPDStatus` based on the new question(application dynamic data)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWtKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ae78503238d38898e6a7a127adb0982b4228e814/image.png)

 new logic must be based on `newQuestion.option1`

Note: When we implemented PPD changes #2001 we left the existing(going to be obsolete) columns to not disturb the workflow logic. Now that workflow logic is being modified, should we create a seperate ticket to do the cleanup ?

3. Ecert Logic
Ecert validation must ensure that if option1 is selected in new question, then the PDStatus must be approved.
Possibly we must save the studentPDStatus variable to workflow_data.

**Note for Devs**: 
The functionality listed  below is correct , however the content wording may change pending usability testing. The Red arrow below indicates where a new section for "Disability Information" Is to be inserted
![image.png](https://images.zenhubusercontent.com/64b6f330bf2c3f481d13bc8d/2e82bdae-e98a-4cc8-8167-0bb5275f200f)

**Acceptance Criteria**
- [x] Add A new section header is added within the ‘personal information tab’ which is called “Disability Information”  
- [x] Under that header add the question, "Are you a student with disabilities and wish to be assessed for disability funding?”. This question should have the following three options: 
-1)  "Yes, I have a disability and want this application to be assessed for disability funding."  (there is no system action as result of this question being selected) 
-2)  "No, I want to access other funding types while I wait for a verification decision."
-3) "No, I do not have a disability. 
- [x] If student selects the first option, the assessment assumes PD/PPD status for assessment purposes, 
- [x]  AND, in the workflow use the form in form data for the disability status instead of student profile.
- [x] " If student selects the first option, then display the following message underneath the selected option “A student cannot receive funding until StudentAidBC has verified your disability status." This messaging also needs to clear at the account level.
- [x] If student selects 2 or 3, then assess as ‘generic’ student. (i.e. no PD/PPD applicable, regardless of whatever has been requested on the student’s profile) 
- [x] Change Camunda to PDPPD status per new question added- stop using PDPPD from student profile and consume status from application.

**Comment by ann-aot** [comment]
**_Analysis and question's_**
1. What is the differences between 1st and 2nd options?

- does the first options means, student profile is already verified for PD/PPD, and if the student wants to consider the disability status for an application, they selects option 1 ??
- does the second options means, student profile is already is either `pending` or `not requested` for PD/PPD, and if the student wants to consider the disability status for an application, they selects option 2 ?? and if the status is `not requested`, during application submission system will create a profile on ATBC server?
- does the third options means, student doesn't have a disability, so they never requested for it?

**Comment by ann-aot** [comment]
3. According to the AC, only for option 1, `Get the information from ATBC about the possible return information from the request PD.`. 
So, What if the student select option 2 in the application and submits it and then goes to the profile and request for the PD/PPD. And SIMS got a response from the ATBC confirming the disability ? According to the current AC, system won't consider the application for PD/PPD, since they haven't selected option 1, but student will know the flow, should there be at least some info banner, if they selected option 2

**Comment by ann-aot** [comment]
4. Is the screenshot in the https://app.zenhub.com/workspaces/student-information-management-system-5fce9df5aa1b45000e937014/issues/gh/bcgov/sims/2135 is the finial flow?

5. What happens, if the student opted for PD/PPD in their application and the were not confirmed before study end date? -> reassessment (more questions added in the https://app.zenhub.com/workspaces/student-information-management-system-5fce9df5aa1b45000e937014/issues/gh/bcgov/sims/2135 )

6. What should happens, if student an application with PD/PPD with a past offering end date or in the last 2 weeks of study end date?

**Comment by ann-aot** [comment]
10. If there is a student with PPD status, who submit an with application with PPD (selected option 1),  what will happen to the application or disbursements, if PPD expired before the study end date?
