### ISSUE TITLE
WAVA Scan Institution Mediums Analysis for Student Portal

### ISSUE THREAD

**Issue by michesmith** [bcgov/SIMS#2154]
**Description**
Generate plan and tickets to address medium vulnerabilities resulting from WAVA scan.

***Additional context***
https://bcgov.sharepoint.com/:b:/r/teams/03177/Shared%20Documents/DEVS/Releases/WAVA%20Scan/v1.2.0-930/1135713-https___test-aest-sims.apps.silver.devops.gov.bc.ca_student_1012Security_Issues%20(1).pdf?csf=1&web=1&e=fmPWg6

**Acceptance Criteria**
- [ ] Review 'MEDIUM' WAVA Scan Results of the Institution Release
- [ ] Determine which are false Positives and prove this to David Malcolm 
"There should be few False Positives – though there will be some. I’m open to alternative suggestions but would default to documenting the WAVA vulnerability and what procedure/test we applied in order to determine it was a False Positive in a SIMS JIRA ticket." ~David
- [ ] Create a plan to address these Mediums. (Should they be address with the results of a Student Scan?)
- [ ] Create tickets to implement fixes

**Comment by cditcher** [comment]
I am ordering another wava scan as the application has seen significant upgrades

**Comment by michesmith** [comment]
@JasonCTang requesting a fresh scan today
