### ISSUE TITLE
Pending Excepetion is listing overwritten application exception too

### ISSUE THREAD

**Issue by ann-aot** [bcgov/SIMS#2158]
Bug:
when a student have an application with exceptions and the exceptions is pending with ministry and before ministry approval, if he/she edit it and submit the application with another exception. The pending Exceptions data table in ministry is listing all the expectation irrespective of the "overwritten` status. I believe we are missing the application status check. In below screenshots,  2 of them are overwritten 
![image.png](https://images.zenhubusercontent.com/608872f7d0d25cdfe8dab75d/d4319ae1-c033-46cd-b2e6-448f2916cf75)

- [x] Add application status check in the query
- [x] Check application status during exception update.
- [x] Create an E2E test for this specific scenario.

**Comment by HRAGANBC** [comment]
@ann-aot Thanks for catching this, I was just about to make a similar ticket. 

Can I please point out that PIR has the same problem, i.e. 'overwritten' PIR requests appear in the Institution PIR queue as well, making it very complicated for institution staff to know which one to action
