### ISSUE TITLE
Question:  Welcome Pages for Institution and Ministry 

### ISSUE THREAD

**Issue by michesmith** [bcgov/SIMS#2160]
What is the Effort to update Content on the the Instition and Ministry ... for Announcements? Is this a deployment to production or a quick thing?

Jason to talk to hugh to confirm reqiurements

**Comment by michesmith** [comment]
@HRAGANBC can you describe more what you want to update- what is the userstories here ;)

**Comment by HRAGANBC** [comment]
Closing as this is replaced by other tickets
