### ISSUE TITLE
Revise Questions and Content on Parent Tab  (FT only)

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2168]
**@all This requires UX Designer updates how can we handle this?**

**Current Behavior**
- Student application identifies student as dependant, and prompts the 'parent' tab on application form. The Following questions appear: 
- "Is your parent(s) a resident of BC"? (if 'no' is selected, no exception is triggered)
- Does your parent(s) have valid SIN? (if 'no' is selected, student self-reports their parental income)
- How many parents do you live with? (the number selected determines how many slots of parents info are required to progress app)

**Problems:**
- If student is a dependant and parents are not residents, student should not be eligible for funding. Therefore selecting 'no' should trigger an exception path. 
- Question suggests BOTH parents have to be resident, but that's not the case. Only one parent needs to be resident to satisfy policy requirements. 
- Ordering of questions and wording of questions is confusing

**Expected Behavior:**
- Student application identifies student as dependant, and prompts the 'parent' tab on application form. Questions should appear as follows, and be re-worded to reflect the following:
- "How many parents/sponsors/legal guardians/step-parents support you financially?" (This is what will dictate how many parent info slots are required to be filled out by parents OR through the self-report feature.
- "Is at least one of your parents/sponsors/legal guardians/step-parents a resident of B.C.?" (If 'no' is selected for this question, the exception path MUST be triggered)
- "Are each of your parents/sponsors/legal guardians/step-parents eligible for a B.C. Services Card?". Help text should read "All applicable parents/sponsors/legal guardians/step-parents must provide their information to StudentAid BC by logging in with a B.C. Services Card. If they are ineligible for a B.C. Services Card (for e.g. if they do not have a valid SIN), select 'no' to this question and provide information on their behalf." If 'no' is selected to this question, add a banner message which reads "If parents cannot access a B.C. Services Card, the student will need to report parental information on their behalf. Please be aware this information will be subject to review by StudentAid BC and may delay a student's application" 
------

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNytDQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7af516629c97d732f9532eef2bd97a4b5c53b37a/Parent%20Tab.JPG)

**Acceptance Criteria**
- [ ] Re-configure questions consistent with the above screenshot

**Comment by HRAGANBC** [comment]
[Uploading... Parent Tab.JPG]

**Comment by CarlyCotton** [comment]
@JerPearson Feel free to close if you think your FT app review has covered the concerns on the ticket.

**Comment by JerPearson** [comment]
Closing ticket as work captured already on other tickets.
