### ISSUE TITLE
Make Self-Report More Similar to Parent/Partner Reporting 

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2169]
Considered non-critical for MVP; moving ticket to icebox

**Current Behavior**
- Regardless of whether 1 or 2 parents are identified, self-reporting feature requires their incomes be reported as combined amounts. Names of parents are not captured, and distinct income amounts for each parent are not possible within this system. 

**AC**
- Make parental reporting distinct per parent and ensure alignment in questions with supporting users portal

**Expected Behaviour**

![image.png](https://images.zenhubusercontent.com/62fc03010dde35d5a39ff930/4e01dd34-09ec-4a49-a8f4-af6d32573b08)

**Comment by CarlyCotton** [comment]
@JerPearson Popping this in SOAP with yourself assigned as it relates to your FT Application review. Feel free to close if you think you've got all you need from it.

**Comment by JerPearson** [comment]
Closing ticket as this ticket was for information purposes
