### ISSUE TITLE
Institution User Completes Institutions Account Profile Information

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#217]
**As ** *(Institution User)* **I want** *(Complete my Institutions Account Profile Information)* **So That** *(I can communicate with SABC).

**Additional Context**
- enter text here

**Acceptance Criteria**
- [x] Given (Institution User), When (is completing an Institution Account Profile ), Then (they must provide the user email)

Given (Institution User), When (is completing an Institution Account Profile ), Then (they must provide the institutions:
- [x] Optional Institution Operating Name (this is different than their Legal name- which comes from Business BCeID) or they select my Legal Operating Name.
- [x] Institution Address: Address line 1, Address Line 2 (Optional), City, Province, Country, Postal Code
- [x] Institution Primary Phone Number
- [x] Institution Primary Email
- [x] Intitution Website
- [x] Established Date (may not be a future date)
- [x] Institutions Legal Authorized Authorities Contact Information- First Name, Last Name, Email, Phone Number
- [x] Instituiontions Primary Contact Information- First Name, Last Name, Email, Phone Number
- [x] Institution Regulating body that governs the institutions- A drop-down List (Private Act of BC Legislature, ICBC, DQAB, PTIB, ITA *update to include full name)

- [x] Given (An Institution User), When (selects save and all mandatory fields are not complete), Then (they are notified of mandatory fields required to complete the Profile
- [x] Given (An Institution User), When (selects save and mandatory fields are complete), Then (the profile information is saved)

Technical Tasks 
--------------------------------------------------

- [ ] Parse and display Token and Additional Information from BCeID
- [ ] Create fields for user input
- [ ] Show notification of mandatory fields on save
- [ ] Save to DB on complete
- [ ] ...
- [ ] ....

**Comment by abschwenker** [comment]
removed 2nd address field due to inconsistencies from stories and wireframe. Can add it with a future story if need
