### ISSUE TITLE
Revise Content of Partner Self-Report Feature

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2171]
**Description of Task**
Change the wording and help text associated with the question dictating whether partners report their own info or not

**Current Behavior**
- Question says "Does your partner have a valid SIN"

**Problem**
- Consistent with Ticket #2168, valid SIN is not necessarily the relevant question. This causes confusion.

**Acceptance Criteria**
- [x] Question **should** read "Is your partner eligible for a B.C. Services Card?" (Applies to PT and FT applications)
- [x] Help text **should** read _"Partners must provide their information to StudentAid BC by logging in with a B.C. Services Card. If they are ineligible for a B.C. Services Card (for e.g. if they do not have a valid SIN), select 'no' to this question and provide information on their behalf."_  (Applies to PT and FT applications)
- [x] If 'no' is selected to this question, revise the banner message to read _"If partners cannot access a B.C. Services Card, the student will need to report partner information on their behalf. Please be aware this information will be subject to audit and review by StudentAid BC and may delay a student's application"_  (Applies to PT and FT applications)
- [x]  Refactor backend and workflow to have a meaningful form IO API key name (Applies to PT and FT applications)
- [x] - Clean content Typos per screenshot below (these typos appear **only if a FT application** - these questions have been removed from PT form as per #2348)

![image.png](https://images.zenhubusercontent.com/62fc03010dde35d5a39ff930/34f928f3-2ce7-47c9-8084-139d6b6cc219)

**Comment by HRAGANBC** [comment]
@HRAGANBC - Review ACs to remove unnecessary partner questions (similar to #2348)

**Comment by lewischen-aot** [comment]
@andrewsignori-aot @dheepak-aot @HRAGANBC @guru-aot @andrepestana-aot @sh16011993 @katrina-aot @Joshua-Lakusta @CarlyCotton 
For this part of the acceptance criteria -- refactor backend and workflow to have a meaningful form IO API key name (Applies to PT and FT applications) -- the current API key for the question "Does your partner has a valid Social Insurance Number" is "isYourSpouseACanadianCitizen". This API key and its associated student data is used in 23 files for Camunda workflows, E2E tests and Form.io. The new API key name I'm thinking about is "isYourPartnerEligible", and please let me know if there is a better name for it. I'm leaving a comment here to keep everyone on the same page before raising the PR for review.

**Comment by CarlyCotton** [comment]
@lewischen-aot 
I'm concerned that isYourPartnerEligible is a little too ambiguous within an assessment. Some suggestions to capture what is being asked about the partner:

- isYourPartnerAbleToReport
- doesPartnerHaveBSCS
- isPartnerBCSCHolder

**Comment by lewischen-aot** [comment]
Thanks @CarlyCotton for the suggestions. I think I would go for "isPartnerBCSCHolder" as it captures the question "Is your partner eligible for a B.C. Services Card?" (part of the AC in this story) quite well. I can use this name if we all agree @andrewsignori-aot @dheepak-aot.

**Comment by andrewsignori-aot** [comment]
@lewischen-aot I would recommend the first suggestion from @CarlyCotton. BCSC is mentioned there just because it is the current authentication method for the Supporting Users Portal. To be less based on the current authentication and more focused on the business I would go with `isYourPartnerAbleToReport`.

**Comment by lewischen-aot** [comment]
Thanks @CarlyCotton @andrewsignori-aot It's confirmed that we will go with `isYourPartnerAbleToReport`.
