### ISSUE TITLE
Add Content-Only 'System Updates' section to Institution Account Landing-page

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2173]
@Hugh- Need to confirm Text for Header and Placeholder Text
**@Michelle (replied Sep 1) - Please note - this ticket shouldn't be treated as a requirement - it is a flag for us to discuss how easily something like this can be implemented and updated relatively frequently going forward. Also, ACs added to respond to your initial question. 

**Context**
We would like to alert the Institutions of upcoming enhancements to the system on their landing page.

**Acceptance Criteria**

- [ ] Add a simple text-only section on the landing page of the institution account to allow SABC to communicate recent and upcoming system changes to Institution users.  This Section would ideally be editable directly by someone on the SABC side or at minimum could be updated by Dev team between deployment productions. 
- [ ] Add Header called "StudentAid BC System Announcements"
- [ ] Add Text blurb referenced below 

Text Blurb:

Date Edited: **manually Input date of edits** 

Known Enhancements Coming Soon:
- "Undergraduate Citation" credential type being added in coming months. Please refrain from adding programs using this credential for now. 
- CIP codes which begin with 19, 49, and 52 are currently not functioning correctly and are being resolved in coming months. Please refrain from inputting programs with these CIP codes for now.

![image.png](https://images.zenhubusercontent.com/62fc03010dde35d5a39ff930/d599920f-ec9c-43b4-aeb2-45187b5d6d5a)

**Comment by HRAGANBC** [comment]
@michesmith Adding back to Lather just to prompt quick convo about feasibility

**Comment by ninosamson** [comment]
Two options for this: 
1. Form.io component can be built and updated by IMB 
2. Ministry users can post banners in their Ministry account that show up on the institution portal. 

devs to demo option 1 to see if this is feasible for MVP.

**Comment by michesmith** [comment]
Closing Duplicate as part of 2x milestone planning discussion
