### ISSUE TITLE
Queued Assessments - Assessment Status Review

### ISSUE THREAD

**Issue by andrewsignori-aot** [bcgov/SIMS#2188]
@HRAGANBC Do we want to display the second set of statuses below (Assessment statuses) to the student or do we want them only to see the first list (Current UI statuses), in which case, we would need to create a mapping between the two lists?

Review the below places along the application where the student's assessment status is being defined from the `workflow_id` and `assessment_date` and change to use the new student assessment status.

- [x] Change [Assessment history](https://github.com/bcgov/SIMS/blob/672f0a4ab89c89cf945cb198f4e778849a182ff5/sources/packages/backend/apps/api/src/services/student-assessment/student-assessment.service.ts) to return the status directly from the assessment status column.
  - [x] Check with the business the expected mapping to be displayed in the UI.
    - Current UI statuses
      - Submitted
      - In progress
      - Completed
    - Assessment statuses
      - Submitted
      - Queued
      - In progress
      - Completed
      - Cancellation requested
      - Cancellation queued
      - Cancelled
    - Proposed mapping (left is what the UI would display)
      - **Submitted**: `Submitted`
      - **In progress**: `Queued` or `In progress`
      - **Completed**: `Completed`
      - **Cancelled**: `Cancellation requested` or `Cancellation queued` or `Cancelled`. We currently do not display this status to the Student because the entire application tracker would not be displayed.

**Comment by andrewsignori-aot** [comment]
@HRAGANBC please check the "Proposed mapping" updated in the ticket.

**Comment by HRAGANBC** [comment]
@andrewsignori-aot Looks great to me, thanks
