### ISSUE TITLE
Analyze tickets in PD/PPD Epic to determine maturity of the requirements and compile list of outstanding questions

### ISSUE THREAD

**Issue by michesmith** [bcgov/SIMS#2193]
Analyze tickets in PD/PPD Epic to determine maturity of the requirements and compile list of outstanding questions for both the business and ATBC.
Refer to workflow graphic in EPIC ticket.

Some questions for ATBC we discussed so far (subject to change): 
- ATBC API where we request the student profile to be created is now failing.
- Our code uses D8Y_TYPE and D8Y_DTE to set the PD status on our end.
- Want to confirm that D8Y_DTE is when they PD status has been approved.
- Because PD requests are never "denied" and left open, what happens if we try to request PD status for the student again?How will we know they already have an existing record?
- What does the sfasDate querystring parameter mean in the API URL?

**Comment by ann-aot** [comment]
**_Analysis by Ann_**
- At the time of analysis, ATBC endpoints are not working[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcm11IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7a80791552afdc3e9b9ada471038b5eca22f990a/image.png)
