### ISSUE TITLE
Application and cancellation unexpected error

### ISSUE THREAD

**Issue by Joshua-Lakusta** [bcgov/SIMS#2194]
Critical: Yes, it is blocking all testing

 

Where: Student Portal
When: Submission of all new applications or cancellations
Who: 3 Testers have reported this issue as of this morning

See attached screen shots[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbzhIIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2112a8118c7bed7a7e9fbfa43d393e0f15704cae/Capture0.PNG)

 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcEFIIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c68d19804c26e4c6ac4649a13430be4dd90549b9/MicrosoftTeams-image.png)

**Comment by michesmith** [comment]
Bug resolved itself auto magically
