### ISSUE TITLE
URGENT- `TEMP` location code can't be added for multiple location as per current dev logic

### ISSUE THREAD

**Issue by ann-aot** [bcgov/SIMS#2200]
This will create a lot of bugs in prod. 

As per the AC-1 of the ticket https://app.zenhub.com/workspaces/student-information-management-system-5fce9df5aa1b45000e937014/issues/gh/bcgov/sims/2123
`TEMP` location code won't be able to add to multiple locations, as it will throw below error,
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaDhPIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f85027b50efa074df4988226e0b9b538ef5fd93a/image.png)

If this logic is to be implemented along side of code duplication error, then we might to skip the duplicate check when location code is `TEMP`

**Comment by HRAGANBC** [comment]
@ann-aot  Thanks for pointing that out. 

You can revise the help text to read: " "Unique 4 digit alpha code assigned the first time an institution is designated in Canada. If your institution has not yet been designated, input a random 4-letter code as a temporary Institution Location Code, and contact SABC to revise this code once your permanent code has been received. This code must be a valid federal education institution code prior to students submitting applications"

**Comment by michesmith** [comment]
@ann-aot Ive updated this in #2123 and have moved this to close
