### ISSUE TITLE
Unable to submit partner declaration  

### ISSUE THREAD

**Issue by Joshua-Lakusta** [bcgov/SIMS#2202]
**Describe the Bug**
Unable to submit partner declaration as the portal says the application is not expecting a partner declaration.

**Expected Behaviour**
When an application is submitted with a partner (married or common law) it should allow the submission of a partner declaration.
**Actual Behaviour**
It is not allowing the submission of the partner declaration and is providing the following error message.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbjBPIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--76f9afbd22b2e9ee022a03e30b82fc9879c0db4c/MicrosoftTeams-image%20%281%29.png)

**Steps To Reproduce**
Submit application with married and common law selected as yes. 
Submit a date for common law or married that is prior to start of study period
Go to partner portal and enter the application number, name, and date of birth to access the application.
Enter declaration information 
Click submit (at this point the error message appears)

**Comment by Joshua-Lakusta** [comment]
Parent1 BCSC:  SIMS00053 / 98900029 
Student:  Gail Garden
App:  2023000612

**Comment by HRAGANBC** [comment]
This was re-tested November 22 and is no longer an issue. Closing ticket
