### ISSUE TITLE
Get Environments Access Links to Ops Team

### ISSUE THREAD

**Issue by michesmith** [bcgov/SIMS#2210]

**Comment by JasonCTang** [comment]
From: Tang, Jason PSFS:EX 
Sent: Monday, August 21, 2023 5:14 PM
To: Johnson, Harold A PSFS:EX <Harold.A.Johnson@gov.bc.ca>; Marchesan, John PSFS:EX <John.Marchesan@gov.bc.ca>; Shekhar, Shashank X PSFS:EX <Shashank.X.Shekhar@gov.bc.ca>; Wang, Yumeng 1 PSFS:EX <Yumeng.1.Wang@gov.bc.ca>; Bisseck, Andre PSFS:EX <Andre.Bisseck@gov.bc.ca>; Marsh, Kal PSFS:EX <Kal.Marsh@gov.bc.ca>; Mohan, Gurumoorthy PSFS:EX <Gurumoorthy.Mohan@gov.bc.ca>; Alnahari, Mohammed PSFS:EX <Mohammed.Alnahari@gov.bc.ca>
Cc: Malcolm, David PSFS:EX <David.Malcolm@gov.bc.ca>; Ragan, Hugh PSFS:EX <Hugh.Ragan@gov.bc.ca>; Klemmensen, Danielle PSFS:EX <Danielle.Klemmensen@gov.bc.ca>
Subject: RE: SIMS Operational Readiness

Hey John and Harry

To address Harry’s comment first, I noticed the error too, but the version of the document that the warning points you to (4.13) is actually older than the one we have linked (4.2), so I suspect someone’s just made a boo boo on their site.  Regardless, I reviewed the instructions and they have not changed; it instructs you to download the tool directly from our own SIMS Openshift instance and therefore, will always be the correct version for our environment (until OCIO upgrades OpenShift to a version that isn’t backwards compatible.)  To make it even easier, I have included a direct link to the download file from our environment. 

Anyway, I have plucked out the tools from the Wiki documentation that require manual download of the installation files and included links for everyone’s convenience in a list below.  These are primarily the development tools, while the development environment is created by downloading images from GitHub and deploying them locally.  I have included links to where those instructions start in our Wiki documentation.  There are no license keys required for any of the installs.  All licensing is either open source or subscription based 

As well, I have included a list of access required.  Please let me know if anything is missing.

Development Tools & Local Environment Setup
There are a few tools that require explicit installations to be downloaded an executed to begin.  Once those tools are installed, you will be downloading the SIMS github repository and deploying images to stand up a local dev environment on your workstation.
1)	Visual Studio Code
a.	https://code.visualstudio.com/download
b.	Install list of additional plugins and follow setup instructions on this page: https://github.com/bcgov/SIMS/wiki/Development---Standards,-Decisions,-and-Troubleshooting#development-environment-setup 
2)	Camunda Desktop Modeler
a.	With the move to Camunda Platform 8, this tool has apparently become optional as the function is now incorporated into the Camunda platform itself.  That said, you may prefer the Desktop Modeler, so I have included the link. 
b.	https://camunda.com/download/modeler/
3)	Openshift command line interface tool.
a.	https://downloads-openshift-console.apps.silver.devops.gov.bc.ca/amd64/windows/oc.zip
b.	Obtain connection scripts from existing developer.
4)	Database Tool.  You can use any tool of your preference, provided it will connect to a Postgres database. 
5)	Docker tool
a.	https://docs.docker.com/desktop/install/windows-install/
6)	From here, you will be deploying images to stand up a local dev environment on your workstation.  The first step is to execute Step 5 in the pre-requisites section on the following page and continuing on from there:  https://github.com/bcgov/SIMS/wiki/DevOps-and-Running-the-Application#prerequisites


ACCESS
1.	Github
a.	Any existing member of a Github organization can invite a new user via their Github ID.
b.	Grant access to both BCGOV organization and BCGOV/SIMS organization
i.	https://github.com/bcgov/ 
c.	https://github.com/bcgov/SIMS/ 
2.	Rocketchat
a.	Access Is granted via an automated process
b.	Login using IDIR or Github ID
c.	https://chat.developer.gov.bc.ca/home 
3.	Zenhub
a.	Access is inherited from Github access.
b.	Login using Github ID
c.	https://app.zenhub.com/workspaces/sims-601318b9c746fc001c3b52cf/board
4.	Openshift (Silver Cluster)
a.	Granted by SIMS OpenShift admin
b.	https://console.apps.silver.devops.gov.bc.ca/ 
c.	Environments organized by “projects”
i.	0c27fb-prod
ii.	0c27fb-tools
iii.	0c27fb-test
iv.	0c27fb-dev
5.	Keycloak access
a.	Granted by SIMS Keycloak Admin
b.	Login using IDIR
c.	Environments
i.	PROD-RH-SSO Admin Console
ii.	TEST-RH-SSO Admin Console
iii.	DEV-RH-SSO Admin Console
6.	Camunda access
a.	Granted by SIMS Camunda Admin
b.	Environments are managed using “organizations”
i.	SIMS-PROD: Not issued by vendor yet
ii.	SIMS-QA: https://console.cloud.camunda.io/org/641613ac-8fae-4954-9acc-342a9888f289
iii.	SIMS-TEST: https://console.cloud.camunda.io/org/21a2c18d-ab8f-4c9a-97f6-b98ff63530be
iv.	SIMS-DEV:  https://console.cloud.camunda.io/org/6404759e-ad1d-43da-9487-7bdfd4ced9c0


Jason Tang
Technical Architect
Technology and Business Transformation Branch
Post-Secondary Educations and Future Skills
Phone: 250-580-7932

From: Johnson, Harold A PSFS:EX <Harold.A.Johnson@gov.bc.ca> 
Sent: Monday, August 21, 2023 4:41 PM
To: Marchesan, John PSFS:EX <John.Marchesan@gov.bc.ca>; Tang, Jason PSFS:EX <Jason.Tang@gov.bc.ca>; Shekhar, Shashank X PSFS:EX <Shashank.X.Shekhar@gov.bc.ca>; Wang, Yumeng 1 PSFS:EX <Yumeng.1.Wang@gov.bc.ca>; Bisseck, Andre PSFS:EX <Andre.Bisseck@gov.bc.ca>; Marsh, Kal PSFS:EX <Kal.Marsh@gov.bc.ca>; Mohan, Gurumoorthy PSFS:EX <Gurumoorthy.Mohan@gov.bc.ca>; Alnahari, Mohammed PSFS:EX <Mohammed.Alnahari@gov.bc.ca>
Cc: Malcolm, David PSFS:EX <David.Malcolm@gov.bc.ca>; Ragan, Hugh PSFS:EX <Hugh.Ragan@gov.bc.ca>; Klemmensen, Danielle PSFS:EX <Danielle.Klemmensen@gov.bc.ca>
Subject: RE: SIMS Operational Readiness

This appears to be a set of instructions, but it might be out of date?   (at least, that’s a warning that comes up on the OpenShift client instructions)

DevOps and Running the Application · bcgov/SIMS Wiki · GitHub

Getting started with the CLI - OpenShift CLI (oc) | CLI tools | OpenShift Container Platform 4.2




From: Marchesan, John PSFS:EX <John.Marchesan@gov.bc.ca> 
Sent: Monday, August 21, 2023 4:35 PM
To: Tang, Jason PSFS:EX <Jason.Tang@gov.bc.ca>; Shekhar, Shashank X PSFS:EX <Shashank.X.Shekhar@gov.bc.ca>; Johnson, Harold A PSFS:EX <Harold.A.Johnson@gov.bc.ca>; Wang, Yumeng 1 PSFS:EX <Yumeng.1.Wang@gov.bc.ca>; Bisseck, Andre PSFS:EX <Andre.Bisseck@gov.bc.ca>; Marsh, Kal PSFS:EX <Kal.Marsh@gov.bc.ca>; Mohan, Gurumoorthy PSFS:EX <Gurumoorthy.Mohan@gov.bc.ca>; Alnahari, Mohammed PSFS:EX <Mohammed.Alnahari@gov.bc.ca>
Cc: Malcolm, David PSFS:EX <David.Malcolm@gov.bc.ca>; Ragan, Hugh PSFS:EX <Hugh.Ragan@gov.bc.ca>; Klemmensen, Danielle PSFS:EX <Danielle.Klemmensen@gov.bc.ca>
Subject: RE: SIMS Operational Readiness

Hey Jason,

We are hoping to get a comprehensive list of the software and licenses required to set up Harry, Mo and Kal as full developers.  If you could get the list to Harry tomorrow he can try to install all the items and then use Friday to debug anything that doesn’t work.  Harry can then show Mo and Kal how to get set up.

If Harry can get everything set-up and we don’t need Friday for that debugging then here are a couple other topics,

In no particular order:
Camunda orientation of the specific Program Year set up and the process to modify for new program years
Database orientation, what are the db’s where are they located, general schema, etc
Logging scheme, what is critical to be logged and monitored on the environment, separate from the how and technology choice
General architecture overview (like the attached PTIB document)

This should be enough to get us going.

John



John Marchesan
john.marchesan@gov.bc.ca
Phone: 778-974-4073
Mobile:250-213-3238
Director, Digital Services for Students and Schools
Technology and Business Transformation Branch
Ministry of Post Secondary Education and Future Skills
