### ISSUE TITLE
Confirm Priority of Content Fixes Institution 

### ISSUE THREAD

**Issue by michesmith** [bcgov/SIMS#2211]
Ann has fixed the "content and workflow updates" per ticket #2123

 We want to confirm the priority.. 
Is this intended to be a "HOT FIX" into prod urgently OR can it wait untill the Next Release of which we could plan to do when we roll out to Privates.

There would be a bit of work to pull out the code from main in order to just Release these updates to Prod. But if its a political priority no probs

**Comment by HRAGANBC** [comment]
@Michelle: None of these are required for HotFix - all can be deployed with other release. Thanks for checking

**Comment by hugh** [comment]
FYI: @HRAGANBC @michesmith I don't think I am the "hugh" that you mean to be tagging here, please check with your team and find out your "Hugh's" username?  Thanks!

**Comment by HRAGANBC** [comment]
Complete
