### ISSUE TITLE
Remaining IER12 (Blue Feilds)

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#2222]
Perform analysis on oustanding fields in the file: 

https://bcgov.sharepoint.com/:x:/r/teams/03177/Shared%20Documents/General/Analysis/Institution%20File%20Specs/IER12_Analysis_Output_and_Mapping_Part_1_V2.xlsx?d=wdb2ac7bfe3c04c788c1fdae81fe84504&csf=1&web=1&e=HLDbkN

- Fields marked Blue correspond directly to a field in the database or camunda workflow.
- Fields marked in Yellow requires further analysis to find the related field, if it exists.  Context/logic has been provided in the form of comments. 
- Fields marked Grey, we have decided to allocate the space, but leave blank for now (do we default to 0 for dollar values or leave them blank?)
- Fields marked in Red indicate a change
- 
Related to #2276

**Acceptance Criteria**
- [x] Map remaining fields to the IER12 file. 
- [x] Saving workflow data
- [x] Add 10th blank award fields to the end of the file.

### Sample Output File

[IER_012_2023-09-21_08.32.57.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb1hHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--65d6d6b9186ca3dc37d121cc06744e81f8ab3e0e/IER_012_2023-09-21_08.32.57.txt)

### Position of each IER field(blue fields)

Student Marital Status Code: 104
Level of study code: 316
Scholastic Standing Code: 496
Contribution expected from applicant and spouse: 516
Contribution expected from parents: 526
Total Contribution expected: 536
Family dependant quantity: 561
Family members quantity: 564
Contribution from assets expected from parents: 580
Contribution from income expected from parents: 590
Parent discretionary income: 610
Student living at home flag: 630
Total educational expenses: 642
Dependant living allowance: 672
Student living allowance: 682
Total living allowance: 692
Alimony costs: 702
Child care costs: 742
Total non educational costs: 752
Total expenses: 762
Assessed need: 772
Student ELigible Award: 782
Student Marital Status Code: 104
Level of study code: 316
Scholastic Standing Code: 496
Contribution expected from applicant and spouse: 516
Contribution expected from parents: 526
Total Contribution expected: 536
Family dependant quantity: 561
Family members quantity: 564
Contribution from assets expected from parents: 580
Contribution from income expected from parents: 590
Parent discretionary income: 610
Student living at home flag: 630
Total educational expenses: 642
Dependant living allowance: 672
Student living allowance: 682
Total living allowance: 692
Alimony costs: 702
Child care costs: 742
Total non educational costs: 752
Total expenses: 762
Assessed need: 772
Student ELigible Award: 782

**Comment by dheepak-aot** [comment]
Analysis on application event codes.

Note: This analysis has been done considering that the assessments of the applications with application_status overwritten is not considered. Current IER12 logic does not ignore overwritten applications.

### Application event code logic to be developed.

Logic 1: Based on application number check if there is more than one application rows to it. Check this only when application status is assessment. To check REIA.
`select count(id) from sims.applications a where a.application_number = '$APPLICATION_NUMBER' `

Logic 2: 

Check the disbursement_feedback_errors feedback table for one or more errors which belongs to given list of FT Error codes. Check this only when disbursement schedule status is sent. To check DISE.

Logic 3:

Check if the student has any active restriction of action type 'Stop full time disbursment' and disbursement date is after cutoff date (current date + 5). Check this condition only when discursement schedule status is pending.  To check DISR

Logic 4:
Check if the restriction_amount_subracted > 0. Check this condition only when disbursement schedule status is sent. To check DISW.

### Process flow to find the event code.

`if application status = Assessment`

then

check Logic 1  if true REIA else ASMT end.

`if application status = Enrolment`

then if coe_status = Required  COER else COED (If not required status must be declined) end.

`if disbursement_schedule_status = Cancelled`
then DISC end.

`if application_status = completed`

then 

 `if disbursement_schedule_status = Pending`
 Check Logic 3 if true DISR else COEA
 
 `if disbursement_schedule_status = Sent`
 Check logic 4 if true then DISW else DISS.
 
 When DISE and DISS is not present and disbursement schedule is sent, it is considered to be sent successful without any anomalies.

**Comment by dheepak-aot** [comment]
## Questions on application status codes and IER

- Should IER consider assessments of application in overwritten status?
- COER vs DISR status: When a disbursement has a coe which is waiting for approval from institution and assume that the coe has not been approved until disbursement_date and the student has restriction. With this situation should we return COER or DISR ? 
- Consider a disbursement which has been sent to finastra and this disburesment had some funds withheld due to restriction at the time of e-cert generation(DISW). After the disbursement is sent to finastra we got disbursement feedback errors(DISE). should we return DISW or DISE ?
- Should DISW and DISE override DISS ?
