### ISSUE TITLE
Ensure Scholastic Standing Events have correct impacts to re-assessments, COE requests, and requirement to 'accept' the new NoA 

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2227]
Danielle Klemmensen performed testing to support this analysis. Outcomes are in Hugh's email, but have yet to beincorporated into ticket below. 

**Questions**
- Should we require student to approve new assessments anytime there are changes?
- Should we generate new COE request anytime there is a reassessment?
- Should we allow multiple scholastic standing events reported on an application? E.g. UC and then WD later
- Any impact to pro-rating assessment amounts based on new end dates?

Create a table of all inputs and outputs for scholastic standing events (eg results in a NOA or COE)

**Current Behaviour:**

Student Request a Change --> Ministry Approves --> Reassessment occurs --> New Disbursement created --> New COE request generated 

School Initiates Changes to Program Info --> Reassessment occurs --> Student Approves Changes --> Ministry Approves --> New Disbursement created --> New COE request generated

Withdrawal Reported --> Reassessment occurs --> New Disbursement created --> New COE request generated

UC Weeks Reported --> Restrictions applied

Early Completion reported --> Reassessment occurs --> New Disbursement created --> New COE request generated

Restriction Removed --> (???TBD whether reassessment occurs)

**Comment by CarlyCotton** [comment]
@Joshua-Lakusta Identified as something to be confirmed via testing for analysis

**Comment by michesmith** [comment]
THis is an old ticket with multiple duplicates covering the issues listed here
