### ISSUE TITLE
SFAS to SIMS Data Bridge Partial Match 

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2235]
**User Story**
As a ministry user, I want to know when a student closely matches a record in our legacy system to make sure we capture students who may have had a name change or SIN change since using the legacy system. This may need to be manually reviewed to update student profiles to ensure all relevant information is communicated between systems.

**Acceptance Criteria**
- [x] Identify partial matches when comparing new student profiles **on creation** in SIMS to legacy data (2/3 for SIN/DOB/LastName)
- [x] When there is a partial match create email to the ministry to review (studentaidbc@gov.bc.ca ):
> SUBJ: Partial Student Profile Match: ((LastName))
> > Email Body:
> >
> > There was a partial match in SIMS to a Legacy Student Account, 2 out of 3 fields matched (Date of Birth, SIN, Last Name).
> > The following fields matched: ((list field types that matched, not the data))
> > Please review SFAS/SAIL and SIMS to determine if further action is required.
> > Name: ((givenNames)) ((lastName))
> > Date of Birth: ((dob))
> > Email: ((studentEmail))
> > Date/Time: ((date/time))

**Technical**
- [x] New email template need to be created on GC Notify.
- [x] Create DB migration to insert the new email notification type.
- [x] Check should be added to the centralized student [creation method](https://github.com/bcgov/SIMS/blob/main/sources/packages/backend/apps/api/src/services/student/student.service.ts#L173).
- [x] Create a new single query to check if a combination of 2 out 3 data matches.
- [x] Generate the message t populate the email body "The following fields matched".
- [x] E2E Test for at least one of the student account creation scenarios to ensure that the partial match with generate the email on database.

**Business Context**
- When new student creates profile in SIMS, we check SFAS database for SIN, DOB, Last Name. Only if all three fields are perfect match do we match the students and import their data. 
- Some students will have changed their name since being in SFAS, in which case our system will not recognize them. 
- If we cannot identify these students, their OA and restrictions and identity validation will not be able to be carried over.

**Comment by CarlyCotton** [comment]
To be discussed with SD/Nat for solutioning
