### ISSUE TITLE
SFTP LINDA SERVER Remediation / Solution 

### ISSUE THREAD

**Issue by michesmith** [bcgov/SIMS#2265]
Need to be reinstated for Go Live. 
Secure File Transfer Protocol. (SFTP) Files.

**Comment by cditcher** [comment]
@michesmith is this related to ticket #[2007](https://app.zenhub.com/workspaces/student-information-management-system-5fce9df5aa1b45000e937014/issues/gh/bcgov/sims/2007)?

**Comment by michesmith** [comment]
@JasonCTang is this a duplicate- see above comment
