### ISSUE TITLE
Ministry Trigger Manual Reassessment 

### ISSUE THREAD

**Issue by michesmith** [bcgov/SIMS#2272]
**User Story**
As a ministry user, I need to be able to trigger a manual reassessment on behalf of a student so that newly updated information can be incorporated into a student's assessment. This is important when the student cannot trigger the re-assessment themselves because of the specific status of their application (e.g. status is 'complete') or because there is no mechanism for any users to capture the new changes to their information (e.g. new Overawards) 

**Acceptance Criteria**
- [x] Create button on Ministry 'assessment history' page which opens Modal for confirmation & notes (see Mock-up 1)
- [x] In Modal, staff can add comments associated to student applications. Students cannot see these. B.C. Publics **can** see these. (see Mock-up 2)
- [x] If re-assessment is triggered, conduct new assessment using all existing application inputs. I.e. skip to the place in the application gateway where assessment is performed. 
- [x] When re-assessment is completed, assign new label called "manual re-assessment" for the 'type' when displaying the assessment history to Ministry and Institution screens. 
- [x] UX/UI component - see mock-ups above. This reflects the Ministry view ONLY. BC Public Institutions should not see this new 'Re-assessment trigger' section 
- [x] Button is enabled if the assessment is in completed status. 
- [x] Archived applications cannot have assessments re-triggered. 
- [x] Business Validations on selecting the button: available on all applications which ITS ORIGINAL ASSESSMENT have reached "COMPLETED" status (no difference if application is pre- or post- COE or pre- or post-Disbursement)
- [x] Ensure the user can still edit the application before completion even after a manual re assessment was triggered
- [x] Set to keycloak role "admin"

**Technical**
- [x] Created a new trigger type named "Manual reassessment" adding a new item to Postgres Enum.
- [x] Create the new entry in the `sims.student_assessments` table to allow the new assessment to start. Base the values in the current assessment as usual, and ensure `offeringId` and `studentAppealId`(if present) are copied.
- [x] Create the Ministry note in the "Application" category.
- [x] Use the mockups as a reference but use the components already in place to create the UI.
- [x] Regarding "Button is enabled if the assessment is in completed status." we will consider the status of the original assessment associated with the application right now where the assessment status (not the application one) should be `Completed`. Ensure button validation is also enforced by the API (this AC was adjusted during PR review due to the adjustment in the business AC as per comments in this ticket).
- [x] Ensure that Keycloak role instructions are part of the release instructions.
- [x] E2E test for the new endpoint.

**Note:** Ministry may need to re-trigger other areas in the workflow. E.g. re-trigger exceptions request, re-trigger COE request, re-trigger eCert generation. These are handled in #2731

**Context:**
- Currently, assessment workflow is only triggered automatically via one of several triggers (scholastic standing event reported, all application info is confirmed submitted, etc..) None of these triggers are initiated by the Ministry user (i.e. even 'Request a Change' requires student to initiate the action)
- Currently, there is no method of manually triggering the assessment workflow by a ministry user
- Several use cases demand that Ministry users be able to manually trigger the assessment workflow. For e.g:
1. A BCSL Lifetime Max restriction is resolved/removed by Ministry staff, and eligible BCSL funding will not be disbursed until the next time an assessment is generated

---

**Mock-Up 1**
<img width="1047" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjM0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--90b37e5e82ae59131019907b593aae49a90c885b/image.png" alt="image.png" />

**Mock-Up 2**
<img width="1012" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFQ0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f0145ec86239d9db2c8cd6e042eaa2df315cac0f/image.png" alt="image.png" />

---

**Comment by hugh** [comment]
@michesmith - you probably mean a different hugh that isn't me!

**Comment by michesmith** [comment]
Apologies yes this is meant for another Hugh.. Nice to meet you ‘Zen Hugh’

Michelle Smith (She/Her)
Product Manager- Student Information Management System (SIMS)
Information Management Branch
Post-Secondary Education and Future Skills
Phone: 1-604-356-5607

**Comment by ninosamson** [comment]
Business team to clean up ticket for grooming - clarify UI and remove questions and move to "grooming" pipeline.

**Comment by andrewsignori-aot** [comment]
As per the conversation with @HRAGANBC the below AC
_Business Validations on selecting the button: available on all applications which have reached "assessment" status (no difference if application is pre- or post- COE or pre- or post-Disbursement)_

Should be

_Business Validations on selecting the button: available on all applications which **ITS ORIGINAL ASSESSMENT** have reached "completed" status (no difference if application is pre- or post- COE or pre- or post-Disbursement)_

The idea was to ensure that the application had passed the "in progress" phase and it would be ready for reassessments.

@HRAGANBC can the AC be adjusted as the above and then I will update the technical ones also to reflect it?

**Comment by HRAGANBC** [comment]
@andrewsignori-aot from our discussion, I thought our decision was "Business Validations on selecting the button: available on all applications which ITS ORIGINAL ASSESSMENT have reached "ASSESSMENT" status (no difference if application is pre- or post- COE or pre- or post-Disbursement)

**Comment by HRAGANBC** [comment]
@andrewsignori-aot Agree with your above revision, noting that your reference to "completed" refers to the status of the assessment workflow, NOT the status of the application itself. 

I have switched the AC accordingly. Thanks
