### ISSUE TITLE
Remaining IER12 Analysis   (Yellow...) 

### ISSUE THREAD

**Issue by michesmith** [bcgov/SIMS#2276]
Perform analysis on outstanding fields in the file: 

https://bcgov.sharepoint.com/:x:/r/teams/03177/Shared%20Documents/General/Analysis/Institution%20File%20Specs/IER12_Analysis_Output_and_Mapping_Part_1_V2.xlsx?d=wdb2ac7bfe3c04c788c1fdae81fe84504&csf=1&web=1&e=HLDbkN

- Fields marked Blue correspond directly to a field in the database or camunda workflow.
- Fields marked in Yellow requires further analysis to find the related field, if it exists.  Context/logic has been provided in the form of comments. 
- Fields marked Grey, we have decided to allocate the space, but leave blank for now (do we default to 0 for dollar values or leave them blank?)
- Fields marked in Red indicate a change
- 
Related to #2222

**Acceptance Criteria**
- [x] Map remaining fields to the IER12 spreadsheet analysis 
- [x] Timebox analysis to 1 week 
- [x] Update #2277 with details if required.

**Comment by guru-aot** [comment]
Fields that have mapping but needs some calculation:
- Family dependent child quantity
- Family dependent daycare quantity
- Family dependent infant quantity
- Family dependent other quantity
- Family dependent post secondary quantity
- Spouse in school flag

Fields with direct mapping:
- Family parent 1 flag
- Family parent 2 flag
- Volunteered contribution from parents
- Parental discretionary income annual formula result
- Spouse’s student loan payment costs

Fields populated by future tickets or tickets need to be created
- Extra local transportation costs - Need to be created
- Extra shelter costs - #2146 
- Other discretionary costs - #2143 
- Return transportation costs - Need to be created
- Disbursement Expiry Date - Need to be created
