### ISSUE TITLE
Mapping IER12 fields resulting from analysis ticket of yellow rows

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#2277]
Mapping outstanding fields that result from the analysis of the yellow rows of the file in ticket #2276
File: https://bcgov.sharepoint.com/:x:/r/teams/03177/_layouts/15/Doc.aspx?sourcedoc=%7BDB2AC7BF-E3C0-4C78-8C1F-DAE81FE84504%7D&file=IER12_Analysis_Output_and_Mapping_Part_1_V2.xlsx&action=default&mobileredirect=true

**Fields to Map**
9 Fields that have mapping but needs some calculation: (Implement the calculations in Camunda and return them as a variable before the IER12 file generation)
- Family dependent child quantity
- Family dependent daycare quantity
- Family dependent infant quantity
- Family dependent other quantity
- Family dependent post secondary quantity
- Family parent 1 flag
- Family parent 2 flag
- Parental discretionary income annual formula result
- Spouse in school flag

**Acceptance Criteria**
- [x] Map 9 fields to IER12 file  (These are currently highlighted in yellow in the attached spreadsheet and listed above) 
- [x] Null out new fields in Camunda
- [x] Save data from Camunda Workflow

**Comment by dheepak-aot** [comment]
## Index positions of all IER Fields 

Assessment Id: 1
Disbursement id: 11
Application Number: 21
Institution Student Number: 31
SIN: 43
Student Last Name: 52
Student Given Name: 77
Date of Birth: 92
Student Group Code: 100
Student marital status code: 104
Student PD status code: 108
Application PD status flag: 112
Address line 1: 113
Address line 2: 138
City: 163
Province code: 188
Postal or zip code: 192
Program Name: 208
Program description: 233
Credential type: 283
Field of study code: 308
Area of study code: 312
Level of study code: 316
Current program year: 320
Cip code: 322
NOC code: 328
SABC Program code: 333
Institution program code: 337
Program length: 362
Study Start Date: 363
Study End Date: 371
Tuition: 379
Books and Supplies: 389
Mandatory Fees: 399
Exception expenses: 409
Total funded weeks: 419
Course load: 421
PT FT Indicator: 424
Application submitted date: 425
Program year ID: 433
Application Status Code: 441
Application Status Date: 445
CSL amount: 453
BCSL amount: 463
EP amount: 473
Provincial default flag: 483
Federal default flag: 484
Provincial overaward flag: 485
Federal overaward flag: 486
Restrictions: 487
Scholastic Standing Effective Date: 488
Scholastic Standing Code: 496
Assessment date: 500
Withdrawal date: 508
Contribution expected from applicant & spouse: 516
Contribution expected from parents: 526
Total contribution expected: 536
Family dependent child quantity: 546
Family dependent daycare quantity: 549
Family dependent infant quantity: 552
Family dependent other quantity: 555
Family dependent post secondary quantity: 558
Family dependent quantity: 561
Family members quantity: 564
Family parent 1 flag: 567
Family parent 2 flag: 568
Family spouse flag: 569
Parental assets: 570
Contribution from assets expected from parents: 580
Contribution from income expected from parents: 590
Volunteered contribution from parents: 600
Parental discretionary income: 610
Parental discretionary income annual formula result: 620
Student living at home flag: 630
Spouse in school flag: 631
Other educational expenses: 632
Total educational expenses: 642
Extra local transportation costs: 652
Extra shelter costs: 662
Dependent living allowance: 672
Student living allowance: 682
Total living allowance: 692
Alimony costs: 702
Other discretionary costs: 712
Return transportation costs: 722
Spouse's student loan payment costs: 732
Childcare costs: 742
Total non-educational costs: 752
Total expenses: 762
Assessed Need: 772
Student Eligible Award: 782
MSS assessed need flag: 792
MSS assessed need: 793
MSS assessed need normal or appeal: 803
MSS child care costs: 813
MSS tuition and supplies: 823
MSS miscellaneous costs allowance: 833
MSS transport costs allowance: 843
MSS extra transport costs: 853
Application event code: 863
Application event date: 867
Document produced date: 875
Confirmation of Enrolment Status: 883
Disbursement Status: 893
Earliest Date of Disbursement: 903
Date of Disbursement: 911
Disbursement Expiry Date: 919
Disbursement Cancel Date: 927
Funding Type CSLF: 935
Funding Type BCSL: 949
Funding Type CSGP: 963
Funding Type CSGD: 977
Funding Type CSGF: 991
Funding Type CSGT: 1005
Funding Type BCAG: 1019
Funding Type SBSD: 1033
Funding Type BGPD: 1047
Funding Type Empty: 1061

**Comment by dheepak-aot** [comment]
Yellow Fields index

Family dependent child quantity: 546
Family dependent daycare quantity: 549
Family dependent infant quantity: 552
Family dependent other quantity: 555
Family dependent post secondary quantity: 558
Family parent 1 flag: 567
Family parent 2 flag: 568
Parental discretionary income annual formula result: 620
Spouse in school flag: 631
