### ISSUE TITLE
Application Status Error On Ministry and Student  'assessment history' page

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2286]
**Application number: 2023000656**

The above application number had an exception request which was submitted, and approved. Immediately after approving the exception, the application went to the assessment stage, however the application status appears as 'complete' on the ministry 'assessments' screen. (See photo below). Application status should be 'assessment'

The exact same error applies for the student assessment screen (see second photo below). **Note: In the student screen, see the highlighted text, which should be changed to 'history of **assessments**', not history of applications

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaFNMIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--885641e2e75349a5cf5a77aff048c5c0d9456590/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaHVMIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2944843ad2e92d59fb24bc53f0d990685afca3f4/image.png)

**Comment by michesmith** [comment]
@HRAGANBC- per Signori and Dheepak  The assessment history table shows the assessment status not the application status.  Knowing this is it still a bug. AND does this get tagged to the Part-time Release?

**Comment by HRAGANBC** [comment]
@michesmith 

Thanks for clarifying - in that case, problem solved and I'm closing the ticket. Thanks!
