### ISSUE TITLE
Load Testing of Form.io using Student Application submission.

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#2287]
**Describe the task**
Load testing for Form.io submission.  Test using the Student Application to test the amount of submission that the form.io server can handle under different configurations and pod numbers. As a suggestion, we can have a Student Application payload sample submitted multiple times directly to the form.io server and check how the form.io server handles the requests till it stops.

**Acceptance Criteria**
- [x] Determine and document load testing strategy in wiki.
- [x] Document testing instructions in wiki so that the process can be repeated.
- [x] Run multiple test to check the performance by increasing the number of PODs and modifying CPU/memory per POD.
- [x] Produce reporting of output vs pod#s/CPU/memory configuration. 
  - Jason/Michelle to identify the location to save this report.
- [x] Identify the best configuration and modify the YAML file to standardize future deployment.

**Additional context**

**Comment by andrewsignori-aot** [comment]
dev-forms
- 2 PODs
- 

checks.........................: 100.00% ✓ 977      ✗ 0
data_received..................: 8.7 MB  65 kB/s
data_sent......................: 3.7 MB  27 kB/s
http_req_blocked...............: avg=81.24ms  min=0s       med=35.86ms max=1.23s   p(90)=157.88ms p(95)=367.93ms
http_req_connecting............: avg=16.38ms  min=0s       med=15.56ms max=89.78ms p(90)=18.51ms  p(95)=19.93ms
http_req_duration..............: avg=11.78s   min=199.45ms med=11.44s  max=22.52s  p(90)=16.07s   p(95)=16.84s
  { expected_response:true }...: avg=11.78s   min=199.45ms med=11.44s  max=22.52s  p(90)=16.07s   p(95)=16.84s
http_req_failed................: 0.00%   ✓ 0        ✗ 978
http_req_receiving.............: avg=893.38µs min=0s       med=0s      max=16.09ms p(90)=1.65ms   p(95)=5.45ms
http_req_sending...............: avg=49.36µs  min=0s       med=0s      max=1ms     p(90)=53.82µs  p(95)=505.54µs
http_req_tls_handshaking.......: avg=64.71ms  min=0s       med=19.82ms max=1.22s   p(90)=138.56ms p(95)=350.97ms
http_req_waiting...............: avg=11.78s   min=185.99ms med=11.44s  max=22.51s  p(90)=16.07s   p(95)=16.84s
http_reqs......................: 978     7.300393/s
iteration_duration.............: avg=12.87s   min=278.96ms med=12.49s  max=23.58s  p(90)=17.11s   p(95)=18.17s
iterations.....................: 977     7.292928/s
vus............................: 5       min=5      max=100
vus_max........................: 100     min=100    max=100

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHdnQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e867ecef5bdea2c8bbd17b01be9b078d099432cc/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDhnQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--be8b1b3a6ad3745fb7d93a12a5a2f871de3e4df4/image.png)

**Comment by andrewsignori-aot** [comment]
### dev-forms (2 PODs)

```ts
export const options = {
  vus: 400,
  duration: "300s",
};
```

checks.........................: 3.44%  ✓ 140       ✗ 3923
data_received..................: 23 MB  70 kB/s
data_sent......................: 15 MB  46 kB/s
http_req_blocked...............: avg=118.31ms min=0s       med=38.25ms max=2.2s    p(90)=385.01ms p(95)=633.94ms
http_req_connecting............: avg=32.96ms  min=0s       med=15.85ms max=1.03s   p(90)=56.04ms  p(95)=147.81ms
http_req_duration..............: avg=29.65s   min=192.39ms med=30.01s  max=35.01s  p(90)=30.08s   p(95)=31.02s
  { expected_response:true }...: avg=16.1s    min=192.39ms med=19.08s  max=25.7s   p(90)=25.32s   p(95)=25.39s
http_req_failed................: 96.53% ✓ 3923      ✗ 141
http_req_receiving.............: avg=306.23µs min=0s       med=0s      max=15.65ms p(90)=813.5µs  p(95)=1ms
http_req_sending...............: avg=41.92µs  min=0s       med=0s      max=2ms     p(90)=0s       p(95)=505.68µs
http_req_tls_handshaking.......: avg=85.27ms  min=0s       med=21.05ms max=2.12s   p(90)=268.27ms p(95)=454.95ms
http_req_waiting...............: avg=29.65s   min=192.39ms med=30.01s  max=35.01s  p(90)=30.08s   p(95)=31.02s
http_reqs......................: 4064   12.306113/s
iteration_duration.............: avg=30.77s   min=243.25ms med=31.06s  max=36.06s  p(90)=31.59s   p(95)=32.15s
iterations.....................: 4063   12.303085/s
vus............................: 3      min=3       max=400
vus_max........................: 400    min=400     max=400

**Comment by andrewsignori-aot** [comment]
### dev-forms (4 PODs)

```ts
export const options = {
  vus: 400,
  duration: "300s",
};
```

checks.........................: 43.74% ✓ 2153      ✗ 2769
data_received..................: 35 MB  105 kB/s
data_sent......................: 18 MB  56 kB/s
http_req_blocked...............: avg=84.79ms  min=0s       med=34.39ms max=1.24s   p(90)=201.64ms p(95)=398.49ms
http_req_connecting............: avg=31.17ms  min=0s       med=15.21ms max=1.02s   p(90)=30.26ms  p(95)=129.76ms
http_req_duration..............: avg=24.5s    min=271.25ms med=30s     max=31.12s  p(90)=30.01s   p(95)=30.02s
  { expected_response:true }...: avg=17.42s   min=271.25ms med=15.96s  max=30.93s  p(90)=27.96s   p(95)=28.94s
http_req_failed................: 56.24% ✓ 2769      ✗ 2154
http_req_receiving.............: avg=562.77µs min=0s       med=0s      max=16.24ms p(90)=1.02ms   p(95)=2.45ms
http_req_sending...............: avg=46.85µs  min=0s       med=0s      max=1.52ms  p(90)=0s       p(95)=513.28µs
http_req_tls_handshaking.......: avg=53.39ms  min=0s       med=18.86ms max=1.22s   p(90)=122.52ms p(95)=262.31ms
http_req_waiting...............: avg=24.5s    min=271.25ms med=30s     max=31.12s  p(90)=30.01s   p(95)=30.02s
http_reqs......................: 4923   14.903407/s
iteration_duration.............: avg=25.58s   min=322.68ms med=31.04s  max=32.51s  p(90)=31.08s   p(95)=31.22s
iterations.....................: 4910   14.864052/s
vus............................: 23     min=23      max=400
vus_max........................: 400    min=400     max=400

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2dnQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--345ed9db3c11589c0827d5c1dc697aa9e8e1ea94/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2tnQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3730196ed69d60918cb5740908f8ff4a477b618d/image.png)

**Comment by andrewsignori-aot** [comment]
### dev-forms (5 PODs)

```ts
export const options = {
  vus: 400,
  duration: "300s",
};
```

checks.........................: 53.94% ✓ 3060      ✗ 2612
data_received..................: 40 MB  122 kB/s
data_sent......................: 21 MB  64 kB/s
http_req_blocked...............: avg=82.56ms  min=0s       med=34ms    max=1.28s   p(90)=164.96ms p(95)=305.85ms
http_req_connecting............: avg=32.62ms  min=0s       med=15.14ms max=1.05s   p(90)=30.36ms  p(95)=91.07ms
http_req_duration..............: avg=21.02s   min=283.02ms med=27.29s  max=31.32s  p(90)=30.01s   p(95)=30.02s
  { expected_response:true }...: avg=13.41s   min=283.02ms med=11.76s  max=30.22s  p(90)=26.58s   p(95)=28.09s
http_req_failed................: 46.04% ✓ 2612      ✗ 3061
http_req_receiving.............: avg=657.41µs min=0s       med=0s      max=45.41ms p(90)=1.16ms   p(95)=2.93ms
http_req_sending...............: avg=46.94µs  min=0s       med=0s      max=1.41ms  p(90)=0s       p(95)=507.97µs
http_req_tls_handshaking.......: avg=49.82ms  min=0s       med=18.6ms  max=1.26s   p(90)=59.87ms  p(95)=210.29ms
http_req_waiting...............: avg=21.02s   min=283.02ms med=27.29s  max=31.32s  p(90)=30.01s   p(95)=30.02s
http_reqs......................: 5673   17.170718/s
iteration_duration.............: avg=22.09s   min=377.08ms med=28.4s   max=32.6s   p(90)=31.06s   p(95)=31.13s
iterations.....................: 5658   17.125317/s
vus............................: 15     min=15      max=400
vus_max........................: 400    min=400     max=400

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN01nQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7266b33952fc5de424a341957446507b05348669/image.png)

[Uploading... image.png]

**Comment by andrewsignori-aot** [comment]
### dev-forms (6 PODs with CPU max reduced from 2 to 1.5)

```ts
export const options = {
  vus: 400,
  duration: "300s",
};
```

checks.........................: 74.00% ✓ 5317      ✗ 1868
data_received..................: 53 MB  159 kB/s
data_sent......................: 27 MB  80 kB/s
http_req_blocked...............: avg=67.8ms   min=0s       med=33.58ms max=1.97s   p(90)=109.53ms p(95)=245.46ms
http_req_connecting............: avg=28.18ms  min=0s       med=14.91ms max=1.04s   p(90)=19.77ms  p(95)=56.35ms
http_req_duration..............: avg=16.2s    min=236.73ms med=12.31s  max=31.36s  p(90)=30.01s   p(95)=30.01s
  { expected_response:true }...: avg=11.4s    min=236.73ms med=10.49s  max=30.03s  p(90)=17.15s   p(95)=21.57s
http_req_failed................: 25.99% ✓ 1868      ✗ 5318
http_req_receiving.............: avg=682.08µs min=0s       med=0s      max=43.75ms p(90)=1.27ms   p(95)=3.25ms
http_req_sending...............: avg=37.75µs  min=0s       med=0s      max=1.42ms  p(90)=0s       p(95)=503.7µs
http_req_tls_handshaking.......: avg=39.53ms  min=0s       med=18.19ms max=1.11s   p(90)=47.28ms  p(95)=151.38ms
http_req_waiting...............: avg=16.2s    min=236.22ms med=12.31s  max=31.36s  p(90)=30.01s   p(95)=30.01s
http_reqs......................: 7186   21.722509/s
iteration_duration.............: avg=17.26s   min=803.71ms med=13.36s  max=32.64s  p(90)=31.06s   p(95)=31.07s
iterations.....................: 7178   21.698326/s
vus............................: 11     min=11      max=400
vus_max........................: 400    min=400     max=400

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFFnQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--109b31a51ab3304c70e7dc044b9f004a50c180fb/image.png)

**Comment by andrewsignori-aot** [comment]
### dev-forms (6 PODs with CPU max reduced from 2 to 1.5)

```ts
export const options = {
  vus: 100,
  duration: "60s",
};
```

checks.........................: 100.00% ✓ 1427      ✗ 0
data_received..................: 11 MB   170 kB/s
data_sent......................: 5.2 MB  79 kB/s
http_req_blocked...............: avg=43.56ms  min=0s       med=32.55ms max=1.3s    p(90)=66.32ms  p(95)=129.69ms
http_req_connecting............: avg=13.68ms  min=0s       med=14.55ms max=77.57ms p(90)=19.83ms  p(95)=27.26ms
http_req_duration..............: avg=3.3s     min=306.8ms  med=2.94s   max=10.35s  p(90)=5.5s     p(95)=6.21s
  { expected_response:true }...: avg=3.3s     min=306.8ms  med=2.94s   max=10.35s  p(90)=5.5s     p(95)=6.21s
http_req_failed................: 0.00%   ✓ 0         ✗ 1428
http_req_receiving.............: avg=829.68µs min=0s       med=0s      max=16.33ms p(90)=1.47ms   p(95)=4.24ms
http_req_sending...............: avg=60.26µs  min=0s       med=0s      max=2.41ms  p(90)=502.63µs p(95)=505.49µs
http_req_tls_handshaking.......: avg=29.71ms  min=0s       med=17.61ms max=1.28s   p(90)=46.27ms  p(95)=97.66ms
http_req_waiting...............: avg=3.29s    min=306.12ms med=2.94s   max=10.35s  p(90)=5.49s    p(95)=6.2s
http_reqs......................: 1428    21.674525/s
iteration_duration.............: avg=4.35s    min=392.57ms med=3.98s   max=11.48s  p(90)=6.55s    p(95)=7.27s
iterations.....................: 1427    21.659346/s
vus............................: 7       min=7       max=100
vus_max........................: 100     min=100     max=100

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzhoQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a49c181fc7989be09f8eff4fad9089e04e4c87b5/image.png)

**Comment by andrewsignori-aot** [comment]
### dev-forms (4 PODs with CPU max reduced from 2 to 1.5) - 98% pass

```ts
export const options = {
  vus: 150,
  duration: "60s",
};
```

### dev-forms (6 PODs with CPU max reduced from 2 to 1.5) - 100% pass

```ts
export const options = {
  vus: 150,
  duration: "60s",
};
```

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVloQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--70804449c4f972799c3ace1b99851c5507f95b81/image.png)

**Comment by andrewsignori-aot** [comment]
### dev-forms (2 PODs with CPU max reduced from 2 to 1.5) - 100% pass

```ts
export const options = {
  vus: 60,
  duration: "60s",
};
```

checks.........................: 100.00% ✓ 377      ✗ 0
data_received..................: 3.4 MB  49 kB/s
data_sent......................: 1.4 MB  21 kB/s
http_req_blocked...............: avg=65.17ms min=0s       med=34.8ms  max=1.14s   p(90)=70.87ms p(95)=188.85ms
http_req_connecting............: avg=17.07ms min=0s       med=15.3ms  max=49.59ms p(90)=24ms    p(95)=27.89ms
http_req_duration..............: avg=9.19s   min=253.47ms med=8.59s   max=21.79s  p(90)=13.06s  p(95)=15.27s
  { expected_response:true }...: avg=9.19s   min=253.47ms med=8.59s   max=21.79s  p(90)=13.06s  p(95)=15.27s
http_req_failed................: 0.00%   ✓ 0        ✗ 378
http_req_receiving.............: avg=426µs   min=0s       med=0s      max=14.91ms p(90)=1ms     p(95)=1.44ms
http_req_sending...............: avg=39.64µs min=0s       med=0s      max=1.66ms  p(90)=0s      p(95)=506.23µs
http_req_tls_handshaking.......: avg=47.98ms min=0s       med=19.16ms max=1.12s   p(90)=43.23ms p(95)=173.89ms
http_req_waiting...............: avg=9.19s   min=253.47ms med=8.59s   max=21.79s  p(90)=13.06s  p(95)=15.27s
http_reqs......................: 378     5.510567/s
iteration_duration.............: avg=10.26s  min=322.82ms med=9.68s   max=23.82s  p(90)=14.28s  p(95)=16.35s
iterations.....................: 377     5.495989/s
vus............................: 9       min=9      max=60
vus_max........................: 60      min=60     max=60

**Comment by andrewsignori-aot** [comment]
```ts
export const options = {
  vus: 65,
  duration: "1000s",
};
```

checks.........................: 99.91% ✓ 7323     ✗ 6
data_received..................: 60 MB  52 kB/s
data_sent......................: 27 MB  23 kB/s
http_req_blocked...............: avg=66.9ms   min=0s       med=34.64ms max=1.37s   p(90)=92.6ms   p(95)=258.1ms
http_req_connecting............: avg=14.46ms  min=0s       med=15.12ms max=1.03s   p(90)=17.33ms  p(95)=19.25ms
http_req_duration..............: avg=7.81s    min=240.56ms med=7.76s   max=23.75s  p(90)=9.95s    p(95)=10.54s
  { expected_response:true }...: avg=7.81s    min=240.56ms med=7.76s   max=23.75s  p(90)=9.95s    p(95)=10.54s
http_req_failed................: 0.08%  ✓ 6        ✗ 7324
http_req_receiving.............: avg=384.84µs min=0s       med=0s      max=20.34ms p(90)=962.92µs p(95)=1.16ms
http_req_sending...............: avg=43.98µs  min=0s       med=0s      max=1.5ms   p(90)=0s       p(95)=503.7µs
http_req_tls_handshaking.......: avg=52.41ms  min=0s       med=19.02ms max=1.35s   p(90)=68.32ms  p(95)=241ms
http_req_waiting...............: avg=7.81s    min=240.56ms med=7.76s   max=23.75s  p(90)=9.95s    p(95)=10.54s
http_reqs......................: 7330   6.339102/s
iteration_duration.............: avg=8.88s    min=293.02ms med=8.83s   max=24.8s   p(90)=11.01s   p(95)=11.62s
iterations.....................: 7329   6.338238/s
vus............................: 22     min=22     max=65
vus_max........................: 65     min=65     max=65

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK01oQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7fe5d34ca621b18a6a3956b62feff1d2ae0ca564/image.png)

**Comment by andrewsignori-aot** [comment]
checks.........................: 99.98% ✓ 13135     ✗ 2
data_received..................: 93 MB  92 kB/s
data_sent......................: 47 MB  47 kB/s
http_req_blocked...............: avg=36.63ms  min=0s       med=32.44ms max=1.39s  p(90)=45.86ms p(95)=74.12ms
http_req_connecting............: avg=11.05ms  min=0s       med=14.35ms max=1.04s  p(90)=16.87ms p(95)=19.72ms
http_req_duration..............: avg=3.91s    min=237.45ms med=2.22s   max=30.01s p(90)=9.03s   p(95)=12.58s
  { expected_response:true }...: avg=3.9s     min=237.45ms med=2.22s   max=29.85s p(90)=9.03s   p(95)=12.56s
http_req_failed................: 0.01%  ✓ 2         ✗ 13136
http_req_receiving.............: avg=752.12µs min=0s       med=0s      max=44.3ms p(90)=1.38ms  p(95)=4.5ms
http_req_sending...............: avg=27.09µs  min=0s       med=0s      max=1.43ms p(90)=0s      p(95)=321.59µs
http_req_tls_handshaking.......: avg=25.5ms   min=0s       med=17.47ms max=1.38s  p(90)=27.66ms p(95)=48ms
http_req_waiting...............: avg=3.9s     min=233.32ms med=2.22s   max=30.01s p(90)=9.03s   p(95)=12.58s
http_reqs......................: 13138  13.09123/s
iteration_duration.............: avg=4.95s    min=365.02ms med=3.26s   max=31.05s p(90)=10.1s   p(95)=13.65s
iterations.....................: 13137  13.090234/s
vus............................: 6      min=6       max=65
vus_max........................: 65     min=65      max=6

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1lpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0990085895d1c05efdbb13d5bc82262a4b1fc5cb/image.png)

**Comment by andrewsignori-aot** [comment]
checks.........................: 99.98% ✓ 13135     ✗ 2
data_received..................: 93 MB  92 kB/s
data_sent......................: 47 MB  47 kB/s
http_req_blocked...............: avg=36.63ms  min=0s       med=32.44ms max=1.39s  p(90)=45.86ms p(95)=74.12ms
http_req_connecting............: avg=11.05ms  min=0s       med=14.35ms max=1.04s  p(90)=16.87ms p(95)=19.72ms
http_req_duration..............: avg=3.91s    min=237.45ms med=2.22s   max=30.01s p(90)=9.03s   p(95)=12.58s
  { expected_response:true }...: avg=3.9s     min=237.45ms med=2.22s   max=29.85s p(90)=9.03s   p(95)=12.56s
http_req_failed................: 0.01%  ✓ 2         ✗ 13136
http_req_receiving.............: avg=752.12µs min=0s       med=0s      max=44.3ms p(90)=1.38ms  p(95)=4.5ms
http_req_sending...............: avg=27.09µs  min=0s       med=0s      max=1.43ms p(90)=0s      p(95)=321.59µs
http_req_tls_handshaking.......: avg=25.5ms   min=0s       med=17.47ms max=1.38s  p(90)=27.66ms p(95)=48ms
http_req_waiting...............: avg=3.9s     min=233.32ms med=2.22s   max=30.01s p(90)=9.03s   p(95)=12.58s
http_reqs......................: 13138  13.09123/s
iteration_duration.............: avg=4.95s    min=365.02ms med=3.26s   max=31.05s p(90)=10.1s   p(95)=13.65s
iterations.....................: 13137  13.090234/s
vus............................: 6      min=6       max=65
vus_max........................: 65     min=65      max=6

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1lpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0990085895d1c05efdbb13d5bc82262a4b1fc5cb/image.png)

**Comment by andrewsignori-aot** [comment]
Wiki documentation created: https://github.com/bcgov/SIMS/wiki/Load-testing
