### ISSUE TITLE
Camunda Load Testing

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#2288]
**Describe the task**
Load test Camunda submission capacity trying to establish the workers capacity to handle the requests.  Test must include the database connection and the workers need to be there to ....

**Additional Context**
- This may grow as the strategy is developed.  Timebox for a sprint for now.  May be additional work to follow.

**Acceptance Criteria**
- [x] Determine and document load testing strategy in wiki.
- [x] Document testing instructions in wiki so that the process can be repeated.

**Comment by dheepak-aot** [comment]
Observation.

Webhooks can be a way to start a process instance by a rest API call

https://camunda.com/blog/2023/05/start-camunda-8-process-rest-webhooks/

**Comment by dheepak-aot** [comment]
Load tests on camunda happen through load-test-gateway a non prod environment application which hosts APIs which are used by K6 framework to load test. APIs in load-test-gateway are authenticated by access token issued by keycloak.

The access token is issued for key cloak client `load-test-gateway`. The keycloak client is already created in dev environment and it is intended to be created in the non prod environments where load test can happen
Here is the wiki to create the keycloak client `load-test-gateway`
https://github.com/bcgov/SIMS/wiki/Keycloak-Config#load-test-gateway-strictly-for-dev-environment-only

**Comment by dheepak-aot** [comment]
Removed ACs which are moved to new ticket from here 

- [ ] Check if there is the best way to configure workers maxJobsToActivate.
- [ ] Produce reporting of output vs pod#s/CPU/memory configuration.
- [ ]  Identify the best configuration and modify the YAML file to standardize future deployment.

**Comment by dheepak-aot** [comment]
Github actions will be done in #2437
