### ISSUE TITLE
Implement logic for Application Event Code in IER12

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#2289]
**Questions on application status codes and IER**
(Answers below are based on discussion with @JasonCTang and @HRAGANBC )

- COER vs DISR status: When a disbursement has a coe which is waiting for approval from institution and assume that the coe has not been approved until disbursement_date and the student has restriction. With this situation should we return COER or DISR ? - _**Answer: COER**_ as per @HRAGANBC 
- Consider a disbursement which has been sent to finastra and this disburesment had some funds withheld due to restriction at the time of e-cert generation(DISW). After the disbursement is sent to finastra we got disbursement feedback errors(DISE). should we return DISW or DISE ? - _**Answer: DISE**_

- Should DISW and DISE override DISS ? - _**Answer:  Yes**_

**Describe the task**
Implementation of Application event code and Application event date for IER 12. For reference Please use the spreadsheet from General > Files >Analysis > Institution File Specs > IER12_Analysis_Output_and_Mapping_Part_1_V2.xlsx

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBanphIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--647bfa0e2600e2bfe2d7e4d88fcf60845d187de6/image.png)

**Additional context**

### List of validations which needs to be in place to derive application status code
**Validation**: Check if an application has more than one submission.
Logic: `select count(id) from sims.applications a where a.application_number = '$APPLICATION_NUMBER'`

**Validation**: Check if the disbursement has any feedback error
Logic: Check the `sims.disbursement_feedback_errors` feedback table for one or more errors which belongs to given list of FT Error codes.
FT Error codes: [Ecert Error Codes and Descriptions External.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0VNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8b8de3b4c6ae5b179b51016fa535eed07015987f/Ecert%20Error%20Codes%20and%20Descriptions%20External.xlsx) (this is only FT codes)

**Validation**: Check if disbursement is not sent due to restriction
Logic: Check if the student has any active restriction of action type 'Stop full time disbursment' and disbursement date is after cutoff date (current date + 5)

**Validation**: Check if any disbursement award was withheld due to restriction
Logic: Check if the restriction_amount_subracted > 0

### Logic to derive the application event code from application and assessment data.
_**Note:**_ BPMN diagram is used only explain the logic, it is not considered as solution for implementation.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNm9NQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd3ce11f4906e59c1d8d6ddb609525bf8bc6dac8/image.png)

Source BPMN file(for making updates) : [application-event-code.bpmn.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1FNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d44b347526b4d96f6ce92d2ceac304e2618bff2a/application-event-code.bpmn.txt)

### Logic to derive application event date (As per discussion with @JasonCTang )
_**Note:**_ BPMN diagram is used only explain the logic, it is not considered as solution for implementation.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbUhhIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--799d5d0cd713fab48c6e1b3a4631286add65faa2/image.png)

Source BPMN: [application-event-date.bpmn.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaVBiIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1d98d2d0dd963cf5cbacb963f28657e2575680c1/application-event-date.bpmn.txt)

**Acceptance Criteria**
- [x] Create the logic required to perform all the validations mentioned
- [x] Implement the mapping for `Application event code` [Application event codes, RECA, COEM, DISP  is not considered for the ticket/not in the scope, that's why it is marked as grey.]
- [x] Implement the mapping for `Application event date`
- [x] Adjust the IER query to make sure that an IER record is sent  if there is any update to feedback table or any pending disbursement beyond cutoff date.
- [x] Create methods for the fields which could be unit tested.
- [x] Create unit tests.
- [ ] Nice to have: More unit tests to other conversions built before.

**Comment by ann-aot** [comment]
Validation: Check if the disbursement has any feedback error
Logic: Check the `sims.disbursement_feedback_errors` feedback table for one or more errors which belongs to given list of FT Error codes.
- What are the codes corresponding to FT Error codes

**Comment by ann-aot** [comment]
Qn 2:
Validation: Check if any disbursement award was withheld due to restriction
Logic: Check if the restriction_amount_subracted > 0.
 -  double checking, so, if there is a lifetime restriction and 2 applications, 
 -  1. from first application certain amount was subtracted as part of the restriction, but the e-cert was sent, is this eligible for code `DISW`
 -  2.  1. from second application the whole amount was subtracted as part of the restriction, is this eligible for code `DISW`

**Comment by ann-aot** [comment]
Application event codes, RECA, COEM, DISP  is not considered for the ticket/not in the scope, that's why it is marked as grey.

**Comment by ann-aot** [comment]
For, `applicationEventDate`, When the `ApplicationEventCode` .is `DISR`:
Logic : `disbursementSchedule.disbursementDate - 5 cut off date for disbusement)`

**Comment by ann-aot** [comment]
For, `applicationEventDate`, When the `ApplicationEventCode` .is `DISE`:
logic:
if there are multiple feedback error, take any random one's `updatedAt`

**Comment by ann-aot** [comment]
Removed below AC -
 - [ ] Please add the index position of these fields to the spreadsheet/IER official document
As it was addressed in #2277
