### ISSUE TITLE
UI/ UX- Cont. V2 Validate Education Programs List Page (Location Level)

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#230]
- [ ] Fine Tune and QA the content and formatting a team
- [ ] Any updates as required per conversations with SMEs

**Comment by hellolynn-dsib** [comment]
**Meeting with Niamh & Haley (April 22, 2021)**

**Attendees:** Lynn, Roop, Courtney, Alys, Michelle, Niamh, Haley

V1 concept to v1 changes from biz:

- Remove start/end date
- Add CIP
- Add Credential (e.g. degree)
- Update the navigation

**Comment by hellolynn-dsib** [comment]
Reviewed with UX team

**Comment by hellolynn-dsib** [comment]
UX connect outcome:

- For v1: to include sort (pulling from vuetify tables)
- For v2: to include search functionality (pulling from vuetify tables)
- Blurred out summary overview (nice to have for MVP)
