### ISSUE TITLE
Input new 2023/2024 Program Year Amounts - PT

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2301]
**Current Behaviour**
Current DMN tables don't reflect 2023-24 limits

 **Expected Behaviour**
Update Required to Part Time Assessment File (parttime-assessment-decisions.dmn)

**Acceptance Criteria**
All values in the file are updated on the "2023-2024" record line as described below:
- [ ] dmnPartTimeAwardAllowableLimits.limitAwardCSGPTAmount = 2800
- [ ] dmnPartTimeAwardAllowableLimits.limitAwardCSPTAmount = 2520
- [ ] dmnPartTimeAwardAllowableLimits.limitAwardCSGDAmount = 2688
- [ ] dmnPartTimeAwardAllowableLimits.limitAwardCSGD2OrLessChildAmount = 56
- [ ] dmnPartTimeAwardAllowableLimits.limitAwardCSGD3OrMoreChildAmount = 84
- [ ] dmnPartTimeAwardFamilySizeVariables as below (largest family size should be "> 7" not just "7" as shown):
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTVhQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--64a0567427ee896992cf61c6cfb3295b1ffe9d2f/image.png" alt="image.png" />
- [ ] Fix E2E if necessary

**Comment by CarlyCotton** [comment]
@HRAGANBC This is ready to go for updates.

**Comment by CarlyCotton** [comment]
Just added quick edit to confirm in our discussion during grooming that for the largest family size it should be "> 7" not just "7" as shown in the picture.
