### ISSUE TITLE
Pending PIR is listing overwritten application PIRs

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#2302]
Bug:
When a student have an application waiting for PIR and the PIR is pending with an institution and before institution has a chance to complete it, if he/she edit it and submit the application with another PIR requirement. The pending PIR data table in Institution is listing all the PIRs irrespective of the "overwritten` status. I believe we are missing the application status check. 

- [ ] Add application status check in the query
- [ ] Check application status during PIR update.
- [ ] Create an E2E test for this specific scenario.

**Comment by ann-aot** [comment]
Not able to reproduce the bug, and overwritten status is already checked the PIR logic, [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0lWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4a60a351fec6f648862ac9dcc92034a6c90c4c3d/image.png)
