### ISSUE TITLE
Total eligible amount is not showing for NOA (part-time and full-time)

### ISSUE THREAD

**Issue by ann-aot** [bcgov/SIMS#2303]
**Acceptance Criteria**
- [x] For the NOA , `Eligible for the amount` is not showing correctly,
- [x] Check all NOA Values to identify the source of truth and ensure they are coming from the database instead of camunda variables
- [x] Everything that they are eligible for prior to ecert generation
- [x] update test cases

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa3loIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5ce70e6b73889561ae3c0efd610e14e0e33f5318/image.png)

**Comment by dheepak-aot** [comment]
From #2222 we found that in assessment_data we map childcareCost from `calculatedDataChildCareCost`. Looks like we must use `calculatedDataTotalChildCareCost ` instead.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaUthIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--018763695093aa20b323731f6cb76545801bbc86/image.png)

**Comment by michesmith** [comment]
Question to be answered in #2331

**Comment by guru-aot** [comment]
Requested Hugh to create a placeholder ticket #2381 for the reviewing the assessment and awards for both the Full time and Part time applications

**Comment by guru-aot** [comment]
https://teams.microsoft.com/l/message/19:meeting_MWY2MWExZjYtODMyZi00YmIxLWI1ZWMtOTFjOWY0M2M5ZTMz@thread.v2/1696957400063?context=%7B%22contextType%22%3A%22chat%22%7D
