### ISSUE TITLE
Parent Contributions: Fix the field mapping issue on parentvoluntarycontributions Costs for IER12

### ISSUE THREAD

**Issue by guru-aot** [bcgov/SIMS#2316]
studentDataVoluntaryContributions is a field to be mapped in IER 12 document. 

The load-assessment-consolidate is also mapping "parentvoluntarycontributionsCosts" twice, which does not seems right.  <zeebe:header key="studentDataVoluntaryContributions" value="$.data.parentvoluntarycontributionsCosts" />  
<zeebe:header key="studentDataParentVoluntaryContributionsCosts" value="$.data.parentvoluntarycontributionsCosts" />. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXNNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5bb41797242638c710527e25759c50ad50f50c7c/parent%20volutary.PNG)
 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1FNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--84012405f166a831178c1be2637e74649db849bb/image.png)

**Test Scenario**
Test the IER using student provide data and partner provide data

**Acceptance Criteria**
- [x] Ensure the zeebe:header key is using the correct variable. (remove or update)
- [x] Review calculatedDataParentalContribution on fulltime assessment workflow (part-time not required)

**Comment by HRAGANBC** [comment]
There are THREE possible fields which capture Parental voluntary contributions:  
1. Student application > financial information section > "Will you receive voluntary contributions from your parents..."
2. Student application > parent information section (if self-reporting parental info) > "How much will your parents be giving the student to help meet their specific educational costs...."
3. Parent support users form > "How much will you/your spouse/common-law partner be giving the student to help meet their educational costs..."

I do NOT know what variable name is created from each field. 

From policy perspective, these fields should be consolidated into one number. I don't think this is currently being done in the workflows. 

Current Full-Time Assessment workflows:
Parent1Contributions
Parent2Contributions
studentDataStudentParentNetContribution

**Comment by guru-aot** [comment]
As the parental voluntary contribution needs more of analysis #2434  is created by Hugh for further analysis and future tickets.
