### ISSUE TITLE
Update Hyperlink for BC Private Information Sharing Agreement

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2317]
**Required for October 11 Technical Release**
@HRAGANBC when is the estimate to complete this agreement?

Currently, hyperlink on the BC Private 'Request Designation' page links here: https://studentaidbc.ca/sites/all/files/school-officials/Schedule_D_Designation_Agreement.pdf 

This is an outdates agreement, and is being refreshed currently. This will need a new hyperlink once finalized.  

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcUcxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--629d4469ded7584c3ed67fd2928f33313cf009cf/image.png)

**Comment by michesmith** [comment]
@HRAGANBC I've added this to the scope of #2300 and have closed this ticket
