### ISSUE TITLE
Release 1.2 Technical Release Activities (Oct 10)

### ISSUE THREAD

**Issue by michesmith** [bcgov/SIMS#2329]
-Create Release Package
-Update Release Report on zenhub (including migration rollback)
-Deploy to test
-Deploy to Staging (Determine if application logging)
-Conduct Smoke Test
-Deploy to Prod

**Comment by ann-aot** [comment]
Created 
- Release Package
-Update Release Report on zenhub (including migration rollback)
-Deploy to test and did smoke test
