### ISSUE TITLE
Update institution portal for publics that have student screens - Request change in offering for single student.

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#2334]
**As a** *(User Type/Persona)* **I want** *(Feature/enhancement)* **So That** *(Value, why is this wanted, what is the user trying to accomplish)*

**Additional Context**
- enter text here
- enter text here

**Acceptance Criteria**
- [ ] Given (Context), When (action carried out), Then (expected outcome)
- [ ] Given (Context), When (action carried out), Then (expected outcome)

**Comment by michesmith** [comment]
@JasonCTang is this still required?

**Comment by michesmith** [comment]
@HRAGANBC is this a duplicate?

**Comment by HRAGANBC** [comment]
@michesmith closing ticket - this is fully resolved within other tickets related to Institutions reporting Offering Changes to Single Students
