### ISSUE TITLE
Removal of Part-Time Application Questions For Partner Supporting Users

### ISSUE THREAD

**Issue by michesmith** [bcgov/SIMS#2348]
Related to #2172

For PT applications, remove the following questions relating to Spouses/Partner information (these questions appear both in the 'supporting users' tab AND in the student's own application if they are self-reporting on behalf of their spouse - they should be **removed in both places**

**Acceptance Criteria**
Remove the following questions **from supporting users form** **and student form 'self-report' feature** 
- [x]   "Will you be employed full-time or part-time during your partner's study period"
- [x]   "Will you be at home caring for eligible dependent children on a full-time basis during your partner's entire study period?"
- [x]  "Will you be living with your partner during the study period"
- [x]  "Will you be a full-time post-secondary student for some or all of your partner's study period (remove the follow-up questions capturing weeks of study as well)" 
- [x]  "Will you be paying a Canada Student Loan.."
- [x]  "Will you be paying for Child support and/or spousal support during your Partner's study period"
- [x]  "Will you be taking care of eligible dependents during your Partner's study period"
- [x]  Add to the ticket comments the removed keys and mention the workflow impact points.

**Comment by lewischen-aot** [comment]
Removing the following questions from PT applications will **NOT** have workflow impact points.

- Will you/your partner be employed full-time or part-time during your Partner's study period
- Will you/your partner be at home caring for eligible dependant children on a full-time basis during your Partner's entire study period?
- Will you/your partner be living with your Partner during your Partner's study period?
- Will you/your partner be taking care of eligible dependants during your Partner's Study Period?

The following questions have related workflow impact points in Camunda.

- Will you/your partner be a full-time post-secondary student for some or all of your Partner's study period?

  - Supporting-user input: How many weeks will you be a full-time post-secondary student during your Partner's study period?
    - FormIO API: `partnerStudentStudyWeeks`
  - Self-reporting input: If your partner will be a full-time student, how many weeks of your study period will they also be in studies?
    - FormIO API: `ifYourPartnerWillBeAFullTimeStudentHowManyWeeksOfYourStudyPeriodWillTheyAlsoBeInStudies` (doesn't have a key in Camunda)

- Will you/your partner be paying a Canada Student Loan and/or a provincial student loan regular scheduled payments during your Partner's study period?

  - Supporting-user input: Enter amount that you will pay during your Partner's study period.
    - FormIO API: `partnerTotalStudentLoan`
  - Self-reporting input: Enter amount that your partner will pay during your study period.
    - FormIO API: `partnerstudentloanCosts`

- Will you/your partner be paying for child support and/or spousal support during your Partner's study period?

  - Supporting-user input: Enter amount that you will pay during your Partner's study period.
    - FormIO API: `partnerTotalSupport`
  - Self-reporting input: Enter amount that your partner will pay during your study period.
    - FormIO API: `partnerchildsupportCosts`

|          FomIO           |          Camunda          |            Calculated Data             |              Workflow Data              |
| :----------------------: | :-----------------------: | :------------------------------------: | :-------------------------------------: |
| partnerStudentStudyWeeks | partner1StudentStudyWeeks | calculatedDataPartnerStudentStudyWeeks | calculatedData.partnerStudentStudyWeeks |
| partnerTotalStudentLoan  | partner1TotalStudentLoan  |                  None                  |                  None                   |
| partnerstudentloanCosts  |          no key           |                  None                  |                  None                   |
|   partnerTotalSupport    |          no key           |                  None                  |                  None                   |
| partnerchildsupportCosts |          no key           |                  None                  |                  None                   |

The following questions have related workflow impact points in ier12.

- Will you/your partner be a full-time post-secondary student for some or all of your Partner's study period?

  - Supporting-user input: How many weeks will you be a full-time post-secondary student during your Partner's study period?
    - FormIO API: `partnerStudentStudyWeeks`
    - A new ier12 record will have `partnerStudentStudyWeeks: workflowData.calculatedData.partnerStudentStudyWeeks or 0`

Conclusion:

- **No** immediate impact on the current workflows for removing the questions for PT applications
- Potential impact later on:
  - In case the question "Will you/your partner be a full-time post-secondary student" becomes available. When the applicant enters a value for
    the self-reporting input -- "If your partner will be a full-time student..." -- the value will not be captured in workflows and
    a new ier12 record will have `partnerStudentStudyWeeks === 0` as the key is missing.

**Comment by andrewsignori-aot** [comment]
@lewischen-aot the possible missing key `partnerStudentStudyWeeks` will always be present for Full-time applications, right?
If it helps, IER12 is only generated for full-time applications.

**Comment by lewischen-aot** [comment]
That's correct @andrewsignori-aot. For FT applications, the key `partnerStudentStudyWeeks` will be present in the supporting user form, but it is missing in the self-report form. We may want to address this later, but it has no impact for PT applications for now.
