### ISSUE TITLE
Generate e-Cert Feedback File Error Ministry - Import Data

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2366]
#2536 is a related ticket handling how these errors are communicated to the student.

**Description of Task**:
Trigger specific actions anytime we receive eCert feedback file records for specific student records. 

**Acceptance Criteria**
- [x] Create a process that reads the daily eCert feedback file and detects any records with associated errors.
- [x] Save all error codes and descriptions (from 'original' worksheets, not the filtered worksheets) in database table
- [x] No MVP functionality to track action/status on these errors. This will be handled by SABC in JIRA. 

**Technical**

- [x] Create the new table `sims.ecert_feedback_errors`
  - Minimum columns
    - error_code
    - error_description
    - offering_intensity (reuse the same type from offerings)
    - block_funding: boolean column to indicate if the error will block the funding. This is the flag to be used as a condition to send Ministry notifications and also display the waning in the application tracker. The flag must be `true` for the error codes indicated in the spreadsheet "PT Errors filtered".
- [x] Populate the new table with all records from the attached spreadsheet for FT/PT.
- [x] Remove the `error_code` column from `sims.disbursement_feedback_errors` and create a relationship with the new table `sims.ecert_feedback_errors`.
- [x] While importing the feedback errors, if the code is not present in the table `sims.ecert_feedback_errors`, abort the process.
- [x] Add a new column `feedback_file_name` to `sims.disbursement_feedback_errors` to capture the file that was imported and inserted the record.
- [x] Add E2E tests
  - Test the file imported with the new table columns and relationships.
- [x] Break into multiple PRs. If not possible to break communicate to DEV and get the approval.
  - DB Changes.
  - Import process.

**Context:**
The federal service provider (NSLSC/Finastra) sends a daily eCert Feedback file which sometimes contains error codes for particular applications disbursement requests. These error codes indicate there was at least one error in the list of validations which exist on the NSLSC side. For e.g., the address listed on a student's application is not recognized, or a student is missing a first name. 

Some of the errors do not block the disbursement from being issued, but others do. For any errors which block disbursement, the student's application and disbursements are now completely in limbo and will not get resolved unless someone within SABC takes an action to resolve. However, without knowledge of which students have errors, there is no way for SABC staff to know which applications need attention. 

**Additional Context - List of Error Codes Which can be Received**
This is a complete list of error codes which can be received for FT and PT eCert feedback files, as well as a filtered list which captures all the errors which result in blockage of funding. Only the **filtered list** should get used in this ticket.
[eCert Error Codes (Consolidated and Filtered).xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2VWQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4c779c3ebb3e63c238a0d1645759d7e9aea2c3f6/eCert%20Error%20Codes%20%28Consolidated%20and%20Filtered%29.xlsx)

**Comment by andrewsignori-aot** [comment]
@HRAGANBC in the attached spreadsheet we have the below:
- FT Errors (Filtered): is this the list of Full-time errors that would block a disbursement or is it the complete list?
- PT Errors (Original): complete list of all PT error codes.
- PT Errors (Filtered): errors that should be considered in this ticket to send Ministry notification and show the message to the student in the application tracker.

As part of this effort we are planing to create a table that would contain all the FT/PT errors. Can we rely in the ones in the spreadsheet?

**Comment by HRAGANBC** [comment]
@andrewsignori-aot 

Correct, you can use the PT Errors (Original) and FT Errors (Original) to represent the COMPLETE list of possible errors codes, and use that to create your table. This corresponds to the second AC. (I think you were not seeing all the worksheets in the file  -there is an additional one called "FT Errors (Original)" which captures all FT errors)

When extracting the report through the interface, display ALL error codes (i.e. use the 'complete' list) 

When dictating what triggers an email, and what gets displayed through the student tracker, use only the filtered lists

**Comment by andrewsignori-aot** [comment]
Thanks @HRAGANBC, everything that you said makes sense.

Just to double check, the table that we will be created will contain specific entries for Full-time and Part-time.
For instance, while comparing both sets of error codes we can see that some are the same but with different descriptions and both have different codes also.
Devs raised the question and I am just trying to settle it.

![image](https://github.com/bcgov/SIMS/assets/61259237/d7cb2a63-7bcc-4939-a090-67632bbd0af5)

**Comment by andrewsignori-aot** [comment]
@HRAGANBC are new codes potentially added to this table without notice or they will be only added if Federal gov gives a notice ahead of time that would allow the system to accept the new number?

**Comment by HRAGANBC** [comment]
@andrewsignori-aot 

Yes, please make seperate tables for PT and FT errors and descriptions because although some of them overlap, some are distinct. 

They would always give us notice anytime errors are added.
