### ISSUE TITLE
Generate Report of MSFAA File Errors

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2368]
#2377 is a supplementary way of handling this issue.

**Description of Task:** 
Generate a daily report documenting all SABC students listed on the MSFAA Received file containing a processing error. 

**Context:**
The federal service provider (NSLSC/Finastra) sends a daily MSFAA Feedback file which sometimes contains error codes for particular applications. These error codes indicate there was at least one error in the list of validations which exist on the NSLSC side. For e.g., the address listed on a student's application is not recognized, or a student is missing a first name. 

Some of the errors do not block the disbursement from being issued, but others do. For any errors which block disbursement, the student's application and disbursements are now completely in limbo and will not get resolved unless someone within SABC takes an action to resolve. However, without knowledge of which students have errors, there is no way for SABC staff to know which applications need attention. 

**What's Included on Each Report**
- A new entry for each student which contained at least one error
- First Name, Last Name, DOB, SIN associated with each student
- A list of all error codes associated with each student, and the written description of what each error code means **Need the list of MSFAA error codes which might be encountered - Hugh to ask NSLSC for these**
- Aggregate details in the report header: 1) Date, 2) Number of students with errors

**Acceptance Criteria**
- [ ] Create a process which reads the daily MSFAA receipt file and detects any students with associated errors.
- [ ] Create a report (.txt?) daily which summarizes all detected errors from that day's MSFAA receipt file. The report should contain info consistent with the above section
- [ ] The report should contain FT and PT applications in one report
- [ ] If there are no error codes detected on that day's MSFAA received file, do not configure a new report
- [ ] When the report is configured, send it to studentaidbc@gov.bc.ca with the subject line "MSFAA Receipt Error Codes Detected"

**Comment by CarlyCotton** [comment]
Closing - MSFAA has a single response file that is R or C (received or cancelled). No errors.
