### ISSUE TITLE
Create Automatic E-mail Notifications to SABC Staff 

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2369]
**User Story**
As a **_Ministry user_**, I want to receive automatic notifications anytime specific trigger events occur within SIMS so that a JIRA ticket gets created for each such event. This will help me manage completion status and assign work tasks to staff members using JIRA functionality. 

**Description of Task:**
Automatically configure simple e-mails to specific SABC e-mail addresses any time particular trigger events occur within SIMS. 

**Context:**
In the absence of custom workload management tools within the various queues in SIMS, Service Delivery staff will have difficulty tracking which staff are working on which pending request, the status of each request, and other ticket management tools. 

**Business Requirements Details**
<img width="1582" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDNKQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--07fd8cc6c09f4e55507048fb02da1ebc0db33a1c/image.png" alt="image.png" />

Email Body should include the following details, if the value doesn't exist can be blank:
Student Profile:
- Student: [StudentFirst] [StudentLast]
- Date of Birth: [StudentDOB]
- Email: [StudentEmail]
- Application: [ApplicationNumber]
- Date/Time: [Date/Time of Event]

Institution Profile:
- Institution: [InstitutionOperatingName]
- Location: [InstitutionLocationName]
- Program: [ProgramName]
- Offering: [OfferingName]
- Email: [InstitutionPrimaryEmail]
- Date/Time: [Date/Time of Event]

**Acceptance Criteria**
- [ ] Configure e-mails to be automatically configured anytime the below trigger events occur within SIMS:
- - [x] Student File Uploads - TemplateID: `3b37994f-464f-4eb0-ad30-84739fa82377`
- - [x] Student Submits Change Request after COE - TemplateID: `241a360a-07d6-486f-9aa4-fae6903e1cff`
- - [x] Student Submits Application with Exception Request - TemplateID: `997c6625-5571-4c92-94d1-7d7c1b86fd8c`
- - [x] Student Requests BasicBCeID account - TemplateID: `e9cf5143-c553-4937-9a5c-fab4230782aa`
- - [x] Student application is edited for 5th time - TemplateID: `952acba8-8806-4b9e-aee3-a14ea3823bbf`
- - [x] Change to a Student's Program or Offering - TemplateID: `d76816c1-9b3c-4fe7-a22d-beb773cfdac5`
    - _Note:_ This should be a student focused template.
- - [x] Institution adds pending program - TemplateID: `98b38e6b-a015-48e8-8058-1e21402bb1b6`
- - [x] Institution adds pending offering - TemplateID: `b4e6252b-e196-4c14-9a29-1b2a71e9131a`
- - [x] Institution requests designation - TemplateID: `a77868a8-c51f-4f79-b6a2-8f855960bb3d`
    - _Note:_ Institution requests designation has a different template:
    - Institution: [InstitutionOperatingName]
    - Email: [InstitutionPrimaryEmail]
    - Date/Time: [Date/Time of Event]
- [x] Emails have generic subject lines that are based on the format **[Short Trigger Name] : [Identifying Name]** - **Short Trigger Name:** see Subject Line in image, it's a shortened version of the trigger events & **Identifying Name:** Either the Institution Name or the Last name of the student
- [x] Each trigger type has a specific email address to be sent to only one of the following per the table trigger above  (studentaidbc@gov.bc.ca, SABC.AppealsUnit@gov.bc.ca, designat@gov.bc.ca), this should **only be in PROD and not in TEST**
- [x] If the trigger event would create a blank field in the template data, please remove the field from the corresponding template.
- [x] For test purposes, configure email to SABCtechhelp@gov.bc.ca
- [x] Create E2E Task Ticket with basic analysis to complete

**Technical (created during the sprint)** 
- [ ] Create a new nullable column `email_contacts` in `sims.notification_messages` similar to `sims.institution_locations.integration_contacts`.
- [ ] While creating the DB migration to insert the new column do not populate any email value. They should be updated to the environments once the feature is deployed to the same.
- [ ] Create an SQL script to be added to the release instructions to have the emails updated on PROD.
- [ ] Use the new column for all emails related to Ministry templates.
- [ ] For templates that require the email column to be populated, register an error log that reads: "Email template <NameOfTheTemplate> requires a configured email to be sent."
- [ ] Remove the existing env variable that contains the Ministry email.

**Comment by michesmith** [comment]
**@Hugh, @JasonCTang, @cditcher: Let's review reference fields to simplify and also split scope into notifications we are ready for and POTENTIALLY split by PT and FT**

**Comment by HRAGANBC** [comment]
@CarlyCotton can you please refine this ticket and simplify the standardized fields which get referenced in each email? I.e. we jsut need something like First Name, Last Name, DOB in the email contents, and the email subject line should be aligned with whatever trigger event prompted it. 

Given this simplification, you might be able to do away with the Excel altogether so Devs dont have to reference that. 

Once done, can put right into PM review. This has recently be deemed critical for PT release. Thanks

**Comment by ninosamson** [comment]
Confirm with @HRAGANBC if distribution to emails other than studentaidbc@gov.bc.ca is required. If so, additional work is required to handle sending to different emails.

**Comment by ninosamson** [comment]
Create templates in GC Notify for each trigger and identify which to use in AC.

**Comment by michesmith** [comment]
@CarlyCotton @HRAGANBC per convo need to create new Templates in GC Notify and add AC's for which Template to use.

**Comment by CarlyCotton** [comment]
@ninosamson @michesmith Can it be pushed to backlog grooming while we wait on access and template creation in GCNotify?

**Comment by CarlyCotton** [comment]
eCert error email is requested on #2366 - can be removed from this request

**Comment by HRAGANBC** [comment]
@andrewsignori-aot Sorry but I don't understand your statement. Are you saying that the intended email address now has to be saved in database as the destination, and any changes to that email address in the future must wait for a new release to PROD to be reflected? Whereas previously the destination email address was more easily configurable?

**Comment by andrewsignori-aot** [comment]
> @andrewsignori-aot Sorry but I don't understand your statement. Are you saying that the intended email address now has to be saved in database as the destination, and any changes to that email address in the future must wait for a new release to PROD to be reflected? Whereas previously the destination email address was more easily configurable?

Right now there is no easy way to change the email other than some level of technical PROD interaction.
The current requirement is asking to have individual emails associated with the individual templates and the logical way to do it would be to save them in the same place where we have the email template configuration.
The DB-saved emails can technically be changed more easily than the current way right now.
Our only concern was if we should keep both configurations in place or if we can assume that DB will have the emails configured and we can get rid of the previous single email configuration.

**Comment by andrewsignori-aot** [comment]
@HRAGANBC can you please confirm which change or changes would trigger the below AC:
"Change to a Student's Program or Offering - TemplateID: d76816c-9b3c-4fe7-a22d-beb773cfdac5"
Would it be the below ones?
<img width="292" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN283QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7366913dbc35ed869bbc394feb867c45831382c2/image.png" alt="image.png" />

**Comment by CarlyCotton** [comment]
@andrewsignori-aot 
It's for the requests that go into the "Applications" dashboard you have highlighted above. The trigger is when Ministry approval is required after an institution has requested a change to an existing application's program and/or offering AND the student has approved.
<img width="1460" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1U3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8ac0ecaa1e0247cea92afe02f3056da3bc058d40/image.png" alt="image.png" />

**Comment by andrewsignori-aot** [comment]
> sted a change to an existing application's program and/or offering AND the st

Thanks @CarlyCotton for the clarification. 
Do we have a notification planned for the "Bulk Offering Bulk Change"? It would be the other link highlighted in the many right above "Applications"

**Comment by andrewsignori-aot** [comment]
> @andrewsignori-aot I'm not aware of an in-progress ticket for ministry notification on an offering change.

Wich is fair @CarlyCotton. My point is that all these emails are supposed to be an alternative way to create a queue of work for the Ministry, and the "bulk offering change" would fall into the same category unless there is a special circumstance where the Ministry does not require it.

@HRAGANBC is it a possible gap?

**Comment by CarlyCotton** [comment]
@andrewsignori-aot I understand what you're saying, but that has not been identified at this time as a priority for email notification to ministry staff. As, you have indicated they should all be in that dashboard. 

There is a difference with a number of these, for example the program/offering change that has been approved by student (these are mixed with other requests within the same dashboard list) and adding a pending program is not on any dashboard.

Is this something holding up the ticket? Or are you just wanting to flag a possible gap?

**Comment by andrewsignori-aot** [comment]
> @andrewsignori-aot I understand what you're saying, but that has not been identified at this time as a priority for email notification to ministry staff. As, you have indicated they should all be in that dashboard.
> 
> There is a difference with a number of these, for example the program/offering change that has been approved by student (these are mixed with other requests within the same dashboard list) and adding a pending program is not on any dashboard.
> 
> Is this something holding up the ticket? Or are you just wanting to flag a possible gap?

@CarlyCotton, just raising the possible gap. If we are missing it, it may be something that we can have some room to address in the same ticket. We can also address in a separated ticket later, it wold just demand more effort.

**Comment by HRAGANBC** [comment]
@CarlyCotton @andrewsignori-aot Thanks for pointing out the gap, but agreed with Carly about the Bulk Offering change being intentionally left off the list because it is: A) much less frequently encountered, and B) schools are much more likely to already be in contact with our Business team prior about any such request. 

Worst case scenario we address in seperate ticket but I think unlikely.

**Comment by CarlyCotton** [comment]
Based on conversation with @sh16011993 and @andrewsignori-aot updated the ACs:
Added:

- If the trigger event would create a blank field in the template data, please remove the field from the corresponding template.

- Note: Institution requests designation has a different template:
> Institution: [InstitutionOperatingName]
> Email: [InstitutionPrimaryEmail]
> Date/Time: [Date/Time of Event]
- Clarification for Change to a Student's Program or Offering template, it is a student template.

**Comment by sh16011993** [comment]
Thanks @CarlyCotton

**Comment by sh16011993** [comment]
@CarlyCotton Quick question: Application is edited for the 5th time, we send a notification to ministry. Any further than 5 times, do we keep sending the ministry a notification?

**Comment by sh16011993** [comment]
Thanks @CarlyCotton

**Comment by andrewsignori-aot** [comment]
@CarlyCotton was a goal of this ticket that Mnistry receives a notification for pending offerings created from `bulk-insert`?

**Comment by CarlyCotton** [comment]
@andrewsignori-aot The goal is to have an email for every pending offering created, regardless of the creation method.

**Comment by andrewsignori-aot** [comment]
> @andrewsignori-aot The goal is to have an email for every pending offering created, regardless of the creation method.

@sh16011993 I believe that this is missing in the PR.

**Comment by andrewsignori-aot** [comment]
@CarlyCotton @HRAGANBC about the AC that reads "Student application is edited for 5th time", we are considering the below.
1. The application is created for the first time and submitted.
2. Student edited the application (first time).
3. Student edited the application (second time).
4. Student edited the application (third time).
5. Student edited the application (fourth time).
6. Student edited the application (fifth time), and here the notification will be generated.
Can you please confirm that this is the understanding?

**Comment by CarlyCotton** [comment]
@andrewsignori-aot Yes, that's the understanding from us regarding a "5th edit" to an application.
