### ISSUE TITLE
Revise Banner Messages when Editing Program&Offering

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2376]
**Description of Task:**
Revise the content wording slightly in one banner message which appear when an institution user attempts to edit a program

**Current Behaviour Screenshot**
Edit a Program
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTRGQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0b3ebbc81e4da061347ddf1d3d1b83bbe52702ea/image.png)

**Acceptance Criteria**
- [x] Adjust the 'Edit Program' banner message _title_ to read "Program Details No Longer Editable"

**Comment by guru-aot** [comment]
The actual acceptance criteria banner is in Pascal Case, as we are not following it in our UI design, changing them to 'Program details no longer editable'
