### ISSUE TITLE
Ecert Error Codes and Descriptions

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#2384]
As part of #2289, we identified a potential future requirement for a table to store ECERT error codes and descriptions should they need to display to any users.  This ticket is a placeholder for now as we do not have any requirements from the business for this yet. 

There are separate codes for full time and part time.
FT Error codes: https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0VNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8b8de3b4c6ae5b179b51016fa535eed07015987f/Ecert%20Error%20Codes%20and%20Descriptions%20External.xlsx
PT Error codes:

**Comment by HRAGANBC** [comment]
Replaced by #2366
