### ISSUE TITLE
Analysis: Validations and logic for scenario where a reassessment has occurred after the request for an offering change

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#2389]
We need to consider the scenario where a request for an offering change was submitted and the original offering is no longer associated with the current assessment. 

- Validations to ensure Ministry (and student if applicable) cannot approve the request for offering change.
- Consider idea of making the request invalid so that approval nor denial is even an option anymore.  The request just becomes informational.

**Comment by HRAGANBC** [comment]
@Joshua-Lakusta 

I am closing this ticket, as I'm fairly confident this is sufficiently handled through #2571 and #2847, but Josh can you please ensure there are TestQuality scenarios capturing this scenario, and close this ticket if so?

I.e. If student is approved for offering change which changes study dates, and then is withdrawn from studies, does the withdrawal recognize the Offering change?
