### ISSUE TITLE
Error Message Program Information Field of Study Code/ CIP code Issues 

### ISSUE THREAD

**Issue by michesmith** [bcgov/SIMS#2393]
- [ ] Explore the bug
- [ ] can we reproduce the issue? 

Hugh and team could not reproduce the error message originally displayed. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzhnQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bfc18424d88afca3070c9ea3756fd1ad45e49c75/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEFnQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--251598d246a79bf39b146f7b9c7b2f10d3a0d4f1/image.png)

**Comment by HRAGANBC** [comment]
Closing as this ticket is replaced by #2215 - the bug was eventually replicated but logged in #2215
