### ISSUE TITLE
Confirm what the Institution needs to know for PD/PPD in the  IER12 File 

### ISSUE THREAD

**Issue by michesmith** [bcgov/SIMS#2399]
Related to ticket #1904

Confirm the following:
NONE = No PD/PPD status has been requested
PDRQ = PD or PPD status has been requested and is awaiting approval
PDAP = PD status approved
PPDA = PPD status approved
PDRJ = PD or PPD request was not approved

**Comment by HRAGANBC** [comment]
Closing-  this is replaced by #2522
