### ISSUE TITLE
(Discussion+Estimate) Revise Calculations Dictating # of Disbursements

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2401]
**Description of Task:**
Conduct sufficient grooming of below acceptance criteria to provide workload estimate to support SABC decision-making. If approved, ACs will be created into a ticket to implement prior to MVP release. 

**Context:**
- Many Study Period Offerings configured by the school will be calculated as 18 weeks in the SIMS system, and therefore be spread across two disbursements.  

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDdiQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e6cc12ff81bcc1dc5a3d6863a0308f22c18de6c2/DisbursementSchedule.JPG)

**Acceptance Criteria**
Revise FT and PT disbursement scheduling calculations such that:
- [x] If offering length is **19 weeks or greater**,  preserve status quo in dividing most funding types across both disbursements (w/ exception of CSL and BCSL which are all-or-nothing) 

**19 weeks or greater disbursement Example Breakdown**
Disbursement 1 
Canada loan 100%
CSG 50%
BC Loan 0%
BC Grant 50%
 
Disbursement 2 
Canada loan 0%
CSG 50%
BC Loan 100%
BC Grant 50%

- [x] If study weeks are **=18 weeks** , change disbursement configuration such that all award types are consolidated onto the first disbursement, EXCEPT Canada Student Grant awards which are distributed equally across two disbursements.
**= to 18 weeks offering disbursement Example break down**
Disbursement 1
CSL 100%
CSG 50%
BC Loan 100%
BC Grant 100%

Disbursement 2
CSL 0%
CSG 50%
BC Loan 0%
BC Grant 0%

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFVWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3713bb465b6ae0919f7dd67686242fc37ec6f94d/image.png)

Additional Context 
Disbursement breakdown for 17 weeks or less
remains status quo of 
1 Disbursement
100% of all funds

**Comment by ann-aot** [comment]
Screenshots of the demo,
**_1. less than 18 weeks_**
<img width="1253" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzluQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d67c2512883d4d5f3b445d23188d31c7972b5fd9/image.png" alt="image.png" />
**_2. Greater than 18 weeks_**
<img width="602" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0JvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cb50d458873b9f03b8e61d5ae8603e4e622c8721/image.png" alt="image.png" />
<img width="534" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0ZvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--18fca3daf767b140ceaa137f7b61382ec12dcde3/image.png" alt="image.png" />
**_3. 18 weeks_**
<img width="544" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1JvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--86c23b17c9fb1f44de040dc406305983c1d7c6b0/image.png" alt="image.png" />
<img width="546" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1ZvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7a61b4a6e0e3231071f5da4c47ce93e6e1d757a0/image.png" alt="image.png" />
