### ISSUE TITLE
Apply Program Year Maximums before sending eCert

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2405]
**Description of Task:**
Student eCerts must be trimmed for each funding type such that the sum of each funding type (across all applications within a Program Year) does not exceed Program Year maximums established by policy. 

**Context:**
Camunda calculates award amounts independantly for each application, based on the inputs provided on the application form and collected from supporting users. 

However, the amount awarded on any given application may have impacts on the award amounts the student will receive on their next application within the same program year. This is a policy rule. 

**E.g. of Policy Rule**: 
- BCAG has a limit of $10,000 per program year (example only, not real numbers) 
- Student submits app #1 for PY 23/24 and is assessed for $4,000 for BCAG. Student receives $4000
- Student submits app #2 for PY 23/24 and is assessed for $4,000 for BCAG. Student receives $4000
- Student submits app #3 for PY 23/24 and is assessed for $4,000 for BCAG. However, they should not receive all $4000 - they should instead be subjected to the annual PY maximums and receive only $2000. 

@Signori proposed the best way to approach these calculations is at the time of eCert generation, along with all the other last-minute adjustments which are made. 

**E.g. of Proposed Approach:**
- Student submits app #3 for PY 23/24 and is assessed for $4,000 for BCAG. (student has already received $8000 BCAG that PY, and the annual max is $10,000. 
- Student NOA for App #3 displays a BCAG eligible award = $4000. IER field also reflects $4000.
- When eCert is being finalized, a calculation is performed which sums all previous BCAG amount received during that PY, and ensures the latest 'eligible award' is reduced to comply with the annual maximum. In this case, the amount is reduced to $2000. 
- The student 'Assessment Summary' screen displays a 'final award' amount of $2000 for BCAG, along with some type of waring message explaining the reason for the discrepancy between 'eligible award' and 'final/actual award'. 

**Acceptance Criteria:**
- [ ] TBD based on full business identification of the funding type maximums
- [ ]

**Comment by Joshua-Lakusta** [comment]
Suggestion to make the changes at ECERT would mean that the assessment becomes worthless for all secondary PT applications as the entire application is built around program year limits.

**Comment by CarlyCotton** [comment]
Going to be addressed on #2571
