### ISSUE TITLE
Revise Offering Length Validations

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2446]
User Story:
As a ministry we want to alter the conditions of the 'minimum offering length' validation on FT and PT study period offerings to be based on the calculated number of funded weeks instead of study start and end date day numbers. Also make an adjustment to the 'maximum offering length' validation. This is important so that offerings that should be approved do not go to pending status.

Acceptance Criteria:
- [x] Remove the current validation on minimum offering lengths which require FT offerings to be at least 84 days, and PT offerings to be at least 42 days. Remove any associated warning message banner as well that is displayed when offering length does not meet those requirements. 
- [x] Apply a new validation on FT offerings which require that the Total Funded Weeks field is 12 or higher. If 11 or below, display an warning banner message below the "Study Period Breakdown" which reads: 

> "Full-time offerings must be at least 12 funded weeks of study or longer to be eligible. Any shorter offerings can be submitted but will require SABC review."

- [x] Apply a new validation on PT offerings which require that the Total Funded Weeks field is 6 or higher. If 5 or below, display an warning banner message below the "Study Period Breakdown" which reads: 

> "Part-time offerings must be at least 6 funded weeks of study or longer to be eligible. Any shorter offerings can be submitted but will require SABC review."

- [x] Adjust validations of PIR process during student application to remove the current validation on students when they enter study length which does not comply with the number of weeks policy.
- [x] We do NOT need to make any changes to current offerings in production
- [x] Adjust the validations imposed on Bulk Offering excel upload, as applicable. 
- [x] Update the warning messages in the Bulk Offering Upload to reflect the minimum funded weeks warnings above.
- [x] Remove second upper limit validation on the funded study days. Keep only the validation for start/end date days for now (will be addresses in future tickets).
- [x] Update the validation banner that shows when the days are over 365 to the following content:
> The dates you have entered will create an offering with more than 365 days.
<img width="1105" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK08wQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--09cf62294b585c91c54044e32a7f089db5d3781b/image.png" alt="image.png" />

**Test Scenarios**
Static generic offering details 
PT 
Any name
Year 1
40% intensity
Onsite
No to Work integrated learning
1000 Tuition
100 Books and Supplies
100 Mandatory Fees
0 Exceptional costs
No to public offering

FT
Any name
Year 1
Onsite
No to Work integrated learning
1000 Tuition
100 Books and Supplies
100 Mandatory Fees
100 Exceptional costs
No to public offering

Specific Scenario details

<img width="1183" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGhrQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2dd80919b47c01d00ab559ba63645a5cefa16c3b/image.png" alt="image.png" />

Business Context
<img width="789" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDVmQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4819b6ede64855dfd65c64cfd3101809e7813a39/image.png" alt="image.png" />

**Technical**
- [x] The validation in the Student Applications offerings dates is currently happening in the custom start and end dates validations and it should be removed. Ensure the start date is before the end date.
- [x] Offerings validations around funded days and weeks happen around the [offering validators](https://github.com/bcgov/SIMS/blob/main/sources/packages/backend/apps/api/src/services/education-program-offering/custom-validators/has-valid-offering-period-for-funded-days.ts#L22-L34).
- [x] Create new E2E tests for the new scenarios.
- [x] Suggested PRs
  - Student application validation changes (no E2Es required). 
  - Offering validations and form.io banners (E2Es required).

**Comment by michesmith** [comment]
@HRAGANBC @CarlyCotton @Joshua-Lakusta  Opportunity to trim out FT

**Comment by andrewsignori-aot** [comment]
@Joshua-Lakusta will provide some test scenarios to allow dev testing.

**Comment by andrewsignori-aot** [comment]
Possible reference: https://github.com/bcgov/SIMS/blob/main/sources/packages/backend/apps/api/src/services/education-program-offering/custom-validators/has-valid-offering-period-for-funded-days.ts#L22-L34

**Comment by dheepak-aot** [comment]
Question to business

This warning banner currently covers 2 validation and it's respective message. 

![image](https://github.com/user-attachments/assets/19ff1147-2e8f-4bf7-9c40-1dc345c504aa)


1. Minimum study period days  must be (84 for FT and 42 for PT)
2. Maximum study period days must be 365.

As per the current ticket we are updating condition 1. 

1. Minimum funded study weeks  must be (12 for FT and 6 for PT)
2. Maximum study period days must be 365.

Considering that the validation 1 is replaced by minimum study weeks. The warning banner message is now updated. 

But the updated warning banner message is completely ignoring the maximum 365 days validation context in it. 


![image](https://github.com/user-attachments/assets/bc87c586-2892-4c4f-bd09-d63fb1ec296b)


Hence either we need to update the warning banner message to have a common context or have a separate banner for condition 2.

**Comment by CarlyCotton** [comment]
@lewischen-aot 
Added two ACs based on our discussion today. Added the updated content for the upper limit validation and confirmed we can remove the second validation on the upper limit (365 funded days).

**Comment by CarlyCotton** [comment]
@lewischen-aot 
Added two ACs based on our discussion today. Added the updated content for the upper limit validation and confirmed we can remove the second validation on the upper limit (365 funded days).

**Comment by CarlyCotton** [comment]
@lewischen-aot 
Thank you for your patience on this ticket Lewis.... based on discussion with @sh16011993 I've updated the content on the two acs to indicate **"funded** weeks of study":

>"Full-time offerings must be at least 12 funded weeks of study or longer to be eligible. Any shorter offerings can be submitted but will require SABC review."

>"Part-time offerings must be at least 6 funded weeks of study or longer to be eligible. Any shorter offerings can be submitted but will require SABC review."

**Comment by CarlyCotton** [comment]
@lewischen-aot 
After discussion with Lewis, added AC to reflect the warning messages about minimum funded weeks in the bulk offering upload.
