### ISSUE TITLE
IER12 file adjustments

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#2452]
IER12 file adjustments.
 - Handle the case where STATE/PROVINCE field is not provided. 
 - Do not allow newline characters in text to split a record into multiple lines.
   
**Additional Context**
- We allow STATE/PROVINCE to be optional for students with addresses outside of Canada.
- The record that is causing the record to split into new lines has new line characters in the Program Description field.
  - The offending application number is 2023000706.
  - Could not attach picture/files., but here is an excerpt of what the record looks like: 
**....4BS        Web Design               Web design FT - Onsite only
Hours based
1year to lgraduateCertificate      0048    5   0144151100000 ....**
  - I have confirmed the offending field, Program Description, does indeed of new line characters.  Here is the SQL query for the field searched by the app number: select ep.program_description  from sims.applications a join sims.education_programs ep on a.pir_education_program_id = ep.id where a.application_number = '2023000706';

**Acceptance Criteria**
- [ ] IER12 file still generates even if there is a record with blank or null STATE/PROVINCE.
- [ ] Look for fields that could have newline characters and sanitize before injecting into IER12.

**Comment by dheepak-aot** [comment]
Province position to test 
Province code: 188
