### ISSUE TITLE
Add Offering ID into Interface

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2462]
**Description of Task**
Display the two unique Offering IDs (Parent ID and Secondary ID) directly onto the Offering form viewable through the interface.

**Acceptance Criteria:**
- [ ] Display parent Offering ID on offering form as soon as offering has been submitted (i.e. regardless of whether it's pending or approved)
- [ ] Display secondary Offering ID on offering form as soon as offering has been submitted (i.e. regardless of whether it's pending or approved)

**Comment by michesmith** [comment]
@HRAGANBC are you able to provide more biz context inthis ticket  as to why this is important and what it is used for. Which users use this feature? 
Also Im assuming this is required for PT Release

**Comment by CarlyCotton** [comment]
@HRAGANBC is this still necessary after the work on #2488 with the offering id being shown on offerings?

**Comment by HRAGANBC** [comment]
Thanks @CarlyCotton , yes it's now redundant. Closing ticket now.
