### ISSUE TITLE
Request a Change Forms - Modified Independent Status

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2468]
**Description of Task:**
Allow students to change their status from dependent to independent (and vice versa) on a complete application.

**Context:**
- See #2467 for context about general Request a Change Process
- 'Mod B' (aka Modified Independant) is a common student change seen in current state, whereby a student who initially reports themselves as having dependants can eventually request a re-assessment where they declare they have seperated/estranged from their parents and want to be considered as independant students for purposes of assessment. 

**Acceptance Criteria**
- [ ] Introduce new 'form title' called 'Modified Independent Status (Full-Time Applications)'
- [ ] The form should display one tick-box which can be selected by the student. The  wording next to the tick-box should read "I wish to submit an appeal request for Modified Independent Status."
- [ ] If the the tick-box is selected, a banner message below should be displayed with the following wording: _"To be approved for modified independant status, the student must provide additional documentation proving an irreconcilable between student and parents such that the student should be considered independent for purposes of Student Aid BC assessment processes. This proof could consist of: 
- A statement from you describing the family rift, how long the rift has existed and why it continues.
- A letter from a responsible third party testifying as to the truthfulness of your explanation and providing an independent
assessment of the situation. The third party could be any of the following: counsellor, psychologist, religious advisor, doctor, teacher, and/or mature relative outside the immediate family or family friend. The status of the third party and their relationship
to you must be identified in the letter.
- A letter from your parent(s)/step-parent/sponsor/legal guardian describing the family rift, how long the rift has existed and why it continues. If a parental letter cannot be obtained, a second letter from another professional third party must be submitted.
- A letter from the appropriate provincial or territorial agency confirming that you were a youth under the guardianship of, or in a Youth Agreement with, the agency on your 19th birthday (if relevant to your appeal circumstance)."_
- [ ] Build the subsequent review screens (_See Ministry Review Request_ photo and _Student Review Request_ photo)
- [ ] Change the workflow logic in the following ways:
- If request is denied, do nothing
- If field is left blank, do nothing
- If tick-box is selected, and the request is approved, treat the student the same as if they had indicated 'estranged from parents' on the initial application form **Workflows suggest this student is simply categorized as Independant, but I want to double check there are no unique Form.IO variables assigned specifically for this question**

- [ ] See #2467 for other details about how request interacts with COE requests, other pending reassessment requests, etc...

**Comment by Joshua-Lakusta** [comment]
This question is handled in the application. Therefore I am closing this for now as it will be incorporated into the change request revamp epic.
