### ISSUE TITLE
PT Request a Change - Financial Information

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2471]
**User Story**
As a Part-Time Student, I want to change my financial information on my Request to Change Form, so that I can ensure the correct financial information is provided for a reassessment.

**Acceptance Criteria**
- [x] Introduce new 'form title' called 'Financial Information'
- [x] The form should contain the following **mandatory** fields/questions, displayed exactly the same as in the Application Form
- "My total income in 2023 was:" (add free-input numeric field below)
- "What are your daycare costs that you incur for your children age 11 years of under?" (add free-input numeric field below)
- What are the total unsubsidized daycare costs during class hours for disabled/infirm dependents 12 years of age or older? (add free-input numeric field below)
- [x] Any file uploaders reflected in application form should be embedded within the Request a Change
- [x] Ensure that this form is Program - Year specific and therefore handled within Camunda inside the Program Year assessment workflow instead of assessment gateway.

**Technical Context**
-  [x] E2E test nice to have

**Business Context**
- See #266 for general business context. esp:
- Ministry approval of these Requested Changes is handled by #2549
- Other notifications to student about the need to consolidate previous Request a Changes is captured by #2555

**Comment by michesmith** [comment]
@HRAGANBC my instinct is to have a ux moc up of this one. Can we try and pull something visual together prior to grooming?

**Comment by michesmith** [comment]
@HRAGANBC The ministry view of this should be a separate ticket. They will need their own user story, and 'mock up' of this page for review. We can link them together as dependencies and they be able may go into the same sprint.

**Comment by dheepak-aot** [comment]
First AC updated from Introduce new 'form title' called 'Part Time Financial Information' 
To
Introduce new 'form title' called 'Financial Information'
as to keep the Financial Information form generic for FT and PT and populate the fields in the form based on offering intensity. 
As per discussion with @CarlyCotton
