### ISSUE TITLE
FT Request a Change - Exceptional Expense Appeal (Student)

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2472]
**Description of Task:**
Allow students to change their financial information 

**Context:**
- See #266 for context about general Request a Change Process

**Acceptance Criteria**
- [ ] Introduce new 'form title' called 'Exceptional Expense Appeal (Full-Time Applications)'
- [ ] Attach the following field/question to the form: "Do you want to submit an exemption request for exceptional expenses?" 
- [ ] Beneath this question, add the following two things:
- free-input numeric field 
- A message beneath the free-input field which is always displayed, and which reads: "You can report exceptional expenses if they created financial hardship that affected your ability to start or continue studies, such as: medical illness or injury, family emergency (e.g. death or injury), natural disaster, unforseen legal expenses, court-ordered payments, expenses related to your or your dependant's permanent disability that are not covered by another funding source (uninsured)." 
- [ ] If student inputs anything in this field, display a warning banner below reading: "Your request will not be approved until the following documentation is added to your Student Aid BC account using the File Uploader:
- A letter explaining your exceptional expenses, when the expenses occured, the amount of payment, and why these expenses were necessary during your study period
- A copy of your medical / dental insurance plan proving that this expense is not covered under your plan
- All relevant supporting documentation of your expenses (payment receipts, a copy of your bank statement, cancelled cheques, etc.)
- [ ] Build the subsequent review screens (_See Ministry Review Request_ photo and _Student Review Request_ photo)
- [ ] Change the workflow logic in the following ways:
- If request is denied, do nothing
- If field is left blank, do nothing
- If any fields are inputted, and the request is approved, replace the appropriate workflow variables with the new amounts and generate new assessment. 

- [ ] See #2467 for other details about how request interacts with COE requests, other pending reassessment requests, etc...

**Comment by Joshua-Lakusta** [comment]
Closing as this will be resolved under the request a change revamp epic.
