### ISSUE TITLE
Update PT Declarations Wording

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2482]
**Description of Task:** 
Update the wording of the Part-Time **partner** declaration and the Part-Time **student** declaration. 

Part-Time Partner Declaration Final Copy
[Part_time_SABC Partner Declaration_Final.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3V4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--80f74dadd42ff22b8e88ef6a027654e6c6cdf15e/Part_time_SABC%20Partner%20Declaration_Final.docx)

Part-Time Student Declaration Final Copy
[Part_time_SABC Student Declaration_Final .docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzZ4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7af961eac39c49eef490bac6e95d1875e7a62b3b/Part_time_SABC%20Student%20Declaration_Final%20.docx)

Acceptance Criteria:
- [x] If the application is for Part-Time students display the following content for partners and students only at declaration. This is *Not Required for Full time Students 
- [x] Update (COPY PASTE ) PT student declaration to reflect the wording provided in the Word document above
- [x] Update (Copy Paste)  PT partner declaration to reflect the wording provided in the Word document above

**Comment by lewischen-aot** [comment]
@HRAGANBC I'm attaching screenshots below for both this story for your reference. 

Part-Time Student Declaration Screenshot
<img width="686" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL09TQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3eda22fe66e11174dfd13d54ea83ede7c2836862/pt-student-declarations-wording.png" alt="pt-student-declarations-wording.png" />

Part-Time Partner Declaration Screenshot
<img width="1001" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1NTQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8b706e950bfebe1bed886bc9165f4e539dc5da31/pt-partner-declarations-wording.png" alt="pt-partner-declarations-wording.png" />

The following screenshots are for full-time applications which are not modified. I'm attaching them here as references to the part-time screenshots above.

Full-Time Student Declaration Screenshot
<img width="1374" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2VTQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--50d38bf89c2dc2fd3e8455ebb52b004a8b25a308/ft-student-declarations-wording.png" alt="ft-student-declarations-wording.png" />

Full-Time Partner Declaration Screenshot
<img width="1146" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2lTQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2f82f477384136748ec75dc1e6ab7a9fc61ef6e2/ft-partner-declarations-wording.png" alt="ft-partner-declarations-wording.png" />
