### ISSUE TITLE
Bull Dashboard UI authentication change

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#2483]
Review with David Malcolm what we are requireed to change, if at all, to the authentication method for Bull Dashboard UI.
If BullDashboard is not pubicly exposed, does that mean we still can't use basic authentication?

**Comment by cditcher** [comment]
Spoke with David. Current connection is https and basic auth is acceptable. For test and prod, non publicly exposed endpoints are not an issue as we can port-forward directly to the OpenShift service layer.
