### ISSUE TITLE
Incorporate 'Year of Study' Field into All Offering Names (mandatory); Change Duplicate Offering Validation   

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#2484]
**Description of Task**
Revise the 'duplicate offering name' validation to allow duplicate offering names **IF** the year of study is different

**Current Behaviour**
- Currently the PSIs cannot see the 'Year of Study' as part of the offering name (when show = yes) when viewing the offerings for a program. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2V4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--52a705f1a997d005111281f81e1ff0cde3a605b1/image.png)
- When trying to create offerings, via SIMS or bulk upload, it prevents creation of new offerings when name, start date and end date have a match.  Even though these are unique offerings based on a difference in the year of study.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2l4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0764b2e3011a4393d0adb1906bdb5a5b926efcbf/image.png)

**Expected Behaviour**
- "Show Year of Study" will no longer be optional and default to "Yes"
- Institutions can view Year of Study in the offering names with viewing offerings.
- When creating new offerings, uniqueness will be determined by: offering name, year of study, start & end dates.
- Reject new offerings from being created if the 4 fields are the same: offering name, year of study, start & end dates.

**Sample data**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenV5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d4cc33378cb046f4bde2270de36a7b40e0da77ae/image.png)
Rows being flagged as duplicates that we would like to allow as unique based on year of study being different:

- 2 + 12
- 3 + 11
- 4 + 9
- 5 + 7
- 6 + 10

Example bulk offering attached (saved as .txt and headers may need to be updated to match bulk upload rules) [uniqueofferings.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemV5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e2b131f077698b02a9356b61f85057c7bb763e6e/uniqueofferings.txt)

**Acceptance  Criteria**
- [x] Display the Year of Study in the Offering Name for Institutions in their list of Offerings
- [x] Add a Year of Study Column to the Institution View of the list of Offerings 
- [x] Remove the "Show Year of Study" option for manual offering creation. Default all new offerings to "yes".
- [x] Remove "Show Year of Study" column from database
- [x] The duplicate check for offerings should only prevent creation when all of the following match: Name, Year of Study, Start date, End Date and Offering Type.(#2567 is handled by the index update here)
- [x] The validation change should be applied to every location where offering validations are applied (i.e. 'Add Offering', 'Edit Offering', 'Bulk Offering Upload', 'Scholastic Standing Cloning Offering')
- [x] Bulk Upload Error **should read:** "Duplication error. An offering with the same name, year of study, start date, and end date was found. Please remove the duplicate offering and try again."
- [x] Manual Creation Error **should read:** "Duplication error. An offering with the same name, year of study, start date, and end date was found."
- [x] On the 'Add Offering' form, add a blurb under the year of study field that says: "This will be displayed as part of the offering name".
- [x] During the reading-in of the **Bulk Upload File**, Ignore the 'Display to Student?' column altogether (but don't change the File formatting) 
- [x] Check student application dropdown and other offering dropdowns
- [x]
- [x] Ensure that the duplicate check will happen only for Public and Private offerings types. Any other type, for instance, Scholastic Standing, should be able to be duplicated as needed. Public and Private offering are the only ones displayed to the users and that is way we need to ensure that they will not be duplicated.
- [x] Ensure that PIR offerings list is also displaying the "Year of Study".

**Comment by cditcher** [comment]
@HRAGANBC and @CarlyCotton to hash out UI details. Should we display the date in UI?

**Comment by CarlyCotton** [comment]
@cditcher No change in withdrawal UI error messaging on the ones that are still duplicates. Displaying the date wouldn't be necessary since they have the line number of the record that has the issue.

Added clarification in ACs above:

If 'display to students' = no for Year of Study & Name/Start Date/End Date match still treat as duplicate offering:
- [ ] Bulk Upload Error: Same as existing "Duplication error. An offering with the same name, start date, and end date was found. Please remove the duplicate offering and try again." _(existing functionality)_
- [ ] Manual Creation in SIMS Error: "Duplication error. An offering with the same name, start date, and end date was found."

**Comment by HRAGANBC** [comment]
@HRAGANBC Need to consider:
- Whether to make Year of Study always displayed in Offering title (i.e. remove the 'optional display' button
- Make any corresponding changes to Bulk Upload template
- Does this impact any Bulk Upload data already inputted by schools?
- What about

**Comment by CarlyCotton** [comment]
Just popping in the quick analysis of options here for future reference:

1. options as written to have "two paths" to provide options to school for show year or not / no change to previously uploaded offerings
2. remove option to show year, default to NO. / remove column from bulk upload / remove from offering creation / update existing records in PROD / keep unique the same (name+start+end) to force schools to update the name manually to reflect year of study
3. remove option to show year, default to YES / remove column from bulk upload/ remove from offering creation / update existing records in PROD / update PSI offering dashboard to show year in offering name (not currently showing) / update unique (name + year + start + end) and force schools to use the year of study in their offering names.
4. ?

**Comment by CarlyCotton** [comment]
Discussion from Dec 13 to have ACs updated to:
remove option to show year / ignore column from bulk upload/ remove from offering creation + default to YES / update existing records in PROD / update PSI offering dashboard to show year in offering name (not currently showing) / update unique (name + year + start + end) and force schools to use the year of study in their offering names / communicate to schools via Instructional Guide

**Comment by CarlyCotton** [comment]
@HRAGANBC I"ve updated the ACs if you want to have a review before sending back for grooming
