### ISSUE TITLE
Integration filenames and encoding changes & SFTP Folder structure change. 

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#2504]
**Describe the task**
Technical adjustments need to be made to the integration filenames and locations.
- All files must be encoded in ASCII instead of UTF-8
  - Includes integration files: IER12, ECE, ECE Response, Bulk Offering and Bulk Withdrawal
  - Includes federal files: MSFAA, ECERT, CRA
  - Please note, we understand any charcters that are not part of the ASCII character set, will not be encoded correctly and if that causes an issue, we will just deal with them on an adhoc basis.
- IER12 filesnames need to be prefixed with the institution code and require some notiation modification to align with existing IER filename standards.
  - Current format: IER_012_2023-10-23_12.17.01.txt
  - New format:      AUAE-IER12-20231023-12170100.txt
    - Changes:
      - YYYY-MM-DD to YYYYMMDD (removal of dashes)
      - HH-MM-SS to HHMMSSMM (removal of dashes and add milliseconds)
      - Change "IER_012_" to "IER12-"  (contraction and change the "_" following "12" to "-")
      - Prefix file name with school code "AUAE-" (note the "-" at the end of the code)
        - Realize this prefix is inconsistent with any other file names, but this was requested by Harry IER12 is a new file that does not require merging and it simplifies processing on his end.
- ECE filename needs some notation modification to align with existing file name structure from SFAS
  - Current format: ECE_2023-10-23_12.08.40.txt
  - New format:      ECE-20230927-11551700.txt 
    - Changes: 
      - YYYY-MM-DD to YYYYMMDD (removal of dashes)
      - HH-MM-SS to HHMMSSMM (removal of dashes and add milliseconds)s
      - Change the "_" following "ECE" to a "-"
- Change in the folder structure for integration files.
  - Swap IN and OUT folder function.  OUT should be for files generated by SIMS and IN should be for files read by SIMS.
  - Instead of "../Institution-Request/[School code]" it will be "../OUT/[School Code]"
    - ***NOTE: I believe this is already modifiable in the secrets variables.  Discuss with Jason***
  - Instead of "../Institution-Response/[School code]" it will be "../IN/[School Code]"
    - ***NOTE: I believe this is already modifiable in the secrets variables.  Discuss with Jason***

      

**Acceptance Criteria**
- [x] Change encoding of all files to ASCII
- [x] Change ECE request file name
- [x] Change IER12 file name
- [x] Adjust for the new folder structure
- [x] Update any impacted E2E tests
- [x] Swap IN and OUT folder function.

**Comment by cditcher** [comment]
Break it down.

**Comment by guru-aot** [comment]
The acceptance criteria point 2
Change ECE request and response file name -  when trying to process the response of ECE file, previously we know the filename so. we process it as asingle file. But now when we change it to finding a pattern of files in the folder path. we may incure multiple files. If that is the case, 
1. how should we process them?
2. What is the order of processing?
3. Do we get multiple files?
@JasonCTang @ninosamson @HRAGANBC

**Comment by guru-aot** [comment]
@JasonCTang when i see the request filenames the milliseconds are 2 digits it should be 3 digits

New format: AUAE-IER12-20231023-12170100.txt
Changes:
YYYY-MM-DD to YYYYMMDD (removal of dashes)
HH-MM-SS to **HHMMSSMM** (removal of dashes and add milliseconds)

Suggested 
HH-MM-SS to **HHMMSSMMM** (removal of dashes and add milliseconds)
AUAE-IER12-20231023-121701000.txt

**Comment by JasonCTang** [comment]
how should we process them?
- This was my mistake.  You've been looking for files that begin with CONR-008*, you can continue doing this.
What is the order of processing?
- Under normal circumstances, we only expect 1 file per day, so there should never be more than one file present.
Do we get multiple files?
- The only circumstance where we would get more than one file is if the job in SIMS stops running for multiple days and SFAS continues to add more files during that time.

**Comment by guru-aot** [comment]
@JasonCTang  

<img width="1547" alt="image" src="https://github.com/bcgov/SIMS/assets/62901416/30c758cc-8db8-404f-bb42-e4b2d7415525">

Both these mentions are contradicting, can you please explain if we need to have a Institution_code folder for IN and OUT folders? or how it should be implemented?

**Comment by JasonCTang** [comment]
That was a copy and paste error on my part. I've updated the description.

**Comment by JasonCTang** [comment]
@guru-aot   As per our discussion, we need to change the action that we take after reading a file.  Instead of deleting it, we need to copy it into a sub folder called /archive.  I will create the folder in each of the response folders.

**Comment by andrewsignori-aot** [comment]
> @guru-aot As per our discussion, we need to change the action that we take after reading a file. Instead of deleting it, we need to copy it into a sub folder called /archive. I will create the folder in each of the response folders.

@JasonCTang the system does not archive files in any of the current processes. The idea was that SIMS SFTP would be just a disposable set of files. I believe now that this direction is changing and we need review this process for the other integrations also. Does it make sense or the archive is only for the institution files?

**Comment by JasonCTang** [comment]
ECE response file name change acceptance criteria moved to #2800

**Comment by guru-aot** [comment]
@JasonCTang  The filenames when we create, the timestamp we append we use it in PST. Is that the right timezone for the file names to be created. Please confirm.

**Comment by JasonCTang** [comment]
Yes, PST is correct.

**Comment by JasonCTang** [comment]
I have made an error in the file path for the new folder structure.  I had previously defined as "../SIMS/OUT/[School Code]/IN/[School Code]" and "../SIMS/IN/[School Code], but this is actually incorrect because the root of the SFTP server is already the folder ../SIMS.  Therefore the actual folder structure should be "../OUT/[School Code]" and "../IN/[School Code]"

I have changed this in the description above already.

I have also removed the folder change for federal files as this is just a change to the Secrets File that I can do myself.
