### ISSUE TITLE
[POTENTIAL DUPLICATE OF 2912] SIMS - SFAS Data Bridge

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2507]
**Description of Task**
Create a process for relaying critical SIMS student account and application information to SFAS to catch study date overlap checks and other policy rules

**Context**
- A data bridge was built to communicate SFAS data to SIMS. This included Study dates, PD/PPD status, Over awards, restrictions etc.. 
- Student 'matches' were detected if all personal details were landed (Name, DOB, SIN) 
- If a PT-first release is being pursued, then SIMS will handle PT students as of Spring 2024, and FT students will continue to be using SFAS. 
- The SIMS --> SFAS data exchange should accommodate a PT release in Spring 2024, but also consider FT students being streamed into two systems simultaneously. 

**Business Requirements**
- Detailed file specifications can be found on MOD External Teams Channel:
https://bcgov.sharepoint.com/:w:/r/teams/00371/Shared%20Documents/General/b)%20Development%20and%20Testing/SIMS%20Business%20Requirements/Under%20Development%20Requirements/SIMS%20to%20SFAS%20Data%20Bridge.docx?d=w588bf9022725400f998ea8cce1c27448&csf=1&web=1&e=JvpAU1

**Acceptance Criteria**
- [ ] Complete the technical requirements to support this file exchange and input them into the above Buiz Reqs document
- [ ] Create file according to specifications in document   
- [ ] Generate file in SFTP server
- [ ] Create queue to generate file every day.

**Comment by michesmith** [comment]
@JasonCTang to update ticket with feedback from Harry

**Comment by HRAGANBC** [comment]
Duplicate of 2912 - closing
