### ISSUE TITLE
Update formio server and js

### ISSUE THREAD

**Issue by guru-aot** [bcgov/SIMS#2509]
Update formio server and js

**Acceptance Criteria**
- [x] Update formio server  to 3.3.(4) or the most updated one and check on the differences from the current one.
https://github.com/formio/formio/compare/v2.5.3...v3.3.4
- [x] Update formio js version to 4.17.3 or the latest.
https://github.com/formio/formio.js/releases/tag/v4.17.3
- [x] Update release notes instructions
- [x] Check the main form applications, designation agreement, student profiles, form.IO definitions
  - [x] Ensure that the smoking test is executed locally using the web docker to check the application deployed using nginx to validate possible security policy adjustments.

**Additional context**
Created the below wiki to help with the form.io server upgrade.
[Development ‐ Form.io Server Upgrade](https://github.com/bcgov/SIMS/wiki/Development-%E2%80%90-Form.io-Server-Upgrade)

**Comment by andrewsignori-aot** [comment]
## Smoking Tests Executed on DEV

- Student
  - Created a new BCeID Student.
    - Updated student profile.
  - Created a new Part-time application with a partner.
    - Provided partner information using supporting users portal.
  - Created a new Full-time application.
- Ministry
  - Created a new institution
  - Updated the new institution
  - View a submitted designation
  - Approve a designation
- Institution Side
  - Update Institution Profile
  - Created a new location
    - Updated a new location
  - Submitted a new designation
    - View a submitted a new designation
  - Created a new program
    - Edited the new program
    - Created a new offering
     - Edited the new offering
- Approved COE
