### ISSUE TITLE
Apply/Receive PD/PPD Profile Verification  (Part 1) 

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2518]
**Description of Task**
- Revise UX/UI for the 'Apply for PD/PPD' on Student Profile; 
- Revise UX/UI for the Ministry and Institution view of Student Profile
- Allow Ministry to manually change the student's PD/PPD profile status 

**Context:**
- Automatic PD/PPD validation with ATBC is **not** critical for a PT-release. Scale of new PD/PPD applications is small, so can be handled via manual data input into SIMS instead of automatic integration with ATBC. 
- All related topics are covered in DIFFERENT tickets:
      - How SIMS PD/PPD profile status maps into IER / ECE files
      - How student can Request a Change on their PD/PPD status
- Expiry date and effective dates are NOT applicable in SIMS for MVP release

### **Acceptance Criteria**

**Student PD/PPD Profile Application**

- [x] Revise the wording on the student's ‘Apply for PD status’ profile button to read: “_Apply for Disability Status_” [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeS80QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--913d2fc2aa2b24ee51196cbf9857243fe8bd6100/image.png)
- [x] Revise the wording on the ‘Apply for PD status’ profile modal header to read: “_Apply for a Disability Status_” [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3Y0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--df9b5f982ed43530b313fad37e2ec16504311a5e/image.png)
- [x] _Hide the ‘apply now’ button from the modal, so that the modal is for information purposes only (The 'apply now' button and resulting functionality will be re-introduced later when ATBC integration is finalized, but for now, the PD/PPD application process will be conducted entirely outside of SIMS.)_
- [x] Revise the student profile disability status ‘tooltip’ to read: "If you wish to identify as a student with a disability and receive disability-related financial assistance as part of your Student Loan award, you will need to have your disability verified by StudentAid BC.”  (See photo) [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekQ0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--64e07e08dd3baace758a17faf92157abecbbfc45/image.png)
 
**Revise PD/PPD Application Wording**
- [x] Revise the PD/PPD application question and options (on FT and PT) to read: 
Question should read: "Are you a student who has verified your Disability Status with StudentAid BC as a Permanent Disability (PD) or a Persistent or Prolonged Disability (PPD)?  If so, choose option 1.  If you have not verified your Disability Status as PD or PPD before, and wish to receive other funding types, choose option 2, complete and submit an Appendix 8 form to StudentAid BC.  This may allow you to receive some funding while StudentAid BC verifies your Disability Status.  

You can find PD and PPD definitions, available disability type funding, eligibility requirements and how to submit your form on Appendix 8"

Options should read: 
- 1. Yes, I identify as a student with a disability and have verified my Disability Status with StudentAid BC before.  I want this application to be assessed for all funding types (including disability type funding).
- 2. No, I have not verified my Disability Status with StudentAid BC and do not identify as a student with a disability at this time.  I want this application to be assessed for other funding types while my Appendix 8 form is being processed to verify my Disability Status.
- 3. No, I will not verify my Disability Status with StudentAid BC.  I want this application to be assessed for other funding types only (no disability type funding)..

- [x] Revise the PD/PPD application question 'info!' banner message (on FT and PT) to read: "Info!
If you have not verified your Disability Status with StudentAid BC as PD or PPD and wish to receive disability type funding, you must first complete and submit an Appendix 8 form. Once StudentAid BC verifies your Disability Status, you must Request a Change on your student financial assistance application to receive disability type funding.  
An applicant who identifies as a student with a disability and does not have their Disability Status verified with StudentAid BC will not receive any funding type (other or disability) until their Disability Status has been verified.  If you wish to receive other type funding while StudentAid BC verifies your Disability Status, please choose option 2."

**Introduce new PD/PPD Statuses**

- [x] Create new PD/PPD Profile ‘status’ options:
- Not Requested (this is already the default)
- Requested (this will not automatically be assigned, this is manual input by the Ministry as well)
- Approved for Permanent Disability
- Approved for Persistent or Prolonged Disability
- [x] Allow Ministry staff to view current PD/PPD Profile status within the Ministry view of Student Profile, and to use a dropdown menu to **change** the status at any time. See photo [Private Zenhub Image]
(https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNy85QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e143b222713dc44562a0f1777ff295fdc81e9b1f/image.png)
- [x] Anytime Ministry staff change the PD/PPD status, require a note to be provided. Note gets added to the Notes section of the student account. 
- [x] Anytime a Ministry staff change a status to 'Approved for PD' or 'Approved for PPD', log the date that this action was taken within the database as 'Effective Date' (Doesn't need to be reflected in UI for now)
- [x] Display the Student Disability Status on the Student Account Profile, **and** the Institution view of the Student Profile **and** the Ministry view of the Student Profile.
- [x] Create a aest role in keycloak for ministry user to update the disability status of a student. And also update the aest keycloak role spreadsheet

 Note: Ministry role `student-update-disability-status` added to `aest-business-administrators` group

**Comment by dheepak-aot** [comment]
Added AC 
- [ ] Create a aest role in keycloak for ministry user to update the disability status of a student. And also update the aest keycloak role spreadsheet

**Comment by dheepak-aot** [comment]
Removed `(Hold off for now)` from second AC as per discussion with @HRAGANBC

**Comment by dheepak-aot** [comment]
Note: Ministry role `student-update-disability-status` added to `aest-business-administrators` group
