### ISSUE TITLE
Map PD/PPD Status to COE screen, eCert and import from SFAS

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2522]
**Description of Task**
Implement/display the student's disability status in the IER-12 fields, the ECE fields, and the COE interface screen

### **Acceptance Criteria:**

**COE Interface Screen**
 - [x] Add a student’s disability profile status
 - [x] Add a student’s disability application request as one line on the student’s COE request
[Private Zenhub Image]
(https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1g5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0068edcc1bc7e1c716c6289192c0df8c1de916b4/image.png)
  - 'Disability Profile Status' description should correspond to the disability status from the student's profile, i.e. "Not Requested", "Requested", "Approved for Permanent Disability", etc....
  - 'Disability Application Status' should have one of the following options, each of which correspond to one of the disability application questions.
     - "Assessment Includes Disability Funding Types" (corresponds to option 1 in the student form)
     - "No disability funding types included on assessment" (corresponds to option 2 or 3 in the student form)

**E-cert**
- [x] On PT eCert SEND file, populate PPD field with CalculatedDataPDPPDStatus
*FT eCert file does not contain any PD/PPD field

**SFAS Data Bridge**
<img width="969" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVZ0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5784f95e0327e4415f9d6a7ce25fdad4c03e1c07/image.png" alt="image.png" />
- [x] Map SFAS imported data in following way:
- SFAS PD Field --> 'Approved for PD' in SIMS (the date the status was changed in SIMS becomes the effective date)
- SFAS PPD Field --> 'Approved for PPD' in SIMS (the SFAS PPD Status Date read from the file becomes the SIMS 
 effective date)
*Note: there is no longer any 'expiry date' for SIMS - only an effective date. 

- [x] Remove the PD legacy column `pd_verified` from the database.

**Comment by HRAGANBC** [comment]
All ACs related to mapping PD/PPD info to IER and ECE are moved to #2606

**Comment by andrewsignori-aot** [comment]
@michesmith @HRAGANBC, I added the below AC to the ticket. It was originally planned to be executed in #2445 but is now in the icebox.
This ticket is already estimated to be 5, so maybe we can double-check with devs if they are comfortable keeping it as a 5.
"Remove the PD legacy column `pd_verified` from the database."

**Comment by HRAGANBC** [comment]
<img width="754" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmpoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--61486afab904e575f488ca4d2d73dcc980a0deaa/image.png" alt="image.png" />

In the above photo, the 'Disability Profile Status' description should correspond to the disability status from the student's _profile_, i.e. "Not Requested", "Requested", "Approved for Permanent Disability", etc....

In the above photo, the "Disability Application Status" should have one of the following options, each of which correspond to one of the disability _application_ questions. 
- Assessment Includes Disability Funding Types (corresponds to option 1 in the student form)
- No disability funding types included on assessment (corresponds to option 2 or 3 in the student form)

**Comment by ninosamson** [comment]
Updated ACs post discussion regarding effective/expiry dates.

**Comment by andrewsignori-aot** [comment]
Currently, SIMS will check for PD/PPD flags only during student account creation, which means that future changes in SFAS will not be reflected on the student profile.
@HRAGANBC, does it make sense?
