### ISSUE TITLE
PD/PPD Assessment and Disbursement Logic

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2523]
**Description of Task:**
Outline the logic for how application and profile status, including expiry date, impact assessment and disbursement

**Context:**
- Request a Change for PD/PPD will be handled by separate ticket (#2466)
- Automatic re-assessment 2 weeks prior to study end date will NOT be pursued anymore. Instead, an email to student will be sent notifying them of next steps
- Instead of automatic re-assessment, we will send email notifying them of withheld disbursements. This is captured in #2536

### **Acceptance Criteria**
- [x] Save PD/PPD Application Question response in the workflow data (to be referenced later at the eCert check)
- [x] Save calculatedDataPDPPDStatus to the workflow data
- [x] **Check for Disability Profile Status at eCert Generation using calculatedDataPDPPDStatus:**
  - Student assessment contains PD/PPD _application_ flag=yes then
    - Student profile PD/PPD approved, generated e-Cert.
    - Student profile PD/PPD missing approval, withhold disbursement.
- [ ] Stop performing this check 42 days after study end date. At that point, disbursement is effectively cancelled and cannot be sent. 
- [x] Add unit or e2e test (depending on which is relevant).

**Comment by andrewsignori-aot** [comment]
@HRAGANBC should we add to this ticket the change to have the proper flag (`calculatedDataPDPPDStatus`) used for the e-Cert?
@dheepak-aot is aware of it and can provide more information if needed.

**Comment by HRAGANBC** [comment]
@andrewsignori-aot  @dheepak-aot 

The logic in the ticket is correct (i.e. check for calculatedDataPDPPDStatus when determining whether to send or withhold the eCert) 

BUT

The variable which gets inputted **onto** the eCert file corresponds to the PD/PPD **application flag** (i.e. **not** the profile status). I will include this in the related mapping ticket

**Comment by guru-aot** [comment]
Stop performing this check 42 days after study end date. At that point, disbursement is effectively cancelled and cannot be sent.
is already happening when we fetch the eligible disbursements records for the ecert generation. Hence not checking this AC.

**Comment by guru-aot** [comment]
PD effective date is not considered, when ecert generation is happening.
