### ISSUE TITLE
Reports Data Inventory Analysis

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2525]
**Description of Task**
- Analyze the list of proposed data elements included in the Reports (aka Data Extracts inventory) to determine which ones are already mapped, which ones can be mapped/retrieved easily, and which ones will be difficult. 

**Context:**
- Link to Data Extract Inventory is [here]: https://bcgov.sharepoint.com/:x:/r/teams/00371/Shared%20Documents/General/b)%20Development%20and%20Testing/SIMS%20Business%20Requirements/Final%20Requirements/SIMS%20Reports%20%26%20Notification%20Triggers/SIMS%20Reports%20%26%20Notification%20Triggers.xlsx?d=w48db67c03b894ce890291a6b6e606e14&csf=1&web=1&e=N6rUNe

Acceptance Criteria:
- [ ] Generate CSV for all data elements from Excel which are currently available / easy. Use Excel fields as friendly names for output of CSV. Only look at the data elements labelled 'critical' in column K
- [ ] Enable new Report type in the UX/UI
- [ ] Create new ticket for all data elements which are NOT incorporated as part of this initial CSV, and which require further discussion.

**Comment by andrepestana-aot** [comment]
The columns not implemented/defined will display "--TBD--" as values to be very clear that it wasn't implemented yet.

**Comment by andrepestana-aot** [comment]
New tickets: https://app.zenhub.com/workspaces/student-information-management-system-5fce9df5aa1b45000e937014/issues/gh/bcgov/sims/2580 and https://app.zenhub.com/workspaces/student-information-management-system-5fce9df5aa1b45000e937014/issues/gh/bcgov/sims/2587
