### ISSUE TITLE
Ensure BCSL Amounts are Split Across Disbursements 

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2533]
**Description of Task**
Ensure that the full award amount of BCSL for an application is split evenly across all disbursements scheduled for the application

Example of error: application number 2023000732

**Acceptance Criteria**
- [ ] Revise disbursement configuration calculation so that BCSL is split evenly across all disbursements of an application

**Comment by cditcher** [comment]
@HRAGANBC is this already covered under the ticket #2401

**Comment by HRAGANBC** [comment]
@Joshua-Lakusta I think Chris's comment above is accurate and this ticket should be closed, but want to confirm with you first. 

#2401 indicated that BCSL and CSL amounts are offset across disbursements, i,e. BCSL and CSL amounts are typically identical for the application, and CSL is assigned to the first disbursement and BCSL is assigned to the second disbursement. This is OK?

**Comment by HRAGANBC** [comment]
@Joshua-Lakusta as dicussed this AM, closing this ticket as its obsolete and fully replaced by 2401
