### ISSUE TITLE
 PT Request a Change - Financial Information (Ministry Processing)

### ISSUE THREAD

**Issue by michesmith** [bcgov/SIMS#2549]
### **In Sprint sequence, this ticket should be prioritized ahead of others related to Request a Change.** 

**User Story**
As a Ministry User, I want to view a Part-Time students changed financial information on their Request to Change Form, so that I can ensure an reassessment is required 

**Acceptance Criteria**
- [x] Change the workflow logic in the following ways if the ministry user:
- [x] denies request, do nothing
- [x] If the request is approved , adapt the calculations to use the new Request a Change variable instead of original values, and re-assess. Incorporate this logic into PT Assessment Workflows for PY 22/23, PY23/24, PY 24/25

**Technical**
- [x] Change the `load-assessment-consolidated-data` to load the appeal data. Follow the same already in place for `appealsStudentDisabilityAppealData`.
- [x] Create a centralized place to process all the "Request a Change"(Appeals) into the program year-specific workflow. Share the approach with DEVs ahead of the PR.
- [x] Create a new calculated variable as a result of the appeal vs student data.
- [x] The current studentData variables should be replaced along the entire workflow.
- [x] Include the PDPPD status, already in place, as part of the centralized logic.
- [x] Add E2E tests following the same from PDPPD.

**Buiz Context:**
- See #266 for context about general Request a Change Process
- See #2471 for Student Request a Change about Financial Information

**Comment by HRAGANBC** [comment]
@michesmit Communications back to student occur through generic auto email anytime a Request a Change is actioned by ministry
