### ISSUE TITLE
PROD Datafix required - Ineligible Program Message on Eligible Program

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#2553]
**Describe the Bug**
In Production, when viewing already existing (eligible) programs there is a warning message that the program is ineligible for StudentAid BC funding.
<img width="740" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU10QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d7c012e7303b8e89cf84bc4794b9ea17996ee7bf/image.png" alt="image.png" />

**Expected Behaviour**
In programs that are eligible for funding, there should not be a warning message. 

**Actual Behaviour**
A data change may have affected the messaging in the program view to show the warning message about being ineligble. They are still **correctly** showing as Approved:
<img width="835" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWt0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7748f8c81ed4f4fbe6745cc7da2a50f9eb850cdb/image.png" alt="image.png" />

** Steps To Reproduce**
Not reproducible in TEST - these are existing programs in PROD.

Programs in PROD prior to late July/August seem to be affected when they have a specific entrance requirement selected:
-  This program has entrance requirements established by the institution that enable completion of the program study.

Some of the programs affected:
BCIT : Boilermaker Foundation (submitted June 29, 2023)
BCIT : Auto Body Repair and Refinishing Technician Foundation (submitted July 4, 2023)
UVIC : Bachelor of Arts (submitted June 28, 2023)
UVIC : Bachelor of Science (submitted June 28, 2023)
Langara : Bachelor of Science in Nursing (Terms 1, 4 and 7)

**Acceptance Criteria**
- [ ] Not possible to reproduce in dev and test.  please consider the prod data for the investigation 
- [ ] Programs that are eligible in SIMS don't show warning message.
<img width="741" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHRNQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7877141b4ba4a970cd3ceb582e8220d64606d41d/image.png" alt="image.png" />

**Comment by michesmith** [comment]
@CarlyCotton  can you please create clear AC's

**Comment by CarlyCotton** [comment]
@michesmith I've added an AC, this is a bug though. It is not operating the same way that it does in current state/test. Something has changed between initial launch for PSIs and approx August to change how these existing programs are being displayed.

**Comment by CarlyCotton** [comment]
May be related to the work done on:
Institutions - Rename an item in Regulatory Dropdown field #2059 ?

**Comment by andrepestana-aot** [comment]
Looks like it happens in DEV too:
<img width="1063" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTA2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--24f7b2e36c5bacee3f547765053a1cd9cda59894/image.png" alt="image.png" />
