### ISSUE TITLE
Remove Course Load Calculation in PT Assessment

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#2557]
**Describe the task**
Currently, the PT assessment reduces the course costs by the course intensity. The assessment for part-time course costs does not need to have a calculation to correct for the course load percentage, it is already entered in the offering based on the intensity.

**Acceptance Criteria**
- [x] Remove _calculatedDataCourseLoadPercentage_ from calculation in parttime-assessment-*.bpmn (Screenshot)
- [x] Under "Calculate Course Load Tuition Totals": Update _calculatedDataActualTuitionCosts_ = offeringActualTuitionCosts
- [x] Under "Calculate Course Load Tuition Totals": Update _calculatedDataMandatoryFees_ = offeringMandatoryFees
- [x] Under "Calculate Course Load Tuition Totals": Update _calculatedDataProgramRelatedCosts_ = offeringProgramRelatedCosts
- [x] Under "Calculate Course Load Tuition Totals": Update _calculatedDataExceptionalExpenses_ = offeringExceptionalExpenses- This one was was complete in #2229
- [x] Update any affected E2E tests- Nothing was affected. 

**Screenshot**
<img width="413" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNk16QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a1e352f3acf43e03f8b34128ebc81d2057229dfe/image.png" alt="image.png" />
<img width="362" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0F6QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--58b858237a3047572eba029475fd8d2641881b55/image.png" alt="image.png" />

**Comment by CarlyCotton** [comment]
@Joshua-Lakusta Can you just double check that this captures it?

**Comment by guru-aot** [comment]
Under "Calculate Course Load Tuition Totals": Update calculatedDataExceptionalExpenses = offeringExceptionalExpenses
 THis AC cannot be done as it has been removes as part of #2229
