### ISSUE TITLE
Institution Profile Information Wireframe 

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#256]
2 sections 
-1 read-only Information from Business BCeID
- 2 Editable Institution Profile Information

**Comment by roopfw** [comment]
**Figma Prototype:**
https://www.figma.com/file/VykmBDwobGoGvK9M5wgOvN/FreshWorks-Studios-StudentAid-BC-App-Design-System-WIP?node-id=21%3A451

![image.png](https://images.zenhubusercontent.com/5e66ca845237f60c730a4aa3/68fae15f-93c7-4319-820e-18e8458c2a20)

**Comment by roopfw** [comment]
Updated Profile page with ability to add multiple institution locations and contacts.
Figma Link: https://www.figma.com/proto/VykmBDwobGoGvK9M5wgOvN/FreshWorks-Studios-StudentAid-BC-App-Design-System-WIP?node-id=400%3A0&viewport=-268%2C-2235%2C0.25&scaling=min-zoom
![image.png](https://images.zenhubusercontent.com/5e66ca845237f60c730a4aa3/8c96b423-7e40-4b70-95a7-f32c5141355b)
