### ISSUE TITLE
Minimum validation for the date entered on scholastic standing creation

### ISSUE THREAD

**Issue by dheepak-aot** [bcgov/SIMS#2568]
**User Story**
As an **Institution User**, I want to be subject to validations on the dates when I can report a scholastic standing event: I should only be able to report scholastic events which fall within a student's study dates. 

**Acceptance Criteria**
- [ ] Only allow the date entered during School Transfer, Early Completion and Withdrawal to be within a student's study dates (actual start and end dates are inclusive within the eligible dates)
- [ ] Only allow the date entered during School Transfer, Early Completion and Withdrawal to be before or equal to today. I.e. an institution cannot report a withdrawal date that is in the future. 
- [ ] The action of reporting the event itself can occur until application is archived. 
- [ ] Ensure the UI list of 'able to report' applications in the scholastic standing section reflects the validations above. 

**Mockups - These are Current-State, but do not reflect changes from #3040**
<img width="896" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFk3QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--267f90599bc97a5c8fb92a9101678ef1fe4ba403/image.png" alt="image.png" />

<img width="682" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGc3QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--21e93a4689b637b25402499eb552d290a2d3e8eb/image.png" alt="image.png" />

<img width="749" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG83QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6442f0269281b73665a25d097c63c0de1912c9d6/image.png" alt="image.png" />

**Business Context**
None

**Technical**
- [x] The list of applications to report a change must not include archived applications. Implement if not already there.
- [x] Add the validation in scholastic standing form.io to validate the date entered to be within study start date and study end date and also not a future date.
- [x] Ensure that the dry run submission happens safely loading from server variables required to complete the validations.
- [x] Ensure that on submission of scholastic standing change, validation for archived application is happening.
- [x] E2E Tests for get scholastic standing list API and submit scholastic standing covering necessary scenarios.

**Comment by Joshua-Lakusta** [comment]
For lather. Hoping to discuss the validation of UC weeks as well and have them have a top end limit of offering weeks for the same reason as the other two changes.
