### ISSUE TITLE
Dev Analysis: Program Year Limits in Assessment

### ISSUE THREAD

**Issue by Joshua-Lakusta** [bcgov/SIMS#2571]
**Description of Task**: 
- Conduct preliminary analysis of the context below. Implementation tickets will be created following the analysis

**Context:**
Eventually, the complete solution will be required to support Program Year rules. This includes referencing historical award info (from SIMS and SFAS); handling the PY limit maximums in each assessment; and introducing sequential re-assessments. 

This ticket will analyze how the full solution can be implemented. 

Based on this analysis, workload estimates can be evaluated, and possible simplification of business requirements can be decided on. 

The full solution must consider:
- Where to collect / save all the appropriate workflow data (i.e. previous award amounts from within that ProgramYear)
- How to save / export all SIMS award amounts to be sent in the new SIMS to SFAS data bridge 
- Where to apply each ProgramYear limit within the workflow (Buiz will provide the full list of PY limit rules relevant to PT release, which relate to: CSGD, CSGP, SBSD, BCAG-PT)
- How to build sequential re-assessments which allow for a change in Application A to automatically re-assess in-progress Applications B and C 
- Whether other processes currently handled at eCert stage (Overawards, Tuition Remittance, etc..) must be moved into the assessment stage as well (Buiz preference is for these to stay at eCert for now, if possible, to minimize Development time for MVP)
- Additional sample demonstration of these rules can be found here: <img width="1214" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzE1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5c5b60eb64d4add3e1df30c67bbda9897ea9de1b/image.png" alt="image.png" />

**Acceptance Criteria**
- [x] Analysis on running assessment sequentially (as opposed to parallel) and changes required
- [x] Impact analysis 
- [x] Create solution options and ticket recommendations

**Comment by dheepak-aot** [comment]
# Part 2 Technical solution of the above described business requirement

To achieve the above business requirement, here is the most suitable technical approach which came out of the analysis ticket.
Here are the high level blocks of the technical requirement.

 ## Input total value

**Comment by dheepak-aot** [comment]
Creation and order of implementation tickets

 - #2664 Execute assessment calculations in sequence
 - #2665 Identify related applications to create reassessments on application change
 - #2672 Input PY Award consumed and Create related application reassessment on reassessment
 - #2677
