### ISSUE TITLE
PY 24/25 Award Configuration Updates - PT

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#2572]
**User Story**
As part of a new program year, the values used in the assessment need to be updated to include 2024-2025 values.

**Acceptance Criteria**
- [x] Update the parttime-assessment-decisions.dmn file with the records on the following file: [DEVS>BPM Workflows>parttime-assessment-decisions.dmn](https://bcgov.sharepoint.com/:u:/r/teams/03177/Shared%20Documents/DEVS/BPM%20Workflows/parttime-assessment-decisions.dmn?csf=1&web=1&e=havrbe)

**Technical**
- [x] Ensure that PY 2021-2022 is removed from the file (if not yet removed).
- [x] Replace the entire file in the Git repository.
- [x] Ensure that E2E tests are running (ensure DMN is deployed locally before executing the test).

**Comment by HRAGANBC** [comment]
Closing as this is on radar and reflected on board elsewhere

**Comment by michesmith** [comment]
Pending Final Values

**Comment by CarlyCotton** [comment]
Just commenting to confirm I have removed the 2021-2022 from the dmn table linked in the ticket.
