### ISSUE TITLE
Confirm there is nothing critical in the 'Main Timeline' in test that would be detrimental to the part-time Release 

### ISSUE THREAD

**Issue by michesmith** [bcgov/SIMS#2578]
Other than submitting FT Application ) a ticket already exists for this)

**Comment by HRAGANBC** [comment]
@michesmith Do you remember any additional context here? Basically wondering whether TEST as it stands today would be acceptable if launched into PROD?

If so, I think this is now replaced by the more recent Dev-supported exercise where they mapped out the 'release activities', for example reviewing how often certain processes are run, the intended email inboxes for particular notification emails, etc... 

Suggest closing this one and removing from PT?

**Comment by HRAGANBC** [comment]
Closing as it's been captured by the Dev-produced release planning exercise
