### ISSUE TITLE
Data Inventory report analysis - next step (SPRINT PRIORITY)

### ISSUE THREAD

**Issue by andrepestana-aot** [bcgov/SIMS#2580]
### Considerations:
- The query as it is now is filtering applications that are not in `Overwritten` status. 
- All the column names should be revised by the business to be clear for the user. E.g.: 
  - parent1 x parent2 should have a prefix or something in the title to distinct parent1 from parent2. 
  - Titles must have max of 63 characters. Some titles were truncated.
- Change sub selects in the `select` statement of the query to be inner join when possible.
- Titles cannot contain commas if the ticket #2589 is not closed.
- There was a really poor performance on DEV env that should be investigated and improved.

### Acceptance Criteria
- [x] Always return the raw data without conversion 
- [x] Change report to bring the whole history for the applications (all applications records);
- [x] Revise the columns titles with business;
- [x] Change sub selects in the `select` statement of the query to be inner join when possible;
- [x] Change the query to return overwritten applications. Analyze the impact for the columns and change it to bring the whole history for the applications (all applications records). See [comment](https://github.com/bcgov/SIMS/pull/2579#discussion_r1424607276).
- [x] If the ticket #2589 is not closed, revise with business the the column titles with commas;
- [x] Work on the "Missing Columns in previous analysis" described below;
- [ ] (NICE TO HAVE) Investigate and fix the performance on DEV (maybe after the changes in this ticket it won't be an issue). If not achievable create another ticket with outstanding columns 

### Missing Columns in previous analysis

|  Column name |  Description  |  Maybe this |
|---|---|---|
| Youth in Care beyond age 19 Flag | There's already a "Youth in Care Flag" column. What's the difference between them?  | maybe one of these? <img width="1402" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODVVQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--769345b583314f18a5c5ca3f02f0888d768ad9b7/image.png" alt="image.png" /> | 
| Child/Spousal Support amount | Couldn't find. |  Probably this <img width="1072" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUpVQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--519719854d93d648ff64306f86576e95dac36b45/image.png" alt="image.png" /> |
| Living in parent house and paying living expenses amount  | Couldn't find. |   
| Parental net annual income (calculated value) |  Couldn't find. |  Probably from here: <img width="167" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU5VQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e30b6028eb07a3c38682abacf90b65cb65a69d35/image.png" alt="image.png" /> |
| Parental value of assets  |  Couldn't find. | 
| Total taxable income (Line 23600) (calculated value) |  Couldn't find. | 
| Parental other dependants – age of dependant (as applicable) |  Couldn't find. |  Maybe from here: <img width="806" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVJVQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0457173e1c316bde0e63d940a2277b7f90057cdf/image.png" alt="image.png" /> <img width="942" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWxVQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--569cd260c952ff7a10ee08912878a9dca2dd4d38/image.png" alt="image.png" /> |
| Parental other dependants – attending high school (Yes/No – as applicable) |  Couldn't find. | 
| Parental other dependants – claimed for disability (Yes/No - as applicable) |  Couldn't find. | 
| Number of Dependent Children (0-11 years of age and Disabled 12 years of age or older) | It needs to have a inner sql to go through the dependants and select with those conditions. |
| Number of Dependent Children (12 years of age or older who are NOT disabled) and Other Dependent Relatives | It needs to have a inner sql to go through the dependants and select with those conditions. |
| Alphabetical Institution Listing | Didn't look for it as it's nice to have. |
|Institution Location (BC Public, BC Private, Other Province, USA, International) | Didn't look for it as it's nice to have. |
| Institution Type (Flight, Medical, Technical Institute, etc) | Didn't look for it as it's nice to have. |
| Institution Contact List (email, phone) | Didn't understand what should be displayed. Wouldn't it be better to have 2 columns |
| De-designation (list of students to be trained out) | Couldn't find. | 
| Credit or Hours Based | Didn't look for it as it's nice to have. |
| Program Regulatory Body | Didn't look for it as it's nice to have. | <img width="997" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1pVQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ad8f45f2fd2a04236e82d96a0baf48cff357ac92/image.png" alt="image.png" /> |
| Entrance Requirements | Didn't look for it as it's nice to have. |
| Program ESL Content Percentage | Didn't look for it as it's nice to have. |
| Program offered jointly/ in partnership (Yes/No) | Didn't look for it as it's nice to have. |
| Program Work Integrated Learning (WIL) Component (Yes/No) | Didn't look for it as it's nice to have. |
| WIL regulatory approval (Yes/No – as applicable) | Didn't look for it as it's nice to have. |
| Program Field Trip / Travel Component (Yes/No) | Didn't look for it as it's nice to have. |
|Program international exchange component (Yes/No) | Didn't look for it as it's nice to have. |
| Program was pending but then approved | Didn't look for it as it's nice to have. |
| Offering course load percentage | Couldn't find. | 
| Offering WIL component (Yes/No) | Couldn't find. | 
| Study Break Start Date(s) | Multiple values. How to display it? | 
| Study Break End Date(s) | Multiple values. How to display it? |
| Total Offering Days | Couldn't find. Should we calculate it? | 
| Total Funded Weeks | Couldn't find. Should we calculate it? | 
| Total Funded Study Period Days | Couldn't find. Should we calculate it? | 
| Total Unfunded Study Period Days | Couldn't find. Should we calculate it? | 
| Offering availability | Couldn't find. | 
| Offering pending flag | Couldn't find. | 
| Early completion date | Couldn't find. | 
| Total number of unsuccessful weeks for that student | Couldn't find. | 
| Reason for Fixed Student Contribution Exemption: Indigenous | Didn't check. |
| Reason for Fixed Student Contribution Exemption: Permanent Disability | Didn't check. |
| Reason for Fixed Student Contribution Exemption: Dependants | Didn't check. |
| Reason for Fixed Student Contribution Exemption: Current or Former Crown Ward | Didn't check. |
| Reason for Fixed Rate Spousal Contribution Exemption: Student | Didn't check. |
| Reason for Fixed Rate Spousal Contribution Exemption: Recipient of Employment Insurance | Didn't check. |
| Reason for Fixed Rate Spousal Contribution Exemption: Recipient of Social Assistance | Didn't check. |
| Reason for Fixed Rate Spousal Contribution Exemption: Recipient of federal or provincial disability benefits | Didn't check. |
| Fixed student contribution review flag | Didn't check. |
| Parental contribution review flag | Didn't check. |
| Fixed spousal contribution review flag | Didn't check. |
| Version Number | Needs to be queried/calculated. Didn't check how to do it. |
| CSL Loan authorization date | Nice to have. Didn't check it. |
| Reason for Single Independant Status | Nice to have. Didn't check it. |
| Number of edits to income fields | This one need an elaborated inner select. |
| Tuition | Couldn't find. | 
| Mandatory fees | Couldn't find. | 
| Other allowable costs | Couldn't find. | 
| Total assessed costs | Couldn't find. | 
| Contribution from targetted funds | Didn't check. | 
| Contribution from scholarships/bursaries/awards | Didn't check. |
| Student fixed contribution | Didn't check. |
| Parental income contribution | Didn't check. |
| Parental asset contribution | Didn't check. |
| Parental voluntary contribution | Didn't check. |
| Parent contribution | Didn't check. |
| Spouse contribution | Didn't check. |
| Other resources  | Didn't check. |
| Total assessed resources | Didn't check. |
| Total assessed need | Didn't check. |
| Total assistance | Didn't check. |
| Unmet need | Didn't check. |
| CSL FT assessed amount | Didn't check. |
| CSL PT assessed amount | Didn't check. |
| BCSL FT assessed amount | Didn't check. |
| CSL FT assessed amount | Didn't check. |
| CSGD assessed amount | Didn't check. |
| CSGP assessed amount | Didn't check. |
| CSGF assessed amount | Didn't check. |
| CSGT assessed amount | Didn't check. |
| BCAG assessed amount | Didn't check. |
| BGPD assessed amount | Didn't check. |
| SBSD assessed amount | Didn't check. |
| Confirmation of Enrolment Approved / Declined? | Didn't check. |
| Date of Confirmation Enrollment Decision | Didn't check. |
| CSL FT disbursed amount | Didn't check. |
| CSL PT disbursed amount | Didn't check. |
| BCSL FT disbursed amount | Didn't check. |
| CSL FT disbursed amount | Didn't check. |
| CSGD disbursed amount | Didn't check. |
| CSGP disbursed amount | Didn't check. |
| CSGF disbursed amount | Didn't check. |
| CSGT disbursed amount | Didn't check. |
| BCAG disbursed amount | Didn't check. |
| BGPD disbursed amount | Didn't check. |
| SBSD disbursed amount | Didn't check. |
| Date of 1st Disbursement | Didn't check. |
| Date of 2nd Disbursement | Didn't check. |

**Comment by michesmith** [comment]
Connect to ticket #2598

**Comment by michesmith** [comment]
@andrepestana-aot- can you please create a first draft Acceptance Criteria for grooming please?

**Comment by michesmith** [comment]
@HRAGANBC @CarlyCotton Is this still a priority for Part-Time Release?

**Comment by HRAGANBC** [comment]
@michesmith @CarlyCotton 

Yes, this is still a priority for PT release.

The ACs are already good from my perspective, but entail some Dev+Biz sync up to work through them. For e.g. it's not clear to me why many of the fields 'weren't found' in the initial analysis given they're questions directly from the App.

Can I suggest we keep this ticket as-is for now, but schedule some time with Andre + Hugh +  Carly + SignoriORDheepak. Depending on the blocker, it might be further analysis that we can help with by mapping Camunda variable names to the missing field, or it might take dedicated Dev time to investigate further.
