### ISSUE TITLE
Child Care Costs Calculations - PT

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#2582]
**Actual Behaviour**
Childcare costs are split in half with the student is married and their partner is also in study.
<img width="575" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUJTQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--266a3e9c4f8b3d9b860ed66bb31ddf6d15369077/image.png" alt="image.png" />

**Expected Behaviour**
No reduction in child care costs in the part time assessment based on partner or marital status.

**Acceptance Criteria**

In _parttime-assessment-*.bpmn_
- [ ] Remove calculatedDataTotalChildCareCost
- [ ] Update calculatedDataTotalAssessedNeed to reflect the change from calculatedDataTotalChildCareCost to calculatedDataChildCareCost

<img width="576" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWRTQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6c2c1f3d2dfa3b1f38a87e042da021e45bd4dc9f/image.png" alt="image.png" />

**Comment by dheepak-aot** [comment]
NOA page is using `calculatedDataChildCareCost` and no changes required for this ticket on NOA page.

<img width="777" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnlTQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ed4b41f5e245c305128b0c8ed1e09703177af5a7/image.png" alt="image.png" />

<img width="977" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjJTQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dbf54cc7c2120d5d5f4cae7d0a124f27768f157f/image.png" alt="image.png" />
