### ISSUE TITLE
FT Request a Change - Financial Information (Students)

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2585]
**User Story**
As a Full-Time Student, I want to change my financial information on my Request to Change Form, so that I can ensure the correct financial information is provided for a reassessment.

**Description of Task:**
Allow Full-Time students to change their financial information 

**Context:**
- See #266 for context about general Request a Change Process
- The ministry user view of this is in a separate ticket #2583
- Part-Time equivalent forms are available here: #2471 , #2549

**Acceptance Criteria**
- [ ] Introduce new 'form title' called 'Financial Information (Full-Time Applications)'
- [ ] The form should display a message which reads "Complete only the forms which have changed since your initial application was submitted"
- The form should contain the following fields/questions:
- "My total income in 2023 was:" (add free-input numeric field below)
- "What are your daycare costs that you incur for your children age 11 years of under?" (add free-input numeric field below)
- What are the total unsubsidized daycare costs during class hours for disabled/infirm dependents 12 years of age or older? (add free-input numeric field below)
- Enter the child support and/or spousal support amount that you will pay during your study period (add free-input numeric field below)
- Enter the amount that you will receive from merit-based scholarships or need-based bursaries (including provincial government scholarships) during your study period" (add free-input numeric field below)
- Enter the estimated amount that your will receive from your parent(s)/step-parent/sponsor/legal guardian to support your educational costs. (add free-input numeric field below) 
- Enter the amount of government funding (e.g. E.I. training allowance, social assistance payment intended to cover education-related costs) that you will receive during your study period" (add free-input numeric field below) 
- Enter the amount of non-government (private sector) funding that you will receive during your study period" (add free-input numeric field below) 
- If you must relocate to a different city to attend school and will return home at least once during your study period, what is the cost of one return trip home?" (add free-input numeric field below)

**Comment by Joshua-Lakusta** [comment]
Closing as this is incorporated into the change request revamp.
