### ISSUE TITLE
Review Form.io long variable names

### ISSUE THREAD

**Issue by andrepestana-aot** [bcgov/SIMS#2587]
There are auto-generated form.io variables in the forms which are excessively long like: `totalUnsubsidizedDayCareCostsDuringClassHoursForTheProposedStudyPeriodForDisabledInfirmedDependents12YearsOfAgeAndOlderPanel` that should be renamed to something smaller.

**Acceptance Criteria**
- [ ] Identify and rename long var names in the forms. When in doubt if it is too big check with devs.
  - [ ] Student Application
  - [ ] Supporting Users
- [ ] Check all the code to rename those variables and check Camunda impacts.
- [ ] Rename variables federalAwardBCAGAmount to provincialAwardBCAGAmount in parttime-assessment-2021-2022.bpmn, parttime-assessment-2022-2023.bpmn, parttime-assessment-2023-2024.bpmn (BCAG is a provincial grant).
- [ ] Remove obsolete variables "isavalidDependant" and "validDependent (#2917)
- [ ] Analyse impact and communicate to business to avoid impacting tests.
- [ ] No migrations needed and the expectation is that applications before these changes will not behave nicely, may be broken, and should no longer be used.

**Comment by andrewsignori-aot** [comment]
@ninosamson @sslaws @michesmith can we bring this back from the Icebox?
Changing this after the applications are in PROD can be more challenging.
The main issue here is that non-properly named inputs in form.io are just auto-generated and they will be saved to DB as in the example in the ticket description.

**Comment by ninosamson** [comment]
Yeah, I'll bring into the Lather and we can discuss.

**Comment by dheepak-aot** [comment]
## Issues that has been noticed to be impacted in DATA INVENTORY REPORT

- The variable `validDependent` has been removed from student application form but it is still used in data inventory report.(This value to be used must come from workflow data)
- The student application variable `pleaseProvideAnEstimationOfYourParentsIncome` has been updated to `studentParentsTotalIncome` and the same needs to be adjusted in data inventory report.
- The data inventory report SQL is using the key of a form panel which is `totalUnsubsidizedDayCareCostsDuringClassHoursForTheProposedStudyPeriodForDisabledInfirmedDependents12YearsOfAgeAndOlderPanel` insted of a form input object. Hence the SQL of data inventory report needs to be updated.

**Comment by dheepak-aot** [comment]
Speadsheet containing all variable changes[Long_Variable_names.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL28rQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--65dc719074691ba1d04691a8ff4312a8f78d11c6/Long_Variable_names.xlsx)
