### ISSUE TITLE
Use a CSV parser library for the report service

### ISSUE THREAD

**Issue by andrepestana-aot** [bcgov/SIMS#2589]
Analyse the possibility of adding a CSV parser library and implement it to our report service:

https://github.com/bcgov/SIMS/blob/5854e3d9951f5fdf99d7cbc90f72c03dc285c07e/sources/packages/backend/libs/services/src/report/report.service.ts#L96-L115

One of the problems to be resolved is to allow titles and values to contain commas. That can be solved double quoting the csv values.

**Acceptance Criteria**
- [x] Check the options for CSV parser libraries available and pick one with the team; 
- [x] Check the existing library for the bulk upload. 
- [x] Add the parser to the report service;
- [x] Test the report creating titles and values with commas to test it;

**Comment by michesmith** [comment]
@andrepestana-aot- can you please create a first draft Acceptance Criteria for grooming please?

**Comment by andrewsignori-aot** [comment]
### Demo Evidences

Extracted a report from DEV using the new lib and a user with quotes and a comma in the body.
<img width="776" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNm1hQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6677e4994aa17177134e3e33cebc8acfe595f43b/image.png" alt="image.png" />

<img width="1667" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnFhQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c3a36f9fdb8f95c4bfcc02cfe9b75c63e33fa599/image.png" alt="image.png" />
