### ISSUE TITLE
Content - Add Banner on Login Page Advising Full-Time Students to use SFAS 

### ISSUE THREAD

**Issue by michesmith** [bcgov/SIMS#2590]
We need to communicate to students that Part-Time is within SIMS, and Full-Time is within SFAS

This can be accomplished through combination of:
- Banner message on SABC website advising them of which system to use (James Harada Down responsible for this - not devs)
- Banner message on SIMS login page and SIMS landing page notifying them that SIMS is for Part-Time only

**Comment by HRAGANBC** [comment]
@michesmith I think James confirmed that this work is indeed a blocker to launch, but does NOT implicate Dev resources in any way. I.e. its being handled between James and IMB folk, and therefore can be included in Yash's Project Plan but doesnt necessarily need to be reflected in ZenHub . 

If this is just placeholder for us not to forget about - fine, jsut want to make sure you didn't take a different impressio from the meeting this AM

**Comment by ninosamson** [comment]
Closing as obsolete and replaced by System Announcement tickets.
