### ISSUE TITLE
Investigate multiple pod restarts for queue-consumers on dev environment

### ISSUE THREAD

**Issue by cditcher** [bcgov/SIMS#2591]
**Describe the task**
Investigate the cause of dev-queue-consumers multiple pod restarts. 

**Additional Context**
It appears to be an OOMKill. Check root cause of out of memory issues. Check resource settings, etc.

**Acceptance Criteria**
- [ ] stable deployment of dev-queue-consumers pods without persistent restarts

<img width="769" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFZoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c655d4b54fea5d20ae170988d43f349cb6e576c2/image.png" alt="image.png" />

**Comment by ninosamson** [comment]
Closing this ticket as obsolete and removing estimate.
