### ISSUE TITLE
Display Lifetime Tally of Unsuccessful Weeks for All Users 

### ISSUE THREAD

**Issue by michesmith** [bcgov/SIMS#2594]
**Description:**
Display the lifetime tally of Unsuccessful Completion for each student on the Institution Account (Restrictions Section) and the Student Account (Account Activity Section)

Acceptance Criteria:
- [ ] Calculate student's lifetime tally of Unsuccessful weeks by summing:
- Unsuccessful weeks # imported through SFAS data bridge
- Summing all individual reports of Unsuccessful completi-on reported through SIMS scholastic standing, _regardless_ of which school reported them
- Note: The number of UC weeks does **not** matter whether it was Part-Time or Full-Time
- [ ] Incorporate new UX display of student lifetime tally of unsuccessful weeks in public Institution view of student details on the Restrictions Page (see photo below)
- [ ] Incorporate new UX display of student lifetime tally of unsuccessful weeks in Student Account Activity Page (see photo below)
- [ ] Add e2e tests

Student Account Activity Page
<img width="865" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDF1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d3a2230d2f6f31b87a112f0ec12a854893988c19/image.png" alt="image.png" />

**Institution Restrictions View**
<img width="1094" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGh1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3699bcee04dee34e050a49aa913e0ff580c4524a/image.png" alt="image.png" />

**Comment by andrewsignori-aot** [comment]
@Joshua-Lakusta the ticket was not closed to confirm that we will also be considering SFAS scenarios like the one here for the testing scopes.
@ninosamson FYI
