### ISSUE TITLE
NOA View - Content Update

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#2610]
**User Story**
As a _student_ I want to be able to see a breakdown of my _assessed costs_ when viewing my assessment and more information about how the amounts were calculated.

**Current State**
- There is a list of "This includes" which doesn't all apply to part-time students and will need to be updated:
<img width="616" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3ZWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cd7c0e9801e9a39cb7f1dbddcb4ffc73574df653/image.png" alt="image.png" />
- Miscellaneous costs show as (Not eligible) when they are eligible and have an amount contributing to the total assessed cost.
- Total Academic expenses shows as $0 when there is a value.
- Total Assessed costs shows as $0 when there is a value.
<img width="1106" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkYxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d9117adde5de1c8e7439a3b1e534065d56757153/image.png" alt="image.png" />

**Expected**
- The values shown should reflect the values used in the assessment.
- The additional information on the page should be accurate to what is used in the assessment.

**Acceptance Criteria**
- [x] Update the wording on the PT & FT NOA display to the follow:

> **This includes:**
> - Income of your partner and/or parent(s), if applicable
> - Scholarships and bursaries reported (Full-time students only)
> - Voluntary or targeted contributions reported (Full-time students only)
> - Assets reported by parents, if applicable

The remaining AC's are exclusively for Part-Time
- [x] Miscellaneous costs should show the value of calculatedDataMiscellaneousAllowance from Camunda.
- [x] New line added "Mandatory Fees" in the "Assessed Costs Breakdown" calculatedDataMandatoryFees 
- [x] Total Academic expenses should show the value of calculatedDataActualTuitionCosts + calculatedDataMandatoryFees + calculatedDataProgramRelatedCosts + calculatedDataTransportationAllownace (Please check current in progress ticket re transportation allowance and the new variable name) + calculatedDataMiscellaneousAllowance 
- [x] Total Assessed Costs should show the value of calculatedDataTotalAssessedNeed

**Comment by CarlyCotton** [comment]
@HRAGANBC @Joshua-Lakusta 
The "This includes" on the NOA page includes things that don't factor in at all for the PT family income value. The only thing that is included is the "Income of your partner (if applicable)". Do we want to scratch this or just include "Income of your partner (if applicable)" as the lone bullet point?
<img width="545" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2wxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cad080a58a217138ad1adbcd49e78cc39dbbb514/image.png" alt="image.png" />

**Comment by HRAGANBC** [comment]
@CarlyCotton To your question above - I think we want to keep the NoA the same form for PT and FT if possible. That would mean noting wherever particular inclusions are specific to only Full-Time. 

So the list could read: 
"This includes:
- Income of your partner, if applicable
- Income of your parent(s), if applicable *Full-Time students only
- Scholarships and bursaries reported *Full-Time students only
- etc...


P.s. There's ACs related to NOA content on here, should we include the recent issue uncovered where the NoA isn't correctly showing the student's MSFAA number?
