### ISSUE TITLE
PT Award Eligibility - BCAG

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#2614]
**User Story**
As a part-time _student_ I am eligible for BCAG if attending a BC Public institution, have assessed need, a family income below the threshold and am in an eligible program credential type.
<img width="556" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjUvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--78e505ca696acced41089154f6182d815414bf89/image.png" alt="image.png" />

**Current Behaviour**
The award eligibility check correct checks for institution type, assessed need and family income thresholds. It is checking for the incorrect program credential types.

```
if institutionType = "BC Public"
  and (calculatedDataTotalAssessedNeed >= 1)
  and (calculatedDataTotalFamilyIncome < dmnPartTimeAwardFamilySizeVariables.limitAwardBCAGThresholdIncome)
  and (programCredentialType = "undergraduateDegree"
       or programCredentialType = "graduateCertificate"
       or programCredentialType = "graduateDiploma"
       or programCredentialType = "qualifyingStudies")
then true 
else false
```

**Expected Behaviour**
The valid credential types to be eligible for PT BCAG are undergraduate degree, undergraduate diploma and undergraduate certificate.

```
if institutionType = "BC Public"
  and (calculatedDataTotalAssessedNeed >= 1)
  and (calculatedDataTotalFamilyIncome < dmnPartTimeAwardFamilySizeVariables.limitAwardBCAGThresholdIncome)
  and (programCredentialType = "undergraduateCertificate"
       or programCredentialType = "undergraduateDiploma"
       or programCredentialType = "undergraduateDegree"
)
then true 
else false
```

**Acceptance Criteria**
- [x] Adjust E2E tests
- [x] Update **awardEligibilityBCAG** in parttime assessments for all program years to the following:
```
if institutionType = "BC Public"
  and (calculatedDataTotalAssessedNeed >= 1)
  and (calculatedDataTotalFamilyIncome < dmnPartTimeAwardFamilySizeVariables.limitAwardBCAGThresholdIncome)
  and (programCredentialType = "undergraduateCertificate"
       or programCredentialType = "undergraduateDiploma"
       or programCredentialType = "undergraduateDegree")
then true 
else false
```

**Comment by CarlyCotton** [comment]
@HRAGANBC - I've confirmed this with policy via email.

**Comment by HRAGANBC** [comment]
@CarlyCotton thanks - moving to grooming pipeline

**Comment by dheepak-aot** [comment]
PY limit deductions(dmnPartTimeAwardAllowableLimits) are not part of this ticket as per grooming discussion. As PY limit deductions are going to be handled in separate ticket.
