### ISSUE TITLE
Award Configurations - PT CSG-DEP (Award)

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#2618]
**User Story**
As a _student_, the amount of CSG-DEP I receive should follow the policy and reflect the correct amount if I'm between the income cap and the income threshold.

**Current Behaviour**
CSGD Award Amount (federalAwardCSGDAmount) is calculated as the max weekly limit if the family income is less than the gross income for the max grant (income cap) based on family size or the larger of weekly max (hardcoded) or the sloped weekly amount (which will always be less than the max weekly). Beyond that it does NOT account for the number of weeks of study.
<img width="292" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2FJQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bca7a1c68eb8c58868f8b8790788e7b13820a5f2/image.png" alt="image.png" />
```
  if (calculatedDataTotalFamilyIncome <= dmnPartTimeAwardFamilySizeVariables.limitAwardCSGDIncomeCap)
then dmnPartTimeAwardAllowableLimits.limitAwardCSGD3OrMoreChildAmount
else
  max(dmnPartTimeAwardAllowableLimits.limitAwardCSGD3OrMoreChildAmount - ((calculatedDataTotalFamilyIncome - dmnPartTimeAwardFamilySizeVariables.limitAwardCSGDIncomeCap) * dmnPartTimeAwardFamilySizeVariables.limitAwardCSGD3OrMoreChildSlope),
     80
  )
```

**Expected Behaviour**
CSGD should calculate the weekly amount as follows: 
- if income is below the income cap for family size, use the maximum weekly amount
- if income is above, use the maximum of (weekly limit - (family income - income cap)*slope) or 0

CSGD should calculate the total award using that weekly amount:
- if that weekly amount * offering weeks is less than the weekly limit, use weekly limit otherwise use weekly amount * offering weeks (rounded to nearest full dollar)
- use the lesser of the above amount or program year limit

```
min(
	round(
		max(
			if (calculatedDataTotalFamilyIncome <= dmnPartTimeAwardFamilySizeVariables.limitAwardCSGDIncomeCap)
			then 
				dmnPartTimeAwardAllowableLimits.limitAwardCSGD3OrMoreChildAmount
			else
				max(dmnPartTimeAwardAllowableLimits.limitAwardCSGD3OrMoreChildAmount - ((calculatedDataTotalFamilyIncome - dmnPartTimeAwardFamilySizeVariables.limitAwardCSGDIncomeCap) * dmnPartTimeAwardFamilySizeVariables.limitAwardCSGD3OrMoreChildSlope),
			     0
			) 
			* offeringWeeks,
			dmnPartTimeAwardAllowableLimits.limitAwardCSGD3OrMoreChildAmount
		)
	),
		dmnPartTimeAwardAllowableLimits.limitAwardCSGDAmount
)
```
<img width="743" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0tJQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3c438b74b4742d3fe3fb20b2bf4f1529ef7f97f3/image.png" alt="image.png" />

**Additional Context**
[MASSvsSIMS_AssessmentComparison.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0NKQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8466c026815eab0035a0e185594e8fe2631c39cb/MASSvsSIMS_AssessmentComparison.xlsx)

**Acceptance Criteria**
- [x] Update federalAwardCSGDAmount calculation for the 3 or More Dependant stream based on above calculation
- [x] Update federalAwardCSGDAmount calculation for the 2 or less Dependant stream based on above calculation, substituting limitAwardCSGD2OrLessChildAmount anywhere there is limitAwardCSGD3OrMoreChildAmount, as well as limitAwardCSGD2OrLessChildSlope for limitAwardCSGD3OrMoreChildSlope.
- [x] Ignore rounding in this ticket; it will be analyzed and addressed in a future ticket.

**Comment by dheepak-aot** [comment]
PY limit deductions(dmnPartTimeAwardAllowableLimits) are not part of this ticket as per grooming discussion. As PY limit deductions are going to be handled in separate ticket.
