### ISSUE TITLE
DUPLICATE Award Configurations - PT CSG-DEP (Award Net)

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#2619]
**User Story**
As a _student_, the amount of CSG-DEP I receive should follow the policy and reflect the correct amount based on my remaining need and CSG-DEP disbursed to me in this Program Year.

**Current Behaviour**
CSGD Award Net Amount (federalAwardNetCSGDAmount), if eligible, is calculated as the federalAwardCSGDAmount * offering weeks if remaining need is greater than the weekly amount calculated in federalAwardCSGDAmount (weekly). If remaining need is <= federalAwardCSGDAmount (weekly) then it takes the remaining need and calculates it by offering weeks.
<img width="292" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2FJQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bca7a1c68eb8c58868f8b8790788e7b13820a5f2/image.png" alt="image.png" />
```
if (awardEligibilityCSGD = true)
then
  if (calculatedDataTotalRemainingNeed2 > federalAwardCSGDAmount)
  then federalAwardCSGDAmount * offeringWeeks
  else calculatedDataTotalRemainingNeed2 * offeringWeeks
else
0
```

**Expected Behaviour**
CSGD should calculate the net amount as follows: 
if ineligible
- return 0

if eligible and remaining need <= 0
- return 0

if eligible and remaining need > 0, calculate the lesser of:
- federalAwardCSGDAmount, or
- dmnPartTimeAwardAllowableLimits.limitAwardCSGDAmount minus any CSGD awarded in the current program year

<img width="568" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3VJQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--72ff5e27472a400168e0367f2f9fac8a368c1170/image.png" alt="image.png" />

**Additional Context**
[MASSvsSIMS_AssessmentComparison.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0NKQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8466c026815eab0035a0e185594e8fe2631c39cb/MASSvsSIMS_AssessmentComparison.xlsx)

**Acceptance Criteria**
- [ ] Create new variable for cumulative total of CSGD awarded for each student per program year
- [ ] Update calculation in federalAwardNetCSGDAmount under both the 2 or less and 3 or more streams
- [ ] Ignore program year maximum validation for now. It will be addressed in a future ticket.

**Comment by dheepak-aot** [comment]
PY limit deductions(dmnPartTimeAwardAllowableLimits) are not part of this ticket as per grooming discussion. As PY limit deductions are going to be handled in separate ticket.

**Comment by sslaws** [comment]
Pulled out and back to Backlog until we officially remove it.

**Comment by ninosamson** [comment]
Closing this ticket as duplicate and removing points.
