### ISSUE TITLE
Notice of Assessment Updates

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2621]
## **Description**
Make several distinct changes to the content wording reflected on a student's NOA to ensure clarity.

## **Acceptance Criteria:**
- [x] Update NOA page for students to align with this new arrangement [FIGMA](https://www.figma.com/design/8nlST7ygNuANpxfp6uw9BT/SIMS-Draft-Playground?node-id=14717-33347&t=h1zSX79fuJlJ2WrT-1)
- [x] All currency should be shown in $##,###.00 format
- [x] There might be some alignment/padding issues in the Figma example, please keep our standard spacing/padding/etc. and exercise good judgement
 
### Section 1 - Notice of Assessment
- [x] Sub header:
    >Name: ((studentName)) | Application Number: ((appNumber)) | Study Dates: ((startDate)) - ((endDate))
- [x] The content with "Please note" is static and will be reviewed under the FT content review

### Section 2A - Funding (calculated)
- [x] This section can be used for PT & FT.

### Section 2B - Funding (breakdowns)
- [x] Assessment costs:
    - [x]  **PT:** Update Categories as shown in FIGMA (including total line)
    - [x] **FT:** Leave as-is

- [x] Award breakdown
    - [x] **PT & FT:** Update to show "Disbursement 1" and only show "Disbursement 2" if there is a second disbursement. 
    - [x] **PT:** Re-order them, update Loan/grant names and tooltips as shown in FIGMA
    - [x] **FT:** Leave as-is

Two disbursements:
<img width="811" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1RoQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9bc064f637cb9748daecfbd7bdee329bb006aef0/image.png" alt="image.png" />
One disbursement:
<img width="817" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2poQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c997bad03bf821e108de3e68c16c5a2130330edf/image.png" alt="image.png" />

- [x] Tool tip content: 
    - [x]  Revise Canada Student Grant for Students with Disabilities tooltip:
    > "Please click [here](https://studentaidbc.ca/explore/grants-scholarships/canada-student-grant-students-disabilities) for more information about this grant.
    - [x]  Revise Canada Student Grant for Part-time Students tooltip:
    > "Please click [here](https://studentaidbc.ca/explore/grants-scholarships/canada-student-grant-part-time-studies) for more information about this grant."
     - [x]  Revise Canada Student Grant for Students with Dependants toolip
    > "Please click [here](https://studentaidbc.ca/explore/grants-scholarships/canada-student-grant-students-dependants) for more information about this grant."
    - [x]  Revise B.C. Access Grant for Part-time Studies tooltip:
    >  "Please click [here](https://studentaidbc.ca/explore/grants-scholarships/bc-access-grant-part-time) for more information about this grant."
     - [x] Remove Canada Student Loan for Part-time Students tooltip
     - [x]  Revise B.C. Supplemental Bursary for Students with Disabilities tooltip:
    >  "Please click [here](https://studentaidbc.ca/explore/grants-scholarships/bc-supplemental-bursary-students-disabilities) for more information about this grant."

### Section 2C - Funding (when)
- [x] Same functionality/content for **PT & FT**
- [x] Change date format shown to "MMMM DD, YYYY"
- [x] This will display dynamically depending on the number of disbursements

Two disbursements:

<img width="577" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenZ4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--39ea5d8c100a6e737aeb25d1026c80cf7b48ec74/image.png" alt="image.png" />

One disbursement: _use date formatting as shown in above screenshot_
<img width="753" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2JoQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8a5342849740bcc91fb5728df41db06ad6e0f289/image.png" alt="image.png" />

### Section 3 - MSFAA
- [x] This section contains dynamic content and can be the **same PT & FT**
- [x] Current MSFAA Patterns have default, cancelled and not-signed yet variations. Keep the associated checkmark/x symbol and supplemental text below the number. 
- [x] Update the bold headers for each to **DYNAMICALLY** include the intensity:
    - [x] Default: "Your Part-time MSFAA number:"
    - [x] Cancelled: "Your cancelled Part-time MSFAA number:"
    - [x] Not signed yet: "Your new Part-time MSFAA number:"
- [x] Keep the Ministry "Reissue" option in the Ministry view
<img width="931" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMURnQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f3881cbaa415c2a51c528dfb22b930751e6fd967/image.png" alt="image.png" />

### Section 4 - Next Steps
- [ ]  Duplicate "Cancel Application" and "Accept Assessment" and put buttons on bottom of the page per FIGMA
- [ ]  Change "Cancel Application" button to red on the top and bottom of page.

**Comment by michesmith** [comment]
@HRAGANBC can you please connect with Jeremy on this one. Astrid you can choose to edit this ticket or create a new one post convo

**Comment by HRAGANBC** [comment]
@JerPearson to recycle this ticket with his final suggestions for NoA revisiosn
