### ISSUE TITLE
Award Configurations - PT CSPT (Net)

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#2632]
**User Story**
As a _student_ who has previously received CSPT funding, I need to have my Net CSPT Award calculated based on policy for CSPT award.

<img width="198" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXFNQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3d9d19c84bed2de30ba38fcbc80182cda44af4c7/image.png" alt="image.png" />

**Current Behaviour**
If the student is eligible, the remaining need (after CSGP award was applied) is compared to the award amount. If the need is greater, we use the award amount calculated in _federalAwardCSPTAmount_. If the need is less than the award amount, we use the remaining need.
```
if (awardEligibilityCSPT = true)
then
	if (calculatedDataTotalRemainingNeed1 > federalAwardCSPTAmount)
	then federalAwardCSPTAmount
	else calculatedDataTotalRemainingNeed1
else
0
```

**Expected Behaviour**
If the student is eligible, we consider the remaining need (after CSGP award was applied), the remaining CSPT amount allowable for the PY, and the award amount calculated. The minimum amount that can be awarded is $100, if remaining need is less than 100 nothing will be awarded. We then return the lesser of remaining need or potential award (lesser of PY max award - amount of CSPT awarded in the current PY and the amount calculated in __federalAwardCSPTAmount__.

```
if (awardEligibilityCSPT = true && calculatedDataTotalRemainingNeed1 >= 100)
then
  min(
     calculatedDataTotalRemainingNeed1,
     min(dmnPartTimeAwardAllowableLimits.limitAwardCSPTAmount, federalAwardCSPTAmount)
  )
else
0
```

**Additional Context**
Example of side by side calc differences in excel (PT - CSPT): [MASSvsSIMS_AssessmentComparison.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWVNQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--950ec6b88a186d031b60a8059ff4c87e7bc30ab9/MASSvsSIMS_AssessmentComparison.xlsx)
<img width="1066" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTJNQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aad5f3e0001d8fa515139f0372df64a9f31fc1c6/image.png" alt="image.png" />
Additional step required to account for prior award in current PY on #2639

**Acceptance Criteria**
- [ ] Update the logic in federalAwardNetCSPTAmount

**Comment by dheepak-aot** [comment]
PY limit deductions(dmnPartTimeAwardAllowableLimits) are not part of this ticket as per grooming discussion. As PY limit deductions are going to be handled in separate ticket.
