### ISSUE TITLE
Child Care Cost Validation - PT

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#2633]
**User Story**
As a _student with dependants_, my costs for childcare should only be considered if I have valid dependants for these costs (Children under 12 and children 12+ with a disability). If I have 3 children over 12, in PS full time and tax=no, I am not eligible for childcare costs. If I have 3 children, 1x<11yo / 1x12+ in PS / 1x12+ disability, then I am eligible for childcare/daycare costs for 2 children. The age of my dependents should be determined as of the study start date, and not at the time of assessment. The age of my dependants is based on the _study period start date_. 

**Current Behaviour**
The application asks questions about child care costs that result in two variables (studentDataDaycareCosts11YearsOrUnder) and (studentDataDaycareCosts12YearsOrOver). 
The care cost amounts are not compared against the number of eligible dependants of each type (11 and under, 12+ with PD)
The validation that occurs prior to accepting these costs toward need is to limit it based on the maximum allowable childcare per week (dmnPartTimeProgramYearMaximums.limitWeeklyChildCare).

_calculatedDataTotalEligibleDependants_ includes dependants 0-18 years, 19-22 years with PS or Disability, and >22 if Disability based on todays date (not study start date). This is the right group for determining family size, but not for calculating child care eligible dependants.
```
calculatedDataTotalEligibleDependants =
if studentDataDependants = null then 0 else
  count(
studentDataDependants[
// 0-18 years of age: eligible.
date(item.dateOfBirth) >= (today() - duration("P18Y"))
// 19-22 years of age: post-sec must be Yes or Tax is Yes.
or (
  date(item.dateOfBirth) < (today() - duration("P18Y"))
  and date(item.dateOfBirth) >= (today() - duration("P22Y"))
  and (item.attendingPostSecondarySchool = "yes" or item.declaredOnTaxes = "yes")
)
// > 22 years: eligible if Tax is Yes.
or (
  date(item.dateOfBirth) < (today() - duration("P22Y"))
  and item.declaredOnTaxes = "yes"
)
]
  )
```

```
calculatedDataChildCareCost=
if 
  dmnPartTimeProgramYearMaximums.limitWeeklyChildCare * offeringWeeks < studentDataDaycareCosts11YearsOrUnder + studentDataDaycareCosts12YearsOrOver
then
  dmnPartTimeProgramYearMaximums.limitWeeklyChildCare * offeringWeeks
else
  studentDataDaycareCosts11YearsOrUnder + studentDataDaycareCosts12YearsOrOver
```

**Expected Behaviour**
When considering the age of dependants, it needs to be based on the study start date, not _today()_.
We need to calculate dependants that the student is eligible to claim child care expenses for (Dependants under 12, Dependants 12+ with Tax="Yes").
The child care costs need to consider that the weekly limit set by SABC is at 100% course load _per eligible child_ per week of study when comparing to the student submitted costs.
```
calculatedDataTotalEligibleDependants =
if studentDataDependants = null then 0 else
  count(
studentDataDependants[
// 0-18 years of age: eligible.
date(item.dateOfBirth) >= ("study start date" - duration("P18Y"))
// 19-22 years of age: post-sec must be Yes or Tax is Yes.
or (
  date(item.dateOfBirth) < ("study start date" - duration("P18Y"))
  and date(item.dateOfBirth) >= ("study start date" - duration("P22Y"))
  and (item.attendingPostSecondarySchool = "yes" or item.declaredOnTaxes = "yes")
)
// > 22 years: eligible if Tax is Yes.
or (
  date(item.dateOfBirth) < ("study start date"  - duration("P22Y"))
  and item.declaredOnTaxes = "yes"
)
]
  )
```

```
calculatedDataDependants11AndUnder =
if studentDataDependants = null then 0 else
  count(
studentDataDependants[
// 0-11 years of age: eligible.
date(item.dateOfBirth) >= ("study start date" - duration("P11Y"))
]
)
```

```
calculatedDataDependants12UpOnTaxes=
if studentDataDependants = null then 0 else
  count(
studentDataDependants[
// >= 12 years: eligible if Tax is Yes.
  date(item.dateOfBirth) < ("study start date" - duration("P11Y"))
  and item.declaredOnTaxes = "yes"]
)
```

```
calculatedDataChildCareCost=
if (calculatedDataDependants11AndUnder > 0 && calculatedDataDependants12UpOnTaxes > 0)
then studentDataDaycareCosts11YearsOrUnder + studentDataDaycareCosts12YearsOrOver
else if (calculatedDataDependants11AndUnder > 0)
then studentDataDaycareCosts11YearsOrUnder 
else if (calculatedDataDependants12YearsOrOver > 0)
then studentDataDaycareCosts12YearsOrOver
else
0
```

```
calculatedDataTotalChildCareCost=
if (offeringWeeks <= 17)
MIN(courseLoad * dmnPartTimeProgramYearMaximums.limitWeeklyChildCare * 17 * (calculatedDataDependants11AndUnder +calculatedDataDependants12UpOnTaxes), calculatedDataChildCareCost)
else if (offeringWeeks <= 34)
MIN(courseLoad * dmnPartTimeProgramYearMaximums.limitWeeklyChildCare * 34 * (calculatedDataDependants11AndUnder +calculatedDataDependants12UpOnTaxes), calculatedDataChildCareCost)
else 
MIN(courseLoad * dmnPartTimeProgramYearMaximums.limitWeeklyChildCare * 52 * (calculatedDataDependants11AndUnder +calculatedDataDependants12UpOnTaxes), calculatedDataChildCareCost)
```

**Additional Context**
Change needs to occur in both the "Single" and the "Married" flows:
<img width="662" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL211QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--927817f213720d71eab14599ab6134d0808c1d2d/image.png" alt="image.png" />
Additional location affected:
<img width="429" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEh5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--56d7033e26e554d3354084704efc23cfb7a17283/image.png" alt="image.png" />
Examples of outcomes:
<img width="1365" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWtUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3c2f96f62f4dd42c86bb7ec116b20429fcd93a1e/image.png" alt="image.png" />
<img width="1367" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMW9UQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dab61316783dece2f6c51663e47a526f2073ba3d/image.png" alt="image.png" />
<img width="1363" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXNUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d2ee63896cf7664a260c4c37901a55ed958f1162/image.png" alt="image.png" />

### Acceptance Criteria
- [x] Assessment-gateway: Update the variable references in _assessmentData_ for PT from calculatedDataChildCareCost to calculatedData**Total**ChildCareCost
The rest of the changes happen in parttime-assessment-**.bpmn:
- [x] Update calculatedDataTotalAssessedNeed from _calculcatedDataChildCareCost_ to _calculatedDataTotalChildCareCost_ 
- [x] Update the "calculatedDataTotalEligibleDependants" event name to "Calculate Eligible Dependants" (x2 in the Single and Married streams)
- [x] Update (x2) calculatedDataTotalEligibleDependants to calculate the age of the dependant based on the study start date and not today()
- [x] Add (x2) calculatedDataDependants11AndUnder and calculatedDataDependants12UpOnTaxes as described in expected behaviour
<img width="559" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2Z5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9f175005ca9ca71ee3b9b3169c30a861f5225838/image.png" alt="image.png" />

- [x] Update the "Calculate calculatedDataChildCareCost" event to the name "Calculate Child Care Costs"
<img width="508" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM255QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6e70b97020550ced43a1019c82648bbdf4aa4802/image.png" alt="image.png" />
- [x] Update calculatedDataChildCareCost as listed in the expected behaviour to validate the student inputs for costs against their declared dependants (There may be a prettier way to do this)
- [x] Add calculatedDataTotalChildCareCost as listed in expected behaviour to take the minimum of the valid student costs and compare against the maximum child care cost allowable
- [x] _(optional)_ Hide the Financial Information section (Dependant care costs) with questions regarding child care and daycare if the dependant question is "No" under Family Information
<img width="566" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0dQQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fe038be945ab86f0a04b9c21295eba58570285b9/image.png" alt="image.png" />
- [ ] E2E Testing

**Comment by CarlyCotton** [comment]
This is a "simplified" calculation vs what is in the MASS. In the MASS we ask for separate care amounts (Under 12 vs 12+ with Disability) and do not add them in if there is not a dependant listed in the corresponding category. (If they claimed $5000 childcare for Under 12 but only had Over 12 eligible dependants it would disregard that $5000)
The actual Policy Manual doesn't specify:
<img width="917" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEtQQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--176779605a2c4059fe5885678436bf107a2ca430/image.png" alt="image.png" />
Will follow up with Policy

**Comment by CarlyCotton** [comment]
@HRAGANBC  or @Joshua-Lakusta can you do a sweep of this before we push to lather?

**Comment by CarlyCotton** [comment]
@michesmith Can we move this to backlog since we were able to vote on it?

**Comment by dheepak-aot** [comment]
Some scenarios in Demo for testing


Scenario 1: Student entered value within considered maximum limit

Offering weeks: 18

Offering Intensity: 20% = 0.20

Offering Weeks multiplier(for child care cost based on workflow) = 34

Dependents who are 11 years and under = 1

Dependents who are 12 years and over and declared on taxes for diability = 1

Total eligible dependents for child care costs = 2 (1+ 1)

Day care cost for 11 years and under = 1000

Day care cost for 12 years and over = 1000

Total daycare cost entered by student = 2000 (1000 + 1000)

Maximum day care cost than is considered as per given offering weeks, intensity and dependents count = 

(Offering-intensity * dmn-weekly-childcare-limit * offering-weeks-multiplier * total-eligible-dependents-for-childcare)

= .20 * 268 * 34 * 2 = 3644.8

Final considered child care cost  = Lesser of (considered limit vs total cost entered by student)

Lesser (3644.8 vs 2000) = 2000


Scenario 2: Student entered value over considered maximum limit

Offering weeks: 8

Offering Intensity: 20% = 0.20

Offering Weeks multiplier(for child care cost based on workflow) = 17

Dependents who are 11 years and under = 1

Dependents who are 12 years and over and declared on taxes for diability = 1

Total eligible dependents for child care costs = 2 (1+ 1)

Day care cost for 11 years and under = 1000

Day care cost for 12 years and over = 1000

Total daycare cost entered by student = 2000 (1000 + 1000)

Maximum day care cost than is considered as per given offering weeks, intensity and dependents count = 

(Offering-intensity * dmn-weekly-childcare-limit * offering-weeks-multiplier * total-eligible-dependents-for-childcare)

= .20 * 268 * 17 * 2 = 1822.4

Final considered child care cost  = Lesser of (considered limit vs total cost entered by student)

Lesser (1822.4 vs 2000) = 1822.4




Scenario 3: Expecting 0 costs

Offering weeks: 8

Offering Intensity: 20% = 0.20

Dependents who are 11 years and under = 0

Dependents who are 12 years and over and declared on taxes for diability = 0

Final considered child care cost = 0
