### ISSUE TITLE
Award Rounding - PT

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#2634]
Waiting on results of initial round of award testing in PT to determine if rounding required at each stage

- [ ] Analyse if we need to round at each stage of award or at the end

**Comment by HRAGANBC** [comment]
@CarlyCotton just pinging you in case this still needs to be part of the last round of assessment related tickets. 

I almost want to defer this one to the Devs as a purely technical consideration - from a business standpoint, we don't care. If I'm understanding correctly, the impact of rounding at each stage vs at the end is trivial - some stages would round up, some would round down, and I would be shocked if the net impact is larger than $20, in which case that's not worth bothering about. 

Let me know if I'm missing something though

**Comment by CarlyCotton** [comment]
@HRAGANBC I'm going to leave it open and see how the assessment testing shakes out. It will give us a good idea of any impacts of rounding at each stage vs how it's being rounded now.

**Comment by CarlyCotton** [comment]
Closing - no need at this time based on assessment tests completed.
