### ISSUE TITLE
2.7.1 Student Request and Report Changes to Application (after COE) 

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#266]
### **Submission of Request a Change**
**Student**
- On the Request a Change page, the student can select 'forms' from the dropdown menu. 
- A student can select as many forms as they wish
- Each form specifically references Part-Time or Full-Time
- Each form is specific to a Program Year (i.e. the fields on the form and the resulting workflow calculations may change across ProgramYears
- Each form can contain one or more 'fields'
- All fields on the form are **mandatory**, i.e. a student must fill out **all** fields of whichever form they select
- **A student must consolidate all previously-submitted Requests for Change into the latest request** 
- Every time a Request a Change is submitted, the student must sign two things:
       1. An application declaration (same one as is displayed upon initial application submission)
       2. A tick-box with the text stating "I acknowledge that this request will not be processed until all required documentation has been provided. I recognize that StudentAid BC representatives may request additional documentation after reviewing my request, and my request cannot be actioned until I provide that documentation."
- A student should be able to submit a request for change **_at any point_** for their application, regardless of whether the end dates have passed.
- If a student submits a Request a Change for an application whose end dates have passed, a banner message should display to the **student** indicating this. (See _After Study End Date Requests_ photo). 
- 

**Ministry User**
- Upon a student submitting their request, all forms requested (and all the fields of each form) are displayed to the Ministry user
- Some specific fields will allow a Ministry staff to input their own value for that field. (See _Ministry Adjustments to Student Requests_ photo)
- In instances where student input and ministry input differ, use ministry input
- - If a student submits a Request a Change for an application whose end dates have passed, a banner message should display to the **Ministry** indicating this. 

**Reassessment**
- All fields included on the Request a Change form get incorproated into the workflow as if they were provided initially
- Any system-generated re-assessment will recognize the latest Request a Change entry. I.e. a scholastic standing re-assessment will recognize that the student was approved for an income change from 20,000 to 10,000 via Request a Change. 
- Any Request a Change which is approved will generate a new assessment which replaces the **Original** assessment, not the **latest** Request a Change re-assessment. I.e. if multiple Request a Changes were submitted, only the latest one is recognized; they are not 'merged' ontop of one another. 
- Any Request a Change which is approved takes effect immediately, and any other pending re-assessment requests will be actioned against this new latest assessment. 
     
**Confirmation of Enrollment**
- Any Request a Change which is approved and has **any** impact to award configuration should trigger a new COE request. The new eCert will not be disbursed until COE is confirmed. 

**Ministry Adjustments to Student Requests**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0tTQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b810cf230e71aa9ae15a05357d27d6c51fd65f21/image.png)

**After Study End Date Requests**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0tTQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2dea6731f5d81ee96bb1168cbf71104e32e63a12/image.png)

**Comment by michesmith** [comment]
@HRAGANBC Can you please confirm 'The Forms' that are in the drop down. Eg; Request a Change PD, Request a Change Personal Info, Request a Change Financial Info.....?
