### ISSUE TITLE
Identify related applications to create reassessments on application change and add that to cancel queue

### ISSUE THREAD

**Issue by michesmith** [bcgov/SIMS#2665]
###  Centralized logic to get all impacted applications
As per cascading impact on applications, when any change happens to an application like:
 - Cancelling an assessed application (will be triggered from `cancel-assessment` queue)
 - COE getting declined for an application (will be triggered from `cancel-assessment` queue)
 - Reassessment happening to an application (will be triggered from `assessment-gatway-workflow`)
 
We need to have a logic that identifies, all the potentially impacted applications due to one of the above actions and create a re-assessment for the identified applications to be potentially impacted.

**Chronology:** we must use **Chronology 2**(order by original assessment calculated date) to execute this logic.
**Logic:** we need to have a logic that identifies, all the potentially impact application due to one of the above actions and create a re-assessment for the identified applications to be potentially impacted.

The logic at a high level must be, to get all the applications whose assessment calculation date(assessment_date) of its original assessment is after the calculation date of the original assessment of the application that is being changed.

### DB Migrations

DB Migrations are required to create a new value for `assessment_trigger_types` like `Related Application Changed` to create reassessment.

Add a new column to identify the assessment that caused the `Related Application Changed` to the `student_assessments` table. The column name could be `related_application_assessment_id`.

### Apply the centralized logic to cancel the assessment queue.

As cancel assessment queue will be executed when the following changes happen to the application 

- Student Cancel Application

The centralized logic to create re-assessments must be called from the cancel assessment queue.

### Identify the best approach between 

Identify the best approach between creating reassessments for all impacted applications at the same time or just creating reassessments for the first impacted application and letting it happen sequentially.

Please consider the following example:

<img width="1753" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUhJQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e6bf7d93270f6a4b91184330a6a9ba625073063e/image.png" alt="image.png" />

**Acceptance Criteria**
- [x] Create DB migration for new assessment trigger type and parent assessment id which caused the change.
- [x] Create the centralized logic to identify impacted applications and create re-assessments with new trigger type.
- [x] On the newly created re-assessments of type `Related Application Changed` save the parent assessment id.
- [x] Identify the best approach between creating reassessments for all impacted applications at the same time or just creating reassessments for the first impacted application and letting it happen sequentially.
- [x] Call the centralized logic from the processor of the `cancel-application-assessment` queue.
- [x] Applications considered meaningful for the program year maximums and sequence
  - Current application assessment calculated.
  - At least one COE Required/Completed.

**Comment by andrewsignori-aot** [comment]
@Joshua-Lakusta and @CarlyCotton do you mind having the below points added to the ticket description since they reflected the decisions made by the team during the development?

- [ ] Applications considered meaningful for the program year maximums and sequence
  - Current application assessment calculated.
  - At least one COE Required/Completed.
