### ISSUE TITLE
PT Assessment - Additional Transportation Costs

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#2668]
**User Story**
As a PT student, I need to be able to report exceptional transportation expenses so that it can be approved and incorporated into my assessed need. This additional expense also needs to be reflected on the NOA page.

**Current Behaviour**
This isn't implemented, we only calculate the base transportation allowance for "onsite" offerings.
<img width="153" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGZYQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--90613c7f883e4466df6ff207773168183c993620/image.png" alt="image.png" />
```
calculatedDataTransportationAllownace=
if offeringDelivered = "onsite"
then dmnPartTimeProgramYearMaximums.limitTransportationAllownace * offeringWeeks
else
  0
```

**Expected Behaviour**
When the ministry approves the Additional Transportation Allowance (Exception Question - See Form/Variable Creation on #1707), this cost should be used in the assessment.

- If the student is travelling more than 280km per week:
-- $94/week
- If the student is travelling between 1 and 280 (inclusive) KMs per week:
-- $94/week * 0.34
- If the student is receiving an additional amount based on a clinical or practicum placement:
-- Reduce the $94/week by $25/week in the above calculations
- If the student is receiving the additional transportation allowance for a week, they are not eligible for the normal allowance that week (dmnPartTimeProgramYearMaximums.limitTransportationAllownace). The $94/week max is inclusive of the $13 per week they may be eligible for if in an "onsite" offering.
- The additional transport weeks requested should not be higher than the total offering weeks in the study period
- The calculated additional transportation costs per week should be the lesser of the student's declared weekly costs and the ministry's pre-determined weekly cost (94, 94-25).

<img width="623" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0R3QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4df0d64210efd070ee7da6cdc86631ce804a20bb/image.png" alt="image.png" />

```
calculatedDataAdditionalTransportationMax =
if (studentDataAdditionalTransportPlacement)
then MIN(dmnPartTimeProgramYearMaximums.limitAdditionalTransportationAllowance-dmnPartTimeProgramYearMaximums.limitAdditionalTransportationPlacement,studentDataAdditionalTransportCost
)*MIN(offeringWeeks,studentDataAdditionalTransportWeeks)
else
MIN(dmnPartTimeProgramYearMaximums.limitAdditionalTransportationAllowance,studentDataAdditionalTransportCost)*MIN(offeringWeeks,studentDataAdditionalTransportWeeks)
```

```
calculatedDataTotalTransportation =
if AND(offeringDelivered="onsite",offeringWeeks>=studentDataAdditionalTransportWeeks)
then
  (offeringWeeks-studentDataAdditionalTransportWeeks)*dmnPartTimeProgramYearMaximums.limitAdditionalTransportationAllowance + calculatedDataAdditionalTransportationMax
else
MIN(calculatedDataAdditionalTransportationMax, studentDataAdditionalTransportCost*MIN(offeringWeeks,studentDataAdditionalTransportWeeks))
```

<img width="580" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1h3QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f8a48d546d7cc81ab5ef2b9d6c59aaf835f9e9b5/image.png" alt="image.png" />

```
calculatedDataAdditionalTransportationMax = 
if (studentDataAdditionalTransportPlacement)
then MIN(dmnPartTimeProgramYearMaximums.limitAdditionalTransportationAllowance-dmnPartTimeProgramYearMaximums.limitAdditionalTransportationPlacement,studentDataAdditionalTransportCost
)*MIN(offeringWeeks,studentDataAdditionalTransportWeeks)*dmnPartTimeProgramYearMaximums.limitAdditionalTransportationKMReduction
else
MIN(dmnPartTimeProgramYearMaximums.limitAdditionalTransportationAllowance,studentDataAdditionalTransportCost)*MIN(offeringWeeks,studentDataAdditionalTransportWeeks)*dmnPartTimeProgramYearMaximums.limitAdditionalTransportationKMReduction
```

```
calculatedDataTotalTransportation = 
if AND(offeringDelivered="onsite",offeringWeeks>=studentDataAdditionalTransportWeeks)
then
  (offeringWeeks-studentDataAdditionalTransportWeeks)*dmnPartTimeProgramYearMaximums.limitAdditionalTransportationAllowance + calculatedDataAdditionalTransportationMax
else
MIN(calculatedDataAdditionalTransportationMax, studentDataAdditionalTransportCost*MIN(offeringWeeks,studentDataAdditionalTransportWeeks))
```

<img width="595" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0x3QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b10d4d3dd52eff7d4ce640ac6a240c4f4c9cd2b5/image.png" alt="image.png" />

```
calculatedDataTransportationAllowance = 
if offeringDelivered = "onsite"
then dmnPartTimeProgramYearMaximums.limitTransportationAllownace * offeringWeeks
else
  0

calculatedDataTotalTransportationAllowance = 
calculatedDataTransportationAllowance

```
<img width="888" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0R4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7dfc493cd9010a3855945bd75adf8b8791cbbf21/image.png" alt="image.png" />

**Additional Context**
- Excel file with the calculations:[PT-AdditionalTransport.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFJXQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--15a7b538a4a8bf9e10d7a90c3e6516f30ce711de/PT-AdditionalTransport.xlsx)

- Additional Transportation Cost is different from Return Transportation Cost.
- The Additional Transportation Allowance does NOT need to get mapped to IER-12
- There is a transportation cost variable in Camunda: studentDataTransportationCost but it is UNCLEAR which field is attached.
- New variables for use in these calculations was requested in the form update #1707: studentDataAdditionalTransportKm, studentDataAdditionalTransportCost, studentDataAdditionalTransportWeeks, studentDataAdditionalTransportPlacement
<img width="498" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnZ3QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--97fb5022c0ca3625d84c14a7800253fbd8a2bf7d/image.png" alt="image.png" />

**Acceptance Criteria**
- [x] Create new limits in DMN table to support this process in dmnPartTimeProgramYearMaximums for all existing program years: 
- limitAdditionalTransportationAllowance: 94
- limitAdditionalTransportationPlacement: 25
- limitAdditionalTransportationKMReduction: 0.34
- [x] **CONSIDER IF ADDITIONAL VARIABLE COULD BE USED** There are multiple MIN(offeringWeeks,studentDataAdditionalTransportWeeks) used. Should this be handled differently? 
- [x] Housekeeping Update any variables of "allownace" to "allowance":
- dmnPartTimeProgramYearMaximums.limitTransportationAllownace
- calculatedDataTransportationAllownace
- [x] Update Camunda Workflow to assess the possible additional transportation allowance. 3 different paths: KMS > 280, 1 -280 KMs, and KM=0 or null (no exception requested)
- [x] Update calculatedDataTotalAssessedNeed from calculatedDataTransportationAllownace to calculatedDataTotalTransportationAllowance 
- [x] Update "save-assessment-data" in assessment-gateway.bpmn for PT from "calculatedDataTransportationAllownace" to "calculatedDataTotalTransportationAllowance"
<img width="825" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUx3QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b1bc032e8efa977c53243c2ed11b3c91670a7d46/image.png" alt="image.png" />
- [x] E2E tests
- [x] Display Additional transportation cost panel for PT applications (updated 2024-02-13)

**Comment by lewischen-aot** [comment]
<img width="1729" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmhjQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--606282be90bccf881122b52cbeecc2ad56f01530/image.png" alt="image.png" />

**Comment by andrewsignori-aot** [comment]
@CarlyCotton as you mentioned in the ticket description the variable `studentDataTransportationCost` does not exists currently in any form.io definition and it is created in the `load-assessment-consolidated-data`.
Right now, it is probably wrongly consumed by the full-time workflows and I assume that once we do a similar change for full-time we should be able to remove `studentDataTransportationCost` completely.

**Comment by lewischen-aot** [comment]
Reference to using `calculatedDataAdditionalTransportationMax` in the else statement above:

Because `MIN(calculatedDataAdditionalTransportationMax, studentDataAdditionalTransportCost*MIN(offeringWeeks,studentDataAdditionalTransportWeeks))` is the same as `calculatedDataAdditionalTransportationMax`, we can safely use `calculatedDataAdditionalTransportationMax` instead. In case there is a change in the formula for `calculatedDataAdditionalTransportationMax` later on, we can reference back to this change log.

**Comment by dheepak-aot** [comment]
@CarlyCotton  I did not get the else logic here in `calculatedDataAdditionalTransportationMax`

Else corresponds to offering weeks < additional transportation weeks

Can additional transportation weeks be greater than offering weeks itself ??

<img width="1027" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVJrQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e7fc24655d3a7fa3f7c134fb81844b5ed16c0200/image.png" alt="image.png" />

**Comment by HRAGANBC** [comment]
@dheepak-aot Correct, additional transportation weeks cannot exceed offering weeks. 

@CarlyCotton FYI
