### ISSUE TITLE
Call the logic to create re-assessment for impacted applications when a COE is Declined

### ISSUE THREAD

**Issue by dheepak-aot** [bcgov/SIMS#2677]
**Describe the task**
When a COE for an application is declined, it means that there can be impacts to other applications submitted for same student in same PY.

In that case we need to call the centralized logic built in #2665 to identify  the impacted applications and create re-assessment for them.

Note: While calculating the PY award consumed in #2672, awards from declined COE must not be included.

**Acceptance Criteria**
- [x] When a COE is declined by the institution, call the centralized logic to identify built in #2665 to identify  the impacted applications and create re-assessment for them.
- [x] First confirm if already implemented. If a student cancel an application who's enrolment was declined, it must not create impacted application re-assessments as COE Decline action is suppose to have handled it already.
- [x] e2e

**Comment by ninosamson** [comment]
@dheepak-aot to update this ticket.
