### ISSUE TITLE
Confirm Details of DISB002 Report during NSLSC file exchange process

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2684]
Have some more questions related to DISB_001. For context, DISB_001 is the file SIMS produces and sends to our Finance department to confirm the sum totals of all the money that has been disbursed that day, organized by award type.  See the highlight in the photo below, and see #139 for further context
 
My questions:
- Can someone please generate a sample version of this file for me? 
- Please confirm precise file name currently used for this report.
- Please confirm the email address destination for this report currently configured in Test and Prod, and what schedule the file is sent.
- Please confirm whether this file contains award total for FT and PT
- **Most importantly**: Please confirm that this file will calculate the sum total of award types which have been confirmed as disbursed through the Federal Daily Disbursement **Feedback** Files (TEDU.PBC.DIS.D#######.###)  as opposed to the Federal Daily Disbursement **Request** File (aka eCert file). I.e. the DISB_001 should reflect the actual disbursements as dictated by the Federal government, not by our system. 

Acceptance Criteria: 
- [x] Analyze current state of report and confirm if this is desired state for business
- [x] Tweak report or create new tickets if needed

<img width="1087" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1RoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e33b8ff478c23cc5c7244826f0e36fd731fe2c9b/image.png" alt="image.png" />

Thank you!!

**Comment by dheepak-aot** [comment]
The original implementation ticket of the requirement - #1249

**Comment by dheepak-aot** [comment]
Here are the answers to the questions in the ticket - 

Can someone please generate a sample version of this file for me? - [Daily_Disbursement_File_2024-02-21_06.07.24.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3g2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9524150ca83dd9c1af5fe9cb4d88d559ce42bbed/Daily_Disbursement_File_2024-02-21_06.07.24.txt)

**Note:** The original file extension is .csv. But Zenhub is not allowing to upload csv file and hence it is renamed to .txt to be uploaded here.


Please confirm precise file name currently used for this report. 

Please confirm the email address destination for this report currently configured in Test and Prod, and what schedule the file is sent.
Please confirm whether this file contains award total for FT and PT
Most importantly: Please confirm that this file will calculate the sum total of award types which have been confirmed as disbursed through the Federal Daily Disbursement Feedback Files (TEDU.PBC.DIS.D#######.###) as opposed to the Federal Daily Disbursement Request File (aka eCert file). I.e. the DISB_001 should reflect the actual disbursements as dictated by the Federal government, not by our system.

**Comment by HRAGANBC** [comment]
@dheepak-aot @CarlyCotton   

Thanks, Dheepak, looks great and very close to what is actually needed. 

Questions:
1. If there are no daily disbursement files received from Feds that day, does CSV report still get produced with no records, or does no file get produced? Either way is fine, as long as the process of creating the CSV doesn't 'error out' 
2. Rather than placing it on SFTP, can we email it out instead? Do we need ticket for this or is it sufficient to just implement the change as part of this ticket?

**Comment by HRAGANBC** [comment]
Further confirmation from Dheepak:
1. Content of file contains no reference to date of batch being referenced. If no Federal file received, CSV will get populated eveyr day with whatever the latest batch received from Feds. This means possible to duplicate rpeorting. Need to include a date of batch in the content of the CSV file itself. 
2. We need a new ticket to create GC notify to send daily CSV file to MOF address. Devs need to figure out how to configure an attachment through GC notify
3. Total number of records refers to the number of individual disbursements relfetced in federal files. I.e. the number of students who received BC funding.

**Comment by dheepak-aot** [comment]
@HRAGANBC 

on 3. Total number of records refers to the number of individual disbursements relfetced in federal files - is right but that may not be necessarily the total number of students who received the funding because one student can have 2 disbursements which can belong to same file.

**Comment by dheepak-aot** [comment]
@CarlyCotton @HRAGANBC created ticket
https://app.zenhub.com/workspaces/student-information-management-system-5fce9df5aa1b45000e937014/issues/gh/bcgov/sims/2869 

for the updates required in the ticket.
