### ISSUE TITLE
Import Provincial Restrictions from SFAS Data Bridge into SIMS Account (Part 1) 

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2685]
**Description**
Ensure that any restrictions imported through the SFAS data bridge are not only logged in SIMS database but **also** translates into those restrictions being applied as 'active' within the student's account. When a restriction code is imported but not recognized by SIMS, convert it to a generic restriction with a warning. 

**Note about the Business Process**
Restrictions will continue to be imported daily from legacy systems even if they've been resolved within SIMS. I.e. SST has to manually resolve them in BOTH systems to prevent them re-appearing through the SFAS data bridge. 

<img width="989" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVgzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b09891292f6a9c1e7cc2972af6c23a309db7889e/image.png" alt="image.png" />

**Acceptance Criteria**
- [x] Import active ("restrictionRemovalDate"= null) provincial restrictions from SFAS_restrictionstable, based on "Restriction Code", updating the student account restrictions. Ignore restrictions with "restrictionRemovalDate". 
- [x] Create new provincial restriction type called "Legacy" with code LGCY. Categorized as 'other' within the Ministry interface. 
- [x] Only one active LGCY restriction at a time 
- [x] Check for necessary mapping from the Excel spreadsheet attached below. 
- [x] If a code is imported from SFAS bridge but **not** explicitly mapped to a SIMS restriction, then convert it to a LGCY and apply that restriction in SIMS.
- [x] LGCY restriction should have the following effects:
- Stop part-time disbursement; stop full-time disbursement
- Add banner message with standard restriction 'error' message on student dashboard
- [x] Apply provincial restrictions imported from SFAS onto the student account, according to the mapping done in the attached excel. (see additional context below)

**Additional Context**
- Restrictions List Mapping found here: [SIMS Restrictions List.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1ZEQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e17df147bc512ce164fc8555fec096637ad98128/SIMS%20Restrictions%20List.xlsx)

Note: Use only the worksheet titled "Restrictions (Devs)' and compare column C for existing SIMS codes and column D for corresponding SFAS codes

**Comment by michesmith** [comment]
@HRAGANBC @Joshua-Lakusta @CarlyCotton Confirming Confirming that all data from SAIL is being sent to SFAS the larger question but in particular regarding restrictions

**Comment by sh16011993** [comment]
@HRAGANBC @Joshua-Lakusta @CarlyCotton Just to confirm, for example, lets say there is a restriction that is imported from SFAS for a student which is not having the `restrictionRemovalDate` and lets say that that the same restriction (having the same restriction code) for the same student is active in the sims system, do we add another entry for this imported restriction in the sims table or not?

**Comment by Joshua-Lakusta** [comment]
@sh16011993 In general I believe you are correct. I cannot think of a scenario where we would want it to be doubled up. There are restrictions that we have in SIMS like withdrawals where there can be multiple in sims but those restrictions do not exist in SFAS as it is a different data type. That is the only one i would be care around as i do not know how we are importing withdrawal and UC data into sims from SFAS. @HRAGANBC @CarlyCotton are you more clear on the data bridge for that data. Is the withdrawals and uc being treated as restriction data when being pulled over. If yes then i think there could be the possibility of needing duplication. Other then that i think it is fine.
