### ISSUE TITLE
Expand SAIL/SFAS Data Import to Support PY Maximum Rules and other functions

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2686]
**Description of Task**
Expand the SFAS -> SIMS data bridge to include additional fields imported from SAIL which support the implementation of PY maximum assessment rules and Part-Time lifetime maximum rules in SIMS. 

SAMPLE FILE: [SFAS-TO-SIMS-2024MAR14-093019.TXT](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVRnQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--63f695f37e2d1472734d4488d99fa7c57714aa97/SFAS-TO-SIMS-2024MAR14-093019.TXT)

SFAS to SIMS spec document AS OF Mar 18, 2024: [SFAS to SIMS Bridge.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWJzQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ae8baf152fca301422d59e876293ae88ee001747/SFAS%20to%20SIMS%20Bridge.docx)

**Acceptance Criteria:**
- [x] Incorporate the following fields into the portion of the data import sourced from SAIL:
- CSPT
- CSGD
- BCAG-PT
- CSLP
- ProgramYear ID associated with application (optional field)
- [x] Save these fields

**Mock-Ups**
**Previous Data Bridge Layouts:**
<img width="803" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOS9OQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2106901cdb6a1d47c52e48ae64a50d2b19f9d9a4/image.png" alt="image.png" />

**Updated Data Bridge Layouts**
**Note** These are additional fields added to the layout in addition to what was previously included. CSGP and SBSD represent 'overwrites' of the old layouts, 
<img width="760" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzNJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--97262283d35472ab3648f99b63ac6d5c0838c94c/image.png" alt="image.png" />

**Business Context:**
- SAIL to NSLSC Loan Balance Update process described on Page 16 of this document: [All Interfaces in and out.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXoyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9a856d30a7cabaeafc21591d0905e0047b4a23db/All%20Interfaces%20in%20and%20out.docx)

**Technical Context**
- [x] Add additional colums in `sfas_part_time_applications` table for the awards `cspt_award`, `csgd_award`, `bcag_award`, `cslp_award`, and `program_year_id`.
- [x] Use [sfas-part-time-application.service.ts](https://github.com/bcgov/SIMS/blob/main/sources/packages/backend/libs/integrations/src/services/sfas/sfas-part-time-application.service.ts#L31-L48) to add the additional values to save in the table.
- [x] E2E test.

**Comment by michesmith** [comment]
@Joshua-Lakusta to wrap this up and move it to lather

**Comment by lewischen-aot** [comment]
@HRAGANBC @Joshua-Lakusta @CarlyCotton 
I'm attaching the screenshot of the updated columns for `sfas_part_time_applications` table on the DEV database as a reference to the completed state of the story where the acceptance criteria were all fulfilled.

<img width="1349" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMU1RQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b8108937b9e4b8267b209bbd7dbdd05c9a32cb6c/story_2686.png" alt="story_2686.png" />
