### ISSUE TITLE
Retrieve SFAS/SAIL Award Values Needed for PT PY Maximums

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2689]
**Description of Task**
Ensure that SFAS and SAIL award amounts are correctly referenced by Camunda when determining the sum of awards already-disbursed within a PY **which impact PT assessment**

**Acceptance Criteria:**
- [x] Store Legacy system award amounts with the associated application dates. Use **legacy application start date** to determine how legacy award values get inserted into SIMS sequential ordering of assessments.
- [x] SIMS will only consider the latest values sent from bridge file. (Bridge file changes are not automatically triggering a reassessment).
- [x] Handle all award values imported from SFAS if the award values are attached to the Program Year ID
- [x] Handle all award values imported from SAIL if the award values are associated with a particular program year  (based on study start dates to infer Program Year). 
- [x] Legacy application award values should be considered the same as SIMS during the assessment calculations
- Note: Program Year in all situations should be based on study start date. ie.. If study start falls within Program Year window. 

**Context:**
The following award types are needed:
SFAS Attribute - (SIMS Attribute) 
CSG-PT - (CSPT)
CSG-PTDEP - (CSGD)
CSG-D (across FT/PT) - (CSGP)
SBSD (across FT/PT) - (SBSD)
BCAG-PT - (BCAG)

**Technical Context**
- [x] Use `sfas_part_time_applications` and `sfas_applications` tables to query and fetch the sum of grants (Federal/Provincial) for all applications submitted by the student for the particular program year, considering the study start date, and limit the date till the "application first calculated assessment". "application first calculated assessment" should be available from the query already in place executed by SIMS to calculate program year maximums Please see the property `referenceAssessmentDate` under `getSequencedApplications` method.
- [x] Include the SFAS/SAIL totals in the existing method `getProgramYearPreviousAwardsTotals`.
- [x] This will be further used in the Camunda calculations automatically.
- [x] E2E test cases need to be enhanced from existing ones.
  - Add more E2E scenarios to the `verify-assessment-calculation-order-task` worker to validate if the outputted values include SAIL/SFAS when available in the same program year.

**Comment by CarlyCotton** [comment]
Just adding here re conversation at Story Review today: we need to consider the "effective date" of the awards from SFAS/SAIL so we can put them in the correct order/sequence for calculations.

**Comment by CarlyCotton** [comment]
@andrewsignori-aot Confirming based on conversation yesterday. 

- We MAY receive a PY ID for SAIL records (2686). Store whatever we receive.
- When using the PY award amounts and determining which PY to use them in, use the study start/end dates for the SAIL records. (ignore any PY ID field on them)

**Comment by andrewsignori-aot** [comment]
@HRAGANBC @Joshua-Lakusta @CarlyCotton 
We would like to revalidate the understanding of how the applications will be filtered from SFAS/SAIL.
SIMS will search for applications in SFAS/SAIL where their `start dates` are between the `program year start date` and the `SIMS application assessment calculation date`. Does it sound right?

For instance, considering the below SIMS application, the SFAS application would be considered in the PY total.

Considering the SIMS application.
- Offering start date: Jul 1st 2024
- Calculated assessment date: Jul 2nd 2024

SFAS Application
- Start date: May 1st 2024
- End date: Dec 1st 2024

@lewischen-aot  @dheepak-aot FYI

**Comment by Joshua-Lakusta** [comment]
@andrewsignori-aot @HRAGANBC @CarlyCotton @lewischen-aot @dheepak-aot 
Yes both of the listed applications would be included in the program year calculation. However, your example would not function because there is study date overlap.

Another example would be the following:

SFAS application Start: Sept 1  End: Dec 31st 2024

SIMS application offering start Jan 10th 2025
SIMS application assessment date December 20th 2024

Order of assessment would be SFAS application and then the SIMS assessment so SIMS app would be affected by the SFAS program year limit usage. I am not 100% certain of the data coming over. However, we can treat the submission date for SFAS similar to how we are treating the assessment date for SIMS as SFAS applications are locked at that point. I hope this helped but I am free to chat if I just further confused this issue.

**Comment by andrewsignori-aot** [comment]
@Joshua-Lakusta I believe that it helped to clarify the questions and it seems that our understand is on the same page.

**Comment by lewischen-aot** [comment]
Just post here for the record:

There can be more then one application in SFAS/SAIL within a program year, but they will never have overlapping dates. That is, the end date of the first SFAS/SAIL application record must be earlier than the start date of the second SFAS/SAIL application record. For example, a SFAS student has a SFAS application record with start date on September 1st, 2023 and end date on Dec 31st, 2024. Then the second SFAS application record will have a start date later than Dec 31st, 2024, e.g., start date on Jan 15th, 2024 and end date Apr 15th, 2024. It is this behavior with the sequential manner that allows us filter the SFAS/SAIL application records in the current implementation.
