### ISSUE TITLE
Remittance calculation change

### ISSUE THREAD

**Issue by Joshua-Lakusta** [bcgov/SIMS#2697]
**As a** *(Student)* **I want** The remittance calculation to apply the institution offering cost rules across my total application **So That** The remittance rules are applied correctly and I have enough funding throughout my study period.

**Acceptance Criteria**
- [x] Change the Inputs into the Maximum Allowable Tuition Remittance Calculation such that:
- The Offering costs used as input (Tuition + Books and Supplies + Mandatory Fees) is equal to the offering costs across the **entire offering**, whereas
- The award amounts used as input is equal to the award amounts assigned **to each specific disbursement**

- [x] If disbursement has not been issued, use requested amount, if eCert was sent, use actual amount remitted.
- [x] Apply the rule change to allow for the offering costs calculation (Tuition +books and supplies) to be a total amount limit for all disbursements in a single application.
- [x] Update E2E tests around remittance

**Additional Context**
- Current formula = the lessor of (tuition + books and supplies (formerly program related costs)) and (Canada Grant + CSL + BCSL – amount already disbursed)
- Current formulas are correct but are not being applied the correct way. 
- Current formula is remittance limit is the lesser of total disbursement award or total cost from the institution. 
- The error in this logic is that the cost calculation is being applied in isolation for each disbursement when there is multiple in the same application
- The costs should be cumulative between the two disbursements in the same application

Example
Current State
Student application has 2 disbursements and total institution costs for tuition and books/supplies are $7000 on the offering. (Canada student grant + CSL+BCSL = $9000)
Disbursement 1 = $5000
Disbursement 2 = $4000

Remittance allowed
D 1 = $5000 (Formula = lesser of total costs or total disbursement) Costs = $7000 so it would max out at the disbursement amount and allow $5000
D 2 = $4000 (Formula would be the same as above because its not cumulative so once again it would max out with the full $4000

Changed version
D1 would use $5000 the same way as above however it would allocate $5000 of the $7000 costs. The total costs remaining would be $2000
D2 would only allow remittance of $2000 as that is the lessor of the amounts since only $2000 was left of the costs for the second disbursement.

This is required for PT release but needs to be done for both PT and FT

**Technical**
- [ ] Adjust the method [getMaxTuitionRemittance](https://github.com/bcgov/SIMS/blob/main/sources/packages/backend/libs/services/src/confirmation-of-enrollment/confirmation-of-enrollment.service.ts#L126) to also consider the value from `sims.disbursement_schedules.tuition_remittance_effective_amount`, if present, or `sims.disbursement_schedules.tuition_remittance_requested_amount` if the e-Cert was not generated yet (it can be done as variable1 ?? variable2 to pick the one available).
- [ ] The change will affect the maximum amount the institution can request during the COE approval and also the `tuition_remittance_effective_amount` calculated during the e-Cert generation. In both situations, the method `getMaxTuitionRemittance` should receive the existing tuition remittance already calculated.
- [ ] E2E tests
  - [ ] Ensure there is at least on scenario validations the value `maxTuitionRemittanceAllowed` from the API endpoint `institutions/location/:locationId/confirmation-of-enrollment/disbursement-schedule/:disbursementScheduleId`.
  - [ ] Expand the current COE confirmation tests to validate the maximum tuition including the tuition already requested in a previous disbursement.
  - [ ] Expand the current e-Cert tests to have a scenario to ensure maximum tuition including the tuition already requested in a previous disbursement.

**Comment by andrepestana-aot** [comment]
@Joshua-Lakusta Talking to Andrew about this ticket we thought that the logic for max tuition remittance should be:
`Math.min((offeringTotalCosts - previousTuitionRemittance), totalAwards)` 
instead of 
`Math.min(offeringTotalCosts, totalAwards) - previousTuitionRemittance`

Could you please confirm?

**Comment by Joshua-Lakusta** [comment]
I agree, after reviewing yours makes more sense. We are taking the min of the costs minus what they have remitted or the total award. Thanks for reaching out and move forward with your calculation.
