### ISSUE TITLE
Program Year 24/25 Updates 

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#2705]
New template files for Camunda, Forms, and DB changes are required to support the upcoming program year 24/25. This effort will focus on duplicating the most recent program year (2023-2024) to enable a Student Application to be submitted by selecting the new program year (2024-2025). New program year parameter values or any processing different than the ones currently enabled for 2023-2024 are not part of this ticket.

New Files that should be copied from their 2023-2024 files:
  - [x] fulltime-assessment-2024-2025.bpmn
  - [x] parttime-assessment-2024-2025.bpmn
  - [x] Ensure to update the internal variable names previously referencing the source year (name, processRef, and id) on the above `bpmns` .

Add new 2024-2025 Values in the DMN tables (copy existing 2023-2024 values):
  - [x] fulltime-assessment-decisions.dmn
  - [x] parttime-assessment-decisions.dmn

Copy and rename the below form.io definitions.
  - [x] `sfaa2023-24.json` to `sfaa2024-25.json`.
  - [x] `supportingusersparent2022-2023.json` to `supportingusersparent2024-2025.json`
  - [x] `supportinguserspartner2022-2023.json` to `supportinguserspartner2024-2025.json`
  - [x]  Update `name` and `path` to reflect the new program year in the above forms.

Create the new program year entry in DB.
- [x] Create a migration to insert the new Program Year record in `sims.program_years`.
  - program_year: 2024-2025
  - program_year_desc: Study starting between August 01, 2024 and July 31, 2025
  - form_name: SFAA2024-25
  - is_active: true
  - start_date: 2024-08-01
  - end_date: 2025-07-31
  - parent_form_name: supportingusersparent2024-2025
  - partner_form_name: supportinguserspartner2024-2025
  - program_year_prefix: 2024
  - max_lifetime_bc_loan_amount: 50000

Create a new suite of E2E tests for the 2024-2025 program year and validate a student application submission.
- [x] Duplicate the folder from sources\packages\backend\workflow\test\2023-2024 and rename it to 2024-2025. Do not rename any program-year-specific named file.
- [x] Update the const under sources\packages\backend\workflow\test\2024-2025\constants\program-year.constants.ts to `2024-2025`
- [x] Ensure that all tests all passing for the new program year.
- [x] Ensure that a new student application can be submitted selecting the new program year and has its NOA generated.
- [x] Remove E2E-related tests to 2021-2022 (maybe 22/23 as well - TBD).

**Comment by andrewsignori-aot** [comment]
@CarlyCotton I added the items needed from a technical perspective to have the new program year added to SIMS. Please let me know if some clarification is needed.

**Comment by andrewsignori-aot** [comment]
Created the wiki with the steps defined in this ticket for a reference for the new years: https://github.com/bcgov/SIMS/wiki/Program-Year-Setup
