### ISSUE TITLE
Student is blocked from accepting Assessment ( Disability Funding not verified, Funding Restrictions, MSFAA not Signed) 

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2706]
**User Story**
As a Student, I should be blocked from accepting my assessment until:
    - My disability profile status is verified (only applicable if they have requested disability funding on their application)
    - My MSFAA is Signed 
    - I have resolved restrictions which have the 'block funding' effect.
So that I am prompted to deal with outstanding items on my application before my study start date. 

**Acceptance Criteria:**
- [x] Do not allow student to **accept** their assessment if: (i.e. disable the button in the UI/UX) for any of the following situations:
    - [ ]  Application requests disability funding & disability profile status is still NOT verified
    - [ ]  The MSFAA is not valid
    - [ ]  Restrictions are preventing their funding from being issued.  
- [x]  If any above condition is =true, the accept assessment button should not be clickable
- [x]  If any above condition is =true, display a warning banner at the top of the Notice of Assessment Page (the location where the 'accept assessment' button is)
- [x]  If multiple blocking conditions display all information under the same banner as a bulleted list (similar to the blocked disbursement tracker card).

**Content for banners:**  
Disability Check Banner:
>Your account has not been approved for disability funding. You will not be able to accept this application until the account disability status has been approved. If you would like to receive all non disability funding please edit your application.

MSFAA Check Banner:
>Your MSFAA is not valid. Please complete your MSFAA with the National Student Loans Centre to move forward with your application. Please note, there is a one day delay between signing your MSFAA and being able to accept your assessment. 

Restrictions Check Banner:
>You have restrictions that block funding on your account. Please resolve them in order to move forward with your application.

**Additional Context:**
    - To confirm criticality for PT MVP Scope. Can we rely on communications instead to ensure students are aware of the below things blocking disbursement? I.e. a banner message which immediately applies to their account right after accepting their assessment if there's anything blocking their eventual eCert, AND/OR an email notification to the student when any such conditions exists. 
    - This ticket does not impact the student's application status tracker in any way
   
**Technical**
- [x] Reuse the same logic from [application.students.controller.ts](https://github.com/bcgov/SIMS/blob/main/sources/packages/backend/apps/api/src/route-controllers/application/application.students.controller.ts#L782) to get the list of all failed validations.
- [x] Adapt the query used by the validation method to allow applications other than `Completed`.
- [x] Change the appropriate API endpoint to return the failed validations list similar to the API endpoint mentioned in the first technical AC.
- [x] "MSFAA Check Banner" will be based on `MSFAACanceled` or `MSFAANotSigned`.
- [x] E2E tests

**Comment by andrewsignori-aot** [comment]
@Joshua-Lakusta the message for the "MSFAA Check Banner"  is targeting only the MSFAA not signed. Should we have a specific one for a canceled MSFAA, or should only the not-signed banner be displayed?

**Comment by andrewsignori-aot** [comment]
@Joshua-Lakusta should we assume that these checks can use the same logic from the Application Tracking Card that lists the e-Cert blocking items?

**Comment by Joshua-Lakusta** [comment]
@andrewsignori-aot 
For the banners: the content there is attempting to cover all situations. So please make that banner appear anytime the MSFAA has a fail whether it is not signed or cancelled. If it is not valid then have that banner appear. 

For the blocking yes it should be the same logic for each of these. Generalized to disability miss match, restriction blocking, and msfaa is not valid for any reason.
