### ISSUE TITLE
Malware Scanning - File Uploads

### ISSUE THREAD

**Issue by ninosamson** [bcgov/SIMS#2708]
SIMS needs to have malware scanning for file uploads on the student account, to prevent malicious files from being uploaded. 

Other teams on OpenShift have implemented [ClamAV ](https://www.clamav.net/)to comply with this requirement. https://github.com/bcgov/clamav

Acceptance Criteria: 

- [ X ] Research ClamAV and connect with other teams on RocketChat 
- [ X ] Implement or create new ticket for implementation on all file uploaders

**Comment by sslaws** [comment]
Created ticket 3180 for implementation and research comments.
