### ISSUE TITLE
Hackathon Option C- CHFS

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#271]
**Describe the task**
This task if to dive deep into the pros and cons of CHFS structure to create question and application framework.

**Acceptance Criteria**
- [ ] Fill out SWOT Model located: https://app.mural.co/t/range1280/m/range1280/1610467278826/d00cb1a391d5c23edb710b6dec2b7b62333bed93

**Additional context**
- [ ] Identify the limitations of this model
- [ ] Identify pros of this model
- [ ] Identify maintenance and longevity issues we may face

https://bcgov.github.io/common-service-showcase/services/chefs.html

**Comment by abschwenker** [comment]
Hackathon.docx uploaded to Teams
