### ISSUE TITLE
Data Integration with SAIL- Part-Time Restrictions 

### ISSUE THREAD

**Issue by michesmith** [bcgov/SIMS#2722]
Are we truly getting everything we need from SFAS?

**Comment by michesmith** [comment]
@CarlyCotton   @HRAGANBC  @Joshua-Lakusta    Are we truly getting everything we need from SFAS? Which Data Do we need. Please let me know if we need to be integrating with SAIL directly for restrictions or scholastic standing etc

**Comment by HRAGANBC** [comment]
Replaced by #2685
