### ISSUE TITLE
Ministry Manually Re-Trigger Specific Workflow Steps 

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2731]
**Story Description:**
As a Ministry user, I want to be able to re-trigger specific steps within Camunda workflows so that applications which were processed in mistake can be re-processed properly without requiring the student to cancel and re-start their application. 

**Acceptance Criteria:**
On Ministry view of student assessment history screen, add buttons and confirmation modals for the following: 
- [ ] "Repeat Exception Adjudication" 
- [ ] "Re-trigger COE Request" 
- [ ] "Re-trigger eCert generation" 

**Context:**
Retriggering Exceptions could be useful when:
- Need to re-collect speciifc supporting information without wanting to re-submit entire application. E.g. school responded incrroectly to PIR, or parent provided inaccurate income information. 
- Ministry has declined or approved exception accidentally and the application must return to the Exceptions checkpoint with all the originally requested Exception requests. 
Retriggering COE Requests could be useful when:
- School has declined COE accidentally and the request needs to be re-issued, without having to re-submit the application and collect all supporting information again
Retriggering eCert Requests could be useful when:
- eCert file was rejected by NSLSC and SIMS needs to re-issue the eCert to be actioned by NSLSC

**Comment by michesmith** [comment]
Closing will be resolved with overhaul to change request.
