### ISSUE TITLE
Content change for Financial tab modifying other financial support header

### ISSUE THREAD

**Issue by Joshua-Lakusta** [bcgov/SIMS#2735]
**Describe the task**
Updating the header for a section of the financial tab based on policy unit request

**Additional context**
<img width="901" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTMvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--83cc1afe941c312c0b29b1d08278e8613143ff5e/image.png" alt="image.png" />

The highlighted is the header to be amended

**Acceptance Criteria**
- [ ] Update the header from "Other financial support" to "Other financial support and targeted resources"

**Comment by JerPearson** [comment]
These updates captured on another ticket[3845](https://app.zenhub.com/workspaces/student-information-management-system-5fce9df5aa1b45000e937014/issues/gh/bcgov/sims/3845)
