### ISSUE TITLE
FT and PT content - Dependent costs header in financial tab needs to be renamed

### ISSUE THREAD

**Issue by Joshua-Lakusta** [bcgov/SIMS#2738]
**Describe the task**
Update header for the "Dependent costs" section to "Child care costs" for both full time and part time applications.

**Additional context**
<img width="919" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUgvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9d273b4c66661f9243ba9b13cc17de2b1160c1ac/image.png" alt="image.png" />

Update the highlighted header

**Comment by michesmith** [comment]
@astridSABC will create a new ticket- Jeremy will connect with @Joshua-Lakusta to confirm any additional requirements
