### ISSUE TITLE
Ministry - Filter/Search Programs & Offerings

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#2741]
**User Story**
As a _ministry user_, I need to search for programs by more than just name within each institution to be able to (quickly) assist Institutions. This involves having a way to search for all institutions or search by institution location code AND being able to filter when viewing/searching programs when viewing the programs of an institution.

**Acceptance Criteria**

- [x] Update the Programs view for ministry users within an Institution (Figure 1):
    - [ ] Add sorting options to the fields to allow ASC/DESC (Program Name, Location name, Status[Pending,Approved,Declined,Inactive])
    - [ ] Add new search options to allow better filtering: Program Name AND Location name AND Status (multiple choice option) with search button
- [ ] If this component is shared with institutions, it's okay to update the institution side too.
- [ ] Search options for Status should load with all options selected. If none are selected, show no programs.
- [x] Sorting by status will change the default when the page loads (priority) to an alphabetical sort of the status names. 

**Business Context**
_Figure 1_
<img width="1427" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1YrQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8a9c7492b4faf4ffdd0f7dd7cea314d60ddb450c/image.png" alt="image.png" />

**Technical**
- [x] Create a new input to allow the search by the location name.
- [x] Create a multi-select drop-down (or similar) to allow filter multiple statuses. By default, all should be marked.
- [x] Add the search button.
- [x] All three search inputs will behave as an "and" logic if provided.
- [x] Convert the table to use Vuetify.
- [x] Sort program statuses as below (the below order was redefined during development by new business ACs).
  - Pending
  - Approved
  - Declined
  - Inactive
- [ ] Ensure at least one E2E will be present to test the data retrieval.

**Comment by CarlyCotton** [comment]
QOL: SABC code, filter by location, better searching options

**Comment by CarlyCotton** [comment]
Met with IPDT Aug 21 to confirm details of the enhancements in this ticket.

**Comment by andrewsignori-aot** [comment]
@CarlyCotton is there a particular order for the statuses?
- They are the below ones:
- Creation pending
- Approved
- Creation declined
- Change under review
- Change awaiting approval
- Change overwritten
- Change declined

**Comment by CarlyCotton** [comment]
@andrewsignori-aot Can we have options that align with the Status Tag that they can see for each program? Pending, Approved, Inactive, Declined

**Comment by CarlyCotton** [comment]
Updated the ACs to align with discussion today about MVP solution

**Comment by andrewsignori-aot** [comment]
@CarlyCotton @sh16011993 It is my understanding that based on a conversation between you two during development, the below decisions were made.
1. Statuses will be sorted in alphabetical order (including `Inactive`, which is not a real status in the backend but it is displayed to the user as if it is).
2. When no options are selected in the dropdown for the statuses, no items will be returned.

@CarlyCotton if the above ones do not represent the output of the conversation, please let me know, otherwise, please ensure these decisions will be persisted in the ACs. If they are and I am missing something, please let me know.

**Comment by CarlyCotton** [comment]
@sh16011993 I've updated the ACs:
<img width="944" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUNaQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--258e52323fb7f2a7343b91c49be4d901c56f6a08/image.png" alt="image.png" />

Please let me know if this is out of line with what we discussed or if I should clarify further.
FYI @andrewsignori-aot
