### ISSUE TITLE
Ministry User Views Institution Profile, and Tabs

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#277]
Vue (not formIO)
Separate API call for tabs

**As a** *(Ministry User )*
**I want** *(View an Institutions Account)*
**So That** *(I can look up information related to that Institution)*

### Prototype
https://www.figma.com/proto/VykmBDwobGoGvK9M5wgOvN/StudentAid-BC-App-Design-System---FreshWorks-Studios?node-id=6209%3A50222&scaling=min-zoom&page-id=5246%3A41267&starting-point-node-id=6209%3A50222

### Additional Context
- UX Ticket #773
- Master View- Ministry User Views Institution Account Details #770 
- Once an Institution account is successfully created, then it can be viewed by approved ministry users
- A ministry user will be able to see the details of an Institution Account. This will include profile information, designation, locations, programs, offerings, restrictions, users & notes
![image.png](https://images.zenhubusercontent.com/6047d6ac906f4ec904f7286c/53862ee5-5eb7-4fae-8ab7-42c187e06968)

### Acceptance Criteria
- [x] From the 'Find Institution page', The ministry user searches and selects for the Institution they wish to view, and they are directed to the Institution Details Page- US #76

### Institution details
On the Institution Details Page, the user will see:
- [x]  the Institutions 'Designation Status' next to the Institution Name
- [x]  The following 'Tabs': Profile, Programs, Locations, Users, Designation, Restrictions, Notes.

### Profile 
![image.png](https://images.zenhubusercontent.com/60c7d7040a42d68fb4abaa59/91b89115-6924-4894-9e22-3c38521952ff)
- [ ] Basic Profile Information Including Legal Operating Name, Institution Name, Type, Regulating Body, Primary Phone Number, Primary Email, Website _(Hyperlink to their website)_ Established Date
- [ ] Contact Information Including Primary Contact ( First Name / Last Name, Phone Number and email) Legal Authorized Authority Contact ( First Name / Last Name, Phone Number and email).
- Mailing Address ( Address 1, Address 2, City, Postal Code, Province, Country)

**Comment by courtneygringras** [comment]
Adding that this should include form fields for all three access areas (students, institutions, business) as consistency with forms is a current challenge we're hoping to solve with MOD.
