### ISSUE TITLE
Update NestJS version to the latest available

### ISSUE THREAD

**Issue by andrepestana-aot** [bcgov/SIMS#2774]
**Context**
There maybe new features and security issues fixed but one issue that this could resolved is that the current @nestjs/common version used doesn't have support for passing cause in the HTTP Exception:
Current used version: https://github.com/nestjs/nest/blob/v9.0.3/packages/common/exceptions/http.exception.ts
Latest version: https://github.com/nestjs/nest/blob/master/packages/common/exceptions/http.exception.ts

**Acceptance Criteria**
- [ ] Update NestJS Version.

**Comment by sslaws** [comment]
Closing as this will be done as part of Security updates related to Dependabot updates.
