### ISSUE TITLE
Adjust eligible dates validations on Application Submission and Request a Change submission (currently allowed up until end date) 

### ISSUE THREAD

**Issue by michesmith** [bcgov/SIMS#2776]
Current Behaviour:
- Applications can be submitted at any time. 
- Applications submitted on or after study end date will result in Exception being triggered and require Ministry approval
- Request a Change can be submitted anytime
- Request a Chnage submitted after study end date will generate a warning message to student indicating they may not be eligible; warning is also displayed to Ministry staff when reviewing request

**Expected Behaviour:**
Revise logic to apply warnings/exceptions _6 weeks prior to end date_ as opposed to _on or after end date_
- Applications can be submitted at any time. 
- Applications submitted within 6 weeks of study end date will result in Exception being triggered and require Ministry approval
- Request a Change can be submitted anytime
- Request a Chnage submitted within 6 weeks of study end date will generate a warning message to student indicating they may not be eligible; warning is also displayed to Ministry staff when reviewing request

**Comment by Joshua-Lakusta** [comment]
Tickets have been completed since and this ticket is obsolete. Other work to be done around application timing but this overall ticket is outdated and no longer useful. Closing due to duplicate work effort.
