### ISSUE TITLE
Content - Student Basic BCeID account creation

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2778]
Re-organize the steps currently displayed on student login landing page so that student is instructed to first create Basic BCeID and _then_ do remianing steps

<img width="692" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVlaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b161f25ee3f8fce4b31a2a827b0ca44ed5ccd65f/image.png" alt="image.png" />

**Comment by michesmith** [comment]
@HRAGANBC  Can you please connect with Jeremy and James on this one.

**Comment by michesmith** [comment]
Jeremy will be bringing a fresh ticket in with content and workflow feedback. Moving to close
