### ISSUE TITLE
POTENTIAL DUPLICATE of 2645: Programs - SABC Program Code Validation

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#2780]
**User Story**
As an _institution user_ I may need to have multiple programs with the same SABC program code. This could be due to changes in programs across program years.

**Current Behaviour**
When adding a new program, I am blocked from creating a new program with the same SABC program code as an existing program. 
<img width="1340" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzRaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--def1cf2e5caa87af81d1ecad3be1c8c010c8b992/image.png" alt="image.png" />

**Expected Behaviour**
Program validation with SABC Program Code being the same should not result in the new program being blocked IF the other program is in a "deactivated" state.

**Acceptance Criteria**
- [ ] Update program validation criteria. Remove requirement for unique SABC Program Codes.
- [ ] Update Bulk Upload to NOT match any offerings to programs with the same SABC program code and the "deactivated" state.

**Comment by CarlyCotton** [comment]
@HRAGANBC @Joshua-Lakusta Please review before we move to Lather. Seems straight forward and I've spoken with IPDT/Policy about this.

**Comment by Joshua-Lakusta** [comment]
Reviewed and agree based on our decommission of programs with the ZZDONOTUSE that we have to allow the repeated use of SABC codes.

**Comment by HRAGANBC** [comment]
@CarlyCotton - I think Devs will have a problem with this. The SABC program code is the singular validation used to link the Bulk Upload file with a particular program. I.e. the Bulk Upload file is a bunch of distinct offerings, and the Institutions need to input an SABC program code next to each offering to 'assign' it to a particular program. 

If we allow multiple SABC program codes, then Bulk Upload offerings will get automatically assigned to multiple programs. Is that acceptable to Institutions? If they're fine, I'm fine. 

Devs might have other concerns though

**Comment by CarlyCotton** [comment]
Removing as no longer necessary with #2645/2930
