### ISSUE TITLE
Patroni going into recovery mode after changing the credentials

### ISSUE THREAD

**Issue by guru-aot** [bcgov/SIMS#2783]
Patroni going into recovery mode after changing the credentials for workers, api, queue-consumers and load-test-gateway from superuser to database user.

<img width="1531" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDBmQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6a196f8102c2c835a01a308bd37a8e7ece77726f/MicrosoftTeams-image%20%286%29.png" alt="MicrosoftTeams-image (6).png" />

<img width="1604" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDRmQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--91051576a4f371120aeb39c77645e0acec796d43/MicrosoftTeams-image%20%287%29.png" alt="MicrosoftTeams-image (7).png" />

<img width="1816" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDhmQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--01b936e8ab8be4c66078bbfab1edcbc9f921b2ed/MicrosoftTeams-image%20%288%29.png" alt="MicrosoftTeams-image (8).png" />

**Comment by dheepak-aot** [comment]
pulling into sprint and added points as per @ninosamson

**Comment by guru-aot** [comment]
As part of the analysis done, the database in dev is going into recovery mode when assessment-workflow-queue-retry queue is running every hour. 

<img width="1367" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3BVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--01a3235854faff1332ace3969f718a981a945d35/image.png" alt="image.png" />


Points tested and analysis done:
1. This is not happening in test and is not repicable. 
2. Initially changed the permission of the database user accordingly of the superuser and tried to solve the issue, but this failed.
3. Changed the permission of the data folders/ changed ownership in patroni to have access to groups and still it fails.
4. Changed the database connection to super user and found it is happening for both the superuser and the databaseuser.
5. Completely removed the Patroni statefulset in dev with the PVC and other configurations and reinstalled new Patroni with Patroni-1 as leader. Still the error persists after db recovered from db recovery pod.
6. Running the sql that was causing the error in parallel execution of the assessment-workflow-queue-retry queue is not causing any failures in the pgadmin software. 
` SELECT "StudentAssessment"."id" AS "StudentAssessment_id"
FROM "sims"."student_assessments" "StudentAssessment"
WHERE "StudentAssessment"."student_assessment_status" = 'Cancellation queued'
    AND "StudentAssessment"."student_assessment_status_updated_on" < '2024-02-08T19:49:01.902Z'
 `
 [enqueueCancelAssessmentRetryWorkflows](https://github.com/bcgov/SIMS/blob/7dc491e6c32eb04ec422e5b492611fdd534ff24a/sources/packages/backend/apps/queue-consumers/src/services/workflow/workflow-enqueuer.service.ts#L147)

7. Actual error found in the queue consumer
<img width="1445" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnRVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7f0385e05dd8f986dbe39fe42fdb4d1be26d1d2b/image.png" alt="image.png" />

8. Kibana logs to check for further investigation 
 `
https://kibana-openshift-logging.apps.silver.devops.gov.bc.ca/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30m,mode:quick,to:now))&_a=(columns:!(message),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'8841c680-a15b-11eb-a4dc-e5bf19f04239',key:kubernetes.namespace_name,negate:!f,params:(query:'0c27fb-dev',type:phrase),type:phrase,value:'0c27fb-dev'),query:(match:(kubernetes.namespace_name:(query:'0c27fb-dev',type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'8841c680-a15b-11eb-a4dc-e5bf19f04239',key:kubernetes.pod_name,negate:!f,params:(query:patroni-1,type:phrase),type:phrase,value:patroni-1),query:(match:(kubernetes.pod_name:(query:patroni-1,type:phrase))))),index:'8841c680-a15b-11eb-a4dc-e5bf19f04239',interval:auto,query:(language:lucene,query:'%22FATAL:%20%20the%20database%20system%20is%20in%20recovery%20mode%22'),sort:!('@timestamp',desc))
 `
<img width="1344" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1JVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--706b6d3573499794a63d31f46339c58be40bdab2/image.png" alt="image.png" />

  Note: The patroni leader changed in the statefulset  from Patroni 2 to Patroni 1, that is the reason the screenshot and the search will have different patroni pod_name. As part of the analysis completely reinstalled it.

Possible Cause:

** The Data in the dev might be the reason that might cause this issue, to further investigate on the analysis a complete new db without any data from scratch can be used to test it**

**Comment by guru-aot** [comment]
Updating the query from typeorm to named query, solved the issue. This is due to the LessThan in typeorm is fetching all the data in the column and comparing the studentAssessmentStatusUpdatedOn. This causes the DB to go into recovery mode.
<img width="857" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOE5hQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1b9c1c9453b66dcb4226bc9d0773c7c3a75cbe0c/image.png" alt="image.png" />

**Comment by guru-aot** [comment]
As a part of the analysis the relationId in the db models created sub query creation, that causes DB to go into recovery mode. So removing it will enhance the queries performance and eventually make 50K records easily.

**Comment by guru-aot** [comment]
![image](https://github.com/bcgov/SIMS/assets/62901416/97cf1f2c-c102-4574-92c2-235d1cd5ea27)
