### ISSUE TITLE
Institution-Focused Report 

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2784]
Pull Institution Data directly (without dependency on student first)

Questions:
- Do we need it to be extractable by Institutions?

**Comment by ninosamson** [comment]
Propose deferring this to post-part time, as ad hoc reports can be generated for institutions quite readily.

**Comment by CarlyCotton** [comment]
Closing - there have been a number of reports created for institutions. Not enough information here to support leaving open for now. New reports may be created based on specific needs from institution users.
