### ISSUE TITLE
Additional Transport - Form Change (FT&PT)

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#2806]
Task:
To update the additional transportation form based on the following acceptance criteria.

**Acceptance Criteria**
- [x] Make the "Which of the following best describes you situation" question mandatory to be completed when "yes" has been selected for Do you want to be assessed for additional transportation costs
- [x] The option under "Which of the following best describes your situation:" needs to have the "Not required" option removed.
- [x] Wording update to the documents required section within the document uploader form. It must include the following "Documents Required" (see mock up below for how it should look)
-  A letter describing your situation to indicate why an exception should be made (including why you cannot move closer to your school)"
-  Copy of your vehicle insurance
-  All relevant supporting documentation (work schedule, clinical or practicum information, etc.)
- [x] Remove the duplicate information asking for the student to "estimate their weekly transportation cost" It appears below the uploader and is no longer required.

Business Context

**Current Behaviour**
When a student selects "Yes" to "Do you want to be assessed for additional transportation costs" a secondary question is triggered: "Which of the following best describes your situation?".
This secondary question is not listed as required, and once a selection is made (radio dials) it causes a document upload prompt to show with other fields (based on work in #1707)
This question currently doesn't show in the PT.
<img width="993" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEE3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--79ae98b8858141ae6e8b88e11f338ebbc4fbb0f0/image.png" alt="image.png" />

**Expected Behaviour**
This question should show in PT.
When a student selects "Yes" to "Do you want to be assessed for additional transportation costs", all supporting questions are displayed (which of the following, weekly costs, kms, number of weeks, practicum yes/no) and the document upload option should show up and be required.
The options under "Which of the following best describes your situation:" needs to have "Not required" removed.
<img width="882" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGM4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f81bb9127881f70156eb873a402b391d87b5f711/image.png" alt="image.png" />
The content under "Upload supporting documents" also needs to be changed:
<img width="910" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBek04QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8aee1580ce96f1c434a41e7f8df4f0ed23e3d328/image.png" alt="image.png" />

**Comment by CarlyCotton** [comment]
@Joshua-Lakusta I basically just matched the form much closer with the ask for documentation. Still open on what can be submitted, but is a little firmer in the ask for more documents to help appeals determine and references a letter.

**Comment by Joshua-Lakusta** [comment]
@CarlyCotton Looks good. The images are not working for me. Is the second image showing the new content for the doc uploader?

**Comment by CarlyCotton** [comment]
@Joshua-Lakusta Second image shows the change in the radio dial options and third shows the change to the document uploader text.

@HRAGANBC Please review the minor content edit with slight changes to the options on the form. Not strictly required but aligns much better with existing appeal app wording.

**Comment by HRAGANBC** [comment]
@CarlyCotton Looks great to me
