### ISSUE TITLE
Revise Logic for Student Accepting Assessments/Re-assessments

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2807]
Related to #2665 

**User Story**
As a Student, I must accept an assessment for each application so I understand what I'm agreeing to by sending it to the institution for confirmation.

**Description**
Revise the logic such that students will need to accept **at least one** assessments OR re-assessments, but any assessments or re-assessments generated after that, the NoA does not require accepting. 

**Acceptance Criteria** 
- [x] Require student to accept at least one NoA for every application, but anything after that (prior to complete status) does not require approval. 
- [x] For assessments where the NoA was already approved, and the application is _not_ completed, the workflow should set application status to 'enrolment'
- [x] If a student has not accepted ANY assessment yet and has multiple assessments: Only allow acceptance on the most recent assessment. Remove the ability to accept on the prior assessments.

**Current Behavior**
An assessment requires accepting; re-assessments do not. 
This leaves possibility of an automatic re-assessment happening prior to COE and immediately changing that NoA to 'accepted'. 
<img width="1041" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1E4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--70751680e454ba9a24e88a06689a78173c3cec19/image.png" alt="image.png" />

User Impact: Student has to potentially accept their assessment multiple times if automatic re-assessments or applications edits occur prior to enrolmet stage. Flip side is that student _does_ need to accept their assesment if there was an automatic re-assessment due to Program Year maximum spillovers

**Technical**

- [x] Load a new variable into Camunda (`load-assessment-consolidated-data`) to define if an NOA was ever accepted by the student for that application.
- [x] Adjust the NOA update in Camunda to reflect the suggested flow below.
<img width="1617" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3hVQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3ef63bb043410ece59445e69f3de08698b1e5764/image.png" alt="image.png" />
- [x] Remove the obsolete data being saved, as shown below.
<img width="900" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEJVQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--da08c0bf969e9e030470e72b350342063c031be2/image.png" alt="image.png" />
- [x] Prevent the user from accepting the NOA from an assessment that is not the application's current one. Remove the button from the UI and block the API.
- [x] E2E tests workflow and API.

**Comment by andrewsignori-aot** [comment]
Proposed alternative workflow changes keeping the workers generic.
<img width="1304" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTFKQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1389c7b04c3ee1c5731bc82ee5667e2f652200a8/image.png" alt="image.png" />

**Comment by andrewsignori-aot** [comment]
@HRAGANBC @CarlyCotton @Joshua-Lakusta Even after changing the workflow we may end up with multiple assessments with the NOA as required.
For instance
1. Student submits an application for the first time ever (NOA will be required).
2. Assuming that the student never approved the NOA from step 1, a "Manual reassessment" happens.
3. A new assessment will be generated and since the student never approved an NOA before it will be required.

The application tracker will display the most current assessment details but the history of the assessment will still display both NOAs in the history for the Student. Should we allow the student to approve the NOA just for the most recent assessment? I believe yes.

**Comment by HRAGANBC** [comment]
@andrewsignori-aot @CarlyCotton @Joshua-Lakusta 

Thanks
I would say yes, any NoAs which are now outdated should NOT be able to be accepted. Only the current NoA can be approved.

**Comment by andrewsignori-aot** [comment]
> @andrewsignori-aot @CarlyCotton @Joshua-Lakusta
> 
> Thanks I would say yes, any NoAs which are now outdated should NOT be able to be accepted. Only the current NoA can be approved.

Thanks for your reply @HRAGANBC. We will need a requirement for it.

**Comment by CarlyCotton** [comment]
@andrewsignori-aot @HRAGANBC 
I've added the following AC to clarify the expectation:

> - [ ] If a student has not accepted ANY assessment yet and has multiple assessments: Only allow acceptance on the most recent assessment. Remove the ability to accept on the prior assessments.

**Comment by andrewsignori-aot** [comment]
@CarlyCotton thanks for adding the AC. Please consider that it is more of a new requirement than a clarification and the DEVs agree to take care of it as per below technical AC in this ticket. If anything different is expected, please let us know.
"Prevent the user from accepting the NOA from an assessment that is not the application's current one. Remove the button from the UI and block the API."

**Comment by katrina-aot-git** [comment]
@HRAGANBC When blocking old assessments from being accepted, do you want _only_ the accept button to disappear, or do you want the full page in view only?

**Comment by HRAGANBC** [comment]
@katrina-aot-git 
Just block the 'accept' button, the rest of the page does not have to be converted to read-only
