### ISSUE TITLE
Disbursement File Code Type Mapping

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#2815]
**User Story**
When we receive disbursement confirmation via disbursement files (TEDU.PBC.DIS.DXXXXXXX.XXX) the award and loan amounts should be confirmed to the student via the assessment page.

**Current Behaviour**
We successfully read in the disbursements but nothing is displayed to the student for each award/loan.
<img width="1158" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2hJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7ee9776cec5801d5bce9dac8db12e43fe27f1fc0/image.png" alt="image.png" />

**Expected Behaviour**
We map the award type codes from the disbursement record to the ones expected in SIMS so we display the amounts for each award.
The loan amount is confirmed from the disbursement record and displayed.

**Acceptance Criteria**
- [x] Display the LOAN amount from the disbursement file (highlighted) as CSLP or CSLF depending on the file (PT or FT respectively):
<img width="950" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3BJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--53cfd5668a70abaf35051f68b7338d5bee837e75/image.png" alt="image.png" />

Note: The loan amount from disbursement file is saved in following column in `sims.disbursement_receipts`
<img width="1068" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejU5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f3884cede9b039d41a98166638a0b2e4c157b3b2/image.png" alt="image.png" />

- [x] Map the award codes from disbursement to their SIMS award counterpart (if no match, save value but do not display): 

- FT = CSGF
- TU = CSGT
- FTDEP = CSGD
- PD = CSGP

- [x] Update display on "Final Award" to show BGPD, SBSD, and/or BCAG if the BCSG that we sent on the ecert matches what was returned on the disbursement file (BCSG = BGPD + SBSD + BCAG (combined): *** if it doesn't match do not display anything "-"
<img width="827" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGhKQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d055c87ca172810bf97818ca1d1e992e09a5688a/image.png" alt="image.png" />
<img width="642" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHRKQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c4fe24099ff099c894a5b19e1fa701e267fe6e04/image.png" alt="image.png" />

- [x] Update the db and model comment for the column `total_entitled_disbursed_amount` and `total_disbursed_amount` in `sims.disbursement_receipts` to match the integration file specifications.
<img width="934" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenA5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f9e6440934a367f712d91e7c02db41815645a0f4/image.png" alt="image.png" />

- [x] Add E2E tests

**Comment by CarlyCotton** [comment]
@HRAGANBC @Joshua-Lakusta Please take a look and confirm if we know what LI, MI, PDSE are and if they need to be mapped to anything in the assessment.

**Comment by HRAGANBC** [comment]
@CarlyCotton 
LI = low income
MI = middle income
PDSE = Permanent Disability Services and Equipment.

**Comment by michesmith** [comment]
@CarlyCotton will answer this in a separate ticket

**Comment by andrewsignori-aot** [comment]
### Sample file used for demo
[DEDU.PBC.DIS.D2024130.001.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0s4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8e2d9f350b0cd62d1251751a7438679f5264af35/DEDU.PBC.DIS.D2024130.001.txt)

### Sample Part-time result
<img width="906" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2E4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d9dcfcf3ec94f2735a19501352ade584a2fc7ed7/image.png" alt="image.png" />

### Sample Full-time result
<img width="895" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2U4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9961516ee6fedeb61447897047fcab5f068034f5/image.png" alt="image.png" />
