### ISSUE TITLE
UI/ UX Research Student Restrictions 

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#282]
Review the Requirements for Restrictions
Institutions restriction?
Ministry Restrictions 

**Acceptance**
SME Interview Confirm Requirements in Confluence 
Determine Restriction Status Location
Visibility of Restrictions (Is it available to Students) How much transparency.
Knowledge Transfer to Team
Confirm Tech Feasibility 
Document Biz Rules
Workflow scenarios 
Sketch draft wireframe

*Additional Context*
- Check out confluence for research - sections 1.4 and 2.4.3 under themes

**Comment by roopfw** [comment]
Created some notes around restrictions that should help distill the conversation and decisions so far.

### [View notes here ➡](https://insidious-snow-19a.notion.site/StudentAid-BC-Restrictions-2a4068003b4246fe8ac73b40624f94a2)

### [View Figjam board here ➡️](https://www.figma.com/file/YIUEy1k5i9lQc1Miu4OIoB/Account-Restrictions?node-id=0%3A1)
