### ISSUE TITLE
Implement Camunda Impacts of Request a Change to Dependants

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2823]
**User Story**
As a _student_ who needs to update my dependants  I have requested a change to update my dependants. I will be re-declaring all of my dependants. 

**Acceptance Criteria**
- [x] If Dependent Request a Change form (#2775) is approved by Ministry, generate a new assessment with the new dependant information.  
  - Note: Handle the newly declared dependants approved through Request a Change exactly as it would be handled if submitted through initial application form. 
- [x] For Camunda, handle this new input of dependants like the other change request data by using a different prefix for it and checking during the assessment if it exists.

**Business Context**
- Related to #2775
- Any Dependants approved through Request a Change are 'effective' for entirety of study period and there is no prorating (i.e. a Child born mid-way through study period is handled same as one born before study period)

**Technical**
- [x] Change the `load-assessment-consolidated-data` to load the appeal data. Follow the same already in place for other appeals.
- [x] Use "Define dependants" script task and calculate the dependants.
  <img width="402" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTFuQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dbec4d285e5ee4de23c87171db238e53c20ae837/image.png" alt="image.png" />
- [x] The current `studentData` variables should be replaced along the entire workflow.
- [x] Follow the latest appeals process like `Additional Transportation`.
- [x] Add E2E tests following the tests for other appeals.

**Comment by michesmith** [comment]
@HRAGANBC finesse and move to lather

**Comment by CarlyCotton** [comment]
@HRAGANBC 

> How to handle casacading quesitons when new dependants are reported through Requesta Change? (I.e. do child ccare costs get invalidated? Does independant status change for single parent?)

The child care costs are validated within the assessment. However, if they have previously indicated that they did not have dependants they would not have had the option to declare child care costs. They also may need to update the costs based on a change to dependants. These questions are in the "Financial Information" tab:
<img width="1275" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVRVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--82e0731de1f8103529198c1ce5f113bf6fe50280/image.png" alt="image.png" />

Options: We can add another change request to dependant care costs, or add these questions into the dependants change request questions.


> - [ ] Confirm whether appropriate to give dependants for entire study period as opposed to pro-rate
This is a larger question for outside of the build of a change request.

**Comment by michesmith** [comment]
@HRAGANBC can you please elaborate on the changes being made moved back to 'Get the Soap"
