### ISSUE TITLE
Update to Youth in Care Question (content & radio option) 

### ISSUE THREAD

**Issue by michesmith** [bcgov/SIMS#2826]
**As a** *(Former Youth in Care Student)* **I want** *(to be notified of my Tuition Waiver eligibility )* **So That** *(I can make an informed decision about which program I can apply for. *

**Acceptance Criteria**

- [x] Revise: "Were you ever considered a child or youth...." to "Are you, or were you ever considered a child or youth under government care?"
- [x] Update tooltip content with the following:
"For a variety of reasons, the government may provide care or guardianship for a child or youth. Answer ‘YES’ to this question if you were ever considered a child or youth in the care of the Ministry of Children and Family Development (MCFD) or an Indigenous Child and Family Service Agency (ICFSA), in the Ministry of Social Development and Poverty Reduction [SDPR] Child in the Home of Relative Program, or in government care through a Canadian province or territory outside of B.C., This includes out of care and temporary care statuses, as well as continuing custody orders both in B.C. and in Canadian provinces or territories outside of B.C."
- [x] For PT only Hide the secondary question that populates to a "Yes" answer to the above question

- [x]  Add radio option called "Prefer not to answer". 
- [x] This new option should be treated **identically** to student answering 'no' for assessment and validation purposes
- [x] Save this value as a new value to the answer.
- [x] **Display Purple Information Banner in Application Form.** If student selects "yes" or "Prefer not to answer" display a banner message in the application which reads:
> 
> Based on your response, you may be eligible for the Provincial Tuition Waiver Program and the Learning for Future Grant. 
> 
> This means you could have your tuition and eligible fees paid for, and you could also receive an annual grant of $3,500 to cover additional education-related costs (e.g., textbooks, computers, supplies, etc.). 
> 
> To learn more about these financial supports, please visit the [StudentAid BC website](https://studentaidbc.ca/explore/grants-scholarships) or contact the Financial Aid Office at your post-secondary institution.

<img width="1174" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUhxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--87a0418b6d4916ee88080211c122dc2388b38e5b/image.png" alt="image.png" />

**Additional Context**
Provincial Youth in care Notification of Grant Eligibility - Need to notify former YIC students of their eligibly for Loan Forgivingness.

**Comment by CarlyCotton** [comment]
@Joshua-Lakusta Looks good. I added some additional info to clarify what type of banner we want for it. (Purple Info)

**Comment by michesmith** [comment]
@Joshua-Lakusta  go get the link to send the students to please

**Comment by michesmith** [comment]
@Joshua-Lakusta  go get the link to send the students to please

**Comment by CarlyCotton** [comment]
@Joshua-Lakusta I've added a link to our general purpose SABC "Grants, scholarships, and other financial supports" page which should be sufficient: https://studentaidbc.ca/explore/grants-scholarships

**Comment by JerPearson** [comment]
Question to be removed from app.  See ticket #3384

**Comment by HRAGANBC** [comment]
@JerPearson to merge #3353 into this ticket
