### ISSUE TITLE
Content- Single Parent Information on Application

### ISSUE THREAD

**Issue by michesmith** [bcgov/SIMS#2828]
**Question** Which Release does this belong to? 

**As a** *(Single Parent Student)* **I want** *(Feature/enhancement)* **So That** *(Value, why is this wanted, what is the user trying to accomplish)*

to make it more clear and to clearly show what it means to be a dependent right now the questions are in awkward position and are not user friendly so we need to take a look at updating the placement of these questions.

**Additional Context**
- enter text here
- enter text here

**Acceptance Criteria**
- [ ] Given (Context), When (action carried out), Then (expected outcome)
- [ ] Given (Context), When (action carried out), Then (expected outcome)

**Comment by HRAGANBC** [comment]
Absorbing into #2827
