### ISSUE TITLE
Confirm NOA accurately reflects the reassessment changes on behalf of a Request of Change 

### ISSUE THREAD

**Issue by michesmith** [bcgov/SIMS#2834]
**As a** *(User Type/Persona)* **I want** *(Feature/enhancement)* **So That** *(Value, why is this wanted, what is the user trying to accomplish)*

**Additional Context**
- enter text here
- enter text here

**Acceptance Criteria**
- [ ] Given (Context), When (action carried out), Then (expected outcome)
- [ ] Given (Context), When (action carried out), Then (expected outcome)

**Comment by HRAGANBC** [comment]
@michesmith This is duplicated by existing Request a Change tickets and NoA content review tickets
