### ISSUE TITLE
Accent characters getting translated during Institution file upload(Bulk Offerings | Bulk Withdrawal)

### ISSUE THREAD

**Issue by dheepak-aot** [bcgov/SIMS#2850]
**Describe the task**
During the effort #2504 we noticed a bug after updating the file reading with ASCII, the bug is that the accent characters like `áéíó` are being translated and saved to SIMS db.

NOTE: It is assumed that file integrations are not affected. But confirmation required on the same. 

**Acceptance Criteria**
- [ ] Find the root cause and fix this translation happening. Test with characters `áéíó`

**Comment by michesmith** [comment]
@JasonCTang 7 beats or 8 beats?

**Comment by andrewsignori-aot** [comment]
As stated in the [nodejs documentation](https://nodejs.org/docs/latest/api/buffer.html#buffer_buffer) when the encoding is set to ASCII the most significant bit will be unset causing the characters to be changed, as per the example below.
<img width="556" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDZEQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4ca8855643180358cf0bea3a9e813ff570c54b92/image.png" alt="image.png" />

The same would not happen it `latin1` is used as per stated by the documentation.

**Comment by andrewsignori-aot** [comment]
As per the meeting, @JasonCTang will schedule some time with IMB to try to settle the questions.
- Considering integrations through file upload and STFP(institutions, ESDC, etc.) is it ok to use regular ASCII (7bits) or can we use ASCII Extended/ISO-8859-1 (8 bits)?

**Comment by andrewsignori-aot** [comment]
### Files generated to the SFTP (`Buffer.from`)

While creating the files to be uploaded to the SFTP both `ascii` and `latin1` resulted in the same bytes.

|Char(áéí)|Encoding|
|---|---|
|UTF-8|195, 161, 195, 169, 195, 173|
|ASCII|225, 233, 237|
|Latin1(ISO8859-1)|225, 233, 237|

#### Sample file generated with UTF8

![image](https://github.com/bcgov/SIMS/assets/61259237/9e5d0806-1da5-4bf0-b11d-8d5083b7d062)

#### Sample file generated with ASCII and Latin1(ISO8859-1) where the same result was produced

![image](https://github.com/bcgov/SIMS/assets/61259237/69b9e648-9749-4e99-b6ce-88d929658052)

@JasonCTang FYI

**Comment by andrewsignori-aot** [comment]
@JasonCTang organized a meeting with IMB and there was some progress.
As per confirmed by Johnson, Harold:
"I’ve verified that I can load, store, display and extract those ASCII special characters (as 1 byte) with no problems, from an SFAS point of view, including doing merges/etc. with any SIMS data containing those characters."

@JasonCTang also checked with Finsatra and apparently, they would not support anything beyond ASCII 7bits (non-extended characters support at all).
We will have a new follow-up call to discuss the next actions.

Current assumptions
- File uploaded through SFTP can be handled by the Ministry including extended characters but Fisnatra would not be able to process them.

Questions to possibly lead further discussions.
- Should we somehow convert the bytes sent to the SFTP? One possible solution would be to remove the most significant bit following the same approach Nodejs buffer uses when defined for `ASCII` encoding.
- Can we keep files uploaded to SIMS allowing the extended ASCII (ISO8859-1)?
- How should we handle the files sent to the SFTP to the institution?

**Comment by andrewsignori-aot** [comment]
As per @JasonCTang conversation with Finastra, the direction from would be: "They want any accented letters to be converted into the non-accented version of the character.".

That triggers the question of what to do with other non-Finastra files, for instance, ESDC SIN validation. If we apply the same conversation, will the SIN validation continue to work as expected?

**Comment by andrewsignori-aot** [comment]
The last conversations with @JasonCTang led to the below conclusions.
- Files generated by SIMS should follow ASCII (7-bit) only.
- Files uploaded to SIMS by institutions may receive ASCII extended (8-bit/latin1/ISO8859-1 or other if the Ministry desires).
- SIMS must be adapted to convert all data for files generated into ASCII (7-bit).

### Conversation to  ASCII (7-bit)

1 - Set the most significant bit to 0 in the same way described in the nodejs documentation ([source](https://nodejs.org/api/buffer.html)).
_'ascii': For 7-bit ASCII data only. When encoding a string into a Buffer, this is equivalent to using 'latin1'. When decoding a Buffer into a string, using this encoding will **additionally unset the highest bit of each byte before decoding as 'latin1'**. Generally, there should be no reason to use this encoding, as 'utf8' (or, if the data is known to always be ASCII-only, 'latin1') will be a better choice when encoding or decoding ASCII-only text. It is only provided for legacy compatibility._
2 - Create a conversion table to translate the most common characters as much as possible, for instance, `áâã` would be translated to `a`.
3 - Convert any byte over 127 to unknown characters, for instance, "?" where a string like `André` would be converted to `Andr?`.

As per the conversation, the desired approach would be a combination of approaches 2 and 3.
