### ISSUE TITLE
SFAS/SAIL Student Data Match/Import Note

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#2852]
**User Story**
As a ministry user, I want to know when there was a successful match between a student's SIMS profile and SFAS/SAIL. so that they know that it is successfully matched so that they can determine if they want to go to the Legacy System to see prior program year awards, restrictions, maximums and notes from Legacy Systems

**Expected Behaviour**
On first import of data or data match with SFAS/SAIL, a note will be placed on student account that is viewable by ministry users to confirm a match was made/data was transferred.

**Acceptance Criteria**
- [ ] Add 'general' note to student profile during **account creation** when match occurs to indicate other data exists from outside of SIMS for student.
_"Successful match with legacy systems - data has been transferred"_

**Technical**
- [ ] Create a new note for the Student in the centralized student account creation method ([source reference](https://github.com/bcgov/SIMS/blob/main/sources/packages/backend/apps/api/src/services/student/student.service.ts#L173)).
- [ ] Use the system user to create the new note to make it clear in the Notes UI that it was a system-generated note.
- [ ] Use the already-in-place centralized method for creating the student note.

**Comment by Joshua-Lakusta** [comment]
Modified the AC from First match to only on account creation. Can further discuss future tickets or manual processes for other match scenarios.
