### ISSUE TITLE
UX- User Research Approach

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#286]
- [ ] Develop User Research Approach

Broken into User Research Schedule in other tickets
What method
What  date
Who specifically 
What Questions are we asking?

**Comment by roopfw** [comment]
Draft 1: https://docs.google.com/document/d/1SZ2PvDVwMETNcxlXzBWzeYc0LhhFcoOHCgEvFl_o26I/

**Comment by roopfw** [comment]
Outstanding Sections:

1. Priorities Section
2. Test 1 Scenarios
