### ISSUE TITLE
Updates to Provincial Daily Disbursement - Import Data Changes

### ISSUE THREAD

**Issue by dheepak-aot** [bcgov/SIMS#2869]
**Story Description**
As a Ministry of Finance partner, I want to receive a daily summary log of all disbursements which were issued the previous day in SIMS, so I can keep my accounting records up to date. 

**Acceptance Criteria**
- [x] Ensure the following data from EDU.PBC.DIS.yyyyjjj.001 file is captured in each report. (**See mockups for mapping**).
- FT BC loans (DISB-TOT-DISB-AMT, total Federal or BC loan disbursed amount).
- FT BC grants (DISB-TOT-GRANT-DISB, total Federal or BC grant disbursed amount).
- FT BC total (SUM of the above two fields, i.e. FT BC loans + FT BC Grants).
- PT BC Grants (DISB-TOT-GRANT-DISB - total Federal or BC grant disbursed amount).
- **File Date (NEW)** (Row 11 in File Layouts) (Note: this reflects the date when the NSLSC file was produced).
- **Batch Run Date (NEW)** This should correspond to the date the disbursement receipts were received through EDU.PBC.DIS.yyyyjjj.001. 
- **Sequence Number (NEW)** (Row 10 in Excel) (Note: this reflects sequence number **as produced by NSLSC report**.
- [x] Persist the file date and sequence number to the database (to assist with troubleshooting when file creation fails).

**Business Context:**
**EDU.PBC.DISyyyyjjj.001 File Layouts**
<img width="1076" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWMyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1d10457c836854c1bbd9ce68d0d1bcff458a8303/image.png" alt="image.png" />

**Funding Totals Mapped to PBC.EDU.DIS.yyyyjjj.001 "Receipts File":**
<img width="1119" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVRhQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2a2ecaef0a2200372571c7928b934b62df416cbc/BC%20Funding%20Totals.jpg" alt="BC Funding Totals.jpg" />

**Technical Context**
Currently we have a scheduler `fin-process-provincial-daily-disbursements-integration` which runs daily and creates Provincial Daily Disbursement report and uploads the report to SFTP location.

Save data in database, generate email as needed, and email or report can be re-generated on demand in case of issue. 

Current Report looks like this:
<img width="581" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0I3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eee1f8ff455c56c5393f5f7fd36689da12e8c439/image.png" alt="image.png" />

**Technical**
- [x] Validate if the existing ones are the desired ones (e.g. are we already saving `DISB-TOT-DISB-AMT`, `DISB-TOT-DISB-AMT`, `DISB-TOT-GRANT-DISB`).
- [x] Adapt the process of importing the receipt file to save the new fields. Source reference for the existing import process: [source reference](https://github.com/bcgov/SIMS/blob/ad90b45f690478e397fb360d52dd280d99d52b1c/sources/packages/backend/libs/integrations/src/esdc-integration/disbursement-receipt-integration/disbursement-receipt.processing.service.ts).
  - [ ] Created a DB migration to insert new data
    - [x] File date (to be checked the origin - probably DISB-CREATE-DT), if not time is present ensure that a date-only filed will be created on DB and also mapped on the DB model as date-only.
    - [x] Sequence number (number - DISB-SEQ)
- [x] E2E test

**Comment by HRAGANBC** [comment]
@HRAGANBC to precisely map specific award types as displayed through Receipt file formatting into ACs to avoid miscommunication

**Comment by andrewsignori-aot** [comment]
> * FT BC loans
> * FT BC grants
> * FT BC total
> * **PT BC Grants (NEW)**
> * **PT BC total (NEW)**
> * **BC Total (FT+PT) (NEW)
> * Total # of records
> * **File Date (NEW)** (Row 11 in File Layouts) (Note: this reflects the date when the NSLSC file was produced)
> * **Batch Run Date (NEW)** This should correspond to the date the disbursement receipts were received through EDU.PBC.DIS.yyyyjjj.001.
> * **Sequence Number (NEW)** (Row 10 in Excel) (Note: this reflects sequence number **as produced by NSLSC report**

@HRAGANBC I was not referring to the trailer information. My point was that we have total grants described award per award (DISB-GR-TYPE and DISB-GR-AMT) and we also have the total for each disbursement (e.g. DISB-TOT-DISB-AMT, DISB-TOT-GRANT-DISB) and we also have total entitled, total paid for to the student and total paid for the institution.

So, can we assume that the below ones are the ones that we will SUM per offering intensity?

- FT BC loans (DISB-TOT-DISB-AMT - total Federal or BC loan disbursed amount)
- FT BC grants (DISB-TOT-GRANT-DISB - total Federal or BC grant disbursed amount )
- FT BC total (Is it the SUM of the above fields)
- PT BC Grants (same data as FT above)
- PT BC total (same from PT BC Grants since there are no loans for BC Part-time)
**BC Total (FT+PT) (NEW)
