### ISSUE TITLE
PT Lifetime Maximum - Assessment Calculation

### ISSUE THREAD

**Issue by ninosamson** [bcgov/SIMS#2872]
**User Story**
As a _part-time student_ I am eligible to have a maximum outstanding loan (CSLP), excluding interest, and should not be assessed for more than what I have available.

**Acceptance Criteria**
- [x] When assessment is started, load most recent monthly loan balance from federal file.
- [x] **Add federalAwardCSLPAmount** calculation and update the calculation to take into consideration the "monthly report balance" from #2694.
```
federalAwardCSLPAmount = 
dmnPartTimeAwardAllowableLimits.limitAwardCSLPAmount - "monthly report balance"
```
- [x] Update **federalAwardNetCSLPAmount** calculation to check against the new calculation federalAwardCSLPAmount instead of itself.
```
federalAwardNetCSLPAmount =
MIN(federalAwardCSLPAmount, calculatedDataTotalRemainingNeed4)
```
- [x] At the time of ecert creation check if CSLP has reached lifetime maximum (if most recent "monthly report balance" + CSLP being disbursed<= total lifetime limit)
    - If it is <= then proceed as normal through ecert process
    - If it is > : do not include record in the daily ecert and only send ONE email and continue to block
- [x] Treat this as a blocked disbursement and send the email for blocked disbursements to ministry
- [x] Ensure Ministry triggered manual reassessments use the most recent monthly loan balance from the federal loan balance file.

**Technical**
- [x] Use the above-mentioned codes as a reference. Check if `calculatedDataTotalRemainingNeed4` is the best reference or we can execute the logic, for instance in `finalFederalAwardNetCSLPAmount` calculation.
- [x] Load the total balance value using the same worker used by program year maximums (`Verify assessment calculation order`).
- [x] e-Cert validation should happen at the same e-Cert validations step only for `part-time` ([source reference](https://github.com/bcgov/SIMS/blob/main/sources/packages/backend/libs/integrations/src/services/disbursement-schedule/e-cert-processing-steps/validate-disbursement-part-time-step.ts#L23)).
- [x] During e-Cert verification check current life-time balance + the CSLP estimated value (`value_amount` column).
- [x] Save the `dmnPartTimeAwardAllowableLimits.limitAwardCSLPAmount` to the `workflow_data` under a new category called `dmnValues` (or similar) to allow the limit calculation at thee-Cert time.
- [x] E2E tests
  - Worker changes to ensure the new balance total is returned to Camunda when a student has some balance.
  - Camunda workflow consuming the new value for a part-time assessment.
  - e-Cert generation blocked by the amount exceeding the limit.

**Business Context**
We correctly assess the maximum possible loan for PT students based on need and check that we do not provide them with more than the lifetime limit for loan.
We do not consider any current loan balance that they have.
The ministry receives a monthly report that shows the outstanding loan and we know what the lifetime limit is.
<img width="864" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG1JQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4d54540d0dbbf4a584abd03638f377f8c52bd6d9/image.png" alt="image.png" />

We need to assess the maximum award allowable based on the monthly report.

**Comment by CarlyCotton** [comment]
@HRAGANBC @Joshua-Lakusta Please review. I've added the additional ecert validation step so we don't have every first app FULL reject. 

Alternatively, we could request a more automatic solution. SIMS can check at the time of ecert generation if there is a difference between the "monthly loan balance" used in the assessment. If a difference exists, use the new information and reassess. This may require some additional messaging/trackers/etc to indicate why numbers have changed (similar to the reassessment due to related app).

**Comment by andrewsignori-aot** [comment]
@CarlyCotton regarding the AC "At the time of ecert creation check if CSLP has reached lifetime maximum", the CSLP used for the calculation will be the estimated one, right?
For instance, if there are possible Overawards that would impact the CSLP final value it would not be considered to block the disbursement, right?

On a side note, if I am not wrong SAIL does not have Overawards but SIMS was built considering that Part-time would possibly have it.

**Comment by CarlyCotton** [comment]
@andrewsignori-aot 
Yes, the CSLP used to check against the lifetime maximum will be the estimated one from the Camunda assessment PLUS the monthly loan balance.
