### ISSUE TITLE
PT Assessment - Dependant Calculation (Newborn)

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#2875]
**User Story**
As a _student_, if I have a dependant born _after_ my study start date but before the study end date, they need to count as a dependant towards family size and eligible dependants for childcare.

**Acceptance Criteria**
- [x] Update the camunda dependent calculations to validate if dependent is born on or before study end date. If born after study end date exclude the dependent. 
    - [x] Calculate Eligible Dependents
    - [x] Calculate Eligible Dependents for Child Care Cost

**Technical**
- [x] Create a new Camunda variable `calculatedDependants` to be processed before "Calculate Eligible Dependents".
- [x] Use the new `calculatedDependants` in every place where `studentDataDependants` was used, for instance, but not limited to, "Calculate Eligible Dependents" and "Calculate Eligible Dependents for Child Care Cost".
- [x] Add a new E2E scenario where some dependents will be filtered for the eligible ones.
  - Consider changing the `createFakeStudentDependentNotEligible` to include one more scenario and one more parameter that would allow a dependent to not be eligible based on his birthdate.
  - Ensure that at least one E2E scenario will cover the changes for "Calculate Eligible Dependents".
  - Ensure that at least one E2E scenario will cover the changes for  "Calculate Eligible Dependents for Child Care Cost".

**Current Behaviour**
The system will allow a dependent to be included in the less then 12 years old  category and be counted as a dependent. However, the system does not validate if the dependent was born within the study period. 

Example: I could added a dependent born in 2030 and it would count in our calculations as a valid dependent under 12.

**Expected Behaviour**
We want the system to continue to count dependents with negative age as it does now. However, we, need the system to confirm that the date of birth does not happen after the study end date.

Example: 
Child DOB: Feb 1, 2024 included even though after start date but before end date
Child DOB: Feb 1, 2023 included as it was born before start date
Child DOB: Feb 1, 2030 excluded because born after end date

Study Start Date: Jan 15, 2024
Study End Date: Feb 28, 2024

Valid Dependants: 2

**Comment by Joshua-Lakusta** [comment]
@CarlyCotton please take a look and review.

**Comment by CarlyCotton** [comment]
@Joshua-Lakusta Looks great. Lather worthy!
