### ISSUE TITLE
Student Reassessment Status on Tracker

### ISSUE THREAD

**Issue by michesmith** [bcgov/SIMS#2877]
**As a** *(Student)* **I want** *(to know the status of my reassessment)* **So That** *.....

**Additional Context**
- enter text here
- enter text here

**Acceptance Criteria**
- [ ] Given (Context), When (action carried out), Then (expected outcome)
- [ ] Given (Context), When (action carried out), Then (expected outcome)

**Comment by michesmith** [comment]
sorry if this is a duplicate.

**Comment by CarlyCotton** [comment]
@michesmith Can you take a look at #2673 (Student application tracker adjustments for new assessment trigger type) and see if this covers what you expect of this ticket?

**Comment by CarlyCotton** [comment]
Closing as a duplicate as mentioned above,
