### ISSUE TITLE
Institution and Ministry Edit Institution details

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#288]
**Additional Context**
Based on the outcome of #331
Review page layout

**Acceptance Criteria**
**A ministry user can edit all institution details**
- [x] A ministry user can click "edit" on the "ministry views institution profile" page
- [x] On click of edit display the institutionprofile form in editable format
![image.png](https://images.zenhubusercontent.com/5fce9c77aab275719112dc74/1d44d7c5-16f2-4451-a0d8-803df9a5d7d8)
**Remove fields**
- [x] Remove Legal Authorized authority from institution details and institution creation forms as its now a role (institutionprofilecreation & institutionprofile)
- [x] Clean up DB and API

**An institution user edits institution information**
NOTE: The following apply to edit only, initial setup remains as-is (FirstName & LastName & Institution Information readonly and remaning need to be completed by institution)
- [x] Institution Details - An institution cannot edit the following fields 
- Legal Operating Name
- Operating Name
- Institution Type
- Institution Regulatory Body
- Established Date
- Primary Email
- Primary Phone Number
- Institution Website
- [x] Institution Details - An institution can edit the following fields 
- Primary Contact - Name
- Primary Contact - Email
- Primary Contact - Phone
- Mailing Address (all fields)

**Comment by IrenaMilosevic1** [comment]
Approved.
