### ISSUE TITLE
Patroni going into recovery mode

### ISSUE THREAD

**Issue by guru-aot** [bcgov/SIMS#2885]
**As a** *developer* **I want** *to have Patroni DB stable* **So That** *we can have a stable environment*

**Additional Context**
- As a part of ticket #2783 we found one query was getting the Patroni DB into recovery mode, this was caused by the relationId between the tables. So tried to remove as much as relationId from the code base.
- Created one more story #2853 for additional removal of relationId between db models which have references and test case failures.

**Acceptance Criteria**
- [ ] Analysis on why patroni db is going to Recovery mode for volumes like 50K or more when tables have relations.
- [ ] Possible solutions

**Comment by michesmith** [comment]
Closing as not able to replicate the bug
