### ISSUE TITLE
Bug - Mass offering change cannot be approved

### ISSUE THREAD

**Issue by Joshua-Lakusta** [bcgov/SIMS#2894]
**Describe the Bug**
When completing the approval for a mass offering change in the ministry portal an error message is received when approving. This was tested with the student application in the following states:
- in progress
- completed
- confirmation of enrollment (assessment accepted)
- assessed but not accepted
All of the states create the error when attached to the offering.

**Expected Behaviour**
Should allow a ministry user to approve a mass change of an offering and reassess attached applications. It should function the same as individual offering changes.  

**Actual Behaviour**
Error message being created when approving the change and no reassessments occurring.

**Steps To Reproduce**
Preconditions:
Have Ministry account access
Have Student account that has an application at the assessment phase (assessment not accepted)
Institution account that holds the program and offering that is attached to the student application but no other student applications
Suggest having a different offering for each mass offering change test

Steps:
Institution portal
Go to the program holding the offering attached to the student application you will be monitoring
Select edit next to the offering
select edit options top right
select request change from the drop down
modify the tuition amount
Click request change on the bottom

Ministry portal
Go to offerings under institution requests on the left side
Find your change request and click view request
Click approve reassessment in the top right corner

Student
Application should be reassessed in the system

Additional context

Confirmation that this was still a bug was requested. Created multiple apps at different states and tried to mass reassess with a mass offering change. Change was able to be submitted and reach ministry but upon approved the following error occurs.

<img width="1720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEk4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2d31b2b68dbf4de9a58cc3beb1d97628eec3fb63/image.png" alt="image.png" />

**Technical**

- [x] Ensure that `application.currentAssessment` is populated or update the current basement using a `repor.update` method ([source code reference](https://github.com/bcgov/SIMS/blob/e8dc452c773c5a01c63c2072f98f668e328a6568/sources/packages/backend/apps/api/src/services/education-program-offering/education-program-offering.service.ts#L1172)).
- [x] Create E2E
  - Approving a request with a completed and in-progress application, checking if the reassessment was created and the in-progress was canceled.

**Comment by HRAGANBC** [comment]
@Joshua-Lakusta Can you please check to ensure this is still a bug?

**Comment by Joshua-Lakusta** [comment]
@HRAGANBC see additional context where i went and retested this again and please see accompanying screen shot showing it still produces an error.

**Comment by andrewsignori-aot** [comment]
Along with the development of #3025 @katrina-aot-git and I were able to reproduce this and it seems that it will fail only if there is at least one application that is not completed which will make the process to try to cancel it and fail while trying it.
Which also means that the process should work when there are only completed applications impacted.
