### ISSUE TITLE
UX- Define Institution Roles

### ISSUE THREAD

**Issue by roopfw** [bcgov/SIMS#291]
**Describe the task**
Admin vs Regular Users Definitions

Check in with Robin and Danna on their work to see if it still makes sense for our new world

**Comment by courtneygringras** [comment]
Need to combine process outlined by dev with roles outlined by business. Attempting to find doc with the business' ideal roles and determine how to support them for MVP.

**Comment by courtneygringras** [comment]
[https://app.zenhub.com/files/319429847/39855874-a375-4599-8cad-350d023196fe/download](https://app.zenhub.com/files/319429847/39855874-a375-4599-8cad-350d023196fe/download)

**Comment by courtneygringras** [comment]
Draft of roles for review attached above. Only area not completed is the New FAO functionality the business is hoping for.

**Comment by courtneygringras** [comment]
Updated sheet to reflect language shift from Appendix 3 -> Program Information Request
