### ISSUE TITLE
SIMS to SFAS Bridge File

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#2912]
### ***Story Description***
As **a SFAS system administrator,** I want to receive data from SIMS to correlate with the data in SFAS. This requires creating a bridge file to communicate SIMS data to SFAS so that SFAS can enforce rules and limits in its own system.  

## Acceptance Criteria
**File Specification**
- [x] Create a file to send to SFAS that aligns with the layout (see Business Context) in the file 
- [x] Each file will have the following naming structure, which will allow for multiple files per day if needed.
  - “SIMS-TO-SFAS-YYYYMMDD-HHMMSS.TXT”
    - YYYY = year of extract date
    - MM = month of extract date
    - DD = day of extract date
    - HH = hour of extract date
    - MM = minute of extract date
    - SS = second of extract date
  - Eg:   “SIMS-TO-SFAS-20240205-153236.TXT”
- [x] The destination of the file will be on the SIMS SFTP server, in the /OUT folder
- [x] The bridge file will be a flat text file encoded in ASCII .
- [x] The job will be run from a queue every 4 hours, schedule should be modifiable, time starting at midnight.
- [x] Field formatting:
    - Dates: All dates will use the format yyyymmdd
    - Dollars: All dollar amounts will but 10 digits long with the last 2 digits representing cents, e.g. “0000080000” for $800.00

**Records to Include**
- [x]  Include student as a record on this file if one of below conditions are met since the last execution of this file:
   - Only send after student submits application AND any time a new record is inserted or an existing record is updated in any of the table that contain the fields in the bridge file.

- [x] **Application records:**
  - ONLY include application records for a student if there is new or updated application information for the student. 
  - Only included submitted applications. 
  - If there are updates to multiple applications for a single student, include one record for each application. 
  - If there are no new or updated applications for a student, do not include any application records for the student. 
  - Include an application record for a student for each application that is:  
    - Newly submitted. 
    - An existing application that has been reassessed. 
    - Has had disbursement status and/or data updated. 
- [x] For PIRS: Can use start/end date submitted by student. When offering is attached, use the start/end dates from offering (which means if the dates change it's a change)

- [x] **Restriction Records:**
  - Anytime a student is included in the bridge file, include PROVINCIAL restriction records for the student. 
  - If a student has had new or updated account/application information, include restriction records for the student even if there are no new or updated restriction records.  
  - If there are new or updated restrictions for a student, include a record per restriction for the student. 
  - If there are no restrictions for a student, do not include any restriction records for the student. 
- [x] If any information has been created or updated for a student, regardless of the category, include an account information record for the student. 

- [ ] Ensure that we can map our funding type produce the information to match what SFAS expects
<img width="832" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2U0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4f455214ea06a170308dc2f3d1a18c093fa762a3/image.png" alt="image.png" />

## **Business Context**
**Full File Specifications and Ongoing Comments** https://bcgov.sharepoint.com/:w:/r/teams/00371/Shared%20Documents/General/b)%20Development%20and%20Testing/SIMS%20Business%20Requirements/Under%20Development%20Requirements/SIMS%20to%20SFAS%20Data%20Bridge.docx?d=w588bf9022725400f998ea8cce1c27448&csf=1&web=1&e=JvpAU1

**Technical**
**The decision to break this ticket into Applications and Restrictions.**

Reference: Before starting to work on this ticket, please take a look at the following PR description to know what has been already implemented and set up in place for this implementation. Most importantly the `TECHNICAL CONTEXT PART`.

https://github.com/bcgov/SIMS/pull/3829 

- [x] Query1: Build a query to return application record data when there is one or more updates in the following tables. As a part of query result, student ids of application students must be returned.
**Note**: Please re-consider during development that watching disbursement schedules and disbursement values tables are required.
 - `sims.applications` 
 - `sims.student_assessments`
 - `sims.disbursement_schedules`
 - `sims.disbursement_values`
 CRITERIA: Application with current assessment and not in `Overwritten` status. Consider only delta changes.
- [x] Query2: Build a query to return restriction data when there is one or more updates in the following tables. As a part of query result, student ids of application students must be returned.
 - `sims.student_restrictions`(Only for provincial restrictions)
 CRITERIA: Consider only  provincial restrictions(include inactive ones as well).
- [x] Both the queries can be executed in Parallel.
- [x] Append the list of student student ids from Query1 and Query2 to the unique student id builder [sims-to-sfas.processing.service](https://github.com/bcgov/SIMS/blob/7eedbb51039cd315ceb5db05b24ae4bf8c07243f/sources/packages/backend/libs/integrations/src/sfas-integration/sims-to-sfas.processing.service.ts#L55)
- [x] Create file line objects for application and restriction records.
- [x] Create append methods for application and restriction records in the file line builder. [sims-to-sfas-file-line-builder](https://github.com/bcgov/SIMS/blob/7eedbb51039cd315ceb5db05b24ae4bf8c07243f/sources/packages/backend/libs/integrations/src/sfas-integration/sims-sfas-files/sims-to-sfas-file-line-builder.ts#L50)
- [x] E2E Tests are in place for file with student records. Either enhance the existing test with application and restriction data or add new tests. 
- [x] Ensure that the demo has an initial file generation and a delta file generation.
Hint: Please search in code for `TODO: SIMS to SFAS` to see all the areas required for code update.

**Comment by CarlyCotton** [comment]
SBSD/CSG-Disability - These two need to be highlighted for FT/PT limits being shared.

**Comment by Joshua-Lakusta** [comment]
Outstanding:
- award mapping for SIMS produced labels
- any other questions on file
- more alignment of AC's to the context for clarity

**Comment by andrewsignori-aot** [comment]
@JasonCTang the criteria to have a student added asks to only include the ones with "application submitted".
The criteria for adding an application is that the assessment must be calculated. Should we consider the same for the student also, which means, include students with an application submitted and assessed?

**Comment by andrewsignori-aot** [comment]
@JasonCTang should we not include submitted applications without assessment data (no awards) to allow the application overlaps?

**Comment by JasonCTang** [comment]
> @JasonCTang should we not include submitted applications without assessment data (no awards) to allow the application overlaps?

Ok, so let's include submitted applications that haven't been assessed yet.

**Comment by JasonCTang** [comment]
> @JasonCTang should we not include submitted applications without assessment data (no awards) to allow the application overlaps?

We have decided to include applications that have not been assessed. (See below.)  So include students with submitted applications and include applications that have been submitted (regardless of assessment status)

**Comment by andrewsignori-aot** [comment]
@CarlyCotton when the application was requested and needs a PIR, we will not have values like start and dates. Is the expectation to just send start and end dates blank?

**Comment by andrewsignori-aot** [comment]
@CarlyCotton about SIMS restrictions, we will be sending only current active restrictions.

**Comment by CarlyCotton** [comment]
@andrewsignori-aot 
>when the application was requested and needs a PIR, we will not have values like start and dates. Is the expectation to just send start and end dates blank?

Can we use the start/end dates that the student submits? As long as a delta change from a PIR being attached would then update the dates (if necessary).

@dheepak-aot 
>while generating the restriction data records, should we should refrain from sending SINR restrictions right?

Can we send all provincial restrictions? They can determine which ones they need to action.

**Comment by dheepak-aot** [comment]
_Can we use the start/end dates that the student submits?_ (Discussed with @andrewsignori-aot ) - Yes. Can you please add this context to the file documentation and also mention in AC?

**Comment by guru-aot** [comment]
As discussed with @CarlyCotton, we had a question whether to send CSGP and SBSD total awards as 0, for cancelled applications, but the outcome was to send the awards as it is and SFAS can handle it.

**Comment by guru-aot** [comment]
The reason for not looking into the disbursement_schedules and the disbursement_valuesis because the change in the awards will never happen after the saveDisbursement(As the first entry to the disbursement_schedules table happens here) step mentioned below. Even if there are any updates that are happening in the workflow, those are captured by the student_assessment table and the applications table changes updated_at. This was already captured while trying to fetch the changes.

![image](https://github.com/user-attachments/assets/49c159ab-2c3d-4387-b74a-580aca644f1d)

**Comment by guru-aot** [comment]
Attaching sample file from demo
[SIMS-TO-SFAS-20241118-175815.TXT](https://github.com/user-attachments/files/17804524/SIMS-TO-SFAS-20241118-175815.TXT)
[SIMS-TO-SFAS-20241118-180321.TXT](https://github.com/user-attachments/files/17804525/SIMS-TO-SFAS-20241118-180321.TXT)
