### ISSUE TITLE
Student can view and download their T4A

### ISSUE THREAD

**Issue by michesmith** [bcgov/SIMS#2929]
**As a** *(Student* **I want** *(View and Download my T4A)* **So That** *(I can have my grant and loan information for CRA files)*

**Additional Context**
- enter text here
- enter text here

**Acceptance Criteria**
- [ ] Given (Context), When (action carried out), Then (expected outcome)
- [ ] Given (Context), When (action carried out), Then (expected outcome)

**Comment by HRAGANBC** [comment]
Replaced by #2994
