### ISSUE TITLE
Institution/Ministry - Deactivate Program - Constraints

### ISSUE THREAD

**Issue by andrewsignori-aot** [bcgov/SIMS#2930]
### **User Story**
As an _Institution or Ministry User_, I may need to deactivate a program. This could be due to no longer offering it, or creating it in error resulting in a new revised program being created. This ticket assumes that UI is already implemented and its focus it to apply the constraints and validations to prevent further activity in the program.

### **Acceptance Criteria**
- [ ] Remove deactivated programs from any program lists: Student Application, PIR, Request an Offering/Program Change
- When student 'edits' an incomplete application, the deactivated program should be removed from the form and no longer viewable/selectable within the dropdown. 
- [ ] Prevent new offering to be added to a deactivated program (scholastic standing clones _can_ be added to deactivated program)
  

**Technical**

- [x] Retrict the below data retrieval do not include inactive programs.
  - [x] Student applications programs dropdown while creating new applications. Applications already submitted should still display the program as it was selected.
  - [x] Program Information Request. Institutions completing the PIR should not be able to select an inactive program. PIRs created using a now inactive program should still be able to display it.
  - [x] Application Offering Change. Prevent the selection of an inactive program but allow displaying it if the program was already associated.
  - [x] Do not allow new offerings to be associated with an inactive program, unless during an "Offering Change Request" when the system needs to generate new versions of the same offering to allow Ministry review or for scholastic standing cloning, for instance. Change the Institution UI to disable the necessary button to prevent new offerings from being created.
- [x] Ensure API validation for the above new criteria.
- [x] Ensure existing E2E tests are updated. Ensure a new ticket is created to ensure E2E coverage for this feature.

**Comment by HRAGANBC** [comment]
@guru-aot 
For students with applications In-Progress or Assessment:
1) They **should** be allowed to edit their application
2) They **should** be able to select the deactivated program from their dropdown list AND be able to submit the application without issue

**Comment by guru-aot** [comment]
While editing the application for the student, can we add a sentence in this dialog?
<img width="1761" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHFxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1518f3791e13b355a44d2e2e99c62ed46312f363/image.png" alt="image.png" />

**Comment by HRAGANBC** [comment]
@guru-aot Confirming here the new decision made since my last comment on this ticket:

A student **should** be able to edit their application
A student **should not** be able to select a deactivated program when editing & re-submitting their application. The form should remove the deadtivated program, and upon editing the application the Program field will be blank. The dropdown menu of available programs should only display active programs. **I have added these two rules as ACs in the ticket**

Regarding your comment and the proposal to adjust the wording of the 'edit application' modal: we will pursue this in a seperate ticket. 

Thanks

**Comment by guru-aot** [comment]
Ticket https://github.com/bcgov/SIMS/issues/3240 is created as part of the E2E test cases for this ticket.
