### ISSUE TITLE
Queue-Consumers going into crash loop in Prod

### ISSUE THREAD

**Issue by guru-aot** [bcgov/SIMS#2956]
Mar19.24 NS: Will close this after successfully validating during PROD release Mar21.24. 

When the queue consumers try to start the readiness probe fails with the below error.
Tried to recover Redis and still it didn't solve.

**Technical**
- [x] Review the GitHub Redis recovery workaround.
  - [x] Review if the workaround can recover all the pods, masters, and slaves.
- [x] Review why queue-consumers readness was not able to check Redis connectivity and failed.
- [x] Try to reproduce the issue on DEV bringing down some Redis clusters.

_If GitHub action recovery works on DEV we can plan a Redis hard reset to make it stable again. If queue-consumers will be available in PROD soon its health check can help throublosooting the issue due to the sysdig alerts generation._

Logs

> api@0.0.1 start:prod:queue-consumers
> node --enable-source-maps dist/apps/queue-consumers/main.js

19:37:45.856 | zeebe |  INFO: Authenticating client with Camunda Cloud...
[32m[Nest] 16  - [39m03/06/2024, 7:37:47 PM [32m    LOG[39m [38;5;3m[NestFactory] [39m[32mStarting Nest application...[39m
[32m[Nest] 16  - [39m03/06/2024, 7:37:54 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mGlobalHttpModule dependencies initialized[39m[38;5;3m +7391ms[39m
[32m[Nest] 16  - [39m03/06/2024, 7:37:54 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mDatabaseModule dependencies initialized[39m[38;5;3m +1ms[39m
[32m[Nest] 16  - [39m03/06/2024, 7:37:54 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mTypeOrmModule dependencies initialized[39m[38;5;3m +0ms[39m
[32m[Nest] 16  - [39m03/06/2024, 7:37:54 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mConfigModule dependencies initialized[39m[38;5;3m +1ms[39m
[32m[Nest] 16  - [39m03/06/2024, 7:37:54 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mZeebeModule dependencies initialized[39m[38;5;3m +0ms[39m
[32m[Nest] 16  - [39m03/06/2024, 7:37:54 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mHttpModule dependencies initialized[39m[38;5;3m +3ms[39m
[32m[Nest] 16  - [39m03/06/2024, 7:37:54 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mBullModule dependencies initialized[39m[38;5;3m +1ms[39m
[32m[Nest] 16  - [39m03/06/2024, 7:37:54 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mLoggerModule dependencies initialized[39m[38;5;3m +0ms[39m
[32m[Nest] 16  - [39m03/06/2024, 7:37:54 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mDiscoveryModule dependencies initialized[39m[38;5;3m +1ms[39m
[32m[Nest] 16  - [39m03/06/2024, 7:37:54 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mTerminusModule dependencies initialized[39m[38;5;3m +1ms[39m
[32m[Nest] 16  - [39m03/06/2024, 7:37:54 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mBullModule dependencies initialized[39m[38;5;3m +0ms[39m
[32m[Nest] 16  - [39m03/06/2024, 7:37:56 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mTypeOrmCoreModule dependencies initialized[39m[38;5;3m +1291ms[39m
[32m[Nest] 16  - [39m03/06/2024, 7:37:56 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mTypeOrmModule dependencies initialized[39m[38;5;3m +0ms[39m
[32m[Nest] 16  - [39m03/06/2024, 7:37:56 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mCRAIntegrationModule dependencies initialized[39m[38;5;3m +5ms[39m
[32m[Nest] 16  - [39m03/06/2024, 7:37:56 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mSFASIntegrationModule dependencies initialized[39m[38;5;3m +0ms[39m
[32m[Nest] 16  - [39m03/06/2024, 7:37:56 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mSystemUserModule dependencies initialized[39m[38;5;3m +1ms[39m
[32m[Nest] 16  - [39m03/06/2024, 7:37:56 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mQueueModule dependencies initialized[39m[38;5;3m +0ms[39m
[32m[Nest] 16  - [39m03/06/2024, 7:37:56 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mATBCIntegrationModule dependencies initialized[39m[38;5;3m +12ms[39m
[32m[Nest] 16  - [39m03/06/2024, 7:37:56 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mNotificationsModule dependencies initialized[39m[38;5;3m +1ms[39m
[32m[Nest] 16  - [39m03/06/2024, 7:37:56 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mDisbursementReceiptIntegrationModule dependencies initialized[39m[38;5;3m +80ms[39m
[32m[Nest] 16  - [39m03/06/2024, 7:37:56 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mIER12IntegrationModule dependencies initialized[39m[38;5;3m +1ms[39m
[32m[Nest] 16  - [39m03/06/2024, 7:37:56 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mECEIntegrationModule dependencies initialized[39m[38;5;3m +0ms[39m
[32m[Nest] 16  - [39m03/06/2024, 7:37:56 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mFedRestrictionIntegrationModule dependencies initialized[39m[38;5;3m +0ms[39m
[32m[Nest] 16  - [39m03/06/2024, 7:37:56 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mSINValidationModule dependencies initialized[39m[38;5;3m +1ms[39m
[32m[Nest] 16  - [39m03/06/2024, 7:37:56 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mMSFAAIntegrationModule dependencies initialized[39m[38;5;3m +0ms[39m
[32m[Nest] 16  - [39m03/06/2024, 7:37:56 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mECertIntegrationModule dependencies initialized[39m[38;5;3m +0ms[39m
[32m[Nest] 16  - [39m03/06/2024, 7:37:57 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mBullModule dependencies initialized[39m[38;5;3m +1214ms[39m
[32m[Nest] 16  - [39m03/06/2024, 7:37:57 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mQueueConsumersModule dependencies initialized[39m[38;5;3m +2ms[39m
[32m[Nest] 16  - [39m03/06/2024, 7:37:57 PM [32m    LOG[39m [32mLoading system user...[39m
[32m[Nest] 16  - [39m03/06/2024, 7:37:57 PM [32m    LOG[39m [38;5;3m[RoutesResolver] [39m[32mHealthController {/health}:[39m
[32m[Nest] 16  - [39m03/06/2024, 7:37:57 PM [32m    LOG[39m [38;5;3m[RouterExplorer] [39m[32mMapped {/health, GET} route[39m
/opt/app-root/src/node_modules/redis-parser/lib/parser.js:179
    return new ReplyError(string)
           ^

ReplyError: CROSSSLOT Keys in request don't hash to the same slot
    at parseError (/opt/app-root/src/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/opt/app-root/src/node_modules/redis-parser/lib/parser.js:302:14) {
  command: {
    name: 'eval',
    args: [
      '--[[\n' +
        '  Pauses or resumes a queue globably.\n' +
        '\n' +
        '   Input:\n' +
        "      KEYS[1] 'wait' or 'paused''\n" +
        "      KEYS[2] 'paused' or 'wait'\n" +
        "      KEYS[3] 'meta-paused'\n" +
        "      KEYS[4] 'paused' o 'resumed' event.\n" +
        "      KEYS[5] 'meta' this key is only used in BullMQ and above.\n" +
        '\n' +
        "      ARGV[1] 'paused' or 'resumed'\n" +
        '\n' +
        '    Event:\n' +
        '      publish paused or resumed event.\n' +
        ']]\n' +
        'local rcall = redis.call\n' +
        '\n' +
        'if rcall("EXISTS", KEYS[1]) == 1 then\n' +
        '  rcall("RENAME", KEYS[1], KEYS[2])\n' +
        'end\n' +
        '\n' +
        'if ARGV[1] == "paused" then\n' +
        '  rcall("SET", KEYS[3], 1)\n' +
        '\n' +
        '  -- for forwards compatibility\n' +
        '  rcall("HSET", KEYS[5], "paused", 1)\n' +
        'else\n' +
        '  rcall("DEL", KEYS[3])\n' +
        '\n' +
        '  -- for forwards compatibility\n' +
        '  rcall("HDEL", KEYS[5], "paused")\n' +
        '\n' +
        'end\n' +
        '\n' +
        'rcall("PUBLISH", KEYS[4], ARGV[1])\n',
      '5',
      'prod:full-time-e-cert-integration:wait',
      'prod:full-time-e-cert-integration:paused',
      'prod:full-time-e-cert-integration:meta-paused',
      'prod:full-time-e-cert-integration:paused',
      'prod:full-time-e-cert-integration:meta',
      'paused'
    ]
  }
}

Node.js v18.18.2
npm notice 
npm notice New major version of npm available! 9.8.1 -> 10.5.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.5.0>
npm notice Run `npm install -g npm@10.5.0` to update!
npm notice

**Comment by ninosamson** [comment]
Please move to dev get dressed for review/estimation.

**Comment by ninosamson** [comment]
Will close after successful validation in PROD release
