### ISSUE TITLE
PT Final Award - NOA Summary based on eCert Totals

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#2958]
**User Story**
As a _student_ I want to be able to understand what my final award values are and when they will be available.

As a _ministry user_, I want to be able to tell when the ecert has been sent and what was requested. I also need to be able to direct students to the correct place when they have concerns about the award amount.

**Acceptance Criteria**
- [x] Once the ecert has been submitted for a PART TIME disbursement, change from the "pending" (FIG 1) final award state to the "complete" award state (FIG 2).
- [x] Update the Final award area for **PT** after the ecert has been sent (FIG 2) with new content:
> If you want to confirm the amounts you will receive or when they will be disbursed, please [access](https://protege-secure.csnpe-nslsc.canada.ca/en/public/sign-in-method) your National Student Loan Service Centre account.
- [x] Use the values sent in the ecert disbursement to populate the award amounts in the table (FIG 2). 
- [x] Add a section visible to only ministry users **FOR FT & PT** to display date that the ecert was submitted and the certificate number.

**Technical**
- [x] Do not change Full-time as it is already working as expected retrieving the values from `sims.disbursement_receipt_values` table.
- [x] Change API endpoint to return the same data as it is right now but get the final award values from `sims.disbursement_values.effective_value`.
- [x] "Date eCert Sent"Certificate should be the `sims.disbursement_schedules.date_sent` and should be added under the already existing section that contains the "Certificate Number". Ensure that only Ministry will be able to see it.
- [x] Method [populateDisbursementReceiptAwardValues](https://github.com/bcgov/SIMS/blob/main/sources/packages/backend/apps/api/src/route-controllers/assessment/assessment.controller.service.ts#L280-L362) should be adapted. Consider creating a new business service to process the final awards for full-time and part-time.
- [x] E2E Tests

**Business Context**
FIG 1:
<img width="334" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFBJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e5074745fdbb5e2796cd6c289f966ebaeb895f1a/image.png" alt="image.png" />
FIG 2:
<img width="552" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODdPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0130d099dbd993885ab88d4084e54d163488ffd0/image.png" alt="image.png" />

**Comment by CarlyCotton** [comment]
@Joshua-Lakusta @HRAGANBC 
This is the solution for PT final awards until we reach a point where the disbursement file includes federal PT amounts.
It aligns with how SD triages issues at this moment: differentiating between pre- and post-ecert, and redirecting students to look at NSLSC info once the ecert has been submitted.

**Comment by andrewsignori-aot** [comment]
@CarlyCotton the section to display the "Certificat Number" is already in place for the Ministry under the "Estimated Award" and we are assuming that we are going to use the same section just adding the "eCert Sent Date", does it make sense? Please see the below screenshot from the Ministry.
<img width="582" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0VmQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ec0c8f18f89861ad8abc721c5da41c22c457686a/image.png" alt="image.png" />

**Comment by CarlyCotton** [comment]
@andrewsignori-aot Same block for under the "Final Award" section, but instead of "Earliest date of disbursement" we display "Date ecert sent:" and the date that the record was sent via ecert.

**Comment by andrewsignori-aot** [comment]
> @andrewsignori-aot Same block for under the "Final Award" section, but instead of "Earliest date of disbursement" we display "Date ecert sent:" and the date that the record was sent via ecert.

It should be ok @CarlyCotton but should we display the "Certificate Number" that is already displayed?

**Comment by andrewsignori-aot** [comment]
@CarlyCotton related the AC that reads "Add a section visible to only ministry users FOR FT & PT" I am assuming that Public Institutions will not have access to it also, right?
If the assumption is wrong please let me know.

**Comment by andrewsignori-aot** [comment]
> > @andrewsignori-aot Same block for under the "Final Award" section, but instead of "Earliest date of disbursement" we display "Date ecert sent:" and the date that the record was sent via ecert.
> 
> It should be ok @CarlyCotton but should we display the "Certificate Number" that is already displayed?

This question is still missing an answer. Can you please review it @CarlyCotton?

**Comment by CarlyCotton** [comment]
@andrewsignori-aot 
Sorry about that, spoke about it with people and forgot to come back and answer the question.
Please display to the ministry on the 'Final Award' side the certificate number that was sent on the ecert. Same as what is displayed on the left award panel once sent. A bit of duplicate information, but we would like it on both sides.

**Comment by andrewsignori-aot** [comment]
## Business Demo

### Full-time
- Application: 2024000011
- Disbusements
  - First:  `Sent`
  - Second: `COE Pending`
  - Receipts: `not received yet`

<img width="1087" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMU9KQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ea6a3cf89b4a70c56f15874eefb31acfbaad71cf/image.png" alt="image.png" />

<img width="564" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVNKQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f249137920e5a2a78f3243725ca967bbe7c64ad3/image.png" alt="image.png" />

**Comment by andrewsignori-aot** [comment]
## Business Demo

Student: Andrew Boni Signori 1 (andrew_signori_1)
Institution: SIMS_COLLE

### Part-time
- Application: 2024000009
- Disbusements
  - First:  `Sent`
  - Second: `COE Pending`
  - Receipts: `not received yet`

#### Student View

<img width="557" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXVKQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9d5c96888c8647ce7063b4e921d2cd6f89be5715/image.png" alt="image.png" />
