### ISSUE TITLE
Files Encoding for Integrations

### ISSUE THREAD

**Issue by andrewsignori-aot** [bcgov/SIMS#2966]
During the analysis of ticket #2850, there was an understanding that the system should not produce files with characters beyond ASCII (7-bit). Please see the comments on the related tickets for further information.

**Assumptions**
- Files generated by SIMS should follow ASCII (7-bit) only.
- Files uploaded to SIMS by institutions may receive ASCII extended (8-bit/latin1/ISO8859-1 or other if the Ministry desires).
- SIMS must be adapted to convert all data for files generated into ASCII (7-bit).

**Acceptance criteria**
- [x] Ensure generated files to be uploaded to the SFTP will contain only ASCII (7-bit).
  - [ ] Apply a conversion in the centralized location responsible for all files written to the SFTP ([source reference](https://github.com/bcgov/SIMS/blob/main/sources/packages/backend/libs/integrations/src/services/ssh/sftp-integration-base.ts#L58)).
  - [ ] Iterate through each character and generate a byte array where each entry will be between 0-127.
    - [ ] For a list of known characters, apply a conversion.
    - [ ] For characters outside the list of known characters, set the byte as 63 ("?").
    - [ ] The file contents should already be converted to 1 byte and after this conversation happens we should do our best effort to convert some of the "Extended ASCII Codes" into the non-extended-ASCII codes (7 bits).
- [x] Ensure buffers converted as a result of a file uploaded are using `latin1`.
  - [ ] [education-program-offering.institutions.controller.ts](https://github.com/bcgov/SIMS/blob/main/sources/packages/backend/apps/api/src/route-controllers/education-program-offering/education-program-offering.institutions.controller.ts#L516)
  - [ ] [student-scholastic-standings.institutions.controller](https://github.com/bcgov/SIMS/blob/354171f89aeada90add4f58a4fae8f4c0d13e369/sources/packages/backend/apps/api/src/route-controllers/student-scholastic-standings/student-scholastic-standings.institutions.controller.ts#L220)
- [x] Adjust current E2E tests already sending extended ASCII characters.

**Sample known characters' conversation**
`áàãâ` would be converted to `a`.
`éèê` would be converted to `e`.

**Comment by andrewsignori-aot** [comment]
@JasonCTang can you please review the ticket to ensure that this is the goal?

**Comment by JasonCTang** [comment]
This aligns completely with what was discussed.  Good to proceed.  Good work!

**Comment by sslaws** [comment]
We would like business confirmation on the approach and then technical team will clean ticket and put into backlog.  Please send to Dressed after review.

**Comment by sslaws** [comment]
We would like business confirmation on the approach and then technical team will clean ticket and put into backlog.  Please send to Dressed after review.

**Comment by michesmith** [comment]
Biz is good with the approach .

**Comment by CarlyCotton** [comment]
Moving to Biz Lather - ok with sample character conversions.
