### ISSUE TITLE
Analysis - SIMS Object Storage for Files 

### ISSUE THREAD

**Issue by michesmith** [bcgov/SIMS#2970]
As an SIMS product team, we need to store files in an object store rather than the persistent volume claims. 

**Acceptance Criteria:** 

- [x] Find a Nodejs library to be used.
- [x] Create the env variable for the S3 connection and operations.
- [x] Keep saving the file bytes to SIMS DB as it is right now but start uploading the file to the S3 storage in parallel. If the S3 uploads fail it should not prevent the API from saving the DB. Log the S3 operation time.
- [x] Try to download the file bytes from the S3 storage, if not present or if an error happens retrieve the bytes from SIMS DB. Log the S3 operation time.

**Technical Context**
Buckets and policies were created for sims-local, sims-dev, sims-test, sims-staging, and sims-prod. Out-of-box server-side managed bucket encryption enabled.

Connection information available from Stephen or Jason

**Comment by michesmith** [comment]
@sslaws this was a note from our previous tech analyst. are you able to discuss at Dev Lather?

**Comment by sslaws** [comment]
@michesmith yes I can discuss.

**Comment by sslaws** [comment]
Dev to dress and include the following: secure retrieval of files from object storage, migration of existing files and updates to application/db to store links to object store.

**Comment by andrewsignori-aot** [comment]
As discussed with @ninosamson moving it to Biz Lather for Ministry agreement and decision on how to proceed.

**Comment by dheepak-aot** [comment]
As per retro discussion moving the ticket to IMB Architecture pipeline.

**Comment by ninosamson** [comment]
re: questions from me: 
- I assumed object / file are same level? 
- if we're trying to clarify whether or not files with PI should be saved, then yes, they should.

**Comment by andrewsignori-aot** [comment]
> re: questions from me:
> 
> * I assumed object / file are same level?
> * if we're trying to clarify whether or not files with PI should be saved, then yes, they should.

@ninosamson can we assume after the last chat with @sslaws and yourself that we are ok to have the encryption at rest as a solution and questions about files saved with potential PI data are ok?

**Comment by ninosamson** [comment]
Confirmed @andrewsignori-aot. The solution will meet the requirements.

**Comment by andrewsignori-aot** [comment]
## Tests on Openshift (~4MB file)

<img width="802" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEF0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--420506e8aefefedbb381a0cce34d188846740c55/image.png" alt="image.png" />

### Upload and download of 4MB-ish file

<img width="640" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEV0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--04d8bdf19e9fc759871a76587da1de736af53ebd/image.png" alt="image.png" />

### The same file was uploaded twice, one was removed from S3 to force the DB download and compare the times.

<img width="658" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEl0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ef32c6acac6732b4346129eeb762b80f3481a68c/image.png" alt="image.png" />
