### ISSUE TITLE
File Uploader Bug in Web UI

### ISSUE THREAD

**Issue by lewischen-aot** [bcgov/SIMS#2973]
**User Story**
As a student, I want to be able to upload a file using the File Uploader and also view the file with its original content by downloading it. As a ministry user, I want to view the original file by downloading it from the File Uploader. 

**Current Behavior**
When a student uploads a file and immediately download it by clicking on the file, the downloaded file doesn't have the original content. The same error happens when the ministry user downloads the file from the File Uploader. It is known to happen for `text files. The downloaded text file will display [object object] as shown below.
<img width="508" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFRJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5afa71372c54016d615d770d98c989b507f7a01c/image.png" alt="image.png" />

**Expected Behavior**
The uploaded file on File Uploaded should have the original file content after downloading.

**Acceptance Criteria**
- [ ] The downloaded file should have the original file content after downloading using the File Uploader
- [ ] Ensure all accepted files (JPG, PNG, DOC, DOCX, PDF, TXT) have the correct behavior.

**Comment by guru-aot** [comment]
There is a change in the feature when the student uploads a file. Currently this bug is created, without virus scanning is enabled. We will have a look on the bug again, once the ticket #3297 for UI enhancement for both Ministry and Student user is complete.
