### ISSUE TITLE
Email notification - PD/PPD Student reminder email 8 weeks before end date

### ISSUE THREAD

**Issue by Joshua-Lakusta** [bcgov/SIMS#2979]
**User Story**
As a student, I am blocked from accepting my application if I answer "Yes" to disability funding in my application and my profile disability status is Pending/Declined/Not Requested. If I take no action and it gets closer to the study end date, I may become ineligible for any funding during this time period. I should receive additional communication to support me in taking action to resolve either the profile status or the application answer.

**Acceptance Criteria**
- [ ] Create email notification trigger if a student is blocked from accepting their assessment due to a disability mismatch (Profile=No and App=Yes) and they are within 8 weeks of their study end date.
- [ ] This should be sent once per assessment
- [ ] This email should be created when the student is blocked at the accept assessment phase or at the completed phase (blocked at ecert)
- [ ] GC Notify Template: `7faea39f-cf8e-41ee-af02-c4790cac5b26`
- [ ] Scheduler to check once a day.
> SUBJ: Your application requires action - StudentAid BC
> Hey ((givenNames)) ((lastName)),
>
> Your application ((applicationNumber)) requires action regarding your disability status before you can receive funding. Please login and visit your application details page to view additional information.
> 
> [Login now](url)

**Business Context**
- Current state SFAS automatically changes the application and distributes base funding. However, does not have the flexibility of sims so this is a better path for us.

**Technical**
- [ ] Create a scheduler to verify the applications once a day. The scheduler can be generic to support similar validations in the future.
  - Suggested name: `student-application-notifications`.
  - Pick a time after `archive-applications` with 30min to 1h difference.
- [ ] Add the new scheduler for the wiki.
- [ ] Select all student applications where
  - Offerings end date within 8 weeks.
  - Applications with current disbursement pending.
  - Application not archived.
  - Remove assessments where a notification was already sent.
  - With the PD/PPD mismatch using the same logic from [validate-disbursement-base.ts](https://github.com/bcgov/SIMS/blob/main/sources/packages/backend/libs/integrations/src/services/disbursement-schedule/e-cert-processing-steps/validate-disbursement-base.ts#L44).
- [ ] Save the assessment ID as metadata and ensure the email will be sent once.
- [ ] E2E Tests
  - [ ] Ensure the email will be sent once for the same assessment.
  - [ ] Ensure the email will be sent again for different assessments for the same application.

**Comment by HRAGANBC** [comment]
@Joshua-Lakusta 
Please confirm that ticket related to application status tracker / student notifications about disbursements being blocked does not overlap with this one

**Comment by CarlyCotton** [comment]
@HRAGANBC I think this was based on feedback from product review and I'm generally in support for more notification than less for PD/PPD students to guide them through the process. I don't think it's 2.0 critical, but would want to keep it close at 2x. Curious to hear from Josh.

**Comment by andrewsignori-aot** [comment]
@Joshua-Lakusta in the technical details we changed the below AC to ensure that the email will be sent once per assessment. If not it will not notify the student for reassessments.
_This should be sent once per application_.

**Comment by andrewsignori-aot** [comment]
> * This should be sent once per application

@Joshua-Lakusta @CarlyCotton can you please adjust the business AC, unless we are missing something?

**Comment by andrewsignori-aot** [comment]
> @Joshua-Lakusta in the technical details we changed the below AC to ensure that the email will be sent once per assessment. If not it will not notify the student for reassessments. _This should be sent once per application_.

@Joshua-Lakusta @CarlyCotton can you please adjust the business AC, unless we are missing something?

**Comment by Joshua-Lakusta** [comment]
@andrewsignori-aot agreed and updated

**Comment by andrewsignori-aot** [comment]
@Joshua-Lakusta we need to ensure the application in undesired statuses would potentially be generating notifications.
Should we consider only applications is Assessment status? Does it seem, right?
