### ISSUE TITLE
6 Week Deadline - Policy

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#2997]
**User Story**
As a student I should be warned before submiting an application within 6 weeks of the study end date. Applications submitted past this deadline are subject to extra review and may result in me not receiving funding. 

**Acceptance Criteria**
- [x] Change the existing validation such that students who input study information with end dates less than 42 daysfrom today are forced down the exception path (current validation imposes exception path when study end date is less than today)
    - [x] This applies to student selecting offerings with actual dates
    - [x] This also applies to student going down the PIR path but inputting dates themselves.
- [x] Change the warning banner displayed to student should be changed to read 
> The dates you have entered are no longer eligible for funding. To receive funding for this study period, you will need to seek approval from StudentAid BC. Once you have submitted your application, please use the following link for information on the [funding after end date appeal.](https://studentaidbc.ca/sites/all/files/form-library/appeal_fundingafterenddate.pdf)

Note: No changes are needed to the PIR process of the Institution account in light of this change in validation. 

**Technical**
- [x] Change the current condition to display the banner and generate the "Application Exception - Study end date is past".
- [x] Ensure the exception is generated for a selected offering or when the student did not find the offering and provided custom dates.
- [x] It is supposed to be a form.io-only change.
- [x] The logic for the 42-day calculation was previously present in the form and should be in a past commit. It was removed due to a change in the requirement (that is now back).

**Comment by HRAGANBC** [comment]
@Joshua-Lakusta 

Can you test:
1) Student using PIR but inputs old dates 
2) School approves PIR using old dates
