### ISSUE TITLE
PT Assessment - Bug Fixes from testing (Rounding Assessment)

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#3001]
New Ticket as a result of this ticket is #3539
**User Story**
As a ministry, I need to calculate the awards accurately. This includes displaying the amounts correctly to the student so they know what to expect and to send the request to NSLSC to fund the student in the correct amount to prevent rejection. If the amounts are rounded at the wrong stage or not rounded to the nearest dollar it could result in a 

**Current Behaviour**
$0.20 calculations round up to $1 in the front end
TC3831 (Astrid's Run)

## SIMS
Student Name: Mightymouse EIGHTYONE
Application: 2024000037
BCAG: SIMS: $588, Mass: $587
CSPT: SIMS: $1943, Mass: $1942
<img width="608" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTU4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d9d0ba03ccf7911ebea14eb8ecf67a769afc2d15/image.png" alt="image.png" />

## Camunda
ProcessInstance: [4503600048565924](https://ont-1.operate.camunda.io/9976422d-01be-4e6f-bb2e-14d4949dd9a9/processes/4503600048565924)
finalFederalAwardNetCSPTAmount: 1942.08
finalProvincialAwardNetBCAGAmount: 587.2033

# Questions for Analysis - provide answers in comments and ping carly

1. The display in the assessment seems to show a full round up to the nearest full number. Do we store the final amounts as 1942 / 587 respectively or do we keep the 1942.08 and 587.20?
2. Which value do we send on the ecert?

**Comment by CarlyCotton** [comment]
@Joshua-Lakusta I've added some questions to the bottom for analysis. If you have any other please add

**Comment by michesmith** [comment]
New Ticket as a result of this ticket is #3539
