### ISSUE TITLE
Convert Enhancements List into Tickets and Tag Appropriately 

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#3006]
Biz to Review the Enhancements List here, and create distinct tickets for each, as needed, and tag all appropriately. 

<img width="1192" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelBtQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--25b7f752cdf99f9112d25b2b76e9ccb2e048d1cd/image.png" alt="image.png" />

**Comment by michesmith** [comment]
Moving to A Zen not Git Ticket
