### ISSUE TITLE
Prepare Student and Institution Staging Environment for BC Public Entry 

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#3007]
Questions to resolve:

- Can staging be configured to only allow PT applications?
- Does Ministry have to create new institutions in Institution Staging environment as well? Or can Institutions login using their Business BCeIDs into staging? 
- Can they keep their access here long-term as training tool? I.e. well after Part-Time launch?
- Which SIMS resources will support this? Good first task for new BAAs

**Comment by michesmith** [comment]
There is a dev ticket to move staging over. Otherwise this is not a dev ticket
