### ISSUE TITLE
PT Lifetime Maximum (Balance) File Import

### ISSUE THREAD

**Issue by andrewsignori-aot** [bcgov/SIMS#3018]
Related to #1749

**User Story**
As a Part-Time student, I want SIMS to be aware of my outstanding loan balance with NSLSC so that this balance can be considered as part of my Part-Time assessment. 

**Acceptance Criteria***
- [x]  Read-in the Monthly Loan Balance received monthly via flat file from NSLSC (PEDU.PBC.PT.MBAL.yyyymmdd.001)
- [x]  Relevant fields to extract from report are: 
- "10 PTMB-DTL-BALANCE" (Row 16)
- "10 PTMB-HDR-MONTH-END-DATE" (Row 10) - This corresponds to the 'date' displayed through UI
- [x] Detect 'match' between students in report and in SIMS if ALL following fields are a match: 
- "10 PTMB-DTL-SIN" (Row 14). 
- "10 PTMB-DTL-LAST-NAME" (Row 17)
- "10 PTMB-DTL-BIRTH-DATE" (Row 19)
- [x] Confirm number of records in the file matches the expected based on trailer information.

**Context:** 
- Seperate ticket will handle the incorporation of monthly amounts into the assessment calcs
- If re-assessment occurs, do **not** read in the monthly balance again. Just rely on the amount already logged the previous month. 
- If student submits multiple applications within a single month, BOTH applications will use the same monthly loan balance per the federal file. This will likely result in student being overfunded, and getting rejected. 
- if e-cert gets rejected, Ministry will just trigger a re-assessment of the student to regenerate new eCert, presumably which also reflects the updated loan balance. 
- And additional enhancement to this feature MAY be added post-launch which provides an additional check at eCert time to ensure student's loan does not exceed the lifetime balance. Decision TBD.

**File Specifications**
[PT Montly Balance File Layout.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzczQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--78dcf37e627de26777773a00da7945ad159f61de/PT%20Montly%20Balance%20File%20Layout.xlsx)
[TEDU.PBC.PT.MBAL.20240331.001.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMllZQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--535eae2b2bb4a317239f8fe9884d74ef35ea4157/TEDU.PBC.PT.MBAL.20240331.001.txt)

**Sample File**
This file has been sanitized to replace SINs with dummy numbers, and remove 95% of the records. Please IGNORE the trailer record, as it reflects the trailer for the original file with many more records. 
[PTMBAL.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1NVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--27815af44e103a37e878b59bef00bcb80d6db9cc/PTMBAL.txt)
 
**Technical Context**
- [x] Create a new scheduler to be executed once a day to process the file. Follow the most recent and updated scheduler pattern for coding.
- [x] Create a table `sims.student_loan_balances` with columns as below.
  - id
  - student_id
  - csl_balance
  - balance_date
  - and the other default audit columns.
- [x] Read the flat file similar to cra-income-verification and populate the above table.
- [x] File expected to be under `MSFT-Response` folder (double check with business).
- [x] File name is expected to be `PEDU.PBC.PT.MBAL.yyyymmdd.001` where the `P` stands for the environment.
- [x] Validations to be done when the file is read. 
  - The number of records should match the trailer record count.
  -  Check for record type. The header is 0 and the footer is 9.
  -  If some of the above failed, abort the file processing.
- [x] Validation for the record data (date and balance number)
  - Validate if the balance is a valid number (check existing similar validations).
  - Validate if the date is a valid date (check existing similar validations).
  -  If some of the above failed, abort the file processing.
- [x] Matching of the student is done by the below criteria (case insensitive).
  - SIN -> student current sin from sin_validations table -> true
  - Last Name -> users.last_name
  - Birthdate - >students.birth_date
  - [x] If no records match, then skip and move to the next record.
- [x] If successfully processed, delete the file. If the process is aborted at any time, do not delete the file.
- [x] If more than one file exists process them all sequentially ordered by name.
- [x] E2E tests.

**Comment by andrewsignori-aot** [comment]
@CarlyCotton the question will not directly impact this ticket but it will be necessary to understand the logic when consuming the data. 
What the file will contain when the student has no balance anymore?
- Would the file contain only students with a balance greater than zero or would the student be present in the file with a "zero balance" record?

**Comment by CarlyCotton** [comment]
@andrewsignori-aot 

> What the file will contain when the student has no balance anymore?
>Would the file contain only students with a balance greater than zero or would the student be present in the file with a "zero balance" record?
No 0 balance records are expected on the file. I expect we'd have many many more records on the monthly file if we had 0s.

>would the match using the DOB, last name, and SIN change somehow for this import also?
We want to only keep when it matches all 3. The partial match is only relevant for when we initially import legacy info to a new SIMS profile.

**Comment by andrewsignori-aot** [comment]
> @andrewsignori-aot
> 
> > What the file will contain when the student has no balance anymore?
> > Would the file contain only students with a balance greater than zero or would the student be present in the file with a "zero balance" record?
> 
> No 0 balance records are expected on the file. I expect we'd have many many more records on the monthly file if we had 0s.
> 
> > would the match using the DOB, last name, and SIN change somehow for this import also?
> 
> We want to only keep when it matches all 3. The partial match is only relevant for when we initially import legacy info to a new SIMS profile.

Regarding the zero balance, should we check if the student is not present in the most recent one then we assume that it is zero?

**Comment by CarlyCotton** [comment]
@andrewsignori-aot  Yes, we can assume monthly balance is 0 if no balance exists on the report for a student. This lack of balance can also be displayed in UI as $ 0

**Comment by CarlyCotton** [comment]
@guru-aot Added the new sample file to the ticket: TEDU.PBC.PT.MBAL.20240331.001
