### ISSUE TITLE
Ecert File Creation - PT & FT

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#3026]
**User Story**
As a ministry user, I need the files sent to NSLSC to reflect all the data we have on file accurately and for the files received to be read in accurately.

### **Acceptance Criteria**
- [x] **FT Ecert**: Update Postal Code when address country is Canada from A#A#A# to A#A #A#. (Add whitespace between the two sets)
- [x] **PT Ecert**: Update format for Federal Loan Disbursement Amount (27 Disb Amt 9(09)). Examples of expected field values based on loan amount:
    - 000001248 is equal to $12.48
    - 000124800 is equal to $1248.00
- [x] **PT Ecert**: Update format for trailing record that sums Federal Loan Disbursement Amount to align with the update to Field 27.

**Technical**
- [x] Postal code is saved to DB without spaces and we keep this behavior. Adjust the format as expected in the e-Cert only before writing the value to the file.
- [x] Ensure the 2 decimals for the part-time only for the required field in the business AC (`Federal Loan Disbursement Amount (27 Disb Amt 9(09))`). No questions should be asked about other similar fields and no investigation is needed beyond this field.
- [x] Adjust the E2E tests to cover the new format including the decimals.

**Comment by HRAGANBC** [comment]
@andrepestana-aot I can confirm the first AC is correct, and should be made ONLY to the FT eCert 

FYI @CarlyCotton

**Comment by CarlyCotton** [comment]
> the field Total Amount Disbursed is the sum of all Disbursement Amount fields. In this case we also need to generate the Total Amount Disbursed with 2 decimals, right?
<img width="1873" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1RGQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f7955f06846078a237b183cc718ffde07fe81c6c/image.png" alt="image.png" />

That trailing field should show 000222200 if the two records are 000111100 and 000111100. Not 000002222

Updated ticket based on conversation with @andrepestana-aot

**Comment by michesmith** [comment]
Reviewed by Biz- waiting for the E2E Test .. then can move to close
