### ISSUE TITLE
PT Lifetime Maximum - Assessment Calculation - Zero Balance Import

### ISSUE THREAD

**Issue by andrewsignori-aot** [bcgov/SIMS#3029]
**User Story**
As a _Ministry user_ I need to be able to see when a Student no longer has a Lifetime Maximum Maximum balance, assuming that he had some in the past. The federal government sends a file that contains all the PT students with balances greater than zero. When a new file is received, if a student is no longer present in the records we should assume the student no longer has a balance.

**Acceptance Criteria**
- [ ] Ensure that all students present in the previous file received that are no longer present in the most recent file will have a "zero balance record" associated with this most updated file.
- [ ] If the student has a balance greater than zero in the future it should be imported as usual, which means that the student statement along the months can be as below.

| Balance Date | Current Balance |
| ------------ | --------------- |
| July         | 0               |
| June         | 1500            |
| May          | 1500            |
| April        | 0               |
| March        | 1000            |
| February     | 2000            |
| January      | 3000            |
| December     | 4000            |

**Technical**
- [ ] After the file records are imported, insert "zero balance" records using a bulk SQL insert (likely an insert of a select).
- [ ] Use the balance date to compare previous imported records. If the file contains no records (unlikely to be a real-world scenario), all students with a previous balance will have inserted a new "zero balance" record.
- [ ] The students to have a "zero balance" record insert will match the below conditions.
  -  Previous file balance value was greater than zero.
  -  Current file balance no longer has a student record.
- [ ] E2E tests
- Import 2 files and check if the "zero balance record" was inserted.

**Comment by andrewsignori-aot** [comment]
@CarlyCotton ticket was created to address the "zero balance" scenario discussed during the last "Dev Get Dressed" meeting.
Should we take this to business or do you believe that we are good to proceed with the understanding that we have now?
I tried to capture in the `User Story` section the expected behavior for the file, please take a look if it is aligned with your understanding.

**Comment by CarlyCotton** [comment]
@andrewsignori-aot That covers what we spoke about and the user story looks good to me.

**Comment by andrewsignori-aot** [comment]
### Scenario planned for demo.

#### Students Users
- SIMS00007 - Jack (not need to demo, it will just be in the file)
- SIMS00005 - MATT FRANKY

#### Queue Dashboard
- URL:https://dev-aest-sims.apps.silver.devops.gov.bc.ca/admin/queues/queue/student-loan-balances-part-time-integration?status=completed

#### Ministry Portal
1. Find MATT FRANKY;
2. Go to the Balances tab, most updated record should be Mar 10 2024;
3. Import file DEDU.PBC.PT.MBAL.20240410.001 and a new record should be created for April;
4. Show the next content of the file DEDU.PBC.PT.MBAL.20240510.001 and point that MATT is no longer present;
5. Execute the scheduler;
6. Show that a new entry was added to the MATT balance history with "zero amount";
7. Import the file DEDU.PBC.PT.MBAL.20240610.001;
8. Show a new record added after a zero balance was present.

#### Sample files
[DEDU.PBC.PT.MBAL.20240410.001.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFZKQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--75c6eaf5e8b68578d1fcf25a48162ffa76b9046b/DEDU.PBC.PT.MBAL.20240410.001.txt)
[DEDU.PBC.PT.MBAL.20240510.001.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFpKQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a480bfcb4468bd15cc053efd7acf4aab8291a1b4/DEDU.PBC.PT.MBAL.20240510.001.txt)
[DEDU.PBC.PT.MBAL.20240610.001.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGRKQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3e17ed700673802f04a59b3694a914e183e8d9d0/DEDU.PBC.PT.MBAL.20240610.001.txt)
