### ISSUE TITLE
Enable Page saving the application info as the student goes along.

### ISSUE THREAD

**Issue by Joshua-Lakusta** [bcgov/SIMS#3035]
As a student, I want to automatically save draft applications as I go to prevent losing my work if I close it or it crashes by accident without saving the draft. This is important because currently when completing the application if you leave or are disconnected you lose a lot of your application progress. It would greatly improve the student experience if this was not the case.

**Acceptance Criteria**
- [ ] For draft applications, save the draft whenever the user navigates between sections of the application. (Next Section/Prev Section/Section Headings)

**Technical**
- [ ] Execute the saving draft only when the application is is Draft state and not in "read-only" mode.

**Comment by Joshua-Lakusta** [comment]
Moving back to shower stall as this should be accelerated to satisfy some accessibility related concerns.

**Comment by andrewsignori-aot** [comment]
@Joshua-Lakusta can you please confirm the toast notification should be disabled while automatically saving the draft?
<img width="1271" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNk5XQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e5f786ced15fa72b726f6a27cf4be947a270cca8/image.png" alt="image.png" />

**Comment by Joshua-Lakusta** [comment]
I am ok with us disabling for each section change as long as it still appears when they select save draft.

**Comment by sh16011993** [comment]
Thanks @Joshua-Lakusta and @andrewsignori-aot 
I have updated the code according to the above comment.
