### ISSUE TITLE
Revise Scholastic Standing Functionality and Content

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#3040]
**User Story**
As an institution user, I want the Scholastic Standing reporting options to fully align with policy, and to provide better wording around each option so I am aware which option is more appropriate to use. 

**Acceptance Criteria**
- [ ] **UI Label Changes**
     - change "Student Withdrew From Program" to "Student Withdrew from funded period" 
     - change "Student completed program early" to "Student completed funded study period offering early" 
- [ ] **Display Different Label Conditional on PT or FT application**
    - If FT app: "Student did not complete program" should become "Student was unsuccessful in completing their funded study period offering"
    - If PT app: "Student did not complete program" should become "Student did not complete courses they were funded for"
- [ ] **Remove Label and Back-End Process for "Student went from Full-Time to Part-Time..."**
- [ ] **Add new option** 
    - label should read "Student is transferring to a different institution or campus"
    - sub-question should ask "Last day the student is attending your institution" (ignore this mockup which says something different)
    - response to sub-question should become new end date during re-assessment. Impact should function identically to "completed early", i.e. re-assess with new end date, but apply no restrictions or other penalties. 
    - store this event in database as a distinct option from "completed early" (so they can be distinguished in future reporting)
- [ ] Add accordion with help text beneath the "Report a Change" header. See Fig 2 for text
- [ ] Adjust the sub-question of the "completed early" to be consistent with the mock-up below. 
- [ ] Change IER file mapping:
    - [ ] Remove "CI" as a possible value
    - [ ] Add "ST" to denote 'School Transfer"
    - [ ] Change the IER file specs document accordingly

**Mock-Ups**
**Fig 1**
<img width="903" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXhoQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b41dc3bc1ace515c45f87eec31f3a278408d7903/image.png" alt="image.png" />

**Fig 2**
<img width="695" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUlDQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--32e21b73461018df740d56f228645b4a6ded948f/image.png" alt="image.png" />

<img width="508" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3BoQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a9d43c35bc3082d0bcc4b0283b65a1c02c194916/image.png" alt="image.png" />

<img width="567" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3RoQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--adf444e1a5471e7ab1a8d120743fc81f1aad2d4a/image.png" alt="image.png" />

<img width="702" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3hoQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ef442ae3fe4e13caffd6c5243f35de848814747d/image.png" alt="image.png" />

<img width="516" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzloQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3b25533063e9cb282b32aa96f956730f3a58d866/image.png" alt="image.png" />

<img width="545" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEJoQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fedf4483200f863c16d4b9b5cda92b3c8ea5adb8/image.png" alt="image.png" />

**Biz Context**
- See Fig 2 for mapping of old to new options
- Separate ticket will be pursued for adjusting Student Application Status Tracker, as needed,

**Technical Context**
- [ ] Rename the DB enum item `Change in intensity` from the table `sims.student_scholastic_standings` to `School transfer`.
- [ ] Remove the `Change in intensity` logic from the backend.
- [ ] Create the new logic for `Student transfer` based on the existing logic for `Student completed program early`.
- [ ] Execute the changes in the current form.io (no plan to convert the UI to Vuetify right now).
- [ ] Conditional label for PT/FT should be based in a hidden field on form.io, if it does not exist yet, please add one.
- [ ] E2E
  - If brand new create at least some E2E.
  - If already existing add new E2E for the new option.

**Comment by HRAGANBC** [comment]
@CarlyCotton @Joshua-Lakusta 
These are primarily content changes landed by policy. Only functional change is removing the redundant 4th radio button called "change from part-time to full-time" which functions identically to withdrawal. 

Ready to lather?

**Comment by michesmith** [comment]
@HRAGANBC can you please ensure that the content is aligned with said policy? also the user story is vague- is that REALLY what they want- to simply align with policy? why do they want to revised scholastic standing functionality and content.

**Comment by CarlyCotton** [comment]
Additional Context for reference
[Uploading... image.png]

**Comment by andrewsignori-aot** [comment]
@HRAGANBC @CarlyCotton the IR12  has the current mapping for Scholastic Standing code.
Student did not complete program: `UC`.
Student completed program early: `EC`
Change in intensity: `CI`
As part of this ticket the code for `Change in intensity` is being removed. Is there an alternative code to be mapped to the new `Student transfer` option?

**Comment by HRAGANBC** [comment]
@andrewsignori-aot 

Please use "ST" to denote "School Transfer" and you can remove "CI" altogether. Thx

@CarlyCotton FYI

**Comment by andrewsignori-aot** [comment]
@HRAGANBC currently formio does not support a tooltip at the option level, only at the component level (same for Student Application).
Is it possible to achieve the same content in a different way?

**Comment by andrewsignori-aot** [comment]
> @andrewsignori-aot
> 
> Please use "ST" to denote "School Transfer" and you can remove "CI" altogether. Thx
> 
> @CarlyCotton FYI

@HRAGANBC we need an AC updated to reflect it.

**Comment by HRAGANBC** [comment]
@andrewsignori-aot 

Can you please merge all ToolTips into a single ToolTip to be placed next to the "Report a Change" Heading? The text should read:
*(The - denotes a bullet point)

> **Student withdrew from funded study period offering**
According to StudentAid BC policy, a student may need to be reported as withdrawn if:
- Student drops below 60% attendance (40% for students with a disability) for three consecutive calendar weeks of study
- Student increases course load from Part-Time to Full-Time studies
- Student misses two consecutive calendar weeks of study
- Student misses sufficient days/hours that they can no longer successfully complete the study period offering
- student transfers to a new institution

>**Student completed funded study period offering early**
- Enter the revised completion date of the student

> **Student was unsuccessful in completing their funded study period** (Full-time students only)
If a Full-Time student was unsuccessful in completing their funded study period offering, enter the total length of the study period offering in which the student was unsuccessful.

> **Student did not complete courses they were funded for** (Part-time students only)
If a Part-Time student did not complete courses they were funded for, enter the total length of the study period in which the student was unsuccessful. 

> Student is transferring to a different campus
If a student is transferring to another school, report the last day of classes that they will attend at your school

This will allow the student to submit a new application to the correct school without penalizing them in any way for the transfer.

**Comment by andrewsignori-aot** [comment]
@HRAGANBC according to our chat this would be the adjusted content.

## Part-time
![image](https://github.com/bcgov/SIMS/assets/61259237/b53e0266-23ff-4e16-a450-cdc520fd0a37)

## Full-time
![image](https://github.com/bcgov/SIMS/assets/61259237/d22c1ad5-096a-42d4-ac30-6cf14ffe1e2d)

## Common content for both
![image](https://github.com/bcgov/SIMS/assets/61259237/e9699f0e-ae9b-4b48-b361-1ef1aeaa892a)

**Comment by andrewsignori-aot** [comment]
## Demo

Student (Basic BCeID): andrew_signori_1 (Andrew Boni Signori_1)
Institution: SIMS_COLLE
Full-time: 2023000544
Part-time: 2023000545

Steps:
1 - Student: Show the student applications.
2 - Institution: Show the application "Report a change"
3 - Institution: Show the content change and the differences between Part-time and Full-time radio options.
4 - Institution: Report the new scholastic standing on both applications setting May 30 as the new end date.
5 - Student: Show new NOA for both applications with the offering end date.
