### ISSUE TITLE
Update the frontend npm packages (outdated)

### ISSUE THREAD

**Issue by dheepak-aot** [bcgov/SIMS#3043]
**Describe the task**
Run the `npm outdated` command in the web to get the list of outdated libraries and update them to required version.

<img width="867" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE1PQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c494975ffdcbb8cabd62a669539c1180c64f2995/image.png" alt="image.png" />
 

**Acceptance Criteria**
- [x] Update all the outdated packages in SIMS Web, as much as possible use the `lastest` version. The image above is just for reference. Please execute the run the `npm outdated` again for the most updated list.
- [x] Check if some packages are no longer used, for instance, `vee-validate`. If major refactors are needed, no need to remove the package.
- [x] Execute as many updates as possible. If some are still missing please create an appropriate ticket.
- [x] Try to execute as much as possible the straightforward updates first.

**Comment by andrewsignori-aot** [comment]
In continuation of the same effort, epic #3197 was created.
