### ISSUE TITLE
Display through UI that Bypass Restriction rule has been exhausted 

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#3044]
**User Story**
As a ministry user, I want to be notified through interface when a Bypass restriction rule has been 'exhausted' because a disbursement has been sent and the restriction has been 're-applied' 

**Acceptance Criteria:**
- [ ] Create new read-only UI card on a Bypass Restriction history page to indicate when a Bypass restriction rule has been 'exhausted' and is no longer active. 

**Mock-Ups**
Biz to provide

**Biz Context**

**Technical Context**

**Comment by CarlyCotton** [comment]
Closing - encompassed in the functionality in the new ticket for Restriction Bypass.
