### ISSUE TITLE
Manually Adjust Program Length Entries in Database 

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#3046]
**User Story**
As an institution user, I want my programs to be manually updated by SIMS administrators to ensure my program data remains accurate in light of the changes to program length options implemented in February 2024. 

**Acceptance Criteria:**
- [ ] Manually adjust database entries for all 5 schools listed below
- [ ] Email confirmation once complete to hugh.ragan@gov.bc.ca

**Coast Mountain College**
<img width="1030" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmdSQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8bf6b27f8c313d84e54c3326a73c5a5a54b5b203/image.png" alt="image.png" />

**College of the Rockies**
<img width="840" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmtSQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0c2ad23d106dffd5a2b1faeffc6c03cfdc0e7154/image.png" alt="image.png" />

**Stenberg** 
<img width="1004" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2NSQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--40002ad7f9bb97f58f94e2c6bf84d33e17df9b97/image.png" alt="image.png" />

**Rhodes Colleges**
<img width="1062" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2dSQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1e724d193fcce93f2b4f19536257b25d7a15bda2/image.png" alt="image.png" />

**BCIT**
TBC

**Comment by JasonCTang** [comment]
Program lengths updated in PROD DB.
