### ISSUE TITLE
PT Additional Transportation - Calculation Update

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#3047]
**User Story**
As a student, I have a reduction to my additional transportation cost if my weekly KMs are lower than 280. Currently my KMs are not considered in the allowance. We need to consider my weekly travel distance. A reduction is against the kms per week.
As a student in an onsite offering, I need to receive at least my minimum transportation cost even if my additional transportation would be lower.

**Acceptance Criteria**
- [x] Update **calculatedDataAdditionalTransportationMax** :
```
 calculatedDataAdditionalTransportationMax = 
MIN(
(calculatedDataAdditionalWeeklyTransportationCost * calculatedDataAdditionalTransportWeeks),
(calculatedDataAdditionalTransportWeeks * calculatedDataAdditionalKMReduction * calculatedDataAdditionalTransportKM))
```
- [x] Update **calculatedDataTotalTransportationAllowance** in the "More than 0km" path:
```
calculatedDataTotalTransportationAllowance = 
If (offeringDelivered = "onsite") 
MAX(
     (offering weeks - calculatedDataAdditionalTransportWeeks) * dmnPartTimeProgramYearMaximums.limitTransportationAllowance + calculatedDataAdditionalTransportationMax,
    (offeringWeeks * dmnPartTimeProgramYearMaximums.limitTransportationAllowance))
else
    calculatedDataAdditionalTransportationMax
```

**Technical**
- [x] Update `calculatedDataAdditionalTransportationMax` and `calculatedDataTotalTransportationAllowance` as per the business ACs.
- [x] Created the E2E tests to validate the expected output as per the spreadsheet image provided in the **Business Context**.

**Business Context**
Sample test scenarios :
<img width="165" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDhYQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--32b662e4ccc20dcfa6e57530d96f4cddb085b76f/image.png" alt="image.png" /><img width="165" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXdYQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6d7cb4854992eb0031796e7c87c62bc63de1343b/image.png" alt="image.png" /><img width="165" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUVYQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--859baf00712eb7f39a9c0a8bd11292330b823155/image.png" alt="image.png" />
<img width="444" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGdZQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--42f33efce3ea39134abd4ab7d54d481cc4e878b8/image.png" alt="image.png" />

Current calculations:
```
calculatedDataAdditionalTransportationMax =
calculatedDataAdditionalWeeklyTransportationCost * calculatedDataAdditionalTransportWeeks * calculatedDataAdditionalTransportKMReduction
```
```
calculatedDataTotalTransportationAllowance =
if (offeringDelivered = "onsite")
then
  (offeringWeeks - calculatedDataAdditionalTransportWeeks) * dmnPartTimeProgramYearMaximums.limitTransportationAllowance + calculatedDataAdditionalTransportationMax
else
  calculatedDataAdditionalTransportationMax
```

**Comment by Joshua-Lakusta** [comment]
Removed the AC for rounding up to nearest full number. All other lines on NOA have 2 decimal points so larger discussion need if we want to make this change.
