### ISSUE TITLE
Upgrade GitHub Actions 

### ISSUE THREAD

**Issue by andrewsignori-aot** [bcgov/SIMS#3061]
As stated, while GitHub actions are executed _"Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/github-script@v6, actions/checkout@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/."_.

**Acceptance criteria**
- [ ] Check the most updated version for `actions/checkout`. The project currently uses `actions/checkout@v3` and at least the `actions/checkout@v4` is available.
- [ ] Check if any other action needs an upgrade to eliminate the warnings below.
<img width="1597" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFluQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1c5a3882c4e299a1fd25c6834fec9fe22afa49d9/image.png" alt="image.png" />

**Comment by andrepestana-aot** [comment]
@guru-aot if you demo this ticket, just show these links to check that there's no Annotations: 

https://github.com/bcgov/SIMS/actions/runs/10310545523
https://github.com/bcgov/SIMS/actions/runs/10309424973

Thanks!
