### ISSUE TITLE
FT + PT Reports - Enable Reports to BC Publics, Build Offering Details Report

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#3062]
**User Story**
As a **BC Public** institution **Admin** user, I need to be able to pull reports about my institution, offerings and students through SIMS. so that I can determine which students have unmet need as Institutions have additional programs that they can provide to students ontop of SABC awards to help students with unmet need. 

**Acceptance Criteria**
- [x] Create a Reports link that is only accessible by Admin users of BC Public Institutions (see link bottom left on second AC).
- [x] Create the page that allows the approved user to select the report type and indicate the filterable field(s):
<img width="1014" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1UxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7779ab03a72fa93888e6897dc38e74bf88f708b0/image.png" alt="image.png" />
- [x] Program Year is a required drop-down filtering field.
- [ ] Intensity is a required drop-down filtering field with options: Full-time Only, Part-time Only, Full- and Part-time. Treat Full-time as FT Only (Program and Offering), Part-time as FT/PT Program and PT Offering, Full- and Part-time will include anything FT Only & FT/PT (Program) and all offerings. 
- [x] Reports available will have mandatory filters to only show records that are related to their institution code and the students that have applications at their institution. These filters are not shown to the institution user, but should align with what the institution users are able to see when searching for student information manually.
 - [ ] Add report option: Offering Details (see Sample Reports tab in the file linked below, under report titled "Offering Details")
    - Note: Include offerings that could potentially have applications with the following statuses (Creation pending, Approved, Change under review). 
    - Note re Comment from 2024-05-09: Offerings should include Public and Private, not scholastic standing types.
    - Note: Count applications that have been **completed**.

**Business Context**
BC Public institution users have access to their own institution data as well as to student information when they have applied to their offerings/programs. This reporting is to support any manual work on the institution side.
See "Sample Reports" tab of [SIMS Reports & Notification Triggers](https://bcgov.sharepoint.com/:x:/r/teams/03177/_layouts/15/Doc.aspx?sourcedoc=%7B08758022-BBDE-485E-86F9-ED065D92BCFE%7D&file=SIMS%20Reports%20&%20Notification%20Triggers.xlsx=&action=default&mobileredirect=true))

**Technical**

**SECTION 1: Adapt the reporting framework for Institutions:**
	
 - [ ] Reports Page(Form.io page) Share the existing reports form.io component between ministry and institutions.
    - Conditionally display the components based on the report type. (e.g. Student unmet need report requires program year component and NOT the start date and end date). Reports that require start and end date must not display program year and vice versa.
    - Create hidden variables in form to capture which reports needs which component. (e.g. StartEndDateRequiredReports = ['Disbursement_Report','Disbursement_Forecast_Report', etc]. 
 - [ ] Load the report type dropdown from Vue using a static list.(This will be enhanced in the future to load from API)
 - [ ] API from ministry and institutions need to be validated for report types.
 - [ ] API needs to be validated to check if the institution is BC Public (existing decorator) and also the institution user is admin.
 - [ ] Load the program year drop down dynamically from Vue.
 - [ ] Build a Institution/Ministry API for program year drop down.
 
**SECTION 2: Build offering details report**
 - [ ] Add offering details report to the form.io 
 - [ ] Create new dynamic sql for the report offering details. Dynamic SQLs created should be requiring institution id to validate the data retrieved must belong that particular institution.
 - `Offering details` is an offering based report. Build a sql to get all the offerings for the given institution along with count of applications (in completed status). (Considering the PY and Offering intensity input which comes from Report filter)
 - [ ] E2E Tests.

**Comment by HRAGANBC** [comment]
@CarlyCotton awesome. 
- Should we specify which report types are able to be extracted by Institutions? I.e. 'forecasted disbursements' was never intended for Institution use. 
- Are these new reports also available to Ministry, or that will be handled thru seperate tick?
- I think we should specify in AC's that for student unmet need, use only current assessments, and include any applications which are between the point of assessment and archived, inclusive. For offerings report, your 'notes' section is good but I think include as AC.

**Comment by dheepak-aot** [comment]
@CarlyCotton - We have a question that came up during the dev dress meeting. In the offering details report, the spreadsheet says that  `Include all offerings, including pending, approved, overwritten, declined.` Does it mean all the offerings of an institution in all different statuses  in SIMS ??.

In SIMS we have following offering status in place.

`Creation pending, Approved, Creation declined, Change under review, Change awaiting approval, Change overwritten, Change declined`

**Comment by CarlyCotton** [comment]
@dheepak-aot 
I've updated the AC above to clarify which statuses we want to include for the offerings and the matching text in the excel sheet:

> Note: Include offerings that could potentially have applications with the following statuses (Creation pending, Approved, Change under review).

**Comment by andrewsignori-aot** [comment]
@CarlyCotton @HRAGANBC @Joshua-Lakusta can you help with the below questions?

1. Do we know if the list of program years to be displayed will always be the active ones only?
2. Is the expected description the same as displayed for the Student?

@sh16011993 FYI

**Comment by HRAGANBC** [comment]
@andrewsignori-aot  @sh16011993 

1. If the PY is available through the student's dropdown menu when submitting new applications, then we'd want it included in the report. 
2. I think you mean "as displayed for the _school_?" Yes, the same description can be used for the report, regardless whether its extracted by Ministry or Institution

**Comment by andrewsignori-aot** [comment]
> @andrewsignori-aot @sh16011993
> 
> 1. If the PY is available through the student's dropdown menu when submitting new applications, then we'd want it included in the report.
> 2. I think you mean "as displayed for the _school_?" Yes, the same description can be used for the report, regardless whether its extracted by Ministry or Institution

@sh16011993 as per the answer for "1", it is my understanding that only active PY will be displayed, hence no changes are needed.

@HRAGANBC I meant as displayed to the student. The below is the way that we display to the Students; it will be the same way that we will display to the Institution and Ministry if no different direction is provided.
![image](https://github.com/bcgov/SIMS/assets/61259237/8e0c7719-d450-43ba-a7fb-0a2890b88aea)

**Comment by HRAGANBC** [comment]
@andrewsignori-aot @sh16011993 

Thanks  - what the student sees is fine, and can be replicated for the school.

**Comment by andrewsignori-aot** [comment]
@HRAGANBC @CarlyCotton we should include in the report on Public/Private offerings, right?
The Scholastic Standing-related ones should be removed, does it make sense?

**Comment by CarlyCotton** [comment]
@andrewsignori-aot Public and Private offerings should be included. No scholastic standing ones.

**Comment by sh16011993** [comment]
> @andrewsignori-aot Public and Private offerings should be included. No scholastic standing ones.

Thanks @CarlyCotton and @andrewsignori-aot
