### ISSUE TITLE
Content: Student: Start New Application: Apply for funding page Fixes

### ISSUE THREAD

**Issue by astridSABC** [bcgov/SIMS#3064]
**Story Description**
As a **Student**, I will be selecting the program year for when my study dates start.  

**Acceptance Criteria**
- [x]  1.	Update Financial Aid Application statement

- Remove current text: “Apply to see if you are applicable for provincial or federal loans and grant. This is for students attending full-time or part-time post-secondary studies.”

- Replace text with:  “Please select your program year.  This is for students attending full-time or part-time studies.”

<img width="1524" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFF4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5d8cf74e0ecc1bdfa1ab2acbbec6982af2c8d3ff/image.png" alt="image.png" />

<p></p>
<p></p>

- [x]  2.	Update text in “Select program year” dropdown list

- Remove current text: “(2024-2025) – Study starting between August 01, 2024 and July 31, 2025”

- Replace with text: “(2024-2025) – My first day of classes starts between August 01, 2024 and July 31, 2025”

<img width="1213" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3d4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2c219c11ee720d009ed4060d28e6c2a452ef7659/image.png" alt="image.png" />

**Business Context:**
- URL to Apply for Funding Page: https://test-aest-sims.apps.silver.devops.gov.bc.ca/student/application-form/start

**Comment by HRAGANBC** [comment]
Business team source material for updates: https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXd4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--38b0ae2202a3e8b7e62770b598d7286770ff6556/Apply%20for%20funding.docx
