### ISSUE TITLE
Change Request - Free form field for student explanation

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#3071]
**User Story**
As a student, when I submit a Change Request I want to include some details to explain why I'm requesting this change. This helps me communicate about the exceptional circumstances and could result in fewer back and forth interactions with the ministry team reviewing it.

**Acceptance Criteria**
- [ ] Add a freeform text field for each Request A Change form.
- [ ] Display this text from the student to the Ministry user when they view the request.

**Comment by Joshua-Lakusta** [comment]
This is being closed as it will be covered under the change request revamp work. @CarlyCotton if you feel we need this before the work on change request is done then we can reopen and prioritize.
