### ISSUE TITLE
Generate e-Cert Feedback File Error Report

### ISSUE THREAD

**Issue by andrewsignori-aot** [bcgov/SIMS#3072]
#2536 is a related ticket handling how these errors are communicated to the student.

**Description of Task**:
Trigger specific actions anytime we receive eCert feedback file records for specific student records. 

**Acceptance Criteria**
- [x] Configure a new report type called "eCert Errors" extractable through the Ministry interface which can be used to extract **all** eCert errors received between certain dates. Columns of the file should be consistent with the above section called "What's included on each report"
**What's Included on Each Report**
Each disbursement represents a distinct record/line on the report
- eCert Number
- Application Number
- Student First and Last Name, DOB
- Indication of which file logged the error (eCert feedback file)
- Student Study start and end dates
- Date the error was logged
- List of all error codes (**not** just the filtered ones) detected for each disbursement  (see the additional context section below for list of possible errors)
- [x] When extracting report through interface, Start and End date filter should correspond to the dates when errors were logged
- [x] The report should contain FT and PT applications in one report
- [x] No MVP functionality to track action/status on these errors. This will be handled by SABC in JIRA. 

**Technical**

- [x] "Date the error was logged" from business AC should be the date_received from sims.disbursement_feedback_errors table.
- [x] Report date based on the date_received from sims.disbursement_feedback_errors table.
- [x] FT and PT filter should follow the same from the other reports.
- [x] When extracting the report through the interface, display ALL error codes (i.e. use the 'complete' list).
- [x] E2E

**Context:**
The federal service provider (NSLSC/Finastra) sends a daily eCert Feedback file which sometimes contains error codes for particular applications disbursement requests. These error codes indicate there was at least one error in the list of validations which exist on the NSLSC side. For e.g., the address listed on a student's application is not recognized, or a student is missing a first name. 

Some of the errors do not block the disbursement from being issued, but others do. For any errors which block disbursement, the student's application and disbursements are now completely in limbo and will not get resolved unless someone within SABC takes an action to resolve. However, without knowledge of which students have errors, there is no way for SABC staff to know which applications need attention.

**Comment by CarlyCotton** [comment]
Had a message with Guru and updated AC to confirm change of column name:

> Each disbursement represents a distinct record/line on the report:
> **eCert #** to **eCert number**
> Application Number
> Student First and Last Name, DOB
> Indication of which file logged the error (eCert feedback file)
> Student Study start and end dates
> Date the error was logged
> List of all error codes
