### ISSUE TITLE
1.3.1 Label Headings - Supporting Partner- Accessibility Fixes - Level A -Info and Relationships

### ISSUE THREAD

**Issue by michesmith** [bcgov/SIMS#3083]
**User Story**
As a Supporting Partner who is visually impaired, I need to headings to be tagged appropriately so my screen reader software can recognize them. 

**Acceptance Criteria**
Add or fix heading tags to the following pages: 
- [x] Supporting user login page
    - [x] Change tag to (h2)
<img width="1470" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2U1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ca3a6a7b8ad768780b689aa7b00904d8856a8e5b/image.png" alt="image.png" />
- [x] Supporting user dashboard page
    - [x] Add heading tags for 
        - [x] Welcome! (h1)
        - [x] For parents (h2)
        - [x] For partners (h2)
- [x] Supporting information form (partner and parent) 
    - [x] Update "Search for Application" tag from (h2) to (h1)
<img width="1747" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWE1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--92b9e0591b10c4e299d27a2e4b6417819b06446a/image.png" alt="image.png" />

**Context:**
- This issues were uncovered through accessibility audit via CITZ.  
- The finding was the Headings are mislabeled or unidentified
- Detailed Spreadsheet for Student s inserted inline and also attached here: [2024_Supporting Information_Audit.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1RsQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--401fd26be3124e38981234d207ea635590b5dcd2/2024_Supporting%20Information_Audit.xlsx)
- Information, structure, and relationships conveyed through presentation can be programmatically determined or are available in text.

Reference for headings and accessibility:  
https://accessibility.psu.edu/headingshtml/#heading 

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTNuQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--668e24293ee48789325d9def6b7a48bc99282265/image.png" alt="image.png" />

**Comment by HRAGANBC** [comment]
@JasonCTang Can you go through the headings and make sure the heading tags are ordered properly? This is for all supporting user (parents &partners) pages. 

Ping us if you need context
