### ISSUE TITLE
2.4.2  Titles- Supporting Partner Accessibility Fixes - Level A- Page Titled

### ISSUE THREAD

**Issue by michesmith** [bcgov/SIMS#3089]
**User Story**
**As a Supporting Partner I need to each page title to describe the topic or purpose so that I can understand what to expect on each page 

**Context:**
- Theses  issues were uncovered through accessibility audit via CITZ. 
- Detailed Spreadsheet for Student s inserted inline and also attached here: [2024_Supporting Information_Audit.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1RsQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--401fd26be3124e38981234d207ea635590b5dcd2/2024_Supporting%20Information_Audit.xlsx)
- Web pages have titles that describe topic or purpose. [W3 Reference](https://www.w3.org/WAI/WCAG22/Understanding/page-titled.html)

**The Problem**
- Not all pages have a title / heading 1.

**Acceptance Criteria**
- [ ] Assign a unique title to each page in the Supporting Partner Portal 
- [ ] Welcome to StudentAid BC 
- [ ] Login with BC Services Card 
- [ ] Welcome! (Start submission) 
- [ ] Search for application 
- [ ] Supporting information form 

<img width="1878" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHRKQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--54a22a2fd34d0083b8112ea7b4ceb836aa835ad1/image.png" alt="image.png" />

**Comment by michesmith** [comment]
@HRAGANBC @CarlyCotton @Joshua-Lakusta  Who decides titles- BA's?

**Comment by CarlyCotton** [comment]
@michesmith This is possibly something that needs to be addressed at the code level and not solely as a forward facing content piece. This seems to be referring to the actual title tag on pages highlighted below. They all seem to be defaulted to "StudentAid BC". 
<img width="752" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2RNQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dac953d5239435e2cb0d32419be1e982cbb7e373/image.png" alt="image.png" />

<img width="1336" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzVNQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--904085e95abaa23f38b0d9bde03c51e0ba2b3560/image.png" alt="image.png" />

**Comment by HRAGANBC** [comment]
@CarlyCotton to be completed using URL paths to propose page titles. 

Not urgent

**Comment by ninosamson** [comment]
@CarlyCotton @michesmith Proposing we close this as #3083 will implement by adding H1 tags.
