### ISSUE TITLE
Application - Accessibility/Usability - Submit Button Location

### ISSUE THREAD

**Issue by michesmith** [bcgov/SIMS#3112]
**User Story**
As a student, I need the submit button to be available at the end of the form flow so I can tab and submit. 

**Acceptance Criteria**
- [ ] Add the Save draft (if visible)/Submit application buttons to the bottom right of the "Confirm Submission" tab of the application.

<img width="1283" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2VJQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e99afc1fd5d19d69eab6f15444b039af49859c30/image.png" alt="image.png" />

**Context:**
- These issues were uncovered through accessibility audit via CITZ ( 1.3.2 Submit Button- Student- Accessibility Fixes - Level A - Meaningful Sequence ) & again on the usability testing
- Detailed Spreadsheet for Student s inserted inline and also attached here: [2024_Student Application_Audit.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0xsQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--578821d4addd12c1babcafba5c861e1f5456bc9c/2024_Student%20Application_Audit.xlsx)

**Comment by CarlyCotton** [comment]
Updated ticket to make it more cohesive between the accessibility and useability feedback.

**Comment by dheepak-aot** [comment]
Confirmed with @CarlyCotton that `Save Draft` button at bottom is only required on the last page, unlike the `Save Draft` button on the top.
