### ISSUE TITLE
Provide descriptions for fields stored in JSONB data types in the SIMS database

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#3116]
## User Story
As the enterprise datawarehouse DBA, I need to understand what the fields stored in JSONB data types represent.  This information is subject to change, so a living document must be produced and kept up to date.

## Additional Context
Attached is a spreadsheet of all the fields identified from the SIMS DEV database as of April 8th. Fields are organized by table.column_name. 
[SIMS_jsonb_fields_20240404.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemxQQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8471e730ff431102b976a4417306ce515a4e10dd/SIMS_jsonb_fields_20240404.xlsx)

## Acceptance Criteria
 - [ ] Produce living document containing a table with descriptions/labels of the fields stored in specified JSONB data types in the database.

**Comment by CarlyCotton** [comment]
@JasonCTang Can you get a more current file with the values in it so I can provide descriptions?

**Comment by ninosamson** [comment]
Bringing back to soap for discussion. Also still need a more current file.

**Comment by ninosamson** [comment]
Closing as separate task outside of scrum team.
