### ISSUE TITLE
Build Ministry-Specific Reports - Institution Designation

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#3132]
Follow-Up to #2580

### **User Story**
As a Ministry user, I want to be able to extract dedicated reports to support day to day operations and workload. These reports will help me understand the designation status of institutions (and upcoming expiration), the approval status of programs and offerings, and identify students from a specific institution and/or program.

### **Acceptance Criteria:**
- [ ] **Build a report titled "Institution Designation".** 
    - Date Range Filter: This should include all institutions with an assessed date OR expiry date within the date range specified.
    - Report Field Notes: Assessed date is the date that the Approved or denied action was taken.
    <img width="383" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1ptQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--df3e732ff59ec729cf49aeefb06b2e1d34d60e92/image.png" alt="image.png" />
    - Each location should be it's own record.
    - File Layouts should be consistent with the table in the "Sample Reports" worksheet of the attached file:
<img width="1353" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2xtQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bbccf64656b65af7510f730cf5bf83ca007b2fc5/image.png" alt="image.png" />

### **Business Context**
[Sample Reports Worksheet](https://bcgov.sharepoint.com/:x:/r/teams/03177/Shared%20Documents/DEVS/Reports/SIMS%20Reports%20%26%20Notification%20Triggers.xlsx?d=w08758022bbde485e86f9ed065d92bcfe&csf=1&web=1&e=BgvbWd)

**Technical Context**
 - [x] Create a entry in the report_configs table to populate the dropdown in the ministry reports screen.
 - [x] Create a sql to fetch all the institution with expired -> designation_agreements -> end_date  **OR** assessed date -> designation_agreements -> assessed_date from the date provided in the date fields from institution table, Primary Contact Name -> institution->primary_contact(add 2 columns for the last and the first name), Primary Contact Email -> institution->primary_email .
 - [x] Update formio for the drop down value "Institution Designation". Note: The functionality to hide the offering intensity should be done already in the previous ticket, use it to hide.
 - [ ] E2E tests

**Comment by sh16011993** [comment]
@CarlyCotton As per our discussion in the meeting together with @andrewsignori-aot , here are the takeaways:

1) If a new location was added and never requested for designation, it would not show up in the report.
2) The report generated will have the following three columns ("Request for designation", "Approved for designation", "Designation Status") in addition to the other columns already mentioned in the spreadsheet, mimicking how the representation happens in the UI.

@CarlyCotton  Can you please confirm if they are correct. Thanks!

**Comment by CarlyCotton** [comment]
@sh16011993

All good on this end. Thank you for clarifying.
