### ISSUE TITLE
Build student unmet need report for BC Public Institutions

### ISSUE THREAD

**Issue by dheepak-aot** [bcgov/SIMS#3133]
**User Story**
As a **BC Public** institution **Admin** user, I need to be able to pull reports about my institution, offerings and students through SIMS. so that I can determine which students have unmet need as Institutions have additional programs that they can provide to students ontop of SABC awards to help students with unmet need. 

**Acceptance Criteria**

- [x] Program Year is a required drop-down filtering field.
- [x] Intensity is a required drop-down filtering field with options: Full-time Only, Part-time Only, Full- and Part-time. Treat Full-time as FT Only (Program and Offering), Part-time as FT/PT Program and PT Offering, Full- and Part-time will include anything FT Only & FT/PT (Program) and all offerings. 
- [ ] Reports available will have mandatory filters to only show records that are related to their institution code and the students that have applications at their institution. These filters are not shown to the institution user, but should align with what the institution users are able to see when searching for student information manually.
- [ ] Add report option: Student Unmet Need (see Sample Reports tab in the file linked below, under report titled "Student Unmet Need")
    - Note: This is a report regarding applications. Include only the most recent assessment for applications from Assessment to Complete status and ignore Archived & cancelled states.

**Business Context**
BC Public institution users have access to their own institution data as well as to student information when they have applied to their offerings/programs. This reporting is to support any manual work on the institution side.
See "Sample Reports" tab of [SIMS Reports & Notification Triggers](https://bcgov.sharepoint.com/:x:/r/teams/03177/_layouts/15/Doc.aspx?sourcedoc=%7B08758022-BBDE-485E-86F9-ED065D92BCFE%7D&file=SIMS%20Reports%20&%20Notification%20Triggers.xlsx=&action=default&mobileredirect=true))

**Technical**
 - [x] Add student unmet need report to the form.io 
 - [ ] Create new dynamic sql for the report student unmet need. Dynamic SQLs created should be requiring institution id to validate the data retrieved must belong that particular institution.
  - `Student unmet need` is an application based report. Build sql to get the current assessment details of all the applications which belong to the given institution which has application status `Assessment` , `Enrolment` or `Completed` and is not archived. (Based on spreadsheet provided).
   (Considering the PY and Offering intensity which comes from Report filter)
 - [ ] E2E Tests.

**Comment by andrewsignori-aot** [comment]
@CarlyCotton we left some questions in the spreadsheet. Can you please take a look?

**Comment by CarlyCotton** [comment]
@andrewsignori-aot 
<img width="394" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFNJQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--29b1a348c7a7e6dde81f05a5b553f8be754d9277/image.png" alt="image.png" />
**Intensity:** no need to translate. FT or PT is fine.
**Profile Disability Status:** a Y/N flag is fine (Y = approved for any disability status, N = requested/not requested/declined). We can also accept a readable version of whatever the full status is.
**Application Disability Status:** Application answer. 

**Study Start/End Date Format:** YYYY-MM-DD

**Comment by CarlyCotton** [comment]
@sh16011993  Removed an AC related to offering status that wasn't relevant to the report.
