### ISSUE TITLE
Display Warning Message to Student when Inputting Application End Dates within next 6 weeks 

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#3135]
**Story Description:**
As a student, I want to be notified immediately of possible barriers when attempting to apply to a study period which ends within the next 6 weeks. 

**Acceptance Criteria** 
- [ ] Create validation on student application form which checks whether study end dates are <= today's date +6 weeks. 
- [ ] Display warning banner when validation is flagged which reads: "Warning: you may be required to submit a study end date appeal.... TBD"

**Business Context:**
- PIR date entries are not impacted.??
- Related to alternative process work

**Comment by CarlyCotton** [comment]
Closing - going to handle as part of #2997.
