### ISSUE TITLE
UX Accessibility for Institution Location

### ISSUE THREAD

**Issue by abschwenker** [bcgov/SIMS#318]
### Additional Context

- Use #1076 accessibility guideline for form template
- Location summary
- Location edit

### Acceptance Criteria

- [ ] Mockup Institution Details (FIGMA)
- [ ] Ensure headers match design system and patterns 
- [ ] Ensure colours used match design system and patterns
- [ ] Ensure no issues on page was flagged during accessibility audit
- [ ] Add NOTES for dev noting change

**Comment by abschwenker** [comment]
![image.png](https://images.zenhubusercontent.com/5fce9c77aab275719112dc74/6b851509-4822-47dc-abed-4cd5fe9b035f)

**Comment by IrenaMilosevic1** [comment]
Approved
