### ISSUE TITLE
Virus Scanning - Enable Server Deployment OpenShift and locally

### ISSUE THREAD

**Issue by sslaws** [bcgov/SIMS#3180]
**User Story**
As a Security Analyst for SIMS, I would like to ensure that malware is not propagated VIA SIMS due to the reputational risk and as such require that all files received via SIMS are scanned. The scan happens at regular intervals rather than in real-time which means that it can be handled asynchronously instead of right away when the file is received.

**Acceptance Criteria**

- [x] Add a ClamAV docker into our existing docker-compose. If any challenges are found check an alternative way to make it available for local development.
  - [x] Add ClamAV as a API dependency in docker-compose.
- [x] ClamAV configuration must align with SIMS file upload maximum. 
- [x] Create ClamAV automatic deployment to the Openshift.
  - [x] Follow the instructions in the context for extracting the proper YAML file.

**Context**
- Deployed into a6ef19-dev via Helm, requires limits of 3GB RAM and 1CPU per pod
A [Common Service](https://bcgov.github.io/common-service-showcase/services/cavms.html) exists for the signature files.
- Common Service deployment [source](https://github.com/bcgov/common-hosted-clamav-service)  
- Clone and create deployable YAML`helm template dev . --namespace licenseplate-dev`
- Run locally via docker `docker run -it --rm --platform linux/amd64 -p 3310:3310 --name clamav ghcr.io/bcgov/clamav-unprivileged:ca3d42f3dde3c5aa9bcab636f752119bbe6a67e8`
- [Sample code](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1dVQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--736af41447165f1f912cdfc83721e8d68e18ded4/clamtest.zip)
uses Docker above, unzip and perform npm i then npm start

- For a Virus HIT update eicar.txt and replace text with
`X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*`

**Comment by ninosamson** [comment]
Requested confirmation of approach to defer scanning to scheduled scans.

**Comment by guru-aot** [comment]
Wiki updated for clamav installation in openshift and local development.
https://github.com/bcgov/SIMS/wiki/DevOps-and-Running-the-Application#clamav-setup
