### ISSUE TITLE
Generate e-Cert Feedback File Error Ministry - Notification

### ISSUE THREAD

**Issue by andrewsignori-aot** [bcgov/SIMS#3183]
#2536 is a related ticket handling how these errors are communicated to the student.

**Description of Task**:
Trigger specific actions anytime we receive eCert feedback file records for specific student records. 

**Acceptance Criteria**
- [ ] Send an email to studentaidbc@gov.bc.ca for every student **disbursement** which contains at least one error from eCert feedback files (PT and FT are separate files). Disbursement must contain an error code from the **filtered** list to trigger an email
- [ ] Email should contain:
>  Subject line: eCert Error - [Last Name] 
> The following student received at least one eCert errors. Use the data report feature to review details.
> Student: ((givenName)) ((lastName))
> Application: ((applicationNumber))
> Error Code(s): ((errorCode1, errorCode2, errorCode3, etc))

**Technical**

- [x] Create a new GC Notify template.
- [x] Create the DB migrations for the new email notification.
- [x] Only generate the notification if the existing errors are flagged as `block_funding` in table `sims.ecert_feedback_errors`.
- [x] Create the SQL to manually update on PROD email address and add the manual instructions to the release.
- [x] Add E2E tests
  - Test if a notification is generated for an error marked as  `block_funding`.
  - Test if a notification is not generated for an error NOT marked as  `block_funding`.

**Context:**
The federal service provider (NSLSC/Finastra) sends a daily eCert Feedback file which sometimes contains error codes for particular applications disbursement requests. These error codes indicate there was at least one error in the list of validations which exist on the NSLSC side. For e.g., the address listed on a student's application is not recognized, or a student is missing a first name. 

Some of the errors do not block the disbursement from being issued, but others do. For any errors which block disbursement, the student's application and disbursements are now completely in limbo and will not get resolved unless someone within SABC takes an action to resolve. However, without knowledge of which students have errors, there is no way for SABC staff to know which applications need attention. 

**Additional Context - List of Error Codes Which can be Received**
This is a complete list of error codes which can be received for FT and PT eCert feedback files, as well as a filtered list which captures all the errors which result in blockage of funding. Only the **filtered list** should get used in this ticket.
[eCert Error Codes (Consolidated and Filtered).xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2VWQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4c779c3ebb3e63c238a0d1645759d7e9aea2c3f6/eCert%20Error%20Codes%20%28Consolidated%20and%20Filtered%29.xlsx)

**Comment by sh16011993** [comment]
@CarlyCotton  @Joshua-Lakusta @HRAGANBC For student disbursements which contain more than one error from the eCert feedback file, if some of those errors are marked for `block_funding` while others aren't marked for `block_funding`, then what should be the system behavior? I believe the expectation is that as long as there is even a single error code related to a student disbursement that is marked for `block_funding`, we send a notification to the ministry.

Please correct me if I am wrong. Thank You.

**Comment by HRAGANBC** [comment]
@sh16011993 

Correct, we only want to notify the Ministry for each student with _at least one_ `block_funding` restriction. And regardless of how many distinct errors are present for each student, only send one notification to the Ministry.

**Comment by CarlyCotton** [comment]
@sh16011993 Updated the AC regarding the email template

FYI @HRAGANBC
