### ISSUE TITLE
Content: Institution: Create program: “SABC program code” text box label Fixes

### ISSUE THREAD

**Issue by astridSABC** [bcgov/SIMS#3185]
**User story:**
As an institution, I want to enter a SABC program code or 3 letters and 1 number (XXX#) so that I can us the bulk “Offerings Upload” feature to import many offerings at one time.

**Acceptance Criteria**
- [x] On SABC Program Code Field, make following changes to align with the mock-up:
    - Revise field name, 
    - Revise text beneath field (capitalize Offerings Upload)
    - Add tooltip 
    
**Mock-Up:**
<img width="988" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUNKQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a23b7aae00f82e59e651208051fd245be3186fc5/image.png" alt="image.png" />

**Business context**: If the SABC program code is not entered when the program is created, the institution cannot use the bulk offering upload feature.  Institutions are currently using this feature.

**Comment by astridSABC** [comment]
@HRAGANBC The mockup that you used might be a better option.

**Comment by HRAGANBC** [comment]
Thanks, @astridSABC 

Please see my adapted wording. The more concise the better - helps cut down on miscommunication and expedites grooming process.

**Comment by astridSABC** [comment]
@HRAGANBC this issue seems to be the same as #3139
