### ISSUE TITLE
Wildcard Cert

### ISSUE THREAD

**Issue by sslaws** [bcgov/SIMS#3192]
**User Story**
As a SIMS team member with the number of environments (dev, test, staging, qa, prod) and EDW Extra routes the use of a wildcard certificate will streamline deployment and annual requests.

**Acceptance Criteria**
- [ ] Generate CSR and Certificate using emailed CNF file
- [ ] Securely store certificate and private key
- [ ] Make available the certificate and private key to dev team for deployment

**Comment by ninosamson** [comment]
After investigating UCC cert, will proceed with wildcard request.
