### ISSUE TITLE
New OCP Routes

### ISSUE THREAD

**Issue by sslaws** [bcgov/SIMS#3193]
As a Product Owner, as we get closer to the launch of sims we need to have URLs that better reflect out branding.

**Acceptance Criteria**
- Existing routes should be maintained and these new routes will be applied.
- Update the routes for dev, test, staging and prod web-sims
    - [x] Dev = https://dev.sims.studentaidbc.ca
    - [x] Test = https://test.sims.studentaidbc.ca
    - [x] Staging = https://staging.sims.studentaidbc.ca
    - [x] Prod = https://sims.studentaidbc.ca
    - [x] Forms = https://*-forms.sims.studentaidbc.ca (not publicly exposed). One per environment. 
- [x] Keycloak clients will need to be updated with the web origins and redirect URLs above per corresponding KC env 
- [x] All routes need the SIMS cert installed
-  For each environment using the web-sims base-url add the following routes
     - [x] Path /api for api-sims
     - [x] Path /swagger for api-sims (one is already in place for Swagger and should be removed before the new deployment happens).
     - [x] Path /admin/queues for queue-consumers 
- [x] All routes should be configured as insecure edge termination redirect
- All routes should have the following annotations applied:
    - [x] haproxy.router.openshift.io/balance: leastconn
    - [x] haproxy.router.openshift.io/disable_cookies: 'true'
    - [x] haproxy.router.openshift.io/hsts_header: max-age=31536000;includeSubDomains;preload
    - [x] haproxy.router.openshift.io/timeout: ??s
        - [x] Replace ?? with the longest query timeout expected - default is 30 seconds
- [x] Create Github secrets **at the repository** level for the new route properties: `certificate`, `key`, and `caCertificate`.
  - [x] Adjust the deployment configs to have the new properties configured. Use this [route](https://console.apps.silver.devops.gov.bc.ca/k8s/ns/0c27fb-dev/routes/tls-dev-edwapi/yaml) to retrieve the values for the properties to be applied to all environments.
  - [x] Update the wiki for the KC changes
  - [x] Ensure release instructions are updated to capture all of the changes
  - _Please note, that these properties are sensitive and should not be exposed in any way._
          
**Other Context**
Sample working routes exist using the cert in dev are called tls-dev-edwapi and tls-dev-swagger
EDW Extract will be /edwapi and is excluded from this ticket
Other environments in dev (performance, load etc) can be migrated to new URLs or left as is.

**Comment by ninosamson** [comment]
just reviewing this ticket - URLs should be "studentaidbc.ca" not "studentaid.bc.ca" @sslaws

**Comment by ninosamson** [comment]
just reviewing this ticket - URLs should be "studentaidbc.ca" not "studentaid.bc.ca" @sslaws

**Comment by ninosamson** [comment]
can we maintain generic routes for lower environments for a bit before we remove?

**Comment by sslaws** [comment]
@ninosamson is correct and I've updated the description with the correct URL.

**Comment by sslaws** [comment]
@ninosamson we can maintain multiple routes

**Comment by ninosamson** [comment]
thanks @sslaws

**Comment by sslaws** [comment]
NOTE, the annotations are from other projects that have had security scans and will resolve #3610 which I'm recommending we close as implemented in this ticket.

**Comment by sslaws** [comment]
Ready for someone to pickup

**Comment by andrewsignori-aot** [comment]
@ninosamson @sslaws After some tests it was not possible to change the form.io server to use a path instead of the domain URL as it is right now which will make not possible to attend the AC that state "Path /forms for forms".

Form.io server has a default.config file that apparently would allow it but there was no success.

![image](https://github.com/user-attachments/assets/ba143740-e656-4aba-bca1-99177ae6bc75)

Also doing a quick search in the form.io source code, the `basePath` does not seem to be used much.
Right now the option would be to proceed using the sub-domain for form.io server only (e.g. dev-forms.sims.studentaidbc.ca).

**Comment by ninosamson** [comment]
@andrewsignori-aot - this is fine by me. I will remove the AC and update the first set of ACs to indicate we will have a subdomain for forms as well.

**Comment by andrewsignori-aot** [comment]
## Demo

### Institution

<img width="1106" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2lLQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9ed25d2d18345b003c357037b30bed3115fb2f5f/image.png" alt="image.png" />

### Ministry

<img width="1101" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3VLQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2b23c38ceb94e70ed2044dfba9abef7fb24bf133/image.png" alt="image.png" />

### Student

<img width="1102" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3lLQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ca7eb6e5cc8a62809630e654089f9e688f3f50e5/image.png" alt="image.png" />

### Supporting Users

<img width="1094" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOENLQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c859a85442abcd49dc815d33cf8b808887bc8bf7/image.png" alt="image.png" />
