### ISSUE TITLE
Create QA Environment for Integration Testing

### ISSUE THREAD

**Issue by sslaws** [bcgov/SIMS#3195]
As a project team, we want an isolated environment to facilitate end to end integration testing in order to increase our confidence of our builds and deployments.

**Acceptance Criteria:**
- [ ] Create a new automation environment for SIMS in namespace a6ef19-dev
- [ ] The environment URLs should use QA
- [ ] It should use all standalone components (forms, DB etc)
- [ ] Keycloak will use test
- [ ] Camunda will use Test or new environment. @ninosamson to ask Camunda about another cluster for separate environment. 
- [ ] GC Notify will get a new key
- [ ] GH Action to deploy on request
- [ ] SFTP Folders will be unique on Test instance
- [ ] Schedule a 1-hour call with DEV team to go over the initial steps of creating a new environment as knowledge transfer.

**Comment by ninosamson** [comment]
Moving this to 2.X as it is not priority.

**Comment by ninosamson** [comment]
Changing priority to SIMSMAS - would be useful to have this environment available for integration testing.

**Comment by ninosamson** [comment]
Closing this issue as obsolete. We will develop other processes for manually testing in lower environments with partners.
