### ISSUE TITLE
Provide Ministry Ability to Edit Student Basic BCeID Profile Info

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#3222]
**Story Description**
As a Ministry user, I want to be able to edit critical details of a BasicBCeID student's profile and contact info, so that a student's info can remain accurate and up to date. This also allows me to identify the type of login credentials the student has used to log in, which can help me identify where they need to go for login/password issues.

**Acceptance Criteria:**
- [ ] Enable Ministry to edit profile details of a **Basic BCeID** student's account. (Given Names,  Last name, DOB, and email)
- [ ] Create an edit button that allows the update of the 4 fields listed above.
- [ ]  Anytime a single, or multiple fields are edited, Ministry user must add a note. (General)
- [ ]  Treat this like a personal information change from BCSC logins and do a new SIN verification for any DOB, Given name, or Last name (not case-sensitive changes "C" to "c")
- [ ]  Replicate the role for account approval of Basic BCeID and create a new one.
- [ ]  Update the role spreadsheet
  
**Business Context**
- Before BasicBCeID account _approval_, Ministry can edit fields and then approve
- After BasicBCeID account approval, Student can edit only their address info, but not their profile details. Ministry can not edit anything on behalf of a student. Process would require student to submit new account, and historical account details would _not_ be imported. 
- Currently, we receive personal information updates on BCSC accounts on each log in by the student and will update accordingly. If DOB, First Name, or Last Name (not case-senstive) change, this will automatically trigger a new SIN verification process. 
- Changing the personal information for a BCeID profile (DOB, Given Name, or Last Name) will start a new SIN verification process.

<img width="1325" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHVxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ef5b9f7d18f3bfdb08268e1cc64060dd76ac5128/image.png" alt="image.png" />

Note: disability status and SIN update processes do not need to be changed.

**Technical**
- [ ] Student users authenticating using BCeID can be identified using the `sims.users.identity_provider_type` as [bceidboth](https://github.com/bcgov/SIMS/blob/b49899306af5a325c794e2dbfff9aaacc8068d01/sources/packages/backend/libs/sims-db/src/entities/identity-providers.type.ts#L13). Please note that `bceidbasic` and `bceidbusiness` are present on DB enum but are not configured.
- [ ] Create a new button in the top-right (same as other areas) enabled only for BCeID students.
  - [ ] Create a new role to restrict the action.
- [ ] Create a modal to edit the required fields below, applying the same validations from the student profile (same for notes).
  -  Given name
  -  Last name
  -  Date of birth
  -  Email
  -  Note
- [ ] Add note to the student notes. The note should be created using the shared method [createStudentNote](https://github.com/bcgov/SIMS/blob/1e08be02c368cb17ec55b8ace0218a920d477990/sources/packages/backend/libs/services/src/note/note.shared.service.ts#L21). No need to persist the generated note ID to the students or users table. Apply the same validations for other areas collecting notes.
- [ ] Create a new endpoint to allow the student to update.
  - [ ] Validate if the student is a BCeID student.
  - [ ] Suggested endpoint: `PATCH` "aest/student/:studentId".
- [ ] E2E Test
  - Should allow student profile update when the student is authenticating using BCeID.
  - Should throw an HTTP exception if the student profile is updated when the student is not authenticating using BCeID.

**Comment by AnnaPBashkatova** [comment]
Additional information to consider: As a Ministry User I can not distinct between BasicBCeID and BC Services Student account once they are created. BC Services student account profile updates must be directed to Service BC and BasicBCeID dealt in the house. How as a Ministry User can I tell which case am I dealing with? Confirm with student verbally?

**Comment by HRAGANBC** [comment]
@AnnaPBashkatova - You're right, however there is _some_ way to distinguish --- the Ministry user can search through JIRA history to see if a ticket was created when this student initially requested account creation. 

Given there is an alternative way of accomplishing this task - however unpleasant - I would deem your suggestion as 'non-critical' for MVP. 

That being said, can you please log a quick barebones ticket to capture that nuance, and we can discuss and triage to a post-MVP release?

**Comment by AnnaPBashkatova** [comment]
@HRAGANBC. Thank you, Hugh. Created separate ticket #3244.

**Comment by andrewsignori-aot** [comment]
@JerPearson @CarlyCotton While updating first name, last name, or DBO we also trigger a new SIN validation.
We will do the same reusing the method already in place for when the BCSC student changes his data. So, when the Ministry updates the BCeID user data it will trigger a SIN validation. It would be good to make it explicit in the AC to be clear for QAs in the future.

**Comment by CarlyCotton** [comment]
@andrewsignori-aot Thank you - I've added business context and an AC to treat this similarly to the BCSC process that happens already.

FYI @sh16011993 @JerPearson

**Comment by JerPearson** [comment]
I think that's a great idea.  Would be very helpful for staff and aligns the outcomes for both paths.

**Comment by sh16011993** [comment]
Thank You @andrewsignori-aot and @JerPearson. Code updated accordingly.
