### ISSUE TITLE
Create history/journal tables  for auditing purposes

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#3223]
***User Story***
As a Privacy and Security Officer (David Malcolm), I need the ability to determine when student profile records were updated, what was updated and who updated them.

***Additional Information***
Tables to create journal table for: 
- users
- students
- supporting_users
- institutions
- institution_locations
- education_programs
- education_programs_offerings

When to create journal entries
- Insert a new record in the original table and then insert a clone of the record in the corresponding journal table
- Update the update_at, modifier & modified fields in the original table, and then insert a clone of the record in the corresponding journal table.

***Acceptance Criteria***
- [x] Create journal tables for the tables listed above
- [x] Implement triggers and stored procedures to insert records into journal tables.

**Technical**
- [x] Create the new triggers on DB for `Insert` and `Update` operations.
- [x] Create new tables appending a suffix like `_history`.
- [x] Duplicate the table structure by adding the below columns.
  - [x] Operation type: `Insert`, `Update`.

**Some References**
https://www.postgresql.org/docs/current/sql-createtrigger.html

**Comment by sslaws** [comment]
Jason to determine what tables we need to journal.

**Comment by sslaws** [comment]
Removing high priority as its pushed to 2.1

**Comment by andrewsignori-aot** [comment]
@JasonCTang @ninosamson we may need to review the apps and also the understanding of the creator/modifier, how they work right now, and the expectation.
Many times the creator will be the "system user", for instance, while processing Camunda workflows. Usually, the DEVs are just taking a best guess.
It was also introduced a long time and many places may not be saving it.
Just to be clear, journal table records are created, creator/modifier should be there most of the time but it is not guaranteed right now.

**Comment by andrewsignori-aot** [comment]
## Demo

Tested on DEV the below scanrions to produce inserts and updates in the required tables.

- Created a new basic BCeID users and created the account  after Ministry approval.
- Ministry creates new institution.
- Institution creates and edit locations.
- Institution creates and edit programs.
- Institution creates and edit offerings.
- Student create an application with supporting users.

Please see below some screenshots with records inserted to the history tables.

![image](https://github.com/user-attachments/assets/b1e999a1-4cb7-480f-9fe5-8941b65681f4)

![image](https://github.com/user-attachments/assets/68fcf254-a292-432e-8841-9e5248a74193)

![image](https://github.com/user-attachments/assets/3bf42e78-7edf-4b26-990a-51f61aa92f95)

![image](https://github.com/user-attachments/assets/d3e8cd9f-b0ae-45a7-8d5b-30ddaf93cc36)

![image](https://github.com/user-attachments/assets/10f867fc-0e91-40f4-b729-f74c0faf2a86)

![image](https://github.com/user-attachments/assets/6c8581d4-e1de-44f8-a397-f70f2eae6dc7)

![image](https://github.com/user-attachments/assets/4d065145-66df-40e6-8364-5e8e1d3f7eb8)
