### ISSUE TITLE
Bug in TEST: Institution View of Student Details is Blank 

### ISSUE THREAD

**Issue by astridSABC** [bcgov/SIMS#3224]
**Describe the Bug**
Test institution portal: No data displayed on Student details page

<b>Steps To Reproduce</b>
1. Submit student application to a BC Public school inTEST
2. Log in as a BC Public institution user into TEST
3. Select “Search student” > select student. Click 'view' 

<b>Expected result</b>
Institution can view info within each tab on the students profile

<b>Actual Result</b>
All fields in all tabs of the student account are blank

<img width="999" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTI1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--caba21ce79ce6f1048b345a4f35dc15e0f4f07b9/image.png" alt="image.png" />

**Comment by michesmith** [comment]
Closing as we cant replicate it now.
