### ISSUE TITLE
Ministry Reports - Student Assessment Details

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#3236]
**Story Description:**
As a Ministry user, I want to be able to view details about a student's assessment so that I can see more detail and support a student through complex questions that cannot be resolved using the assessment information presented through the SIMS interface. 

**Acceptance Criteria:**
- [ ] Optional Report-Specific Filter - Student SIN or Application #. This allows pulling report with single student.

**Comment by michesmith** [comment]
Include more information on the Notice of Assessment instead of providing a Report for Ministry. Moving to Close
