### ISSUE TITLE
Change function of Federal Week maximum restrictions

### ISSUE THREAD

**Issue by Joshua-Lakusta** [bcgov/SIMS#3242]
As a ministry user I want the restrictions around weeks of study to effect Part time students as well as Full time students

**Acceptance Criteria**
- [ ] Modify the outcome of the following restrictions so that they effect both Full time and Part time applications.
  - [ ]  Code 5
  - [ ]  Code 7
  - [ ]  Code 9

**Additional Context**
Note: the warning versions of these restrictions do not need to be changed as they will show and not effect either application type as they are warnings only.

<img width="668" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWpGQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--507a6ec909551df662586c857e664843240caa0b/image.png" alt="image.png" />

**Technical**
- [ ] DB migration only.
- [ ] Update the below restriction to include `Stop full time disbursement`.
<img width="433" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelhSQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4a4aefc0ebc5c2f7202a0e10b132b418aace7ffd/image.png" alt="image.png" />
- No E2E test required.
- Can be demoed showing that when added to the student account this restriction will now prevent a user from accepting the assessment from a part-time application.

**Comment by andrewsignori-aot** [comment]
@CarlyCotton this change was already taken care of in #3512, can we close this one?

<img width="1359" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWZnQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--93212c3f417e284b95d7ca34466af4dde0f33ec5/image.png" alt="image.png" />

**Comment by CarlyCotton** [comment]
@andrewsignori-aot Yes, confirmed that this is no longer needed with the work on the restrictions list. Removing the points and closing.
