### ISSUE TITLE
CAS Integration 2 - (UX/UI) Add or Edit CAS Supplier Info to Student Profile

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#3257]
**User Story:** 
As a Ministry user, I want to see a student's supplier information on their profile, and be able to manually edit specific fields, so that I can view and manage their information and keep it current. 

**Acceptance Criteria:**

**Display CAS Info through UI Table**
- [x] Create "CAS Supplier Info" tab in Student Profile. This is viewable to Ministry only (No institutions, no students)
- [x] Create "CAS Supplier Information" screen consistent with **Fig 1**. This table will function very similarly to the student's SIN table
- [x] Add text below the "CAS Supplier Information" header which reads _"The top row in the table below is the most current CAS information for the student"_
- [x] In response from CAS, look for first address/site info which has an active status, and Map those response variables to the UI table accoridng to the below mapping:

|  Column Header |  Description/Mapping  |  E.g. |
|---|---|---|
| Date Created | Date When this row in the table was updated in SIMS | Sep 12, 2024 |
| Supplier Number | `supplierNumber` | 1234567 |
| Supplier Protected | `supplierprotected` | Yes or No |
| Supplier Status | `status` | Pending supplier verification/Pending address verification/Verified/Verified manually |
| Supplier Valid | `is_valid` | Yes/No |
| Site Code | `suppliersitecode`| 001 |
| Address Line 1 | `Addressline1` from CAS response | 123 Fake St |
| Site Status | `SupplierAddress` > `status` | Active/Inactive |
| Site Protected | `supplierAddress` > `siteprotected` | Yes/No |

- [x] Create a new line in this table everytime a 'Get Supplier' process returns a successful response 

**Allow CAS Info to be Manually Edited through UI**
- [x] Edit function is only permitted for 'Business Adminstrators' user role
- [x] If 'edit information' is submitted:
    - The modal should prompt for "Supplier Number" and "Site Code"
    - Both fields mandatory
    - Format & length validations on both fields (Ref: [Individual Supplier Web Service Field Requirements (All Requests) JAN2023.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGJYQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd785e77d67f3e11bfd591da13f2baae828b7436/Individual%20Supplier%20Web%20Service%20Field%20Requirements%20%28All%20Requests%29%20JAN2023.xlsx) )
        - <img width="1335" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMENQQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c193cc57d059d88d280d03359fd19193017a898a/image.png" alt="image.png" />

    - A new row in the table is created with just the manually inputted info (all other fields will be null)
    - A note is NOT created
    - NO further CAS calls/transactions are conducted

**Business Context:**
- Handling 'update supplier site' and 'create new site' is in seperate ticket
- Handling Get Supplier is in seperate ticket

**Technical Context:**

**Mock-Ups**
**Fig 1**
<img width="1104" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3hOQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2b6a0b5c04b0638794cfb6a5a39b0780ea3d2888/image.png" alt="image.png" />

**Fig 2 - Workflow**
<img width="1349" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFJPQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f387cca7b8a377d5599123239b00167cedb255f3/image.png" alt="image.png" />

**Technical**
- [x] Create a new tab on Ministry for Students following the SIN.
- [x] Create a button "Edit Information" to create a new record with the `supplierNumber`, `supplierSiteCode`, and supplier status as `Verified manually`.
- [x] Add to the table the "Is valid" and "Supplier status".
- [x] Display the "Supplier status" as a status chip on every row.
- [x] Ensure the new row is associated in `sims.students.cas_sppllier_id`.
- [x] Use Vuetify table.
- [x] No server-server pagination needed. Do not build server pagination. Do not work on server pagination.
- [x] E2E Tests for the new API methods.

**Comment by andrewsignori-aot** [comment]
@CarlyCotton there is a note in the ticket about "A note is NOT created" but we believe that it would be important and it would also follow the SIN process. Is there a string reason to not have it?

**Comment by andrewsignori-aot** [comment]
@CarlyCotton the table is missing some record statuses highlighted below. Can we have those added to the table?
<img width="679" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkYrQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--613fc40d7dbcb1d849459712b01d7a5bfd5cf24f/image.png" alt="image.png" />

**Comment by andrewsignori-aot** [comment]
@CarlyCotton the below AC is not possible to achieve yet because we do not update the data if the Get Supplier did not return or did not return an active supplier.
"'Edit Information' button should become available after a 'Get Supplier' transaction has been executed at least once.".

To allow us to go ahead with this ticket, cn we move this AC to another ticket?

**Comment by CarlyCotton** [comment]
@andrewsignori-aot 

1. Removed AC:
> 'Edit Information' button should become available after a 'Get Supplier' transaction has been executed at least once.

2. Updated Table to (hopefully match what you were telling me about

3. Going to get confirmation from business (finance) on the question of enforcing a note. I think there may be concerns about how limited the access to this CAS functionality/info is going to be and that it would be useful to a VERY small group of people.

**Comment by CarlyCotton** [comment]
@andrewsignori-aot 

> there is a note in the ticket about "A note is NOT created" but we believe that it would be important and it would also follow the SIN process. Is there a strong reason to not have it?

Confirmed with Finance, mandatory note NOT required. There are going to be a lot of limitations on who does this work and who can access this information. They can still add a note to the student profile if they need to.
