### ISSUE TITLE
CAS Integration 4A - Supplier Maintenance Errors

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#3258]
### **User Story**
As a Ministry user, I need to know if SIMS could not successfully verify and assign a supplier number and site, this could be due to an identified manual intervention requirement or due to an error with the request to CAS. This needs to provide me context in which this occurred so I know if I can retry or resolve it. Retrying involves asking SIMS to attempt the action again with the current information (eventually). Resolving means that I have reviewed CAS and SIMS, making any necessary updates in either system and SIMS will not need to attempt the action again. This information will be used to create UI or populate a report.

# Acceptance Criteria
- [x] Update the CAS table column order, add new columns, update column names (ignore differences in the status label or formatting):
<img width="1001" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkdmQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a393bd5619b71669f0a2075fc2248488be9866e4/image.png" alt="image.png" />

- [x] User should see the response message for any CAS error or manual intervention pre-validation error records. 

- [x] If Manual Intervention is required the associated **Error message** based on the situation:
    - [x]  "Address outside of Canada cannot be processed." 
    - [x]  "Given name required for creation."

- [x] For error responses from CAS set the status to "Manual Intervention" include the **Error Message** received from CAS (it comes in as a string, multiple are split by bars. See CAS 2A)
   

- [x] Any of these errors should make the Supplier `isValid = false` and in cases where Supplier found but create Site failed, save any valid Supplier info

- [x] Retry button means creating a new pending CAS request  and is only available to the `business-administrator` group (can be linked to the existing cas-edit-supplier role)
    - [x] Student data may be updated (Given Name, Last Name, SIN, Address Line 1, City, etc) and we need to perform the same attempt again with the most current student info.
    - [x] On retry provide success toast pop message "A new CAS pending verification record was created. A new attempt will be made to get information from CAS."

- [x] Include all error responses, including those from GetSupplier requests.

**Business Context**
- Identification of almost certain errors are noted as Manual Interventions. These will not be able to be resolved through automatic SIMS-CAS communication and will require a user to review CAS and update CAS and/or SIMS as a result.
- Some errors are due to technical issues and not as a result of an error response from CAS. These will be automatically retried right away.
- Errors that we receive a response from CAS about may need to be resolved manually (see Manual Interventions above.) Some error responses will require that SIMS retries the same attempt with potentially new student data (name, address, sin).
 - [List of Errors SWS Feb 2024.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTFnQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--317f04738b5d2da714fad5185edb9d3ccee346e9/List%20of%20Errors%20SWS%20Feb%202024.pdf)

**Technical**
- [x] Please see the reference for the Vuetify with the row expander: https://v2.vuetifyjs.com/en/components/data-tables/#expandable-rows
- [x] Create new columns on DB to save the list of errors (array of string), suggested column name `errors`.
- [x] For CAS errors, split the result by "|" and save as list.
- [x] Retry operation should create a record following the same creation when a new student account is created.
- [x] Disable the "Retry" button if there is already a pending record.
- [x] Ensure API will block the creation of a pending record when one is already in place.
- [x] PRs
  - DB migrations, saving reasons from pre-validations and handling the CAS bad requests.
  - UI changes and retry.
- [x] E2E Tests for queue-consumers and the new API.

**Comment by CarlyCotton** [comment]
Need to incorporate Name and SIN updates on SIMS into error handling to resolve manually with CAS.

**Comment by andrewsignori-aot** [comment]
@CarlyCotton we will disable the "Retry" if there is already a pending record created.

**Comment by CarlyCotton** [comment]
@andrewsignori-aot That works. Can we be specific and say "Pending supplier verification" status?
