### ISSUE TITLE
Edit Program info during CoE requirements

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#326]
**Tasks**
When: edit Program Information" on COE
- [x] Hide "Edit Program Information" on COE when PIR=Not Required and block API
- [ ] When Camunda updates the offering_id and program_id (see below) do not overwrite the DB when values are NULL. 
![image.png](https://images.zenhubusercontent.com/5fce9c77aab275719112dc74/dd943824-3620-4bac-8127-7db9aa4dde85)

**Comment by ann-aot** [comment]
dropdown loading id was due to router conflict

**Comment by ann-aot** [comment]
`When Camunda updates the offering_id and program_id (see below) do not overwrite the DB when values are NULL.` - I test the edit PIR scenario in COE, I couldn't find any gap, so keeping the point here itself,
