### ISSUE TITLE
CAS Integration 3A - Create new Supplier and Site

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#3260]
## **User Story:** 
As an SABC Finance team member (Ministry user), I need all students in SIMS to have a supplier and site number attached. If we do not receive a match from the initial CAS supplier search after SIN validation, we need to create a new supplier and site for the student. 

## **Acceptance Criteria:**

- [x] Create new Supplier Status: "Manual Intervention" Set the flag isValid=FALSE

### **Get Supplier (Last Name and SIN)**
- [x] Ensure **initial** Get Supplier call uses the follow name format to search:
    - [x] ALL upper case letters
    - [x] Hyphens accepted, not dashes
    - [x] Special characters: Please use our current translation strategy to convert special characters where possible, or omit them. 
    - [x] If the student does NOT have a Given name, do NOT attempt the Get Supplier Call. Status: Manual Intervention Required
    - [x] If the student does NOT have a Canada address, do NOT attempt the Get Supplier Call. Status: Manual Intervention Required

### Get Supplier Response "None found/0 Count":
- [x] Schedule these to go once a day at noon during weekdays for now.
- [x] Call **Create New Supplier and Site (command 1)** 
- [x] Fields to include (See Field Requirements File below): SIN, AddressLine1, City, Province, Country, PostalCode, EmailAddress (Optional/Conditional fields can be left out or left null)
    - [x] **Name Field:** Use ALL CAPS. LASTNAME, GIVENNAMES (must have a space after the comma). Hyphens accepted, not dashes (CAS only translation).
    - [x] **AddressLine1:** Use first addressline from SIMS. Truncate if ours is longer than supported. Convert or omit special characters (like is done with other integrations).
    - [x] **City:** Use as-is
    - [x] **Province:** Use abbreviated versions AB,BC,MB,NB,NL,NS,NT,NU,ON,PE,QC,YT
    - [x] **Country:** For Canada: CA
    - [x] **Postal Code:** ALL CAPS, no space.
    - [x] **Email Address:** Use as-is

- [x] If successful response to Create New Site & Supplier, then update SIMS CAS table with the returned `supplierNumber`, `SiteCode` and any other required info and set `isValid`=true
- [x] If error response, retry for now. Manual intervention may be required and will be dealt with on ticket #3258
<img width="897" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3IyQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3fcc0daf0a6b0e05cf4499e70c0e754f84f447df/image.png" alt="image.png" />

**Business Context**
[Supplier Web Service RESTful Client Onboarding v02_01.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXpWQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--361bbb0afd9232c66288a57ce767a1a8d478f535/Supplier%20Web%20Service%20RESTful%20Client%20Onboarding%20v02_01.pdf)

[Individual Supplier Web Service Field Requirements (All Requests) JAN2023.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGJYQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd785e77d67f3e11bfd591da13f2baae828b7436/Individual%20Supplier%20Web%20Service%20Field%20Requirements%20%28All%20Requests%29%20JAN2023.xlsx) 

***Technical Context***

Sample CURL to create
```console
curl --location '${BASEURL}/cfs/supplier/' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer ${TOKEN}' \
--data-raw '{
    SupplierName: '\''Skywalker, Leia'\'',
    SubCategory: '\''Individual'\'',
    Sin: '\''422233197'\'',
    SupplierAddress: [
    {
        AddressLine1: '\''1012 Douglas St'\'',
        City: '\''Victoria'\'',
        Province: '\''BC'\'',
        Postalcode: '\''V8W 2C3'\'',
        Country: '\''Canada'\'',
        EmailAddress: '\''stephen.laws@gov.bc.ca'\'',
    }]
}'
```

Response:
```console
{"SUPPLIER_NUMBER":"2007638","SUPPLIER_SITE_CODE":"[001] ","CAS-Returned-Messages":"SUCCEEDED"}
```

### Command 1 - Create New Supplier and Site Call
**SupplierName:** 
```
{
    "SupplierName":"SMITH, SUSAN",
    "SubCategory":"Individual",
    "Sin":"",
    "BusinessNumber":"",
    "SupplierAddress":[
       {
           "AddressLine1":"5522 Oyama Lake Rd",
           "AddressLine2":"",
           "AddressLine3":"",
           "City":"Lake Country",
           "Province":"BC",
           "Country":"CA",
           "PostalCode":"V4V2C9",
           "EmailAddress":abc@xyz.com,
           "EftAdvicePref": 
       }
    ]
}
```

**Successful Response**
```
{
    "Supplier_Number":"123456789",
    "Supplier_Site_Code":"001",
    "CAS-Returned-Messages":"SUCCESS"
}
```

```
**Error Response**
{
    "Supplier_Number":"123456789",
    "Supplier_Site_Code":"001",
    "CAS-Returned-Messages":"Error Message"
}

```

**Technical**
- [x] While creating the new supplier on CAS ensure the name also has the special characters removed.
- [x] To handle the " Special characters", extract the logic from method [convertRawContent](https://github.com/bcgov/SIMS/blob/4e3b55ab77ffb49cf25f35eaa0fd0f8650e38e3f/sources/packages/backend/libs/integrations/src/services/ssh/sftp-integration-base.ts#L77) to the [string-utils.ts](https://github.com/bcgov/SIMS/blob/main/sources/packages/backend/libs/utilities/src/string-utils.ts).
  - [x] The method should receive a string and return a string.
  - [x] Add the hyphen/dash conversion. `hyphen-minus` is the ASCII character 45 while the "dash" is a Unicode character, hence it would make sense to add it to the conversation shared with the SFTP.
  - [ ] Check if the request was successful by inspecting the response property `"CAS-Returned-Messages":"SUCCEEDED"`.
    - [ ] If the value is different than `SUCCEEDED` log the error message.
- [x] Create the new status `Manual intervention required`.
  - [x] For the business AC that leads to `Manual Intervention Required`, set the `is_valid` column to `false`.
- [x] Log to the ProcessSummary the individual errors for the students.
  - [x] Ensure that all the students will have at least one attempt, meaning do not stop processing at the first student error.
  - [x] If some error is present throw in the scheduler to allow it to be retried.
- [x] Expand existing E2E tests. Please add at least the below positive scenario.
  - [x] Should create a new supplier on CAS and update `sims.cas_suppliers` table when the student was not found on CAS and the request to create the supplier was successful.
  - [x] Should set the case supplier record status as 'Manual Intervention Required' when the student does not have the first name.
- [x] Breaking the PR.
  - [x] Adjust the "Get Supplier", including the characters translations.
  - [x] Create the CAS call.

**Comment by andrewsignori-aot** [comment]
@CarlyCotton I would like to request the change of the below AC, from
```
Hyphens accepted, not dashes (CAS only translation)
```
to
```
Hyphens accepted, not dashes.
```
The point is that "dashes" can also be present on names and it is not an ASCII character hence it would make sense to have it added in the current ASCII conversion table that we use for the SFTP. Please let me know if there is any concern.

**Comment by CarlyCotton** [comment]
@andrewsignori-aot Updated the AC. Happy to keep things consistent across SIMS when possible rather than have one-offs.

**Comment by andrewsignori-aot** [comment]
# Demo

## New student created

<img width="1390" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1IyQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3eea729e0f55cffe5f1ea0e59ac77f28028ed8b9/image.png" alt="image.png" />

### New Suplier and Site Creation

#### Pending
<img width="1590" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0IyQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7df2df4402eddc1cd3c6a3d4d4fdb6af134e6466/image.png" alt="image.png" />

### Completed

<img width="1591" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK04yQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0d8964cf7f6ddc8455db68323f990ccc1391bf2c/image.png" alt="image.png" />

#### Bull Logs

<img width="697" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTkyQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ab70eeee9a4a390620870e3f817de9d52a051529/image.png" alt="image.png" />

##### Log details
```text
[2024-10-25 21:20:19]INFO: Log details
[2024-10-25 21:20:17]INFO: Executing CAS supplier integration...
[2024-10-25 21:20:17]INFO: Found 1 records to be updated.
[2024-10-25 21:20:19]--INFO: Log details
[2024-10-25 21:20:19]----INFO: Log details
[2024-10-25 21:20:19]------INFO: Log details
[2024-10-25 21:20:17]------INFO: Processing student CAS supplier ID: 118.
[2024-10-25 21:20:17]------INFO: CAS evaluation result status: NotFound.
[2024-10-25 21:20:17]------INFO: No active CAS supplier found. Reason: Supplier not found.
[2024-10-25 21:20:19]------INFO: Created supplier and site on CAS.
[2024-10-25 21:20:19]------INFO: Updated CAS supplier and site for the student.
[2024-10-25 21:20:19]INFO: CAS supplier integration executed.
```
