### ISSUE TITLE
CAS Supplier Integration 0.5 - Technical Setup

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#3267]
**User Story**
As a SIMS Product Team, we need to validate the integration between SIMS and the Corporate Account System so that our story implementation is straightforward. 

**Acceptance Criteria:**
- [ ] Request Access Token from Supplier API 
- [ ] Create SIMS API to enable integration with CAS Supplier API and mapping of values: 
    - [ ] GET by Last Name and SIN
    - [ ] Create Supplier with POST Request 

**Technical**
- [ ] Firewall rules should be enabled between OpenShift and CAS
    - [ ] Developers to use VPN to ensure network connectivity 
- [ ] ClientID and Secret for token generation to be provided by @sslaws. 
- [ ] Endpoints and JSON example JSON response provided in documentation for Supplier API 
    - [ ] Get by Last Name and SIN: https://< webserviceURL >:<port_no>/ords/cas/cfs/supplier/:snum/site

**Doc 1 - Full Onboarding Document**
[Supplier Web Service RESTful Client Onboarding v02_01.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFRSQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d96bf5d2cda006ceea49704e161a14f1b0aed8f3/Supplier%20Web%20Service%20RESTful%20Client%20Onboarding%20v02_01.pdf)

**Doc 2 - Individual Supplier Webservice Field Requirements**
[Individual Supplier Web Service Field Requirements (All Requests) JAN2023.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVBWQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ae697f29399dea8cb31224082f8a41cdd925bd78/Individual%20Supplier%20Web%20Service%20Field%20Requirements%20%28All%20Requests%29%20JAN2023.xlsx)

**Context:**
- a student is a supplier and has a 'supplier number'
<img width="503" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNExwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--75983825b8922e9716738e8e7e698019768eb782/image.png" alt="image.png" />

**Comment by HRAGANBC** [comment]
@sslaws 
I don't think appropriate to bring through Dev lather/groom sequencing, so please let me know if you need clarity on any of this. See the rest of the 'CAS Integration' tickets for context, as necessary.

**Comment by ninosamson** [comment]
Sample JSON Response - GET Supplier: 
{
 "SupplierNumber":"2002492",
 "SupplierName":"XYZ Supplier",
 "SubCategory":"Individual",
 "Sin":"",
 "ProviderId":"",
 "BusinessNumber":"",
 "Status":"ACTIVE",
 "SupplierProtected":"N",
 "StandardIndustryClassification":"Pharma",
 "LastUpdated":"2019-11-13 11:09:50",
 "SupplierAddress":[
 {
 "SupplierSiteCode":"001",
 "AddressLine1":"3350 CLEARBROOK RD",
 "AddressLine2":"",
 "AddressLine3":"",
 "City":"ABBOTSFORD",
 "Province":"BC",
 "Country":"CA",
 "PostalCode":"V2T4T4",
 "EmailAddress":"abc@xyz.com",
 "AccountNumber":"",

**Comment by sslaws** [comment]
Closing and merging details into #3255
