### ISSUE TITLE
Content: Ministry: Your Profile Info: Update content for “Deny request for a student account” modal

### ISSUE THREAD

**Issue by astridSABC** [bcgov/SIMS#3280]
**User story**
As a _ministry_ user, I want to deny the request for a student account so that they have to start over with the Basic BCeID account application.

**Acceptance Criteria**
- [ ] Update current text “Denying the request means that the student will not be able to access the system using a Basic BCeID” to "Attention: Denied account requests are final and cannot be reactivated. Students will need to start over with the Basic BCeID account application process."

**Supporting steps and screenshot**
A student has created a new profile and it is sitting in the Student Requests>Accounts page
Click "View"
Click "Deny request"
Message displayed needs to be updated

<img width="980" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLy9jQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--02bf0d4545e198dc19a766b60752ccae83eb52c9/image.png" alt="image.png" />

Supporting document [Deny Account.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWJkQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5d8dfb12e776076068d06f5c54b126d9fe0b1b4d/Deny%20Account.pdf)

**Comment by HRAGANBC** [comment]
@Holding off until we can investigate workload with allowing Basic BCeID re-applications

**Comment by HRAGANBC** [comment]
We are moving forward this content change - post PT launch to students, we will gauge scale of problem and address the underlying functionality then, if at all
