### ISSUE TITLE
Detect Assessment Offering Dates Change for 'Application Changes' Report

### ISSUE THREAD

**Issue by andrewsignori-aot** [bcgov/SIMS#3282]
**Description of Task**
As an NSLSC partner, I need to be aware of relevant changes to student applications so that I can accurately adjust a student's interest-free status and adjust validations on study date overlap within the NSLSC system (among other things). In preparation to allow the report data generation (#2499) the assessment workflow will detect the changes and prepare the data that will be used as a main source for the report generation.

**Technical**
- [x] Create new columns on the `sims.student_assessments`.
  - [x] `previous_date_changed_reported_assessment_id`, references assessment_id, nullable.
  - [x] `reported_date`, date and time, nullable.
- [x] Change the `workflow-wrap-up` worker to populate the new column `previous_date_changed_reported_assessment_id` (`reported_date` will be populated upon report generation in the upcoming ticket).
  - [ ] Create a new service method to populate the `previous_date_changed_reported_assessment_id` if needed.
  - [ ] Ensure the worker and the method execution are idempotent.
  - [ ] Execute the new method only if.
    - Application status is `Completed`. Non-completed applications will never generate an e-Cert hence they should not check for offering changes.
    - Trigger type is different from `Original assessment`. Only reassessments can cause a date change hence there is no reason to check `Original assessments`.
  - [ ] The new method should.
    - Scenario 1
      -  Check if there is a previously reported assessment for the application (`order by assessment_date desc`, `limit 1`), immediately before the assessment being processed right now. It can be checked based on the below conditions:
        -   `previous_date_changed_reported_assessment_id` has value
        -   `reported_date` has a date.
    - Scenario 2
      - If no assessment was ever reported, check if an e-Cert was generated for this application.
    - If ` Scenario 1` or `Scenario 2` produced an assessment (both scenarios can be executed in a single DB query).
      - Check if the offering dates changed,
        - If `yes, they changed`, save the assessment in the `previous_date_changed_reported_assessment_id`
        - If `no, they are the same`, do nothing.
- [ ] E2E tests to be applied to the worker
  - [x] An application with an 'Original Assessment' and a 'Reassessment' should populate the 'previous_date_changed_reported_assessment_id' when the e-Cert was generated for the 'Original Assessment' and offering dates differ.
  - [x] An application with an 'Original Assessment' and a 'Reassessment' should not populate the 'previous_date_changed_reported_assessment_id' when the e-Cert was never generated for the 'Original Assessment' and offering dates differ.
  - [x] An application with multiple reassessments should populate the 'previous_date_changed_reported_assessment_id' with the most recent reported reassessment when there was a previously reported reassessment.
  - [x] An application with multiple reassessments should not populate 'previous_date_changed_reported_assessment_id' if an intermediate reassessment has a different offering date but the current one changed the date back to its original values.
  - [ ] An application with multiple reassessments should not populate the 'previous_date_changed_reported_assessment_id' when the e-Cert was generated and the offering dates never change.
- [ ] PR breakdowns
  - DB Migrations must be finished first to allow #2499 if in the same sprint.
  - E2E tests and worker implementation.

**Comment by andrewsignori-aot** [comment]
@HRAGANBC does a newly generated e-Cert count as a reported?
Please consider the example below where multiple reassessment happens and two had the e-Cert generated even before the report was generated. Should we add anything to the report when assessment 103 is generated? Which assessment id should be considered the previous one?

<img width="766" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnpyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--60bda6376092070770c5afebdaeeb2491ba5d81b/image.png" alt="image.png" />

**Comment by HRAGANBC** [comment]
@andrewsignori-aot 

>The overall question is if the e-Cert sent plays any role after the first one was ever generated.

The answer is **no**, the 2nd, 3rd, etc.. e-Cert being sent status should have **no** impact on what gets included on the Type B report.

**Comment by sh16011993** [comment]
Thanks @HRAGANBC

**Comment by sh16011993** [comment]
@CarlyCotton As per our discussion in the meeting together with @andrewsignori-aot , here are the takeaways:

1) If a new location was added and never requested for designation, it would not show up in the report.
2) The report generated will have the columns ('Designation Requested', 'Designation Approved', << 3rd column representing the designation status  of the designation request as a whole >> similar to how the representation happens in the UI.

@CarlyCotton  Can you please confirm if they are correct. Thanks!

**Comment by CarlyCotton** [comment]
@sh16011993 

All good on this end. Thank you for clarifying.
