### ISSUE TITLE
Content: Ministry portal: Add identifying information to assessment 

### ISSUE THREAD

**Issue by JerPearson** [bcgov/SIMS#3288]
**As a ministry user I want to see identifying information on the 'assessment' page to confirm I am viewing the correct account. 

## Acceptance Criteria
> Generated by [Zenhub AI](https://www.zenhub.com/ai)

 - [ ] **Scenario: Identifying information displayed on 'assessment' page**
  - Given the user is logged in on the ministry portal
  -  Has navigated to the  'assessment' page 
  - When the user views the page content
  - Then identifying information should be displayed on the page to confirm user is viewing the correct account
- [ ] **Scenario: Identifying information matches user's application data**
  - Given the user's application information is stored in the system
  - When the user views the identifying information on the 'assessment' page
  - Then the information should match the information on the 'view assessment' page

Mock up:

- The identifying information should be added to the top left to align with the 'view assessment' page
<img width="1502" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUxrQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--72762d2b84ff55d933723fbc3eeb4c546dfc5663/Assessment%20page.PNG" alt="Assessment page.PNG" />

- This information can be reused for the assessment page
<img width="1420" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHprQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--623c198e072c581d290ba575a42abc835ed014e6/View%20Assessment.PNG" alt="View Assessment.PNG" />

 Additional context provided**

Technical context:
 - Zenhub #3287 adds the full name to the identifying information
 - Once that ticket is updated all of the identifying information on that page should be reused on the 'assessment' page using the same formatting and location
 
Business context:
- When a ministry user is processing work from the exceptions/change request (appeals) page, if they click the wrong 'view' button they have no way of knowing they are on the wrong account.
- As ministry staff cannot reverse actions in SIMS, not having identifying information increases the chance for error

**Comment by CarlyCotton** [comment]
Closing - done on another ticket.
