### ISSUE TITLE
UX/ UI- Determine Institution Role for FIRST Time Account Setup 

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#330]
Burning Question
- [ ] Determine Does a first-time account set up always have to be an ADMIN or can it be a USER (aka Zoe? 
- [ ] Update the login workflow to confirm this answer. 
- [ ] Confirm Identity Requirements with Andrew Schwenker Jamie and privacy policy as required

**Comment by hellolynn-dsib** [comment]
**Notes meeting 6 April (designation workflows working group)**
- If Zoe is setting up an institution profile, allow her to define roles as part of the designation onboarding (with ability to undelegate herself)
- Zoe is not usually a legal authorized authority
- Business wants to ensure it's clear who can legally sign the designation

**Updated Workflow**
- Under common scenario assumption that David the Director signs DA (Zoe setups)
- Zoe is BCeID approved and signs in, starts onboarding
- Zoe adds David as the legal authorized authority on profile setup
- NEW! UI call out with messaging legally signing the designation/next steps for this person
- REMOVED declaration UI from "final dec" screen (to add to David's BCeID experience V2 onboarding)
- REPLACED declaration UI with same form section and messaging - legal authorized authority

**Figma Screens**

https://www.figma.com/proto/VykmBDwobGoGvK9M5wgOvN/StudentAid-BC-App-Design-System-(WIP!!)---FreshWorks-Studios?node-id=842%3A5387&scaling=min-zoom&page-id=642%3A2733
