### ISSUE TITLE
Income Eligibility - PT CSLP/SBSD

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#3300]
**User Story**
As a student I am only eligible for CSLP (Part-time loan) and SBSD (supplemental bursary). This is required for all PT program years.

**Acceptance Criteria**
- [ ] Update **awardEligibilitySBSD** in all PT program years
```
if (institutionType = "BC Public" or institutionType = "BC Private") 
  and (calculatedDataTotalAssessedNeed >= 1) 
  and calculatedDataPDPPDStatus = true
  and (calculatedDataTotalFamilyIncome < dmnPartTimeAwardFamilySizeVariables.limitAwardSBSDThresholdIncome)
then true 
else false
```
- [ ] Add **awardEligibilityCSLP** in all PT program years
```
if (calculatedDataTotalAssessedNeed >= 1)
  and (calculatedDataTotalFamilyIncome < dmnPartTimeAwardFamilySizeVariables.limitAwardCSLPThresholdIncome)
then true
else false
```
- [ ] Update **federalAwardNetCSLPAmount** in all PT program years
```
if (awardEligibilityCSLP = true)
then
    min(limitAwardCSLPRemaining,calculatedDataTotalRemainingNeed4)
else
0
```

**Technical**
- [ ] E2E Tests
  - [ ] Create the new E2E for the eligibility check for `awardEligibilityCSLP` and ensure an assertion for the `federalAwardNetCSLPAmount` (if not eligible it must be zero), otherwise ensure a positive value should be present.
  - [ ] Create/update a scenario to ensure a test for the new logic added for `SBSD`.

**Comment by andrewsignori-aot** [comment]
@CarlyCotton with the CSLP being possibly ineligible we may end up in a situation where no awards will be present.
For instance, in the below example, only a PD/PPD is available but if not, the system is not even ready to display an assessment with zero dollar amount.

<img width="1405" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGszQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ba71ae4ff90972d25bb80fa213a5c262b5451fb5/image.png" alt="image.png" />

**Comment by CarlyCotton** [comment]
@andrewsignori-aot @guru-aot 

It is possible for a student to be "Not eligible" for every award. In those cases we still want to display that to them (there are times an appeal may need to be made so that they become eligible). 
I understand it may result in some wonky content and I'm making a ticket to support the display in these instances (#3382)

**Comment by guru-aot** [comment]
@CarlyCotton The ticket handles till the NOA is shown to the Users. So the change that was done to show it, might have consequences in the ecert generation. Please create a ticket to handle those scenarios.
