### ISSUE TITLE
Content: Student: Personal Information 

### ISSUE THREAD

**Issue by JerPearson** [bcgov/SIMS#3310]
**User Story**
As _student user_, I want to have clearer instructions so that I can provide SABC the information it needs

**Acceptance Criteria**

Your StudentAid BC profile information section

- [x] Revise text "This information was provided by you ...account." **to** ""Because your profile information is used across your application(s), it's important to keep your information accurate and up to date." 

Note: DOB is in [3357](https://app.zenhub.com/workspaces/student-information-management-system-5fce9df5aa1b45000e937014/issues/gh/bcgov/sims/3357)

 <img width="729" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0lrQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--775a63489fb9e96236d74efb6157f5694ad6c495/image.png" alt="image.png" />

Citizenship status: protected person upload proof of citizenship section

- [x] Revise 3 bulleted list "Valid confirmation....document"  **to**: 

- Valid Confirmation of SIN document ; and
- Notice of Decision (issued by Immigration and Refugee Board) or
- Verification of Status document (IMM5009) or
- Confirmation of Protected Persons Status document (IMM5292)"
 
<img width="490" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemtxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--42e091c3ebee3c36cf9864bcf5cbd664e5b8b9de/image.png" alt="image.png" />

Citizenship status: permanent resident upload proof of citizenship section

- [x] Revise text for bulleted list "Valid record of landing....resident card"  **to**: 

- Permanent Resident Card (IMM5445) or
- Record of Landing (IMM1000) or
- Confirmation of Permanent Residence (IMM5292 or IMM5688) or
- Verification of Status document (IMM5009)."

<img width="471" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBem9xQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--94b39c7d3f1009572037c909b01722c17427035d/image.png" alt="image.png" />

Are you a resident of BC section

- [x] Revise help info text for "Are you a resident of BC?" from "you have lived in BC....months" **to** 

"As a student you are a considered to be a resident of B.C. if one of the following criteria are met:

- B.C. is the province where you last lived for 12 continuous months, as of your study start date, not including months of full-time post-secondary study; or

- You are an independent permanent resident, or designated as a protected person, living in B.C. at the time of application and will spend the study period in B.C. but have not lived in any one province for at least 12 continuous months. For example, if an independent student arrived in Canada as a permanent resident less than 12 months before the start date of classes, and intends to study in B.C., the student would be considered a resident of B.C. for student financial assistance purposes."

<p></p>

Are you a resident of B.C.? (Selecting no option) upload supporting documents section

- [x] Revise text for bulleted list from (keep SIMS bullet type) "Lease agreements....residency" **to:** 
- Lease agreement and utility receipts
- A minimum of 4 years of unofficial transcripts to show attendance at a BC post-secondary institution
- A spouse/partner employer letter
- A student financial aid denial letter from your previous province of residency

<img width="709" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBek1xQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2baf603d0e932223736e1a2c74aa45c9f0159f68/image.png" alt="image.png" />

Share information with trusted contact section

- [x]  Remove text "Do you want allow another person to be able to contact StudentAid BC and inquire about the status of your application or provide additional information on your behalf? (A parent/guardian for example.)"
- [x]  Revise text "Do you want to allow a trusted ...behalf?  to ""Do you want to authorize a trusted contact to access information about this application on your behalf?"

<img width="602" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnNnQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0736dbd9cae218e473fb28bcf895450b73e147b0/image.png" alt="image.png" />

Add a trusted contact section

- [x] Revise text "Add trusted contact' to "Add a trusted contact"
- [x] Revise text "Enter the information....if needed." to "Enter the information of the trusted contact(s) you would like to add to this application.  This is for information sharing purposes only."
- [x] Remove text "ROI information"
- [x] Revise text "Other relative" to "Relative"

<img width="564" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjRnQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a8502a06627f3d1c3618fe74b5d65312bcc02e81/image.png" alt="image.png" />

Refer to [Personal Info Complete.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2drQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6c70b8556316b3fad4ab55400c9b97573217bf54/Personal%20Info%20Complete.pdf)

**Comment by astridSABC** [comment]
@JerPearson pls review
