### ISSUE TITLE
Content: Student: Financial Information 

### ISSUE THREAD

**Issue by JerPearson** [bcgov/SIMS#3311]
**User story**
As a _student user_, I want the award types and additional transportation sections updated so that I can make better decisions on my application and things are more clear.

**Acceptance Criteria**

- [x] Revise text “Canadian” **to** “Canada”

Note: The federal government department name is the [Canada Revenue Agency](https://www.canada.ca/en/revenue-agency.html)

<img width="935" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHdQQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c7582b77a1ad3cbd90dee70bcced982746b07b47/image.png" alt="image.png" />

<p></p>

**Award Types section**

- [x] Revise text “Type” **to** “type”

Note: These types of labels are sentence case e.g. Awards type, Additional transportation costs

- [x]  Revise text “I am …., if applicable” **to** "You have six months from your study period end date before you must start paying back your loans."

<img width="997" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUlQQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ff62e1e3d8bf6d52f370bbd4108a840dae7b1c7f/image.png" alt="image.png" />
 
<p></p>

**Additional transportation cost section**

- [x] Revise text “You may …travel.” **to** "You may be eligible for an additional transportation allowance if you are the primary operator of your vehicle and there is limited or no local transit where you live, or if you have special circumstances that require extra travel."

<img width="851" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVVQQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--77e8abb1393602dcffcfb7eb209738c20b0eabfb/image.png" alt="image.png" />

<p></p>
<b>Which of the following best describes your situation? section</b>

- [x] Revise text “There is ….” **to** "Public transit takes more than two hours from your neighborhood to your school and back by the quickest/most direct route."

- [x] Revise text “Please estimate your weekly travel distance…” **to** "Please estimate your weekly travel distance from home to school in kilometers:"

<img width="1065" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0lrQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b8e121043707276507bbbb2562c0575d66e7b713/image.png" alt="image.png" />

<img width="1058" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1VrQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f4380de062bb66e14d52310a7e08bb5dee5cbcc5/image.png" alt="image.png" />

<p></p>

**Upload supporting documents section**

- [x] Revise text “Please provide…” **to** "Please provide all of the applicable documents below."

- [x] Revise text “Work, clinical….” **to** "Work, clinical, or practicum location and schedule with a letter of explanation and"

- [x] Revise text at the end of “Statement…or daycare) or **to** “and”

<img width="820" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWNQQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--28209d95cedb7c6d72e4a67269266cfde3104a7c/image.png" alt="image.png" />

Supporting document [Financial Info.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWdQQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--778f9966e773209e30168b3295b1ce8a3d7d145d/Financial%20Info.pdf)

**Comment by katrina-aot-git** [comment]
The transport supporting documents section was also changed in https://app.zenhub.com/workspaces/student-information-management-system-5fce9df5aa1b45000e937014/issues/gh/bcgov/sims/2806 , so presently does not look like the version that updates here are built off of. Which changes should persist for that section?
