### ISSUE TITLE
Content: Support Portal: Spouse/Partner Search for application page fixes

### ISSUE THREAD

**Issue by JerPearson** [bcgov/SIMS#3322]
**User Story**
As a _support user_, I want the questions reviewed so that I provide only the most important information to the Ministry.

**Acceptance Criteria**

Supporting information section
- [x] Revise text "Partner's Profile" label **to** "Partner profile" label
- [x] Revise text in Partner information text box "Supporting Information" **to** "Supporting information" 
- [x] Revise text for "Supporting Information" section **to** sentence case "Supporting information"

- [x] Remove the three questions, radio buttons and any associated text boxes

- Will you receive income assistance/social assistance (welfare) and/or BC income assistance for persons with disabilities during your Partner's study period?

- Will you be in receipt of Employment Insurance benefits during your Partner's study period?

- Will you be in receipt of federal or provincial permanent disability benefits during your Partner's study

<img width="624" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjBmQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d451cab214c69d7efaac6a9b113fbfe17679d9ea/image.png" alt="image.png" />

Review your profile section

- [x] Revise text "Verified email" **to** "Email address"
- [x] Revise text "Your information above is taken from your B.C. Services Card. If the information is incorrect, please update your information with B.C. Services Card first." **to** "Your information above is taken from your BC Services Card account. If the information is incorrect, please update your information with [BC Services Card account](https://www2.gov.bc.ca/gov/content/governments/government-id/bc-services-card/your-card/change-personal-information)  first.

<img width="606" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0VmQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--be0a13cbb650481a19ed4544e0e944dd8af90872/image.png" alt="image.png" />

- [x] Revise text: "Your contact information" to "Contact information"

<img width="1063" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUtKQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--22f8dad4568e82b237cb746953d2fc4dcd27359e/image.png" alt="image.png" />

Reference documents: [Partner Supporting Info.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEFmQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5c6bee7caa97b746b419cd22f408fff9188fc2aa/Partner%20Supporting%20Info.pdf) and [Partner Profile.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNElmQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c480bc228e7547f160d7bed2503f726e7ebe1845/Partner%20Profile.pdf)

Related issue #3343 re: previous years tax return

**Comment by katrina-aot-git** [comment]
@JerPearson Is the first AC meant to refer to Partner Profile? Otherwise the highlighted Partner Profile from the mockup isn't mentioned.

**Comment by JerPearson** [comment]
@katrina-aot-git good catch thank you.  Yes, the first AC was meant to refer to Partner Profile and has now been updated.  I have also added one additional AC at the bottom of ticket for a missed content update.
