### ISSUE TITLE
Content: Student: Partner Information fixes

### ISSUE THREAD

**Issue by astridSABC** [bcgov/SIMS#3342]
**User Story**
As a _student user_, I want to have clearer language and questions removed in the partner information section so that I can provide the information that SABC requires.

### **Acceptance Criteria**
Partner Details section

- [x] Revise "Is your partner eligible for a B.C. Services Card? " **to** ""Is your partner eligible for a BC Services Card account?"
- [x] Keep information bullet and header wording and revise " If partners cannot access....."  **to** ""If your partner is not eligible for a BC Services Card account, you will need to report their financial information on their behalf.  Please note this information may be subject to audit and review, which could delay your application."

<img width="731" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN29ZQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f73f0cdef4a270a0faa066543fbc047c58773de0/image.png" alt="image.png" />

<p></p>

- [x] Remove question, radio buttons and associated text field "Will your partner receive income assistance/social assistance (welfare) and/or BC income assistance for persons with disabilities during your study period?"

- [x] Remove question, radio buttons and associated text field "Will your partner be in receipt of Employment Insurance benefits during your study period?"

- [x] Remove question, radio buttons and associated text field "Will your partner be in receipt of federal or provincial permanent disability benefits during your study period?"

<img width="365" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGNZQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--758716864e9f51cc23c7d724496ab43863d89e93/image.png" alt="image.png" />

**Business Context**
The three questions above have no impact on PT applications.  However, they do need to be available for FT (TBD)

Reference file attached: [Partner Information.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHdZQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d3f83148cf6b838698f18f1a91edf7eafd6693d0/Partner%20Information.pdf)

**Comment by CarlyCotton** [comment]
@JerPearson 
On the second AC:
> Keep information bullet and Revise " Please be advised..." entire section to ""If your partner is not eligible for a BC Services Card account, you will need to report their financial information on their behalf. Please note this information may be subject to audit and review, which could delay your application."

The structure for these banners is to have a header (in bold) and then content below. Is it possible to keep this consistent for this one rather than removing the heading?

**Comment by JerPearson** [comment]
@CarlyCotton made changes to second AC . Good catch!
