### ISSUE TITLE
Analysis: Archive SFTP files

### ISSUE THREAD

**Issue by sslaws** [bcgov/SIMS#3354]
***Describe the task***
Perfrom Analysis for #2801 - 

***Acceptance Criteria***
- [ ] Investigate and identify which files MUST be processed sequentially and which ones do not.
- [ ] Provide list of sequentially executed ones and non-sequentially executed one, defined during development

**Comment by sslaws** [comment]
@JasonCTang @ninosamson this one doesn't have a release assigned?

**Comment by ninosamson** [comment]
I'd call this 2.1 for hardening. will update.

**Comment by ninosamson** [comment]
I'd call this 2.1 for hardening. will update.

**Comment by sslaws** [comment]
@JasonCTang is this a duplicate of #2801?  Can we close as that one has action on it lately.

**Comment by ninosamson** [comment]
I am closing this ticket as duplicate.
