### ISSUE TITLE
Change Request - Add current year income question (income appeal)

### ISSUE THREAD

**Issue by Joshua-Lakusta** [bcgov/SIMS#3375]
As a student I want to be able to submit a change request that allows me to request the use of my current year income (income appeal).

**Acceptance Criteria**
- [x] Add the additional question for using current year income to the current change request. Add it between the income and dependant care cost question section. (see image, to be placed at bullet one)
- [x] ensure that if this income is approved it is used over all other incomes including CRA verified income which matches the functionality of the current year income application question
- [x] Update the camunda flow for the change request
- [x] Include the same dynamic questions as the base application question. Yes vs no if yes expands to include income field, criteria for eligibility options, and mandatory document uploader with applicable content.

**Additional Context**
See ticket https://app.zenhub.com/workspaces/student-information-management-system-5fce9df5aa1b45000e937014/issues/gh/bcgov/sims/1706 for question information or complete this ticket after 1706 is complete for content clarity.

<img width="917" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTVzQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0aa306235937101ee8d799b7c1d5cf56535931cd/image.png" alt="image.png" />

**Technical**
- [ ] Update to be made in the existing appeal request "Appeals - Student Financial Information"(`studentFinancialInformationAppeal`).
- [ ] Copy the same form definitions for the "Financial circumstances" already implemented for the student. Place between the existing panels "Financial Information Panel" and "Dependant care costs panel".
![image](https://github.com/user-attachments/assets/f8f7c715-073d-46f5-85ec-67b922113dea)
- [x] Adapt the "Financial Information" (number 2 in the image below) to follow the same pattern as number 1 in the image below.
- [x] Change the logic in number 3 below to use the new calculated variables from the appeals.
- [x] Change the logic in number 3 below to ensure the current year's income will take precedence over all others.
<img width="967" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeS9SQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--52a7e118d94f68d1a2cb1744e540d64cbd6e9e0e/image.png" alt="image.png" />
- [ ] Create E2E tests to ensure the precedence.
- [ ] Update the current note on workflow that states "Use CRA Income if provided" to reflect the most updated logic and precedence.
- [ ] Convert the current logic inside "Define Student Total Income" to a flow.
- [ ] `studentDataCurrentYearIncome` inside "Define Student Total Income" will become a calculated variable resulting from the appeals flow.

**Comment by andrewsignori-aot** [comment]
@CarlyCotton the year is now displayed on DEV.
<img width="1200" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnNXQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--301d9bc4eea0cd834c8a00785003e4d9e239430b/image.png" alt="image.png" />

**Comment by CarlyCotton** [comment]
@andrewsignori-aot @guru-aot Looks good to me, thank you!
