### ISSUE TITLE
[WAITING ON FINAL NAMES] GC Notify - Update all login links to production environment

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#3385]
**User Story**
As a student, if I receive an email notification that requires me to log in to SIMS it should provide me the link to the production environment.

**Acceptance Criteria**
- [ ] Update all student applications to ensure the log in links are pointing to the correct place.

##This might be something that we just do on our end vs through dev cycle

**Comment by ninosamson** [comment]
Adding dependency on OCP routes - this will create the URLs to be used in PROD.

**Comment by CarlyCotton** [comment]
Closing - I've updated all of the current templates to include the new addresses for login links.
