### ISSUE TITLE
Content: Student: Change Request Personal Info PD section content and func fixes

### ISSUE THREAD

**Issue by JerPearson** [bcgov/SIMS#3415]
**User Story**
As as student user with a PD, I want the change request questions to be more clear about the options available so that I can get the appropriate funding that I need

**Acceptance Criteria**
- [x] **Revise Question wording**.  Change text from "Are you a student with disabilities and wish to be......?" **to** 
> "Are you a student with a permanent disability, or a persistent or prolonged disability, and applying for disability grants?"
- [x] **Add tooltip next to question.** Text should read:
> "If you are a student with a permanent disability, or a persistent or prolonged disability, as defined below, you may be eligible for additional student financial assistance.

>Permanent Disability:
>Any impairment, including a physical, mental, intellectual, cognitive, learning, communication or sensory impairment - or a functional limitation - that restricts the ability of a person to perform the daily activities necessary to pursue studies at a postsecondary school level or to participate in the labour force and that is expected to remain with the person for the person’s expected life.

>Persistent or Prolonged Disability:
>Any impairment, including a physical, mental, intellectual, cognitive, learning, communication or sensory impairment - or a
functional limitation - that restricts the ability of a person to perform the daily activities necessary to pursue studies at a post secondary school level or to participate in the labour force and has lasted, or is expected to last, for a period of at least 12 months but is not expected to remain with the person for the person’s expected life.”

- [x] **Reduce the radio button options.** Options should be:
    - [ ] "Yes" 
    - [ ] "No"
<img width="1127" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmhvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ecfc321028f0d4cb85c753905d785b87e097cde0/image.png" alt="image.png" />

- [x] **Create Information Banner.** If 'yes' selected, text should read:  
- [x] Info box header text:  "Information"
> Please note you must have your disability status verified by StudentAid BC to receive disability funding.  If your disability status has already been verified, no further action is required.

> If your disability status has not yet been verified by StudentAid BC,  you must complete an [**Appendix 8  - Disability Programs Application**](https://studentaidbc.ca/sites/all/files/form-library/appendix_8.pdf) to verify your permanent, or persistent or prolonged disability, and have your disability approved. 

> Students with a permanent disability, or a persistent or prolonged disability may qualify for other programs. Contact the Accessibility Services Coordinator or financial aid office at your school, or visit [www.StudentAidBC.ca](https://studentaidbc.ca/)"

<img width="1384" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnliQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9a8419f08bf0d612d54297a9b6b7d191f4227738/image.png" alt="image.png" />

**Comment by ninosamson** [comment]
@JerPearson Can you please confirm if this is a duplicate?

**Comment by JerPearson** [comment]
@katrina-aot-git I noticed I made a spelling error in the tool tip for PD/PPD.  Under the PPD section of the tool tip "postsecondary" was showing without a space so I had made an update to the AC to the correct spelling 'post secondary'

**Comment by katrina-aot-git** [comment]
@JerPearson I'll make the same adjustment to the application disability tooltips as well.
