### ISSUE TITLE
BUG - Institution Reports Have Unexpected Error

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#3432]
**Current Behaviour**
When logged in as a BC Public Admin trying to generate the Offering Details Report I receive an unexpected error while downloading the report. It also does not prompt for intensity (mandatory for all reports)

<img width="1495" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkp5QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5459cc4cb2bfed7da063b475709b15e10811db28/image.png" alt="image.png" />

**Additional Context**
[Teams Channel Thread](https://teams.microsoft.com/l/message/19:9feec5c00f8141aea3af18d53a205a6a@thread.tacv2/1718652811581?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&groupId=454b1d3b-af0f-4b44-b891-f4320c85d290&parentMessageId=1718652811581&teamName=External%3A%20AEST-SIMS&channelName=General&createdTime=1718652811581)
- Was successfully working May 23 in TEST
- Confirmed with SWilliams that it is also occuring in PROD
- DEV & (Lewis') LOCAL both generating error
- From Andre:
    I think that requires a ticket to investigate it but as I could see, the report query is expecting `offeringIntensity` and `institutionId` but the UI is not displaying `offeringIntensity`. Maybe it was an issue reusing the UI component. I'm not totally sure.

**Comment by andrewsignori-aot** [comment]
@CarlyCotton is this bug considered a high-priority?

**Comment by CarlyCotton** [comment]
@andrewsignori-aot Yes, high-priority but not hotfix level of priority. There are other tickets in progress for institution reports in this current sprint.
