### ISSUE TITLE
Content: Student: Basic BCeID Create Profile

### ISSUE THREAD

**Issue by JerPearson** [bcgov/SIMS#3455]
As a student I want to be able to create a SIMS profile after creating a basic BCeID so that I can access the SABC student account.

**Acceptance Criteria**
- [x] **Common to Both** Remove text: "Use your most up to date personal information.  We'll us the same information to help you apply for financial aid"
- [x] **Common to Both** Revise header: "Your profile info" to "Profile information"
- [x] **BCeID Only** Revise text: "Please ensure your information below matches....." to "Please ensure your profile information exactly matches the information you provided on the identity verification form issued to you by StudentAid BC."
- [x] **BCeID Only** Remove text: "Because your information is used across your application(s)....."

<img width="1375" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmlWQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0a214302b3d7175f3e5bda90b09e7263d4bd5568/image.png" alt="image.png" />

- [x] **Common to Both** Revise: "Email" to "Email address"
<img width="607" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNCtKQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f18cc4fdde7d0667d8d49b7e0a2abdf617822d21/image.png" alt="image.png" />

- [x] **Common to Both** Revise header: "Your contact info" to "Contact information"

<img width="833" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUNKQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ffb5157c25b9f740ae37ab80aa9576c2d74b8048/image.png" alt="image.png" />

- [x] **Common to Both** Revise: "Your consent" to "Declaration" 
<img width="975" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2FWQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--335cbc533b2dee98108c492c4b9daab220bf28d3/image.png" alt="image.png" />

Declaration content update: [3456](https://app.zenhub.com/workspaces/student-information-management-system-5fce9df5aa1b45000e937014/issues/gh/bcgov/sims/3456)

**Additional Context**
- enter text here
- enter text here

**Comment by CarlyCotton** [comment]
Updated ticket to clarify between the common and login-specific items for BCeID/BCSC users
