### ISSUE TITLE
Bug - trusted contact fails to revalidate 

### ISSUE THREAD

**Issue by Joshua-Lakusta** [bcgov/SIMS#3468]
**Describe the Bug**
When you fail to complete all of the trusted contact information and try to move forward. If you go back and resolve the fields it still does not treat it as fixed.

**Expected Behaviour**
What should happen is when the info is added it should identify that the question is now correct and allow you to move forward

**Actual Behaviour**
When you fail to complete all of the trusted contact information and try to move forward. If you go back and resolve the fields it still does not treat it as fixed.

** Steps To Reproduce**
Steps to reproduce the behaviour:

1. Create a New application (I used 23-24)
2. Go to personal information section
3. Complete all other questions on the page except trusted contact
4. select yes to trusted contact
5. complete name but do not select a relationship
6. click next section
7. It flags the error for missing information
8. Try to select and relationship
9. Try to move forward and it does not unflag the missing information validation

Additional context:
I redid this test with each piece missing and the error occurred. Left first name blank, then last name, and relationship.
View post fixing and after I selected next section

<img width="1262" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkdiQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--04327cf63fc5eba872a7d4f8837ea6ab0ad32a7d/image.png" alt="image.png" />

related to #3485

**Comment by andrewsignori-aot** [comment]
@Joshua-Lakusta we checked this during DEV Dress and we were non longer able to reproduce it.
Can you please check it?

**Comment by Joshua-Lakusta** [comment]
@andrewsignori-aot I will take a look

**Comment by Joshua-Lakusta** [comment]
@andrewsignori-aot  I have confirmed that this is no longer occurring. I'm curious if the veutify update helped but tried it multiple times and am un able to recreate now. closing ticket
