### ISSUE TITLE
Content: Student: BCSC: Create your profile 

### ISSUE THREAD

**Issue by JerPearson** [bcgov/SIMS#3470]
As I student I want clear instructions when logging in with my BC Services Card for the first time and creating my profile.

**Acceptance Criteria**
- [ ] **Common to Both** Remove text: "Use your most up to date personal information. We'll use the same information to help you apply for financial aid."
- [ ] **Common to Both** Revise text: "Profile Information" to "Profile information:
- [ ] **BCSC only** Revise text: Remove "here" from sentence and add "." after "up-to-date."
- [ ] **BCSC only** Revise info box header: "How to update your information" to "Information"
- [ ] **BCSC only** Revise info box text:  "Your information above is taken from...." to "Your information above is taken from your BC Services Card account. If the information is incorrect, please update your information with [BC Services Card account.](https://www2.gov.bc.ca/gov/content/governments/government-id/bc-services-card/your-card/change-personal-information)

<img width="1328" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHkxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2f6df2fbc54bfd1a50f8714c82aa211a3e3f8e4f/image.png" alt="image.png" />

- [ ] **Common to Both** Revise text: "Your consent" to "Declaration"

<img width="412" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUtjQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0518f900e1f3558a4cc2ad09051ef966b9d4b397/image.png" alt="image.png" />

Additional Information:

- [ ] Related to [3456](https://app.zenhub.com/workspaces/student-information-management-system-5fce9df5aa1b45000e937014/issues/gh/bcgov/sims/3456) account declaration updates

**Comment by CarlyCotton** [comment]
Updated ticket to clarify between the common and login-specific items for BCeID/BCSC users

**Comment by CarlyCotton** [comment]
@bidyashish Thank you, definitely a miss on my part. Updated the AC.
