### ISSUE TITLE
Student: New applications: Student can no longer immediately add trusted contact when "Yes" is selected similar to Add a dependant feature

### ISSUE THREAD

**Issue by astridSABC** [bcgov/SIMS#3485]
### **Related to #3468**

**Describe the Bug**
Create a new application to reproduce the bug, as the edit application does not reproduce it.
Student can no longer immediately add trusted contact when "Yes" is selected (similar to Add dependants feature)

**Expected Behaviour**
Upon selecting the "Yes" option, the student can immediately enter their trusted contact's first name, last name, select the appropriate radio button option and there is a clear button.  There is a button "Add another trusted contact" available to add more.

Note: Review the use of the asterisk.  Column names with asterisk is sufficient.
Nice to have enhancements: 
- [ ] Remove red * asterisk at the top of the table since all the other column names have *.  
- [ ] Remove red * in the editable fields in the First name and last name columns
- [ ] Remove red * that are beside all the radio buttons:

     - Parent/step-parent/sponsor/legal guardian
     - Spouse/common-law partner
    - Relative
    - Other

<img width="1139" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3UxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--78ae53e4c9267137dd8d67aeaf1cb9da24f0d789/image.png" alt="image.png" />

**Actual Behaviour**
Windows Chrome: When the student selects the "Yes" radio button, a table is displayed and they can enter information in the editable fields and no delete button.  When they select "Add another trusted contact" the information in the top row disappears. Or they select "No" and then "Yes" again, the correct layout of the table is displayed.

Note: Sometimes the same table that displays on Windows Edge (no fields) will display on Windows Chrome. 

<img width="502" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOSsxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aee06e3be8163d8a8fa8bbd5f266d19c0b698ac7/image.png" alt="image.png" />

Windows Edge/Mac Safari and Chrome: The student either has to select "Add another trusted contact" or they select "No", then "Yes" again and the correct table is displayed.

<img width="1000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3kxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ab6f50ff8fb3c1537c024d171613f0a29a9bfe42/image.png" alt="image.png" />

** Steps To Reproduce**

Precondition: A student user can create an application. A new application needs to be created. 
1. Click "Start an application" button
2. Select an option from the "Please select your program year..." dropdown list
3. Click "Start Application" button
4. Select any data in the program tab that will create a program (this step is not necessary)
5. Select "Personal information" tab
6. Scroll to the "Share information with trusted contact" section
7. Select "Yes" radio button
8. Review the table that is displayed

Bug: #3468 may be related

Reviewed asterisks with JP.

**Comment by CarlyCotton** [comment]
@andrepestana-aot As discussed regarding the request of which asterisks to keep and which to remove. The green boxes are ones to keep and the red would be removed:
<img width="1163" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXpKQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d30c5cadd8f971a650e9bf5e86ee91a0a0a884a5/image.png" alt="image.png" />
