### ISSUE TITLE
Content fixes for previous issues

### ISSUE THREAD

**Issue by astridSABC** [bcgov/SIMS#3486]
Various fixes from other ZH issues

**Acceptance Criteria**

On _Apply for disability status popup information_ (Go to Profile>Apply for disability status)

- [x] Remove "a" and revise "d" and "s" to lower case "disability status" (sentence case) 

<img width="500" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDIyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--877bc50b10e1e6a6b41b90fb25748a1d5462cfdc/image.png" alt="image.png" />

Ref #3303

On the Additional transportation 

- [x] Add **bold** style to the three occurrences of "and" 
copy of your vehicle **and**
....letter of explanation **and**
....to and from school or daycare **and**

<img width="500" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3kxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b611c5251a97309dc7794a144af79fd55a76bbe8/image.png" alt="image.png" />

- [x] Add punctuation "." at the end of the "I am in a clinical or practicum placement that requires travel" sentence

<img width="500" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUMyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--83f32a27ef33308e100fa12b1ae72c612a5c8038/image.png" alt="image.png" />

- [x] Add question mark to the end of the "Do you want to be assessed for additional transportation costs" question

<img width="897" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMU1aQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6a89be88e55c59895edde9c908a6927c91a534e5/image.png" alt="image.png" />

Ref #3311

On the FAQ third option on the Welcome to StudentAid BC page on the "I am not eligible for a BC Services Card account. What can I do?" in the _What you need to do_ section 

- [x] Make email address a link "StudentAidBC@gov.bc.ca"

<img width="500" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDYyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--95036e3a308f165c444f9c540b1629f09f2d1a22/image.png" alt="image.png" />

Ref #3301

Information bubble for "Do you have eligible dependants"
The information is cutoff after the third bullet.

- [x] Add all content to information bubble.  Keep SIMS style hyphen intact not the round bullet below (**TBD: May need to chat with @JerPearson if tool tip is too long**)

"For StudentAid BC purposes, eligible dependents/dependants are any dependents for whom the Canada Child Tax Benefit is claimed, or for whom a benefit is claimed on the applicant’s income tax return. Eligible dependents/dependants must meet one of the following criteria:
•	For the student’s or spouse/common-law partner’s children who are 18 years of age and under, the student and/or spouse/common-law partner must be guardians of the children who must live with the student or spouse/common-law partner at least two full days per week; or
•	The student’s or spouse/common-law partner’s children aged 19 to 22 are full-time dependent students in study; or
•	The student’s or spouse/common-law partner’s children are permanently disabled, are 19
years of age or over, are fully supported by the student or spouse/common-law partner and
are claimed on the student’s or spouse/common-law partner’s income tax return; or
•	The children are the student’s foster children and foster-parent income is claimed on the
application; or
•	The dependents are the student’s or spouse/common-law partner’s elderly relatives who
are fully supported by the student and claimed on the student’s or spouse’s income tax."

<img width="500" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeCsyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6a2ad931bd9855c77c9dbe06486f5442dd27a689/image.png" alt="image.png" />

Ref #3309

Personal Information page

- [x] When indicating "Yes" to the Indigenous question revise "Metis" to "Métis" on the multiple choice options that populate
<img width="820" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlFpQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a25553422fee93cf4a1a768e4752ff70089559eb/image.png" alt="image.png" />

Student Home Page

- [ ] On the bulleted list found on the center of the home page
- [x] Remove the "."  from "Apply for student financial assistance." 
<img width="644" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2NpQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f857cbfb20cbdbe0fefb41d8d3b8e685535aeee3/image.png" alt="image.png" />

**Comment by Joshua-Lakusta** [comment]
Added missing question mark on additional transportation question to this ticket as per group discussion.
