### ISSUE TITLE
Make Institution Field Optional on Ministry Programs and Offerings Report

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#3492]
**Acceptance Criteria:**
- [ ] Make the Institution field optional on the Ministry Programs and Offerings report.

**Technical**
- [ ] Follow the same from the "Student Unmet Need" that already has the same as optional.

**Comment by ninosamson** [comment]
Closing this ticket as no longer required, after consulting with @Joshua-Lakusta and @CarlyCotton.
