### ISSUE TITLE
UX/ UI- Draft a Priorities Timeline

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#350]
**Consider**
 Quick wins
 Dependencies 
 Things we really need to noodle through
Small Med Large Efforts
 
eg: Ministry workflow (approvals) and supporting exception pathways and required manual interviews. 
      Notifications 

- [ ] Confirm whats remaining and propose whats next

**Comment by roopfw** [comment]
Refer to Alys' MVP Roadmap doc…

**Comment by hellolynn-dsib** [comment]
Lynn to start the process while folks are working on other tickets. Team will reconnect/discuss.

**Comment by hellolynn-dsib** [comment]
Team connected EOD Wednesday. Lynn drafted version Friday. Team to reconvene Monday and finalize for review.
