### ISSUE TITLE
Additional transportation calculation updates

### ISSUE THREAD

**Issue by Joshua-Lakusta** [bcgov/SIMS#3505]
As a student I want the additional transportation to calculate correctly based on the changes to the forms on #3351.

**Acceptance Criteria**
- [x] Update the part-time dmn table file to include "dmnPartTimeProgramYearMaximums.limitAdditionalTransportationNonOwner":
<img width="583" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdy9aQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--39e19aed5434e0ea7caac892367ce6f3b0abf8ef/image.png" alt="image.png" />

- [x] Update the application variable names as needed based on the changes to form on #3351:

| Question | Response | Old Variable | New Variable | 
|----------|----------|----------|----------|
| 1. Do you want addtl transport?  | Yes/No   | studentDataEligibleForAnAdditionalTransportationAllowance   | studentDataAdditionallTransportRequested  |
| 2. Are you the listed driver?    | Yes/No  | _n/a_  | studentDataAddtionalTransportListedDriver   |
| 3. Are you the owner?    | Yes/No  | _n/a_  | studentDataAddtionalTransportOwner   |
| 4. Weekly KM     | 1-999   | studentDataAdditionalTransportKm   | _no change_   |
| 5. Is their a clinical practicuum?     | Yes/No  | studentDataAdditionalTransportPlacement   | _no change_   |
| 6. Weekly travel costs    | 1-999  | studentDataAdditionalTransportCost | **removed**  |

- [x] Update the Change Request variable names to align with the application names above.
- [x] Update the appeals section of the assessment to reflect the change in variables/values & use the corresponding
- [x] Replace entire current additional transportation flow (see business context) in all part-time assessment flows with new one:
<img width="521" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFBaQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4d05659d34cad0f4fe6741582f8cbb3a5697f9a1/image.png" alt="image.png" />
- [x] Initial Exclusive gateway: Upper path = Additional Transportation Requested (studentDataAddtlTransportRequested == Yes && studentDataAddtlTransportListedDriver == Yes), the lower path for everything else
- [x] Lower Path (NO Addtl Transport) under "Total Transportation Allowance" **calculatedDataTotalTransportationAllowance** : 

```
if(offeringDelivered = "onsite")
then 
  offeringWeeks *  dmnPartTimeProgramYearMaximums.limitTransportationAllowance
else
  0
```
- [x] Upper Path "Limit Transportation Weeks" **calculatedDataAdditionalTransportWeeks**: 
```min(offeringWeeks, studentDataAdditionalTransportKm)```
- [x] Upper Path "Limit Transportation Weeks" **calculatedDataRemainingTransportWeeks**: 
```
// Accounts for students that request addtl transport for less weeks than their offering period.
if(offeringDelivered = "onsite")
then 
  offeringWeeks - calculatedDataAdditionalTransportWeeks
else
  0
```
- [x] Upper Path "Additional Transportation Allowance" **calculatedDataWeeklyMaxAdditionalTransport**:
```
//If the student is the owner then they are eligible for the maximum weekly allowance. If not the owner, the maximum weekly is the non-owner amount.
if (studentDataAdditionalTransportOwner = true)
then
dmnPartTimeProgramYearMaximums.limitAdditionalTransportationAllowance
else dmnPartTimeProgramYearMaximums.limitAdditionalTransportationNonOwner
```
- [x] Upper Path "Additional Transportation Allowance" **calculatedDataWeeklyMinTransport**:
```
//If student is in onsite courses they get a minimum per study week, otherwise 0
if(offeringDelivered = "onsite")
then 
 dmnPartTimeProgramYearMaximums.limitTransportationAllowance
else
  0
```
- [x] Upper Path "Additional Transportation Allowance" **calculatedDataWeeklyAdditionalTransportCost**:
```
//Multiplier for their weekly kms vs the max
MIN(calculatedDataWeeklyMaxAddtlTransport,studentDataAdditionalTransportKM * dmnPartTimeProgramYearMaximums.limitAdditionalTransportationKMReduction)
```
- [x] Upper Path "Additional Transportation Allowance" **calculatedDataNetWeeklyAdditionalTransportCost**:
```
//If placement then placement reduction. Otherwise none.
if studentDataAdditionalTransportPlacement = true
then MAX(calculatedDataWeeklyAdditionalTransportCost - dmnPartTimeProgramYearMaximums.limitAdditionalTransportationPlacement,
  calculatedDataWeeklyMinTransport)
else
calculatedDataWeeklyAdditionalTransportCost
```
- [x] Upper Path "Additional Transportation Allowance" **calculatedDataTotalAdditionalTransport**:
```
//Multiples the higher of the minimum transportation cost or weekly addtl transport cost by the number of weeks requested by the student
calculatedDataNetWeeklyAdditionalTransportCost * calculatedDataAdditionalTransportWeeks
```
- [x] Upper Path "Total Transportation Allowance" **calculatedDataTotalTransportationAllowance**:
`calculatedDataTotalAdditionalTransport + (calculatedDataRemainingTransportWeeks * calculatedDataWeeklyMinTransport)`

**Additional Context**
Proposed [BPM Changes for additional transport](https://bcgov.sharepoint.com/:u:/r/teams/03177/Shared%20Documents/DEVS/BPM%20Workflows/%233505,%233351/ProposedAdditionalTransportation.bpmn?csf=1&web=1&e=DY7rP4) (Under AEST-SIMS>Devs>BPM Workflows>#3505,#3351)
App & Change Request Questions updated on #3351
New rules for calculation:
- Maximum when student is owner of the vehicle is $94 per week .
- Maximum when student is not the owner of the vehicle is $69 per week.
- Minimum when offering is onsite is $13 per week.
- Minimum when offering is NOT onsite is $0 per week.
- Weekly travel KM is multiplied by 0.34 within the MAX and MIN per week above to find weekly amt.
- Placement calculation is $25 less than he final calculated weekly amount down to the minimum per above.

Current Flow:
<img width="1171" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeExaQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b5f4f6c8f7f139d69ea3dd1ad0ca479d87812af2/image.png" alt="image.png" />

Test scenario examples
<img width="1150" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1hzQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9d419d7e9656410b5dfa6489e288063371bfa990/image.png" alt="image.png" />

**Technical**
- [ ] Change the DMN with the new column values dmnPartTimeProgramYearMaximums.limitAdditionalTransportationNonOwner.
- [ ] Update the Additional Transportation in the existing workflow from the bpmn "parttime-assessment-XXXX-XXXX.bpmn" for all the years with the provided reference above.
- [ ] There will be change in the Additional Transportation appeals flow to include new variable and renaming the existing one. <img width="1818" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXZrQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1872534dd8978255d5e2bee99dc610ab2d6214d8/image.png" alt="image.png" />
- [ ] Update the existing test case E2E with the provided sample data and output that was requested from test scenarios from Carly and Josh
- [ ] Updating the old data(either in reports or old application data) is not part of this effort.

**Comment by andrewsignori-aot** [comment]
@CarlyCotton to add the BPMN for reference.
@Joshua-Lakusta to provide test input scenarios and expected outputs.

**Comment by guru-aot** [comment]
If some report is using the existing additional transportation variables, this changed variable will not be fetched, if a change is required or investigated, please create tickets. @CarlyCotton  @Joshua-Lakusta

**Comment by dheepak-aot** [comment]
As discussed with @Joshua-Lakusta @CarlyCotton there is a minor update to the way how `calculatedDataNetWeeklyAdditionalTransportCost` is calculated.

<img width="827" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzBJQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c4f82d3da6692a9722eb749406bb8406471ef123/image.png" alt="image.png" />

<img width="809" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzRJQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--287521b7269a63520a4ed5f17baa25541125384f/image.png" alt="image.png" />
