### ISSUE TITLE
Revise PT scholastic standing consequences - skip directly to PTSSR

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#3511]
User Story
As a ministry user I want the PTWTHD to be applied when a withdrawal is reported  on PT and show on the ministry portal. I also want PTSSR to be shown in the accordion list under the activity page for students when they have the restriction. This is important so that they understand what is happening to them in terms of restrictions and why they are blocked from funding.

**Acceptance Criteria:**
- [x] When a withdrawal is reported the PTWTHD restriction should be applied along with the PTSSR. The PTWTHD should not have an impact and should only show to the ministry user. It should be viewable by a ministry user for record keeping purposes. (see image below for the ministry view post reporting a withdraw.)

Business context

<img width="1502" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVZKQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--10031bcffe0ed2589fadee3a288b8ed022e6c82e/image.png" alt="image.png" />

**Technical**
- [x] Ensure the creation of the `PTWTHD` at the same time and under the same condition of the `PTSSR`.
- [x] Create at least one E2E test to validate its creation.

**Comment by CarlyCotton** [comment]
Based on Lather - going to receive most recent table of restriction information and compare to the table in the ticket. 
Todo:
Identify areas that have NO change required btw file attached and new table
Only highlight the cells (not the whole line) that requires updates
Verify Federal/Provincial if they should be inconsistent between restriction_type and restriction_category

If we receive a federal restriction that SIMS doesn't list as federal it could create blocks/unnecessary _new_ restrictions added
Re: BCLM and "Stop full time BC funding" vs This should be BCSL only and allow BC Grants - should have a conversation about current functionality to ensure same page of current/expected functionality

**Comment by andrewsignori-aot** [comment]
The `PTWTHD` will have its behavior updated as this ticket requires on #3512.
The tickets can be developed in parallel with the understanding of the goal of generating the `PTWTHD` only.

**Comment by andrewsignori-aot** [comment]
@CarlyCotton can we do the below AC alongside the development of #3634 since they will change the same page and are now in the same sprint?
"Add a new accordion to the student Account Activity Page provincial restriction list with PTSSR code under the provincial restrictions."

**Comment by CarlyCotton** [comment]
@andrewsignori-aot Yes. As long as the work gets done, it doesn't matter to me which ticket it comes in on.

**Comment by CarlyCotton** [comment]
Removing the two ACs that dealt with the new accordion content on the restrictions page and adding them to #3634:
- [ ] Add a new accordion to the student Account Activity Page provincial restriction list with PTSSR code under the provincial restrictions. 
- [ ] Add text to the accordion drop down that reads:
> "Your account is restricted from future part-time funding due to poor scholastic standing. You are no longer eligible to receive student financial assistance. If you need more information or have concerns, please contact StudentAid BC."
