### ISSUE TITLE
Review Impact of All Restrictions

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#3512]
**Acceptance Criteria:**
- [x] Update restrictions per the spreadsheet to ensure all behaviors and names are updated. ALL CHANGES ARE IN HIGHLIGHTED CELLS
- [x] NOTE There are other updates to when the PTWTHD restriction is applied and accordion behavior for PTSSR. (Effects are updated within this spreadsheet)
- [x] Note ID #8 was previously APPC and the name is being changed to HOLD (line 9 on the spreadsheet)
- [x] In the document below, "Part Time" and "part time" may be used interchangeably. Please use whatever case the existing effects are and be consistent across FT/PT.

Document for revision:

[UPDATED RESTRICTION LIST](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTFWQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--764aa9ec4b55b20aa189a8d382857961a028f00d/updates_to_restrictions.xlsx)

**Technical**
- [x] Crate a DB migration to update the `sims.restrictions`.
- [x] Use the `restriction_code` to apply the updates.

**Comment by CarlyCotton** [comment]
Based on Lather - going to receive most recent table of restriction information and compare to the table in the ticket. 
Todo:

- Identify areas that have NO change required btw file attached and new table
- Only highlight the cells (not the whole line) that requires updates
- Verify Federal/Provincial if they should be inconsistent between restriction_type and restriction_category

If we receive a federal restriction that SIMS doesn't list as federal it could create blocks/unnecessary _new_ restrictions added
Re: BCLM and "Stop full time BC funding" vs This should be BCSL only and allow BC Grants - should have a conversation about current functionality to ensure same page of current/expected functionality

**Comment by CarlyCotton** [comment]
Updated the list based on grooming discussion today.

**Comment by CarlyCotton** [comment]
@lewischen-aot Updated to add an AC based on the question about if we need "Part Time" to be exactly in the case specified or if it could be "part time"

**Comment by andrewsignori-aot** [comment]
The spreadsheet contains a new type for stop the BC funding for part-time applications, similar to what is in place for full-time. The restriction action will be added to DB but the change in the part-time calculations is not in the scope of this ticket.
