### ISSUE TITLE
Update Ministry User Roles  /Groups

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#3519]
**Acceptance Criteria:** 
- [ ] Create new user groups per the matrix file (See Fig 1)
- [ ] Update all user tasks & groups per above document

Fig 1:
<img width="997" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW5lQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6a701fa818a2c4d4b1ed2d13820015e4854f336c/image.png" alt="image.png" />

Note: 
- This list has been put to Nate and Liz for Service Delivery review but has received no response

**Comment by michesmith** [comment]
Cancelling- as this is a process issues and will need to go in Jira
