### ISSUE TITLE
Create Education Program Data model

### ISSUE THREAD

**Issue by 2011sandeepraj** [bcgov/SIMS#353]
**Additional Context**
Data model and a team to ensure fluidity amongst team members

**Acceptance Criteria**
Review and complete datamodel for each of the below
- [x] Education Program (Program and Offering)

**Comment by abschwenker** [comment]
[https://app.zenhub.com/files/319429847/7bba4675-ffa8-4267-86e9-3af693dd0348/download](https://app.zenhub.com/files/319429847/7bba4675-ffa8-4267-86e9-3af693dd0348/download)

![image.png](https://images.zenhubusercontent.com/5fce9c77aab275719112dc74/ae115be0-1b52-41b5-ab51-285fe73de8af)

**Comment by abschwenker** [comment]
Please note: tables and column names are not final. Developer to adjust as per standards when implementing
