### ISSUE TITLE
UX / UI V3 Institution Manage Locations Summary List Page 

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#359]
As an institution user Institution from the settings page i can view a page that has all the locations listed.

Info on the Manage Locations List Page 
-Location Name
-Location Address?
-Primary Contact Per Location
-Designation Status. (remove status)

As a admin user i am able to manage locations details such as:

- -Edit Information for the Location as button:
 - Edit
 - Remove
 - Add new location button

***Users are in the details of each location (so not shown on this screen)

**Comment by roopfw** [comment]
![image.png](https://images.zenhubusercontent.com/5e66ca845237f60c730a4aa3/61dfbe2c-3081-4c7d-8d57-c50a079be72f)

[Figma Link](https://www.figma.com/proto/VykmBDwobGoGvK9M5wgOvN/StudentAid-BC-App-Design-System-WIP-FreshWorks-Studios?page-id=642%3A2733&node-id=1057%3A409&viewport=47739%2C11039%2C0.929593026638031&scaling=min-zoom)
