### ISSUE TITLE
Update data inventory report SQL with updated dynamic variables

### ISSUE THREAD

**Issue by dheepak-aot** [bcgov/SIMS#3616]
**Describe the task**
Update the data inventory report to be in sync with the updated dynamic variables.

## Issues that has been noticed to be impacted in DATA INVENTORY REPORT

**Acceptance Criteria**
- [ ] The variable `validDependent` has been removed from student application form but it is still used in data inventory report SQL and needs to be updated.(This value to be used must come from workflow data)
- [ ] The student application variable `pleaseProvideAnEstimationOfYourParentsIncome` has been updated to `studentParentsTotalIncome` and the same needs to be adjusted in data inventory report SQL.
- [ ] The data inventory report SQL is using the key of a form panel which is `totalUnsubsidizedDayCareCostsDuringClassHoursForTheProposedStudyPeriodForDisabledInfirmedDependents12YearsOfAgeAndOlderPanel` insted of a form input object. Hence the SQL of data inventory report needs to be updated.

**Comment by michesmith** [comment]
close it as obsolete and note that we'll have a ticket to sunset the data inventory
