### ISSUE TITLE
SFAS-SIMS Bridge File - Update layout and Insert PT MSFAA info

### ISSUE THREAD

**Issue by michesmith** [bcgov/SIMS#3623]
**User Story**
As a student, it is possible for me to have two MSFAA numbers (PT and FT). I don't want to have a new one issued by SIMS when I already have a valid one in SFAS/SAIL. 

**Acceptance Criteria**
- [ ] Needs to be released ASAP to support re-start of bridge file information as release first part of 1.15 release. 
- [ ] Update expected file layout for SFAS to SIMS bridge to include the second set of MSFAA information for PT (number and effective date) [SFAS to SIMS Bridge v2.0.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzRmQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--571eeb815c841e8fe6350765c78a02a6e64b3e35/SFAS%20to%20SIMS%20Bridge%20v2.0.docx)

 

**Business Context**
- Only VERIFIED MSFAA SAIL data will be reported. (This is a status in SAIL that is displayed based on the validity of the MSFAA number.)
- We are receiving the "Effective Date" for PT MSFAAs. As noted in the bridge file layout, this is really the only date data that we have easily accessible from SAIL for the MSFAA.  The signed date is contained within a text file in a BLOB field in another table, which is difficult to get at.  At this time, we are not going to try and get the signed date, but we will be using the effective date on this table, which is actually the date that the MSFAA request was created and should be close enough.
- We recognize that the gap between effective date and signed date could result in us declaring a MSFAA number "expired" slightly sooner than it would normally. This amounts to a small risk based on volume of students in PT with the circumstances that could end up in that situation. It results in the least number of students being impacted by having to be re-issued an MSFAA pre-maturely or worse, during an active application in the legacy systems.
- NULL date_requested/sent date would indicate that it is an imported MSFAA number

**Comment by CarlyCotton** [comment]
@Joshua-Lakusta I've added some tiny ACs here and will bring to SOAK so we can have our devs add the additional fields to support the two MSFAAs and actually use it when it comes over.

**Comment by Joshua-Lakusta** [comment]
Set up additional meeting with Jason to validate what information is being brought over for MSFAA and then we can move ticket forward to confirm consumption of information into the system instead of just saving to database.

**Comment by andrewsignori-aot** [comment]
## Demo

Used the below file to import MSFAA Part-time information.
```txt
100AESTSFAS TO SIMS BRIDGE                    20240709110630                                                                                                                                                                                              
2000000083540GIORGIO        GIOVANNI                                19660721121380174Y19660721Y1967072298765432102024071276543210010000005000000000500000007560500000756050000007413000000741300000074130000007413000000000020000000017                  
2000000083541GIORGIO        GIOVANNI                                19491116108796293N        N        98765432112024071376543220020000005000000000500000011040000001104000000110400000011040000001104000000110400000000000020000000002123456789020241231
2000000083542GIORGIO        GIOVANNI                                19700702122886591                  00000000000000000000000000000000000000000000000000000000000000000000000000000000011039000000000000000000000000000000000000000000                  
999000048090000009580094900                                                                                                                                                                                                                               
```

<img width="735" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUkxQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a8ddfa4082c947ce624165d37d31a3f301786fa5/image.png" alt="image.png" />
