### ISSUE TITLE
BUG: PT Test Envi (stg) for ASAP: Ministry: Internal Server Error: Basic BCeID user cannot be added to Institution Account

### ISSUE THREAD

**Issue by astridSABC** [bcgov/SIMS#3628]
**Describe the Bug**
Basic BCeID user cannot be added to an Institution Account through the [Ministry Portal - PT SIMS Test  for ASAP (staging)](https://stg-aest-sims.apps.silver.devops.gov.bc.ca/ministry/dashboard)

Note: This may be related to the OCIO issue on Thursday August 8th.  

**Expected Behaviour**
Basic BCeID user is added as an Admin to the Institution

**Actual Behaviour**

Error Message "Internal server error" is displayed

<img width="300" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHRVQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--62727be601bd69816226fc8f46dd766aba8a3b55/image.png" alt="image.png" />

User cannot be added to the account

 ### **Steps To Reproduce**

**Preconditions**

Basic BCeID Institution user has been created at the: [Institution Portal - PT SIMS Test for ASAP (staging)](https://stg-aest-sims.apps.silver.devops.gov.bc.ca/institution/login)

Verify you can login to the institution portal with new Basic BCeID

Ministry user has created an institution account (e.g. SABC TEST) on the [Ministry Portal PT SIMS Test for ASAP (staging)](https://stg-aest-sims.apps.silver.devops.gov.bc.ca/ministry/dashboard)

Logged in as a Ministry user on the [Ministry Portal - PT SIMS Test for ASAP (staging)](https://stg-aest-sims.apps.silver.devops.gov.bc.ca/ministry/dashboard)

Steps to reproduce the behaviour:
1. Click "Search Institutions" link on the left margin
2. Enter operating name for Institution that was created above (e.g. SABC TEST)
3. Click "Search" button
3. Click "View" button on the right
4. Click "Users" link on the Institution Details banner
5. Click "Add new user" button
6. Enter the Basic BCeID username created on the PT SIMS Test Environment for ASAP () (e.g. SABC1)
7. Toggle the Admin slider to "On"
8. Click "Add user now" button

**Comment by CarlyCotton** [comment]
Issue Resolved
