### ISSUE TITLE
Content: Student: Account Activity: Restrictions 

### ISSUE THREAD

**Issue by JerPearson** [bcgov/SIMS#3634]
**As a** *student* **I want** detailed information about the restrictions on my account  **So That** I can better understand how to resolve/next steps.

**Acceptance Criteria**

For all content updates below remove all text currently displayed and replace with revised wording.

Provincial Restrictions 

- [x] **Code 12 - Denied from poor scholastic standing** - **REMOVE**

- [x] **Code B3D - B.C. loan in default**
>  Your B.C. loan is in default and has been transferred to the Revenue Services of British Columbia for further collection activity.  You are restricted from further StudentAid BC funding. Please contact Revenue Services of British Columbia immediately before your credit rating is further impacted: 1-866-361-5050 (Toll free within North America) or 250-387-6093 (outside North America).

- [x] **Code B6A - Bankruptcy**
> According to the information on file, you have declared bankruptcy involving student loans.  As your bankruptcy involves student loans, you are not eligible for funding through StudentAid BC and your application is currently restricted.

> If you have declared bankruptcy in which Canada student loan or British Columbia student loan funds were involved, you cease to be eligible for both federal and provincial assistance.  You may be considered for further student financial assistance if federal and/or provincial authorities approve of the steps taken to meet rehabilitation criteria on your outstanding debt(s). For further information regarding rehabilitation with respect to Canada student loan funds, please contact the Canada Student Financial Assistance Program at 1-888-815-4514 to speak with a Case Review Officer. For further information regarding rehabilitation with respect to BC student loan funds, please contact StudentAid BC at 1-800-561-1818 (within North America) 250-387-6100 (outside North America).

- [x] **Code ECRS - Early completion** 
>We have been advised that you completed your part-time program of study early. Therefore, the change in your study period end date has been recorded at StudentAid BC. For further information please contact StudentAid BC at 1-800-561-1818 (within North America) 250-387-6100 (outside North America).

- [x] **Code PTSSR - Poor scholastic standing** - **NEW ADDITION**
> "Your account is restricted from future part-time funding due to poor scholastic standing. You are no longer eligible to receive student financial assistance.  Students who have not successfully completed courses funded through student financial assistance may be reinstated to receive further part-time funding either by submitting a successful appeal or by successfully completing one semester funded through their own resources.  For further information please contact StudentAid BC at 1-800-561-1818 (within North America) 250-387-6100 (outside North America).

- [x] **Code SSR - Poor scholastic standing**

> A review of your scholastic standing while receiving student financial assistance indicates that you have withdrawn on two occasions or have failed to successfully complete 68 weeks of funded post-secondary study.  By policy, this disqualifies you from further funding and a restriction has been placed on your file.

> Although you are not eligible for funding, you may apply to continue, or rehabilitate, your in-study payment-free status whenever you are enrolled in at least 60 per cent of a full-time course load of post-secondary study (40 per cent for students with a permanent disability, or a persistent or prolonged disability, who have been approved by StudentAid BC to study at the reduced course load) by submitting an in-study payment-free status application to the financial aid office at your school. For further information please contact StudentAid BC at 1-800-561-1818 (within North America) 250-387-6100 (outside North America).

- [x] **Code UNCL - Maximum funding of unclassified funding**
> Students enrolled in 'unclassified studies' may be eligible for a maximum of 52 weeks of funding through StudentAid BC.  You have exceeded the maximum allowable funded weeks for unclassified studies.  For further information please contact StudentAid BC at 1-800-561-1818 (within North America) 250-387-6100 (outside North America).

- [x] **Code B2D - B.C. loan delinquency**
> Our records indicate you are delinquent on your British Columbia student loan payments which disqualifies you for further funding through StudentAid BC. For information regarding your delinquency status, please contact your lender.
To be considered for further funding through StudentAid BC, please contact StudentAid BC at 1-800-561-1818 (within North America) 250-387-6100 (outside North America).

- [x] **Code B2 - B.C. loan delinquency**
> Our records indicate you are delinquent on your British Columbia student loan payments which disqualifies you for further funding through StudentAid BC. For information regarding your delinquency status, please contact your lender.
To be considered for further funding through StudentAid BC, please contact StudentAid BC at 1-800-561-1818 (within North America) 250-387-6100 (outside North America).

- [x] **Code SINF - Temporary Social Insurance Number (SIN) expiration**
> Our records indicate that your temporary Social Insurance Number (SIN) has either expired or is not valid for the entirety of your study period. For further information, please contact StudentAid BC at 1-800-561-1818 (within North America) or 250-387-6100 (outside North America).

- [x] **Code BCLM - BC Lifetime Maximum Reached**
> Our records indicate that you have reached your B.C. Lifetime loan maximum, which disqualifies you for further provincial  funding through StudentAid BC.  For further information, please contact StudentAid BC at 1-800-561-1818 (within North America) or 250-387-6100 (outside North America).

- [x] **Code LGCY - Legacy Restriction**
>  Our records indicate you have a restriction on your account from a past student loan that is preventing your application from moving forward.  For further information please contact StudentAid BC at 1-800-561-1818 (within North America) 250-387-6100 (outside North America).

Federal Restrictions 

- [x] **Code 4 - Nearing the lifetime maximum** 
>You are approaching your Canada-B.C. integrated student loan maximum lifetime number of weeks allowable for funding for your current level of study.

>Canada-B.C. integrated student loan lifetime maximums are as follows:

> 	340 weeks of study for loans and/or payment-free status for first time borrowers on August 1, 1995 or later;
>	400 weeks of study for student enrolled in a doctoral program;
>	520 weeks of study for loans and/or payment-free status for students who received assistance prior to August 1, 1995; and
>	520 weeks of study including loans/payment-free status, for students with a permanent disability, or a persistent or prolonged disability, providing the disability status has been approved by the Canada Student Financial Assistance Program.
>If you reach the lifetime maximum during your study period, your funding will be continued to the end of the study period in which you are enrolled. If you have any questions, please contact the Canada Student Financial Assistance Program at 1-888-815-4514 to speak with a Case Review Officer.

- [x] **Code 5 - Reached the lifetime maximum** 
>You have exhausted the Canada-B.C. integrated student loan maximum lifetime number of weeks allowable for funding for your current level of study.  We are unable to issue further assistance through StudentAid BC while this restriction is in effect. 

>Canada-B.C. integrated student loan lifetime maximums are as follows:

>340 weeks of study for loans and/or payment-free status for first time borrowers on August 1, 1995 or later;
400 weeks of study for students enrolled in a doctoral program;
520 weeks of study for loans and/or payment-free status for students who received assistance prior to August 1, 1995; and
520 weeks of study including loans and/or payment-free status, for students with a permanent disability, or a persistent or prolonged disability, providing the disability status has been approved by the Canada Student Financial Assistance Program.
> If you reach the lifetime maximum during your study period, your funding will be continued to the end of the study period on your application.  If you have any questions, please contact the Canada Student Financial Assistance Program at 1-888-815-4514 to speak with a Case Review Officer.

- [x] **Code 6 - Nearing the lifetime maximum**

>You are approaching your Canada-B.C. integrated student loan maximum lifetime number of weeks allowable for funding for your current level of study.

>Canada-B.C. integrated student loan lifetime maximums are as follows:

> 	340 weeks of study for loans and/or payment-free status for first time borrowers on August 1, 1995 or later;
>	400 weeks of study for student enrolled in a doctoral program;
>	520 weeks of study for loans and/or payment-free status for students who received assistance prior to August 1, 1995; and
>	520 weeks of study including loans/payment-free status, for students with a permanent disability, or a persistent or prolonged disability, providing the disability status has been approved by the Canada Student Financial Assistance Program.
>If you reach the lifetime maximum during your study period, your funding will be continued to the end of the study period in which you are enrolled.  If you have any questions, please contact the Canada Student Financial Assistance Program at 1-888-815-4514 to speak with a Case Review Officer.

- [x] **Code 7 - Reached the lifetime maximum**

>You have exhausted the Canada-B.C. integrated student loan maximum lifetime number of weeks allowable for funding for your current level of study.  We are unable to issue further assistance through StudentAid BC while this restriction is in effect.

>Canada-B.C. integrated student loan lifetime maximums are as follows:

>340 weeks of study for loans and/or payment-free status for first time borrowers on August 1, 1995 or later;
400 weeks of study for students enrolled in a doctoral program;
520 weeks of study for loans and/or payment-free status for students who received assistance prior to August 1, 1995; and
520 weeks of study including loans and/or payment-free status, for students with a permanent disability, or a persistent or prolonged disability, providing the disability status has been approved by the Canada Student Financial Assistance Program.
> If you reach the lifetime maximum during your study period, your funding will be continued to the end of the study period on your application.  If you have any questions, please contact the Canada Student Financial Assistance Program at 1-888-815-4514 to speak with a Case Review Officer.

- [x] **Code 8 - Nearing the lifetime maximum**

>You are approaching your Canada-B.C. integrated student loan maximum lifetime number of weeks allowable for funding for your current level of study.

>Canada-B.C. integrated student loan lifetime maximums are as follows:

> 	340 weeks of study for loans and/or payment-free status for first time borrowers on August 1, 1995 or later;
>	400 weeks of study for student enrolled in a doctoral program;
>	520 weeks of study for loans and/or payment-free status for students who received assistance prior to August 1, 1995; and
>	520 weeks of study including loans/payment-free status, for students with a permanent disability, or a persistent or prolonged disability, providing the disability status has been approved by the Canada Student Financial Assistance Program.
>If you reach the lifetime maximum during your study period, your funding will be continued to the end of the study period in which you are enrolled.  If you have any questions, please contact the Canada Student Financial Assistance Program at 1-888-815-4514 to speak with a Case Review Officer.

- [x] **Code 9 - Reached the lifetime maximum**
>You have exhausted the Canada-B.C. integrated student loan maximum lifetime number of weeks allowable for funding for your current level of study.  We are unable to issue further assistance through StudentAid BC while this restriction is in effect.

>Canada-B.C. integrated student loan lifetime maximums are as follows:

>340 weeks of study for loans and/or payment-free status for first time borrowers on August 1, 1995 or later;
400 weeks of study for students enrolled in a doctoral program;
520 weeks of study for loans and/or payment-free status for students who received assistance prior to August 1, 1995; and
520 weeks of study including loans and/or payment-free status, for students with a permanent disability, or a persistent or prolonged disability, providing the disability status has been approved by the Canada Student Financial Assistance Program.
> If you reach the lifetime maximum during your study period, your funding will be continued to the end of the study period on your application.  If you have any questions, please contact the Canada Student Financial Assistance Program at 1-888-815-4514 to speak with a Case Review Officer.

- [x] **Code AV - Maximum for an aviation program**

> Your application for assistance through StudentAid BC has been denied.  You have been issued your maximum entitlement to funding through StudentAid BC for aviation programs. For further information please contact StudentAid BC at 1-800-561-1818 (within North America) 250-387-6100 (outside North America).

- [x] **Code B6 - Bankruptcy**
> According to the information on file, you have declared bankruptcy involving student loans.  As your bankruptcy involves student loans, you are not eligible for funding through StudentAid BC and your application is currently restricted.
You should note the following:

> Rehabilitation Through StudentAid BC
If you have declared bankruptcy in which Canada student loan or British Columbia student loan funds were involved, you cease to be eligible for both federal and provincial assistance.  You may be considered for further student financial assistance if federal and/or provincial authorities approve of the steps taken to meet rehabilitation criteria on your outstanding debt(s).

>If you have any questions, please contact the Canada Student Financial Assistance Program at 1-888-815-4514 to speak with a Case Review Officer.  For further information regarding rehabilitation with respect to BC student loan funds, please contact StudentAid BC at 1-800-561-1818 (within North America) 250-387-6100 (outside North America).

- [x] **Code BF - Risk guaranteed portfolios frozen**
>  A restriction has been placed on your file by officials of the Canada Student Financial Assistance Program which disqualifies you from receiving further funding through StudentAid BC.  For information regarding this restriction and possible resolution you will need to contact the Canada Student Financial Assistance Program at 1-888-815-4514 and ask to be transferred to the Case Review Unit. 

- [x] **Code C - Restriction on file**
>  A restriction has been placed on your file by officials of the Canada Student Financial Assistance Program which disqualifies you from receiving further funding through StudentAid BC.  For information regarding this restriction and possible resolution you will need to contact the Canada Student Financial Assistance Program at 1-888-815-4514 and ask to be transferred to the Case Review Unit. 

- [x] **Code TD - Account closed**
> A restriction has been placed on your file by officials of the Canada Student Financial Assistance Program which disqualifies you from receiving further funding through StudentAid BC.  For information regarding this restriction and possible resolution you will need to contact the Canada Student Financial Assistance Program at 1-888-815-4514 and ask to be transferred to the Case Review Unit. 

- [x] **Code E2 - Bankruptcy**
> According to the information on file, you have declared bankruptcy involving student loans.  As your bankruptcy involves student loans, you are not eligible for funding through StudentAid BC and your application is currently restricted.
You should note the following:

> Rehabilitation Through StudentAid BC
If you have declared bankruptcy in which Canada student loan or British Columbia student loan funds were involved, you cease to be eligible for both federal and provincial assistance.  You may be considered for further student financial assistance if federal and/or provincial authorities approve of the steps taken to meet rehabilitation criteria on your outstanding debt(s).

> For further information regarding rehabilitation with respect to Canada student loan funds, please contact: 
Canada Student Financial Assistance Program at 1-888-815-4514
For further information regarding rehabilitation with respect to BC student loan funds, please contact StudentAid BC at 1-800-561-1818 (within North America) 250-387-6100 (outside North America).

- [x] **Code O - Grant overawards
> Due to an outstanding grant overaward from a previous student assistance application, you are not eligible for StudentAid BC funding at this time. This grant overaward must be repaid in full before further provincial funding can be considered.  To arrange payment of your grant overaward, please contact Revenue Services of British Columbia at 1-866-361-5050 or (250) 387-6093. Once this overaward has been repaid in full, please forward proof of payment to this office.

- [x] **Code P - Offense related to Canada student loans**
> A restriction has been placed on your file by officials of the Canada Student Financial Assistance Program which disqualifies you from receiving further funding through StudentAid BC.  For information regarding this restriction and possible resolution you will need to contact the Canada Student Financial Assistance Program at 1-888-815-4514 and ask to be transferred to the Case Review Unit. 

- [x] **Code R - Risk-shared loan collection**
> A restriction has been placed on your file by officials of the Canada Student Financial Assistance Program which disqualifies you from receiving further funding through StudentAid BC.  For information regarding this restriction and possible resolution you will need to contact the Canada Student Financial Assistance Program at 1-888-815-4514 and ask to be transferred to the Case Review Unit. 

- [x] **Code RB - Bankruptcy**
> According to the information on file, you have declared bankruptcy involving student loans.  As your bankruptcy involves student loans, you are not eligible for funding through StudentAid BC and your application is currently restricted.
You should note the following:

> Rehabilitation Through StudentAid BC
If you have declared bankruptcy in which Canada student loan or British Columbia student loan funds were involved, you cease to be eligible for both federal and provincial assistance.  You may be considered for further student financial assistance if federal and/or provincial authorities approve of the steps taken to meet rehabilitation criteria on your outstanding debt(s).

> For further information regarding rehabilitation with respect to Canada student loan funds, please contact Canada Student Financial Assistance Program at 1-888-815-4514.  For further information regarding rehabilitation with respect to BC student loan funds, please contact StudentAid BC at 1-800-561-1818 (within North America) 250-387-6100 (outside North America).

- [x] **Code RJ - Ineligible for funding**
> A restriction has been placed on your file by officials of the Canada Student Financial Assistance Program which disqualifies you from receiving further funding through StudentAid BC.  For information regarding this restriction and possible resolution you will need to contact the Canada Student Financial Assistance Program at 1-888-815-4514 and ask to be transferred to the Case Review Unit. 

- [x] **Code RP - Offense related to Canada student loans**
>A restriction has been placed on your file by officials of the Canada Student Financial Assistance Program which disqualifies you from receiving further funding through StudentAid BC.  For information regarding this restriction and possible resolution you will need to contact the Canada Student Financial Assistance Program at 1-888-815-4514 and ask to be transferred to the Case Review Unit. 

- [x] **Code RP - Ineligible for funding**
> A restriction has been placed on your file by officials of the Canada Student Financial Assistance Program which disqualifies you from receiving further funding through StudentAid BC.  For information regarding this restriction and possible resolution you will need to contact the Canada Student Financial Assistance Program at 1-888-815-4514 and ask to be transferred to the Case Review Unit. 

- [x] **Code T - Claim for loss**
>A restriction has been placed on your file by officials of the Canada Student Financial Assistance Program which disqualifies you from receiving further funding through StudentAid BC.  For information regarding this restriction and possible resolution you will need to contact the Canada Student Financial Assistance Program at 1-888-815-4514 and ask to be transferred to the Case Review Unit. 

- [x] **Code W - Repayment assistance program**
> A restriction has been placed on your file by officials of the Canada Student Financial Assistance Program which disqualifies you from receiving further funding through StudentAid BC.  For information regarding this restriction and possible resolution you will need to contact the Canada Student Financial Assistance Program at 1-888-815-4514 and ask to be transferred to the Case Review Unit. 

- [x] **Code X Risk-shared or direct loan in arrears**
>A restriction has been placed on your file by officials of the Canada Student Financial Assistance Program which disqualifies you from receiving further funding through StudentAid BC.  For information regarding this restriction and possible resolution you will need to contact the Canada Student Financial Assistance Program at 1-888-815-4514 and ask to be transferred to the Case Review Unit. 

- [x] **Code Z3 - Repayment assistance program**
>A restriction has been placed on your file by officials of the Canada Student Financial Assistance Program which disqualifies you from receiving further funding through StudentAid BC.  For information regarding this restriction and possible resolution you will need to contact the Canada Student Financial Assistance Program at 1-888-815-4514 and ask to be transferred to the Case Review Unit. 

- [x] **Code ZR - Repayment assistance program**
> A restriction has been placed on your file by officials of the Canada Student Financial Assistance Program which disqualifies you from receiving further funding through StudentAid BC.  For information regarding this restriction and possible resolution you will need to contact the Canada Student Financial Assistance Program at 1-888-815-4514 and ask to be transferred to the Case Review Unit. 

- [x] **Code B7 - Reached lifetime maximum**
>As you have been advised per previous correspondence, you have exhausted the BC student loans (BCSL) maximum number weeks of funding. There is no appeal process for obtaining further BC funding through StudentAid BC, after reaching the maximum number of  weeks. You may still be eligible for funding or in-study payment-free status under the Canada Student Financial Assistance Program. For further information please contact StudentAid BC at 1-800-561-1818 (within North America) 250-387-6100 (outside North America).

- [x] **Code BO - Nearing lifetime maximum** 
>You are approaching your BC student loans (BCSL) maximum number of weeks of funding.  For further information please contact StudentAid BC at 1-800-561-1818 (within North America) 250-387-6100 (outside North America).

- [x] **Code RD - Ineligible for funding**
>A restriction has been placed on your file by officials of the Canada Student Financial Assistance Program which disqualifies you from receiving further funding through StudentAid BC.  For information regarding this restriction and possible resolution you will need to contact the Canada Student Financial Assistance Program at 1-888-815-4514 and ask to be transferred to the Case Review Unit. 

- [x] **Code XB - Altered date**
>A restriction has been placed on your file by officials of the Canada Student Financial Assistance Program which disqualifies you from receiving further funding through StudentAid BC.  For information regarding this restriction and possible resolution you will need to contact the Canada Student Financial Assistance Program at 1-888-815-4514 and ask to be transferred to the Case Review Unit. 

- [x] **Code XD - Altered date for direct lend**
> A restriction has been placed on your file by officials of the Canada Student Financial Assistance Program which disqualifies you from receiving further funding through StudentAid BC.  For information regarding this restriction and possible resolution you will need to contact the Canada Student Financial Assistance Program at 1-888-815-4514 and ask to be transferred to the Case Review Unit. 

- [x] **Code XJ - Canada Student Financial Assistance Program restriction**
> A restriction has been placed on your file by officials of the Canada Student Financial Assistance Program which disqualifies you from receiving further funding through StudentAid BC.  For information regarding this restriction and possible resolution you will need to contact the Canada Student Financial Assistance Program at 1-888-815-4514 and ask to be transferred to the Case Review Unit. 

- [x] **Code XP - Canada Student Financial Assistance Program restriction**
> A restriction has been placed on your file by officials of the Canada Student Financial Assistance Program which disqualifies you from receiving further funding through StudentAid BC.  For information regarding this restriction and possible resolution you will need to contact the Canada Student Financial Assistance Program at 1-888-815-4514 and ask to be transferred to the Case Review Unit. 

- [x] **Code SA - Canada Student Financial Assistance Program restriction**
> A restriction has been placed on your file by officials of the Canada Student Financial Assistance Program which disqualifies you from receiving further funding through StudentAid BC.  For information regarding this restriction and possible resolution you will need to contact the Canada Student Financial Assistance Program at 1-888-815-4514 and ask to be transferred to the Case Review Unit. 

- [x] **Code SO - Canada Student Financial Assistance Program restriction**
> A restriction has been placed on your file by officials of the Canada Student Financial Assistance Program which disqualifies you from receiving further funding through StudentAid BC.  For information regarding this restriction and possible resolution you will need to contact the Canada Student Financial Assistance Program at 1-888-815-4514 and ask to be transferred to the Case Review Unit. 

- [x] **Code IC - Canada Student Financial Assistance Program restriction**
> A restriction has been placed on your file by officials of the Canada Student Financial Assistance Program which disqualifies you from receiving further funding through StudentAid BC.  For information regarding this restriction and possible resolution you will need to contact the Canada Student Financial Assistance Program at 1-888-815-4514 and ask to be transferred to the Case Review Unit. 

- [x] **Code IS - Canada Student Financial Assistance Program restriction**
> A restriction has been placed on your file by officials of the Canada Student Financial Assistance Program which disqualifies you from receiving further funding through StudentAid BC.  For information regarding this restriction and possible resolution you will need to contact the Canada Student Financial Assistance Program at 1-888-815-4514 and ask to be transferred to the Case Review Unit. 

- [x] **Code F3 - Fraud**
> A restriction has been placed on your file by officials of the Canada Student Financial Assistance Program which disqualifies you from receiving further funding through StudentAid BC.  For information regarding this restriction and possible resolution you will need to contact the Canada Student Financial Assistance Program at 1-888-815-4514 and ask to be transferred to the Case Review Unit. 

- [x] **Code F4 - Fraud**
> A restriction has been placed on your file by officials of the Canada Student Financial Assistance Program which disqualifies you from receiving further funding through StudentAid BC.  For information regarding this restriction and possible resolution you will need to contact the Canada Student Financial Assistance Program at 1-888-815-4514 and ask to be transferred to the Case Review Unit. 

- [x] **Code F5 - Fraud**
> A restriction has been placed on your file by officials of the Canada Student Financial Assistance Program which disqualifies you from receiving further funding through StudentAid BC.  For information regarding this restriction and possible resolution you will need to contact the Canada Student Financial Assistance Program at 1-888-815-4514 and ask to be transferred to the Case Review Unit. 

- [x] **Code DR - Canada Student Financial Assistance Program restriction**
> A restriction has been placed on your file by officials of the Canada Student Financial Assistance Program which disqualifies you from receiving further funding through StudentAid BC.  For information regarding this restriction and possible resolution you will need to contact the Canada Student Financial Assistance Program at 1-888-815-4514 and ask to be transferred to the Case Review Unit. 

- [x] **Code B5 - Lifetime maximum for permeant disability**
- [x] In title revise "permeant" to "permanent"
>As you have been advised per previous correspondence, you have exhausted the BC student loans (BCSL) maximum number weeks of funding for student with a permanent disability. . For further information please contact StudentAid BC at 1-800-561-1818 (within North America) 250-387-6100 (outside North America).

- [x] **Code A - Canada Student Financial Assistance Program restriction**
> A restriction has been placed on your file by officials of the Canada Student Financial Assistance Program which disqualifies you from receiving further funding through StudentAid BC.  For information regarding this restriction and possible resolution you will need to contact the Canada Student Financial Assistance Program at 1-888-815-4514 and ask to be transferred to the Case Review Unit. 

- [x] **Code Z1 - Overaward**
>A restriction has been placed on your file by officials of the Canada Student Financial Assistance Program which disqualifies you from receiving further funding through StudentAid BC.  For information regarding this restriction and possible resolution you will need to contact the Canada Student Financial Assistance Program at 1-888-815-4514 and ask to be transferred to the Case Review Unit. 

- [x] **Code Z2 - Canada student financial aid restriction**
> A restriction has been placed on your file by officials of the Canada Student Financial Assistance Program which disqualifies you from receiving further funding through StudentAid BC.  For information regarding this restriction and possible resolution you will need to contact the Canada Student Financial Assistance Program at 1-888-815-4514 and ask to be transferred to the Case Review Unit.

**Comment by CarlyCotton** [comment]
@katrina-aot-git 
Updated to add new AC for an additional accordian/restriction:

- [ ] **Code PTSSR - Poor scholastic standing** 
> "Your account is restricted from future part-time funding due to poor scholastic standing. You are no longer eligible to receive student financial assistance. If you need more information or have concerns, please contact StudentAid BC."

FYI @andrewsignori-aot

**Comment by andrewsignori-aot** [comment]
The below AC had a type and was fixed during development.
_Code B5 - Lifetime maximum for permeant disability_, should be _Code B5 - Lifetime maximum for permanent disability_.

**Comment by michesmith** [comment]
@JerPearson is going to do his content review on this ticket and once confirmed we can move to close.

**Comment by JerPearson** [comment]
@katrina-aot-git I have made a few slight adjustments under the following AC's.  @michesmith once tweaks are made the ticket can be closed.

Code BCLM: There was a "," after StudentAidBC and I have changed it to a "."
Code PTSSR: I have added some additional content 
Code O: Just confirming that the title was not changed to include "no effect".

**Comment by JerPearson** [comment]
@lewischen-aot I have reviewed and made updates to the following AC's.  Ticket now ready for you.
Code BCLM: corrected a "," to "." after StudentAid BC
Code PTSSR: Added additional content
Code 0: Updated the title of the restriction.
