### ISSUE TITLE
Save fields from parttime assessment in Camunda to SIMS database (EDW)

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#3636]
The Enterprise Data Warehouse team requires additional fields from the parttime assessment in Camunda to be saved to the database.
Save the following fields from Camunda to the student_assessments table:

- calculatedDataDependants11YearsOrUnder
- calculatedDataDependants12YearsOverOnTaxes
- calculatedDataPartner1TotalIncome
- calculatedDataStudentTotalIncome
 
**Acceptance Criteria**
- [ ] Camunda variables saved into the workflow_data column of the table, student_assessment

**Comment by JasonCTang** [comment]
Removed the following fields after business discussed with Petr.
- awardEligibilityCSPT
- awardEligibilityCSGP
- awardEligibilityCSGD
- awardEligibilityBCAG
- awardEligibilitySBSD
- awardEligibilityCSLP

**Comment by CarlyCotton** [comment]
Spoke with Petr @ EDW and updated to workflow_data from assessment_data

**Comment by CarlyCotton** [comment]
Per lather - will combine with other EDW ticket re childcare changes and close this one.

**Comment by CarlyCotton** [comment]
Added to #3560 - closing this ticket.
