### ISSUE TITLE
UX/ UI- Add NEW Location to Institution on the Manage Locations Page 

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#364]
Persona: Admin user

The scope of this work does NOT include approval of a location just of the user adding the information.

- Use details from designation onboardings screens for each location + approved program details view
- Each location must have a primary contact defined
- Must be reviewed by SABC so "submitted screen"
- Don't worry about any downstream processes on SABC side for now until.

- Requires inactive status until approved.
-Show approved status on list page 

 
- Determine the Details on this page- this is similar to the Onboarding page.

**Comment by hellolynn-dsib** [comment]
**Discussed at UX connect:**

- Bulk upload for education program is in MVP (include in later versions)
- Adding a location/program is part of the designation eligibility
- Looking to reuse onboarding workflow/functionality as much as possible 
- However don't add functionality to add multiple locations (just 1 location)
- Also no functionality for copying
- Submission then SABC will confirm and turn location into designated location
- To revisit discussion tomorrow
