### ISSUE TITLE
SIMS Beta User Validation

### ISSUE THREAD

**Issue by ninosamson** [bcgov/SIMS#3668]
**User Story**
As a product team, we want to allow a small number of student users to apply for student funding in SIMS so we can confirm the functionality works end-to-end in production, before launching. 

**Acceptance Criteria:**
- [ ] Create a beta user authentication flow for student users. The given and last names of candidate beta users will be collected and added to a beta user table. 
- [ ] Upon login, validate against Given and Last Names from the BCSC credential. 
     - [ ] If the name matches the BCSC credential, the user can create a profile. 
     - [ ] BCeID users cannot log in. 
     - [ ] If there is a mismatch of name or BCeID user, show an error message on the login page: "Unable to login as the system is not yet available."
- [ ] Beta Validation is configurable on/off (toggle to enable validation of student user credential/name) 

**Technical**
- [x] Create a toggle to allow the behavior, default `true`, suggested name `ALLOW_BETA_USERS_ONLY`.
- [x] Create a new table to store beta users information.
  - Table name: `sims.beta_users_authorizations`.
  - Columns
    - id: 
    - given_names (varchar 100): User given names.
    - last_name (varchar 100): User last names.
    - enabled_from (date and time, default now): From when the user should be able to log in.
    - _No audit columns are needed._
   - Create a unique constraint for `given_names` and `last_name`.
- [x] If the toggle is enabled, don't allow BCeID users to reach the student API. Added the below code to the [AuthorizedPartiesGuard](https://github.com/bcgov/SIMS/blob/b49899306af5a325c794e2dbfff9aaacc8068d01/sources/packages/backend/apps/api/src/auth/guards/authorized-parties.guard.ts#L59) right before the method `return`.
```ts
if(TOGGLE_IS_ENABLED &&
  userToken.azp === AuthorizedParties.student
  && userToken.identityProvider === IdentityProviders.BCeIDBoth){
  throw new UnauthorizedException(
    new ApiProcessError(
      "The student authentication provider is not allowed at this moment.",
      INVALID_BETA_USER,
    ),
  );
}
```
- [x] If the toggle is enabled, in the [jwt.strategy](https://github.com/bcgov/SIMS/blob/4dde03d07b37a188ce39381f986f5a1452ae90e8/sources/packages/backend/apps/api/src/auth/jwt.strategy.ts#L54) execute a parallel verification with the `getUserLoginInfo` to check if the beta user is present on DB. If the user is not a registered beta user throw an exception as below.
```ts
throw new UnauthorizedException(
  new ApiProcessError(
    "The student is not registered as a beta user.",
    INVALID_BETA_USER,
  ),
);
```
- [x] In the web portal, change the student login flow in the [AuthService](https://github.com/bcgov/SIMS/blob/2cfff523c1ddccffec4664f4402bd9a676a9270c/sources/packages/web/src/services/AuthService.ts#L138) to handle the `INVALID_BETA_USER`.
  - The user should be logged off;
  - Redirected to the login page; and
  - The banner with the error message should be displayed. A [similar process happens for a Ministry user](https://github.com/bcgov/SIMS/blob/2cfff523c1ddccffec4664f4402bd9a676a9270c/sources/packages/web/src/services/AuthService.ts#L225-L230) who is not registered on Keycloak.
- [x] Error message for a non-beta user trying to log in or for a BCeID user should be similar to the banner below.
<img width="732" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1RFQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5e93debc0bdf9028b98b118eb7cb76be1f431855/image.png" alt="image.png" />
- Tests
  - Manual tests and demos are expected for toggle on and off.
  - Test should include BCeID and BCSC scenarios.
  - Nice to have an E2E test for BCSC validation in `auth.e2e-spec.ts`.

**Comment by ninosamson** [comment]
Sample message: 
<img width="748" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWVwQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--45913c2008184ab27a614c0ac12e36e34e398579/image.png" alt="image.png" />

**Comment by sh16011993** [comment]
@andrewsignori-aot How few Beta users are we talking about? Are we sure that 2 beta users won't have the same full name?
