### ISSUE TITLE
Content: CRA consent, declarations, and estimated student current year income 

### ISSUE THREAD

**Issue by astridSABC** [bcgov/SIMS#3676]
**Describe the task**
As a _student user or supporting user_, _I want_ to only see content related to me _so that_ when I'm reviewing the information I am not confused.
As a ministry user, I want the consents and declarations acknowledged by students and supporting users to be accurate.

## Acceptance Criteria

**Application: Financial Information tab**
- [x] Revise text for single student from ..."verifying my information and for my spouse's eligibility" to "verifying my eligibility"
- [x] Revise text for single student whose partner cannot get a BCSC from ..."verifying my information and for my spouse's eligibility" to "verifying my eligibility" (**Note: this might be the same form io?**)
- [x] Revise text for ministry name from "Ministry of Post Secondary and Future Skills" to "Ministry of Post-Secondary Education and Future Skills"

<img width="500" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNk91Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--41592212287cf3ae7e68c2e2b8a6f2fac2afd040/image.png" alt="image.png" />

**Student: Create profile page Declaration**
- [x] Revise text for ministry name from Ministry of "Advanced Education and Skills Training" to "Ministry of Post-Secondary Education and Future Skills"

<img width="500" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjZ6Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--84925b1517cbedbc1160a72add265a1b4bf36fbf/image.png" alt="image.png" />

**Student Declaration**
- [x]  Revise: "All information is subject to audit and verification" to "**All information is subject to verification and review.**"
<img width="455" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3ZyQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7faeef0a67c6a14d1aca310f70a1a83b5c7eb4de/image.png" alt="image.png" />

**Student: Collection of use**
- [x] Revise text for ministry name from "Ministry of Post Secondary and Future Skills" to "Ministry of Post-Secondary Education and Future Skills"
- [x] Change from centre justify to "full justified"

<img width="1224" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2ZKQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f108c9ef88ab8ee62fb5a12af6963b15c497ad98/image.png" alt="image.png" />

**Partner: Canada Revenue Agency consent**

- [x] Revise text for ministry name from "Ministry of Post Secondary and Future Skills" to "Ministry of Post-Secondary Education and Future Skills"
- [x] Revise test from "Student Aid BC" to "StudentAid BC"

<img width="500" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3ZGQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4a7ce4416fce3533f816baa286795da2ab433cf7/image.png" alt="image.png" />

**Partner: Collection of use:**
- [x] Revise text for ministry name from Ministry of "Advanced Education and Skills Training" to "Ministry of Post-Secondary Education and Future Skills"

<img width="1001" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGJGQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--355f9c2d61f24d346dbb07cc631ec32a97a078b6/image.png" alt="image.png" />

### Estimated student current year income update

As a ministry user I no longer want Covid-19 to be an option for why a student needs to use their estimated current year income.

### **Acceptance Criteria**
- [x] Remove Covid-19 from the options attached to the current year income question in the application
- [x] Remove Covid-19 from the options attached to the current year income question in the change request

<img width="1124" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGo3Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ead98636dceef896473aa0cb28983fa1d1bea0b2/image.png" alt="image.png" />

### **Additional context**

Screenshots below are from the legacy system of declarations

<img width="400" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmF1Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6315aa058dbd38615bf175fe000a8241a8364685/image.png" alt="image.png" />

<img width="300" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnl1Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--245ce1f9ee9392145110149b296b9fa6d4f5e6d0/image.png" alt="image.png" />

**Comment by katrina-aot-git** [comment]
@andrewsignori-aot clarified that points 1 & 2 were for all students.

@JerPearson I'm changing the ministry name across the app to the new name, including in the parents form.
