### ISSUE TITLE
Determine Scope of FormsFlow Ai Solution

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#368]
**Additional context**
- Are all forms Form IO?
- Are API managing the Data Structure?
- Storage Source of Truth? 
- Backend Integration API / Subscriber? 
- How we manage Camunda workflow connection with Forms? 

**Acceptance Criteria**
Determine and draw dataflow for each of the below
- [ ] Student profile
- [ ] Inst Account Details
- [ ] Inst location
- [ ] Save Application
- [ ] Submit Application

**Comment by abschwenker** [comment]
3 BPMN drawings have been created and are in devs channel. Drawings are guidlines for data flow and will be integrated on.
