### ISSUE TITLE
UX/UI for Ignore Restriction - Bypass Add/Remove

### ISSUE THREAD

**Issue by andrewsignori-aot** [bcgov/SIMS#3691]
**User Story**
As a Ministry user, I need the ability to Ignore restrictions through the interface, as well as see some limited historical details of any ignored restrictions 

**Acceptance Criteria**
- [x] Build modal for when Ministry selects "Bypass restriction" .
- [x] Build modal for when Ministry selects "View details" and the Bypass is active.
- [x] Build modal for when Ministry selects "Remove bypass".
- [x] Create role and add permissions for this feature to existing group `business-administrators`.
- [x] Applications are eligible for this ignore restriction bypass once they have been submitted and have an application number.

**Technical**
- [x] Similar modals process exists for the Ministry while adding a student restriction to the student, they can used as a reference.
- [x] "View detail" displays the "Bypass restriction" modal in the "view mode".
- [x] "Remove bypass rule?" should be enabled for active bypasses only and active student restrictions. If the student restrictions associated with the bypass gets resolved the bypass should no longer be removed.
  - [x] When enabled, display the "Bypass restriction" modal "removal mode".
    - [x] When the bypass is removed update the following DB fields.
      - `is_active` : false.
      - `bypass_removed_date`: current date.
      - `bypass_removed_by`: Ministry user.
      - `removal_note_id`: create a related note.
      - usual audit fields.
    - [x] Ensure API enforces the validation.
- [x] Header button "Bypass a restriction" displays the "Bypass restriction" modal in the "create mode".
  - [x] Dropdown should be populated as below.
    - [x] If no restrictions are available to be populated, disable the "Bypass restriction" button, disable the dropdown, and show a waning banner right above the dropdown with the message "No active restrictions available to be bypassed or all active restrictions already have an active bypass.".
    - [x] Display restriction code and creation date from the `sims.student_restrictions` table. The same restriction code may have multiple active entries in the student restrictions. Format sample `B3D added on Aug 28 2024`.
    - [x] Only populate restriction currently active in the student account.
    - [x] Use a simple dropdown to list the items. No search is needed on the client or server side.
    - [x] Populate part-time/full-time restrictions based on the application following the below.
      - For full-time application: only restriction where its action type contains `Stop full time BC funding` or `Stop full time disbursement`.
      - For part-time applications: only restriction where its action type contains `Stop part time disbursement`.
    - [x] Do not add to dropdown active restrictions that already have an active bypass. Filter to be done in the SQL query.
    - [x] Do not allow the creation for draft applications.
    - [x] Do not allow the creation of the bypass if there is already an active bypass for the student restriction ID.
    - [x] When the bypass is created update the following DB fields.
      - `is_active`: true. 
      -  `bypass_created_date`: current date.
      - `bypass_created_by`: Ministry user.
      - `creation_note_id`: create a related note.
      - `bypass_behavior`: selected behavior from the UI. Ensure DTO validation.
      - `student_restriction_id`: selected from the UI. Ensure the logic to populate the dropdown options will be checked in the API.
      - usual audit fields.
- [x] Suggested API endpoints
  - `GET` aest/application-restriction-bypass/:id
  - `GET` aest/application-restriction-bypass/application/:applicationId/options-list
  - `POST` aest/application-restriction-bypass
  - `PATCH` aest/application-restriction-bypass/:id
- [x] E2E tests
  - Get bypasses 
    - Should get a list of restrictions bypasses when there are restrictions ignored for a Student Application.
  - Get non-bypassed restrictions.
    - Should list all student active restrictions for a part-time application when there is one restriction bypassed and one not.
    - Should list all student active restrictions for a full-time application when there is one restriction bypassed and one not.
  - Remove bypass
    - Should be able to remove an active bypass when there is an active bypass.
    - Should throw an HTTP error while removing a bypass when the bypass is not active.
  - Create bypass
    - Should be able to create a bypass when there is not an active bypass for the same student. 
    - Should throw an HTTP error while creating a bypass when there is an active bypass for the same active student restriction ID.
    - Should throw an HTTP error while creating a bypass when student restriction is not active.
    - Should throw an HTTP error while creating a bypass when the student application is in draft.

**Supporting Mockups**

_These mockups follow a similar approach from the Ministry adding and removing restrictions. Please use that feature as a reference._ 

**Ministry 'Bypass Restriction' Modal**
![image](https://github.com/user-attachments/assets/00779910-3f28-48f7-852b-198ab0260d3d)

**Ministry 'View Details' Modal - Bypass was Removed**
![image](https://github.com/user-attachments/assets/8d0db57b-2d11-4737-88dd-7369b3ea861d)

**Ministry 'Remove Bypass' Modal**
![image](https://github.com/user-attachments/assets/75ba37d9-9e39-49d1-bae7-1963911f4e90)

**Comment by CarlyCotton** [comment]
@andrepestana-aot Can you link that to only business-administrator group for now?
