### ISSUE TITLE
Stop part time BC funding - Implement new restriction effect

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#3710]
**User Story**
As a ministry user, I need to implement a restriction to BC funding for part-time students. On #3512, we added a new restriction type "Stop part time BC funding" that occurs when the B6A restriction is in effect. We need to still disburse any federal funds and disburse $0 for any BC funding (BCAG-PT and SBSD).

**Acceptance Criteria**
- [ ] Update effect of "Stop part time BC funding" to reduce any provincial funding to $0 on PT ecert creation.

**Additional Context**

- This will impact SBSD and BCAG for part-time students.

**Technical**
- [ ] Implement the same process already in place for full-time in [apply-stop-bc-funding-restriction-full-time-step.ts](https://github.com/bcgov/SIMS/blob/main/sources/packages/backend/libs/integrations/src/services/disbursement-schedule/e-cert-processing-steps/apply-stop-bc-funding-restriction-full-time-step.ts#L35).
- [ ] Try to share the same step if possible.
- [ ] Add E2E test to check the part-time step.

**Comment by CarlyCotton** [comment]
@Joshua-Lakusta For your review

**Comment by Joshua-Lakusta** [comment]
Need to communicate with SCR team to validate the approach they want for this. Will connect next week 30th-4th of October.

**Comment by andrewsignori-aot** [comment]
@CarlyCotton @Joshua-Lakusta we were replicating the same behavior from full-time that would be set $0 to any BC-related award.
The additional comment states: "This will impact SBSD and BCAG for part-time students." but part-time also has BCSG as a grant. Is it not being considered?
