### ISSUE TITLE
CAS Integration 3B - Create New Site (Supplier found, Multiple Sites / No matching address)

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#3729]
## **User Story:** 
As an SABC Finance team member (Ministry user), I need all students in SIMS to have a supplier and site number attached. If we receive a successful response from a Get Supplier call, we need to assign that Supplier Number to the student and either use an existing Site or create a new one. We should use an existing site if the addressline/postal code match to avoid duplication.

## **Acceptance Criteria:**
- [x] If a Get Supplier Response is Successful and returns Active Supplier and NO active Sites, **Create New Site**
- [x] If a Get Supplier Response is Successful and returns Active Supplier and ONE OR MANY active Site, Compare the Response AddressLine1 and Postal Code to SIMS address (Compare against the Addressline and Postalcode as we would be submitting and NOT case sensitive. Truncated and translated / No space in postal code):
    - [x] Match FOUND: Save/Use that site. 
    - [x] NO Match: **Create New Site**

### **Create New Site**
- [x] Only use the **Create New Site** if Get Supplier Response is Successful and:
    - No Sites Returned (0 count/not found)
    - No Sites matching address are found
- [x] Fields to include (See Field Requirements File below): SupplierNumber, AddressLine1, City, Province, Country, PostalCode, EmailAddress (Optional/Conditional fields can be left out or left null)
    - [x] **AddressLine1:** Use first addressline from SIMS. Truncate if ours is longer than supported. Convert or omit special characters (like is done with other integrations).
    - [x] **City:** Use as-is
    - [x] **Province:** Use abbreviated versions AB,BC,MB,NB,NL,NS,NT,NU,ON,PE,QC,YT
    - [x] **Postal Code:** ALL CAPS, no space.
    - [x] **Email Address:** Use as-is
- [x] If successful response to Create New Site, then update SIMS CAS table with the prior **Get Supplier** returned `supplierNumber`, `SiteCode` and any other required info and set `isValid`=true
- [x] If error response, retry for now. Manual intervention may be required and will be dealt with on ticket #3258

**Business Context**
[Supplier Web Service RESTful Client Onboarding v02_01.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXpWQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--361bbb0afd9232c66288a57ce767a1a8d478f535/Supplier%20Web%20Service%20RESTful%20Client%20Onboarding%20v02_01.pdf)

[Individual Supplier Web Service Field Requirements (All Requests) JAN2023.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGJYQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd785e77d67f3e11bfd591da13f2baae828b7436/Individual%20Supplier%20Web%20Service%20Field%20Requirements%20%28All%20Requests%29%20JAN2023.xlsx) 

<img width="897" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUgyQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--31051caa2ae7e6d28fb178e5d4cbd39d81b7999b/image.png" alt="image.png" />

***Technical Context***

Sample CURL to create
```console
curl --location '${BASEURL}/cfs/supplier/' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer ${TOKEN}' \
--data-raw '{
    SupplierName: '\''Skywalker, Leia'\'',
    SubCategory: '\''Individual'\'',
    Sin: '\''422233197'\'',
    SupplierAddress: [
    {
        AddressLine1: '\''1012 Douglas St'\'',
        City: '\''Victoria'\'',
        Province: '\''BC'\'',
        Postalcode: '\''V8W 2C3'\'',
        Country: '\''Canada'\'',
        EmailAddress: '\''stephen.laws@gov.bc.ca'\'',
    }]
}'
```

Response:
```console
{"SUPPLIER_NUMBER":"2007638","SUPPLIER_SITE_CODE":"[001] ","CAS-Returned-Messages":"SUCCEEDED"}
```

### ** Create Site for Existing Supplier**
```
{
 "SupplierNumber":"2002492",
 "SupplierAddress":[
 {
 "AddressLine1":"3350 CLEARBROOK RD",
 "AddressLine2":"",
 "AddressLine3":"",
 "City":"ABBOTSFORD",
 "Province":"BC",
 "Country":"CA",
 "PostalCode":"V2T4T4",
 "EmailAddress":"abc@xyz.com",
 "EftAdvicePref":"E"
} 
]
}
```

**Success Response**
```
{
 "Supplier_Number":"123456789",
 "Supplier_Site_Code":"001",
 "CAS-Returned-Messages":"SUCCESS"
}
```

**Error Response**
```
{
 "Supplier_Number":"123456789",
 "Supplier_Site_Code":"001",
 "CAS-Returned-Messages":"Error Message"
}
```
<img width="901" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzMxQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--79afd1ddf036de4d5c1454b76a0d4698aec14237/image.png" alt="image.png" />

**Technical**
- [x] The address match logic was already added during the implementation of #3260. The address match is happening during [evaluateCASSupplier](https://github.com/bcgov/SIMS/blob/3aa80354234645a78640f45a5c394e72e8643ed5/sources/packages/backend/apps/queue-consumers/src/services/cas-supplier/cas-supplier.service.ts#L200-L220).
- [x] Create the new API call on CAS service.
- [x] E2E Tests
  - [x] Should create a new site and update the student CAS supplier when an active CAS supplier exists with no match addresses.

**Comment by andrewsignori-aot** [comment]
@CarlyCotton the bullet point that reads "If a Get Supplier Response is Successful and returns a Supplier that is NOT Active ignore for now see..." may be misleading since it is an expected behavior where we will be creating the supplier and it is actually referencing an error handler ticket. Can we remove this or can you please clarify if I am missing something?

**Comment by andrewsignori-aot** [comment]
@CarlyCotton about the below bullet point, is there a need to expect ONE site to be present?
```
Get Supplier Response is Successful and returns Active Supplier and ONE active Site which doesn't have an address match
```
What if we adpapt the second bullet in the same AC as below.
```
Get Supplier Response is Successful and returns Active Supplier and one or many active Sites, none of them have a matching address.
```
