### ISSUE TITLE
UX / UI Designation Renewal Page 

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#374]
### Acceptance Criteria

- [x] Follows the same flow as onboarding
- [x] Show Schedule A,B,D
- [x] Show designation agreement
- [x] Show checkmark/content let them know about eligibility/enrollment roles being different people.

**Comment by roopfw** [comment]
![image.png](https://images.zenhubusercontent.com/5e66ca845237f60c730a4aa3/623566c9-ca76-431d-bd99-58ba86d04339)

**Comment by roopfw** [comment]
https://app.mural.co/t/range1280/m/range1280/1619728949632/8c472ef9560cfd2ec084bf6ba0d6b0c1fe8da591
