### ISSUE TITLE
Investigate and modify process that reads CRA income verification response file if required

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#3746]
The CRA income verification request file will be merged with SFAS data and therefore, the response file will contain both SIMS and SFAS records.  Investigate if any modifications are necessary to handle the SFAS records that will not match with any SIMS CRA income verification requests. 

Initial investigation suggests that the code already handles non-matching records gracefully.

**Comment by sslaws** [comment]
Merged into #3745
