### ISSUE TITLE
Content - Student current year income dynamic year / Remove COVID option for Student Current Year Income

### ISSUE THREAD

**Issue by Joshua-Lakusta** [bcgov/SIMS#3748]
Dynamic year for current year income was changed from original developed year and needs to be changed back.

- [ ] Student current year income **application** question the dynamic year calculation should be first year of program year.
- [ ] Student current year income **change request** question should have a dynamic year calculation for first year of program year.

example:
2024-2025 would be 2024

<img width="1271" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2tWQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--706b8b645b257f9f7f71ab4e4b0f6febf782d023/image.png" alt="image.png" />

**Comment by ninosamson** [comment]
removing last two ACs as they have been implemented in previous ticket
