### ISSUE TITLE
Pre-Draft of the Assessment Workflow

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#375]
Review Assess Need Calculation (Mass Breakdown Calculator) and Translate to Camunda Workflow

**Additional Context**
Ignore any reference to "Appendix 3"
If a variable is not build yet (Eg. Tuition) assign it a basic name and add to ticket
This ticket is only focused on assessed need

**Acceptance Criteria**
- [x] Draft BPMN (Business Process Modeling Notation) and BMN (Business Modelling Notation) workflow calculations for "Determine Assessed Need"
- [x] Identify any major gaps for "Determine Assessed Need"
- [x] Knowlege Transfer
- [x] Identify variable information (when information changes ,eg.Program Year)
   ----Contact Andrew Schwenker for questions before documenting gaps

**Comment by abschwenker** [comment]
[https://app.zenhub.com/files/319429847/66468a5c-8fda-4c84-a94e-9692dccbd29c/download](https://app.zenhub.com/files/319429847/66468a5c-8fda-4c84-a94e-9692dccbd29c/download)

**Comment by guru-aot** [comment]
https://teams.microsoft.com/_#/files/DEVS?threadId=19%3Ac91c9c0acf5f44dcab6789f870ddf47e%40thread.tacv2&ctx=channel&context=BPMWorkflowFiles&rootfolder=%252Fteams%252F03177%252FShared%2520Documents%252FDEVS%252FBPMWorkflowFiles

BPM and DMN draft version has been updated
