### ISSUE TITLE
Ministry Reports - Supplier Maintenance Updates (CAS)

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#3768]
**User Story**
As a ministry user, I need to know if student profile details after they have had a verified CAS supplier. CAS must be kept up to date with site and supplier information so any changes in SIMS should be reviewed to identify if there is further action required. I need to know which fields were updated so I can take the correct action with CAS.

**Acceptance Criteria**
- [x] Update the current CAS record referenced in the student table when Ministry manually adds a supplier/site.
- [x] When we save a CAS record where isValid = true, save a snapshot of student profile data in the CAS table (Given Name, Last Name, SIN, Address line 1, City, Province, Postal Code, Country)

- [x] Identify any students with a valid CAS supplier and if they have an update to their student profile data (Given Name, Last Name, SIN, Address line 1, City, Province, Postal Code, Country) and compare to their CAS `isValid` snapshot
    - [x] Not case-sensitive
    - [x] Don't need to monitor changes in: Gender, Date of Birth, Email, Phone number
- [x] Create a report that is called 'Suppler Maintenance Updates'
    - [x] No date filter
    - [x] No PT/FT filter
 - [x] Include the following information in the report similar to the screenshot:
     - [x] Current Student Information (Given Name, Last Name, SIN, Addressline 1, City, Province, Postal Code, Country)
     - [x] Current Student Disability Status
     - [x] Current Student Profile Type (BCSC / BCeID)
     - [x] Supplier Information (Supplier, Site, Protected Supplier, Protected Site, Verification Date)
     - [x] Date profile updated
     - [x] Student Information Fields that were updated (List? Flag?)

<img width="1774" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1NnQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aacdcfe6601a2cb4e193b21b69eff3f434eddbf7/image.png" alt="image.png" />

**Additional Context**
- Some updates cannot be done directly through SIMS via the webservice to CAS. Name updates and SIN updates need to be handled manually through CAS.
- Fields on Report are subject to change due to dev preference

**Technical**
- [x] Create a new JSONB column on `sims.cas_suppliers` table to save the necessary student profile data. Suggested column name `student_profile_snapshot`.
- [x] Business if flexible about how to display the "Student Fields Updated". The goal is to provide what is the profile snapshot changed.
- [x] Ensure saving the snapshot is centralized.
- [x] E2E
- [x] PRs
  - DB migration;
  - Save snapshot;
  - Generate the report.

**Comment by ninosamson** [comment]
@CarlyCotton -feedback: 
- Currently we are checking address line 1 and postal code only. Not sure we need to check the other attributes.

**Comment by ninosamson** [comment]
@CarlyCotton - may be simpler to implement call to CAS when student profile info is updated. 

There may be some complexity on implementing this, especially around what to compare against to then find what changed.

**Comment by ninosamson** [comment]
If we do this in line with profile update, should we be Invalidating the CAS supplier record?

**Comment by ninosamson** [comment]
Proposed approach: 
- persist data after CAS call (at creation) - determine if we need to save all the attributes in first AC. probably best to do so. 
- report will provide records where data saved from CAS request is different from student data 
- May need future ticket to assist Ministry in tracking suppliers they have updated in CAS.

**Comment by CarlyCotton** [comment]
Based on discussion from @dheepak-aot added an AC to ensure the student record reflects the current CAS record when manually verified by ministry.
