### ISSUE TITLE
UX /UI Designation Summary Page

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#377]
### Acceptance Criteria

- [ ]  Show list of all past and current designation agreements
- [ ] Also show upcoming designation agreements that have been signed
- [ ] Edit active agreement (change control/new owner old)
- [ ] Designation active
- [ ] Designation expiry

**Comment by roopfw** [comment]
![image.png](https://images.zenhubusercontent.com/5e66ca845237f60c730a4aa3/ebb34949-8d42-480a-99bd-25c7a78db545)

**Comment by roopfw** [comment]
![image.png](https://images.zenhubusercontent.com/5e66ca845237f60c730a4aa3/ac992086-a02e-4598-8f96-56ee85f0e2a9)

**Comment by roopfw** [comment]
https://app.mural.co/t/range1280/m/range1280/1619728949632/8c472ef9560cfd2ec084bf6ba0d6b0c1fe8da591

**Comment by roopfw** [comment]
![image.png](https://images.zenhubusercontent.com/5e66ca845237f60c730a4aa3/cf3849bc-eba1-4c06-bdd7-7199d418185d)
