### ISSUE TITLE
SFAS-SIMS Bridge File - MSFAA Implementation

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#3774]
**User Story**
As a student, it is possible for me to have two MSFAA numbers (PT and FT). I don't want to have a new one issued by SIMS when I already have a valid one in SFAS/SAIL. 

**Acceptance Criteria**
- [x] On application submission during "Associate MSFAA" in the gateway, add another way to validate MSFAA (this can be done the same for PT/FT)
- [x] If a student does not have a SIGNED SIMS generated MSFAA number, search Bridge file Individual data records to find matching (SIN/DOB/LastName) student profile
    - [x] If no match found, Create New MSFAA as normal (or use the unsigned SIMS MSFAA number).
    - [x] If the most recent match found **DOES NOT** contain a MSFAA number for the intensity, Create New MSFAA as normal.
    - [x] If the most recent match found **DOES** contain a MSFAA number for the intensity, search the bridge file application data and use the most recent (or future) study end date ("300" for FT or "301" for PT) to ensure it is within 730 days of this date.  System cancel/void any other MSFAAs for that intensity. If No application or end date outside of 730 days: related to the student/MSFAA number, do not USE and create new as normal.
- [x]  In cases where we find a match in bridge file with a valid study end date: import that MSFAA number and use the most recent application end date from bridge file information as a "signed date"
 

**Business Context**
- Only VERIFIED MSFAA SAIL data will be reported. (This is a status in SAIL that is displayed based on the validity of the MSFAA number.)
- We are receiving the "Effective Date" for PT MSFAAs. As noted in the bridge file layout, this is really the only date data that we have easily accessible from SAIL for the MSFAA.  The signed date is contained within a text file in a BLOB field in another table, which is difficult to get at.  At this time, we are not going to try and get the signed date, but we will be using the effective date on this table, which is actually the date that the MSFAA request was created and should be close enough.
- We recognize that the gap between effective date and signed date could result in us declaring a MSFAA number "expired" slightly sooner than it would normally. This amounts to a small risk based on volume of students in PT with the circumstances that could end up in that situation. It results in the least number of students being impacted by having to be re-issued an MSFAA pre-maturely or worse, during an active application in the legacy systems.
- NULL date_requested/sent date would indicate that it is an imported MSFAA number

**Technical**
- [x] Create an additional process to be executed if SIMS does not have a **VALID AND SIGNED** MSFAA.
  - [x] Look for the individual in the `sims.sfas_individuals` by its `student_id`.
    - [x] For part-time MSFAA use the columns `part_time_msfaa_number`.
    - [x] For full-time MSFAA use the columns `msfaa_number`.
    - [x] The student should have at least one application for the intensity.
    - [x] If the student is present in the SFAS table and it has an application for the intensity a new MSFAA record should be created.
      - [x] Create a new MSFAA entry as below.
        - [x] `msfaa_number`: from SFAS individual table;
        - [x] `date_requested`: `null`;
        - [x] `date_signed`: date from `study_end_date` from the most recent application on SFAS table.
        - [x] `service_provider_received_date`: `null`;
        - [x] `reference_application`: populate with the SIMS application id.
- [x] Reuse(and adapt) the method [internalActivateMSFAANumber](https://github.com/bcgov/SIMS/blob/8864eaa8a5f62360f5e3c91c6de06f319e008250/sources/packages/backend/libs/services/src/msfaa-number/msfaa-number-shared.service.ts#L157) to ensure the new created MSFAA will be the only active. If not possible to reuse please have a team sync-up to explain the reason and talk about alternatives. This method can potentially be invoked using the  `options.existingMSFAA` to allow process already in place to consistently keep only one active MSFAA.
- [x] Create new E2E tests for the worker [associateMSFAA](https://github.com/bcgov/SIMS/blob/363df0d21ea086e3329e0605c9b1aa2147305376/sources/packages/backend/apps/workers/src/controllers/disbursement/disbursement.controller.ts#L95).
  - [x] Create a scenario for the SFAS import.
  - [x] Create a scenario for the creation of the SIMS MSFAA.
  - [x] Include multiple applications to also test the MSFAA reassociation.
  - [x] Consider checking the E2E tests from the [application.aest.controller.reissueMSFAA.e2e-spec.ts](https://github.com/bcgov/SIMS/blob/main/sources/packages/backend/apps/api/src/route-controllers/application/_tests_/application.aest.controller.reissueMSFAA.e2e-spec.ts) for some reference or E2E data setup.

**Comment by andrewsignori-aot** [comment]
@ninosamson bringing this ticket back as there is a pending minor refactor to be executed.
@guru-aot FTI
