### ISSUE TITLE
CAS TRAIN Environment

### ISSUE THREAD

**Issue by ninosamson** [bcgov/SIMS#3780]
**User Story**
As a SIMS project team, we should be integrated with appropriate environments for proper implementation and testing of external integrations. 

**Acceptance Criteria**
- [ ] Update integration for SIMS Staging to connect to CAS Train environment. 
- [ ] Confirm implemented API calls function properly.

**Comment by CarlyCotton** [comment]
Closing - combining with #3776 to support this update.
