### ISSUE TITLE
Gateway Assessment Data Update - PT & FT

### ISSUE THREAD

**Issue by Joshua-Lakusta** [bcgov/SIMS#3788]
As a ministry user I want to ensure the assessment data that is appearing is the data we expect to see. This is important because we want to ensure our NOA displays the correct information.

**Acceptance Criteria**
- [x] On the NOA make sure we are using the calculated camunda outputs in Assessment Data and not direct info from offerings or other. (Award amounts are ok to come from the DB)

**PT**
- [x] Replace the books and supplies from offeringProgramRelatedCosts to calculatedDataProgramRelatedCosts 
- [x] Update `tuitionCost: offeringActualTuitionCosts` to calculatedDataActualTuitionCosts

**FT**
- [x] Update `otherAllowableCost: calculatedDataChildCareCost` with `otherAllowableCost: calculatedDataTotalChildSpousalSupport + calculatedDataTotalSecondResidence`
- [x] Update `childcareCost: calculatedDataChildCareCost` with `childcareCost: calculatedDataTotalChildCareCost`
- [x] Update `totalProvincialContribution: calculatedDataTotalProvincialFSC + calculatedDataTotalSpouseContribution + calculatedDataTotalParentalContribution` with `totalProvincialContribution: calculatedDataTotalProvincialContribution`
- [x] Update `totalFederalContribution:  calculatedDataTotalFederalFSC + calculatedDataTotalSpouseContribution + calculatedDataTotalParentalContribution` with `totalFederalContribution:  calculatedDataTotalFederalContribution`

<img width="795" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0JBQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fe089e49f6e938a7914eb3b2933a24500efe2663/image.png" alt="image.png" />

<img width="1085" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejltQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7312e71b0806fb3dc4fc2f535b84388e4656d175/image.png" alt="image.png" />

**Additional Context**
The assessmentData table has not been reviewed in a long  time and we need to validate that the sources are all correct.

**Technical**
- [x] Adjust E2E tests.

**Comment by CarlyCotton** [comment]
Added an AC based on discussion with @andrewsignori-aot about Tuition in PT.

**Comment by andrewsignori-aot** [comment]
## Demo

Student: Basic BCeID andrew_signori_20
Part-time application: 2024000057

<img width="532" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNStQQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bc25bdb370a115ec87f84932d62777a3d0a41359/image.png" alt="image.png" />

### Offering

<img width="932" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkdQQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--be3efedef6d4b19eebde7f3962976716845e54e1/image.png" alt="image.png" />
