### ISSUE TITLE
BUG: Student and Institution: PIR: Program Name and Program Description from student request not displayed for institution or for student (View Application)

### ISSUE THREAD

**Issue by astridSABC** [bcgov/SIMS#3789]
**Describe the Bug**
The PIR (Programs) program name and program description created by the student are not displayed in the Student View Application or in the Institution PIR view for the request.  

The institution won't know what program that the student is requesting.

**Expected Behaviour**

**Student View Application**
Program name that you entered is displayed
Program description that you entered is displayed
Start date and end dates that you entered are displayed
TBD: Select your study dates section is not displayed as this is a program request

<img width="300" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1ZBQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--edab84b9052be9830a80981b6cb71eee34f34a40/image.png" alt="image.png" />

**Institution view**
Program name that the student entered is displayed
Program description that the student entered is displayed
Start date and end dates that the student entered are displayed

**Actual Behaviour**

**Student view**:
Program name that the student entered is not displayed. ‘Enter the name of your program’ is displayed
Program description field is blank
Start date and end dates are displayed
Select your study dates and field is not displayed/disabled

<img width="300" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTVBQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2cf80e61cbbfd0fcb478eb452274f0894f214663/image.png" alt="image.png" />

**Institution view**:
Program name that the student entered is not displayed
Program description that the student entered is not displayed

<img width="300" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWRBQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4468dab59bbf1a75a86e71caf84ee399a9183216/image.png" alt="image.png" />

**Steps To Reproduce**

**Precondition**:
BC Public institution (designated)
Student account with verified SIN

1. Login to student portal
2. Click “Start Application” button
3. Select program year "(2024 – 2025 – My first…)" in the program year dropdown list
4. Click “Start Application” button
5. Select an institution from the select your institution dropdown list
6. Select "Part time" for capacity
7. Select “Your program is not listed” checkbox
8. Enter any valid name in the program name field (required field): e.g. B Sc Ocean Science
9. Enter any valid information in the program description field (required field): e.g. test this
10. Enter any valid date in the “Start date” calendar widget (e.g. Sept. 4, 2024)
11. Enter any valid date in the “End date” calendar widget (e.g. Dec. 20, 2024)
12. Take a screenshot of the program that you entered or note the contents of the fields above (steps 8-12)
13. Continue with generic information for the rest of the application
14. Confirm submission
15. Submit application
16. Application needs to be “**In Progress**” status 
17. Click “**Financial Aid Application**” link
18. Click “View application” from Application actions dropdown list
19. Click “Program” tab
20. Scroll to the Program selection section
21. Note the program information that was entered for the program info request previously above
<br></br>
22. **Login to the institution portal**
23. Select location to view the Program Info Request
24. Select “Program Info Requests”
25. Click “View” button beside the student that has created a Program info request for a program
26. Note the screen

**Technical**
- [ ] Ensure PIRs are tested using two scenarios.
  - [ ] PIR when the program is not provided.
  - [ ] PIR when the offering is not provided.
- [ ] E2E to test the PIR to get information for the two scanrios above.

**Comment by CarlyCotton** [comment]
<img width="1175" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDFmQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1a2873899c666e64d707a7197f7c2485df2f9c92/image.png" alt="image.png" />

**Comment by CarlyCotton** [comment]
@sh16011993 Just reproduced in test

Student App: 
<img width="947" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXUxQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3f4ab22d69b948872791005a2046fb83fe51dcab/image.png" alt="image.png" />


PIR View:
<img width="744" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXExQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--114d5b22bfd9af31995cb4913c5e226b3f54e150/image.png" alt="image.png" />
