### ISSUE TITLE
Student: Sole custody dependant question change

### ISSUE THREAD

**Issue by JerPearson** [bcgov/SIMS#3827]
On the family information tab move location of sole custody question to allow the question to be dependent specific.

**Acceptance Criteria**

- [x] Make these changes for the 25-26 program year application form
- [x]  Move "Are any of the dependants listed above supported by you financially but not under your sole custody?" question to the Add Dependants box.
- [x]  Revise question to: "Is the dependant listed above supported by you financially but not under your sole custody?" 
- [x]  This question should be included for each individual dependant added.  
- [x]  If possible please make it so that each individual dependant that has this exception selected has their own exception line on the ministry UI. If not possible due to effort or function one is fine for PT MVP.
- [x]  Apply changes to FT/PT

<img width="903" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFJzQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--83b4fd842237eda50a6a1cd2feb9b11f98a7cf20/image.png" alt="image.png" />

**Technical**
- [x] The new exception will follow the solution in place using the same behavior from the exception created for "Declared on taxes due to a disability" which means that we will be complying with the AC that states "If not possible due to effort or function one is fine for PT MVP.".

**Comment by andrewsignori-aot** [comment]
@Joshua-Lakusta @JerPearson regarding the below AC
```
 If possible please make it so that each individual dependant that has this exception selected has their own exception line on the ministry UI.
```
We saved a single expectation entry to the database, even if multiple are present.
My recommendation would be to execute the MVP version for this ticket unless we have a better idea about the Ministry's expected changes.

**Comment by ninosamson** [comment]
removed estimate and linked to #4132, which should resolve this ticket.
