### ISSUE TITLE
Change all OpenShift template api version

### ISSUE THREAD

**Issue by fwpushan** [bcgov/SIMS#383]
**Additional Context**
Context: Processing template showing waring message to fix that we need to change template api version to `template.openshift.io/v1`

**Warning on issuing old templates (viewable on github actions during deployment)**

++ Deploying Web with tag: main-992
+
W0210 18:31:43.356311    1691 shim_kubectl.go:55] Using non-groupfied API resources is deprecated and will be removed in a future release, update apiVersion to "template.openshift.io/v1" for your resource

**Acceptance Criteria**
- [x] Change OpenShift template api versions
- no warnings should appear during a build/deployment

**Comment by guru-aot** [comment]
![image](https://user-images.githubusercontent.com/62901416/160183048-970d4a38-e054-4802-9501-ce8354e8411c.png)
