### ISSUE TITLE
Hotfix: Name change for CRA Response file

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#3841]
The expected file name for the CRA Response file is changing to the following format:

Acceptance Criteria
- [x] Update CRA Response Integration job to search for new file name 
    - [x] [CRA Environment Code]BCSA#####.TXT
- [x] No change on request - confirmed with IMB CRA income verification request file name can remain the same. 

**Context:** 
DEV: ABCSA#####.TXT
TEST: ABCSA#####.TXT
PROD: PBCSA#####.TXT

**Current File Names for CRA Income:** 
- CCRA_REQUEST_${this.craConfig.environmentCode}${sequenceFile}.DAT
- /CCRA_RESPONSE_[\w]*\.txt/i

**For DEV environment:** 
- Harry suggests that we use the A prefix from TEST, but if we ever send files from both environments, will need a way to coordinate the sequence number between the two.

**Comment by CarlyCotton** [comment]
Successfully read in CRA response file with the new naming system.

**Comment by dheepak-aot** [comment]
@CarlyCotton @ninosamson Added an AC which mentions that the request file must have the correct CRA PROGRAM AREA CODE.
