### ISSUE TITLE
UX/ UI - Education Programs Page (View)

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#386]
A place to view parent program and offerings (reusing the designation view - may be a bit additional consideration for displaying info)

AC:
- Displays tombstone info
- Has an edit button to edit tombstone
- Displays offerings 
- Has an edit button to edit offerings
- Modals to display warning messages for editing that might trigger process and affect student applications
- Status to show program states (and pt/ft)

Additional context:
- THIS PAGE DOES NOT CONTAIN WHAT HAPPENS AFTER YOU EDIT (i.e. the required processes)

**Comment by hellolynn-dsib** [comment]
I believe this ticket is no longer relevant as the approach for Education Programs has changed and kicked off new tickets located in the backlog (add offerings, edit offerings). So moving this back in Sprint Backlog for now (but think this could be removed)
