### ISSUE TITLE
Unzip Federal Restrictions File 

### ISSUE THREAD

**Issue by ninosamson** [bcgov/SIMS#3869]
**User Story**
The federal restrictions file is passed to SIMS as a zip file. We need to unzip the file and then import the .txt file. Right now we are not expecting to unzip the file.

**Acceptance Criteria**
- [x] unzip the federal restrictions file when it comes to SIMS from the SFTP so we can process the .TXT file 
- [x] archive the zip file during this process

**Technical**
- [x] Only one file is expected per zip file.
- [ ] Use the out-of-box node lib.
- [x] Try to create the ability to decompress any zip file using the common method that reads the files.
- [ ] Nice to have, create an E2E to have a mocked zip file.

**Comment by CarlyCotton** [comment]
Just a note for me to grab a sample and update ACs to be more fulsome

**Comment by dheepak-aot** [comment]
While running the federal restrictions file with bulk volume of data (139MB File), we noticed that the required resource limit is going beyond that maximum limit for both CPU and Memory.

<img width="796" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2hDQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--244e66681706f8abbef3806607305c38190a7a67/image.png" alt="image.png" />

<img width="813" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2xDQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e6330bd1dc05dcb65518744ed056b33afaf558d8/image.png" alt="image.png" />

Hence to meet the demand for job(s) requiring more resources(Currently federal restrictions is the only one such job), CPU and Memory limits and requested have been increased a little.

<img width="740" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3BDQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b09146a233f8f68a3386ca092e675ead8ff8e4f8/image.png" alt="image.png" />
