### ISSUE TITLE
Parallel Processing Limits

### ISSUE THREAD

**Issue by ninosamson** [bcgov/SIMS#3887]
Code is starting 32 parallel processes where each one will create its own transaction. Once the typeorm pool reaches its maximum (configured to 10 right now) it will be waiting forever.

The next PROD release changed the default configuration and should already resolve this issue for the e-Cert.

- [ ] Ensure the parallel process no longer uses the `os.cpus()` as a limit when no other limit was provided.

**Comment by Joshua-Lakusta** [comment]
@astridSABC Testing note. This has the low potential to impact bulk offering upload. Ensure we test bulk upload to ensure no impact.

**Comment by andrewsignori-aot** [comment]
## Demo

### Federal Restrictions

Logs now show the import progress, as shown below. The restrictions are inserted in bulks of 500 records in parallel, usually leading to 1000 records inserted per progress line below.

![image](https://github.com/user-attachments/assets/c5d23cf4-b2c0-4d6c-927d-b9d37169e217)

![image](https://github.com/user-attachments/assets/39a04ca1-1c0a-49e5-be9c-120230eb81cd)

![image](https://github.com/user-attachments/assets/ad3acb65-c19e-4c4b-abce-a332687403a1)
