### ISSUE TITLE
Mask Institution User Income View 

### ISSUE THREAD

**Issue by ninosamson** [bcgov/SIMS#3896]
**User Story**
As a ministry, we need to comply with our CRA MOU.

**Acceptance Criteria**
Options: 
- [ ] Mask the Total income used for assessment purposes on the assessment with X's for BC Public Institutions (see screen shots below)

<img width="945" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd20xQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8bcdffe8df802990531e38665ba49c8e663ca08d/image.png" alt="image.png" />

<img width="1176" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHk1Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c32254617fc4721a7281b03872a7b761fafed408/image.png" alt="image.png" />

<img width="1152" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDI1Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--52f16cc6df7c9a56da43b4c8a0ebf5645080c052/image.png" alt="image.png" />

**Comment by Joshua-Lakusta** [comment]
Can we make this configurable and have a toggle so when it inevitably get reversed or changed in the future its easy to turn back on?

**Comment by ninosamson** [comment]
Now you're talking @Joshua-Lakusta

**Comment by andrewsignori-aot** [comment]
@CarlyCotton @ninosamson I am not planning to demo this one since it is part of the 1.15 release to be validated by QA.

**Comment by ninosamson** [comment]
Understood @andrewsignori-aot
