### ISSUE TITLE
Institution Admin User (Zoe) Views Institution Account Location Summary Page

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#391]
**As a** *(Institution Admin User)* **I want** *(View the Institution Account Location Summary Page* **So That** *(Choose to Add or Edit  Institution Location Details)*

**Additional Context**
- An Institution Location is a Campus - EG (Camosun College has 2 Campuses ( Landsdown and Interurban) 
- We will never Delete a location but we will enable archiving a location However Archiving a Location is out of scope for MVP.

**Acceptance Criteria**
- [x] Given (Institution Admin User), When they view the Institution Locations Summary Page) Then (they can see a list of All of the Institution's locations). Location Summary Information Includes Location Mail Address)
- [x] Given (Institution Admin User), When they view the Institution Locations Summary Page) Then they can click an edit button
- [x] Given (Institution Admin User), When they view the Institution Locations Summary Page) Then they can view 'Add Location' Button)

**Comment by ann-aot** [comment]
PR - https://github.com/bcgov/SIMS/pull/438
