### ISSUE TITLE
ARDA- Indigenous Question

### ISSUE THREAD

**Issue by michesmith** [bcgov/SIMS#3919]
<img width="1302" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHFxQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d946bee24ce637da10b2a318956ae881d2f2c718/image.png" alt="image.png" />

**Comment by CarlyCotton** [comment]
Closing - already being addressed on #3879
