### ISSUE TITLE
Institution Admin User (Zoe) wants to View & Edit an Institution's Account Location Details

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#392]
Clean Up --Ensure Edit after add below

**As a** *(Institution Admin User)* **I want** *(Edit An Institution's Location Details )* **So That** *(I can ensure SABC has the most current information about my location)*

**Additional Context**
- This does not need to be submited to formio. Information will be saved to SIMSDB and not trigger a re-approval

**Acceptance Criteria**
- [x] Given (an Institution Admin User), When (they select the 'Edit Button on the Locations summary page"), Then (they are DIRECTED to the 'Edit Location Details Page')

VIEW
- [x] Given (an Institution Admin User), When, (they View the "Edit Locations Page")Then, (they can SEE the Locations Address (Location Name, Address, City, Postal / Zip Code, Province'/ State and Country)
- [x] Given (an Institution Admin User), When, (they View the "Edit Locations Page")Then, (They can SEE the Saved Changes.) 

EDIT
- [x] Given (an Institution Admin User), When, (want to Edit their location details ")Then, (they can EDIT all fields) 

https://www.figma.com/file/VykmBDwobGoGvK9M5wgOvN/StudentAid-BC-App-Design-System-(WIP!!)---FreshWorks-Studios?node-id=21%3A451

**Comment by abschwenker** [comment]
![image.png](https://images.zenhubusercontent.com/5fce9c77aab275719112dc74/62cc5a9f-527e-4c20-8689-8c4b1f3dbf5e)
