### ISSUE TITLE
DUE DEC 1: PT Monthly Loan Balance - Update Balance

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#3922]
**User Story**
As a system, SIMS needs to read in the correct value into our database to correctly include the value from the monthly file.

**Acceptance Criteria**
- [ ] The PTMB-DTL-BALANCE value includes decimal places. 
- [ ] Value of 0090254 is equal to $902.54.

<img width="325" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3UwQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--21ab36434afae03af1dddb587955173b221a7e06/image.png" alt="image.png" />

---
**Additional Context**
student_loan_balances table:
<img width="319" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3kwQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--85c7c0c98bba50ea1d92d1b0b753ad3ac04f938e/image.png" alt="image.png" />
MBAL Layout:
<img width="517" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3EwQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6dc1287ed154a1c1b1e0e4c2b34e18ff2b779790/image.png" alt="image.png" />

**Comment by andrewsignori-aot** [comment]
@CarlyCotton @ninosamson I am not planning to demo this one since it is part of the 1.15 release to be validated by QA.

**Comment by ninosamson** [comment]
Understood @andrewsignori-aot  - business team will be validating.
