### ISSUE TITLE
Ecert Creation - "Prefer not to answer" Gender

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#3924]
**User Story**
SIMS needs to create files that conform to a certain layout. If a student answers "prefer not to answer" as their gender in SIMS, we need to correctly apply a ' ' character to any gender markers to our partners.

**Acceptance Criteria**
- [ ] Update PT Ecert creation to map the following so the spacing stays consistent with the layout:
    - Prefer not to answer => ' ' (space)
- [ ] Ensure the FT Ecert creation functions the same
- [ ] Please check SIN, CRA, IER12, MSFAA, or anywhere else that we generate a file with gender.

**Additional Context**
- This was updated under #2831
- Test Student "Jeanine Kinch" has Non-Binary as their gender 
- Test Student "Corey Reeves" has "Prefer not to answer" as their gender
<img width="799" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2kwQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--856a817d4cfd486ead0bda57f5cd147a14298087/image.png" alt="image.png" />

**Comment by andrewsignori-aot** [comment]
@CarlyCotton @ninosamson I am not planning to demo this one since it is part of the 1.15 release to be validated by QA.

**Comment by ninosamson** [comment]
Understood @andrewsignori-aot  - business team will be validating.
