### ISSUE TITLE
Show student number in instiution search and make mandatory app field

### ISSUE THREAD

**Issue by Joshua-Lakusta** [bcgov/SIMS#3937]
As a public institution user i want to be able to see the student number when i search for students. i also want the student number to be a mandatory field in the application

**Acceptance Criteria**
- [ ] Make student number mandatory in application
- [ ] create new column on studnet search for institutions
- [ ] have that column labled Student ID
- [ ] Have the field pull the student ID number from the application

**Additional Context**
Easy win for institutions
I feel that its not needed and we should allow for them to adapt to new process. Entered into back log

**Comment by CarlyCotton** [comment]
Student number is based on student inputting into application. They could have MULTIPLE or NONE attached to their applications. Student name, app number, or SIN will be better searches for the institution.
