### ISSUE TITLE
UX /  UI Designation Agreement Research

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#401]
The UI Team understands the Designation Flow.
- Tweek Designation Onboarding Workflow
- Confirm Designation Approval Workflow

**Comment by courtneygringras** [comment]
Research of required info to collect at each page found here: https://app.mural.co/t/range1280/m/range1280/1619728949632/8c472ef9560cfd2ec084bf6ba0d6b0c1fe8da591 

Reviewed with UX/UI team on 04-30-2021
