### ISSUE TITLE
UX / UI Institution Location- Student Application DETAILS Page

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#402]
As an Institution user I want to see details of a student application so that I can confirm enrollment and perform other administrative tasks (withdrawals and scholastic standing)

### Additional details:
Students who are no longer active are not shown in the system
Name change: Applications vs Students?

### Acceptance Criteria

- [x] Display all relevant details so that Institution can perform admin tasks such as Confirmation of enrollment, report withdrawals and scholastic standing.
- [x] Buttons that allow users to perform admin task
- [x] Confirm and display fields as defined in Confluence user stories

**Comment by roopfw** [comment]
For now, this mockup shows the following information to Institutions:

- NAME
- APP NUMBER
- STATUS
- STUDY PERIOD
- PROGRAM NAME
- OFFERING


Will show more if needed but as a base level this should let them look up the student in their systems to manually do a COE for example

[https://www.figma.com/file/VykmBDwobGoGvK9M5wgOvN/StudentAid-BC-App-Design-System-WIP-FreshWorks-Studios?node-id=1771%3A0](![image.png](https://images.zenhubusercontent.com/5e66ca845237f60c730a4aa3/066e7ca1-ec45-431b-8e15-1463b181fafe))
