### ISSUE TITLE
LGCY restriction visability

### ISSUE THREAD

**Issue by Joshua-Lakusta** [bcgov/SIMS#4036]
As a ministry user I don't want the LGCY restriction to display to students in the activity page for the time being in order to reduce call volumes being produced.

**Acceptance Criteria**
- [x] Set the LGCY restriction communication effect to "no effect" so that they don't see a banner or anything on the activity page.

**Additional Context**
This is a short term resolution in order to alleviate current call volumes for the LGCY restriction

**Comment by CarlyCotton** [comment]
Updated the notification_type for LGCY restriction to "No effect" so no banner will be there.
Closing as complete @Joshua-Lakusta @ninosamson
