### ISSUE TITLE
Add action to handle imported cancelled SFAS applications

### ISSUE THREAD

**Issue by Joshua-Lakusta** [bcgov/SIMS#4041]
As a student I need my cancelled applications in SFAS (application_cancel_date) to be treated as if they do not exist. This means all areas where we import SFAS application data and utilize it should ignore cancelled application data when calculating or validating.

**Acceptance Criteria**
- [x] Should not trigger date overlap validation if application has been cancelled (cancelled apps should be ignored during this process)
- [x] Program year limit amounts for applications that have been cancelled should be ignored
- [x] Total Legacy BCSL amount should be ignored for cancelled apps (calculation for BC lifetime max full time)

**Additional Context**
Currently blocking students from being able to submit as we are not digesting the information for application_Cancel_date from SFAS

Not addressing MSFAA as SFAS apps do not effect PT applications and we need to do further investigation on when MSFAA is validated. Another ticket will be created if deemed neccessary.

**Comment by dheepak-aot** [comment]
There was a technical  bug in deriving total legacy BCSL value for FT. (Student id was checked against sfas_individual id instead of individual linked student id)

**Comment by CarlyCotton** [comment]
Checked cancelled sfas app with an overlap in SIMS. SIMS allowed app and did NOT use any award amounts in PY totals.
