### ISSUE TITLE
UIUX - Student views document / upload documents

### ISSUE THREAD

**Issue by abschwenker** [bcgov/SIMS#408]
A student may need to provide supporting information or submit other documents not part of their application

**Additional Context**
- A student may need to re-upload a document to an existing application (their initial upload did not pass a ministries approval (proof/exceptions))
- A student may need to submit a document that's not part of their application (e.g. Other applications, verifications, appeals, supporting information)
- Consider a design pattern that can be re-used for multiple scenarios outlined above
- Connect with Alana (FO - triage / file size concern) - decide how much to action

**Acceptance Criteria**
- [x] Review with Devs for direction as there is some background to know
- [x] Mockup the file uploader itself 
- [x] Mock up navigation to file upload/download area (view)
- [x] Mock up content needed
- [x] Mock up ministry view the student files

**Comment by TeresaBia** [comment]
This part is done but further tweaks coming.
