### ISSUE TITLE
Bug - COE 21 day validation not applying to initial COE when 2 disbursments.

### ISSUE THREAD

**Issue by Joshua-Lakusta** [bcgov/SIMS#4080]
**Describe the Bug**
When there are two disbursements that will require COE the 21 day validation is only applying to the last one. When there is only one disbursement for coe there is no issue.

**Expected Behaviour**
Expect all COE attached to an application to be validated to see if they are within 21 days.

**Actual Behaviour**
When two COE's exist only the second one has the 21 day validation applied and the first coe can be completed early.
<img width="1561" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDhlQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--392aec5d849590d84e8b36280924db8837741e8b/image.png" alt="image.png" />

** Steps To Reproduce**
Steps to reproduce the behaviour:
Create a program
Create an offering over 18 weeks long
Start date of study at least 22 days in the future
Generic information to complete

Student application
use the offering and create a happy path student application (other questions have no impact)
Accept assessment

Insitution confirm COE
First COE will be approvable over 21 days before study start date

**Comment by CarlyCotton** [comment]
Likely related to #4082

**Comment by CarlyCotton** [comment]
Closing
