### ISSUE TITLE
2 Disbursement PT Schedules - Correct First Disbursement Date

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#4082]
**User Story**
When a student has a PT application where there is an offering study start date AFTER today with 2 potential disbursements AND date(disbursmenentScheduleDate2Potential) > today()... the earliest date of disbursement should be the offering study start date.

**Current Behaviour**
Disbursement schedule is resetting the disbursement 1 schedule date to `today()` .. instead of using the previously assigned `offeringstudystartdate`

**Expected Behaviour**
Disbursement 1 date should be today's date ONLY if the study start date has passed.

<img width="620" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHdoQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--689e740725659fccd8e044c83e1eb81b2951f689/image.png" alt="image.png" />
<img width="682" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDBoQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--acbd71f423bac3d0c15dae1c2c30e1c2f74fde0d/image.png" alt="image.png" />

**Comment by CarlyCotton** [comment]
@andrewsignori-aot Testing in staging and it was successful.

FYI @Joshua-Lakusta

**Comment by ninosamson** [comment]
Closing as complete, following staging QA.
