### ISSUE TITLE
SIMS to SFAS Bridge - Legacy Restrictions

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#4101]
**User Story**
In the file layout for our SIMS to SFAS Bridge we have allocated 4 characters for the restriction code. With the change in functionality to legacy restrictions, we have created LGCY_ restriction codes that are longer than 4 characters. As an internal integration partner, I need the layout on the flat file to be consistent and any newly created LGCY_AA restriction is being sent and throwing off the layout for restriction records.

**Acceptance Criteria**
- [x] Do not send any `isLegacy = true` restrictions in the SIMS to SFAS Bridge file
- [x] Update restricion field in bridge file with restriction code to allow 10 characters
- [x] Ensure the bridge file is created with the record fields limited to the length as stated in the File Layout
- [x] Add filler as needed to bring to 10 characters

**Additional Context**
Carly will update bridge layout doc and send to legacy team
Example of >4 characters
<img width="588" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1F1Q0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0daf33679e64319f409895fc92dfd073cb8fb8e6/image.png" alt="image.png" />
<img width="740" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1V1Q0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--740b6c7536752f12e5c44a8485eccb993e8cf7a9/image.png" alt="image.png" />

**Technical**
- [ ] Add the filter to the [existing query](https://github.com/bcgov/SIMS/blob/6e418df8ba606fdbb935e51224b102c91b1dc973/sources/packages/backend/libs/integrations/src/services/sfas/sims-to-sfas.service.ts#L236).
- [ ] Create or adapt an existing E2E to test the `isLegacy` filter.

**Comment by Joshua-Lakusta** [comment]
2.3 release assuming 2.2 has been pushed to stage
