### ISSUE TITLE
Persist uploaded documents and exception triggering for dependants with disability 

### ISSUE THREAD

**Issue by Joshua-Lakusta** [bcgov/SIMS#4128]
As a student and ministry user we need to be able to see the documents uploaded for dependants with disabilities declared on taxes when there is also a dependant that is not declared on taxes. We also require the exception to be triggered in this situation. 

**Acceptance Criteria**

- [ ] Ensure that when "Clear value when hidden" is not checked in form IO for this specific question so that the file information is not removed for all program years
- [ ] It is ok that this information will reappear when reactivated with future edits
- [ ] Ensure that when this change is made that the dependant declared on taxes exception triggers in scenarios where there is a disability dependant 

**Additional Context**
This was captured during another ticket by Lewis. Goal of this ticket is to ensure behaviour is the same for all program years.

<img width="690" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDRyQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f9fe73a9b9034cf058f289fb7718a6954502f5b5/image.png" alt="image.png" />

**Comment by ninosamson** [comment]
removed estimate and linked to #4132, which should resolve this ticket.
