### ISSUE TITLE
UX/ UI- Education Program Details ADD  Offerings Page

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#418]
It has been identified during UX connect a different approach that marries UX/UI, DEV and potentially business needs.

This ticket is a placeholder for what's to come out once we present the different approaches to business.

Acceptance Criteria:
* Ability to enter all fields (Study period offerings) 
* Program delivery method
* Cost
* Time (Min 6 weeks+)
* Intensity
* Tuition remittance (added)

* Content to be confirmed by @courtneygringras

**Comment by courtneygringras** [comment]
@hellolynn-dsib Content feedback for programs and offerings section:

**NEW PROGRAM SECTION**

- Add new question:
How will the program be delivered? (Select all that apply)
[ ] On site
[ ] Online
- Add _conditional question_: If they do not select ON SITE, show the following question:
 "Will the students earn the same number of credits in the same time period as students in other StudentAid BC eligible programs delivered on site? Yes/No" 
IF NO -> Ask "Will they earn academic credits that are recognized at another designated institution listed in the BC Transfer Guide or other acceptable articulation agreements from other jurisdictions? Yes/No"

- Years required to complete program – use basic dropdown options reflected in current designation application and confirm with Niamh/Haley
- Remove the 'Are all the courses distance/correspondence?' question as this will be addressed in the OFFERINGS section as it relates to the specific offerings
- PLA question - TBD - need to discuss further

**NEW OFFERINGS SECTION**
-	Move ‘Program Delivery’ section – program delivery is a facet of each offering and keep three options as radio buttons
-	Note – If the study period offering is “Blended” we will need to ask the student if ALL of their courses for that study period are online to determine the student is eligible to receive a transportation allowance

**Comment by courtneygringras** [comment]
@hellolynn-dsib Revising the question wording per feedback from feature owner:

How will the program be delivered? (Select all that apply)
[ ] On site
[ ] Online

- Conditional series of questions: If they select ONLINE, show the following question:
"Will the program also be offered and delivered at 100 percent course load on site? Yes/No"

- IF NO -> Ask "Will the students earn the same number of credits in the same time period as students in other StudentAid BC eligible programs delivered on site? Yes/No"
- IF NO -> Ask "Will they earn academic credits that are recognized at another designated institution listed in the BC Transfer Guide or other acceptable articulation agreements from other jurisdictions? Yes/No"
