### ISSUE TITLE
Analysis - Enable CORS on SIMS API (allow API call from formsflow.ai)

### ISSUE THREAD

**Issue by andrewsignori-aot** [bcgov/SIMS#419]
**Additional Context**
- The CORS was enabled on SIMS Api in a permissive way to allow the formsflow.ai to have access to SIMS API.
We need to configure CORS to be more restrictive as possible or consider deploying the formsflow.ai applications under the same domain.

As an output of the analysis it has been found that, in API CORS must be restricted to all web domains. 
As camunda to SIMS API call does not happen  through browser, CORS does not have any impact on Camunda API calls.
As SIMS Web and API are sharing the same origin, they API calls from SIMS web to API are not considered as Cross Origin Resource Sharing.

**Acceptance Criteria**
- [x] Enable CORS restriction in all non developement/openshift environments
- [ ] Determine method to resolve CORS issue
- [ ] Put api+web under same domain and disable CORS
OR
- [ ] explicitly define domain to enable CORS for a particular domain

**Comment by dheepak-aot** [comment]
Tested in DEV by submitting application no: 2023000016 (Application id: 1427)

Camunda was able to call SIMS API and successfully update the application. 

![image.png](https://images.zenhubusercontent.com/60e72aa247c95cd873ed8ce1/de8bca2a-17cb-465a-9922-e2c31f4933c3)

Camunda workflow details: 
![image.png](https://images.zenhubusercontent.com/60e72aa247c95cd873ed8ce1/323b7c79-a24c-47bf-94e2-51107734f5a8)
