### ISSUE TITLE
UX / UI  Institution Location- Student Application SUMMARY Page

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#424]
As an Institution user I want to see a summary of student applications so that I can confirm enrollment and perform other administrative tasks (withdrawals and scholastic standing)

### Additional details:
Students who are no longer active are not shown in the system
Name change: Applications vs Students?

### Acceptance Criteria

- [x] See a summary of all students with active (study period) applications at the location
- [x] Display: Name, Program, Application number, Period (Start/End), Status
- [x] Confirm fields with Confluence

**Comment by roopfw** [comment]
[Figma Link: ](https://www.figma.com/file/VykmBDwobGoGvK9M5wgOvN/StudentAid-BC-App-Design-System-WIP-FreshWorks-Studios?node-id=1724%3A18852)

![image.png](https://images.zenhubusercontent.com/5e66ca845237f60c730a4aa3/879139cb-dab1-4c16-b138-ac166f95224a)
