### ISSUE TITLE
Institution User edits a program or offering when a Student is enrolled in the program. 

### ISSUE THREAD

**Issue by roopfw** [bcgov/SIMS#431]
What happens when an Institution User edits a program or offering when a Student is enrolled in the program. 

Before COE:
This is likely to happen before COE. Which will involve a Bulk Reassessment or Individual Reassessment depending on the offering. 

After COE:
Active Application linked to Offerings- Offerings cannot be edited once any application has been Confirmed Enrollled in that Offering. This requires manual intervention from SABC Staff. 

Manual Intervention from Ministry Staff is TBD- Staff can edit Offerings for example?

NEW STORY-Institution User wants to Deactivate Offer _ add a date for when it should be deactivated by.

Robins's list of Ministry Tasks could inform this.

**Comment by alpivett** [comment]
Awaiting user testing as understood that currently this would result in a reassessment prior to CoE and restriction and addition to a change list after CoE.
