### ISSUE TITLE
Continue Draft Assessment

### ISSUE THREAD

**Issue by abschwenker** [bcgov/SIMS#465]
- [x] Continue draft assessment
- [x] Pass some variables and see some calculations (Steps 1-4)

**Comment by sumathi-thirumani-aot** [comment]
Working copy of DMNS uploaded in location - https://teams.microsoft.com/_#/files/DEVS?threadId=19%3Ac91c9c0acf5f44dcab6789f870ddf47e%40thread.tacv2&ctx=channel&context=v1-alpha&rootfolder=%252Fteams%252F03177%252FShared%2520Documents%252FDEVS%252FBPM%2520Workflows%252FAssessment%252Fv1-alpha
