### ISSUE TITLE
UX / UI- Institution User Research Scenarios & Questions

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#469]
For Institutions 
**Acceptance Criteria**

- [x] Scenarios Documented
- [x] Questions Documented
- [  ] Prototypes organized in a manner for interview
- [x] Identify specific Users 
- [x] Gather contact Info

**Comment by hellolynn-dsib** [comment]
### Ready for Monday

✓ Scenarios documented with PO in UX connect sesh
✓ Questions completed by Roop
✓ Prototype completed by Lynn
✓ Scheduling/consent by Adrienne

### Links:
- Questions/tasks: https://docs.google.com/document/d/1SZ2PvDVwMETNcxlXzBWzeYc0LhhFcoOHCgEvFl_o26I/edit#heading=h.1a8yk8widr5f
- Prototype: https://www.figma.com/file/veFP4DBBFE3SRu3TjkC0Hv/StudentAidBC-Education-Programs-Prototype?node-id=0%3A1

### Note:
Will need to expand FIGMA license to store prototypes/wireframes in 1 place

**Comment by hellolynn-dsib** [comment]
![Schedule](https://images.zenhubusercontent.com/6047d6ac906f4ec904f7286c/67a8e9ce-0cef-480a-8d68-16f3427751db)
