### ISSUE TITLE
UX/ UI- Update Student Application Process Wireframes to reflect new workflow and Additional questions

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#477]
Update Student Application to reflect Courtney's Workflow diagram and the associated questions. 

**Acceptance Criteria**
[ ] -Update Wireframes to reflect the new Student Application Workflow
[ ] -Add Missing Questions 
[ ] -Update Wireframe Questions

**Comment by abschwenker** [comment]
https://hive.aved.gov.bc.ca/wiki/pages/viewpage.action?spaceKey=SIMS&title=Student+Application+Questions
