### ISSUE TITLE
Create Confirmation of Enrolment send file for institutions

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#486]
Additional Context
- File layout in analysis folder
- File is based off all applications that have an eligible COE request waiting
- file layouts are in analysis folder for ECE file layouts
- The file is only for FT course offering, (Course load field is hardcoaded to 100 as per the filelayout document)

Acceptance Criteria
- [x] Create ECE request file if integration flag = true
- [x] Generate the pending COE's for the institution till date

**Comment by dheepak-aot** [comment]
On the SFTP server, the expectation is to create folder for each institution location which has `hasIntegration` flag set to true
