### ISSUE TITLE
Ministry Views Student Application Details

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#487]
Additional Context
When a ministry user navigates to a student and clicks "view" on an application the ministry user needs to be able to see the:
- Student Application Form
- Attached Partner information Form (if present)
- Attached Parent(s) information Form (if present)
Keep the same practice for read-only forms (student, partner, parent 1, parent 2)

Acceptance Criteria
- [x] When a ministry user clicks "view" on a student application from the application summary page on the student account they can view the student form in read only.  (default view after clicking view)(files, questions, and dropdowns should populate correctly)
- [x] After clicking "view", Change Side Nav bar to view the application nav bar
- Display Student, Parent 1, Parent 2, Partner. If no data is present display do not display the button for "Parent 1, Parent 2, Partner"
- [x] Add "Back to student applications" button which navigates back to the student application summary page
- [x] When a ministry user clicks "Parent 1" from the student application page AFTER CLICKING "view" on a student application from the application summary page on the student account they can view the Parent 1 form in read only. (files, questions, and dropdowns should populate correctly)
- [x] When a ministry user clicks "Parent 2" from the student application page AFTER CLICKING "view" on a student application from the application summary page on the student account they can view the Parent 2 form in read only. (files, questions, and dropdowns should populate correctly)
- [x] When a ministry user clicks "Partner" from the student application page AFTER CLICKING "view" on a student application from the application summary page on the student account they can view the Partner form in read only. (files, questions, and dropdowns should populate correctly)
- [x] When a ministry user clicks "Student" again from the student application page AFTER CLICKING "view" on a student application from the application summary page on the student account they can view the Student form again in read only. (files, questions, and dropdowns should populate correctly)

Tech notes
- create API to retrieve data (parent and partner)

**Comment by IrenaMilosevic1** [comment]
Approved.
