### ISSUE TITLE
UX Cleanup for Student Application

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#51]
### Additional Context

- Go to DEV as source of truth and clean up mockups in FIGMA
- Goal is to stabilize FIGMA for AA accessibility changes / content designer to work off from
- Keep layouts mobile ready
- Ensure design still uses OOTB forms.IO layout / components
- Provide visual design direction (from design system) for any unstyled UI in DEV

### Acceptance Criteria

- [ ] Mockup student application (FIGMA)
- [ ] Record future enhancements here #1018

**Comment by hellolynn-dsib** [comment]
### Heads up (trusted contact mobile view) - redesigned to match dependants
![image.png](https://images.zenhubusercontent.com/6047d6ac906f4ec904f7286c/10196271-4ecc-43bd-844c-6436b71bfdfa)

### Dependants
![image.png](https://images.zenhubusercontent.com/6047d6ac906f4ec904f7286c/c44e6685-74cf-42b7-98d0-e142b1767ac3)

**Comment by IrenaMilosevic1** [comment]
Approved
