### ISSUE TITLE
Dev Priorities / Timeline

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#542]
Student
- [ ] Application Summary
- [ ] Application Offering dates to use in application
- [ ] Display Offering, no dates/costs?
- [ ] Save assessment
- [ ] Display assessment
- [ ] income validation
- [ ] Select what to apply for
- [ ]
Institution
- [ ] Complete program information request
- [ ] Confirm enrollment
- [ ] 
Integrations
- [ ] ESDC File Integration
- [ ] ATBC Integration
- [ ]
Technical Abilities
- [ ] Reassessment
- [ ] Cancel Application
- [ ] Audits
- [ ] Save draft application
- [ ]
Ministry Portal
- [ ] What do?
- [ ]

**Comment by abschwenker** [comment]
Sprint board updated to reflect dev discussions
