### ISSUE TITLE
Accessibility and Mobility with Devs

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#546]
- [x] Present to Devs for a refined approach
- [x] Define action plan for development (#576)

https://www.a11yproject.com/checklist/
https://www2.gov.bc.ca/gov/content/home/accessible-government/toolkit/testing-and-auditing

Accessibility[https://app.zenhub.com/files/319429847/d3446c47-5b9a-41c7-8076-9fcdc2bd17b2/download](https://app.zenhub.com/files/319429847/d3446c47-5b9a-41c7-8076-9fcdc2bd17b2/download): 
AA excelsheet: [https://app.zenhub.com/files/319429847/78e45e8f-6dd2-4b46-9948-44e1aa5bccb0/download](https://app.zenhub.com/files/319429847/78e45e8f-6dd2-4b46-9948-44e1aa5bccb0/download)

**Comment by abschwenker** [comment]
Action Plan

Create a "baseline" - Run a full set of automated tested for AA Compliance (See ticket .....)

Developers - When doing UI Development tickets follow a basic set of guidelines
1. Perform Basic Keyboard testing to ensure functionality
2. Perform zoom testing up to 200% to ensure layout functional
3. 


UX Team - Lead in depth testing at staggered intervals (Every 2 months??)
1. Lead and confirm Minimal requirements are met (AA Compliance)
2.

**Comment by roopfw** [comment]
[https://app.zenhub.com/files/319429847/b0488029-e81b-43ad-903b-5a8e92ec4155/download](https://app.zenhub.com/files/319429847/b0488029-e81b-43ad-903b-5a8e92ec4155/download)

**Comment by abschwenker** [comment]
separate ticket created for dev action plan to be prioritized
