### ISSUE TITLE
UX/UI-BC Loan Forgiveness (Application) 

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#556]
- [ ] BC Loan Forgiveness- https://studentaidbc.ca/repay/repayment-help/bc-loan-forgiveness-program
- [ ] Pacific Leaders (#710) 

*Acceptance Criteria*
- [x] Research BC Loan Forgiveness
- [x] Determine the questions on the application (workflow)- Is this a separate application from Pacific Leaders Loan Forgiveness?
- [x] Determine the Application Logic
- [x] Draft Wireframe/ Forms io

- [x] Document the Biz Rules for Approval (AKA info is sent to MCFD for approval)
- [x] Document what happens 'After Approval'.

**Comment by roopfw** [comment]
[**Application - BC Loan Forgiveness Program**](https://www.figma.com/file/lAm53dM5Guyf42GjE47W8d/Application---BC-Loan-Forgiveness-Program?node-id=0%3A1)
![image.png](https://images.zenhubusercontent.com/5e66ca845237f60c730a4aa3/d1c7a460-a6fd-4360-8e96-fb92e1188e60)

![image.png](https://images.zenhubusercontent.com/5e66ca845237f60c730a4aa3/fdc089e4-87ec-448d-9c11-92d063d91d6f)
[BC Loan Forgiveness Program Wireframes](https://www.figma.com/file/VykmBDwobGoGvK9M5wgOvN/StudentAid-BC-App-Design-System---FreshWorks-Studios?node-id=5877%3A46755)
