### ISSUE TITLE
Disbursement forecast report

### ISSUE THREAD

**Issue by andrewsignori-aot** [bcgov/SIMS#559]
**Additional Context**
- Explore possibility to make the reports dynamically generated based of pre saved queries (stored procedures, views, etc., to be discussed)

- User must have the ability to generate “Disbursement Forecast Report” in SIMS
- This report is for Pending disbursements (scheduled)
- the system to forecast disbursement value based on the application and notice of assessment (NOA) information, including different types of funding.
- SABC can determine how much will be disbursed in future/ a given time period (Provincial Treasury and Federal Government also asks for projected disbursement info during peak periods).
- SIMS can produce a report based on applications in the system to determine disbursement data (planned disbursements each day) 
- For this report, SIMS must replicate existing SFAS report scr-sd-48325 (refer Analysis doc) with potential UI improvements (Mock-ups to be validated with Blaine) 

**Acceptance Criteria**
**- Create UI**
- [x] Display "Reports" button in bottom of left navigation in the ministry portal
- [x] On click of "Reports" button navigate to "Reports" Page
- [x] Display the following fields
- Report Type (dropdown consisting of "Disbursement Forecast") - More will be displayed later
- Start Date (Date picker)
- End Date (Date picker)
- Intensity (Full Time / Part Time MultiSelect)
- [x] "Export CSV File" button

**- Create Report**
- [x] On click of "Export CSV File" (from above UI) generate following CSV
- [x] Report must display each Loan and Grant total for the day of disbursement
- Report DETAILS:
- [x] Report Name (Disbursement Forecast Report)
- [x] Date and time of report generation (Part of the file name)

- Columns in CSV: 
- [x] Date of Disbursement
- [x] Funding Type (Loan or Grant type)
- [x] Total Disbursement amount (add values of all retrieved records in "Count" (below) to calculate this number
- [x] Count (the number of records/student applications that sum up to the disbursement amount for a day (above))
- Criteria: Check for disbursement schedules, and date to be disbursed falls in the selected date range

CSV Example,
Disbursement_Forecast_Report-YYYYMMDDTT:TT
Date of Disbursement, Funding Type,Amount,Count
2020-AUG-01,BCAG,16073.00,12
2020-AUG-01,BGPD,5073.00,15
2020-AUG-01,CSLF,1236073.00,206
2020-AUG-04,BGPD,77073.00,88
2020-AUG-04,BCAG,36073.00,71
2020-AUG-05,BCSG,10415.00,88

**Design Details**
- User must have the ability to download the report using at least 1 format, such as: PDF, Excel/.CSV 
- Date Range and Export feature
- Part time and Full time selection feature
- Users who must have access to this report in SIMS:
- Will have access role associated with this report

Analysis Doc Link: Teams Channel>General>Files>Analysis>User Story Specifications>559

**Comment by dheepak-aot** [comment]
The format of "Date of Disbursement" in the CSV file follows ISO date format(YYYY-MM-DD) so that it is parsed/read as date instead of text so that it can be used in data operations which can be performed by a spreadsheet editor.
