### ISSUE TITLE
UX/ UI Student Satisfaction Survey

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#566]
Lynn to work with Danielle on V2 Student Satisfaction Survey

This will out Aug 5th.

**Comment by hellolynn-dsib** [comment]
### What's this?:
- A short survey to provide a "health check" around users' satisfaction and usability for the website & application
- The results for the survey in March 2021 will be compared with this survey - and another one after launch

### Where will this be published?

- A popup will display on the website and dashboard inviting users to participate in a short survey - sending participants to the links below

_Website:_ ![image.png](https://images.zenhubusercontent.com/6047d6ac906f4ec904f7286c/d244117a-efe5-42f0-a4cd-ffba6a24cf85)

_Dashboard:_
![image.png](https://images.zenhubusercontent.com/6047d6ac906f4ec904f7286c/073c830b-5529-41f1-8e49-3acd8cf8cdfc)

### Survey Test Links:

- StudentAidBC website: https://unc2751u.optimalworkshop.com/questions/2smo30rm-0-0-1-2
- StudentAidBC dashboard: https://unc2751u.optimalworkshop.com/questions/2smo30rm-0-0-1-1-1

### Dates:

- **Test on UAT:** Wednesday, August 4
- **Survey start date:** Thursday, August 5 (morning)
- **Survey end date:** Sunday, September 5

### Notes:

- The orange colours in the test link will be replaced with B.C. Government colours after survey purchase
- Lynn to coordinate purchase with an admin on Thursday, August 5
