### ISSUE TITLE
UX/ UI Report Scholastic Standing 

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#569]
- [ ] Workflow
- [ ] Wireframe /Forms IO
- [ ] Confirm Tech Feasibility 

https://www.figma.com/file/pkyswXF1Sbc1O7W8eBeslW/Actions-on-Student-Scholastic-Standing?node-id=27%3A263

**Comment by roopfw** [comment]
Discussed with UX team and PO:

When viewing an "active" student you will see the option to "update scholastic standing" in the "Application Actions" menu.

Once chosen, the institution can select from several scholastic standing options, with ability to enter relevant dates.

The downstream effects of these actions still need to be investigated.

Created a ticket in the backlog!

Prototype Link: [View prototype here](https://www.figma.com/proto/VykmBDwobGoGvK9M5wgOvN/StudentAid-BC-App-Design-System-WIP-FreshWorks-Studios?page-id=642%3A2733&node-id=3513%3A29256&viewport=39825%2C63317%2C0.9965201616287231&scaling=min-zoom&starting-point-node-id=3513%3A29256)

**Comment by roopfw** [comment]
### Section 6.2 needs to be added to this work:

https://studentaidbc.ca/sites/all/files/school-officials/admin_manual.pdf
Page 42 onwards

**Comment by roopfw** [comment]
Created board to ensure the outcomes of the scholastic standing changes are clear:

[Process Journey Board](https://www.figma.com/file/pkyswXF1Sbc1O7W8eBeslW/Actions-on-Student-Scholastic-Standing?node-id=0%3A1)
