### ISSUE TITLE
Award Eligibility in Camunda- CSG-PTDEP

### ISSUE THREAD

**Issue by roopfw** [bcgov/SIMS#572]
[https://app.zenhub.com/files/319429847/2f48750e-a746-40ff-8373-4ba094194b6f/download](https://app.zenhub.com/files/319429847/2f48750e-a746-40ff-8373-4ba094194b6f/download)

**Additional Information**
BCAG-PT = BC Access Grant for Part-Time Students
-When determining "Program longer than 2 years" use Program_length: 1-2 years, 2-3 years, 3-4years, 4-5years, 5years or more

**Acceptance Criteria**
- [ ] Create dynamic eligibility per attached file

**Comment by guru-aot** [comment]
Testing Scenarios

If the student have dependants,
![image](https://user-images.githubusercontent.com/62901416/150585358-f0251673-e441-485f-979f-311a08f6806a.png)

CSG-PTDEP grant is given
![image](https://user-images.githubusercontent.com/62901416/150585193-eb0476d2-6443-4bd6-af05-10c490c433ae.png)

If the student have no dependants
![image](https://user-images.githubusercontent.com/62901416/150585504-4d6694be-efd5-405b-98f8-55bd61e8516d.png)

CSG-PTDEP grant is not given
![image](https://user-images.githubusercontent.com/62901416/150585722-ffd2754b-03ec-4261-8cbe-a7df028f8461.png)
