### ISSUE TITLE
Analysis- Student Reports a Change 

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#621]
- Any change in Student circumstances After Institution confirms Enrolment
- Student Reports a Change- What are the Scenarios?- What triggers a Reassessment

Related Tickets
#335
#659
#649

What can we easily automate vs what is a manual intervention? 

Scenarios:  EG. A student changes from Part-Time to Full time- this triggers a reassessment.
Student Graduates Early then...? 

What happens when? .. Reassessment? Nothing? 
-Change Programs 
 - Course 
- change from Full time to Part-time
- Withdrawal
- Family Changes (new dependant) (marriage) blah blah
- Death

What does Staff need to do with this? (lets create another ticket for this) 
-Reported Changes

Figma Links:
https://www.figma.com/file/VykmBDwobGoGvK9M5wgOvN/StudentAid-BC-App-Design-System-(WIP!!)---FreshWorks-Studios?node-id=21%3A451

https://www.figma.com/file/pkyswXF1Sbc1O7W8eBeslW/Actions-on-Student-Scholastic-Standing?node-id=0%3A1
https://www.figma.com/file/pkyswXF1Sbc1O7W8eBeslW/Actions-on-Student-Scholastic-Standing?node-id=27%3A263

**Acceptance Criteria**

**Analysis**
- [ ] Process flow of scenarios of when a student would Report a change.
- [ ] Start with PO and Validate with FO (as Required)

**Comment by alpivett** [comment]
Institution  Users report changes after CoE through 'academic standings' such as withdrawal, early/late completion or unsuccessful completions.  Students report all kinds of changes through their application (addition of dependent/spouse, change in finances, change in program or program length/intensity).  

In any case, we want changes reported by institutions users or students to result in the same outcome:  add an automated provincial restriction stopping future disbursements and outline the change on a list for Ministry staff to resolve

**Comment by michesmi** [comment]
This ticket is answered with #868
