### ISSUE TITLE
Additional Ed Program and Offering Enhancements

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#639]
**Institution User Creates Program and Offering Study Period**
**Create New Program Page**
** Overview**

_Mockups:_ https://www.figma.com/file/VykmBDwobGoGvK9M5wgOvN/StudentAid-BC-App-Design-System---FreshWorks-Studios?node-id=5925%3A45231

- [x] Provide the following text for guidance, " Submit your program to ensure it meets the eligibility for student funding
After the program is approved, you’ll get to add study periods and costs to it"
- [x] Program Description (_Is now optional)_ _(Updates to the following: Program Details, Student App Selection View, Student App, 'Not Listed' View)
- [x] Credential Type is now revise_d to be the following list, (_Updates to the following: Program Summary Table, Offering Summary Table & Student View)_ Revise credential type to the following:
      - Undergraduate Certificate 
      - Undergraduate Diploma 
      - Undergraduate Degree 
      - Graduate Certificate 
      - Graduate Diploma 
      - Graduate Degree / Master’s
      - Post-Graduate / Doctorate
      - Qualifying Studies 
![image.png](https://images.zenhubusercontent.com/5fce9c77aab275719112dc74/9c2f811f-609d-40f5-8ad9-3b1be2133432)
- [x] Update the credential type values in Camunda(award-eligibility.bpmn)
- [x] Add Institution Program Code _(Optional) (Update Program Details)_

 ** Program Eligibility** (_This is a new heading)_
- [x] Are students able to take this program on a part-time basis?  Y/ N  _(Move this content into (?) - A part-time program has a course load between 20 and 59%. A full-time program must have a course load of: 60% or greater or Between 40 and 60% for students with a permanent disability)__
- [x] New Validation on Question- "Does this program include a minimum of 20 instructional hours per week?" _(Include validation for 20 hours and 15 for aviation.) The absolute minimum number of hours of study for a full-time program in a post-secondary institution is 20 instructional hours per week and 15 instructional hours per week for aviation
institutions._
 ![image.png](https://images.zenhubusercontent.com/60c7d7040a42d68fb4abaa59/9c1878d2-108c-445d-b1ef-d766dc283ae6)

**Entrance Requirements**
- [x] "What are the entrance requirements for this program? (Select all that apply)" _(Must Select at least 1)_ If none is selected, provide the pop-up, "An Entrance requirement is required" Entrance Requirement Options are
    - "Students to have graduated from grade 12 or equivalent.
    - Students are 19 years old or older before the start of classes.
    - This program has entrance requirements established by the institution that enables completion of the program study.
    - This program is approved by the B.C. Industry Training Authority and students must meet the entrance requirements set by the B.C. ITA."

** Work-integrated Learning** (New Section) 
- [x] Does the Program have a WIL component?" (Y/N)
      - [ ] If No- Do not provide the following questions
      -  [ ]  If Yes- Provide the following question, " Is the WIL approved by your regulator or oversight body?"
             - [ ] If No-Provide the pop-up, "This program is ineligible for StudentAid BC funding" The work-integrated learning component must be approved by your regulator or oversight body first.
             - [ ] If Yes, Provide the Question, "Does the WIL meet the program eligibility requirements according to StudentAid BC policy?" (Y/ N)
                 - [ ] If Yes (?)
                 - [ ] If No, Provide the following pop-up, "This program is ineligible for StudentAid BC funding" This must meet the StudentAid BC policy."

**Field Trip, field placement, or Travel** (New Section)
- [x] Is a field trip, field placement or travel part of this program? (Y / N)
     - [x] If No, do not provide the following questions
      - [x] If Yes, Provide the following question, "Does the field trip, field placement, or travel meet the program eligibility requirements according to StudentAid BC policy?" (Y /N) 
  - [x] If Yes,- (?)
  - [x] If No, provide the pop-up, "This program is ineligible for StudentAid BC funding" "This must meet the StudentAid BC policy."

**International Exchange** (New Section)
- [x] Does this program have an International Exchange? (Y / N)
   - [x] If No, Do not provide the following questions
   - [x] If Yes, Provide the following question, "Does the international exchange meet the program eligibility requirements according to StudentAid BC policy?" (Y / N)
       - [ ] If Yes (?)
       - [ ]  If No, Provide the following pop-up, "This program is ineligible for StudentAid BC funding" "This must meet the StudentAid BC policy."
**Declaration** (New Section)
- [x] Provide the text, "Program declaration, "All information is subject to verification and auditing."
- [x] "I confirm this program meets the policies outlined in the StudentAid BC policy manual." _(Mandatory must select)_
----------
**Program Details Page** 
- [x] Show new credential types
- [x] Show Institution Program Code
- [x] Update "Offerings" to "Study Period Offerings"

-------

**Add "Offerings" Page** (Add Study Period)
**Overview**
- [x] Change to "Add Study Period" _(Change headings/body copy that doesn’t impact devs (database etc)_
- [x] Add overview text, "Students will see the program name, description, and credential type including your study period name, dates, and year of the program."
- [x] "Study period name/offering name (e.g. 2022 Fall semester, Term 1, Cohort A)" (Max 50 Characters/ if over 59 characters product the warning, "The maximum limit is 50 characters."

**Year of Program**
- [x] Year of Program, Dropdown to select the following: "Year 1, Year 2, Year 3, Year 4, Year 5, Year 6, Year 7, Year 8,
Year 9" 
     - [ ] "Display this to students (Optional)" (Present option to hide/display year to students to help identify) (Provide a pop-up of what the Students will see, "Here’s an example of what students will see."e.g. 2022 Winter co-op (Jan 15 2022 - Mar 20 2022) - Year 1"
- [x] How will this be delivered? (Onsite, Online, Blended) (If what is selected here is not aligned with what was selected in the Program, "Revise the Error Message) "Please ensure the study delivery aligns with program eligibility. To fix this, go back to your program and edit the delivery method." 

**Work-Integrated Learning** (New Section)
- [x] "Does this contain a work-integrated learning component?" (Y / N)
   - [x] If No, proceed to next section
   - [x] If Yes, Provide the following question, "What work-integrated learning type is contained within this study period?" _(Free Text)__(Add error message "This study period can’t contain a WIL component. Your program must be approved with a WIL component." (if NO in program level, can’t say yes in study period offerings page)_ 

**Study Breaks**
- [x] Add multiple study breaks functionality (including delete functionality)
![image.png](https://images.zenhubusercontent.com/60c7d7040a42d68fb4abaa59/d45392eb-1935-4a93-a864-f35c5a06a3b3)
 - [x] if it exceeds 10% = display warning that breaks in excess of 10% will not be funded, "This program is ineligible for StudentAid BC funding. Your break(s) can’t exceed 10% of study dates."
- [x] If breaks exceed 21 days = display error message (, "This program is ineligible for StudentAid BC funding. Your break(s) can’t exceed 21 days."
- [x] If both exceed 10% or 21 days, display error message, "This program is ineligible for StudentAid BC funding. Your break(s) can’t exceed 10% of study dates and exceed 21 days"

**Declaration** (New Section)
- [x] Provide the text, "All information is subject to verification and auditing."
- [x] "I confirm this Study Period Offering meets the policies outlined in the StudentAid BC policy manual." _(Mandatory must select)_
 - [x] Update PIR(create new offering) with all the study period(offering) updates
-------------
**Student Select Program**
**Select Program Page** 
- [x] "What capacity will you be taking this program? (Part-Time / Full Time) _Put this in a (?) A part-time program has a course load between 20 and 59%. A full-time program must have a course load of 60% or greater or 
40 and 60% for students with a permanent disability. If you are unsure, contact your school’s financial aid officer._
- [x] Year of Study
![image.png](https://images.zenhubusercontent.com/60c7d7040a42d68fb4abaa59/3992b0ea-3d92-4dd4-b427-72d3bc44f821)

- [x] Add Courses 
![image.png](https://images.zenhubusercontent.com/5fce9c77aab275719112dc74/133dab7e-6f64-41af-83e4-fe4e53e1ee48)
 - [x] Program Description _(Is now optional)_
- [x] Credential Type _(Confirm correct Credential type) (Confirm if this also needs to be updated in COE view)?_
 - [x] Update COE to display multiple study breaks

**Comment by dheepak-aot** [comment]
Camunda testing  -
CSGFT Eligible scenario - id: cb6b1cc9-4ca2-11ec-b5ee-0a580a613cf5 [graduateCertificate]
CSGFT Not Eligible scenario - id:feacf2b4-4ca3-11ec-b5ee-0a580a613cf5 [postGraduateOrDoctorate]
