### ISSUE TITLE
UX/UI Institutions - Editing program and offerings (when students are in it)

### ISSUE THREAD

**Issue by hellolynn-dsib** [bcgov/SIMS#649]
[**Describe]([url](url)) the task**
It was defined in a previous ticket 520 - all fields are editable (if NO students in it)
but we need to look at what happens if a student is in it.

What are the processes that need to happen?

**Acceptance Criteria**
- [ ] Research workflow required process on ministry side
- [ ] Research what happens with students (if anything)
- [ ] Document Scenarios
- [ ] What happens to the Draft Applications and Submitted Applications
- [ ] Draft a workflow

**Additional context**
- Use the new workflows that exist in place

**Comment by lislap** [comment]
[https://app.zenhub.com/files/319429847/9a1dba75-bcd4-418b-bcf4-e70e2c8534db/download](https://app.zenhub.com/files/319429847/9a1dba75-bcd4-418b-bcf4-e70e2c8534db/download)

**Comment by lislap** [comment]
Attached workflow showing what happens when institutions edit programs when students are enrolled.

**Comment by lislap** [comment]
Reopened to attach revised workflow with start showing institution must submit a request to change the program offering when students are enrolled.
