### ISSUE TITLE
BLOCKED - Change BCeID IDP to BCeID Business

### ISSUE THREAD

**Issue by abschwenker** [bcgov/SIMS#663]
BLOCKED - Waiting on Marco to confirm requirements for Firstname/lastname, business NAME/GUID working properly

Additional Context
- BCeID is changing the way keycloak using their service. We have a new IDP (identify provider) added in keycloak that will operate similar to how BCSC operates.
- The "BCeID Business" IDP should have all required attributes mapped directly into the token and not require going back to bceid webservices on log

Tasks
- Change BCeID IDP to BCeID Business and correct login to use information in login token. Manage users function will still need to go to BCeID webservices

**Comment by HRAGANBC** [comment]
Relevant Devs?

**Comment by sslaws** [comment]
@andrewsignori-aot please add details on why we are closing this and then close.

**Comment by andrewsignori-aot** [comment]
This was created a long time ago and the decision was to use the `bceidboth` IDP to handle Business and Basic BCeID authentications.
