### ISSUE TITLE
Student Updates Info at BC Services Card Information

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#67]
As a Student, I want my updated information at Services Card to be updated on my SABC Profile / Account, so that my current accurate information is provided

**Additional Context**
- Information from BC Service Card will be read-only on the SABC Account.
-The information from Services Card includes First Name, Last Name, Middle Name, Date of Birth, Email, and Gender as read-only.
-When BC Services card information is updated, then the information will be updated on the SABC account).- Another User Story
- enter text here

**Acceptance Criteria**
- [x] Given (Student), When (updates their information at BC Services Card and they login the next time (First Name, Last Name, Middle Name, Date of Birth, Email, and Gender), Then (this information will be updated on their Student Account automagically)

**Comment by andrewsignori-aot** [comment]
![image.png](https://images.zenhubusercontent.com/5fcebe3c076e6aaed83693fb/4a64d68c-4426-45ef-896c-cfd1de93d016)
