### ISSUE TITLE
Edit and Cancel Application

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#673]
**Additional Context**
- Currently the rules for edit cancel are not working correctly, you can edit/cancel at the incorrect time.
- This ticket is verify and resolve the edit, cancel application
- Currently the application appears to not be editable once the assessment is confirmed

**Acceptance Criteria**
- [ ] Edit and Cancel Application should be available for the student ONLY:
- When application is in Draft, Submitted, In Progress, Assessment, Enrollment Status

QUESTIONS:
1. How many application statuses are there in total ? (7?)

Draft
Submitted
In Progress
Assessment
Enrollment 
Completed = first enrollment has been completed
Cancelled = can only be cancelled by student up to the point of CoE

2. Is Edit/Cancel default functionality on all applications except those with Completed/Cancelled status?

**Comment by TeresaBia** [comment]
Superseded by [#880](https://app.zenhub.com/workspaces/student-information-management-system-5fce9df5aa1b45000e937014/issues/bcgov/sims/880)
