### ISSUE TITLE
Student Letters Solution Review

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#684]
Review the solution response makes sense?.

[https://app.zenhub.com/files/319429847/febcbf3f-9004-40c1-9413-38f5bc615e16/download](https://app.zenhub.com/files/319429847/febcbf3f-9004-40c1-9413-38f5bc615e16/download)

**Comment by alpivett** [comment]
see #621

**Comment by alpivett** [comment]
completed a review of the automated letters with the business - ALL automated letters will be replaced by a process in the new system.  

Reviewed remaining Forms with the business to confirm processes.
