### ISSUE TITLE
Confirm Accessibility Plan 

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#687]
- [x] With Alys 
- [ ] With UX/UI
- [ ] With Devs
- [ ] With Jen

**Comment by alpivett** [comment]
We have confirmed that accessibility testing must require AA standard prior to go live.  We will use the approach of becoming familiar with expectation of AA standard and, as much as possible, designing and building to this standard.  However, after we are nearing completion we will do a more specific review to ensure compliance with AA standards.
