### ISSUE TITLE
Institution and Ministry Edit Institution Locations

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#696]
**Additional Context**
Based on the outcome of #331
Review page layout

**Acceptance Criteria**
- [x] A ministry user can edit all location details
- [x] Institution Locations - An institution cannot edit the following fields 
- Location Name
- Institution Code
- Mailing Address (all fields)
- [x] Institution Locations - An institution can edit the following fields 
- Primary Contact - Name
- Primary Contact - Email
- Primary Contact - Phone

**Tech Notes**
- Create common component
- Possible new API
- Follow DA Program component pattern (API calls happen outside the component)

**Comment by roopfw** [comment]
2) Adding a Legal Authorized Authority

- There can only one legal authority at a time per institution.
- If a legal authority is changed at any time this will trigger a designation renewal
- In the old mockups legal authority is selected in the initial institution profile creation
- UX feasibility converation is pretty easy on this one.

3) **Institution User Administrator Determines which locations they want to be designated on the Locations Page.** [#890](https://github.com/bcgov/SIMS/issues/890)

- User must be able to select one or more locations that the institution  has added to add to the system

4) **Validate Location Designation Eligibility automagically (check for created offering for program year).** [#891](https://github.com/bcgov/SIMS/issues/891)

- If selecting a location each must have at last one approved program and offering.
    - There will need to be validation that each meets this criteria.

**5) Institution User Legal Authorized Authority Views Designation Agreement** [#892](https://github.com/bcgov/SIMS/issues/892)

- Once ministry has accepted the designation a notification + email will be sent out the signing authority who will need to come into the system to sign the designation agreement.

**6) Institution User Legal Authorized Authority -Confirms/ Signs / Submits Designation Agreement**

- Signing will add all relevant documents/manuals/agreements to the designation agreement
- The date (and time potentially) will need to be noted on the designation agreement
- As soon as the designation has been signed it will come into effect immediately (or whenever the start date has been set by staff)

**7) Ministry User Views Designation** [#894](https://github.com/bcgov/SIMS/issues/894)

- Minister users can view an institutions designations (expired, approved, pending) from its profile
- Users can view all "pending" designations that require a decision across all insitutions (accept/decline) from the **all designations page.**
    - Once a decision is made on the all designations page the designation can then be found in the institutions profile

**8) Ministry User Approves or Denies Designation** [#795](https://github.com/bcgov/SIMS/issues/795)

- This may need to be moved ahead in the flow refer to flow as defined in this ticket

Submitted → Approved → Legal Signing Authority Notifications→ Signed agreement → Complete

OR

Submitted → Declined →  Notifications of Decline → Resubmit agreement → Start approval flow again
