### ISSUE TITLE
Study Break Dates

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#700]
Review proposal in application. Date Ranges

Question:  What are the dates of your offering (enter dates)?
Question:  Please provide the dates of any breaks in study during this offering.  (allow for multiple break periods)
   Validation Rule:  Add the total number of break days and divide by the total number of days in the offering.  IF less than 10% proceed if more than 10% throw warning (Be advised that your breaks in study exceed the allowable percentage as per SABC policy.)
If Yes,  then 
If No, then  throw a warning and 

![image.png](https://images.zenhubusercontent.com/60c7d7040a42d68fb4abaa59/a516aaf0-0d1e-4da3-8755-36fe64cf326d)
Related to #737

**Comment by abschwenker** [comment]
decision captured in 737
