### ISSUE TITLE
UX/UI Pacific Leaders Loan Forgiveness Application

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#710]
**Additional Info**
This is owned by PSA so may be difficult to simplify/insert creativity.
https://www2.gov.bc.ca/gov/content/careers-myhr/all-employees/career-development/pacific-leaders/bc-loan-forgiveness

*Acceptance Criteria*
- [ ] Research BC Loan Forgiveness for Pacific Leaders
- [ ] Determine the questions on the application (workflow)- is this really a separate application from #556?
- [ ] Determine the Application Logic
- [ ] Draft Wireframe/ Forms IO

- [ ] Document the Biz Rules for Approval 
- [ ] Document what happens 'After Approval'.

![image.png](https://images.zenhubusercontent.com/6047d6ac906f4ec904f7286c/254752dc-5119-41ec-977d-3c2723271146)

**Comment by roopfw** [comment]
![image.png](https://images.zenhubusercontent.com/5e66ca845237f60c730a4aa3/c5771ee9-f735-4973-8185-d8d443ccf9f3)

https://www.figma.com/file/lAm53dM5Guyf42GjE47W8d/Application-BC-Loan-Forgiveness-Program

![image.png](https://images.zenhubusercontent.com/5e66ca845237f60c730a4aa3/524e839e-f170-4384-8d41-7057ff41620b)
https://www.figma.com/file/VykmBDwobGoGvK9M5wgOvN/StudentAid-BC-App-Design-System---FreshWorks-Studios?node-id=5833%3A45746
