### ISSUE TITLE
Report a change in Student Circumstances (Business Rules) 

### ISSUE THREAD

**Issue by abschwenker** [bcgov/SIMS#723]
Biz Rules from #335 To be determined once Ministry Interventions have been solutioned.

Final Study costs for early program completion

-[ ] If, Submit' is selected, then provide the popup on the Application Details Page, "This student’s scholastic standing was updated on {INSERT DATE}. Update (PROVIDE REASON), Date of Effective Change (Not last date of Study) (PROVIDE DATE), Statement of Grades- (Not Needed- do not build).

- [ ] Content should tell an institution to "report a change" when completing a 2nd COE if a student is withdrawn. 
- When an institution declines enrolment and the student has withdrawn the institution should be reporting a change

**Comment by IrenaMilosevic1** [comment]
Duplicate ticket #791
