### ISSUE TITLE
Create Part-Time Assessment

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#726]
Tasks
- [x] Using the attached spreadsheet create a draft part-time assessment workflow
- [x] create structure and draft BPMNs/DMNs for configuring the assessed need, eligibility, and awards
- [x] workflow should reuse common paths (MSFAA, disbursement schedule, income verification)
- [x] Identify major gaps from spreadsheet

[https://app.zenhub.com/files/319429847/d906692e-cf3b-4b68-82a1-ea9a0c8ac345/download](https://app.zenhub.com/files/319429847/d906692e-cf3b-4b68-82a1-ea9a0c8ac345/download)

**Comment by guru-aot** [comment]
- There should be course_load- currently its harcoaded in the assessment-gateway
- parttime offering should have check to have only 52 weeks or lesser - Missed for both full time
- renamed the workflow with proper id’s - TODO
- dynamic workflow selection - but what if partTime does not need parents and stuff??
- calculate assessment workflow has bug in selecting relationship_status
- Hard coded value in award-eligibility gateway for familysize and noOfDependants in fulltime
