### ISSUE TITLE
Student can View Read Only BCSC Information on Account Set up

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#74]
**As a** *(Student)* **I want** *(I want to view the Read-Only Services Card Information)* **So That** *(I can confidently ensure that SABC has the correct information.

**Additional Context**I 
- The information from Services Card includes Given Names, Last Name, Date of Birth, verified email, and Gender as read-only.  
- When BC Services card information is updated, then the information will be updated on the SABC account).- Another User Story
-The information from Services Card includes Given Names, Last Name, Date of Birth, Verified Email, and Gender as read-only.

**Acceptance Criteria**
- [ ] Given (The student has been redirected to the SABC Site ), When (after authentication, Then they can view the information that has been received from the SABC Card site)
- [ ] Given (The student has been redirected to the SABC Site ), When (Im viewing the BCSC information) Then, SABC Information is there but it is 'greyed out.

** Technical Task **
- [x]  No Keycloak or login related development/test is needed.
- [x]  Development - Create a Vue Single Page Form on SABC-SIMS Website with the fields mentioned above in the user story. (First Name and Middle Name changed to 'Given Names')
- [x]  Parse the returned token information on the Keycloak object will done by User Story 17 and information will be stored in the state object.
- [x]  Display the information in the vue form .
- [x]  Nothing is being stored in the database for this user story.
- [x]  Route to this page should be available only after successful authentication
- [x]  Develop functional tests - Use Manual Person(Schwenker) 
- [x]  Unit Testing using Vue Testing Library (Plumbing) - Please see the comment below in this user story to understand the limitation. Raised a technical debt -https://app.zenhub.com/workspaces/student-information-management-system-5fce9df5aa1b45000e937014/issues/bcgov/sims/119
- [x]  How to find out email is verified - Email WILL BE verified from the identity provider and available in the state by User Story 17

**Comment by roopfw** [comment]
![download.png](https://images.zenhubusercontent.com/5e66ca845237f60c730a4aa3/63fd0d5e-7696-4d08-a69d-f5b7f6abb13d)

**Comment by 2011sandeepraj** [comment]
1. Development - Create a Form on SABC Website. call the API? to get the information
2. Route to the page should be available only after successful authentication
3. Develop functional tests using mocha?
4. How to find out email is verified?

**Comment by abschwenker** [comment]
Confirmed with FO - Jamie Glennon that using Given_Names and Last_Name will work for now. If we discover we need to provide middle name for a reason a separate user story will be created.

@alpivett  @mzmichellesmith FYI User Story has been updated to reflect the above

**Comment by 2011sandeepraj** [comment]
Unit Tests for front end Vue component: Vue Test Library plus Jest do not render Prime vue components and we are using these in our Vue pags.  There is just one mention on the internet of successful testing of something that had primevue components but that was using babel instead of using jest.  For now, we can test custom components that don't have primevue components in them using our setup.
Added technical debt task ticket: https://app.zenhub.com/workspaces/student-information-management-system-5fce9df5aa1b45000e937014/issues/bcgov/sims/119
