### ISSUE TITLE
Add minority and parent question to student application

### ISSUE THREAD

**Issue by hellolynn-tbtb** [bcgov/SIMS#758]
Reporting to FEDs. There are no ties to assessments. Robin following up on "prefer not to answer".

**Acceptance criteria:**
- [ ] Add a Y/N
- [ ] Add if Y, add which minority group student self identifies
- [ ] Determine correct question for "how many parents do you live with"
![image.png](https://images.zenhubusercontent.com/6047d6ac906f4ec904f7286c/d0b15c5f-27c2-4f5f-b147-0a6d062c1642)

**Additional context**
-Parent question to confirm:
**As an applicant** 
**I want to provide my parent(s) marital status**  **So That** the correct parent information is requested*

**Additional Context**
- This can replace the current question "How many parents do you live with?"

**Acceptance Criteria**
- [ ] When parent information is required, the following application question is included:
**My parent(s) marital status is:
- Single
- Married/Remarried
- Common-Law
- Seperated/Divorced/Widowed**

- [ ] Given (Single OR Seperated/Divorced/Widowed), When (application is submitted), Then (1 Parent Information Request is generated)
- [ ] Given (Married/Remarried OR Common-Law), When (application is submitted), Then (2 Parent Information Request are generated)

**Comment by alpivett** [comment]
Awaiting confirmation of question and LOV from CSFA - will bring forward for enhancement once confirmed.

**Comment by TeresaBia** [comment]
Business confirmed on May 13 no decision has been made on this issue. Given it will not affect assessment or award, it can be removed from MVP scope list.
