### ISSUE TITLE
Reassessment Analysis

### ISSUE THREAD

**Issue by roopfw** [bcgov/SIMS#759]
**Additional Context **
- Analysis Ticket #791
- Analysis Ticket #868

**Acceptance Criteria**
- [x] 2x 1-hour sessions with Dev team
- [x] 1 Dev to lead and investigate providing input to 2nd session
- [x] Taking into account the below areas, create tickets and structure of how to proceed
- Student Requests change
- Institution Requests change (program / Scholastic standing)
- Student Requests change
- Overawards
- Restrictions

**Comment by abschwenker** [comment]
Added numbers to above comment
1. Overawards should be subtracted from the account when the first COE is confirmed and application is moved to completed
1. Overawards need: Added by, added when posibbly a status if need. Use a transaction based table not a  running value
1. Overewards need a maul way to be added, add a row to table of manual added or subtracting
2. yes, current approach resolved this, will be part of output ticket AC
3. yes, current approach resolved this, will be part of output ticket AC
4. yes, current approach resolved this, will be part of output ticket AC
5. yes, current approach resolved this, will be part of output ticket AC
6. yes, current approach resolved this, will be part of output ticket AC
7. yes, current approach resolved this, will be part of output ticket AC
8. yes, we will have a restriction to stop the disbursmenet then be adjusted based on outcome, will be part of output ticket AC
9. yes, We will have specific tickets for the grant/loan maximums
