### ISSUE TITLE
Tech Analysis - Global Auditing Interceptor

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#771]
**Acceptance Criteria**
- [x] Investigate Generic global way of userid audit in create and update requests

**Comment by guru-aot** [comment]
**TypeORM Subscribers**
https://orkhan.gitbook.io/typeorm/docs/listeners-and-subscribers
https://github.com/typeorm/typeorm/issues/4537
The entity should have the userId, without that the beforeUpdate methods implemented in the typeorm subscribers will not know that to update to the entity.

**Using Nest Middleware**
https://github.com/nestjs/nest/issues/173
NestMIddleware intercepts before the context is set in the request, this inturn does not contain the user object, to pass them in the service layer.

**ModuleRef**
https://docs.nestjs.com/fundamentals/module-ref#instantiating-custom-classes-dynamically
The contextId for a particular request cannot be retrieved from the registered factory to the service it needs to be fetched.

**Other Documents on Injection Scopes && interceptors**
https://docs.nestjs.com/fundamentals/injection-scopes
https://docs.nestjs.com/interceptors
