### ISSUE TITLE
UX/UI Ministry User Views Institution Account Navigation and Institution Details Information

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#773]
### Who's doing what (in this ticket):

- [ ] Ministry navigation (Both)
- [ ] Institution details (Both)
- [ ] Institution Profile (Lynn)
- [ ] Designations (Roop)
- [ ] Locations + programs/offerings (Lynn)
- [ ] Notes (Roop)
- [ ] Users (Lynn)
- [ ] Restrictions (Roop)

![image.png](https://images.zenhubusercontent.com/6047d6ac906f4ec904f7286c/6517a568-f78c-430e-b608-1aa11977e7de)

Slight adjustment on sitemap (pulling programs up)

**Describe the task**
- [ ]  Navigate to all pages in Institution Focus
- [ ] Ministry View of Design the Institution Details Page Share Common Components
- [ ] Create Wireframe for Everything in Institution Details for Ministry Users
![image.png](https://images.zenhubusercontent.com/60c7d7040a42d68fb4abaa59/1962dbd1-4756-4993-b857-3033338ebd59)

Above and beyond ticket #770 Info

**Comment by abschwenker** [comment]
output ticket #770
