### ISSUE TITLE
UX/UI Port to Gov Figma?

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#776]
### New MOD SIMS FIGMA link
https://www.figma.com/file/9Om2tzLAVEoMQrjmrH4fhu/MOD-SIMS?node-id=64%3A632

### Backup Figma (from Freshworks)
https://www.figma.com/file/i3vsdnGiEMp0AN1I4vmXc6/MOD-from-Freshworks-(2021-Dec)?node-id=2%3A48738

_Note this backup is stored in Lynn's government figma account._

-----

- [ ] Move over Freshworks  Figma to Gov Figma (?)  
- [ ] Determine if we need a PIA (borrow a PIA)
- [ ] Cost? Approval from Caitlin
- [ ] Who needs access?

**Comment by hellolynn-dsib** [comment]
Update - free version likely works for now. FIGMA pia with Jason Tang.
