### ISSUE TITLE
Institution User confirm Second Confirmation of Enrolment

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#792]
UX Ticket #918

Additional Context
- COE will happen up to 2 times for each application (1 for each disbusement). This will cause up to 2 identical entries to appear in the table for coe. Most often only 1 will be within the 21 day window but not always.

Acceptance criteria
- [ ] Save below fields along side the **disbursement schedule**
- [ ] Save approved by / declined by along side the disbursement schedule
- [ ] Implement pagination, sort, search
- [ ] Change disbursement to check Approved- coe_approved = Y
- [ ] Create 2 tab UI according to wireframes (Adjust columns to include disbursement date)
- [ ] Update status badges accordingly
- [ ] Applications disbursement within 21 days should appear in the first tab
- [ ] Applications disbursement outside the 21 days window / Declined COEs / Approved COEs , should appear in the 2nd tab
- [ ] Order for 2nd tab should be Required -> Completed -> Declined
- [ ] Add disbursement_date field to COE Form
- [ ] If an institution declined the FIRST coe, the 2nd coe should also be declined
- [ ] If an institution declined the 2nd coe, the FIRST coe should NOT be declined
- [ ] If an institution tried to complete the 2nd coe BEFORE the FIRST coe, Restrict "approval" and display toast message "Please complete the first disbursement"

**Tech Notes**
In sims.disbursement_schedules
additional required fields
coe_approved (Y/N)
coe_updatedby
coe_updatedon

COEStatus's
Required- coe_approved = null
Approved- coe_approved = Y
Denied- coe_approved = N

**Comment by IrenaMilosevic1** [comment]
Approved.
