### ISSUE TITLE
UX / UI Ministry User Views all Pending Designations

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#795]
![image.png](https://images.zenhubusercontent.com/60c7d7040a42d68fb4abaa59/e3549e35-1ef2-4b26-afc6-292861e400d1)

- [ ] Draft Wireframe for Ministry Users to View, Accept, Decline All Pending Designations
- [ ]  Confirm Technical Feasibility. 
- [ ] Including the upstream/downstream impacts of this analysis

**Comment by roopfw** [comment]
### All Pending Designations View
![image.png](https://images.zenhubusercontent.com/5e66ca845237f60c730a4aa3/44a0920b-f6bd-4fbb-84d3-487c3068b73e)
**[Clickable Figma Prototype:](https://www.figma.com/proto/VykmBDwobGoGvK9M5wgOvN/StudentAid-BC-App-Design-System---FreshWorks-Studios?page-id=642%3A2733&node-id=7002%3A54331&viewport=350%2C48%2C0.24&scaling=scale-down&starting-point-node-id=7002%3A54331)**

### Current Designation Workflow
![image.png](https://images.zenhubusercontent.com/5e66ca845237f60c730a4aa3/e95b35f5-b5bd-4b3f-acd4-74c7758e488a)

**Comment by roopfw** [comment]
Based on the feedback received in standup I have updated screens with the following changes:
* Added a type column type on the All Designations screen
  * Initial Agreement
  * Renewal
* Removed ability for staff to select start and expiry when approving.
* Removed start/expiry dates to the destination replaced with designation period

### Backlog items to be created
* Updates to designation application to ensure it follows this flow
* Ensure institutions can select WHICH years they want to be designated for.

**Comment by abschwenker** [comment]
[https://app.zenhub.com/files/319429847/c07e5f4e-1965-4141-8d55-bb3e10c778f6/download](https://app.zenhub.com/files/319429847/c07e5f4e-1965-4141-8d55-bb3e10c778f6/download)
