### ISSUE TITLE
Analysis- Create UAT Test Plan 

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#797]
Testers from the Biz.
- [ ] Determine Is there a way we can enable automated Testing (A technical resource)  
- [ ] Leverage Niki's original test scenarios as a starting point
- [ ] Confirm UAT Testing Approach (aka at the end of each sprint moving forward?)
- [ ] Develop Test Plan with UAT Person
- [ ] Schedule first UAT Testing for January (?)  Nicki, Tatianna, Stuart.
- [ ] Confirm Access for Danielle.
- [ ] Define what Successful Testing Looks like.
- [ ] Develop Process for UAT (eg: at the end of each sprint or beginning of the next sprint?)
----- [ ] Determine how to document Feedback and present to PO for Prioritization.
- [ ] Do the testers need a Detailed Product Overview First?-likely.

Danielle is available for assistance.

**Comment by lislap** [comment]
[https://app.zenhub.com/files/319429847/1dc99928-7e06-47e9-ac58-73d775fa49f1/download](https://app.zenhub.com/files/319429847/1dc99928-7e06-47e9-ac58-73d775fa49f1/download)

**Comment by lislap** [comment]
@michesmi and @alpivett - I've attached the test strategy document with test process flow and approval process flow for your review. I won't move the whole ticket to review as I'm working on scenarios and test cases still.
