### ISSUE TITLE
UX Ministry Views Application Specific Offerings

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#799]
Additional Context
- When an institution user completes a PIR they can select Public or Private offering (screenshot below)
- The only way an institution can see which offering a student is in for "non-public" offerings is to view the PIR for a student
- Currently, the program and offering areas are "public-only"
- Using the same structure for a ministry user, Currently, the program and offering areas are "public-only", meaning a ministry user cannot see offerings a student is in if they are private
- A ministry user does not have a direct way of viewing a program for a student
- Consider #814 in your design

Acceptance Criteria
- [ ] Determine way for ministry user to see the offerings a student is enrolled in (public+private)

**Comment by abschwenker** [comment]
resolved with #980
