### ISSUE TITLE
Update NOA to include approval for Grant Only

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#800]
- [ ] Confirm Award Grant Only or Confirm All
- [ ] Remove the hidden variable that calculates eligibleAmount=data.assessment.totalFederalAward+data.assessment.totalProvincialAward; in the form definition
- [ ] Execute any necessary rounding on workflow and persist to the DB ready to be displayed anywhere as needed.

**Comment by HRAGANBC** [comment]
Closing as this is replaced by other tickets which allow student to select grant only.
