### ISSUE TITLE
Upgrade Formsflow to latest versions

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#813]
**Acceptance Criteria**
- [x] Upgrade formsflow (Camunda, Form.io, formsflow)
- Do not downgrade formio

**Comment by guru-aot** [comment]
General Dev and Test environment has been updated to formsflow-4.0.4 version. The release notes for the version can be found in https://github.com/AOT-Technologies/forms-flow-ai/releases/tag/v4.0.4

Major upgrades:
forms-flow-bpm

- Camunda upgrade from 7.13.0 to 7.15.0.
- Upgraded springboot from 2.4.2 to 2.4.8
- Upgraded spring-security-oauth2 from 2.4.2 to 2.4.8

forms-flow-forms

- Formio upgrade from 2.2.x to 2.3.0

forms-flow-web

- Added upload/download forms feature.
- Added a feature to search submissions in metrics based on created or modified date range.

forms-flow-api

- Better logging for Python API including coloured logs and API time details.
- Add pessimistic Database disconnection handling mechanism.
- Added pagination, sorting and filtering for Application Page.
- Added new APIs which acts as a gateway for calling forms-flow-analytics APIs.
- Added new API for modifying group details in Keycloak with the help of Keycloak admin APIs.
- Add application status list API.

Visible improvements in our application are 

- Better Student application submission time
- Forms upload and download feature in the formsflow admin page
- Overall system stability
