### ISSUE TITLE
FO Tuition Waiver - YEAF Meeting Policy Updates Review 

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#835]
questions around how this will rolled into an application with Youth educational assistance fund   Waiting on a decision from FO biz/ direction from alys

**Comment by alpivett** [comment]
Met with the team and they have provided me with the list of changes and a solid overview of what is needed for the application.

**Comment by alpivett** [comment]
Plan 
Integrated application for Tuition Waiver Program and YEAF as decision is that IF student eligible for TWP then eligible for FYIC Grant.
