### ISSUE TITLE
Update Designation Text

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#85]
**Acceptance Criteria**
- Update designation agreement text to the attached

**Comment by mzmichellesmith** [comment]
Matts Persona Journey Through the Financial Aid Persona- Focus on Personal Questions

**Comment by TeresaBia** [comment]
Designation text confirmed by Alys.[https://app.zenhub.com/files/319429847/c95a2450-9d67-4f25-ba52-3e59ea2496b9/download](https://app.zenhub.com/files/319429847/c95a2450-9d67-4f25-ba52-3e59ea2496b9/download)

**Comment by TeresaBia** [comment]
Updated legal text confirmed by Alys. 
[https://app.zenhub.com/files/319429847/dd7d125b-22b9-460f-b77b-3339669c24c8/download](https://app.zenhub.com/files/319429847/dd7d125b-22b9-460f-b77b-3339669c24c8/download)
