### ISSUE TITLE
Student Views Message Centre

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#860]
**As a** *(Student)* **I want** *(View my Message Centre)* **So That** *(I can see if there are any Notification that requires my attention)*

**Tech Notes:**
Every 1-minute refresh notification for a user. Similar to the timeout. Timer check API notification to update the state of the vue store, UI react to that

**Additional Context**
- The UX Story is #783
- The Message Centre for Institutions is the same #861
- At points in the student process there is a Trigger that will initiate a generic email prompting the user to log in to their SABC Account

**Acceptance Criteria**
- [ ] The Student logs in and there is a new message for them to view, there is an alert (in red) indicating that there is a notification waiting for them, and the # of notifications
![image.png](https://images.zenhubusercontent.com/60c7d7040a42d68fb4abaa59/1fbe4292-4f24-4394-bb23-e5edf81856c4)
- [ ] When the Student Selects Notifications from the top navigation then a Messaged 'Drawer' is displayed. 
![image.png](https://images.zenhubusercontent.com/60c7d7040a42d68fb4abaa59/80e14eb6-5129-49e1-b753-56c10fa37960)
- [ ] The Student Can see the Title of the message, a brief truncated description of (? characters) and a symbol indicating that the message has not been read (blue dot on the left side).
The Student Can see the Title of the message, a brief truncated description of (? characters) and a symbol indicating that the message is a priority to action (orange with an exclamation mark). Priority = Student has something to ACTION. e.g Notice of Assessment. Not a Priority is FYI information.
- [ ] Once the student has selected this message the status of the message is changed and a symbol is shown to indicate that it has been 'seen' (green with a checkmark)
      - [ ] The student has the option to "Mark All as Seen" which turns all messages to the 'seen' status.
- [ ] The Student has the option to "See all messages" which expands the notifications centre from a drawer view to a full page view
![image.png](https://images.zenhubusercontent.com/60c7d7040a42d68fb4abaa59/577510a0-ba38-4994-b09d-d576f63c01bf)
-[ ] The example is given in this scenario is "Your assessment is Ready," should the student select this message they are directed to the NOA page to accept their Notice of Assessment.

**Comment by TeresaBia** [comment]
Change Request 3.
