### ISSUE TITLE
Institution User Views Message Centre

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#861]
**This Story May need to be updated based on the results of #451 and #245

**As a** *(Institution User)* **I want** *(View my message Centre)* **So That** *(I can see any notifications that may require my attention)*

**Additional Context**
- The UX Story is #783
- The Message Centre for Institutions is the same #861
- At points in the student process there is a Trigger that will initiate a generic email prompting the user to log in to their SABC Account
- The images presented in this story are from the Student Dashboard but the message center for the Institution user *should operate the same.

**Acceptance Criteria**
- [ ] The Institution User logs in and there is a new message for them to view, there is an alert (in red) indicating that there is a notification waiting for them, and the # of notifications
![image.png](https://images.zenhubusercontent.com/60c7d7040a42d68fb4abaa59/ece51d65-d929-4c85-b449-f0d3f4886535)
- [ ] When the Institution User Selects Notifications from the top navigation then a Messaged 'Drawer' is displayed. 
![image.png](https://images.zenhubusercontent.com/60c7d7040a42d68fb4abaa59/fcaa9673-ce7f-48f3-ad1b-5191a97efb22)
- [ ] The Institution User can see the 'Title' of the message, a brief truncated description of (? characters) and a symbol indicating that the message has not been read (orange with an exclamation mark).
- [ ] Once the Institution user has selected this message the status of the message is changed and a symbol is shown to indicate that it has been 'seen' (green with a checkmark)
      - [ ] The Institution User has the option to "Mark All as Seen" which turns all messages to the 'seen' status.
![image.png](https://images.zenhubusercontent.com/60c7d7040a42d68fb4abaa59/b318895f-fa50-40c0-9007-d2f82ce43506)

**Question**
Is it marked as seen for all users or just the one User?

**Comment by TeresaBia** [comment]
Removed from scope.
