### ISSUE TITLE
Analysis- Calculate Over award / Reassessment on Student Account

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#868]
**Analysis**
- [ ] Determine how to calculate an over-award
- [ ] Determine how to calculate a reassessment
- [ ] Determine how this affects disbursements- future disbursements
- How it affects scheduled disbursements
- How it affects already sent disbursements
- Variables in
- Variables out
- Data needed to save and report
- How the math works with grants/loans based off the above

**Acceptance Criteria**
- [ ] Review Tech Feasibility Options with Schwenker

**Analysis**
- [ ] Workflow Scenarios / Document Requirements

**Comment by abschwenker** [comment]
[https://app.zenhub.com/files/319429847/e531d5b2-0655-4f56-a4b9-fb3666de9c68/download](https://app.zenhub.com/files/319429847/e531d5b2-0655-4f56-a4b9-fb3666de9c68/download)
