### ISSUE TITLE
PPD status - Persistent or Prolonged Disability

### ISSUE THREAD

**Issue by alpivett** [bcgov/SIMS#871]
@Hugh @Josh this is a very old ticket. I want to confirm that this is not a duplicate now or? 

**Additional Context**
- PD = Permanent Disability
- PPD = Persistent or Prolonged Disability (When performing assessments, treat this exactly the same as PD)
- Federal PPD legislation changes for Program Year 22/23 were implemented July 17
- Partner PPD status is out of scope (the question regarding partner permanent disability will not be expanded to include PPD)
- To reverify PPD status, students with PPD must attest that their PPD is still active on each application, through the single disability question
- PD/PPD status students only need 40% course load to qualify for full time application.
- PD/PPD status does not apply to Part Time applications.  IE, if the student has a part time application with 50% course load and is granted PD/PPD status, while their course load technically qualifies them for a full time application, it DOES NOT automatically change them to full time.  If they want full time, they would need to withdraw a part time application and start a new full time application.

**Acceptance Criteria**
- [ ] Add Request PPD Status 
- [ ] Student can request either PD or PPD Status (revisit buttons on account details)
- [ ] confirm text on question
- [ ] Revisit and confirm new interface requirements with ATBC
- [ ] Confirm reassessment when PD changes calculation
- [ ] Changes to PD/PPD status will trigger a reassessment for FULL TIME applications only. 

**Outstanding**
- Waiting for API specifications
- What happens if student with PPD statud and has a full time application with 50% course load.  What happens if they lose PPD status? 
- At what point in an application does PD/PPD status change no longer trigger reassessment of an application? After the last disbursement? End of study period? 
- Institutions already indicate course load intensity for Part Time offerings.  Why the need to verify PD/PPD status.

- School will determine if student is compliant with courseload requirements relating to PD/PPD when approving COE.

- With this work, I think you can have a better idea of how and what are going to be needed on your side. I also have some questions regarding the scope of what will be reported from this file (concretely about the change from PPD to PD) or if that change (or other you might need) are going to be reported by other means. I also want to know the default value for the date because currently SFAS is only for the day before, but not before that; so, it makes useless the date parameter, but we need to discuss the scope of this feature specially to get rid off many of the fields that are not used currently for the current use of the SFAS file.

**Comment by michesmith** [comment]
This is an old ticket and now a duplicate
