### ISSUE TITLE
UX Student Report a Change (after COE) 

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#882]
### Describe tasks
A student may want to change their application info (after COE):
- New child has been born
- New income, etc
- When a student doesn't like the outcome and wants to "appeal" (ADDED)

### Additional context
- Work along side DEVS (use reassessment analysis to inform mockups)
- Ministry analyze outside of system before accepting/denying change
- Students can click "EDIT APPLICATION" before COE but CAN'T after COE (this tix after COE)
- Therefore need to report a change somehow
- Which needs ministry decision (include notes for audit)

### Acceptance Criteria
- [x] Student -  mockup student reporting change
- [x] Institution - mockup institution reports change CLEANUP 
- [x] Ministry - mockup main navigation & summary view (pending applications needing decision)
- [x] Ministry - mockup inner navigation (a history of change / assessments / requests)
- [x] Ministry - mockup approving student changes (YES REASSESS / NO DO NOT REASSESS)
- [x] Ministry - mockup approving institution reported changes

**Comment by hellolynn-dsib** [comment]
### Lynn, Katrina, Signori, Schwenker tix feeds into each other (aka reassessments, students app detail status)

**Here is our workspace to evolve as we learn**
https://www.figma.com/file/5xPLQ5ocqOrtGJdKf0vZp2/SIMS-Workspace?node-id=0%3A1
