### ISSUE TITLE
UX Ministry Views / Approve Reassessments and Disbursements

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#893]
Assumptions:
1. Institution makes a change to study dates
2. Student is enrolled
3. Re-assessment needs to be done
4. Therefore Ministry user needs to approve reassessment and disbursement

- [ ] Wireframe indicates how this is shown on Ministry Views Student Account
- [ ] Notes section may be required for auditing phase

**Comment by IrenaMilosevic1** [comment]
Duplicate ticket #862
