### ISSUE TITLE
Ministry user Approve / Deny Education Program

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#894]
**Additional Context**
- Database changes are required

**Acceptance Criteria**
- As a ministry user when viewing PENDING program:
- [x] Should display "Approve" "Decline" buttons
- [x] Submitted date should populate
- [x] Approved date should populate
- [x] Declined date should populate
- [x] Effective End date should populate
- [x] We need to include approve by/declined by/submitted by
- As a ministry user when clicking APPROVE PENDING program:
- [x] Display Approve program" Modal
- [x] include Effective end date (this is for data collection purposes only, does not have any associated business rules)
- [x] Include Notes, free text up to 500 characters (confirm same length as other note components)
- [x] Notes should display under notes page with program filter working
- As a ministry user when clicking DENY PENDING program:
- [x] Include Notes, free text up to 500 characters (confirm same length as other note components)
- [x] Notes should display under notes page with program filter working

**Comment by IrenaMilosevic1** [comment]
Approved.
