### ISSUE TITLE
UX Accessibility Feedback - Plan to Move Forward

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#899]
- [x] Review Feedback from Jen
- [x] Meet with Jen / our QA team
- [x] Create a plan for how to tackle this feedback (eg. Tickets)

### Report from Jen (UX channel > Accessibility)
https://bcgov.sharepoint.com/:b:/t/03177/EaxxsbP6c3lGgbyh7feSXJcBrzQvkRgfN6Hjr5eNkvi0XA

### The plan

Tackle forms accessibility first
Tickets kicked-off

- #1076 UX Accessibility Design
- #318 UX Accessibility for Institution locations
- #593 UX Accessibility for Institution Details
- More to come in future

**Comment by hellolynn-dsib** [comment]
Lynn followed up with Jen. Likely end - mid feb delivery (absolute deadline Mar 31)

**Comment by hellolynn-dsib** [comment]
Jen to deliver report EOD March 1

**Comment by hellolynn-dsib** [comment]
Received March 2 - In UX CHANNEL under ACCESSIBILITY
