### ISSUE TITLE
Post MVP- Institution- Education Program and Study Period Offering Enhancements

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#901]
![image.png](https://images.zenhubusercontent.com/60c7d7040a42d68fb4abaa59/533ba35e-076c-4bfe-a136-f0c40bacbe26)
![image.png](https://images.zenhubusercontent.com/60c7d7040a42d68fb4abaa59/4777bb77-71b8-49f7-9b1c-89bcff4a703c)
![image.png](https://images.zenhubusercontent.com/60c7d7040a42d68fb4abaa59/5ef131b8-08a9-4ae1-a5d3-ad0c1b6a1468)
![image.png](https://images.zenhubusercontent.com/60c7d7040a42d68fb4abaa59/4f51d55c-eb19-418a-80cd-1bc287c4c74b)
![image.png](https://images.zenhubusercontent.com/60c7d7040a42d68fb4abaa59/5c70bd93-c294-422b-8978-15686bbc361e)

**Comment by HRAGANBC** [comment]
Tackled row by row:

1. (CIP) - forwarded to Jeremy for content
2. Already implemented
3. #2623 (now closed / implemented)
4. #967 (Post-Full Time)
5. Not pursuing, waste of time
6. Already implemented 
7. already implemented
8. Just question that was answered - no feature needed
9. Same as above. 
10. Same as above
11. (multiple bullets within this row)
- Aviation (implemented)
- Not enough context to understand the ask
- All remaining bullets nothing needed
