### ISSUE TITLE
Bulk Upload of Offering Details Part 1 of 2

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#910]
**Additional Context**
- This does NOT include programs
- template located in general -> analysis -> user story specifications
- Assume maximum of 1000 records
- This is a direct replacement of the institutional appendix (IA)

Important Technical Notes
- [x] Review formio performance and load testing of uploading and dryrun validations (dryrun loop of 100/1000/10000recods to test, parallel, not parallel, etc)
- [x] Review multiple formio pods load balancing correctly
- [x] service layer changes needed to provide formio payload to both controller and dryrun
- [x] Review moving validations to SIMS-API to increase performance

**Acceptance Criteria**
- [x] Determine mechanism for institutions to be able to bulk upload offering information
- [x] Add initial functionality for above solution (The data upload)
- [x] Starting point - Upload, save the data, provide initial data response, small ui for data upload processing, and performance testing, determine path to complete implantation

**- Process**
- [ ] Institutions admins will have a "Bulk Offering Upload" in bottom left name (like AEST reports)
- [ ] Institutions will upload a "CSV"
- [ ] This CSV will have EVERY piece of data on the offering AND the SABC program code and Institution location_code (AUGG)
- [ ] If ANY record fails, do not import any (This can be changed if a good implementation path is determined)
- [ ] When its submitted it will create all the offering in their correct status
- [ ] If an error occurs, the user must know what record had an error (record line number)

**Comment by andrewsignori-aot** [comment]
From some information gathered by @abschwenker from PROD, we are assuming:
- Institutions will be uploading no more than 3000 at one time.
- The sum of the total records uploaded over some weeks can be 60,000 considering all institutions for the period of one year.
- Executed some benchmarks considering 1, 2, and 3 form.io PODs, as shown below.
![image.png](https://images.zenhubusercontent.com/5fcebe3c076e6aaed83693fb/9d49ef25-03eb-41c0-a3e2-502d32a37cd5)

- For the 3 PODs scenario, we can consider around 35 validations executed per second for the provided offering sample.
- The validations can take longer depending on how the form.io definition will evolve.
- One POD was able to process around 256 parallel calls and then started to fail with "Gateway timeouts".
- Tow PODs were able to process 600 parallel calls and then started to fail with "Gateway timeouts".

**Comment by abschwenker** [comment]
analysis complete and branch on git
