### ISSUE TITLE
Ministry User Views  Programs and Study Period Offering Details 

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#917]
**Additional Context**
- This ticket does NOT require DB changes, DB changes will be a part of #894

**Acceptance Criteria**
- As a ministry user when viewing program summary:
- [x] Should display "No records found."   -Not a toast message
- [x] Update UI badge style in table
- [x] Review discrepancies with wireframe
- [x] Review pagination implementation
- As a ministry user when clicking "view" from program summary:
- [x] Create shared component for ministry and institution user program summary view (ministry user will have "view" buttons NOT "edit")
- [x] Update UI badges and date headers
- [x] Review discrepancies with wireframe
- As a ministry user when clicking "view" on the program summary program page PROGRAM:
- [x] display read-only view of program details page
- As a ministry user when clicking "view" on the program summary program page OFFERING:
- [x] `study period` in the offering summary should not include application specific offering? and the count should match the offering id inside?
- [x] display read-only view of offering details page
- [x] remove `locationName` from the route and take the name from API. (BUG - > EDIT OR CREATE offering  then click 'back all programs` from the view program page and location at the muted heading is undefined)
- [x] total offering count in summary include application specific offerings?

**Comment by IrenaMilosevic1** [comment]
Reviewed Dev. Looks very good. Thanks Ann
