### ISSUE TITLE
UX/ UI Second CoE 

### ISSUE THREAD

**Issue by alpivett** [bcgov/SIMS#918]
If a study period is under 18weeks after COE. If a Study Period is over 18 weeks -disbursement will happen twice and a second COE (financial control) is required. This is the last quality assurance required prior to the second disbursement.

- [ ] Couple COE with Disbursement Schedule? 1 COE for 1 Disbursement Schedule / 2 COE for 2 Disbursement Schedules
- [ ] COE is currently 21 days prior to the Study Period Offering start date. The second COE is? days prior to the second Disbursement.
 - [ ] 

**Acceptance Criteria**
- [ ] Analysis-  Gather Requirements (Lisa) and Blaine (Financial Lead)
- [ ] Update *Workflow as required 
- [ ] Update Wireframes as required

**Comment by abschwenker** [comment]
institutions should NOT be able to decline a 2nd COE, they should be doing a withdrawl? Alys to confirm
