### ISSUE TITLE
 UX/ UI Ministry User Views Parent / Partner Application Details 

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#937]
Related to ticket #100

Acceptance Criteria
- [ ] When a ministry user views a student application they MUST be able to see the:
- Student Application
- Attached Partner information (if present)
- Attached Parent(s) information (if present)

Additional context
- Keep the same practice for read-only forms (student, partner, parent 1, parent 2)

**Comment by dheepak-aot** [comment]
There is a known issue that when student application is loaded in read-only mode, the pre-selected value in drop downs like programs and offerings are displayed as number instead of description. There is an assumption that #357 should have fixed it. But it needs to be validated with this story.
