### ISSUE TITLE
Analysis- IDIM Response (BC Services Card) 

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#955]
**Acceptance Criteria**
Facilitate IDIM-AEST meetings to:
- [ ] Compile initial report of Business related issues
- [ ] Compile initial report of Technical related issues
- [ ] Reports should relate to each other (Business-Technical)
- [ ] Confirm list valid and accurate with Alys and Schwenker

**Additional Context**
Thanks all for your time today great discussion! Very helpful. I’ve captured some notes here with the intention that they are companion to the great table we reviewed as part of the meeting. Please share as appropriate (I feel like there’s a name missing from the CITZ team) and please let me know if I’ve misrepresented or missed anything critical. Also to inform those that weren’t able to join us. 

We talked about our stated intention to halt the attestation reliance as best we can – having a handle on what situations cannot be rectified any other way via these conversations and not having attestation as the default option so we can uncover any additional potential gotcha’s is the goal. I asked for us to have a solid understanding of those situations, who (BCSC or SABC) will be leading any ‘fix’, and what the alternate supports if any are no later than the end of January.

Note: Current wording that ServiceBC staff uses ‘please contact SABC to see if there is an alternative’ if BCSC is unable to rectify situation. 

The areas SABC frequently assists with are:
•	Students with Single Names (mononym or double mononym)
o	Initial discussion indicates that a mononym is often replicated in both last name and first name fields on BCSC
o	ICBC can support mononym but Health Insurance BC cannot (HIBC needs it in both fields and issues a non-photo BCSC with that – therefore they end up with a BCDL and a non-photo BCSC that do not match)
o	Marlowe’s thought – I believe we may be able to tackle this one via business rule in SIMS
•	Students with multiple first names (seems to be biggest volume)
o	May have potential to tackle SOME of these through communication/training of ICBC counter staff
o	WE find out either:
	Our account creation does not match BCSC, we coach them to change the account login
	Sometimes still caught at SIN check
	Sometimes school won’t confirm enrolment
	Last catch can be federal account mismatch
o	Marlowe’s thought – in our workflow would there be some way to flag for manual intervention? Need to understand in more detail how to identify.
•	Double last name (ie. hyphenated)
o	Per Jeremy P usually problematic only when also have multiple first name
•	Students whose name on BCSC does not match SIN or school record
o	Ie. married but did not change SIN record (takes 6-9 months)
o	Reissuance of BCSC with spelling mistakes could be 4-6 weeks but more often a couple of weeks
o	Marlowe’s thought – ties into communications to schools (post-sec AND K-12) and students in that we may be able to direct earlier and inform re SIN name mismatch potential
•	Two legal middle names
o	Health Insurance only allows one middle name (non-photo ID)
•	Student with two BC Services Card
o	Ie. Health Insurance with divorced parents
o	Workaround available via BCSC with agreement of student/parents to cancel/deactivate second card
	Better training on this particular scenario will help
•	Expired/Relinquished BC Services Card for out of province students
o	6-10 occurrences last week per Jeremy
o	Students have given up BCSC and/or BCDL after moving for education
o	Currently ‘guarantor’ attestation process
o	OOP users that don’t have MSP (non-MSP credential) currently out of luck but it is on the roadmap of the future 

Q for SIMS: 
•	Do we have system limitations for name length?
Jeremy’s situation of BCSC reissue (GUID mismatch) – currently a minor in-house workaround. Let’s talk this one through.

Communication for our applicants:
•	We need to ensure that our communications include strong recommendation for students and soon-to-be students to get their BCSC, review for correctness…

**Comment by abschwenker** [comment]
Passed Task to Anna - No longer required
