### ISSUE TITLE
Confirming SCOPE-System Content tasks

### ISSUE THREAD

**Issue by hellolynn-tbtb** [bcgov/SIMS#960]
** Question CONFIRM SCOPE is included in other tickets

## All users

These are system messages that the business does not need to be part of as these as "best practice" system messages.

- [ ] Review and write TOAST messages
- [ ] Review and write BANNER messages
- [x] Review and write ALT TAGS for images

## Supporting-Users

Tasks
- [ ] Polish UI design (for content designer)
- [ ] Revisit the words and where the fields are organization
- [ ] Revisit login page text
- [ ] Revisit home page text
- [ ] Polish parent partner form
- [ ] Additional context: mobile friendly, accessibility considerations

## Students
- [ ] Review and refine Notice of Assessment (NOA)

- Add earliest disbursement date
- Explain acronyms
- Add a state (0 values or not eligible)

- [ ] Application tracker 

- Submitted, in progress, assessment, enrolment, complete / #671

- Include outcome when a student reports a change
- Include outcome when a student updates a document

- [ ] Restrictions banner 

- SIN (how can students resolve if SIN fail?)
- Connect with Alana (FO)

- [ ] Email (out of app)
- [ ] Notifications (in NOTIFY)

## Institutions / Ministry

- [ ] Review messages for approve / decline requests
- Institution puts in request / Ministry reviews / Institution gets notified the result
- Program/offering changes
- Profile changes
- Location changes
**Acceptance Criteria**
- [ ] Update "Legal operating name" = Legal name
- [ ] Update "Institution name" = Operating name
- [ ] Update "Legal signing authority" = Legal authority

## Low priority
- [ ] Writing guide for SABC (based on BC Gov standards) 
- [x] Institutions vs Schools language
- [x] Restrictions vs hold language
- [x] Check spelling for British (e.g. enrolment)
- [x] Attribution for free images through Storyset ([helpful link](https://storyset.com/faqs))
- [ ] Rename "Student Financial Assistance Application" as an umbrella term for FT/PT applications?
- [ ] Change CSLP to CSFA (canada financial aid name change)
- [x] Review the the role title "Legal authorized authority" or "Legal signing authority" (inconsistencies in production and SME)
- [ ] Usability sessions (focusing on guided microcopy)

**Comment by michesmith** [comment]
This is an old ticket and has been covered else where
