### ISSUE TITLE
Document upload for dependants with PD

### ISSUE THREAD

**Issue by RobinDirks** [bcgov/SIMS#983]
As an applicant,
I want to upload proof of permanent disability for my dependants age 12 and older,
So that they can be included in the assessment process according to SABC policy.

**Additional Context**
- Dependents over 22 (or over 18 if not in postsecondary) with a PD can be included in the family size.
- Students with a PD dependant age 12 and older are also eligible for the CSG-FTDEP and/or CSG-PTDEP.
- Applicant must provide proof that the PD has been approved for federal or provincial disability assistance.

**Acceptance Criteria**
- [ ]If the student answers "Yes" to "Declared on taxes due to a disability" when adding a dependent, they will be prompted to upload supporting documents.

**Comment by abschwenker** [comment]
duplicate
