### ISSUE TITLE
FT/PT Application question for parent marital status

### ISSUE THREAD

**Issue by RobinDirks** [bcgov/SIMS#984]
**As an applicant** 
**I want to provide my parent(s) marital status**  **So That** the correct parent information is requested*

**Additional Context**
- This can replace the current question "How many parents do you live with?"

**Acceptance Criteria**
- [ ] When parent information is required, the following application question is included:
**My parent(s) marital status is:
- Single
- Married/Remarried
- Common-Law
- Seperated/Divorced/Widowed**

- [ ] Given (Single OR Seperated/Divorced/Widowed), When (application is submitted), Then (1 Parent Information Request is generated)
- [ ] Given (Married/Remarried OR Common-Law), When (application is submitted), Then (2 Parent Information Request are generated)

**Comment by abschwenker** [comment]
duplicate, see #758
