### ISSUE TITLE
UX Institution/Ministry Address Field 2

### ISSUE THREAD

**Issue by hellolynn-tbtb** [bcgov/SIMS#986]
**Describe the task**
Revisit "address 2" on institution side.

Currently the address labels say "address 1" and "address 2".

We are not collecting a "2nd address" for institutions. Is this field to capture suite/unit numbers? How does it show up in ministry view? Does the label need to be reworded? What are the technical impacts?

For example, if an institution address is this, what is best practice for displaying address fields:
#104 - 2345 Victoria Drive

**Acceptance Criteria**
- [ ] Revisit requirements for collecting institution address (do we need to collect a 2nd address or is it meant for suite/unit #'s)
- [ ] Design a mockup address field for Institutions / Ministry view
- [ ] Check with tech feasibility

**Additional context**
- Keep in mind reusing components (MVP)
- This impacts ministry summary views

**Comment by abschwenker** [comment]
already resolved
