### ISSUE TITLE
FT/PT Application field for additional transportation allowance

### ISSUE THREAD

**Issue by RobinDirks** [bcgov/SIMS#989]
**As an** *Applicant* **I want** *to provide the number of weeks that I have additional transportation costs* **So That** *I can get the right amount of transportation allowance*

**Additional Context**
- There is a maximum allowable weekly amount for transportation allowance of $94 based on 2021-2022 PY amounts. This maximum applies to both FT and PT assessments.
- PT already includes a default transportation allowance of $13 per week in the assessment.

**Acceptance Criteria**
- [ ] When applicant indicates that they require additional transportation funding and provide an estimate of their weekly transportation costs, applicant can then enter the number of weeks 
- [ ] Validate number of weeks against study period (should not exceed total number of funded weeks in the study period)
- [ ] Validation error if number of weeks exceeds study period
- [ ] Banner if validation error and student not able to submit application

Current test site:
![Test site.png](https://images.zenhubusercontent.com/61c390f5d34132a9b12ca101/e5ad2cbd-5b17-4211-9f91-fd85ca8c1ef0)

New mockup:
![transportation.JPG](https://images.zenhubusercontent.com/61c390f5d34132a9b12ca101/1a96ee30-acae-412d-93ca-6a8bd8a8eb02)

**Comment by abschwenker** [comment]
as per current calculations and #577, not currently required
