### ISSUE TITLE
Ministry Views uploaded student files

### ISSUE THREAD

**Issue by abschwenker** [bcgov/SIMS#994]
**Additional Context**
- Local pagination only, not DB
- Does NOT include files uploaded from the student applications
- Review behavior of viewing files (recommend in another tab)

**Acceptance Criteria**
- [x] As an ministry user, create "File Uploads" navigation on student main page (new tab)
- [x] Display a table of all the submitted files that were uploaded via the student file uploader. Columns include
- Document purpose
- Application #
- Date submitted
- File
- [x] When a ministry user clicks the file, they can view the file that was uploaded

**Comment by IrenaMilosevic1** [comment]
Approved
